# 1. Imports

In [1]:
import os
import weave
import wandb
import torch
import pandas as pd
import os.path as osp
import io
import base64
import re
import trl
import inspect
import time
import numpy as np
from openai import OpenAI
from transformers import AutoProcessor, Qwen2VLForConditionalGeneration
from models.mllm_wrappers import LLaVA, Qwen, Janus, Qwen3_5, Molmo
from peft import LoraConfig, get_peft_model
from configuration_template import Config
from bert_score import BERTScorer
from data_prep.data_utils import build_grid_image, build_patch_image_with_target_highlight
from trl import GRPOConfig, GRPOTrainer
from sentence_transformers import SentenceTransformer, util

/home/alesau/miniconda3/envs/mllm/lib/python3.14/site-packages/requests/__init__.py:113: RequestsDependencyWarning: urllib3 (2.6.3) or chardet (7.4.3)/charset_normalizer (3.4.6) doesn't match a supported version!
  warnings.warn(

In [2]:
os.environ["WANDB_API_KEY"] = "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"
wandb.login(key="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")

wandb: WARNING If you're specifying your api key in code, ensure this code is not shared publicly.
wandb: WARNING Consider setting the WANDB_API_KEY environment variable, or running `wandb login` from the command line.
wandb: [wandb.login()] Using explicit session credentials for https://api.wandb.ai.
wandb: Appending key for api.wandb.ai to your netrc file: /home/alesau/.netrc
wandb: Currently logged in as: alex-esau98 to https://api.wandb.ai. Use `wandb login --relogin` to force relogin

True

In [ ]:
#!pip install -U transformers accelerate datasets peft trl qwen-vl-utils wandb weave bitsandbytes
#!pip install wandb
#!pip install weave

:

:

# 2. Inits

### Patches

In [3]:


weave.init('alex-esau98/mllm')


wandb.init(
    entity="alex-esau98",
    project="mllm",
    config={
        "model": "Qwen/Qwen2-VL-2B-Instruct",
        "method": "GRPO",
        "reward": "judge_accuracy_plus_penalties"
    }
)

weave: weave version 0.53.11 is available!  To upgrade, please run:
weave:  $ pip install weave --upgrade
weave: Logged in as Weights & Biases user: alex-esau98.
weave: View Weave data at https://wandb.ai/alex-esau98/mllm/weave

wandb: Initializing weave.

In [4]:
config = Config(model="Qwen/Qwen2-VL-2B-Instruct")
config.input_type = 'simple'
config.task = 'patches'

img_kwargs = {
        "patch_size": config.patch_size,
        "patch_padding": config.patch_padding,
        "patch_pad_color": config.patch_pad_color,
    }

generate_kwargs = {
        "max_new_tokens": config.max_new_tokens,
        "do_sample": True,
        "temperature": 0.7,
        "top_p": 0.8,
        "top_k": 20,
        "min_p":0.0,
        "presence_penalty": 1.5,
        "repetition_penalty": 1.0,
    }

model_kwargs = {"cache_dir": config.model_cache_dir, "quant": config.quant}

Model = Qwen
model = Model(config.model_id, **model_kwargs)
print(f'Model: {model.__class__}')

model_version: Qwen2
model_type: Qwen
/home/alesau/mllm/mllm/PATH
building Qwen model...

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/729 [00:00<?, ?it/s]

Model: <class 'models.mllm_wrappers.Qwen'>

In [5]:
config_judge = Config(model="Qwen/Qwen3.5-4B")
config_judge.input_type = 'simple'
config_judge.task = 'patches'

img_kwargs_judge = {
        "patch_size": config.patch_size,
        "patch_padding": config.patch_padding,
        "grid_padding": config.grid_padding,
        "patch_pad_color": config.patch_pad_color,
        "grid_pad_color": config.grid_pad_color,
    }

generate_kwargs_judge = {
        "max_new_tokens": config_judge.max_new_tokens,
        "do_sample": True,
        "temperature": 1.0,
        "top_p": 0.85,
        "top_k": 20,
        "min_p":0.0,
        "presence_penalty": 1.5,
        "repetition_penalty": 1.0,
    }       

model_kwargs_judge = {"cache_dir": config_judge.model_cache_dir, "quant": config_judge.quant}

JudgeModel = Qwen3_5
judge_model = JudgeModel(config_judge.model_id, **model_kwargs_judge)
print(f'Judge Model: {judge_model.__class__}')

#judge_model = OpenAI(
#    api_key="EMPTY",
#    base_url="http://0.0.0.0:8080/v1",
#)

model_version: Qwen3.5
model_type: Qwen3_5
/home/alesau/mllm/mllm/PATH
building Qwen3_5 model...

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/723 [00:00<?, ?it/s]

Judge Model: <class 'models.mllm_wrappers.Qwen3_5'>

In [5]:

print(type(model))
print(model.__dict__.keys())
print(type(model.model))
print(type(model.processor))

print()
print(type(judge_model))
print(judge_model.__dict__.keys())
print(type(judge_model.model))
print(type(judge_model.processor))
print(judge_model.model_size)

<class 'models.mllm_wrappers.Qwen'>
dict_keys(['model', 'processor', 'model_id', 'model_size', 'quant', 'device'])
<class 'transformers.models.qwen2_vl.modeling_qwen2_vl.Qwen2VLForConditionalGeneration'>
<class 'transformers.models.qwen2_vl.processing_qwen2_vl.Qwen2VLProcessor'>

<class 'models.mllm_wrappers.Qwen3_5'>
dict_keys(['model', 'processor', 'model_id', 'model_size', 'quant', 'device'])
<class 'transformers.models.qwen3_5.modeling_qwen3_5.Qwen3_5ForConditionalGeneration'>
<class 'transformers.models.qwen3_vl.processing_qwen3_vl.Qwen3VLProcessor'>
4b

In [6]:


hf_model = model.model
processor = model.processor

lora_config = LoraConfig(
    r=16,
    lora_alpha=32,

    target_modules=[
        "q_proj",
        "k_proj",
        "v_proj",
        "o_proj"
    ],

    lora_dropout=0.05,
    task_type="CAUSAL_LM",
)

hf_model = get_peft_model(hf_model, lora_config)

hf_model.print_trainable_parameters()

trainable params: 4,358,144 || all params: 2,213,343,744 || trainable%: 0.1969

### Grids

In [3]:


weave.init('alex-esau98/mllm')


wandb.init(
    entity="alex-esau98",
    project="mllm",
    config={
        "model": "Qwen/Qwen2-VL-2B-Instruct",
        "method": "GRPO",
        "reward": "judge_accuracy_plus_penalties"
    }
)

weave: weave version 0.53.7 is available!  To upgrade, please run:
weave:  $ pip install weave --upgrade
weave: Logged in as Weights & Biases user: alex-esau98.
weave: View Weave data at https://wandb.ai/alex-esau98/mllm/weave

wandb: Initializing weave.

In [4]:
config = Config(model="Qwen/Qwen2-VL-2B-Instruct")
config.input_type = 'simple'
config.task = 'grid'

img_kwargs = {
        "patch_size": config.patch_size,
        "patch_padding": config.patch_padding,
        "grid_padding": config.grid_padding,
        "patch_pad_color": config.patch_pad_color,
        "grid_pad_color": config.grid_pad_color,
    }

generate_kwargs = {
        "max_new_tokens": config.max_new_tokens,
        "do_sample": True,
        "temperature": 0.8
    }

model_kwargs = {"cache_dir": config.model_cache_dir, "quant": config.quant}

Model = Qwen
model = Model(config.model_id, **model_kwargs)
print(f'Model: {model.__class__}')

model_version: Qwen2
model_type: Qwen
/home/alesau/mllm/mllm/PATH
building Qwen model...

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/729 [00:00<?, ?it/s]

Model: <class 'models.mllm_wrappers.Qwen'>

In [5]:
config_judge = Config(model="Qwen/Qwen3.5-9B")
config_judge.input_type = 'simple'
config_judge.task = 'grid'

img_kwargs_judge = {
        "patch_size": config.patch_size,
        "patch_padding": config.patch_padding,
        "grid_padding": config.grid_padding,
        "patch_pad_color": config.patch_pad_color,
        "grid_pad_color": config.grid_pad_color,
    }

generate_kwargs_judge = {
        "max_new_tokens": config_judge.max_new_tokens,
        "do_sample": True,
        "temperature": 0.8
    }       

model_kwargs_judge = {"cache_dir": config_judge.model_cache_dir, "quant": config_judge.quant}

#JudgeModel = Qwen3_5
#judge_model = JudgeModel(config_judge.model_id, **model_kwargs_judge)
#print(f'Judge Model: {judge_model.__class__}')

from openai import OpenAI

judge_model = OpenAI(
    api_key="EMPTY",
    base_url="http://0.0.0.0:8080/v1",
)

model_version: Qwen3.5
model_type: Qwen3_5
/home/alesau/mllm/mllm/PATH

In [7]:

print(type(model))
print(model.__dict__.keys())
print(type(model.model))
print(type(model.processor))

print()
print(type(judge_model))
print(judge_model.__dict__.keys())
print(type(judge_model.model))
print(type(judge_model.processor))
print(judge_model.model_size)

<class 'models.mllm_wrappers.Qwen'>
dict_keys(['model', 'processor', 'model_id', 'model_size', 'quant', 'device'])
<class 'transformers.models.qwen2_vl.modeling_qwen2_vl.Qwen2VLForConditionalGeneration'>
<class 'transformers.models.qwen2_vl.processing_qwen2_vl.Qwen2VLProcessor'>

<class 'models.mllm_wrappers.Qwen3_5'>
dict_keys(['model', 'processor', 'model_id', 'model_size', 'quant', 'device'])
<class 'transformers.models.qwen3_5.modeling_qwen3_5.Qwen3_5ForConditionalGeneration'>
<class 'transformers.models.qwen3_vl.processing_qwen3_vl.Qwen3VLProcessor'>
9b

In [6]:


hf_model = model.model
processor = model.processor

lora_config = LoraConfig(
    r=16,
    lora_alpha=32,

    target_modules=[
        "q_proj",
        "k_proj",
        "v_proj",
        "o_proj"
    ],

    lora_dropout=0.05,
    task_type="CAUSAL_LM",
)

hf_model = get_peft_model(hf_model, lora_config)

hf_model.print_trainable_parameters()

trainable params: 4,358,144 || all params: 2,213,343,744 || trainable%: 0.1969

# 3. Data Prep

### Patches

In [9]:
data_df = pd.read_json(osp.join(config.data_dir, "color_patch_data_far.json"))
print(len(data_df))
dataset_train = data_df.sample(frac=0.12665, random_state=1998)  # far = frac=0.12665; close=0.12865; split = 0.12735; general=0.04252
dataset_judge = data_df.drop(dataset_train.index)

print(len(dataset_train))
print(len(dataset_judge))
#data_df

#print(dataset_train)
print(f"Length of dataset_train: {len(dataset_train)}")
print(f"Share of split_condition: {len(dataset_train[dataset_train['condition'] == "split"]) / len(dataset_train)}")
print(f"Share of far_condition: {len(dataset_train[dataset_train['condition'] == "far"]) / len(dataset_train)}")
print(f"Share of close_condition: {len(dataset_train[dataset_train['condition'] == "close"]) / len(dataset_train)}")
#for i in range(70,80):
#    print(data_df["conversation"][i])

15791
2000
13791
Length of dataset_train: 2000
Share of split_condition: 0.0
Share of far_condition: 1.0
Share of close_condition: 0.0

### Grids

In [7]:

data_df = pd.read_json(osp.join(config.data_dir, "color_grid_data_far.json"))
print(len(data_df))
dataset_train = data_df.sample(frac=0.5502, random_state=42) ##grid = 0.55  patches = frac=0.12665
dataset_judge = data_df.drop(dataset_train.index)

print(len(dataset_train))
print(len(dataset_judge))
data_df

#for i in range(70,80):
#    print(data_df["conversation"][i])

3635
2000
1635

,gameid,game_idx,roundNum,round_id,condition,success,utterances,n_utterances,objs,target,speaker_order,listener_order,listener_clicked
0,4147-9d9582f2-28d0-431f-b6ba-35fd1be76619,1,1,4147-9d9582f2-28d0-431f-b6ba-35fd1be76619_1,FAR,True,"[[speaker, green top left corner, 1528144087280]]",1,"[{'shapes': [{'color': [322, 21, 50]}, {'color...",1,"[2, 1, 0]","[1, 0, 2]",0
1,4147-9d9582f2-28d0-431f-b6ba-35fd1be76619,1,4,4147-9d9582f2-28d0-431f-b6ba-35fd1be76619_4,FAR,True,"[[speaker, green in the middle square top row,...",1,"[{'shapes': [{'color': [294, 7, 50]}, {'color'...",0,"[1, 2, 0]","[2, 1, 0]",2
2,4147-9d9582f2-28d0-431f-b6ba-35fd1be76619,1,11,4147-9d9582f2-28d0-431f-b6ba-35fd1be76619_11,FAR,True,"[[speaker, bottom left not yellow not orange, ...",1,"[{'shapes': [{'color': [339, 87, 50]}, {'color...",1,"[1, 2, 0]","[0, 2, 1]",2
3,4147-9d9582f2-28d0-431f-b6ba-35fd1be76619,1,12,4147-9d9582f2-28d0-431f-b6ba-35fd1be76619_12,FAR,True,"[[speaker, top middle is grey, 1528144497114]]",1,"[{'shapes': [{'color': [199, 26, 50]}, {'color...",1,"[0, 1, 2]","[1, 0, 2]",0
4,4147-9d9582f2-28d0-431f-b6ba-35fd1be76619,1,15,4147-9d9582f2-28d0-431f-b6ba-35fd1be76619_15,FAR,True,"[[speaker, top right is green, 1528144581184]]",1,"[{'shapes': [{'color': [329, 14, 50]}, {'color...",2,"[2, 1, 0]","[2, 1, 0]",0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3630,6068-c8135454-2875-41d9-918c-60c34fc9460c,198,45,6068-c8135454-2875-41d9-918c-60c34fc9460c_45,FAR,True,"[[speaker, Center of middle row is green, cent...",1,"[{'shapes': [{'color': [345, 11, 50]}, {'color...",1,"[2, 0, 1]","[2, 0, 1]",2
3631,6068-c8135454-2875-41d9-918c-60c34fc9460c,198,47,6068-c8135454-2875-41d9-918c-60c34fc9460c_47,FAR,True,"[[speaker, middle tile and middle bottom are b...",1,"[{'shapes': [{'color': [354, 73, 50]}, {'color...",1,"[0, 2, 1]","[0, 1, 2]",1
3632,6068-c8135454-2875-41d9-918c-60c34fc9460c,198,52,6068-c8135454-2875-41d9-918c-60c34fc9460c_52,FAR,True,"[[speaker, top left green, 1526435104682]]",1,"[{'shapes': [{'color': [277, 19, 50]}, {'color...",1,"[2, 0, 1]","[1, 2, 0]",0
3633,6068-c8135454-2875-41d9-918c-60c34fc9460c,198,57,6068-c8135454-2875-41d9-918c-60c34fc9460c_57,FAR,True,"[[speaker, Top middle green, 1526435245005]]",1,"[{'shapes': [{'color': [195, 34, 50]}, {'color...",1,"[2, 1, 0]","[1, 2, 0]",0
3634,6068-c8135454-2875-41d9-918c-60c34fc9460c,198,58,6068-c8135454-2875-41d9-918c-60c34fc9460c_58,FAR,True,"[[speaker, middle right pink, 1526435266994]]",1,"[{'shapes': [{'color': [187, 64, 50]}, {'color...",2,"[0, 1, 2]","[2, 0, 1]",0

# 4. Methods and Dataset

### Patches

In [ ]:
####patches

scorer = BERTScorer(lang="en", rescale_with_baseline=True)

wandb.define_metric("reward/local_step")
wandb.define_metric("reward/*", step_metric="reward/local_step")

def build_prompt(target_position):
    return f"""
Describe the color patch {target_position} so that another model can identify it among three patches.

Rules:
- The other model does not see the patches in the same order as you do.
- Describe only visual properties.
- Mention hue, saturation, brightness, contrast, texture, etc. if useful.
"""

#- Keep it under 30 words.
#- Do not use left, middle, right, center.



def parse_position(text):
    text = text.lower().strip()

    if "left" in text:
        return "left"

    if "middle" in text or "center" in text:
        return "middle"

    if "right" in text:
        return "right"

    return "invalid"



@weave.op()
def judge_patch_from_description(image, description, judge_order):

    judge_prompt = f"""
You see an image with three color patches: left, middle, right.

A description says:
"{description}"

Which patch is described?

Answer only:
left, middle, or right.
"""

    # Hier dein Judge-VLM aufrufen
    img = build_patch_image_with_target_highlight(image, judge_order, **img_kwargs, highlight_target=False)
    #display(img)
    #print(f"Generated Description: {description}")
    answer = run_vlm_judge(img, judge_prompt)
    #print(f"Judge Answer: {answer}")
    #print("-" * 50)

    return  {
        "position": parse_position(answer),
        #"image": img
    }



def run_vlm_judge(image, prompt):
    # Hier rufst du dein Judge-VLM mit dem Bild und Prompt auf und bekommst die Antwort zurück
    # Zum Beispiel:
    # answer = judge_vlm.generate(image=image, prompt=prompt, **generate_kwargs)
    # return answer
    response = judge_model.generate(prompt, image, **generate_kwargs_judge)
    
    # buffer = io.BytesIO()
    # image.save(buffer, format="PNG")
    # img_base64 = base64.b64encode(buffer.getvalue()).decode("utf-8")

    # image_url = f"data:image/png;base64,{img_base64}"

    # response = judge_model.chat.completions.create(
    #     model="Qwen/Qwen3.6-27B-FP8",
    #     messages=[
    #         {
    #             "role": "user",
    #             "content": [
    #                 {
    #                     "type": "image_url",
    #                     "image_url": {
    #                         "url": image_url
    #                     }
    #                 },
    #                 {
    #                     "type": "text",
    #                     "text": prompt
    #                 },
    #             ],
    #         }
    #     ],
    #     temperature=1.0,
    #     top_p=0.95,
    #     presence_penalty=0.0,
    #     max_tokens=800,
    #     extra_body={
    #         "chat_template_kwargs": {
    #             "enable_thinking": False
    #         },
    #         "thinking_budget_tokens": 100,
    #     }
    # )

    # response = response.choices[0].message.content


    
    
    
    
    
    # Dummy-Implementierung für das Beispiel
    return response





def contains_position_words(text):

    forbidden = [
        "left",
        "middle",
        "right",
        "center",
        "centre",
    ]

    return any(w in text.lower() for w in forbidden)






@weave.op()
def compute_reward_bert(description, image, target_position, judge_order, og_description):
    global scorer

    reward = 0.0

    
    bert_weight = 0.5  # Gewichtung für den BERT-Score
    judge_weight = 1-bert_weight

    try:
        F1, _, _ = scorer.score([description], [og_description])


        torch.cuda.synchronize()  # Ensure all CUDA operations are complete before timing
        t0 = time.perf_counter()
        bert_reward = bert_weight * F1[0].item()
        

        torch.cuda.synchronize()  # Ensure all CUDA operations are complete before timing
        bert_time = time.perf_counter() - t0
    except Exception as e:
        print(f"Error computing BERT score: {e}")
        bert_reward = 0.0
        bert_time = 0.0

    reward += bert_reward  # F1-Score als Belohnung hinzufügen
        

    torch.cuda.synchronize()  # Ensure all CUDA operations are complete before timing
    t0 = time.perf_counter()
    result = judge_patch_from_description(
        image=image,
        description=description,
        judge_order=judge_order
    )

    torch.cuda.synchronize()  # Ensure all CUDA operations are complete before timing
    judge_time = time.perf_counter() - t0

    judge_prediction = result["position"]
    #img = result["image"]

    # Judge richtig?
    prediction_true = judge_prediction == target_position

    if prediction_true:
        judge_reward = 1.0* judge_weight
    else:
        judge_reward = -0.2* judge_weight
    reward += judge_reward

    # Cheating bestrafen
    #if contains_position_words(description):
    #    reward -= 0.5

    # Zu kurz
    word_count = len(description.split())

    # Zu lang
    #reward -= word_count * 0.015

    return {
        "reward": reward,
        "judge_prediction": judge_prediction,
        "word_count": word_count,
        "contains_position_words":
            contains_position_words(description),
        "image": img,
        "bert_reward": bert_reward,
        "judge_reward": judge_reward,
        "prediction_true": prediction_true,
        "bert_time": bert_time,
        "judge_time": judge_time
    }




all_rewards = []
sample_rewards_avg = []
judge_correct_avg = []
word_count_avg = []
contains_position_words_avg = []
reward_local_step = 0




def reward_func(completions, patches, rl_order, judge_order, og_description, **kwargs):
    global all_rewards
    global reward_local_step

    rewards = []
    #print(type(completions[0]))
    #print(completions[0])

    bert_time = 0.0
    judge_time = 0.0
    misc_time = 0.0

    reward_start = time.perf_counter()
    for desc, img, rl_ord, judge_ord, og_desc in zip(
        completions,
        patches,
        rl_order,
        judge_order,
        og_description
    ):
        misc_start = time.perf_counter()
        
        desc = desc[0]["content"]
        
        target_position = None
        if judge_ord[0] == 0:
            target_position = "left"
        elif judge_ord[1] == 0:
            target_position = "middle"
        elif judge_ord[2] == 0:
            target_position = "right"

        misc_time += time.perf_counter() - misc_start

        """result = compute_reward(
            description=desc,
            image=img,
            target_position=target_position,
            judge_order=judge_ord
        )"""

    

        result = compute_reward_bert(
            description=desc,
            image=img,
            target_position=target_position,
            judge_order=judge_ord,
            og_description=og_desc
        )

        bert_time += result["bert_time"]
        judge_time += result["judge_time"]

        rewards.append(result["reward"])

        reward_local_step += 1

        wandb.log({
            "reward/local_step": 
                reward_local_step,
                
            "reward/sample_reward":
                result["reward"],

            "reward/judge_correct":
                int(result["judge_prediction"] == target_position),

            "reward/word_count":
                result["word_count"],

            "reward/contains_position_words":
                int(result["contains_position_words"])
        })

    torch.cuda.synchronize()  # Ensure all CUDA operations are complete before timing
    reward_total = time.perf_counter() - reward_start

    print(
        f"\nReward total: {reward_total:.2f}s | "
        f"BERT: {bert_time:.2f}s | "
        f"Judge: {judge_time:.2f}s | "
        f"Misc: {misc_time:.2f}s"
    )

    all_rewards.append(rewards)
    return rewards

Loading weights:   0%|          | 0/389 [00:00<?, ?it/s]

[transformers] RobertaModel LOAD REPORT from: roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.dense.bias        | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.layer_norm.weight | UNEXPECTED |
pooler.dense.bias         | MISSING    |
pooler.dense.weight       | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [10]:
####patches batches

scorer = BERTScorer(lang="en", rescale_with_baseline=True)

wandb.define_metric("reward/local_step")
wandb.define_metric("reward/*", step_metric="reward/local_step")

def build_prompt(target_position):
    return f"""
Describe the color patch {target_position} so that another model can identify it among three patches.

Rules:
- The other model does not see the patches in the same order as you do.
- Describe only visual properties.
- Mention hue, saturation, brightness, contrast, texture, etc. if useful.
- Keep it under 30 words.
- Do not use left, middle, right, center.
"""

#- Keep it under 30 words.
#- Do not use left, middle, right, center.



def parse_position(text):
    text = text.lower().strip()

    if "left" in text:
        return "left"

    if "middle" in text or "center" in text:
        return "middle"

    if "right" in text:
        return "right"

    return "invalid"



@weave.op()
def judge_patch_from_description(image, description, judge_order):

    judge_prompt = f"""
You see an image with three color patches: left, middle, right.

A description says:
"{description}"

Which patch is described?

Answer only:
left, middle, or right.
"""

    # Hier dein Judge-VLM aufrufen
    img = build_patch_image_with_target_highlight(image, judge_order, **img_kwargs, highlight_target=False)
    #display(img)
    #print(f"Generated Description: {description}")
    answer = run_vlm_judge(img, judge_prompt)
    #print(f"Judge Answer: {answer}")
    #print("-" * 50)

    return  {
        "position": parse_position(answer),
        #"image": img
    }

def judge_patch_batch(
    images,
    descriptions,
    judge_orders,
    batch_size=4
):

    judge_images = []
    judge_prompts = []

    for image, description, judge_order in zip(
        images,
        descriptions,
        judge_orders
    ):

        prompt = f"""
        You see an image with three color patches: left, middle, right.

        A description says:
        "{description}"

        Which patch is described?

        Answer only:
        left, middle, or right.
        """

        img = build_patch_image_with_target_highlight(
            image,
            judge_order,
            **img_kwargs,
            highlight_target=False
        )

        judge_images.append(img)
        judge_prompts.append(prompt)

    predictions = []

    # Erstmal bewusst in kleinen GPU-Batches
    for start in range(0, len(judge_images), batch_size):

        end = start + batch_size

        answers = judge_model.generate_batch(
            prompts=judge_prompts[start:end],
            images=judge_images[start:end],

            max_new_tokens=5,
            do_sample=False,
        )

        predictions.extend(
            parse_position(answer)
            for answer in answers
        )

    return predictions



def run_vlm_judge(image, prompt):
    # Hier rufst du dein Judge-VLM mit dem Bild und Prompt auf und bekommst die Antwort zurück
    # Zum Beispiel:
    # answer = judge_vlm.generate(image=image, prompt=prompt, **generate_kwargs)
    # return answer
    response = judge_model.generate(prompt, image, **generate_kwargs_judge)
    
    # buffer = io.BytesIO()
    # image.save(buffer, format="PNG")
    # img_base64 = base64.b64encode(buffer.getvalue()).decode("utf-8")

    # image_url = f"data:image/png;base64,{img_base64}"

    # response = judge_model.chat.completions.create(
    #     model="Qwen/Qwen3.6-27B-FP8",
    #     messages=[
    #         {
    #             "role": "user",
    #             "content": [
    #                 {
    #                     "type": "image_url",
    #                     "image_url": {
    #                         "url": image_url
    #                     }
    #                 },
    #                 {
    #                     "type": "text",
    #                     "text": prompt
    #                 },
    #             ],
    #         }
    #     ],
    #     temperature=1.0,
    #     top_p=0.95,
    #     presence_penalty=0.0,
    #     max_tokens=800,
    #     extra_body={
    #         "chat_template_kwargs": {
    #             "enable_thinking": False
    #         },
    #         "thinking_budget_tokens": 100,
    #     }
    # )

    # response = response.choices[0].message.content


    
    
    
    
    
    # Dummy-Implementierung für das Beispiel
    return response





def contains_position_words(text):

    forbidden = [
        "left",
        "middle",
        "right",
        "center",
        "centre",
    ]

    return any(w in text.lower() for w in forbidden)






@weave.op()
def compute_reward_bert(description, image, target_position, judge_order, og_description):
    global scorer

    reward = 0.0

    
    bert_weight = 0.5  # Gewichtung für den BERT-Score
    judge_weight = 1-bert_weight

    try:
        F1, _, _ = scorer.score([description], [og_description])


        torch.cuda.synchronize()  # Ensure all CUDA operations are complete before timing
        t0 = time.perf_counter()
        bert_reward = bert_weight * F1[0].item()
        

        torch.cuda.synchronize()  # Ensure all CUDA operations are complete before timing
        bert_time = time.perf_counter() - t0
    except Exception as e:
        print(f"Error computing BERT score: {e}")
        bert_reward = 0.0
        bert_time = 0.0

    reward += bert_reward  # F1-Score als Belohnung hinzufügen
        

    torch.cuda.synchronize()  # Ensure all CUDA operations are complete before timing
    t0 = time.perf_counter()
    result = judge_patch_from_description(
        image=image,
        description=description,
        judge_order=judge_order
    )

    torch.cuda.synchronize()  # Ensure all CUDA operations are complete before timing
    judge_time = time.perf_counter() - t0

    judge_prediction = result["position"]
    #img = result["image"]

    # Judge richtig?
    prediction_true = judge_prediction == target_position

    if prediction_true:
        judge_reward = 1.0* judge_weight
    else:
        judge_reward = -0.2* judge_weight
    reward += judge_reward

    # Cheating bestrafen
    #if contains_position_words(description):
    #    reward -= 0.5

    # Zu kurz
    word_count = len(description.split())

    # Zu lang
    #reward -= word_count * 0.015

    return {
        "reward": reward,
        "judge_prediction": judge_prediction,
        "word_count": word_count,
        "contains_position_words":
            contains_position_words(description),
        "image": img,
        "bert_reward": bert_reward,
        "judge_reward": judge_reward,
        "prediction_true": prediction_true,
        "bert_time": bert_time,
        "judge_time": judge_time
    }




all_rewards = []
sample_rewards_avg = []
judge_correct_avg = []
word_count_avg = []
contains_position_words_avg = []
reward_local_step = 0



def reward_func(completions, patches, rl_order, judge_order, og_description, **kwargs):
    global all_rewards
    global reward_local_step

    descriptions = []
    target_positions = []

    for desc, judge_ord in zip(
        completions,
        judge_order
    ):

        desc = desc[0]["content"]

        descriptions.append(desc)

        if judge_ord[0] == 0:
            target_position = "left"

        elif judge_ord[1] == 0:
            target_position = "middle"

        elif judge_ord[2] == 0:
            target_position = "right"

        else:
            target_position = "invalid"

        target_positions.append(
            target_position
        )

    #judge_start = time.perf_counter()

    judge_predictions = judge_patch_batch(
        images=patches,
        descriptions=descriptions,
        judge_orders=judge_order,
        batch_size=8
    )

    #torch.cuda.synchronize()

    #judge_time = (
    #    time.perf_counter()
    #    - judge_start
    #)

    print("BEFORE BERT sync")
    torch.cuda.synchronize()
    print("BEFORE BERT sync OK")
    try:
        _, _, F1 = scorer.score(
            descriptions,
            list(og_description),
            batch_size=4
        )

    except Exception as e:
        print(f"Error computing BERT score: {e}")

        F1 = [0.0] * len(descriptions)

        for i in range(len(descriptions)):
            try:
                _, _, F1_i = scorer.score(
                    [descriptions[i]],
                    [og_description[i]]
                )

                F1[i] = float(F1_i[0])

            except Exception as e:
                print(
                    f"Error computing BERT score "
                    f"for description {i}: {e}"
                )

                F1[i] = 0.0

    print("AFTER BERT call")

    torch.cuda.synchronize()

    print("AFTER BERT sync OK")

    rewards = []

    bert_weight = 0
    judge_weight = 1

    prediction_correct_list =[]
    word_count_list = []
    contains_position_words_list = []
    bert_reward_list = []
    judge_reward_list = []
    for i in range(len(descriptions)):

        word_count = len(descriptions[i].split())
        word_count_list.append(word_count)

        contains_position_words_list.append(contains_position_words(descriptions[i]))

        bert_reward = bert_weight * float(F1[i])

        correct = (
            judge_predictions[i]
            == target_positions[i]
        )

        if correct:
            judge_reward = (
                1.0 * judge_weight
            )
            prediction_correct_list.append(1)
        else:
            judge_reward = (
                -0.2 * judge_weight
            )
            prediction_correct_list.append(0)

        bert_reward_list.append(bert_reward)
        judge_reward_list.append(judge_reward)
        
        reward = (
            bert_reward +
            judge_reward
        )

        rewards.append(reward)

    reward_local_step += 1

    wandb.log({
        "reward/local_step": 
            reward_local_step,
    
        "reward/sample_reward":
            np.mean(rewards),
    
        "reward/judge_correct":
            np.mean(prediction_correct_list),
    
        "reward/word_count":
            np.mean(word_count_list),
    
        "reward/contains_position_words":
            np.mean(contains_position_words_list)
    })

    for i in range(len(descriptions)):
        image = build_patch_image_with_target_highlight(patches[i], judge_order[i], **img_kwargs, highlight_target=False)
        log_params(
            description=descriptions[i],
            target_position=target_positions[i],
            speaker_order=rl_order[i],
            judge_order=judge_order[i],
            og_description=og_description[i],
            reward=rewards[i],
            judge_prediction=judge_predictions[i],
            word_count=word_count_list[i],
            img=image,
            bert_reward=bert_reward_list[i],
            judge_reward=judge_reward_list[i],
            prediction_true=bool(prediction_correct_list[i]))




    all_rewards.append(rewards)
    return rewards

@weave.op()
def log_params(description, target_position, speaker_order, judge_order, og_description, reward, judge_prediction, word_count, img, bert_reward, judge_reward, prediction_true):
    return



# def reward_func(completions, patches, rl_order, judge_order, og_description, **kwargs):
#     global all_rewards
#     global reward_local_step

#     rewards = []
#     #print(type(completions[0]))
#     #print(completions[0])

#     bert_time = 0.0
#     judge_time = 0.0
#     misc_time = 0.0

#     reward_start = time.perf_counter()
#     for desc, img, rl_ord, judge_ord, og_desc in zip(
#         completions,
#         patches,
#         rl_order,
#         judge_order,
#         og_description
#     ):
#         misc_start = time.perf_counter()
        
#         desc = desc[0]["content"]
        
#         target_position = None
#         if judge_ord[0] == 0:
#             target_position = "left"
#         elif judge_ord[1] == 0:
#             target_position = "middle"
#         elif judge_ord[2] == 0:
#             target_position = "right"

#         misc_time += time.perf_counter() - misc_start

#         """result = compute_reward(
#             description=desc,
#             image=img,
#             target_position=target_position,
#             judge_order=judge_ord
#         )"""

    

#         result = compute_reward_bert(
#             description=desc,
#             image=img,
#             target_position=target_position,
#             judge_order=judge_ord,
#             og_description=og_desc
#         )

#         bert_time += result["bert_time"]
#         judge_time += result["judge_time"]

#         rewards.append(result["reward"])

#         reward_local_step += 1

#         wandb.log({
#             "reward/local_step": 
#                 reward_local_step,
                
#             "reward/sample_reward":
#                 result["reward"],

#             "reward/judge_correct":
#                 int(result["judge_prediction"] == target_position),

#             "reward/word_count":
#                 result["word_count"],

#             "reward/contains_position_words":
#                 int(result["contains_position_words"])
#         })

#     torch.cuda.synchronize()  # Ensure all CUDA operations are complete before timing
#     reward_total = time.perf_counter() - reward_start

#     print(
#         f"\nReward total: {reward_total:.2f}s | "
#         f"BERT: {bert_time:.2f}s | "
#         f"Judge: {judge_time:.2f}s | "
#         f"Misc: {misc_time:.2f}s"
#     )

#     all_rewards.append(rewards)
#     return rewards

Loading weights:   0%|          | 0/389 [00:00<?, ?it/s]

[transformers] RobertaModel LOAD REPORT from: roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
lm_head.layer_norm.weight | UNEXPECTED |
pooler.dense.weight       | MISSING    |
pooler.dense.bias         | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [11]:
##patches

train_dataset = []
for i, entry in dataset_train.iterrows():
    #print(f"Entry {i}: {entry}")


    if entry.s_order_t_distr1_distr2[0] == 0:
        target_position = "on the left"
    elif entry.s_order_t_distr1_distr2[1] == 0:
        target_position = "in the middle"
    elif entry.s_order_t_distr1_distr2[2] == 0:
        target_position = "on the right"
    img = build_patch_image_with_target_highlight(entry.hls_values, entry.s_order_t_distr1_distr2, **img_kwargs, highlight_target=False)
    prompt = build_prompt(target_position)

    utterances = entry.conversation
    conversation = ""
    for utt in utterances:
        if conversation == "":
            conversation += f"{utt[1]}"
        else:
            conversation += f", {utt[1]}"
    conversation = re.sub(r"[^A-Za-zÄÖÜäöüß,\s]", "", conversation)
    

    
    #print(f"Prompt: {prompt}")
    #display(img)
    sample = {
        "prompt": [
            {
                "role": "user",
                "content": [
                    {
                        "type": "image", 
                        "image": img,
                    },
                    {
                        "type": "text",
                        "text": prompt
                    }
                ]
            }
        ],

        "patches": entry.hls_values,
        "rl_order": entry.s_order_t_distr1_distr2,
        "judge_order": entry.l_order_t_distr1_distr2,
        "og_description": conversation
    }
    train_dataset.append(sample)

train_dataset

[{'prompt': [{'role': 'user',
    'content': [{'type': 'image',
      'image': <PIL.Image.Image image mode=RGB size=330x110>},
     {'type': 'text',
      'text': '\nDescribe the color patch on the left so that another model can identify it among three patches.\n\nRules:\n- The other model does not see the patches in the same order as you do.\n- Describe only visual properties.\n- Mention hue, saturation, brightness, contrast, texture, etc. if useful.\n- Keep it under 30 words.\n- Do not use left, middle, right, center.\n'}]}],
  'patches': [[285, 50, 86], [219, 50, 48], [89, 50, 42]],
  'rl_order': [0, 1, 2],
  'judge_order': [0, 1, 2],
  'og_description': 'purple'},
 {'prompt': [{'role': 'user',
    'content': [{'type': 'image',
      'image': <PIL.Image.Image image mode=RGB size=330x110>},
     {'type': 'text',
      'text': '\nDescribe the color patch on the right so that another model can identify it among three patches.\n\nRules:\n- The other model does not see the patches in the same order as you do.\n- Describe only visual properties.\n- Mention hue, saturation, brightness, contrast, texture, etc. if useful.\n- Keep it under 30 words.\n- Do not use left, middle, right, center.\n'}]}],
  'patches': [[128, 50, 26], [317, 50, 35], [240, 50, 82]],
  'rl_order': [2, 1, 0],
  'judge_order': [2, 0, 1],
  'og_description': 'green'},
 {'prompt': [{'role': 'user',
    'content': [{'type': 'image',
      'image': <PIL.Image.Image image mode=RGB size=330x110>},
     {'type': 'text',
      'text': '\nDescribe the color patch in the middle so that another model can identify it among three patches.\n\nRules:\n- The other model does not see the patches in the same order as you do.\n- Describe only visual properties.\n- Mention hue, saturation, brightness, contrast, texture, etc. if useful.\n- Keep it under 30 words.\n- Do not use left, middle, right, center.\n'}]}],
  'patches': [[306, 50, 76], [252, 50, 14], [56, 50, 70]],
  'rl_order': [1, 0, 2],
  'judge_order': [2, 0, 1],
  'og_description': 'purple'},
 {'prompt': [{'role': 'user',
    'content': [{'type': 'image',
      'image': <PIL.Image.Image image mode=RGB size=330x110>},
     {'type': 'text',
      'text': '\nDescribe the color patch on the right so that another model can identify it among three patches.\n\nRules:\n- The other model does not see the patches in the same order as you do.\n- Describe only visual properties.\n- Mention hue, saturation, brightness, contrast, texture, etc. if useful.\n- Keep it under 30 words.\n- Do not use left, middle, right, center.\n'}]}],
  'patches': [[279, 50, 85], [90, 50, 61], [209, 50, 24]],
  'rl_order': [1, 2, 0],
  'judge_order': [0, 2, 1],
  'og_description': 'purple'},
 {'prompt': [{'role': 'user',
    'content': [{'type': 'image',
      'image': <PIL.Image.Image image mode=RGB size=330x110>},
     {'type': 'text',
      'text': '\nDescribe the color patch on the left so that another model can identify it among three patches.\n\nRules:\n- The other model does not see the patches in the same order as you do.\n- Describe only visual properties.\n- Mention hue, saturation, brightness, contrast, texture, etc. if useful.\n- Keep it under 30 words.\n- Do not use left, middle, right, center.\n'}]}],
  'patches': [[67, 50, 66], [175, 50, 16], [358, 50, 56]],
  'rl_order': [0, 1, 2],
  'judge_order': [1, 2, 0],
  'og_description': 'mustard yellow'},
 {'prompt': [{'role': 'user',
    'content': [{'type': 'image',
      'image': <PIL.Image.Image image mode=RGB size=330x110>},
     {'type': 'text',
      'text': '\nDescribe the color patch on the right so that another model can identify it among three patches.\n\nRules:\n- The other model does not see the patches in the same order as you do.\n- Describe only visual properties.\n- Mention hue, saturation, brightness, contrast, texture, etc. if useful.\n- Keep it under 30 words.\n- Do not use left, middle, right, center.\n'}]}],
  'patches': [[111, 50, 89], [300, 50, 88], [203, 50, 63]],
  'rl_order': [2, 1, 0],
  'judge_order': [0, 1, 2],
  'og_description': 'flor green'},
 {'prompt': [{'role': 'user',
    'content': [{'type': 'image',
      'image': <PIL.Image.Image image mode=RGB size=330x110>},
     {'type': 'text',
      'text': '\nDescribe the color patch in the middle so that another model can identify it among three patches.\n\nRules:\n- The other model does not see the patches in the same order as you do.\n- Describe only visual properties.\n- Mention hue, saturation, brightness, contrast, texture, etc. if useful.\n- Keep it under 30 words.\n- Do not use left, middle, right, center.\n'}]}],
  'patches': [[316, 50, 15], [175, 50, 89], [350, 50, 81]],
  'rl_order': [1, 0, 2],
  'judge_order': [2, 0, 1],
  'og_description': 'purple one'},
 {'prompt': [{'role': 'user',
    'content': [{'type': 'image',
      'image': <PIL.Image.Image image mode=RGB size=330x110>},
     {'type': 'text',
      'text': '\nDescribe the color patch on the right so that another model can identify it among three patches.\n\nRules:\n- The other model does not see the patches in the same order as you do.\n- Describe only visual properties.\n- Mention hue, saturation, brightness, contrast, texture, etc. if useful.\n- Keep it under 30 words.\n- Do not use left, middle, right, center.\n'}]}],
  'patches': [[50, 50, 82], [250, 50, 47], [355, 50, 91]],
  'rl_order': [1, 2, 0],
  'judge_order': [1, 2, 0],
  'og_description': 'yellow'},
 {'prompt': [{'role': 'user',
    'content': [{'type': 'image',
      'image': <PIL.Image.Image image mode=RGB size=330x110>},
     {'type': 'text',
      'text': '\nDescribe the color patch on the left so that another model can identify it among three patches.\n\nRules:\n- The other model does not see the patches in the same order as you do.\n- Describe only visual properties.\n- Mention hue, saturation, brightness, contrast, texture, etc. if useful.\n- Keep it under 30 words.\n- Do not use left, middle, right, center.\n'}]}],
  'patches': [[231, 50, 9], [135, 50, 75], [94, 50, 13]],
  'rl_order': [0, 2, 1],
  'judge_order': [1, 2, 0],
  'og_description': 'the target is gray'},
 {'prompt': [{'role': 'user',
    'content': [{'type': 'image',
      'image': <PIL.Image.Image image mode=RGB size=330x110>},
     {'type': 'text',
      'text': '\nDescribe the color patch on the right so that another model can identify it among three patches.\n\nRules:\n- The other model does not see the patches in the same order as you do.\n- Describe only visual properties.\n- Mention hue, saturation, brightness, contrast, texture, etc. if useful.\n- Keep it under 30 words.\n- Do not use left, middle, right, center.\n'}]}],
  'patches': [[31, 50, 72], [105, 50, 34], [321, 50, 12]],
  'rl_order': [1, 2, 0],
  'judge_order': [0, 2, 1],
  'og_description': 'orange'},
 {'prompt': [{'role': 'user',
    'content': [{'type': 'image',
      'image': <PIL.Image.Image image mode=RGB size=330x110>},
     {'type': 'text',
      'text': '\nDescribe the color patch on the left so that another model can identify it among three patches.\n\nRules:\n- The other model does not see the patches in the same order as you do.\n- Describe only visual properties.\n- Mention hue, saturation, brightness, contrast, texture, etc. if useful.\n- Keep it under 30 words.\n- Do not use left, middle, right, center.\n'}]}],
  'patches': [[141, 50, 91], [206, 50, 9], [334, 50, 28]],
  'rl_order': [0, 1, 2],
  'judge_order': [2, 0, 1],
  'og_description': 'green'},
 {'prompt': [{'role': 'user',
    'content': [{'type': 'image',
      'image': <PIL.Image.Image image mode=RGB size=330x110>},
     {'type': 'text',
      'text': '\nDescribe the color patch on the left so that another model can identify it among three patches.\n\nRules:\n- The other model does not see the patches in the same order as you do.\n- Describe only visual properties.\n- Mention hue, saturation, brightness, contrast, texture, etc. if useful.\n- Keep it under 30 words.\n- Do not use left, middle, right, center.\n'}]}],
  'patches': [[76, 50, 51], [199, 50, 72], [286, 50, 92]],
  'rl_order': [0, 2, 1],
  'judge_order': [0, 2, 1],
  'og_description': 'green'},
 {'prompt': [{'role': 'user',
    'content': [{'type': 'image',
      'image': <PIL.Image.Image image mode=RGB size=330x110>},
     {'type': 'text',
      'text': '\nDescribe the color patch on the right so that another model can identify it among three patches.\n\nRules:\n- The other model does not see the patches in the same order as you do.\n- Describe only visual properties.\n- Mention hue, saturation, brightness, contrast, texture, etc. if useful.\n- Keep it under 30 words.\n- Do not use left, middle, right, center.\n'}]}],
  'patches': [[54, 50, 83], [297, 50, 57], [100, 50, 62]],
  'rl_order': [1, 2, 0],
  'judge_order': [0, 1, 2],
  'og_description': 'yellow'},
 {'prompt': [{'role': 'user',
    'content': [{'type': 'image',
      'image': <PIL.Image.Image image mode=RGB size=330x110>},
     {'type': 'text',
      'text': '\nDescribe the color patch on the right so that another model can identify it among three patches.\n\nRules:\n- The other model does not see the patches in the same order as you do.\n- Describe only visual properties.\n- Mention hue, saturation, brightness, contrast, texture, etc. if useful.\n- Keep it under 30 words.\n- Do not use left, middle, right, center.\n'}]}],
  'patches': [[327, 50, 72], [103, 50, 38], [235, 50, 37]],
  'rl_order': [1, 2, 0],
  'judge_order': [1, 2, 0],
  'og_description': 'pink'},
 {'prompt': [{'role': 'user',
    'content': [{'type': 'image',
      'image': <PIL.Image.Image image mode=RGB size=330x110>},
     {'type': 'text',
      'text': '\nDescribe the color patch on the left so that another model can identify it among three patches.\n\nRules:\n- The other model does not see the patches in the same order as you do.\n- Describe only visual properties.\n- Mention hue, saturation, brightness, contrast, texture, etc. if useful.\n- Keep it under 30 words.\n- Do not use left, middle, right, center.\n'}]}],
  'patches': [[189, 50, 40], [90, 50, 93], [47, 50, 5]],
  'rl_order': [0, 2, 1],
  'judge_order': [0, 1, 2],
  'og_description': 'blue'},
 {'prompt': [{'role': 'user',
    'content': [{'type': 'image',
      'image': <PIL.Image.Image image mode=RGB size=330x110>},
     {'type': 'text',
      'text': '\nDescribe the color patch on the left so that another model can identify it among three patches.\n\nRules:\n- The other model does not see the patches in the same order as you do.\n- Describe only visual properties.\n- Mention hue, saturation, brightness, contrast, texture, etc. if useful.\n- Keep it under 30 words.\n- Do not use left, middle, right, center.\n'}]}],
  'patches': [[149, 50, 72], [118, 50, 13], [192, 50, 74]],
  'rl_order': [0, 1, 2],
  'judge_order': [1, 2, 0],
  'og_description': 'green'},
 {'prompt': [{'role': 'user',
    'content': [{'type': 'image',
      'image': <PIL.Image.Image image mode=RGB size=330x110>},
     {'type': 'text',
      'text': '\nDescribe the color patch on the right so that another model can identify it among three patches.\n\nRules:\n- The other model does not see the patches in the same order as you do.\n- Describe only visual properties.\n- Mention hue, saturation, brightness, contrast, texture, etc. if useful.\n- Keep it under 30 words.\n- Do not use left, middle, right, center.\n'}]}],
  'patches': [[252, 50, 62], [54, 50, 77], [32, 50, 2]],
  'rl_order': [2, 1, 0],
  'judge_order': [0, 1, 2],
  'og_description': 'blue'},
 {'prompt': [{'role': 'user',
    'content': [{'type': 'image',
      'image': <PIL.Image.Image image mode=RGB size=330x110>},
     {'type': 'text',
      'text': '\nDescribe the color patch in the middle so that another model can identify it among three patches.\n\nRules:\n- The other model does not see the patches in the same order as you do.\n- Describe only visual properties.\n- Mention hue, saturation, brightness, contrast, texture, etc. if useful.\n- Keep it under 30 words.\n- Do not use left, middle, right, center.\n'}]}],
  'patches': [[33, 50, 87], [50, 50, 6], [216, 50, 50]],
  'rl_order': [2, 0, 1],
  'judge_order': [2, 1, 0],
  'og_description': 'orange'},
 {'prompt': [{'role': 'user',
    'content': [{'type': 'image',
      'image': <PIL.Image.Image image mode=RGB size=330x110>},
     {'type': 'text',
      'text': '\nDescribe the color patch on the left so that another model can identify it among three patches.\n\nRules:\n- The other model does not see the patches in the same order as you do.\n- Describe only visual properties.\n- Mention hue, saturation, brightness, contrast, texture, etc. if useful.\n- Keep it under 30 words.\n- Do not use left, middle, right, center.\n'}]}],
  'patches': [[183, 50, 35], [315, 50, 16], [229, 50, 94]],
  'rl_order': [0, 1, 2],
  'judge_order': [0, 1, 2],
  'og_description': 'not bright blue'},
 {'prompt': [{'role': 'user',
    'content': [{'type': 'image',
      'image': <PIL.Image.Image image mode=RGB size=330x110>},
     {'type': 'text',
      'text': '\nDescribe the color patch on the left so that another model can identify it among three patches.\n\nRules:\n- The other model does not see the patches in the same order as you do.\n- Describe only visual properties.\n- Mention hue, saturation, brightness, contrast, texture, etc. if useful.\n- Keep it under 30 words.\n- Do not use left, middle, right, center.\n'}]}],
  'patches': [[128, 50, 4], [40, 50, 77], [210, 50, 81]],
  'rl_order': [0, 1, 2],
  'judge_order': [2, 1, 0],
  'og_description': 'grey'},
 {'prompt': [{'role': 'user',
    'content': [{'type': 'image',
      'image': <PIL.Image.Image image mode=RGB size=330x110>},
     {'type': 'text',
      'text': '\nDescribe the color patch in the middle so that another model can identify it among three patches.\n\nRules:\n- The other model does not see the patches in the same order as you do.\n- Describe only visual properties.\n- Mention hue, saturation, brightness, contrast, texture, etc. if useful.\n- Keep it under 30 words.\n- Do not use left, middle, right, center.\n'}]}],
  'patches': [[192, 50, 13], [346, 50, 89], [111, 50, 88]],
  'rl_order': [1, 0, 2],
  'judge_order': [2, 0, 1],
  'og_description': 'the gray box'},
 {'prompt': [{'role': 'user',
    'content': [{'type': 'image',
      'image': <PIL.Image.Image image mode=RGB size=330x110>},
     {'type': 'text',
      'text': '\nDescribe the color patch in the middle so that another model can identify it among three patches.\n\nRules:\n- The other model does not see the patches in the same order as you do.\n- Describe only visual properties.\n- Mention hue, saturation, brightness, contrast, texture, etc. if useful.\n- Keep it under 30 words.\n- Do not use left, middle, right, center.\n'}]}],
  'patches': [[296, 50, 9], [351, 50, 44], [215, 50, 75]],
  'rl_order': [2, 0, 1],
  'judge_order': [0, 1, 2],
  'og_description': 'grey'},
 {'prompt': [{'role': 'user',
    'content': [{'type': 'image',
      'image': <PIL.Image.Image image mode=RGB size=330x110>},
     {'type': 'text',
      'text': '\nDescribe the color patch on the left so that another model can identify it among three patches.\n\nRules:\n- The other model does not see the patches in the same order as you do.\n- Describe only visual properties.\n- Mention hue, saturation, brightness, contrast, texture, etc. if useful.\n- Keep it under 30 words.\n- Do not use left, middle, right, center.\n'}]}],
  'patches': [[46, 50, 46], [60, 50, 5], [60, 50, 87]],
  'rl_order': [0, 2, 1],
  'judge_order': [0, 2, 1],
  'og_description': 'tan'},
 {'prompt': [{'role': 'user',
    'content': [{'type': 'image',
      'image': <PIL.Image.Image image mode=RGB size=330x110>},
     {'type': 'text',
      'text': '\nDescribe the color patch in the middle so that another model can identify it among three patches.\n\nRules:\n- The other model does not see the patches in the same order as you do.\n- Describe only visual properties.\n- Mention hue, saturation, brightness, contrast, texture, etc. if useful.\n- Keep it under 30 words.\n- Do not use left, middle, right, center.\n'}]}],
  'patches': [[79, 50, 83], [37, 50, 20], [262, 50, 96]],
  'rl_order': [2, 0, 1],
  'judge_order': [2, 0, 1],
  'og_description': 'green'},
 {'prompt': [{'role': 'user',
    'content': [{'type': 'image',
      'image': <PIL.Image.Image image mode=RGB size=330x110>},
     {'type': 'text',
      'text': '\nDescribe the color patch on the right so that another model can identify it among three patches.\n\nRules:\n- The other model does not see the patches in the same order as you do.\n- Describe only visual properties.\n- Mention hue, saturation, brightness, contrast, texture, etc. if useful.\n- Keep it under 30 words.\n- Do not use left, middle, right, center.\n'}]}],
  'patches': [[261, 50, 88], [82, 50, 1], [305, 50, 75]],
  'rl_order': [2, 1, 0],
  'judge_order': [1, 2, 0],
  'og_description': 'water'},
 {'prompt': [{'role': 'user',
    'content': [{'type': 'image',
      'image': <PIL.Image.Image image mode=RGB size=330x110>},
     {'type': 'text',
      'text': '\nDescribe the color patch on the left so that another model can identify it among three patches.\n\nRules:\n- The other model does not see the patches in the same order as you do.\n- Describe only visual properties.\n- Mention hue, saturation, brightness, contrast, texture, etc. if useful.\n- Keep it under 30 words.\n- Do not use left, middle, right, center.\n'}]}],
  'patches': [[171, 50, 31], [125, 50, 64], [31, 50, 27]],
  'rl_order': [0, 2, 1],
  'judge_order': [1, 0, 2],
  'og_description': 'blue'},
 {'prompt': [{'role': 'user',
    'content': [{'type': 'image',
      'image': <PIL.Image.Image image mode=RGB size=330x110>},
     {'type': 'text',
      'text': '\nDescribe the color patch in the middle so that another model can identify it among three patches.\n\nRules:\n- The other model does not see the patches in the same order as you do.\n- Describe only visual properties.\n- Mention hue, saturation, brightness, contrast, texture, etc. if useful.\n- Keep it under 30 words.\n- Do not use left, middle, right, center.\n'}]}],
  'patches': [[101, 50, 15], [226, 50, 17], [349, 50, 98]],
  'rl_order': [2, 0, 1],
  'judge_order': [1, 2, 0],
  'og_description': 'grey'},
 {'prompt': [{'role': 'user',
    'content': [{'type': 'image',
      'image': <PIL.Image.Image image mode=RGB size=330x110>},
     {'type': 'text',
      'text': '\nDescribe the color patch on the left so that another model can identify it among three patches.\n\nRules:\n- The other model does not see the patches in the same order as you do.\n- Describe only visual properties.\n- Mention hue, saturation, brightness, contrast, texture, etc. if useful.\n- Keep it under 30 words.\n- Do not use left, middle, right, center.\n'}]}],
  'patches': [[211, 50, 9], [116, 50, 23], [323, 50, 59]],
  'rl_order': [0, 1, 2],
  'judge_order': [0, 1, 2],
  'og_description': 'grey'},
 {'prompt': [{'role': 'user',
    'content': [{'type': 'image',
      'image': <PIL.Image.Image image mode=RGB size=330x110>},
     {'type': 'text',
      'text': '\nDescribe the color patch on the right so that another model can identify it among three patches.\n\nRules:\n- The other model does not see the patches in the same order as you do.\n- Describe only visual properties.\n- Mention hue, saturation, brightness, contrast, texture, etc. if useful.\n- Keep it under 30 words.\n- Do not use left, middle, right, center.\n'}]}],
  'patches': [[23, 50, 17], [71, 50, 32], [224, 50, 82]],
  'rl_order': [1, 2, 0],
  'judge_order': [2, 0, 1],
  'og_description': 'RosePurple'},
 {'prompt': [{'role': 'user',
    'content': [{'type': 'image',
      'image': <PIL.Image.Image image mode=RGB size=330x110>},
     {'type': 'text',

In [15]:
print(judge_model.model.config._attn_implementation)

sdpa

### Grids

In [8]:
####grids

scorer = BERTScorer(lang="en", rescale_with_baseline=True)

wandb.define_metric("reward/local_step")
wandb.define_metric("reward/*", step_metric="reward/local_step")

def build_prompt(target_position):
    return f"""
Describe the color grid {target_position} so that another model can identify it among three grids.

Rules:

- You may use positional word to reference colors in the grid, but not to reference the grid itself among the three grids.
- Describe only visual properties.
- Mention hue, saturation, brightness, contrast, texture if useful.
- Keep it under 60 words.
"""



def parse_position(text):
    text = text.lower().strip()

    if "left" in text:
        return "left"

    if "middle" in text or "center" in text:
        return "middle"

    if "right" in text:
        return "right"

    return "invalid"



@weave.op()
def judge_grid_from_description(image, description, judge_order):

    judge_prompt = f"""
You see an image with three color grids: left, middle, right.

A description says:
"{description}"

Which grid is described?

Answer only:
left, middle, or right.
"""

    # Hier dein Judge-VLM aufrufen
    #print(f"Judge Order in judge_grid_method: {judge_order}")
    img = build_grid_image(image, judge_order, **img_kwargs)
    #display(img)
    #display(img)
    #print(f"Generated Description: {description}")
    answer = run_vlm_judge(img, judge_prompt)
    #print(f"Judge Answer: {answer}")
    #print("-" * 50)

    return  {
        "position": parse_position(answer),
        "image": img,
    }


# def run_vlm_judge(image, prompt):
#     # Hier rufst du dein Judge-VLM mit dem Bild und Prompt auf und bekommst die Antwort zurück
#     # Zum Beispiel:
#     # answer = judge_vlm.generate(image=image, prompt=prompt, **generate_kwargs)
#     # return answer
#     response = judge_model.generate(prompt, image, **generate_kwargs_judge)
#     # Dummy-Implementierung für das Beispiel
#     return response


def run_vlm_judge(image, prompt):
    # Hier rufst du dein Judge-VLM mit dem Bild und Prompt auf und bekommst die Antwort zurück
    # Zum Beispiel:
    # answer = judge_vlm.generate(image=image, prompt=prompt, **generate_kwargs)
    # return answer
    #response = judge_model.generate(prompt, image, **generate_kwargs_judge)
    
    buffer = io.BytesIO()
    image.save(buffer, format="PNG")
    img_base64 = base64.b64encode(buffer.getvalue()).decode("utf-8")

    image_url = f"data:image/png;base64,{img_base64}"

    response = judge_model.chat.completions.create(
        model="Qwen/Qwen3.8-27B-FP8",
        messages=[
            {
                "role": "user",
                "content": [
                    {
                        "type": "image_url",
                        "image_url": {
                            "url": image_url
                        }
                    },
                    {
                        "type": "text",
                        "text": prompt
                    },
                ],
            }
        ],
        #temperature=0.7,
        #max_tokens=800,
        extra_body={
            "chat_template_kwargs": {
                "enable_thinking": False
            },
            "thinking_budget_tokens": 40
        }
    )

    response = response.choices[0].message.content


    
    
    
    
    
    # Dummy-Implementierung für das Beispiel
    return response





def contains_position_words(text):

    forbidden = [
        "left",
        "middle",
        "right",
        "center",
        "centre",
    ]

    return any(w in text.lower() for w in forbidden)






@weave.op()
def compute_reward(description, image, target_position, judge_order):

    reward = 0.0

    judge_prediction = judge_grid_from_description(
        image=image,
        description=description,
        judge_order=judge_order
    )

    # Judge richtig?
    if judge_prediction == target_position:
        reward += 1.0
    else:
        reward -= 0.2

    # Cheating bestrafen
    #if contains_position_words(description):
    #    reward -= 0.5

    # Zu kurz
    word_count = len(description.split())

    # Zu lang
    #reward -= word_count * 0.015

    return {
        "reward": reward,
        "judge_prediction": judge_prediction,
        "word_count": word_count,
        "contains_position_words":
            contains_position_words(description)
    }






@weave.op()
def compute_reward_bert(description, image, target_position, judge_order, og_description):
    global scorer

    reward = 0.0

    F1, _, _ = scorer.score([description], [og_description])

    bert_weight = 0.5  # Gewichtung für den BERT-Score
    judge_weight = 1-bert_weight

    bert_reward = bert_weight * F1[0].item()
    reward += bert_reward  # F1-Score als Belohnung hinzufügen

    result = judge_grid_from_description(
        image=image,
        description=description,
        judge_order=judge_order
    )

    judge_prediction = result["position"]
    img = result["image"]

    


    # Judge richtig?
    prediction_true = judge_prediction == target_position

    if prediction_true:
        judge_reward = 1.0* judge_weight
    else:
        judge_reward = -0.2* judge_weight
    reward += judge_reward

    # Cheating bestrafen
    #if contains_position_words(description):
    #    reward -= 0.5

    # Zu kurz
    word_count = len(description.split())

    # Zu lang
    #reward -= word_count * 0.015

    return {
        "reward": reward,
        "judge_prediction": judge_prediction,
        "word_count": word_count,
        "contains_position_words":
            contains_position_words(description),
        "image": img,
        "bert_reward": bert_reward,
        "judge_reward": judge_reward,
        "prediction_true": prediction_true
    }




all_rewards = []
sample_rewards_avg = []
judge_correct_avg = []
word_count_avg = []
contains_position_words_avg = []
reward_local_step = 0




def reward_func(completions, grids, rl_order, judge_order, og_description, target, **kwargs):
    global all_rewards
    global reward_local_step

    rewards = []
    #print(type(completions[0]))
    #print(completions[0])
    for desc, img, rl_ord, judge_ord, og_desc, tgt in zip(
        completions,
        grids,
        rl_order,
        judge_order,
        og_description,
        target
    ):
        desc = desc[0]["content"]
        target_position = None
        if judge_ord[0] == tgt:
            target_position = "left"
        elif judge_ord[1] == tgt:
            target_position = "middle"
        elif judge_ord[2] == tgt:
            target_position = "right"



        """result = compute_reward(
            description=desc,
            image=img,
            target_position=target_position,
            judge_order=judge_ord
        )"""

        result = compute_reward_bert(
            description=desc,
            image=img,
            target_position=target_position,
            judge_order=judge_ord,
            og_description=og_desc
        )

        #display(result["image"])
        #print(f"OG Description: {og_desc}")
        #print(f"Description: {desc}")
        #print(f"Target: {target_position}")
        #print(f"RL Order: {rl_ord}")
        #print(f"Judge Order: {judge_ord}")
        #print(f"Judge Prediction: {result['judge_prediction']}")
        
        #print("___________________________________________________________________")

        rewards.append(result["reward"])

        reward_local_step += 1

        wandb.log({
            "reward/local_step": 
                reward_local_step,
                
            "reward/sample_reward":
                result["reward"],

            "reward/judge_correct":
                int(result["judge_prediction"] == target_position),

            "reward/word_count":
                result["word_count"],

            "reward/contains_position_words":
                int(result["contains_position_words"])
        })
    all_rewards.append(rewards)
    return rewards

Loading weights:   0%|          | 0/389 [00:00<?, ?it/s]

[transformers] RobertaModel LOAD REPORT from: roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
pooler.dense.bias         | MISSING    |
pooler.dense.weight       | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [9]:
##grids

train_dataset = []
for i, entry in dataset_train.iterrows():
    #print(f"Entry {i}: {entry}")



    target = entry.target
    if entry.speaker_order[0] == target:
        target_position = "on the left"
    elif entry.speaker_order[1] == target:
        target_position = "in the middle"
    elif entry.speaker_order[2] == target:
        target_position = "on the right"
    img = build_grid_image(entry.objs, entry.speaker_order, **img_kwargs)
    prompt = build_prompt(target_position)

    utterances = entry.utterances
    conversation = ""
    for utt in utterances:
        if conversation == "":
            conversation += f"{utt[1]}"
        else:
            conversation += f", {utt[1]}"
    conversation = re.sub(r"[^A-Za-zÄÖÜäöüß,\s]", "", conversation)
    

    
    #print(f"Prompt: {prompt}")
    #display(img)
    sample = {
        "prompt": [
            {
                "role": "user",
                "content": [
                    {
                        "type": "image", 
                        "image": img,
                    },
                    {
                        "type": "text",
                        "text": prompt
                    }
                ]
            }
        ],

        "grids": entry.objs,
        "rl_order": entry.speaker_order,
        "judge_order": entry.listener_order,
        "og_description": conversation,
        "target": target
    }
    train_dataset.append(sample)

train_dataset

[{'prompt': [{'role': 'user',
    'content': [{'type': 'image',
      'image': <PIL.Image.Image image mode=RGB size=1110x370>},
     {'type': 'text',
      'text': '\nDescribe the color grid in the middle so that another model can identify it among three grids.\n\nRules:\n\n- You may use positional word to reference colors in the grid, but not to reference the grid itself among the three grids.\n- Describe only visual properties.\n- Mention hue, saturation, brightness, contrast, texture if useful.\n- Keep it under 60 words.\n'}]}],
  'grids': [{'shapes': [{'color': [284, 23, 50]},
     {'color': [79, 20, 50]},
     {'color': [46, 44, 50]},
     {'color': [317, 3, 50]},
     {'color': [344, 27, 50]},
     {'color': [187, 28, 50]},
     {'color': [72, 71, 50]},
     {'color': [156, 93, 50]},
     {'color': [70, 77, 50]}],
    'gridDimension': 3,
    'cellLength': 40},
   {'shapes': [{'color': [212, 26, 50]},
     {'color': [271, 95, 50]},
     {'color': [237, 8, 50]},
     {'color': [82, 81, 50]},
     {'color': [220, 25, 50]},
     {'color': [328, 36, 50]},
     {'color': [282, 15, 50]},
     {'color': [15, 74, 50]},
     {'color': [113, 43, 50]}],
    'gridDimension': 3,
    'cellLength': 40},
   {'shapes': [{'color': [31, 96, 50]},
     {'color': [5, 43, 50]},
     {'color': [25, 48, 50]},
     {'color': [193, 41, 50]},
     {'color': [277, 78, 50]},
     {'color': [37, 98, 50]},
     {'color': [37, 63, 50]},
     {'color': [201, 8, 50]},
     {'color': [2, 18, 50]}],
    'gridDimension': 3,
    'cellLength': 40}],
  'rl_order': [2, 1, 0],
  'judge_order': [2, 0, 1],
  'og_description': 'true orange bottom center',
  'target': 1},
 {'prompt': [{'role': 'user',
    'content': [{'type': 'image',
      'image': <PIL.Image.Image image mode=RGB size=1110x370>},
     {'type': 'text',
      'text': '\nDescribe the color grid on the right so that another model can identify it among three grids.\n\nRules:\n\n- You may use positional word to reference colors in the grid, but not to reference the grid itself among the three grids.\n- Describe only visual properties.\n- Mention hue, saturation, brightness, contrast, texture if useful.\n- Keep it under 60 words.\n'}]}],
  'grids': [{'shapes': [{'color': [57, 43, 50]},
     {'color': [189, 23, 50]},
     {'color': [356, 95, 50]},
     {'color': [237, 33, 50]},
     {'color': [17, 48, 50]},
     {'color': [282, 22, 50]},
     {'color': [255, 90, 50]},
     {'color': [120, 5, 50]},
     {'color': [149, 40, 50]}],
    'gridDimension': 3,
    'cellLength': 40},
   {'shapes': [{'color': [208, 66, 50]},
     {'color': [189, 23, 50]},
     {'color': [48, 67, 50]},
     {'color': [237, 33, 50]},
     {'color': [17, 48, 50]},
     {'color': [160, 83, 50]},
     {'color': [255, 90, 50]},
     {'color': [203, 52, 50]},
     {'color': [149, 40, 50]}],
    'gridDimension': 3,
    'cellLength': 40},
   {'shapes': [{'color': [345, 3, 50]},
     {'color': [189, 23, 50]},
     {'color': [111, 83, 50]},
     {'color': [237, 33, 50]},
     {'color': [17, 48, 50]},
     {'color': [58, 75, 50]},
     {'color': [255, 90, 50]},
     {'color': [4, 64, 50]},
     {'color': [149, 40, 50]}],
    'gridDimension': 3,
    'cellLength': 40}],
  'rl_order': [2, 1, 0],
  'judge_order': [1, 0, 2],
  'og_description': 'Red in the top right ',
  'target': 0},
 {'prompt': [{'role': 'user',
    'content': [{'type': 'image',
      'image': <PIL.Image.Image image mode=RGB size=1110x370>},
     {'type': 'text',
      'text': '\nDescribe the color grid on the right so that another model can identify it among three grids.\n\nRules:\n\n- You may use positional word to reference colors in the grid, but not to reference the grid itself among the three grids.\n- Describe only visual properties.\n- Mention hue, saturation, brightness, contrast, texture if useful.\n- Keep it under 60 words.\n'}]}],
  'grids': [{'shapes': [{'color': [358, 85, 50]},
     {'color': [49, 84, 50]},
     {'color': [71, 79, 50]},
     {'color': [101, 67, 50]},
     {'color': [188, 77, 50]},
     {'color': [200, 72, 50]},
     {'color': [127, 39, 50]},
     {'color': [269, 33, 50]},
     {'color': [292, 20, 50]}],
    'gridDimension': 3,
    'cellLength': 40},
   {'shapes': [{'color': [208, 43, 50]},
     {'color': [99, 35, 50]},
     {'color': [303, 6, 50]},
     {'color': [243, 83, 50]},
     {'color': [246, 23, 50]},
     {'color': [21, 50, 50]},
     {'color': [279, 72, 50]},
     {'color': [138, 67, 50]},
     {'color': [193, 78, 50]}],
    'gridDimension': 3,
    'cellLength': 40},
   {'shapes': [{'color': [193, 85, 50]},
     {'color': [202, 80, 50]},
     {'color': [188, 19, 50]},
     {'color': [264, 1, 50]},
     {'color': [67, 2, 50]},
     {'color': [278, 76, 50]},
     {'color': [337, 12, 50]},
     {'color': [65, 10, 50]},
     {'color': [114, 80, 50]}],
    'gridDimension': 3,
    'cellLength': 40}],
  'rl_order': [2, 0, 1],
  'judge_order': [0, 2, 1],
  'og_description': 'Dark blue left side',
  'target': 1},
 {'prompt': [{'role': 'user',
    'content': [{'type': 'image',
      'image': <PIL.Image.Image image mode=RGB size=1110x370>},
     {'type': 'text',
      'text': '\nDescribe the color grid on the left so that another model can identify it among three grids.\n\nRules:\n\n- You may use positional word to reference colors in the grid, but not to reference the grid itself among the three grids.\n- Describe only visual properties.\n- Mention hue, saturation, brightness, contrast, texture if useful.\n- Keep it under 60 words.\n'}]}],
  'grids': [{'shapes': [{'color': [52, 50, 50]},
     {'color': [357, 82, 50]},
     {'color': [346, 62, 50]},
     {'color': [330, 43, 50]},
     {'color': [91, 50, 50]},
     {'color': [15, 33, 50]},
     {'color': [258, 98, 50]},
     {'color': [195, 88, 50]},
     {'color': [218, 62, 50]}],
    'gridDimension': 3,
    'cellLength': 40},
   {'shapes': [{'color': [113, 27, 50]},
     {'color': [153, 50, 50]},
     {'color': [53, 83, 50]},
     {'color': [21, 43, 50]},
     {'color': [296, 60, 50]},
     {'color': [204, 23, 50]},
     {'color': [312, 50, 50]},
     {'color': [339, 91, 50]},
     {'color': [1, 75, 50]}],
    'gridDimension': 3,
    'cellLength': 40},
   {'shapes': [{'color': [184, 40, 50]},
     {'color': [234, 7, 50]},
     {'color': [296, 54, 50]},
     {'color': [71, 7, 50]},
     {'color': [230, 47, 50]},
     {'color': [277, 97, 50]},
     {'color': [151, 27, 50]},
     {'color': [310, 92, 50]},
     {'color': [310, 94, 50]}],
    'gridDimension': 3,
    'cellLength': 40}],
  'rl_order': [1, 0, 2],
  'judge_order': [1, 0, 2],
  'og_description': 'Top left faded green Top middle green blue',
  'target': 1},
 {'prompt': [{'role': 'user',
    'content': [{'type': 'image',
      'image': <PIL.Image.Image image mode=RGB size=1110x370>},
     {'type': 'text',
      'text': '\nDescribe the color grid on the left so that another model can identify it among three grids.\n\nRules:\n\n- You may use positional word to reference colors in the grid, but not to reference the grid itself among the three grids.\n- Describe only visual properties.\n- Mention hue, saturation, brightness, contrast, texture if useful.\n- Keep it under 60 words.\n'}]}],
  'grids': [{'shapes': [{'color': [22, 94, 50]},
     {'color': [314, 16, 50]},
     {'color': [12, 5, 50]},
     {'color': [139, 57, 50]},
     {'color': [233, 53, 50]},
     {'color': [220, 9, 50]},
     {'color': [157, 60, 50]},
     {'color': [347, 7, 50]},
     {'color': [278, 49, 50]}],
    'gridDimension': 3,
    'cellLength': 40},
   {'shapes': [{'color': [118, 37, 50]},
     {'color': [314, 16, 50]},
     {'color': [12, 5, 50]},
     {'color': [139, 57, 50]},
     {'color': [233, 53, 50]},
     {'color': [220, 9, 50]},
     {'color': [157, 60, 50]},
     {'color': [347, 7, 50]},
     {'color': [278, 49, 50]}],
    'gridDimension': 3,
    'cellLength': 40},
   {'shapes': [{'color': [291, 26, 50]},
     {'color': [314, 16, 50]},
     {'color': [12, 5, 50]},
     {'color': [139, 57, 50]},
     {'color': [233, 53, 50]},
     {'color': [220, 9, 50]},
     {'color': [157, 60, 50]},
     {'color': [347, 7, 50]},
     {'color': [278, 49, 50]}],
    'gridDimension': 3,
    'cellLength': 40}],
  'rl_order': [2, 0, 1],
  'judge_order': [0, 2, 1],
  'og_description': ' purple',
  'target': 2},
 {'prompt': [{'role': 'user',
    'content': [{'type': 'image',
      'image': <PIL.Image.Image image mode=RGB size=1110x370>},
     {'type': 'text',
      'text': '\nDescribe the color grid on the right so that another model can identify it among three grids.\n\nRules:\n\n- You may use positional word to reference colors in the grid, but not to reference the grid itself among the three grids.\n- Describe only visual properties.\n- Mention hue, saturation, brightness, contrast, texture if useful.\n- Keep it under 60 words.\n'}]}],
  'grids': [{'shapes': [{'color': [332, 56, 50]},
     {'color': [260, 28, 50]},
     {'color': [153, 78, 50]},
     {'color': [119, 42, 50]},
     {'color': [223, 11, 50]},
     {'color': [103, 24, 50]},
     {'color': [219, 14, 50]},
     {'color': [144, 31, 50]},
     {'color': [335, 21, 50]}],
    'gridDimension': 3,
    'cellLength': 40},
   {'shapes': [{'color': [247, 32, 50]},
     {'color': [69, 94, 50]},
     {'color': [249, 37, 50]},
     {'color': [24, 89, 50]},
     {'color': [62, 91, 50]},
     {'color': [310, 46, 50]},
     {'color': [65, 30, 50]},
     {'color': [29, 78, 50]},
     {'color': [251, 69, 50]}],
    'gridDimension': 3,
    'cellLength': 40},
   {'shapes': [{'color': [161, 88, 50]},
     {'color': [34, 35, 50]},
     {'color': [338, 23, 50]},
     {'color': [225, 7, 50]},
     {'color': [236, 48, 50]},
     {'color': [15, 87, 50]},
     {'color': [280, 51, 50]},
     {'color': [333, 32, 50]},
     {'color': [310, 0, 50]}],
    'gridDimension': 3,
    'cellLength': 40}],
  'rl_order': [2, 1, 0],
  'judge_order': [0, 2, 1],
  'og_description': 'top rigght a greenteal color and top left is pinkish',
  'target': 0},
 {'prompt': [{'role': 'user',
    'content': [{'type': 'image',
      'image': <PIL.Image.Image image mode=RGB size=1110x370>},
     {'type': 'text',
      'text': '\nDescribe the color grid in the middle so that another model can identify it among three grids.\n\nRules:\n\n- You may use positional word to reference colors in the grid, but not to reference the grid itself among the three grids.\n- Describe only visual properties.\n- Mention hue, saturation, brightness, contrast, texture if useful.\n- Keep it under 60 words.\n'}]}],
  'grids': [{'shapes': [{'color': [344, 51, 50]},
     {'color': [250, 85, 50]},
     {'color': [353, 5, 50]},
     {'color': [268, 85, 50]},
     {'color': [101, 96, 50]},
     {'color': [73, 79, 50]},
     {'color': [335, 97, 50]},
     {'color': [343, 92, 50]},
     {'color': [51, 12, 50]}],
    'gridDimension': 3,
    'cellLength': 40},
   {'shapes': [{'color': [344, 51, 50]},
     {'color': [250, 85, 50]},
     {'color': [353, 5, 50]},
     {'color': [268, 85, 50]},
     {'color': [101, 96, 50]},
     {'color': [176, 7, 50]},
     {'color': [335, 97, 50]},
     {'color': [180, 84, 50]},
     {'color': [225, 34, 50]}],
    'gridDimension': 3,
    'cellLength': 40},
   {'shapes': [{'color': [344, 51, 50]},
     {'color': [250, 85, 50]},
     {'color': [353, 5, 50]},
     {'color': [268, 85, 50]},
     {'color': [101, 96, 50]},
     {'color': [136, 46, 50]},
     {'color': [335, 97, 50]},
     {'color': [290, 15, 50]},
     {'color': [265, 92, 50]}],
    'gridDimension': 3,
    'cellLength': 40}],
  'rl_order': [0, 1, 2],
  'judge_order': [1, 0, 2],
  'og_description': 'bottom row are has  pinks',
  'target': 1},
 {'prompt': [{'role': 'user',
    'content': [{'type': 'image',
      'image': <PIL.Image.Image image mode=RGB size=1110x370>},
     {'type': 'text',
      'text': '\nDescribe the color grid in the middle so that another model can identify it among three grids.\n\nRules:\n\n- You may use positional word to reference colors in the grid, but not to reference the grid itself among the three grids.\n- Describe only visual properties.\n- Mention hue, saturation, brightness, contrast, texture if useful.\n- Keep it under 60 words.\n'}]}],
  'grids': [{'shapes': [{'color': [88, 21, 50]},
     {'color': [103, 61, 50]},
     {'color': [75, 39, 50]},
     {'color': [87, 27, 50]},
     {'color': [197, 1, 50]},
     {'color': [242, 66, 50]},
     {'color': [311, 47, 50]},
     {'color': [50, 47, 50]},
     {'color': [251, 66, 50]}],
    'gridDimension': 3,
    'cellLength': 40},
   {'shapes': [{'color': [88, 21, 50]},
     {'color': [103, 61, 50]},
     {'color': [75, 39, 50]},
     {'color': [87, 27, 50]},
     {'color': [16, 93, 50]},
     {'color': [242, 66, 50]},
     {'color': [311, 47, 50]},
     {'color': [292, 54, 50]},
     {'color': [196, 82, 50]}],
    'gridDimension': 3,
    'cellLength': 40},
   {'shapes': [{'color': [88, 21, 50]},
     {'color': [103, 61, 50]},
     {'color': [75, 39, 50]},
     {'color': [87, 27, 50]},
     {'color': [338, 82, 50]},
     {'color': [242, 66, 50]},
     {'color': [311, 47, 50]},
     {'color': [116, 89, 50]},
     {'color': [45, 29, 50]}],
    'gridDimension': 3,
    'cellLength': 40}],
  'rl_order': [1, 0, 2],
  'judge_order': [0, 2, 1],
  'og_description': 'middle box is gray',
  'target': 0},
 {'prompt': [{'role': 'user',
    'content': [{'type': 'image',
      'image': <PIL.Image.Image image mode=RGB size=1110x370>},
     {'type': 'text',
      'text': '\nDescribe the color grid on the left so that another model can identify it among three grids.\n\nRules:\n\n- You may use positional word to reference colors in the grid, but not to reference the grid itself among the three grids.\n- Describe only visual properties.\n- Mention hue, saturation, brightness, contrast, texture if useful.\n- Keep it under 60 words.\n'}]}],
  'grids': [{'shapes': [{'color': [328, 48, 50]},
     {'color': [43, 59, 50]},
     {'color': [334, 57, 50]},
     {'color': [89, 28, 50]},
     {'color': [222, 90, 50]},
     {'color': [224, 0, 50]},
     {'color': [184, 25, 50]},
     {'color': [81, 42, 50]},
     {'color': [272, 28, 50]}],
    'gridDimension': 3,
    'cellLength': 40},
   {'shapes': [{'color': [53, 97, 50]},
     {'color': [277, 93, 50]},
     {'color': [144, 99, 50]},
     {'color': [230, 31, 50]},
     {'color': [166, 38, 50]},
     {'color': [77, 43, 50]},
     {'color': [10, 37, 50]},
     {'color': [268, 80, 50]},
     {'color': [248, 79, 50]}],
    'gridDimension': 3,
    'cellLength': 40},
   {'shapes': [{'color': [27, 77, 50]},
     {'color': [358, 33, 50]},
     {'color': [46, 43, 50]},
     {'color': [104, 97, 50]},
     {'color': [328, 19, 50]},
     {'color': [303, 56, 50]},
     {'color': [105, 65, 50]},
     {'color': [309, 3, 50]},
     {'color': [61, 68, 50]}],
    'gridDimension': 3,
    'cellLength': 40}],
  'rl_order': [0, 2, 1],
  'judge_order': [0, 2, 1],
  'og_description': 'pink left top ',
  'target': 0},
 {'prompt': [{'role': 'user',
    'content': [{'type': 'image',
      'image': <PIL.Image.Image image mode=RGB size=1110x370>},
     {'type': 'text',
      'text': '\nDescribe the color grid on the right so that another model can identify it among three grids.\n\nRules:\n\n- You may use positional word to reference colors in the grid, but not to reference the grid itself among the three grids.\n- Describe only visual properties.\n- Mention hue, saturation, brightness, contrast, texture if useful.\n- Keep it under 60 words.\n'}]}],
  'grids': [{'shapes': [{'color': [207, 92, 50]},
     {'color': [108, 78, 50]},
     {'color': [33, 60, 50]},
     {'color': [136, 27, 50]},
     {'color': [66, 41, 50]},
     {'color': [86, 44, 50]},
     {'color': [159, 98, 50]},
     {'color': [201, 80, 50]},
     {'color': [246, 9, 50]}],
    'gridDimension': 3,
    'cellLength': 40},
   {'shapes': [{'color': [250, 9, 50]},
     {'color': [190, 14, 50]},
     {'color': [207, 92, 50]},
     {'color': [203, 41, 50]},
     {'color': [278, 19, 50]},
     {'color': [30, 42, 50]},
     {'color': [298, 11, 50]},
     {'color': [128, 39, 50]},
     {'color': [58, 29, 50]}],
    'gridDimension': 3,
    'cellLength': 40},
   {'shapes': [{'color': [243, 68, 50]},
     {'color': [241, 96, 50]},
     {'color': [255, 2, 50]},
     {'color': [346, 81, 50]},
     {'color': [168, 78, 50]},
     {'color': [222, 25, 50]},
     {'color': [108, 6, 50]},
     {'color': [57, 43, 50]},
     {'color': [277, 52, 50]}],
    'gridDimension': 3,
    'cellLength': 40}],
  'rl_order': [0, 2, 1],
  'judge_order': [1, 2, 0],
  'og_description': 'dark purple center',
  'target': 1},
 {'prompt': [{'role': 'user',
    'content': [{'type': 'image',
      'image': <PIL.Image.Image image mode=RGB size=1110x370>},
     {'type': 'text',
      'text': '\nDescribe the color grid on the left so that another model can identify it among three grids.\n\nRules:\n\n- You may use positional word to reference colors in the grid, but not to reference the grid itself among the three grids.\n- Describe only visual properties.\n- Mention hue, saturation, brightness, contrast, texture if useful.\n- Keep it under 60 words.\n'}]}],
  'grids': [{'shapes': [{'color': [174, 44, 50]},
     {'color': [114, 74, 50]},
     {'color': [89, 12, 50]},
     {'color': [242, 3, 50]},
     {'color': [282, 29, 50]},
     {'color': [95, 76, 50]},
     {'color': [163, 51, 50]},
     {'color': [140, 39, 50]},
     {'color': [203, 50, 50]}],
    'gridDimension': 3,
    'cellLength': 40},
   {'shapes': [{'color': [174, 44, 50]},
     {'color': [114, 74, 50]},
     {'color': [89, 12, 50]},
     {'color': [242, 3, 50]},
     {'color': [282, 29, 50]},
     {'color': [95, 76, 50]},
     {'color': [163, 51, 50]},
     {'color': [140, 39, 50]},
     {'color': [100, 19, 50]}],
    'gridDimension': 3,
    'cellLength': 40},
   {'shapes': [{'color': [174, 44, 50]},
     {'color': [114, 74, 50]},
     {'color': [89, 12, 50]},
     {'color': [242, 3, 50]},
     {'color': [282, 29, 50]},
     {'color': [95, 76, 50]},
     {'color': [163, 51, 50]},
     {'color': [140, 39, 50]},
     {'color': [303, 20, 50]}],
    'gridDimension': 3,
    'cellLength': 40}],
  'rl_order': [2, 1, 0],
  'judge_order': [0, 2, 1],
  'og_description': 'Bottom right purple',
  'target': 2},
 {'prompt': [{'role': 'user',
    'content': [{'type': 'image',
      'image': <PIL.Image.Image image mode=RGB size=1110x370>},
     {'type': 'text',
      'text': '\nDescribe the color grid on the right so that another model can identify it among three grids.\n\nRules:\n\n- You may use positional word to reference colors in the grid, but not to reference the grid itself among the three grids.\n- Describe only visual properties.\n- Mention hue, saturation, brightness, contrast, texture if useful.\n- Keep it under 60 words.\n'}]}],
  'grids': [{'shapes': [{'color': [262, 77, 50]},
     {'color': [102, 74, 50]},
     {'color': [326, 84, 50]},
     {'color': [112, 56, 50]},
     {'color': [357, 29, 50]},
     {'color': [181, 19, 50]},
     {'color': [86, 6, 50]},
     {'color': [180, 56, 50]},
     {'color': [350, 42, 50]}],
    'gridDimension': 3,
    'cellLength': 40},
   {'shapes': [{'color': [214, 33, 50]},
     {'color': [310, 11, 50]},
     {'color': [310, 3, 50]},
     {'color': [226, 33, 50]},
     {'color': [204, 80, 50]},
     {'color': [294, 36, 50]},
     {'color': [21, 39, 50]},
     {'color': [118, 59, 50]},
     {'color': [145, 50, 50]}],
    'gridDimension': 3,
    'cellLength': 40},
   {'shapes': [{'color': [114, 99, 50]},
     {'color': [202, 25, 50]},
     {'color': [66, 44, 50]},
     {'color': [82, 4, 50]},
     {'color': [124, 66, 50]},
     {'color': [219, 50, 50]},
     {'color': [215, 30, 50]},
     {'color': [232, 28, 50]},
     {'color': [211, 5, 50]}],
    'gridDimension': 3,
    'cellLength': 40}],
  'rl_order': [0, 2, 1],
  'judge_order': [0, 2, 1],
  'og_description': 'bottom middle square green',
  'target': 1},

# 5. Training

In [ ]:


training_args = GRPOConfig(

    output_dir="./qwen2vl_patch_grpo",

    report_to="wandb",

    logging_steps=1,

    learning_rate=1e-6,

    per_device_train_batch_size=4,

    gradient_accumulation_steps=2,

    num_generations=8,

    max_completion_length=80,

    num_train_epochs=1,

    bf16=True,

    save_steps=200,

    gradient_checkpointing=False,
)

In [13]:
class TimedGRPOTrainer(GRPOTrainer):

    def _generate_and_score_completions(self, inputs):

        t0 = time.perf_counter()

        result = super()._generate_and_score_completions(inputs)

        t1 = time.perf_counter()

        #print(
        #    f"Generate + Reward + Scoring: "
        #    f"{t1 - t0:.2f}s"
        #)

        return result

trainer = TimedGRPOTrainer(
    model=hf_model,
    args=training_args,
    train_dataset=train_dataset,
    reward_funcs=reward_func,
    processing_class=processor,
)


trainer.train()
wandb.finish()
weave.finish

[transformers] The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'eos_token_id': 151645, 'bos_token_id': None, 'pad_token_id': 151643}.
[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

/home/alesau/miniconda3/envs/mllm/lib/python3.14/site-packages/bert_score/scorer.py:139: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  self._baseline_vals = torch.from_numpy(
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15e-0628-7ba5-8564-bd29c4414a59
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15e-0606-7b2e-96bd-dc68efe3a95c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15e-0612-7a7e-95fb-6db4d38ee082
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15e-064f-7abb-b943-ccdeec6164f7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15e-0643-7d1c-b743-f7aa5bd7caca
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15e-0653-7d2c-917a-4662e5f30632
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15e-0655-75f7-90e7-12d0ed1509a7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15e-0657-7700-b896-1703c3549b66

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15e-3773-70c2-abbc-314cbe8c8ca3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15e-3779-7fa1-8ef0-0f3aae78aeb0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15e-3782-7dbe-a6d9-569afdd7d06a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15e-3788-74aa-8ba8-761c13fcc23c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15e-378d-7964-ab7b-5d549b3b3a5e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15e-3795-7bd0-8b3c-b97a056bedfb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15e-379d-7386-a5bb-3e98085c6280
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15e-37a4-7784-8753-a48671b13ec1

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15e-4c3f-71b8-871a-029e5be1fb1b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15e-4c43-7219-b5b7-988c7364c191
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15e-4c49-7b9f-afe9-a93df43b2776
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15e-4c4f-709f-aa00-1905f3bca715
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15e-4c56-7214-8472-92667bbeb50a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15e-4c5d-742f-b9a1-b5e4b1ea0b2e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15e-4c63-75c3-ba57-fe15d6d41ffa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15e-4c6a-7cd9-a146-a019dba9ae76

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15e-63ef-73cc-8ed2-7b33504fc7ed
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15e-63f4-7a74-a770-451a2e65f48d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15e-63fb-75d4-83e2-97b5f53208f3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15e-6400-7de4-a07c-f17f034448c6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15e-6408-7a1b-8c08-d19f26f582a7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15e-6410-7bcd-80f3-ffbd7ed80397
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15e-6417-7382-ac6e-89261edc1fd8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15e-641f-7a59-98d6-f6c54593b424

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15e-7bed-767f-996c-b1fd0efc0369
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15e-7bf2-749f-8b53-2e8810e481ac
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15e-7bf9-71a4-a7e9-32fea6ffd0fc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15e-7bff-776b-83b0-2a9a0c554cee
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15e-7c07-7af7-87d7-1f47aa1526a4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15e-7c0f-7d04-b731-5303558f3e7e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15e-7c15-76a6-acfe-288a01a9e92e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15e-7c1c-79c1-a418-90b41174e5da

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15e-8f6f-74af-9753-4789c2d4267a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15e-8f73-786a-81f8-309bd82a040d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15e-8f7e-74f6-8fbd-71e8cfc86ed1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15e-8f85-7b6c-aec3-7e6bd4bccc07
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15e-8f8c-73ff-a31a-7b4518fc7bc0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15e-8f91-7ac6-9440-5d3eaf79b078
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15e-8f97-7644-9663-8c02b6165719
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15e-8f9d-7a00-b505-73681bee41a7

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15e-a282-7a72-85dd-5de530b17c93
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15e-a285-76b1-991e-05b086bb5e27
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15e-a28c-7c23-ab7e-80f78e986845
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15e-a293-7b5b-89a9-fe00ebfd7345
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15e-a29b-709c-bd9a-4d53f8224e7d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15e-a29f-7518-976e-1408c1c102f7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15e-a2a5-75c8-b340-922e8b50a38b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15e-a2ac-78fc-9d94-0a0f4260d3df

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15e-bafd-7d8c-84d3-e7695f642e3c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15e-bb00-781e-89aa-5a33b0502c5f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15e-bb07-73a5-8cb7-8ae45bad8897
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15e-bb0e-7dcc-b754-2d7bd5f2cf8f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15e-bb14-7156-863b-6a6ca2979b01
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15e-bb1b-7424-a3f3-cb60f384807e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15e-bb22-7448-bdf9-2f71bb2435ef
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15e-bb29-7bba-99e1-f228a1eed113

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15e-c847-7569-a2a2-6eb49d513d25
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15e-c84a-7b17-9ddb-47caaeb22efc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15e-c853-7d64-b8fd-10ed5aeed1a8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15e-c85a-7fab-b398-b21e2f2c987d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15e-c860-78ab-8f9f-05dae396f90e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15e-c865-7a38-a519-041d86515984
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15e-c86a-7257-b7c2-1b23a62b9dff
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15e-c872-7182-89b9-08d8b679d3c9

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15e-dfd5-7bf3-8290-5bf43a9f3c61
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15e-dfd8-7f7a-a92b-74445189ae99
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15e-dfe0-75aa-b31e-119cd6857bc9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15e-dfe8-73b1-9a49-6e0c4539b3ea
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15e-dfef-7e1e-9080-7745851a3fd6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15e-dff6-71cd-83fb-1cabeea6c568
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15e-dffd-7f6e-b22f-03ce500c4af7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15e-e005-7e89-b358-f9e77d6a3fec

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15e-f5c8-7e6e-b628-6ab9405d5f83
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15e-f5cc-7cc6-af05-aa3523baae91
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15e-f5d6-7f50-a66e-1917967b7735
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15e-f5dd-731e-8eb7-338c3bf6a27a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15e-f5e5-71e2-8179-462b50a074d3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15e-f5ea-752a-b8bf-2fe690489351
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15e-f5f1-72c4-acb8-0b760d0da85d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15e-f5f7-73ea-8b07-d05967c927b1

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15f-198b-7c9f-9bef-b47b97c025b2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15f-198f-7627-91ef-76a5e2bcdca7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15f-1995-7278-b630-dba764624aa3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15f-199a-7b2e-ad4c-bcefe554a7b6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15f-19a0-7578-b5c2-1711145c532b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15f-19a6-7aa2-8791-1db2df35b59a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15f-19ac-702d-97ff-2e6800a03458
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15f-19b2-74ae-9c32-66b4a72116b2

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15f-2c80-720e-bfbd-a00c6ddd6203
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15f-2c84-7db8-8a3e-7f9cf1c000dd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15f-2c8a-7f9d-8d6b-fc931917ff37
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15f-2c94-71ce-ac7e-b0b52e00bd1f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15f-2c9a-741e-a6ae-982b657ff7fc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15f-2ca1-71c7-8376-a895eacbb280
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15f-2ca8-747a-bedc-931873f976db
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15f-2caf-7d04-9a59-0b5ab6f90aab

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15f-4017-7725-a99e-7c26eba8500e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15f-401b-769a-b007-131d6f456acd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15f-4022-7083-a66b-b495fe3fcb62
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15f-4027-71d8-a490-d44f39daa851
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15f-402c-74ec-8e08-df6c961b9a4b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15f-4033-7e2c-97cb-3c2a03cfb785
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15f-4039-7cdc-8e13-34a836de29f9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15f-403f-7289-9bc8-f43668052df5

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15f-5198-7ef0-85ca-3bc2c6e0c9a3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15f-519e-784a-8de3-4351d9157733
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15f-51a3-7f89-94f2-33752e403a66
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15f-51a9-7adc-a85a-00a0bb876ef7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15f-51af-7331-b462-e8cb3d553517
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15f-51b5-7f4f-af74-9a9dc583fa93
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15f-51bd-7cf1-a3a1-be6ced925925
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15f-51c3-7137-932c-13bb193d4fb7

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15f-666e-7252-b3c3-d1725d6706db
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15f-6671-7277-bc24-f3a0e2931153
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15f-6679-7836-b3b1-1ca21856979b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15f-667e-7376-b4b1-5115d3a4ec35
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15f-6685-7593-b728-acdd8eb1ae81
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15f-668c-755f-a1ad-60ea7320e681
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15f-6693-7a38-950d-9f2688bd26ee
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15f-6699-772d-a34e-35ef77a2b175

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15f-7a72-7419-8041-e8cae1265f09
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15f-7a76-7aa3-9ff5-4c6119cbd59a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15f-7a7e-76dd-a272-fa657213d639
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15f-7a84-7399-be21-4385323bb46f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15f-7a8b-7656-90a3-a3f3093665b5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15f-7a90-716b-bd34-a4b49f6227dc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15f-7a96-75d4-99a3-a3d9ad39a18a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15f-7a9f-707c-b6e5-62a5f3953741

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15f-8e0c-70e0-8002-86654b974f68
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15f-8e0f-7ceb-b3ac-3d4c83732e4a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15f-8e17-7107-ab2c-6d578b949540
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15f-8e1c-7cca-a845-93627774c715
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15f-8e22-7eb8-8b2d-21e2ce814f93
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15f-8e28-7fb0-a2c0-c3b399640a90
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15f-8e2f-7b2e-af43-1378844b7a48
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15f-8e35-7bf8-9370-242c07829614

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15f-9d85-7e36-857c-c92a9b03eb67
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15f-9d88-70d2-aa90-2c4b11622599
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15f-9d8f-78ec-ab82-883f04e592f5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15f-9d97-7a68-88d3-9bba9fd51c9f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15f-9d9e-7566-bb95-c13a509e53de
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15f-9da3-7037-994a-3a45e3efa780
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15f-9da8-73da-9f55-637456bd0450
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15f-9dae-7c4d-bb6c-72f1dcb92ac1

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15f-ae5d-759e-9f71-c5986b1b0fe9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15f-ae60-798f-b6b8-421dd19025a8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15f-ae68-7c8a-ba1c-24d1a09d08d7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15f-ae6c-7935-884a-d621e0843472
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15f-ae74-718b-911d-2dc1d384582c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15f-ae79-7100-9307-5b0aa767911d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15f-ae7f-7d08-9a4d-d21f8b3b15c6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15f-ae86-7541-b9c3-85b9bb5fd130

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15f-c2cc-7beb-82fe-84b78eb3b017
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15f-c2d2-78ca-b20b-25c1280aaf51
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15f-c2d8-7010-8a13-75ad8f92e5fe
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15f-c2df-7998-ae96-91a0ed7d52fe
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15f-c2e4-71bd-a489-b20d88977850
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15f-c2ea-77df-b762-82ed17e83b5d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15f-c2f0-7f3d-807e-edc8aab3a2ad
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15f-c2f6-7747-b189-ea4c9edd318b

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15f-e681-72bf-b72b-7b3cf44fb8a6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15f-e685-7812-8da3-5cf6e383ce5f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15f-e68a-7e7c-8c7d-adeb08bfdf7b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15f-e690-72c9-9cf9-ca038664616f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15f-e696-7324-b2ba-47c3c5292153
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15f-e69c-7114-a6b2-cbb41bd07b40
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15f-e6a2-75cb-bd78-4a11d6def808
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15f-e6aa-77b5-af0d-661ceb5a2053

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15f-f925-7074-bb70-4cd96ad06317
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15f-f928-77af-9764-2b1d08548ded
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15f-f92f-7604-811c-d347c03015b7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15f-f936-74f7-8ca0-935b7042fedc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15f-f93c-7352-942b-182c9fa42352
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15f-f942-7c7b-9851-faf1454da7b9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15f-f948-70c8-aee6-9e0199077160
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f15f-f94d-75d8-9ae1-65e272c458e6

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f160-11ff-7c9f-8a99-2c49dc27d6fc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f160-1203-7155-b005-f8a4a4735fc1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f160-1209-7373-99e5-654528b35e92
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f160-1211-7166-bc81-9ad89a2059c2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f160-1217-751c-96f9-18ef7b87312b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f160-121e-73f1-b534-291255987819
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f160-1227-72ae-a05f-a5f9c8f2cd8f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f160-122c-7a9b-9443-54dc2cc59f62

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f160-2667-7aa7-babf-a13eac9b611f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f160-266a-73a5-a81d-823f566fb821
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f160-2671-7e03-9931-8136db6b593a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f160-2677-71d5-8a48-aeab07ee81a0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f160-267d-7556-be38-4a2fe034b1ab
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f160-2682-7fb2-952d-aa7a708b69ad
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f160-268a-76ef-b8ae-f8380f029f98
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f160-268f-71a2-9741-cd4ce72afbbd

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f160-4779-7608-a813-aa10aabe5b44
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f160-477d-7927-b4c9-40dfc7fb2ae6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f160-4782-7001-ad4b-bfc4621e082c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f160-4788-7b27-a5fb-01c9e23dc606
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f160-478e-79a8-8d43-ee5eef58ae40
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f160-4795-7668-a24c-3b1d5916551b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f160-479a-79e7-b4c1-ab51a0808c50
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f160-47a1-75ad-882e-3ca258fe6deb

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f160-5bb5-7330-a21a-b742d7365998
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f160-5bb8-7257-be34-574f1e84ec38
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f160-5bc1-718b-8cf6-f6241cb473eb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f160-5bc6-7e93-94ce-9ffd9e72c450
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f160-5bcc-793d-bb74-900ce26461e1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f160-5bd2-7458-a6cb-0989302c8814
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f160-5bd8-7539-962a-3b8a5175a565
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f160-5bdf-70cd-a688-c8fc68c28856

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f160-70e5-7f45-9b8e-2dc13258e634
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f160-70ea-750d-9cbc-358743492a7b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f160-70f1-7a84-afb7-f6841de52c4d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f160-70f7-7f34-a490-04b71df20567
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f160-70fe-7e7d-a76c-7b61f4269ee0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f160-7105-70bd-91c6-b022244cace1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f160-710b-750f-ab6f-d4ef34613229
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f160-7111-7a03-aa0f-14ece649c0be

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f160-8cf8-74fe-9809-2333a4032c6d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f160-8cfc-77d4-a8f6-3547f2e4d29b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f160-8d03-713f-ba51-080e239c292c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f160-8d08-7889-ad4c-cff43189d18d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f160-8d0e-7fe9-b47c-0d9fb9faa88c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f160-8d13-7602-a4c6-2a4198984271
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f160-8d1b-7d6b-b94c-373f6e7fe34c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f160-8d24-738e-b4b9-408831a6dd9d

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f160-adc9-7ad2-9273-d4966bad6083
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f160-adcd-7415-9156-90fce39a91fb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f160-add4-7ee2-b9be-10f8f775b842
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f160-add9-780c-b5f4-0533c3cca234
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f160-addf-75e0-b145-5ccc94d93a39
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f160-ade9-7383-bff1-619a9353804c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f160-adf2-7940-bdb2-382e4e53e40b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f160-adf7-7728-8cf1-78b4fd30dc3f

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f160-b823-73fc-b025-cd53db9a2983
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f160-b828-7d62-8053-2f4b8feb11c4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f160-b82f-76f9-8fd5-e52a90dada55
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f160-b835-7887-88d1-51bf6cd1bc73
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f160-b83a-7cd1-b148-b51fb2263a15
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f160-b841-770c-82a3-123480c78840
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f160-b847-7206-b42c-9db7ea4b18c2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f160-b84d-70bf-a32e-eb7c15dcbeca

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f160-d181-7fc7-98b9-2027f86b07dd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f160-d184-78a5-82ba-a55ee2fe3cd0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f160-d18b-7ba0-9a29-c786be5af1b6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f160-d191-7e6d-be53-1058fad5c727
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f160-d199-77cd-b3e3-4570cb07e7af
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f160-d19f-7dd3-b1d9-c1abcb97309c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f160-d1a5-7823-a7b3-bf30872d4103
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f160-d1ab-7237-8efe-017e81ee3acf

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f160-ebce-7b71-852d-2dd135505a21
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f160-ebd3-79ed-9b52-a20b52d9db78
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f160-ebd8-7dbc-a5a7-5d418d05bb2c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f160-ebdd-70e1-bace-4ec61d509ac7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f160-ebe3-7ae7-9e6b-038ecf64ae90
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f160-ebe9-7818-a28e-920dd83119c1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f160-ebf0-7cde-b8a6-e0d8018c8499
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f160-ebf6-7833-b82b-e13332e6f622

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f161-0a45-7cb3-aba3-54c5b45d6957
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f161-0a49-7d55-87c0-7aa0dae05c08
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f161-0a51-7452-9d9e-e4aea2fd4794
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f161-0a57-7ff4-a5f4-f18d55bba2b1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f161-0a5e-78a8-a4b9-74f564927f1d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f161-0a67-7f20-ba61-5c16830e887e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f161-0a6e-7494-9c33-707649f86a5b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f161-0a76-7581-afc8-bd8d90120c5c

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f161-224d-755b-be47-7a9876b9056a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f161-224f-77bc-b031-02c1fea4f3e5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f161-2258-7de9-8b9f-20de1d6ba759
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f161-225e-7d9c-a3de-4f89468b9935
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f161-2262-775f-9000-1fc2e0ecb03c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f161-2269-73a8-8105-9a531c48c3df
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f161-226f-7b8a-9839-153089460db9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f161-2275-744f-b39a-567267ed25f3

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f161-40f9-70f6-98df-9a021a099e1e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f161-40fe-72a2-9821-577d6b085bc5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f161-4102-7e86-ac71-5eb8bf789d49
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f161-4107-7c5c-a668-5c7be392f5c4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f161-410e-74bb-b9fc-bc44f81970f6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f161-4116-795a-bdb9-5c8d0f070947
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f161-4120-728b-bcba-139081840888
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f161-4128-7632-9011-721066b820bd

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f161-66c7-751b-ae20-74c577e3ab42
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f161-66cd-733d-b475-2c80750070a3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f161-66d6-7feb-9642-06902651b044
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f161-66de-7136-8fad-f3e7d89866a4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f161-66e5-703a-adbd-be72adcda31d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f161-66ed-70ef-b09d-3306fbeced47
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f161-66f8-77d3-bf8a-7b66aee77444
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f161-66fe-7417-9256-3c1bf2f6ff39

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f161-83db-7e67-9146-06b50a9579da
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f161-83de-7ffb-9d0e-9290a09af95d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f161-83e4-734d-ac6b-2f39302f1502
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f161-83ea-74cc-b504-afd036269e8a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f161-83ef-7f3e-8a45-893e3a3a27ed
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f161-83f7-7fc7-9712-b9de275afdc9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f161-83fd-7881-b20f-d56c79ea3d12
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f161-8403-7e78-a264-16f810ae911f

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f161-968d-7e7d-a9b5-e5a76a7f95d4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f161-9690-7d59-bcac-fc60603d0202
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f161-9697-7ee0-8887-7372e59d70a9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f161-969d-7fdb-97d7-7a7bf2acd6ae
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f161-96a4-7aae-80db-5f182dcf42b9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f161-96a9-7cee-a5fe-0f66f958ebcd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f161-96af-70e8-bbc9-7aff518992f3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f161-96b6-7ddb-8d7a-580590987e75

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f161-ae66-796d-a7a2-9d9cd81cfe9a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f161-ae6a-76e0-8bbe-f4b30f558bfe
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f161-ae72-7c8f-9507-c4a20897f38b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f161-ae77-7874-8149-5fce58052535
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f161-ae7d-7657-be6d-64f6dcfa150c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f161-ae84-7cc7-8f05-9cba45244811
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f161-ae8c-730c-8b52-d93720457806
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f161-ae90-7bff-9459-8e4d2f446aa2

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f161-c07d-76c5-8cf0-f88385fdcf6a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f161-c084-7144-a0b1-c012830df948
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f161-c089-7eb0-8dad-138a67b58749
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f161-c08d-7e5c-b997-a45e039bbf96
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f161-c093-71ea-a954-f1cc00b3b2dc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f161-c097-7bad-963f-eec72e6c2ef6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f161-c09f-7a13-83d8-a521ca215c4d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f161-c0a5-7da1-9360-5c324a7d63b5

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f161-d758-76a1-a124-ca31a921d6fa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f161-d75b-7066-9ef6-afe89fdf7d25
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f161-d764-72ae-9a38-d965107ed2c5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f161-d76a-7754-b749-7a6a93916384
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f161-d770-7584-9b7d-ed2494e6e81a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f161-d776-7b1f-a09b-e5eee39e0981
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f161-d77c-706a-b23d-29e5a566a413
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f161-d782-7fe7-87cc-84eb0530a705

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f161-e1a4-7a8c-b573-a930cbdf213c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f161-e1a7-7098-9770-46e6aa09691a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f161-e1ad-78cf-ba6c-c0cc24494702
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f161-e1b8-76d1-ba5a-b475e7d2d2ed
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f161-e1bc-744f-98a3-a43058be99ed
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f161-e1c4-72db-a84c-26e840edc6de
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f161-e1c9-77a5-b388-668dbef2abf4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f161-e1cf-7158-b55b-6c33c1f10dfb

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f161-fdb5-7026-bad6-03563e8486dc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f161-fdb8-7337-aef7-801747fc69a9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f161-fdbf-779a-9ac5-81c387bc11ec
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f161-fdc5-7269-afcc-e4cae073f37f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f161-fdcc-738c-a252-9916af2cb8f8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f161-fdd2-7166-9bcb-0c141786189f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f161-fdda-7d6c-90eb-b1a5bf20c494
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f161-fdde-7150-882f-ad01f8f981fe

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f162-10b2-7d99-9785-f9864c024e68
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f162-10b6-7122-be75-d7d2f636aa31
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f162-10bf-7dce-b208-a60c33057aa8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f162-10c5-7e63-be18-e8e22abfc430
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f162-10ca-79e2-8d16-e51f25735b1f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f162-10cf-7d26-9353-04a95d7e79e6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f162-10d7-7805-933d-aad6d065837e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f162-10dd-7cbf-8d17-d61ffff1eb96

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f162-27be-7927-8fc1-77861b80a33c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f162-27c2-701b-8ba5-18b68580f5d9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f162-27c9-7569-a76d-3fa4e3715a8e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f162-27ce-7d94-b97d-61d9930993bd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f162-27d5-73af-a91c-58a72d02f2b6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f162-27da-7433-8e94-8ea19ede7fd8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f162-27e1-787a-bbeb-049d345b968d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f162-27e8-7d85-8c1f-4ea2e804fe47

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f162-46f0-741f-9b2f-89626e55d0d5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f162-46f4-7fe9-bccd-980858413b06
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f162-46fa-7507-9fbc-7494f1eb3467
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f162-4700-7e18-90df-795e9962ec08
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f162-4706-757a-a23d-bc145ddbfc22
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f162-470c-7f64-80ac-50d440d67e43
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f162-4713-7c69-954f-bd49f896dfde
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f162-4719-7335-8c43-bbb7e18eaa44

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f162-5a8c-7a5f-922e-226dff47ef25
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f162-5a8f-7297-8a52-11a9a0761a91
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f162-5a97-7bf5-b42e-85409d82cdc2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f162-5a9d-7bb1-be69-dc64ddb6d6bf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f162-5aa2-76cb-9519-51c5432831a2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f162-5aaa-766a-9271-54971f74016f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f162-5ab1-776a-9375-ecbaf0fa44fd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f162-5ab8-712f-b122-66aa1c00d03e

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f162-79fc-7fa8-beef-2d7303aa9ad3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f162-79ff-76fa-bbb8-ddd3ac4a9ace
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f162-7a05-7a61-a2f7-0f122a34c9ea
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f162-7a0a-70cd-b7ab-ae3e5a5e26f1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f162-7a0f-73e8-93f1-00ccd0bb0469
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f162-7a17-7f8f-bcd1-be8dca898564
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f162-7a1d-74be-afee-68624e184fc9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f162-7a23-7edc-a4d2-a7eddebd498a

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f162-935c-79b5-8cf2-c0eb7e4e3c30
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f162-9360-7ca6-b277-99e801274b6d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f162-9366-7c33-af9c-3417b01052cb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f162-936b-75a2-8e58-153c065654b7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f162-9370-7b04-a30e-be127b107b87
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f162-9377-7a49-a42e-eab08eddc3b3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f162-937c-77b2-b158-557f43dd60dc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f162-9384-79f1-bf0f-b8e3529153b8

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f162-b84e-7586-9194-cf2de608afc9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f162-b851-7371-883c-531f9fd7c145
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f162-b857-7b98-9ac4-7b8afde5dfb9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f162-b85f-70ce-acda-a7fe3d67291c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f162-b863-7a60-86c8-deeac1dfa276
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f162-b869-7626-9382-d5d6572460a4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f162-b870-7161-a8ad-a384db3b3c1a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f162-b876-7870-8f5d-4abcacf930d7

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f162-d340-7df3-bdbb-b1dbb3245024
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f162-d343-7cd3-aea3-25682a51b9a0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f162-d349-7f24-a095-7c7c77fec06d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f162-d34e-7473-b40e-f96516410299
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f162-d354-7137-b701-183d8b3f06d2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f162-d35b-7a4c-aeec-7d94082e999a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f162-d362-7b38-856b-be73a954e4bf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f162-d367-7f0b-b54c-c0404d6846d9

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f162-f57f-7d44-a2d9-37596b5d3168
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f162-f583-7e43-819f-774c04d851bb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f162-f589-7e6d-8511-ba4bcff8f66a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f162-f58f-7bbf-8d10-5006cb327f21
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f162-f594-7e1d-9440-28133fda0dc7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f162-f59b-7290-b7b4-0cd6bda0e486
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f162-f5a2-79ce-b2e5-e23219498d03
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f162-f5a7-70e1-8d7b-9188dbfa61be

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f163-188d-707f-a06b-d9b664515637
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f163-1892-71a6-bf00-81c1ac81965d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f163-1898-7aee-bf23-6daf1b5dff13
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f163-189d-72a5-ad86-58d231a400bb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f163-18a3-7fec-97e8-82fc37c6fd74
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f163-18a8-7b08-92f2-576f26b340b2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f163-18ad-773f-bc32-f4e02c78668a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f163-18b4-774e-b8f0-81c3f2011fc2

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f163-28f7-7c16-a80b-88250226d964
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f163-28fc-7073-b953-a35972751762
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f163-2903-78f2-ba8e-f58868fec856
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f163-2909-78c2-8df5-7984ce4a8f1b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f163-290f-777c-a0ba-c7fba7a96b09
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f163-2917-7770-b3bb-882e12367cb3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f163-291e-7f79-84b1-202432be24d9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f163-2925-7058-a612-0b37e7d25475

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f163-4006-7c47-bff7-9edd07e52d24
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f163-4009-700d-bc56-4ad0443d9c7b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f163-4010-77c4-a775-40896a7e8610
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f163-4015-79db-9997-ef2f244acbbd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f163-401a-7405-8df9-19691998e061
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f163-4021-7feb-a0b2-b5313a0cf1bd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f163-4026-7795-889d-ca121baff31c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f163-402d-7b93-82f0-6c82cb89d484

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f163-4dcc-7a07-9148-2c4c0bdeb00f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f163-4dd2-722a-b359-4cb21618e0d6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f163-4dd7-715a-89bb-28c70ad54893
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f163-4ddd-7fd1-9858-0f6c9cea1e1f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f163-4de2-701b-97d6-c6c57f46cc35
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f163-4de8-7cae-9c58-2f3424909a32
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f163-4dee-724b-9cf6-df43759c5904
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f163-4df3-7b6e-8215-e19f09c69d41

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f163-6895-7a0e-a883-d74c4db770d6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f163-6898-7543-94a6-f4017dc05fc5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f163-689f-7119-ac8c-7351ae3bb4c9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f163-68a7-7912-baa8-73479b881e3a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f163-68ad-7b9b-b965-32ddf0ec5260
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f163-68b3-78f8-b65f-615cf2d8b392
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f163-68b9-71c4-b8ca-b4d1d4c822b9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f163-68bf-7dd3-b25c-5d098f9806c3

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f163-7e1d-7ff5-8372-db74fe8d429f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f163-7e24-7eaf-badf-baec475bc289
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f163-7e2a-72fc-8f26-6a2e93db2233
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f163-7e2e-78db-a2f8-8e0c95ffa01c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f163-7e35-7e48-ad39-45a54004eadf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f163-7e3a-7a02-b10b-e61b79a6c234
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f163-7e41-7ba6-bbff-38bfa508d8ff
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f163-7e46-7290-aa1d-6aaa42b2ba3d

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f163-9858-7605-934d-8cf8a0f9c3d1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f163-985d-76ff-9bd7-a6f13dd6c74d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f163-9863-73e6-ae89-8756b89a8dbc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f163-9868-7c54-8f11-8d8d87e16488
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f163-986f-721e-9e7f-21350f2bc5c5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f163-9874-7910-9a0a-1f2c7ae3b6b3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f163-9879-740d-98a3-1ec77452dd65
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f163-9880-7a28-86c8-b0e407982d67

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f163-adaf-703c-8d31-b687c069a7fb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f163-adb5-71de-928e-b0f578e8153e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f163-adbb-73fb-a52f-3dd6ef94820f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f163-adc0-74e6-9e8b-43668940deea
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f163-adc5-79da-9e13-ccad28c1fe63
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f163-adcc-776a-927e-8dde5fa2a740
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f163-add3-7028-9062-901a6c7d0e83
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f163-add9-73e5-a83a-bb9e5b67ecba

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f163-cbf9-7e33-8eaf-8c8f636fcdea
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f163-cbfe-76f1-b60a-5611dd63ebbd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f163-cc04-7cb5-a7c0-7810e40d02fb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f163-cc09-7bf9-9947-fe0d30c3c6f8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f163-cc10-76da-a7eb-d6413352d0e6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f163-cc14-7e10-bb0c-ac9ec553be47
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f163-cc1c-7eea-ad7c-2b1560ef218b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f163-cc23-7b83-9e00-8105efd52b04

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f163-e7c2-7313-ae35-3593dc39d8df
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f163-e7c6-7948-9aeb-786dc9f567d8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f163-e7cd-7ea5-b391-a986c7283532
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f163-e7d3-7300-9017-c2f0ab600a0a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f163-e7d9-7985-bee5-a362673fec34
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f163-e7df-7185-a3f8-34816266922c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f163-e7e7-7b89-94d6-ca2d3638810f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f163-e7ea-7e3a-847d-a3b6ce3c0136

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f163-fc44-7a51-b6f9-25c9d81ae0a4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f163-fc47-738f-ab9c-26576764b2b6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f163-fc4e-7fc3-a8ec-1ce85ac7b8ee
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f163-fc53-76dc-8de9-b91b704c54d7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f163-fc5a-7c5c-8a3b-ef5945f181a9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f163-fc5f-716a-b548-bb1ab538d710
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f163-fc64-74d8-ad04-19a34520a2a7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f163-fc6a-7582-a22b-e344503f4903

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f164-117a-7878-965e-ad18cc778530
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f164-1180-7b3a-9687-b265eba65629
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f164-1184-7b6e-bdd3-300cfd27b85e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f164-118b-7939-b2d9-8e073ca7a65a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f164-1191-746b-aa10-bf223396e01a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f164-1197-7ece-8c8c-3c76df7aefd7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f164-119c-73b4-a935-a816d08d49e4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f164-11a2-7ec4-b498-a178fb97fcaa

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f164-2bb9-7210-8ace-d1a1bc2b27fc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f164-2bbc-74a2-a842-4125e7e1af5a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f164-2bc2-7ad2-809f-df95ba501efe
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f164-2bc7-7340-941b-105a2623a5ea
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f164-2bcd-71ed-9ee4-4437eabd5e29
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f164-2bd2-7622-bd1f-53bccad91324
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f164-2bd8-7790-9cdc-4ef0c8d2b3d6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f164-2bdf-7a58-8bbb-b92659eb4091

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f164-4a01-7bdc-9aa9-35d267e774ab
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f164-4a04-7179-99dd-dc0b549e456a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f164-4a0a-7657-a5ff-330878b8b24b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f164-4a12-7543-9bc3-f878406cefbc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f164-4a1a-7a0a-95ba-96b7e24dafb2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f164-4a22-7faa-9df4-a8e309ceb2ee
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f164-4a29-79ba-bcd9-b4202ccce92c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f164-4a2f-7a12-8468-1313ba6c20ef

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f164-625f-763d-a7c4-ce41537d03bb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f164-6262-7737-8fcc-92aab928bb53
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f164-626a-73d4-a691-c60d99051791
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f164-6271-7bfc-aba0-c323a26c963a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f164-6277-7088-90e9-8b41e1fb79a7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f164-627f-71e3-9840-4d8bee08307e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f164-6287-7180-8113-ae52603f2909
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f164-628d-78e8-a88c-3861ab3ebbac

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f164-8299-7634-a690-97588481e5bd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f164-829e-75bb-bed3-2feaa9825c38
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f164-82a2-7650-a2d8-2b63387872d7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f164-82a8-7a76-aa1f-b6dc6b1b13ee
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f164-82ad-711e-a9f0-786c163d44ee
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f164-82b3-7c9a-a31c-82723cbc0e2f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f164-82bb-73be-99fa-8b3fdba11821
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f164-82c0-7fdb-9f47-c85f8dccbb76

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f164-a60f-750d-8db0-0910e8673fae
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f164-a60b-791f-825a-32a48034ccf2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f164-a616-7f7f-95b3-a9f26eaf1a93
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f164-a61c-79c8-98f8-51b738fd6295
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f164-a622-7b76-8e2b-2c4b5a99ff05
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f164-a627-7a1b-bce5-ef4bcf8d9206
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f164-a62d-79cc-ae84-a08d68609f9f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f164-a633-7601-ae50-7f74ef9bb599

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f164-c493-7727-9e4f-53a2439473ba
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f164-c498-7500-b952-fc314d9e65e1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f164-c49d-7c6e-a919-2cf1b8d7ce5e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f164-c4a2-78ac-97cd-d475df09650b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f164-c4a9-7575-97be-bf592371d1ca
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f164-c4ae-71f4-832c-48da321606be
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f164-c4b4-7486-90bb-ed3515a910cc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f164-c4bb-717a-ba04-294834851cb0

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f164-e326-70d5-9605-105e6b0cf5a2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f164-e329-7656-835b-6890fbc1f524
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f164-e32f-78ca-8516-7cee14e07ec6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f164-e335-7feb-b21b-0c6df562f413
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f164-e33b-739e-888d-e10f5c4f7a2c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f164-e342-7927-b6b6-7b2effbdb90e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f164-e348-767d-aa29-77a08508c613
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f164-e34f-7dbe-8ac6-912c9fa226bb

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f164-f580-7b4b-b0c8-1655883857cb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f164-f583-741d-bb3d-a2bdcc906eb9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f164-f58b-719f-bef0-2dc311ce44f6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f164-f592-7c60-85d5-9718f5c38f84
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f164-f596-7610-a222-a5148cefa884
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f164-f59f-75ac-8a01-718bc11f789e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f164-f5a2-7a56-afc2-144be8ae61d2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f164-f5a7-76b9-b74b-054e226301cf

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f165-0575-7efc-975f-ee66074a345e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f165-057b-7e9f-842d-833979dcbce2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f165-057f-7911-9399-530a5974b069
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f165-0585-7e94-86b3-c04b64af6554
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f165-058b-74c5-982a-39e9211e641f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f165-0591-7d8a-8fdb-f854f14d3e96
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f165-0597-7c56-93d8-f113371b8e36
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f165-059d-758b-8ccd-d5b5012a160e

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f165-17fe-7cea-9ddd-10a4b119a3f8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f165-1801-7bb6-8f20-6edb1902b69c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f165-1808-707a-993e-47776ec75699
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f165-180e-71ed-bcf0-be21dc31eaf1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f165-1814-789b-8c0d-563590df5c78
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f165-181a-798e-a39f-13fbc9ac69ff
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f165-181f-798d-893a-305284447e3d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f165-1826-723a-ac67-2faee6495bf4

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f165-2376-7b6b-8019-691f50cfabe4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f165-2379-7347-ba88-60be83f89ac8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f165-2380-7929-90e4-0b45cc5a1054
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f165-2387-77e4-a441-aead4502ed4b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f165-238e-7f50-84f2-5c3c193f19d6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f165-2395-7ffc-843c-c561eb135740
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f165-239b-779b-913b-9b2de262a2cc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f165-23a2-7a6c-ac62-17588ed7436d

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f165-37ea-72b1-a1a9-20a2bc2e0097
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f165-37ef-773c-b198-a99533003f3e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f165-37f6-7cae-8354-9b1ccca21b8c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f165-37fc-723c-96d4-2fa74d9f14bf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f165-3802-704d-9a12-fc3aa0786486
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f165-3809-7110-a84d-e2d6fb6b939c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f165-380f-73e3-821d-d69cb6ef1351
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f165-3817-7954-9e86-c9625e5e9390

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f165-4f38-736d-8403-3686132c6d9d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f165-4f3e-7ddb-afa7-6e8897ca071a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f165-4f44-7446-9d40-a51ad043fd14
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f165-4f4a-7e08-8459-176218c0ffc4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f165-4f50-7004-9859-5facff2cc5d3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f165-4f57-722e-a93f-f01fd32e8053
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f165-4f5c-7389-a396-6935021eb236
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f165-4f64-7f60-afe2-7631d475cc4d

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f165-6695-7731-8bb5-57e3efeef861
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f165-669c-749d-abf7-904e887f2351
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f165-669f-79c5-a718-abaaddbed2c6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f165-66a5-72ad-8309-ad855afd28ff
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f165-66ab-7184-a3bc-7f0d29f48758
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f165-66b1-7c44-8b3c-7aa8160c1448
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f165-66b9-7037-aa93-52ac3bb8c5a7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f165-66bf-7c10-a120-49cb9f6c892c

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f165-7989-76ea-9f3f-6ea58446f39f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f165-798e-7f9d-bc92-aa1c55a46b5a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f165-7994-77a1-9312-db867ca83add
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f165-799a-71dc-a9ac-0416781bd1d0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f165-79a0-7c7c-888e-45107d46904f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f165-79a5-72c4-a26c-8831e7eb4621
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f165-79ab-74da-9789-9ad675f25e80
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f165-79b2-7658-88c5-f82c400460fc

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f165-9351-7aca-a292-9b6112fd8092
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f165-9357-78f8-bff4-000eaadb3a08
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f165-935c-77cc-94c6-e78b8fae4ddd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f165-9361-74f5-aebc-456952fd1d22
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f165-9369-7759-a788-bbf576cb5c19
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f165-936d-71d9-9acd-881362c03840
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f165-9374-7e35-a307-423bd4f90f16
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f165-937a-7214-bc22-4d8f2bd7e188

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f165-ab99-7507-b591-f0296b3918d5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f165-ab9d-7887-9de9-0dc144f2589b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f165-aba2-7783-93cc-a2930d5f3b1b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f165-aba7-7c9c-9368-e158fb3cd298
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f165-abad-7b22-b332-7cdcd215bde0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f165-abb3-72f0-b8db-ed005fa05b0b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f165-abb9-78da-a02e-e8983129df2d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f165-abc0-7536-8750-15c8a5a4774d

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f165-c8ec-75b1-811d-e0ba88c5d2af
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f165-c8f1-7672-a50d-ca0a0a74722e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f165-c8f8-7b58-b115-3803d33f2fac
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f165-c8fe-7e56-963d-b0b02bf2e832
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f165-c905-711e-ad1c-2c41191436c3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f165-c90c-795d-8df4-b1680ce17444
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f165-c912-7d0a-af39-e31104be1d69
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f165-c91a-7d31-8e08-fe49809f6b9b

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f165-dc75-7e9c-bf6a-ef1638d68570
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f165-dc79-7a90-a208-93214b619120
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f165-dc81-7fa4-ad30-9d1d5d3a84b3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f165-dc88-7965-83d4-50e587c8bd0e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f165-dc8e-7b30-b61c-3fd0e58a3577
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f165-dc96-7cef-85c0-f063475de47a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f165-dc9b-7d6c-a643-32af4a704a86
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f165-dca1-739a-9e79-1c65fb4c1d8b

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f165-edd2-7ca9-966b-6a8463e3e9a2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f165-edd7-7176-851d-de9a909e23c5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f165-eddd-79cf-97f6-f44465341663
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f165-ede1-7175-af5d-1c38a3197dd0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f165-ede8-7721-bf8f-a9a5b918e75e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f165-edee-7de4-bcff-a0127051803b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f165-edf4-788b-acad-d16c350bdf83
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f165-edfc-7396-b991-e6af8a4b0722

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f166-07d7-7fe7-9f5f-43a7c6dc446a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f166-07dd-7e5d-ac23-4aa5f773f255
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f166-07e3-74fc-9948-6938b978e3dd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f166-07e7-7dc3-ac6a-e8de7c87640e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f166-07ec-79f2-ae01-0d145b675f00
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f166-07f2-7feb-850f-588fda7a795e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f166-07f8-7646-9a7a-de3413121586
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f166-07fe-731a-bb48-a8f539206b65

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f166-2433-7595-9283-925f8eaf212b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f166-2436-74d7-9f05-1c5d70c31b46
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f166-243c-73d8-ac84-cab8268ff5cf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f166-2441-7195-86d7-78b86364b328
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f166-2447-7ce0-b2e0-96a2836617c1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f166-244d-7f12-ae2e-a41b8b8b9381
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f166-2454-7722-b640-73e0a718a0d0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f166-2459-7794-9a20-33f55172fa57

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f166-38cf-70f9-9eb2-18f444a4f348
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f166-38d3-7f99-a7a6-b5e32c339ff7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f166-38da-7d94-99ed-5471701dc747
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f166-38e1-7b09-aebe-e2ff07fe0c83
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f166-38e6-72ec-a967-6b609fe8cba5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f166-38ec-789a-914a-ee2bfb2a1db7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f166-38f2-7234-a1b0-173d4ef89f29
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f166-38f8-79f4-8343-220f179aa4e2

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f166-4a05-78fb-b640-f39441af4409
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f166-4a09-7426-8dd7-837321e3756c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f166-4a11-7766-ad36-5cc8acf84b4a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f166-4a17-70d2-a924-88b7a6cb4cb4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f166-4a1c-7a09-ad6e-11166ca2a48e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f166-4a22-7d24-837b-91c27a55610d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f166-4a27-7f02-926e-8c981e762f0f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f166-4a2d-78e5-b983-2e8ad2214e40

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f166-6884-7b5a-a67e-cc28168784db
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f166-6889-7d73-9aa7-1a776afaa312
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f166-688e-74ad-9b0f-8f19b86cc3d5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f166-6893-7349-83d2-595cbe9d0caf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f166-689b-778b-ab5d-4250c5202736
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f166-68a0-7e47-bc84-19e5adcd1f2c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f166-68a5-7c6a-9d90-9b4a63080542
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f166-68ab-7660-a804-7e82a785be1a

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f166-7c59-71c4-8871-ef75b22bdf9e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f166-7c5c-7d3d-a83d-5de42ab76dca
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f166-7c64-7979-b33f-3a10c0e49f24
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f166-7c6b-75c2-a7d2-abf44935d562
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f166-7c71-7e03-9121-28fa5d2c5bcf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f166-7c76-7df4-9f33-c716c50b99b7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f166-7c7d-788c-9966-d89f159c2513
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f166-7c82-71f4-aca6-602887503196

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f166-918d-79e5-8e54-6654feb296c0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f166-9193-7f49-8aba-6a4ffddcc30e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f166-9198-7b55-ad50-9a9584f4bd04
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f166-919c-7f86-b12e-1b01375777cd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f166-91a4-71d5-89b3-956531b3b421
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f166-91aa-7348-bf2e-df7d28fdc09d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f166-91b0-7067-8f53-9fba50629de3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f166-91b8-787f-b2ff-c45346a62ad6

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f166-aeec-775b-b0e8-10ed2cbcb0de
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f166-aef1-7db7-a906-7f483332ac96
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f166-aef6-7804-849b-6b9da405b1c9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f166-aefc-7c25-9eac-8d0f80c24e6c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f166-af01-7e99-a1e5-a0a7f2d30408
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f166-af06-7745-b1b8-507d6c60120e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f166-af0d-78c8-b704-e55fb7340726
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f166-af13-7872-8e75-c43fe923413a

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f166-c2c2-77e8-9b2e-8c3c4021037f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f166-c2c5-74b3-8c3f-4bfe2e3ff3f6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f166-c2cd-70fb-ba13-0bdcf4d29c49
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f166-c2d1-74ee-8ddb-6a51590f536a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f166-c2d7-784b-a775-b980305dc327
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f166-c2dd-7fc6-a292-04d3f9e5c13b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f166-c2e2-7723-854b-a4b4af06a428
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f166-c2ea-7564-ace3-ba55ea68aab5

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f166-d558-7598-ab9c-3852b228ce00
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f166-d55b-783a-80e8-d88ebf977d16
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f166-d562-7113-aca3-39b4720f9bbe
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f166-d568-70d6-bb93-90c47a25110c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f166-d56e-7dfd-9576-20ef5e1a25ca
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f166-d574-7bfc-aa41-d2962313f856
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f166-d57b-7e15-be61-d0439599e36e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f166-d581-74b7-ad5b-1a569777f167

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f166-e853-7c0a-94c1-ce3051dc1f2c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f166-e857-74cd-86d2-cb231ddd3d7a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f166-e85e-7fda-bc75-3608ca1102c4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f166-e863-7a09-9693-9bff142d1adb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f166-e868-7b2f-a1c8-9f9d65fa39f4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f166-e870-7246-ab1b-d61204d13f33
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f166-e875-79f0-a0d8-b971f2b8ca4e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f166-e87b-7240-8d27-a15e382edc88

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f166-f98d-7145-b8de-0d453a411495
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f166-f992-74f7-9011-428442d4c615
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f166-f998-70ae-b41a-0e5cad2aa7f3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f166-f99e-75f6-89a4-beb60397a7cb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f166-f9a4-7125-8696-7e88d48b3f50
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f166-f9a9-749e-b94b-902bb92b2cbf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f166-f9ae-7be6-96dd-e2dfb0a4a7e9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f166-f9b6-77c8-8546-d38dc6de6b99

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f167-0c35-702d-8855-1cffeb6d95b6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f167-0c3b-75fd-81b3-67f3ab38fb9a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f167-0c41-7811-9b6a-943d1f5d6256
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f167-0c48-762d-b3b5-e590e1af4abf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f167-0c4f-7c2d-9ba9-9132be1cf0be
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f167-0c55-7410-99bb-e3c6d1f4def5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f167-0c5b-7f94-a23e-54a7e4972370
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f167-0c64-7834-92d8-bb1365804c34

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f167-2134-74e9-abe9-c323e17a21c3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f167-2139-793e-b13b-5a9951305bc8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f167-2140-7b40-83bf-0b6dab1d3a75
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f167-2146-7c17-ba2d-90034587403f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f167-214a-784f-8ab9-a4afd9b496fe
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f167-2151-7073-b069-e7b354ec51fd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f167-2157-7848-a166-a3cfa11d485e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f167-215d-7792-8353-1deb1da6aed1

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f167-34ac-7851-bf65-ce17a3618e8a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f167-34b0-799b-80cd-e2ee7ee1d3a8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f167-34b5-7691-a10f-d5e274fe0bed
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f167-34ba-7320-b9d9-827ae452dddf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f167-34c1-7480-a538-8b3ff6dc3e37
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f167-34c6-78a1-be04-26e436c128fd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f167-34cc-7b09-b40e-1ae40ae5bc75
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f167-34d4-7249-a784-b26646bf22b1

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f167-4751-7ee6-afb7-3c7f4279ec5f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f167-4754-7429-9b2f-6cabeee15ee7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f167-475a-700b-ba4d-8931bebf165f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f167-4761-727d-9882-109ec9c1c78b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f167-4767-7094-8ef2-6e407219f5d8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f167-476d-7424-8ea2-8f735fb386b9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f167-4774-778c-a2fa-a514929be7d1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f167-477b-713a-948a-98c0c98c3baa

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f167-5a06-71fe-9ac5-0042ba3e8194
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f167-5a0c-7cb1-966d-c43fdc1b1e63
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f167-5a12-7171-addc-166d666a78dd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f167-5a18-7c06-9cbf-4ddf312f18a7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f167-5a1d-71cf-86f5-484f7641bd47
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f167-5a23-7e32-bbc4-e5403016e46f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f167-5a28-7e59-8251-b2c77c0447ae
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f167-5a2f-79df-a15c-8e89b3832c54

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f167-6e7c-7802-968a-0ee39a6944e4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f167-6e7f-73cd-b773-4cb235c01ce4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f167-6e86-7cf7-9245-b1b8e15bd502
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f167-6e8b-7758-930a-1b357a4829f0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f167-6e90-716c-9f1c-3ef20713e0fe
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f167-6e98-70d7-9490-8dba2a308cba
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f167-6ea0-777d-b8d2-9437a234133a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f167-6ea5-7c6e-8bbd-a5af82c108d2

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f167-832f-7072-9e88-209b9112913b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f167-8333-7a78-bd0a-8c256ed6d89b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f167-833c-7021-85e0-1f9dd883a652
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f167-8341-7a01-83e8-6b7f7cce6c8d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f167-8348-7cbb-b4c1-793bbe422487
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f167-834d-770b-9533-4143e27f0187
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f167-8354-7adb-b24b-b718a04b433b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f167-835a-7d11-9e1d-683b022c62da

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f167-9559-7538-b752-0d6829bbf145
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f167-955d-7583-a2d8-90f5e19798f7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f167-9564-78f7-9e88-f8f55b78de7d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f167-956b-7843-836f-cd531a7e5cad
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f167-956f-7627-8fbe-c3c3da4ad84a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f167-9575-7366-be72-eaf59d22df99
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f167-957b-7bf8-87aa-5d2967335908
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f167-9582-7b26-88de-229f12a776cb

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f167-ad7f-7333-8881-97a2b7ac04fc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f167-ad84-7a67-bf0f-9b4d5e313eb0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f167-ad89-7c30-a091-98c67b578944
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f167-ad8e-7895-9e0a-18172981b1b5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f167-ad93-7ea1-92f3-fa6888662903
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f167-ad98-7105-bcaf-244eccd36bd4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f167-ad9e-7f2e-abb3-72288b7b2abc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f167-ada3-767d-a342-f550d941d7c6

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f167-c8f2-7b42-ba68-fc7d922987b8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f167-c8f6-7a8d-8153-a3642be22299
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f167-c8fc-7881-8eb8-fc77b5b0b930
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f167-c901-7e88-a3e9-5fb49d489d3b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f167-c906-7e23-9643-11ed02db92be
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f167-c90d-7948-9fa1-f382610cb863
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f167-c913-7589-b01d-520da6b6bfde
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f167-c919-7a70-ae04-7a67c9fecc44

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f167-dfe6-7944-a5af-508809292e6c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f167-dfeb-729a-b206-cb123eef3233
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f167-dff1-79eb-88cf-d3a1d2e04e2c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f167-dff6-728b-b4e5-a54fac63e98d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f167-dffc-79b6-81bf-f3975e3444d3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f167-e002-7e41-abf4-b8272104794c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f167-e008-7eb4-8bb7-cedf4f5b7a68
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f167-e010-7d4a-8fc9-963c41790db7

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f167-f5d1-7027-8f79-7734c8cfe7d4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f167-f5d5-734e-9cf1-59bb35f496fc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f167-f5de-7fee-8f41-d4d9c0275f2a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f167-f5e5-7bfa-8cc1-b50f8e498e77
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f167-f5ea-7053-9f54-8e798cfaac8d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f167-f5f1-7aa9-8f60-04a56f5563e2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f167-f5f9-7b2c-ac1a-ebaa3a7367d5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f167-f601-79fc-8400-3dbfac6acb16

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f168-05f4-768d-9d22-b2a83d37da38
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f168-05f9-70f5-b4b0-034bf9ca815e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f168-05ff-77b4-b62a-fb48f347b022
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f168-0604-7294-9b4b-24542d6054b8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f168-060a-7bcd-baac-9df889eb346b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f168-0611-7520-b4f6-23b79cf9b2af
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f168-0618-7bf4-bb57-5a2eea405b76
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f168-061d-7f93-be8e-a911beabdf4f

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f168-216e-72e5-86ec-313246158892
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f168-2173-752a-9d1e-fc4a794a5e57
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f168-2177-7ae7-98e2-d3a08cce2bcd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f168-217d-78aa-b800-be910cf27401
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f168-2184-7465-aaa1-15e796043489
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f168-218a-7b0d-83b9-53eb3e76d2bf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f168-2191-72e8-97cb-4ada20a587a7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f168-2198-7545-8608-cf961b88a5d1

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f168-3856-71e9-8860-5c2aee8309e8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f168-3859-786f-89e7-c4c5e506eac3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f168-3861-7de2-9a92-c88dfa0f51be
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f168-3865-79f8-904c-9894499c5c91
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f168-386b-7b95-b75e-cfe75e846425
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f168-3872-7ed3-8c05-441051f504fb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f168-3878-7f26-909c-d0b1549dbe86
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f168-3880-79ab-a8c8-5cb4c82676eb

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f168-4a18-7661-b04f-caebd9279e1c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f168-4a1d-716b-b8f5-d56d81600029
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f168-4a23-76ad-b165-0acd42099d3f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f168-4a28-77f0-8c89-2ba2ac944bf6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f168-4a2e-78af-a895-0eaad3c64d4a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f168-4a37-7068-943e-012e778369c0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f168-4a3c-7f5f-ae82-16c368f45c46
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f168-4a42-7d83-9504-c5fddf534fe1

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f168-5e88-74f1-9260-5117649e8be3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f168-5e8e-75f0-91cd-d4dd8127e055
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f168-5e93-7217-b87f-9b550abea2c1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f168-5e98-7a34-bb96-17c616bde1bd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f168-5e9d-7ae9-9558-8db6c5fc5530
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f168-5ea4-71c1-8464-02eedb8126f3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f168-5eaa-7e64-be4b-ceb0e8a510ad
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f168-5eb2-7107-821b-e5ad552342b1

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f168-75fd-7d3c-802a-d58926bc9eb0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f168-7601-74ea-8c74-f5247228d43d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f168-7606-7451-9791-489c46f879c6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f168-760c-714e-914b-b1ebd0c459db
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f168-7612-7b64-9d33-2aae9f7da12d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f168-7618-7a81-af7f-82cb597e7276
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f168-7621-721b-b806-f119827ef779
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f168-7626-776d-9a4c-7322279a4c14

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f168-8ba3-7d15-98d7-162450cf19c2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f168-8ba6-7479-95d3-0fc410a617a7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f168-8bae-77a3-99b6-dcbe2cac16f2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f168-8bb3-7163-b0a6-3a6fca934c0d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f168-8bb9-77f7-bfbc-1d9fe8761e45
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f168-8bbf-7553-a37f-dc6ddd846a0d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f168-8bc5-7711-ace8-e8b7d72dde76
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f168-8bca-794e-a053-969dc0349a23

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f168-983a-7c58-98e1-e5e064b03fe0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f168-983e-7a9e-86f1-8a9687b64261
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f168-9845-7fd8-92ec-f445ef256980
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f168-984b-748c-a07b-7291ebe923d7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f168-9853-7593-9a97-92ad81c749de
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f168-9857-7f7c-9662-59d021e78364
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f168-985d-76b2-a569-386d2a815d78
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f168-9863-7fdd-97bf-8df80b733389

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f168-a67b-7727-8b7f-f9b6c1ba67f3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f168-a681-7bb6-aedc-d949fbe8f996
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f168-a686-7d8f-9582-86fd0aa10213
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f168-a68c-7030-90d3-2d5b55c20806
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f168-a692-77ca-a977-1af33eb0a2a1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f168-a698-776f-a966-7dbf7b1cba9e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f168-a69c-7654-a7fc-4c0713e2d70e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f168-a6a3-7dbd-8124-c12c4719d0ce

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f168-bf08-71e2-8ce2-2ae02b7b1d31
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f168-bf0d-7f3c-9595-1aaf411c4a16
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f168-bf13-7e7b-8795-a0e1357e28de
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f168-bf18-79e7-a9e5-b90d87763740
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f168-bf1f-7a24-86eb-66ed0ebd880d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f168-bf25-7754-8041-094cf3ef3960
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f168-bf2c-7074-b9d7-4b61e9a29f9d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f168-bf32-7fe3-b015-ec1aa1efc194

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f168-e358-7c33-bc1e-7609b7ec81f8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f168-e35c-7ea1-a371-d9ac80829e26
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f168-e361-7807-8f7b-a0a84d49153b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f168-e368-7c80-9f61-b1d761419b03
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f168-e36c-7710-be4f-b3968b410d6d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f168-e372-78fc-b2cd-e1018cde204e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f168-e378-7551-89b1-1ade2ffc9fd5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f168-e37e-71e6-9d4a-690b3ce8858e

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f169-0644-7e6b-82d2-22c875f68697
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f169-064a-798f-ad30-456313d045ca
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f169-064f-7bb9-83ed-2a392db4d1e3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f169-0654-7d76-a55a-4e59ad262cc8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f169-065a-78ee-b4da-750025d292d6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f169-0661-7124-a5d8-8530e1fa61b3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f169-0666-7e0f-9fa5-86944e9b4d57
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f169-066b-7745-88b4-c643261b30b8

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f169-1956-7d04-bafb-f7031a26eaf6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f169-195a-79b6-8e6d-ae284c604875
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f169-1960-7b43-b882-ef4b16ba1fbf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f169-1966-7074-8f01-c012e71b94ca
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f169-196b-7e40-b88b-7cade008f82a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f169-1971-7753-8663-ccbde3b7f2c2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f169-1977-770c-95a0-8b0c308d98a3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f169-197c-7b0e-a1e1-4546b74d399b

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f169-2c63-7a4d-b861-f020f4fc0032
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f169-2c69-72e5-a89d-41d2c3455862
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f169-2c6e-7b83-8e6c-30be5d78f47c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f169-2c73-71f6-b9e1-463ebabb4c38
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f169-2c77-762b-b283-8cbdb1f069c0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f169-2c7b-7a90-b654-15bb54bae8f6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f169-2c81-7f14-9f22-b0901afde0b0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f169-2c86-74b2-8818-8fbb4e9d64e8

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f169-4448-73db-be14-98aba9b5fc97
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f169-444c-79eb-8e5d-3e758ae59d73
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f169-4453-75de-87ec-62ffd087be0a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f169-4457-7f9a-b98d-507b44559580
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f169-445d-788f-94f2-9a51eed7aff2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f169-4464-7645-82b9-537876dbe5b1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f169-4469-7419-beaa-15ef0494913c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f169-4470-745d-a434-cfd11394fb8c

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f169-5d53-7861-94e9-b484ac897a0a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f169-5d59-7f58-bccb-fb4e4f6f73a7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f169-5d5e-70ef-8fe6-1e590084848a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f169-5d64-79bc-94e0-50ebc6523f6a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f169-5d6a-7cce-930b-41c9446bd35f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f169-5d70-791b-af12-9b4420724769
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f169-5d75-7296-a095-a5e7ac8984bc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f169-5d7c-7b5f-9b9c-b886c9637324

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f169-7562-7b0d-80ad-85fec3346837
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f169-7568-7964-8acd-435f7210a9fd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f169-756d-7356-91ff-de2eb03a28fe
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f169-7573-7731-b9eb-94a3d1b25c7d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f169-757a-777d-8de9-1420ef2f63ff
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f169-7581-7360-be6a-6d95f578d0de
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f169-7586-7fa3-885f-a3e6815d7ed0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f169-758c-7e3f-9036-a65baa9fc5e1

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f169-932c-7414-b8ae-80e3dceae0ea
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f169-932f-7db4-92b4-0f7dffd1a8df
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f169-9336-70ce-aa09-039db0d97790
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f169-933c-7665-9f3a-9da7eb788eb0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f169-9341-737f-a090-4826ec64d120
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f169-9345-7d8a-a0bd-b1a99264ef79
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f169-934e-72d5-af13-be02bca4cec5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f169-9352-7398-bb97-208101619d5c

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f169-af53-7bb0-a39a-274cf6691cd3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f169-af58-7ae4-9f80-cc387f8e5907
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f169-af5e-737e-8be8-578c0469b7eb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f169-af63-7346-a574-067c6f2d919c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f169-af6a-7c38-bd38-4d9214217836
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f169-af70-7de5-8d51-9a51bc0598bc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f169-af74-71f9-9e9e-fae282323f24
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f169-af7b-775c-9d40-6677eeaeef41

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f169-c86f-7c14-9c50-ba8c96251168
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f169-c872-7781-9d03-4e376a392cec
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f169-c879-7855-8b4f-c7884752f191
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f169-c87e-74db-8e85-4fab55ba7fe2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f169-c884-7ca6-bff8-93381870a600
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f169-c88a-71f7-a1e0-3a60363e7a0a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f169-c890-7735-a661-4e3b413e6616
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f169-c896-74e2-a294-f66790240358

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f169-e9d6-73b4-9dd5-5239374a1752
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f169-e9db-7c50-9f59-f408ff70e6c3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f169-e9e0-78f2-bfef-9a96c77c14a7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f169-e9e6-7658-ba2d-b9f167f0b28c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f169-e9ec-7816-aa39-fb1d5a462949
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f169-e9f1-790f-8467-06bbda6b0617
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f169-e9f7-7d67-b62d-682d740106cd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f169-e9fe-7d11-9e23-19826c0cae79

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f169-ffc7-78ca-885d-637dfbd3724e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f169-ffcd-7edb-9c46-e7746fe44a40
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f169-ffd2-7900-8608-407090797ea6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f169-ffd8-7a5d-9fca-3a7dd28c0900
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f169-ffdf-73e1-836b-da7f87fe3b13
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f169-ffe5-789b-9563-716bb78342ee
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f169-ffeb-7b56-af2e-179e955a6a90
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f169-fff1-797b-a415-7e085f3eca7d

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16a-0e35-7dd8-a7c2-e8db5e0f8520
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16a-0e3a-7e03-abc4-c7668a1e3ab5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16a-0e40-754d-8e91-b1b534c563a3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16a-0e45-7c86-a922-cece4c62e323
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16a-0e4c-776b-b2fb-8a69494e08ae
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16a-0e52-7fd5-8773-c11a65ecd3e0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16a-0e58-7045-9d78-bee567c1154a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16a-0e5e-78fe-8737-cd4e2381d44b

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16a-30f1-7273-96b2-b55828046877
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16a-30f4-7f16-a80d-48b318fd4997
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16a-30fa-76cb-83bd-a464eda303df
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16a-3100-7839-9f6a-83cfd4a1d687
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16a-3105-7bda-8441-1487fa4e4600
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16a-310c-7f13-843a-bb25e674411f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16a-3111-7d6f-b6ce-aa95021d5a38
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16a-3118-749c-8c36-0246c83f334f

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16a-4048-795b-a92c-15af36246dca
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16a-404b-74e2-afd5-aa9b1cc1fb25
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16a-4053-795e-8061-8c5420647f4b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16a-4059-76c6-8b71-763873633c80
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16a-405f-713c-b7fe-af0a94dc5a54
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16a-4065-7b2c-ba8e-6c67d8af359e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16a-406a-7469-98e4-e298903cdb9e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16a-4070-74c0-b671-c772f1c48b44

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16a-570a-723d-9b31-f4e04eb92d96
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16a-570f-7459-8aa5-6bca3cff1f06
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16a-5716-721c-b5be-bf787a08bf08
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16a-571b-749d-bf9c-2c7356361d64
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16a-5722-7119-a4d3-1b5bd897970d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16a-5729-7ff5-af92-f535a66a9889
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16a-572f-793c-ba8e-dc272ee01967
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16a-5736-70e1-ba22-98437e00f806

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16a-654b-747d-9707-7109d88518ab
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16a-654f-74b7-bd0b-9669bed0379d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16a-6555-7944-8040-06284cb39bf4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16a-655d-7c2e-8570-0948c0857ebe
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16a-6562-7c80-8f82-b0c0d1af1f64
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16a-6568-713b-a6a0-ed093aa525be
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16a-656d-7e09-97eb-305356f63852
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16a-6573-7267-8583-46e62a51fbfb

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16a-80f2-779d-b37a-d63e0a87c81d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16a-80f6-7114-9ea8-ceac9ed1e0b8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16a-80fc-7fc2-94c7-ffb27794ba84
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16a-8103-7430-99e7-992a96abf6b0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16a-8108-7d49-95ca-a30163d6bea3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16a-810f-7bc5-8490-0435f4b26e4d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16a-8115-740b-ba82-fea2c69b52e7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16a-811c-721d-9589-504c441d664b

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16a-9355-7739-a6cd-88197873630c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16a-9358-7d91-8539-12acabddd7d3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16a-935f-7228-918a-8489857b9635
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16a-9364-7ce5-9773-eccc6859e636
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16a-936b-7b5e-98a9-3c0d643cae8b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16a-936f-7bf0-9061-b876f294f39b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16a-9376-7ac2-a374-3eaeab655a52
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16a-937c-732c-a418-31759fb4766d

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16a-a530-7360-a9d8-202c345d9a6b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16a-a533-7f0d-8d5a-243cba6db3d5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16a-a53b-71cd-a1e5-d95e6c77dc44
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16a-a540-7174-ab44-0e0e4a8367bd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16a-a547-76ea-9b97-8b3419057432
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16a-a54c-7784-b550-fbaafbb21495
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16a-a552-767a-8899-800ea8e7b7bc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16a-a559-771f-b0ae-299a958bfcf2

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16a-bcc6-7886-9c19-33e81ed3d36a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16a-bccb-7c5b-b97c-304aa93b5fa3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16a-bcd0-7ee0-819a-c863b4cccd08
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16a-bcd5-7510-9a63-523f6d1bb428
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16a-bcdc-7a60-ba42-c1e203f85627
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16a-bce1-7ec1-b71b-fecfaf96aeeb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16a-bce8-79d7-a7b7-84dbe505503c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16a-bced-7897-9398-ddd5bb785705

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16a-cd11-7615-bb9c-0408f27414cd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16a-cd16-7e18-be45-7258ddc993a2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16a-cd1d-7fc8-bbe8-ab5c07273833
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16a-cd22-72f2-87cb-78435255ebc7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16a-cd29-77b0-bfe9-468ddf242fe9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16a-cd30-72e2-b175-623df0a6519c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16a-cd35-7a01-b681-fc2ca7e84d57
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16a-cd3b-7e27-877a-b9ca1b06e97d

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16a-e7be-76c7-ac60-3f454b495e06
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16a-e7c2-70e7-bf59-d53886cde9c5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16a-e7ca-742d-958d-258b735ce07d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16a-e7ce-7fb5-857c-c76f6bf9c74d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16a-e7d6-7de4-ac42-4f8d38103fe8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16a-e7db-77f6-a124-adab9fc0537b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16a-e7e1-7278-9e98-4b94a5e4456b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16a-e7e8-7e59-a2a7-a5cdebe03e67

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16b-0008-7a73-898e-c1fd9f5e635e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16b-000d-7f03-8a38-2b1e2bf06486
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16b-0011-730e-bbf1-78af0225f80c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16b-0016-7c24-b2d2-4c2536292fe5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16b-001d-7d3b-a602-bf96ea5ec271
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16b-0022-7804-bb70-e2f58659a382
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16b-0029-77dc-9e5f-c866d078a3e8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16b-002f-7587-9b46-bbd175c6d0b0

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16b-1911-7679-8654-6eb1cdc7e1e2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16b-1914-7170-b917-be7dbbdc5f39
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16b-191b-7915-b60d-3d7446d2cf37
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16b-1922-7a37-823b-f6f12a1b0d58
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16b-1926-7ee8-9ae9-b1a7bfaa0863
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16b-192c-7d97-a97c-ac18b11ad1ae
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16b-1931-7b7f-986d-01ebd432ca46
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16b-1938-7255-a870-97d17204d79f

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16b-2eb8-713c-a7c9-916d6e859e63
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16b-2ebb-7540-b22e-ee1142594e8a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16b-2ec2-7342-80f0-70a3c1a90e82
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16b-2ec8-70c7-bd65-c01710b8277a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16b-2ecd-7b3a-b114-96d97c2a731a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16b-2ed4-7a90-a7ef-813a486cf0f8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16b-2eda-79ad-ac45-39e0f8997879
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16b-2ee0-7b3c-a826-a0990d43bc5d

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16b-5438-7f16-8e8d-7e76f470c0f9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16b-543c-7db7-b303-373eae920319
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16b-5443-74e5-ae95-8840c2de6ff4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16b-5449-7880-9782-232c7406cecb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16b-544d-76e8-99f0-ae32a426466a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16b-5453-79cc-a594-326738addf59
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16b-5458-734f-8f5a-afb2b10b9000
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16b-545e-748a-80aa-1d4900fa8481

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16b-6f84-788a-b07d-011de4d2c05b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16b-6f87-74fb-a14e-14450aef8d4b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16b-6f8d-75e7-81b4-120b2145fd1a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16b-6f92-7d21-886c-a0a734f81626
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16b-6f99-7610-a818-2a911b73e61e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16b-6f9e-70c9-864f-10e8b7fd6b63
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16b-6fa4-7cc0-9c91-eee1eef21572
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16b-6fa9-7257-ac12-376f4b8aa893

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16b-7eb5-79a7-8459-1c7f1317fc79
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16b-7eb9-7f91-959c-78331b81099f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16b-7ec1-76ee-b236-c8ec5ec90263
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16b-7ec8-7e1c-90d2-279203bc0f3a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16b-7ecd-75bd-80da-407ac816975c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16b-7ed3-75a8-809d-7400f6d7be23
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16b-7ed9-78ee-b655-1f4111d5400e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16b-7ede-70e6-9501-35e59acdd340

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16b-9d6a-7d5b-bd75-6fc7a794981c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16b-9d6f-7413-887f-81136a98b5e3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16b-9d75-74b4-9fde-378e3cb358a4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16b-9d7a-7c56-ad6d-67a4bbcaaa27
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16b-9d7f-776a-8748-d6fd9cae3b3c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16b-9d85-7fb1-9763-27aba84cbe6b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16b-9d8c-74db-a3de-28dd8b595719
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16b-9d92-7f60-8f0d-41549178cde0

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16b-b217-7a7e-9844-4d69126fe91b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16b-b21a-790b-98b9-89efe1fe3d3b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16b-b221-7b70-b1ca-4182b2fa165b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16b-b226-7274-afa4-5bffcf8de13b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16b-b22d-7b38-82ef-734158dc4988
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16b-b233-728e-9c60-a6704d63ea46
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16b-b239-7dee-9925-9616d68bf11e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16b-b23f-7b74-ab85-99da676eccbc

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16b-c984-709d-ba7a-1e6ba9090021
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16b-c988-71c7-a770-8c8dbae0650d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16b-c98e-76c0-afcc-c5190694f55d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16b-c993-7a66-a38f-f0791a3adb5c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16b-c999-7bf7-ba63-08d3edbfc912
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16b-c99f-7b87-b51c-2211b5e2f1b1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16b-c9a5-75de-bb96-608cc082f8bb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16b-c9ac-7fef-8532-41ae7476015d

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16b-df4e-7696-8a49-42a55906072e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16b-df54-7ca8-8975-0a3fa6166f65
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16b-df59-77d5-955b-75c23869b41b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16b-df60-7436-b026-477bad852ba4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16b-df66-70bc-af5c-6a0399815bb8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16b-df6c-7932-b2ad-2ac6d53859d7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16b-df70-7d2d-b909-b07fcc28a062
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16b-df76-7c2e-bbdf-84470658759b

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16b-f5fd-71ce-91a9-e0fde64154e3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16b-f601-7603-a06b-99448d685c48
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16b-f607-7890-b9e1-5144c37fa6e3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16b-f60e-785c-ae93-13b426d11351
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16b-f612-7349-9426-72c6ff3048a6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16b-f618-7480-bb08-ecbc8573b882
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16b-f61c-71b0-9596-6c217018ce16
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16b-f623-70ac-bda2-0d9185fd68fc

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16c-0e25-75cf-a8c6-11801db40048
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16c-0e28-7917-91f7-16462c90712f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16c-0e2f-7e12-ad0a-10c49dec8a46
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16c-0e35-7a62-acb4-88b5f75813c8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16c-0e3b-73dc-a18e-521346113d82
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16c-0e42-759c-9335-906a7ee6174b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16c-0e47-79da-95fc-4c20a512427b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16c-0e4c-7eee-a3af-73b461cecdbe

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16c-2c66-79f0-b97f-e6a5014c909e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16c-2c6a-7981-b0e2-bfc5e8ba92ad
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16c-2c6f-72d0-b3b7-eed469ee7a12
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16c-2c74-7614-9c4d-ad603c1d8ab2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16c-2c7a-7eab-a85b-1f02071b5017
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16c-2c82-7b66-8872-d1dae70e2b8d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16c-2c88-7502-baee-aab990d7e984
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16c-2c8f-78dc-a7b7-31851a908e1a

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16c-3fda-7291-8742-2fecc01b62be
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16c-3fdd-70d6-805f-7bd9303920db
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16c-3fe4-78c6-b605-50e730838f36
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16c-3feb-7ac4-80af-68be14b607bb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16c-3ff0-7142-86fa-a2c8ed5a2f4f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16c-3ff7-7b3f-b670-bc8dae06c3f1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16c-3ffc-72cf-ba7d-5e7552e3882a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16c-4003-7ff8-ba99-bc62acd19d28

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16c-557a-706f-9341-c9f5795cbccc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16c-557e-7fb9-bed6-d9b26236fda6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16c-5587-7eda-8e04-6db75a920e49
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16c-5590-78f9-b23e-c88d6a66cc4e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16c-5594-7756-854d-0fc7c32af237
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16c-559b-7363-89a9-645781b339c9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16c-55a2-70de-9af9-eceffca4fc0f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16c-55a9-7cde-8f8c-998b249fc9f5

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16c-6242-77d3-820a-5cfa36100a78
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16c-6245-7ed8-95c5-0d0a766f873f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16c-624b-776c-8200-ff2ca279cbca
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16c-6252-718d-bdfa-c39724ee9e3d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16c-6258-77d1-a31f-01a88c7b7dda
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16c-625e-7c8f-ad4a-63e6ae56b1a2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16c-6265-7538-b1f6-e42220395e3e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16c-626d-7516-9cf5-2aae6f5a309a

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16c-7d28-7d29-a187-bfcd41f88d95
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16c-7d2c-7f67-a2a7-15ab031f8153
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16c-7d32-7a70-affc-2e9702dde1e2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16c-7d37-7ba5-8553-73c778eb4901
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16c-7d3c-7386-8e98-19676650624d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16c-7d42-7228-b48a-3cf346319cc3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16c-7d48-7b98-a6f5-8ce76fef7409
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16c-7d4e-75ff-a6e6-67015b6ed0d5

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16c-9225-7d33-9060-da31e1ec2d7a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16c-9228-7e82-87b3-4a1a86e9edb3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16c-922f-7dfb-94d1-8ab90e8ee36e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16c-9235-784a-82f9-14af744fb9c4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16c-923a-73bd-a5a7-b34fa7075792
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16c-9241-7a43-8727-9f734a207b4a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16c-9247-7ea0-804d-244dde8876ae
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16c-924d-7608-90d6-3f00e21d7f99

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16c-a8c3-7c89-85ac-6942b48cbf94
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16c-a8c7-718b-8742-e3b78650f422
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16c-a8cf-70a5-94af-1147ddfd6334
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16c-a8d6-7cdb-b714-ae3634632d30
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16c-a8dc-7bc1-8691-445c7e96bb48
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16c-a8e3-7aa7-a8f3-c205b45edfde
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16c-a8e9-7a50-ad9c-10d163a18ae0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16c-a8f1-7d6b-b71a-81a40f60a477

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16c-c177-7fa2-9f69-7034928b0d81
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16c-c17c-7a04-ae80-6d90f9d39314
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16c-c182-7428-9a65-7596e893fff9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16c-c187-7996-8f0f-bbc958457707
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16c-c18d-76b4-967f-05448b80e03d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16c-c193-7763-9175-3225b1480603
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16c-c199-7244-97d9-0dc15adaecaa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16c-c19f-72c5-817b-24088300a88c

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16c-d510-7b7b-90c6-cf860fea21ee
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16c-d513-7d5d-9294-b19debf30159
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16c-d51b-7263-b342-29c41d542ab0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16c-d51f-7b1b-85fd-3a1a6cec2d5d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16c-d526-7f2b-b08a-4bb31822c552
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16c-d52d-756b-9dec-00f2180bf596
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16c-d533-7090-8701-3ddd09e41f26
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16c-d538-7c95-a64d-314af0748a1f

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16c-e5ff-7662-913d-d44cd1bdbe4b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16c-e602-7eea-9faf-791120e50043
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16c-e609-7926-be74-ce19010d3799
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16c-e60d-7fde-a5ff-495450610464
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16c-e613-7664-b7dd-388198ac7458
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16c-e619-7539-af1d-339ada218cca
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16c-e61f-730c-896c-a8dd4bf8e476
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16c-e625-7c59-ac26-6f63eea9d393

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16d-0506-70ae-bde3-35bafb74f1f7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16d-050a-7ffd-b2c9-1f8310232d27
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16d-050f-7532-acf8-b919b4ab2571
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16d-0516-7bf8-a14b-a08bae03e464
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16d-051b-7375-bfd1-e7fb62ac800a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16d-0521-7c39-b11d-86e63cba867e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16d-0526-7306-b3d1-28e1cc379b00
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16d-052c-7a4f-87ea-5623c5a9b13e

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16d-17e0-796c-b65d-0dc474b57960
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16d-17e6-7f5c-9526-68cc32d0c1d6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16d-17eb-7835-9cdd-4b1637682c0a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16d-17f2-71a7-a8d9-c26e2a329de8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16d-17f9-7f60-bdf1-b64f58433024
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16d-17fe-7a6d-bc1c-a0183a0830f8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16d-1804-7a85-ba73-868d13150d29
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16d-180a-7610-9c08-ba3172d2b847

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16d-3413-7366-bc81-fde94b7d48eb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16d-341a-7699-bfd8-0cec0316b55d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16d-341d-7dc4-9940-b93dd918b432
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16d-3422-7c4d-8964-d4bc35dcd52c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16d-342b-7e3e-a3dc-427635c375bf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16d-342f-7016-8da4-1c261a63315d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16d-3434-74cc-8bd6-c40bc28b759b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16d-343a-7ca4-8d67-c7afe6edecf8

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16d-580c-76fe-9df9-15c80f5998ed
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16d-5811-7526-9c4f-25ee09e997d4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16d-5816-71af-b4fd-61bc71dec5ee
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16d-581b-7cf5-84ac-31714afd5782
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16d-5821-7ccb-92d3-b9007c6dd647
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16d-5828-7d87-93cd-6ca52beec846
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16d-582d-76f8-bd78-1488d3bc8c09
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16d-5835-7b5f-a9e9-4d057ada8512

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16d-7243-777f-b3b0-158b60abc101
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16d-7249-73b0-aba0-fa8b03c7f444
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16d-724f-7f50-8ff3-221588474c79
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16d-7256-791a-90eb-8169925bcff4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16d-725d-740e-a69a-550c350e982b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16d-7262-7365-a6f0-623e79359771
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16d-7269-72e1-92a0-1c355c030502
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16d-726f-70bf-ab8a-aee2b3f4a62a

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16d-8908-7945-be75-1c40986e1a6a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16d-890c-7a6d-9502-1439e25b480e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16d-8914-7c3e-8c21-95a3e8ac4770
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16d-891a-7d6f-8235-0c4d0d8cb441
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16d-8920-71c5-a5b2-18f02adbbb5b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16d-8925-7ddf-856c-4f1338b2cfac
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16d-892a-7d3c-813e-88aed1185fe8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16d-8934-7225-86ab-83de3805cd67

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16d-9a96-726f-a6ae-c9e474c55535
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16d-9a9a-76b7-8d93-850e30150b86
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16d-9aa3-703e-8cab-e66416935c9b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16d-9aaa-74ce-809b-0cead55a18be
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16d-9aaf-7eed-8578-28b724d7c473
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16d-9ab7-7159-9329-86772a9e2f46
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16d-9abe-717c-8456-c6190fe8e953
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16d-9ac4-7b4a-ad8c-3084d1f4da01

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16d-b24f-77fb-b54b-b17c07f87005
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16d-b253-7515-a7a6-06336f84ba6c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16d-b259-7250-9945-5da616047a69
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16d-b260-7e53-925c-860c618050cf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16d-b265-7fa3-8c0d-6f3355c0c0de
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16d-b26b-79a4-a9ea-2ee7960a0c18
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16d-b273-7988-8c34-91aae826a7e7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16d-b278-7131-bc63-7ecd76385047

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16d-c7fb-74fb-b946-9622abc2b7cb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16d-c7fe-7c48-b834-a825f9df16a2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16d-c806-75c6-be02-61368b2d1485
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16d-c80a-7c75-97da-119e1cede9dc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16d-c812-7a71-9e4e-9176bd2dfbc0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16d-c819-768b-a84e-c99242ee0548
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16d-c821-72f7-bd00-3e9848ce9fe2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16d-c825-7576-900e-8126128ab5b8

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16d-dae9-7908-b6e7-10734bad5e24
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16d-daed-7556-809f-c8c76a768d63
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16d-daf3-7ce7-b5c7-b1674879cd58
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16d-daf8-7e02-8f41-8cd68250bde6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16d-dafe-7143-a69a-fe88fecf348d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16d-db04-7cfc-b96e-d381a7b89ac9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16d-db0b-706b-9c62-0c1e10f15469
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16d-db12-7409-9ab8-01409547f7e4

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16d-f33e-716a-b0dc-0e6030e57abe
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16d-f342-76d6-ac2e-8e6a9c253b64
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16d-f347-743b-9b64-fcba69a6080e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16d-f34e-79a1-890c-07f8def435f9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16d-f354-7233-81af-200152cc1b3f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16d-f35b-79b0-b2c0-c4ed0c6bd5f1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16d-f362-7ecc-8b8d-33963ff0f6fc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16d-f369-717b-8625-74f8a51a8f3a

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16e-0eca-78cb-ac86-d7ac92033dc1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16e-0ecd-7f2b-88a6-dee26de7b159
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16e-0ed6-7113-9a55-f8eccae27385
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16e-0edc-71f5-a0e4-b4be121d8768
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16e-0ee3-70e7-aeb7-be743b316abd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16e-0ee9-700e-9b9b-0e74513ca1e8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16e-0ef0-757c-949c-d361b19c30c8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16e-0ef7-7ff9-83d9-9a2147735c19

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16e-2198-7fa2-90d4-93b0d360c879
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16e-219d-7c75-980d-4ec549f8db3e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16e-21a4-7725-a7f4-ff8aa56f5c8a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16e-21a8-7faf-a5db-e9f5d4c43290
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16e-21af-7c84-9460-703aa07b398a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16e-21b4-78ff-9f57-57a321e68761
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16e-21bb-7523-a712-e5c741f410f1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16e-21c2-7e2b-ab61-625aea29b559

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16e-3889-7de0-aeea-ead5334e00ad
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16e-388f-79cd-b4af-78919dc1ba40
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16e-3894-75bf-8ca3-e9c4c291e3a4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16e-389b-742a-be0d-675e24128194
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16e-38a1-7f6c-bab7-af1714927996
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16e-38a7-74da-8fcc-8460ed68d7ab
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16e-38ac-7c0c-9afd-bccaae6e66d4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16e-38b3-730f-a266-477a31d3b1e1

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16e-576b-7bfc-91d2-c980c97c2233
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16e-5770-70f3-9df8-733592e43733
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16e-5775-73c3-93aa-202782f9c705
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16e-577b-783b-90a6-b1d050c63732
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16e-5781-7400-b0cb-a9971b87a187
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16e-5789-7e1d-98c9-6182bbccb554
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16e-578d-75ac-bd5e-e88dc40b7bb1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16e-5792-73d4-aa70-3708fcd820ac

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16e-7de6-703b-bbd7-d44bedaa6b46
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16e-7dea-763a-8835-7eff512dd0e1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16e-7df3-79c1-8863-da151d50f795
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16e-7df8-76b3-8cbf-1a7863e01904
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16e-7dfe-79c5-9921-d3be9d980df1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16e-7e04-71ef-b160-9d3daf5ff760
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16e-7e0b-7646-a338-66626418de7f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16e-7e11-7a5c-b2a8-88bb187875c9

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16e-93cd-7938-b49c-145f7cd88f08
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16e-93d0-7419-975f-191097b2a7e8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16e-93d5-7597-ae0f-e7cf1ef9a91a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16e-93db-750f-932e-234773b10c83
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16e-93e2-7533-a75d-312306b97afd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16e-93e8-711b-9f29-648f882b1a27
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16e-93ef-71f6-b671-091fe822d37e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16e-93f6-7c57-8a27-17ed93708376

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16e-aaae-779d-92f6-4685be3b0c9c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16e-aab2-7f9b-94b8-b5355e58ed89
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16e-aab8-7073-b107-dea261b2787e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16e-aabf-76c3-ad02-04fa11eb5849
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16e-aac5-7a70-a4ec-b555d97091ec
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16e-aacc-7133-98f6-c771c1849129
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16e-aad2-79a4-a9c6-d465809e98f8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16e-aad9-7ce5-b8ba-b593dca2cb21

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16e-ca61-7267-b82f-76ca4be24ebf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16e-ca66-76c5-a613-20dbdb4131a1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16e-ca6e-79b3-b2a3-390586667536
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16e-ca74-7cea-8c7d-dca05153a194
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16e-ca7d-70a2-b1ef-a63f3f18624a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16e-ca82-7d07-816c-35ddea08ce1e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16e-ca8c-72cd-964c-2c6a4fcaa5ef
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16e-ca92-79f2-b725-1ca23d0abf75

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16e-e0e7-71ec-8bb4-3e2a6a85703e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16e-e0ec-7741-b59e-4dc3f5e72fa3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16e-e0f4-74c2-bb29-4808c52178e9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16e-e0fa-7216-a034-014171e5d75e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16e-e100-7c03-9772-22c93fefd6b5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16e-e109-763e-aa39-495d89115ce4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16e-e110-7df8-9fbb-51ec9244d7e4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16e-e117-7d0a-be5c-291cb915540f

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16f-0318-7112-b0ac-295c9a78675c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16f-031c-7a37-93ee-7978da96ff88
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16f-0323-73e8-967c-d7823ebd0aeb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16f-032b-7651-9577-250a926a6f73
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16f-0332-7a44-afa1-c01c93ba15a7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16f-0338-7c0c-86f5-d7dc48b22df5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16f-033e-75b6-987a-73e898abd026
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16f-0345-71f9-bb8f-a8f30c7df8ad

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16f-1b83-7c94-b41b-7db9d7d8019c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16f-1b8c-7e66-9f84-3b7a91008d09
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16f-1b92-7eeb-b1c6-bff2f8a71d44
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16f-1b9b-7a37-87ba-5cd2cb5f0eb3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16f-1ba5-7045-a9a1-d7e8026858b3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16f-1bac-7fb5-b18d-7d58c6acf4c7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16f-1bb3-7eed-8688-1ed0e52924a0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16f-1bb9-7ed1-bbc5-cb74c667fc6c

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16f-2f7e-7196-a608-5ed4f2eac148
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16f-2f82-7241-a475-e01f4877c642
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16f-2f88-72ea-b6c6-7ef0453679df
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16f-2f8e-78b7-b3cf-3aaaafa158da
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16f-2f94-7307-8315-ffb1ece52b7b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16f-2f9a-7df3-8b19-ea51e6a11711
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16f-2fa0-7eb4-a274-029f8a348c5d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16f-2fa6-7b3f-802e-f4a1adfd5351

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16f-480c-7a11-afe8-6e8598cab0e0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16f-4810-7605-b485-ffc6f5ef41c3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16f-4816-7c2f-a8fc-0883ce5e5759
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16f-481a-792a-9ea7-1f3b25eab986
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16f-4823-75c5-bf71-8cc48a50b1a7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16f-4829-7f52-9a99-491c9afe49d5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16f-482f-7d4b-9a98-57ccc9f8ab74
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16f-4836-76d0-9f75-bc60a29254c8

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16f-6014-748a-928e-a9e4b1bd6735
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16f-6018-7f75-9dcc-86b4905ef22a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16f-6020-744d-989b-997c241161df
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16f-6028-71ab-b89e-f6d93efabb97
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16f-602f-7172-a1b1-d190eb494899
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16f-6037-7c81-a977-baedf6c0558a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16f-603e-729e-bf89-a2c216fd7ac9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16f-6045-7e33-b7f6-16cb50c3f793

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16f-76e2-7be4-9d56-02230f42ec94
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16f-76e6-7fce-803b-682f5d067f34
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16f-76ec-72bb-8df2-c76553d5ff78
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16f-76f2-7df8-b909-b74370ed2ec1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16f-76f8-7098-a069-6e4881b1c0ac
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16f-76fe-78dc-97e4-0b53a6233f8e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16f-7704-7df6-9f7d-d61a535b5fdc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16f-770c-7b84-9647-4075c6402208

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16f-88ba-71a0-93e5-82717fe475cb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16f-88bf-78cb-89f3-b042a5457d20
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16f-88c6-7c54-a7df-c6fc91a84945
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16f-88cc-76f3-b48d-56f60d7387f8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16f-88d3-72c9-ae65-4064a0e29f07
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16f-88d7-7169-a3fa-5953b8a83094
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16f-88dd-71c2-bcc3-440a25af57b2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16f-88e3-7ad0-90d6-435f0673e400

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16f-a4d5-7ddf-bc48-c5ce51524939
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16f-a4d9-7a66-8c1a-08355d0b3a88
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16f-a4e0-7a18-979e-1d5198fd3f94
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16f-a4e6-7a7a-91b3-da5cd19aaa54
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16f-a4ec-7eea-95ca-081086dc8147
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16f-a4f2-7b47-ad42-03510bec1bb8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16f-a4fb-7b8c-b502-eba6072cc118
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16f-a501-7865-97e1-cc9c084b9fe4

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16f-b3e4-7532-a190-ce7ec57e10ff
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16f-b3e8-7b12-a824-2a1f429906a2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16f-b3f0-797a-bbc3-efb1b11e3674
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16f-b3f7-7e4d-b544-b3347358e781
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16f-b3ff-7338-a85a-1ac93b66ba8e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16f-b405-793b-bd30-39868264ae02
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16f-b40c-7cb8-92fd-ca2361bd28d7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16f-b412-7600-9535-6d9250f86e8a

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16f-ca06-764a-a01e-eac5e7f7ef28
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16f-ca0b-75c7-ba0f-e4df1b09e846
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16f-ca11-70db-a44e-d9674c673d96
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16f-ca16-746f-b573-0352d575d14c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16f-ca1d-74ac-9f9b-776b59ecc270
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16f-ca24-7537-a49c-18f8a400abc6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16f-ca2b-7ec3-a5c2-487796cdcb58
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16f-ca31-706e-bc7b-36a8f7b13a2a

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16f-dce1-7d01-abd3-6ea4859eb07a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16f-dce5-70ed-aec8-3a6038f22f61
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16f-dced-77e0-9e19-93f3db91d4c4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16f-dcf3-71b4-836f-2cc63717f5e9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16f-dcfa-7869-9ceb-e4754f75e566
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16f-dd00-7570-af45-39085e1ee571
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16f-dd06-784b-a3f7-38f0b161651b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16f-dd0d-7291-9f25-a784867c7633

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16f-ff19-7529-87c3-b96e7a8e6f63
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16f-ff1c-721b-9c35-5b57564c64b2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16f-ff22-7a3f-ad3f-8424520c7271
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16f-ff29-713c-8b15-f3fd82256b7f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16f-ff31-7c15-a5ac-aefe5bbd61c8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16f-ff35-7749-8913-acc1dbe5bea2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16f-ff3b-78dc-8769-84741bfe98c3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f16f-ff40-735f-beef-fdc2be102087

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f170-163d-7847-8884-565000454d8f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f170-163f-7001-b2a9-2173ca203aa3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f170-1647-7327-8ac6-322db525d553
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f170-164f-72d3-b4fc-36519ef5ca04
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f170-1654-715e-86ae-874147052ae5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f170-165b-7cab-bd91-c78a6e808ddb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f170-1661-716d-bb05-14761f8f8031
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f170-1666-7f5b-b416-4666ddad3c8e

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f170-218d-70ba-8de9-74d8ce723788
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f170-2192-77a4-8a3d-2ca2de56de25
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f170-2199-75c8-adc5-f02965f19ee6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f170-21a1-79a0-9b0c-2b434ccfdf4a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f170-21a7-7a81-9ee4-1cdb6c19cb63
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f170-21af-7dd5-b539-2ccf49a0add1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f170-21b7-7601-a555-721d9a2c15e9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f170-21bd-7ed5-8573-697f68376cab

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f170-35bf-7238-bf11-4443f444d5eb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f170-35c2-7c91-a4be-caa01260ce7d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f170-35c9-7ac6-9a6d-18107499d994
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f170-35d1-765d-b5e0-030ca83da7e9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f170-35d7-7827-a911-49c8c6829c36
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f170-35de-77b8-9b0c-192391fc1a2b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f170-35e4-7d9e-8b3b-23fdce96f6e2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f170-35e9-738b-89a5-706cec066f42

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f170-5c96-7d7c-a2ff-9020c2773b25
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f170-5c9a-7215-8196-ec584cd9bb39
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f170-5ca1-7cf9-ba48-56fa33aec48a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f170-5ca7-7b8a-a1a0-c61e58323661
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f170-5cad-7f82-a244-8be70115494f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f170-5cb3-740b-b79b-a863ab5d62ed
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f170-5cb9-766b-bade-5d34fd5a67e8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f170-5cc0-72cb-aeda-26933667630b

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f170-7ace-7151-993f-a3ff89a91fe9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f170-7ad3-73e0-8941-1e26c5ee3577
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f170-7ad9-7260-b8c4-b3ec4f17440f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f170-7ade-7275-b7fa-657a082298e8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f170-7ae3-75b4-b8dd-df277dfffeab
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f170-7ae8-788b-a876-8d8770e2d6ed
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f170-7af0-7ced-98a9-0937136c8389
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f170-7af8-797e-a9cf-660b927ee835

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f170-8ce6-7287-9d88-cd967742c189
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f170-8cea-7e77-9d1a-9de033e17cb1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f170-8cf0-7e17-a1e0-7c10a1e4f64e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f170-8cf6-775b-afdf-39612ac1dbb1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f170-8cfd-7687-bf0c-cd378016bdbf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f170-8d05-746d-8ef7-3ac8eef951e5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f170-8d0d-73fb-b315-fc306e0f657d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f170-8d11-709f-bedd-7ffc6fe69658

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f170-9c6e-76ff-bc87-cf310e51be96
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f170-9c72-7eff-b22c-cd5a377b2cbf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f170-9c7b-7749-9314-13191c33871f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f170-9c80-75c2-afa4-2176d6585801
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f170-9c86-7243-9b74-790ad2ad6652
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f170-9c8c-74eb-805f-d4015843587c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f170-9c93-7e4d-94b8-9c4152b7b88f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f170-9c99-7887-a7d2-4b59753bb458

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f170-b274-7585-9f01-af7f82896f8e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f170-b277-76d7-acfa-f8838cbf9ef3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f170-b27e-7fc8-8338-531b36ecd7f7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f170-b283-7e18-8262-01c33c487c01
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f170-b28a-7274-a845-843778c8770e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f170-b28f-7da6-8b5b-5608988d92f7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f170-b294-7234-940e-b5a5cec31303
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f170-b29b-7d65-b14c-cf0021917a77

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f170-d81a-7f64-be88-b2fdf4440deb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f170-d81d-72f5-ad23-d5e7b5d92325
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f170-d825-7cc5-b120-23f77d052187
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f170-d82c-7439-9af6-b423457e47f8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f170-d834-7ae7-a279-d74afacc6749
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f170-d83a-7d70-ba44-4da352234340
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f170-d840-73b8-95d8-352b01e37392
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f170-d846-7006-a2ad-931293f09ff3

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f170-f817-795b-9c3a-fa8e35164c43
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f170-f81b-71dc-ae19-4d7dbe684169
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f170-f823-7e35-a2b9-a6df0e4d6ed9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f170-f829-7d95-9926-70ce8d24e279
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f170-f82e-7c43-a65e-f8330919fb02
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f170-f834-7468-a804-a0246bb68553
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f170-f83a-7056-a4fc-4cc4fce8b8e6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f170-f842-7e57-801c-d718e8cadf3e

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f171-1179-7f5f-bad7-246ca040647b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f171-117e-79fd-9919-782394ceed90
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f171-1183-7e41-9b53-0ed1460d57c9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f171-118a-7f13-9499-75c9990da8b3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f171-1191-76a6-9ed1-7998a38657b1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f171-1195-745d-a008-e3b44301d36d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f171-119b-7218-b217-a88154ff4a0f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f171-11a4-7d65-a464-40f8ba0fa7eb

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f171-2d07-72c0-9478-87049da55ebb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f171-2d0a-74af-bfb7-6a0353bc69b0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f171-2d10-7c2b-9bca-9105fede5dd7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f171-2d15-78dc-a9b5-2f710ec0fba6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f171-2d1d-717f-9c3d-814e02545e7f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f171-2d22-7d2d-80b8-974ab0a8a235
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f171-2d29-7b08-9952-973d91e7c8e6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f171-2d2f-77ee-bdc8-1e97d995d529

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f171-47ec-7326-86fb-1d21563d67e7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f171-47f0-76eb-9460-1fb4e25e11bc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f171-47f7-73ff-9dc3-01418b76a98e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f171-47ff-786b-b0d1-d0f47a543f01
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f171-4805-7d6a-8a68-3f0a5341854e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f171-480b-730f-bd0c-50d2549068b7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f171-4813-7206-9d06-3ba8457ddc15
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f171-4818-7303-9f03-a04cdee43590

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f171-6dfc-7252-aba4-08e0682ececa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f171-6e00-7dc3-8a94-55cd89b5cbde
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f171-6e09-7747-aa29-31d5a76bcea9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f171-6e0f-7d46-8344-e250e6f9e9e6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f171-6e18-793d-936f-240860aa575c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f171-6e22-7264-96b4-0988016f4779
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f171-6e29-75ed-8efd-5d2d6698aaf1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f171-6e31-7087-8b4d-f9e06efcddc7

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f171-8446-7a2e-8314-3d3c49dbcb37
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f171-844a-7c7e-b722-3f70d9dee31d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f171-8451-7245-b1c2-930417b43fe7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f171-8457-7ac0-9ab8-219dda78c90c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f171-845c-7e81-8973-ee20a993fc84
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f171-8462-7d50-a9dd-598bc9d2b33d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f171-8469-7293-b923-53e814763ec4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f171-846e-7cd5-a9c8-a2732c9b100e

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f171-9b5f-7d08-88ed-22669ac89c65
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f171-9b63-712d-816a-6080cd9ae8c3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f171-9b6b-76f9-86e7-a8521ff950ec
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f171-9b6f-7764-920a-4fc9b66ae5f1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f171-9b74-7124-b82b-beaf7f89accb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f171-9b79-72c0-85e7-84f347c0deda
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f171-9b7f-702a-91d3-f63ae6bf1aa8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f171-9b85-7d61-bed9-577f52928bae

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f171-af86-7b69-b6bb-c41b7ef283a8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f171-af89-78a0-92e5-5680c501f736
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f171-af90-7266-87b3-e808dadd099b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f171-af97-7067-bffb-e938022d9a1f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f171-af9d-73b1-a963-5ecfe219d037
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f171-afa4-7517-ae49-698c3575d77b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f171-afaa-7065-9ec0-4dcd466f14c9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f171-afb1-7081-a6e5-9d72134a1cae

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f171-c7de-7ca6-924e-34253d8a87aa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f171-c7e2-7dc9-9ba7-8234b4c52d4e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f171-c7e6-7749-8608-e37816dfa45c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f171-c7ed-788f-91d6-1428f4407824
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f171-c7f2-7d39-a526-4f75b6c3db9a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f171-c7f7-7cc3-ad6c-40e429d72d52
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f171-c7fd-7171-afb8-f85466dfbf97
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f171-c804-71fe-ac68-8cf6cc097b50

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f171-d9dc-7a8b-b7e5-4a879715ea8f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f171-d9e1-7bfd-be80-293b59d4b47b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f171-d9e8-75c1-bd05-e02200800c35
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f171-d9ee-74a4-b7ab-20ddea5df70d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f171-d9f4-70e8-80aa-a8f18ec2bb14
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f171-d9fb-779e-8266-91a94bb8c6de
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f171-da01-7da9-ba61-62227f2e088c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f171-da06-7ba4-9714-ad9b855ef444

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f171-ef29-7b6b-965a-c3784297ae47
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f171-ef2b-730e-9977-039cbaf105ec
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f171-ef32-7de4-baef-fa0c96c97631
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f171-ef38-7fb0-b8a4-d3e8ee036ef6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f171-ef3d-7681-83e6-534c100bd078
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f171-ef43-7cfc-924e-14231a955ed7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f171-ef4a-7a75-8bb9-5dcfc0049e77
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f171-ef51-7670-a8f2-eab55a03e42a

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f172-02b1-7d81-9e21-25d6cc3e358d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f172-02b5-7404-a916-142a8eab23ca
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f172-02bc-7210-87d9-0f0810412693
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f172-02c2-73a4-89d1-2095cf489b38
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f172-02c7-7300-b48c-a364f9610123
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f172-02cd-7049-ad9e-51deff3bccbd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f172-02d3-724c-a910-3a3e7bf33c2d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f172-02d9-7632-83d4-fe1a96445969

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f172-1468-7bfc-8fa3-30aebc2eb160
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f172-146c-749a-beb7-723dbbb6bc9f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f172-1474-7c95-ba5b-ed18d2bb7cb4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f172-147a-7e9c-b360-118a712b249a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f172-1480-7979-a945-62f55983cb7a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f172-1486-7a7f-83bb-bd99de7ded5a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f172-148b-7948-a740-987d60f4e73d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f172-1490-757e-a83d-3766228aabb5

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f172-2f29-7731-9079-bb0491eeb5bb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f172-2f2d-7f09-970f-afde0796cdf3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f172-2f34-76b0-a044-19c15590c67e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f172-2f3a-774b-9a8e-cad9df2a35e1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f172-2f40-79ad-a657-992418f6935e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f172-2f46-77e5-bea5-ead56b72cff6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f172-2f4d-73f5-8702-2affa28bcccc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f172-2f53-70f8-af6a-c50bc4560d3d

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f172-4c34-7b4f-b968-7c35386279df
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f172-4c39-7259-9de7-c91342fae213
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f172-4c40-7fe2-9350-5b94f0c6efe6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f172-4c46-77af-9f14-2cee0e65457f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f172-4c4b-7958-a297-292aec8d88d0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f172-4c50-79ee-9b6a-5946686d84ff
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f172-4c57-72e8-99d0-128d5121f79a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f172-4c5d-7a79-a72b-56cb8d8c5163

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f172-6a84-7039-befc-e559cec580c7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f172-6a87-7b0b-aa7a-6cd895a00411
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f172-6a8d-7276-be25-d4f024be9031
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f172-6a92-7ed8-96d3-d2cbabdfc305
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f172-6a99-7812-9c42-66d354210bfd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f172-6a9e-7256-b2de-8426f6128591
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f172-6aa4-79b5-98bb-b99e8a8b5b2a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f172-6aaa-70b0-88be-e2cb67fdb889

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f172-84e9-7b54-a866-36b8c2b1e5f7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f172-84ee-79c0-ba5f-136000dafd0c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f172-84f4-701e-9ee0-c5d5d7375d2a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f172-84f8-7b4d-89b9-fdc1ded86e14
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f172-84ff-7466-9ead-44d7776a3aba
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f172-8505-74f6-94a9-2846d303fb0e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f172-850b-7673-8ed3-3850102364fc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f172-8512-7e04-b914-db7e7c78378a

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f172-a4f4-73c1-b71d-b7b22bc466f7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f172-a4fa-7d50-8674-512a1becd51c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f172-a4fd-7442-8df9-0ac5d90859e0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f172-a502-7292-a151-35e58145f890
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f172-a509-7770-94ae-028b952dac80
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f172-a50e-7b47-973e-e69b10bb64de
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f172-a516-7a3b-bbf2-f606b771c7c9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f172-a51b-7efc-8b0e-2b781d76042f

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f172-b23b-7935-bca1-31986c1e52f3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f172-b23f-7b43-9bd6-82f168f4c146
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f172-b245-7e76-96fc-fe1c5baebad8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f172-b24b-7b37-99d6-0d406628c63a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f172-b251-73d7-8c04-697c42e53b06
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f172-b257-70fa-bee0-f2031b4a3cd0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f172-b25d-76fd-a85a-8c0e19260455
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f172-b264-771c-9668-1cd1d14a56fb

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f172-c737-7787-86af-220ce601701a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f172-c73b-7dd7-a24f-07c1090767e3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f172-c741-762e-aea7-8c6510479719
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f172-c748-7e70-804b-c5a4b9b52fa1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f172-c74e-707c-957c-5689d515dd20
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f172-c754-74ad-8b2a-bd25636eed6f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f172-c759-7125-9f61-42f77bef7409
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f172-c760-7491-8d52-37770b2c7081

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f172-e431-715b-9c79-e9385b8b33cc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f172-e435-7fc1-a3b0-1b528b0e2c57
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f172-e43b-72cc-b391-d57e386367ce
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f172-e440-73b5-85aa-677cd9fda0f8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f172-e445-7f84-85bd-84c0444fad47
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f172-e44c-7a89-8eb6-0fb10b87f6df
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f172-e452-7a20-b2f1-81e4bda2d890
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f172-e458-78a3-935e-40b3b1e1b45d

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f172-f0e0-7723-b063-b7b43305e612
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f172-f0e4-7a06-8f5e-b5891e08530d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f172-f0eb-7995-899e-3c167833471c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f172-f0f1-7d39-bff5-a1de9bd0d13c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f172-f0f7-7c8c-84ad-65db232fa5a1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f172-f0fc-71da-a231-86d748a64ee3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f172-f102-77fb-927b-e9237ccaf198
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f172-f108-7f65-8bcb-463b77db594a

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f173-0486-7bf3-8ffe-0613ec4e9c18
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f173-048a-7770-af81-a2246ed44e35
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f173-0491-7e9f-b12d-2c15eda37382
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f173-0497-7234-8505-409354b1e77a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f173-049d-7f08-b102-06bd9821c975
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f173-04a3-7af1-a185-e4cdb8094ba1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f173-04a9-7fb8-8d4a-440e8ef4e5b2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f173-04b0-7378-b39c-b5144a293b9d

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f173-1456-7fc4-9be2-049e9d611d68
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f173-145d-7127-abef-e70d8e8914b8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f173-1460-72aa-bab7-dd11b100c4e8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f173-1465-7449-95a0-19c3c104d162
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f173-146a-77b5-b574-623e67c8c6b5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f173-1473-77f0-af18-4e40b5b8dcc0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f173-1478-7122-bb3c-ccf32279a07c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f173-147e-7d5f-969b-1b35a8329f0b

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f173-26a9-7dd3-8d06-4df3683ccaac
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f173-26ad-7b40-b674-5040edd03efc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f173-26b3-7227-bc8a-53fdd8981342
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f173-26b8-7722-9c00-999254282dfd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f173-26be-71f4-827e-3d986e86f358
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f173-26c6-785a-97f9-10b21b2ef043
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f173-26cc-7350-86bb-07431e6b8078
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f173-26d3-77da-a606-9283dd41b2ae

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f173-3afc-7e6e-9bbe-79a179f6dd44
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f173-3b02-7f0b-968d-b7ee70eca355
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f173-3b07-7b2e-bc26-37488509d806
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f173-3b0b-7754-ab0b-dff6dfd7a957
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f173-3b12-7846-8aab-133ba5c4241d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f173-3b1a-78b9-9cba-d1afa2eab81b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f173-3b1e-72ff-9bd6-948b8c75d815
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f173-3b25-7ba0-a09f-21ef9d706587

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f173-5042-7722-b67e-294b33b8919f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f173-5046-706a-a220-8d1118db5a61
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f173-504d-7351-b57f-dcb384ee2f34
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f173-5053-756f-9247-58797679f025
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f173-505a-77fb-9f75-494046039357
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f173-505f-79e0-8de8-a27688656930
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f173-5065-764e-94cc-1f65933f264e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f173-506c-7c01-9328-10ba1a2cce09

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f173-61b4-798d-8272-4c4d48ed5274
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f173-61b7-7914-977e-b67bf17024b1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f173-61be-7fea-b08c-fe5ca7c56f0d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f173-61c3-75b5-8e4c-882815eb8245
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f173-61c8-7661-9c97-a01afc5d875a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f173-61cf-721a-bc0b-67052c5d3660
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f173-61d4-7937-804c-a565c80054ec
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f173-61da-7c89-8410-b95bf94b47e5

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f173-8573-7e66-a865-d77e11cf5a38
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f173-8578-7b39-baca-b478b9e3ec8f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f173-857d-701b-9015-d88b4978b076
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f173-8582-7577-a109-43e48ea98897
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f173-8588-7918-9848-af714b72409e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f173-858e-7a39-83d6-7df0415da23e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f173-8594-70d4-afbc-ac5a47f05974
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f173-859a-74e7-892e-4f5666dc1673

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f173-9c10-7bfb-a53a-84424059560c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f173-9c16-7987-bfb9-73983a20ef55
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f173-9c1b-7454-960e-350f232fabc8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f173-9c21-7a97-adc4-8bf6a764ef7f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f173-9c27-79d7-b739-340caeb7a311
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f173-9c2e-7c80-999d-109045b674e0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f173-9c35-74f6-bfd8-22c23da7675f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f173-9c3b-707b-b893-8bac71c26e62

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f173-b0f8-7278-a71c-dcd43478f0a5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f173-b0fa-7a1a-b036-af383a3f086c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f173-b102-795d-be00-7fa243992c0c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f173-b108-70b7-af4d-2b0a6c4db492
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f173-b10d-7f55-90fe-909abd70750d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f173-b113-71fb-9f83-21d4db76de9f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f173-b118-784e-8572-aae4390860ca
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f173-b120-7067-bfae-5faadbac30cc

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f173-cc15-7139-a148-387a7202c191
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f173-cc18-795f-a9b9-cc3996f29db0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f173-cc1f-78e0-b5e2-5892af8c1d06
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f173-cc25-72a0-bbd9-233177260231
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f173-cc2b-7154-8d96-db2789718295
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f173-cc31-76c1-92a0-dff16345c211
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f173-cc37-7640-a9e1-c5c0cb93cc1c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f173-cc3e-71de-b9ad-6c9b8f8259ab

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f173-ddaf-7787-b04e-81f542e8eb8e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f173-ddb5-70bf-bbde-898b7456d1f0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f173-ddbd-77a5-b251-82f2e698f7c0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f173-ddc2-7fab-aaf0-f8c64168f64b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f173-ddc9-7329-9c39-86e758155cd2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f173-ddd0-77ea-94c5-f53808db559e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f173-ddd5-799a-b364-2230c3ed1157
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f173-dddb-7283-be8f-1990d2f97953

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f173-f5e2-77aa-b683-59b56d7a19b9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f173-f5e7-79aa-91b4-2a017b8cd786
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f173-f5ed-7681-9954-001c07afdd8b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f173-f5f3-7125-9dfe-474dfc35307b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f173-f5f8-7ee5-8d22-08291e9b9fe9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f173-f5fe-7bd8-a91e-83b29bd2a6f0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f173-f604-7dfa-8ae4-742febf876be
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f173-f60a-7cbf-b7b5-945a238f8ba5

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f174-0b50-75f3-a1d7-0b192e04d082
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f174-0b54-7a43-b0af-63d2e9bd4094
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f174-0b5b-7d5d-86ec-159cdf1a8ca4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f174-0b61-79b9-b2f2-e087d34f8b9f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f174-0b69-7c3c-934a-835159c277e8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f174-0b6f-7b6d-93b6-4670213db361
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f174-0b77-709c-b612-21776218a94e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f174-0b7f-72a5-87c0-0e09a6dd239a

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f174-1ffb-70a4-89d1-1229775b5e8e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f174-2000-7058-a02a-35d14e22d432
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f174-2006-708c-85b1-35371862aa26
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f174-200d-7b21-bbcb-f65350c19507
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f174-2013-78c2-9b07-61946ca88ea0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f174-2018-7de0-869f-93803b74c4fd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f174-201e-7103-9a7a-a304bbbdcf50
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f174-2024-7a26-9397-211d742cd1d7

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f174-3e71-7f90-b7f6-365cd4f3718a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f174-3e76-7776-b009-117b035bb37e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f174-3e7b-7cdf-b281-7fb68f9ccf87
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f174-3e80-781f-b4a5-a7e13d03d921
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f174-3e87-76a2-bd92-fd5e19321459
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f174-3e8c-76d3-befe-1277832d061d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f174-3e92-74b0-9d9c-fd09c4211c51
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f174-3e9a-7857-ac0f-ee6ca3b1db8a

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f174-5aab-752f-842d-68d53efc2bdb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f174-5aae-7247-8c05-65446a6e7401
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f174-5ab4-779d-a366-a9dbe0df2e15
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f174-5aba-7d22-820c-4b8ff0dcf0b8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f174-5abf-7315-9e69-e336ebe2523c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f174-5ac5-725f-93c8-37566e847cb8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f174-5acb-7d77-877a-a497578d4cfb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f174-5ad0-7844-aa98-94cbedc441b6

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f174-71a6-7f95-9618-5de9fd28b24f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f174-71ac-7633-906e-e982ff0faca5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f174-71b1-739e-a5b6-d45b7d588fe3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f174-71b6-7c5c-ba70-dd2613648c47
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f174-71bd-7952-a087-7858c82fab69
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f174-71c2-7b66-bb25-b7b0d8929ffb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f174-71c9-725f-b54f-8fb696cd3c38
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f174-71cf-7e60-afcc-1990830dab6a

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f174-87d7-7000-b522-6b8e89a12395
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f174-87db-785b-b4cc-0957fdfd10fa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f174-87e4-76ba-8dc1-c2a7cd52066f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f174-87ec-7c20-833a-876453eadcd1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f174-87f4-7091-83dd-abd3756c31d9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f174-87fd-7a6d-9987-97881f097036
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f174-8805-7dc0-87b1-40a41ec68410
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f174-8809-7a7d-b012-9b0bc38fb75f

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f174-9ee0-7d99-8774-459adc85b4b7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f174-9ee5-7574-b9ac-b5fd5c071412
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f174-9eec-7339-968f-072b4a922133
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f174-9ef0-765d-9d2d-c28018aee2b9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f174-9ef5-7ebf-8c88-5416e4bfe2f6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f174-9efd-73e6-b926-5d6bf50d473d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f174-9f03-7da2-8064-2b39aa8aa958
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f174-9f0b-75b0-b37f-ae34af84cb83

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f174-b1b2-72f5-92dc-ff9f352cf94a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f174-b1b6-7158-bda3-55a8f1d569b2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f174-b1bd-7a2e-b99f-93492e935a53
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f174-b1c3-7d26-b513-4027f2214860
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f174-b1c9-71be-a5f0-8bb635fb2d0c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f174-b1cf-79f8-b910-f81afbac7d03
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f174-b1d5-7f60-8c4d-b3ebc1208ea9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f174-b1da-72e7-8a53-3c1ff3a76f48

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f174-c8e9-7e92-a220-11c83374b1ad
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f174-c8ed-74d8-adb8-a44c3028c239
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f174-c8f3-765a-a97d-204d55175e46
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f174-c8f8-7409-a506-61504271510d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f174-c8fe-7e23-8e1b-19f64574251f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f174-c905-7df0-8e41-9c8468ab6858
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f174-c90a-75bb-adad-fcfb274fc83a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f174-c912-78f3-94e9-60fc2ba9c742

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f174-da4b-77fd-aca7-4f825be3a4f5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f174-da4f-72ba-b685-319f792858bd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f174-da56-76d4-8332-6842874216d1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f174-da5b-741c-a566-1586a04d5b16
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f174-da61-720d-b8d4-32574e5dccec
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f174-da67-71eb-ac6a-58592a5e639b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f174-da6d-76d9-8bf9-04f425303d8c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f174-da74-77bd-97ab-99b7a551059a

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f174-f7aa-7ed0-8575-be48573b32a2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f174-f7af-7448-93d0-cde31b94af7d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f174-f7b7-7828-a1e7-0adfaa7e0d3d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f174-f7bc-7f20-83d8-69f12eb05024
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f174-f7c2-7ed4-8f8d-193dc9b06fe1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f174-f7c8-7927-b974-1376ac961ef3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f174-f7cc-7ab7-9662-86bc44f7d85f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f174-f7d6-7653-b8d7-b43e8d30a836

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f175-1111-780e-9929-61b62e3029d7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f175-1116-7b01-9001-c18c1fc95396
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f175-111b-7832-a89d-ab94fe1cd161
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f175-1120-7eee-8b6e-5b3b8c1b3bc2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f175-1125-775d-bd10-25619750b3c8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f175-112d-793f-965e-f2b96c1e54b3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f175-1132-7006-8923-49001213d7bf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f175-1138-760f-b8f7-e636b7a1bb6f

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f175-21d9-7c01-b703-662307a72cb9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f175-21e0-7771-ae20-776ad91f130d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f175-21e4-74ff-90a0-9a4360695302
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f175-21ea-7bf0-99df-50e1c18de0b2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f175-21ef-7045-a957-606ed088432c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f175-21f5-762e-a064-04fd445f5394
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f175-21fa-77f0-85df-035014101a48
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f175-2200-76ee-b9d5-8fa0d20efc0d

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f175-3b3a-7ee1-9780-7f43cc82cd0a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f175-3b3d-7090-959f-deb401312563
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f175-3b44-73fa-9385-e20c8487be12
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f175-3b4b-70cb-a07e-0a7a1d347fb3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f175-3b50-773f-b16f-d31d2f419417
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f175-3b56-7ba8-a808-877c18a64c72
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f175-3b5c-77ec-9f9a-37cf2d1e615e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f175-3b62-7570-83a6-c1c709f8398f

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f175-4f2f-7c21-9710-18c2191d2ff6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f175-4f32-7044-9089-444bf7388b3f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f175-4f37-7993-af4e-db5823a77549
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f175-4f3e-7dd3-9956-6744229e78bc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f175-4f44-79ef-a1d0-7e5877f02fd2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f175-4f49-7916-92e3-0db7b3f60a33
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f175-4f4e-7ea3-a93e-35c25d2fbbfa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f175-4f53-77af-aaf6-648635253e61

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f175-6f80-7bfa-97e8-1412d27e6d4e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f175-6f82-7126-b67b-0b0730c20c51
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f175-6f89-7267-9837-d004df0c6236
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f175-6f8f-72ff-9e66-13246566855d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f175-6f95-7907-a3b6-bfd97fc9ca5d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f175-6f9a-77ea-8ca3-1602cc24d413
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f175-6f9f-705c-b2dd-f94c6db15cc8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f175-6fa4-7842-ad5d-3251c4d6ecf5

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f175-8092-717d-adbc-f10da20b568c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f175-8095-7466-bd5c-b568b2dd6103
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f175-809c-77db-88ba-3eaa48ef1576
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f175-80a2-776f-9f6a-75f1819dd778
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f175-80a7-7dbc-9709-35e15b6a7db2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f175-80ae-7173-afda-f32fa2f22dbe
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f175-80b3-7c0b-9156-56d7f2b74af9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f175-80b9-7d89-8acd-b5e11e6ebd73

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f175-a4c1-75ad-8077-48eb1767e9e4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f175-a4c7-78b7-bd91-b49a2fd19e1e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f175-a4ca-7a8c-bea2-4fbb2964b5e4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f175-a4cf-7f31-9000-08324ea08895
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f175-a4d5-7ce6-a2fe-1cf8211e9874
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f175-a4dc-7baa-ae9f-a9de4e05d1fe
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f175-a4e0-7d60-8d14-9f587cad9074
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f175-a4e7-77a9-9df4-aa52741507ca

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f175-b970-7019-bd0d-b5fd76398111
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f175-b972-7dfe-885b-7dbcb5362388
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f175-b979-7835-8917-2945d1289ecb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f175-b97e-73dc-929c-1ff1ec67e8b9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f175-b983-77bb-8caa-aa2610f818e0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f175-b98a-7476-a70d-3461a5d3767e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f175-b990-7e79-bf23-e90916b9970b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f175-b994-7574-be6a-96830a3dd964

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f175-daf6-7c4c-b0db-595265798bf6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f175-dafa-767f-9f91-6c76274b8d41
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f175-db00-76ba-ba18-92966f3b0c69
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f175-db06-70aa-a5c4-e81c6f4bae4b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f175-db0a-7df7-acf0-dd162fd21edd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f175-db12-7acb-81c1-a17946419e21
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f175-db16-75a1-9202-9ce318154e51
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f175-db1b-7749-9082-dd3ceda2dc4c

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f175-ed65-7589-8df5-7c16f60681d1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f175-ed69-792b-817a-b96ccef15885
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f175-ed70-76d4-bca6-ecd1e92f5ef6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f175-ed77-7d21-bc07-f88fd7d3f69f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f175-ed7e-720e-8d2b-d23da9a8261d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f175-ed85-729e-a863-cd93466838f9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f175-ed8c-7f3d-b745-3b4a854a2541
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f175-ed93-7ee2-98b5-7e8c51046c28

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f176-03ca-73a3-8c0b-2b20e01d65d6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f176-03d0-7e86-a548-1513f4124689
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f176-03d5-79eb-9adc-04dfea99b980
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f176-03da-7ff4-a22a-2ee471752689
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f176-03e1-7ba7-847d-ff988994b1b5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f176-03e6-756a-b56f-62acfe321a66
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f176-03eb-7ca0-9e4c-717de3bd3ad6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f176-03f1-791b-b41e-755c461812a5

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f176-14a4-740e-b54a-163010fa96bf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f176-14a7-7526-b480-1136017238ef
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f176-14ae-73ca-a3c5-eb7a2fb57be9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f176-14b3-7e43-9916-172a78ae2679
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f176-14b9-701e-9ecf-a62cea2d3027
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f176-14c1-7ea7-bdbf-ee70b7f6644b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f176-14c6-7164-b628-866beaa4485d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f176-14cc-7f53-9473-9094d0add592

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f176-2f87-73ba-a548-479aff77baec
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f176-2f8c-75c3-a643-dcf34f17ada9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f176-2f91-7bbf-8071-e47c3c4ed74b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f176-2f96-79a7-9c64-5dbc78eb3f4f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f176-2f9c-7498-9a85-cec0c0b76bc4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f176-2fa1-7498-849e-c2e78a2264ae
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f176-2fa8-7713-8cb9-d2974260090e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f176-2fac-77cd-bf70-f7aaa8dd868f

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f176-4701-7041-a418-1714815a18e4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f176-4704-7579-873b-4adc53404362
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f176-470c-7dea-ae9f-2066c319186f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f176-4710-7eab-9972-0b3905ca157c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f176-4716-78f2-897d-8311bebbf5a2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f176-471b-7491-b3dd-993550f7f5c7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f176-4720-7fbb-a8bc-00854474c843
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f176-4727-7375-a6f5-376366f8e859

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f176-6a26-704a-aec0-02163e3bbf2e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f176-6a2c-72ef-8e05-56b4597d8eb6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f176-6a30-7776-bbb3-8fafc662452f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f176-6a35-71c5-ae0b-fe0b89084a97
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f176-6a3b-74d6-a82e-314f12a30144
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f176-6a41-73d3-aec3-6243a1df50e2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f176-6a48-7d68-b3b6-a9656c5f906c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f176-6a4d-77bf-930a-f885b0295d3d

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f176-7d43-7720-b39f-8f70eea7f9ff
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f176-7d47-7f5a-967a-aba5985cdad2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f176-7d4e-78ad-bb5b-f47fceca4c4f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f176-7d54-78e9-841d-5a961e537532
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f176-7d5b-7ef1-a989-9aa1f24af0ac
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f176-7d62-7e24-b656-c94cb754eb08
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f176-7d66-7d71-9682-cb0954fc724b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f176-7d6a-7625-9126-c84bc3c9c597

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f176-8e07-7326-917d-80850f77f1f9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f176-8e0a-7709-b382-ea12b49dab50
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f176-8e10-7e7f-b534-f6891a59951d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f176-8e16-7d71-9ca6-2a9fecee208e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f176-8e1c-7b1c-a97f-eac87575b829
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f176-8e21-754e-a525-7e16cd953367
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f176-8e27-7172-a908-0407ed76fb60
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f176-8e2c-71f7-ab5f-2159503629f0

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f176-a356-7e9b-9a99-b95a087a6091
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f176-a35a-7cc8-bbf2-c7107245461e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f176-a363-7884-b344-324a1daa60b4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f176-a368-75e6-99cb-d2b3b848ac3f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f176-a36e-7081-b548-a397224ae615
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f176-a374-7040-987b-a3ac3bf567a2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f176-a379-7982-953b-3bc9e7d111ad
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f176-a37f-7ef9-bc0b-eef87332904a

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f176-b694-7852-828a-d2aaf2b71ece
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f176-b69a-77f0-a3ea-a81b17620e78
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f176-b69e-740e-9487-6d7b06bf003a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f176-b6a4-7c53-983e-14c24e41be40
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f176-b6a9-7bbe-9abf-3f86df952fd1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f176-b6ae-7fb6-8b7e-29c08ac25ebd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f176-b6b6-77c0-b397-f6f04767e5e7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f176-b6ba-7353-8ab0-ace4602b9283

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f176-cff6-72b9-be1f-77cdb82746e7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f176-cffa-71df-87de-4f7656ce44ef
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f176-d000-722e-ad22-c08fce032738
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f176-d004-7468-b26a-b4a2b1d02148
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f176-d00b-7e80-a0f6-af445a0446ce
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f176-d012-783a-9c20-2ae79f92dcae
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f176-d017-77a9-bd6a-590732386d01
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f176-d01d-787b-80df-d6a0cd734f1e

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f176-e944-7a13-8a12-e107d13bd0f3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f176-e949-7b59-97d9-380aa3fd0b40
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f176-e950-7b7d-b1bc-0471b4b27ecf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f176-e956-7776-9e6a-ced469e208c8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f176-e95d-7a59-893b-a39fd3c1b23c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f176-e963-74da-bdc5-776d6145e566
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f176-e968-764f-8657-64bfe07f0dca
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f176-e96e-7ba8-8a1b-ea4ae41aa4e7

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f176-fef9-7e26-9a20-1b682b06b5ad
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f176-fefc-7906-85e7-52eb0c1b0f8c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f176-ff03-763c-a53d-ac1743dc614e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f176-ff09-7624-9ef8-ff38213fddd0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f176-ff0e-71ea-be30-2abacbc103f1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f176-ff15-70ca-9660-365548e334e5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f176-ff1b-7d00-82c3-df15d3911625
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f176-ff20-77e4-a1c5-2bb13673ab18

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f177-139a-7011-a271-6e8d2480176a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f177-13a0-7981-9af2-e90e8fa9bac5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f177-13a5-74b5-9e89-559b207247a9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f177-13aa-7762-9eb2-a905043906cd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f177-13b1-77bd-b8bd-5b7497902bf2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f177-13b6-774d-8923-da6835f8917a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f177-13bb-734d-a370-8e6ec9b8225a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f177-13bf-784a-a864-c587fe6b22a1

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f177-25f8-76b4-b20d-88ca6c4fec2e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f177-25fb-7d21-a8e0-8afc425b05a3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f177-2601-7574-abdc-22983fb6cc75
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f177-2607-730c-b089-11e898d22e05
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f177-260d-7366-bc57-3e0d37b18f6a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f177-2614-749f-866c-04824b9c460b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f177-2619-796b-99f9-bbe7a9f20722
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f177-2620-7060-adcd-b985a11fa0c7

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f177-39af-7f7b-9ae5-cc2421e96294
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f177-39b4-76ad-83d1-c9943d7b1da0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f177-39ba-7693-a391-abc7d472ca91
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f177-39c0-7a10-aaa6-9fac1de6dd4d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f177-39c6-7811-ba8d-95505d124d5b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f177-39cb-7018-a6f7-1dbad7b5782b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f177-39d1-73e0-b87e-24c39e35f540
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f177-39d8-7d36-bd1e-baa6dc34e306

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f177-56de-7cb1-a887-d5dc4ecbfa5f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f177-56e1-7b8b-9cb3-3d3a236f19f9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f177-56e7-72e6-b15c-9c0722eb2c7f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f177-56ed-778c-a7b8-cfe0faf9e17c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f177-56f1-7506-800c-6e5ad2a01709
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f177-56f8-71fa-9a43-67632820e9d3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f177-56fe-72a2-a52b-4a49d03dc81f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f177-5704-7f2c-83a3-70847deca588

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f177-645d-7ee1-aff8-907fdf19c64e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f177-6460-7247-bca2-7ae8a2fd3911
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f177-6466-7294-8130-fe2771d597d5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f177-646d-76ec-adc1-825c67d4a503
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f177-6472-78f4-94e0-569b519afaa0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f177-6478-7d5c-af71-21b3bbb62ef3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f177-647f-72f8-a450-9467c7566da0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f177-6485-71a6-9ca2-636b0138881b

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f177-79c4-7221-95e3-c888236e5eb2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f177-79c9-7fb9-b207-d61bb43a8067
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f177-79cf-7f0a-8d55-e7c996f7a823
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f177-79d4-7f39-a2ea-e22fda3af608
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f177-79da-7872-9e17-10abec28cca9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f177-79e0-74a7-92b3-b6136ec505ab
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f177-79e8-7b31-9dff-58037cb605f7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f177-79ee-7411-bba3-9496adce15a9

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f177-9279-76e5-9656-5c878bd8d7fe
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f177-927d-7f00-a11f-7e78f26e361f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f177-9283-724e-8eb2-9f9b7953074d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f177-9289-78b8-a20f-8113fda59179
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f177-928e-7225-9ba5-1e531ac57f1f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f177-9293-7250-b1e8-5366ea0ac9e8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f177-929a-78d4-96e7-140e5c1aeeb9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f177-92a1-711f-b2d4-da29a1d1610e

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f177-a3ce-7d99-9dc3-ce6ef193adf6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f177-a3d2-7ae1-b6eb-ff46019abce8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f177-a3d7-79d0-8e50-14cb253a5f46
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f177-a3e0-7b85-a867-634d798bc23f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f177-a3e6-79ee-8e37-6d0efe024125
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f177-a3ec-719a-8f35-711e5832eba4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f177-a3f2-7482-b36e-8b37c0bc383a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f177-a3f8-799f-b225-e49903d65068

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f177-bafe-7dcb-9707-943783014838
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f177-bb03-7f9c-8656-c9ba3ee424b1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f177-bb0a-77aa-bee0-6a07a45b61a8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f177-bb11-7fe1-926d-77a88a9d7a7c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f177-bb19-7178-80f0-627cac91051e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f177-bb1e-7c09-af26-465401de8df4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f177-bb24-72ae-9d09-fa8c36b56882
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f177-bb29-734f-b15c-4d5d0098089f

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f177-d041-7ad5-885e-4aee496c8d37
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f177-d046-7e70-98d0-579d9d95079e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f177-d04c-72bc-b9df-4b519228b310
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f177-d052-715a-ba9a-fc3fd0f7eecd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f177-d058-7ca0-8dd7-80cc80c273d6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f177-d05e-7746-bd43-85abede65b6d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f177-d064-7c5c-a9df-29515dbf683f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f177-d06a-760a-bd20-791f2866beec

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f177-e9e4-738b-8f93-45d1e80c0fcb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f177-e9e8-7a47-8e86-91442befd238
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f177-e9ee-729d-a29d-2c5b28d46741
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f177-e9f3-7420-be96-eb33e4439207
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f177-e9f8-7b94-bf67-1fce62c0d6e2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f177-e9ff-70ec-9e3a-dc51d1feaa75
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f177-ea04-7ccb-8541-196d11c4f374
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f177-ea09-70fc-9294-219cda4b38f0

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f178-03b0-734e-b4c0-1ce28cc3623d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f178-03b3-7f59-b11a-7aeb4e103b8f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f178-03b9-7ce0-acd5-d699be7b7c32
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f178-03be-7084-bf99-69f5dee49cac
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f178-03c4-7440-9f57-c986dc9f0688
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f178-03ca-76a6-8ccd-956a38f594af
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f178-03d0-770e-9f8a-33773d6c2018
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f178-03d4-74cf-97c6-8660f7f6b709

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f178-21cb-79fe-99f4-1ad7eea574ef
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f178-21cf-7c7e-99ea-1de5ad8d355d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f178-21d5-7431-ac94-7af427297bba
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f178-21da-7fe2-8dbf-c9accc4fa458
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f178-21e0-7229-95dc-8eee2a2b2721
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f178-21e6-77fa-b97f-7365dfcbf33b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f178-21ec-771f-89bd-07724634aa45
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f178-21f0-7250-9ef6-eacb5521d11a

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f178-34de-78e8-9eeb-4a04f7aca661
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f178-34e2-7162-8ed6-bbd852fb50c1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f178-34ea-7272-89e1-d45f01345381
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f178-34f2-7c53-911f-eea44e205e27
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f178-34f8-725f-830d-cc26eb04f65a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f178-3504-7dd8-908c-18e53589053d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f178-350d-7757-ae92-2e0451b7962d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f178-3513-7368-bafa-f4c66d60c057

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f178-4a0c-7a3c-8c53-cc60948106f9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f178-4a10-72cb-a0dd-450a17bfa4af
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f178-4a18-7eed-9523-52246684c74b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f178-4a1f-71e6-bd1c-474054ef83c7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f178-4a26-745e-887d-f3d579f01cd8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f178-4a29-7a35-a3d1-1a25205f11d2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f178-4a2f-7623-8c67-2555332acbc7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f178-4a35-7e2e-aacc-730d8748b0f8

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f178-5bf9-7dc7-94e7-b72686026c2a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f178-5bfc-7837-af43-dfcb1c75d921
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f178-5c03-7ec5-a604-6998151427e3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f178-5c09-7ff0-873b-f90def781e66
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f178-5c0d-76b1-b5f9-b2b8541e691a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f178-5c14-76a3-a3df-a165534b4738
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f178-5c1b-7b21-a4b8-c18d4fc7fe49
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f178-5c21-7b0a-988c-2cc3eaca8326

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f178-730a-7f99-acb6-0f4914bcddff
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f178-730d-747c-9de7-5da61fa7c361
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f178-7312-7a32-bf31-727279ea038d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f178-731b-74e8-ad33-22b2bf12a6ff
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f178-7321-7cef-a3aa-a31b8fe35c25
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f178-7327-7223-af54-bae87e90d6ff
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f178-732e-7cb7-a396-a3b7bab8eb75
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f178-7332-7332-aa53-1056bd6bb0f0

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f178-843e-7dda-93e7-f83dae2da414
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f178-8441-78e9-ae9b-7a34eb7c84b9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f178-8449-7d22-aa7f-3a3e0ded93fe
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f178-844f-7df2-9167-16e9d3ca8cb1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f178-8455-724e-b008-0d997d70048f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f178-845e-7821-adbe-677f4de8e5e0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f178-8463-7a7f-a645-3f26de5cf849
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f178-8468-77ad-b73a-43fd9f890353

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f178-9c5e-7f5c-89f4-88de271b3fa8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f178-9c61-73cc-822a-19017ca09a1e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f178-9c67-71be-9b6b-cc7283193cf6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f178-9c70-7542-9623-77946a46303b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f178-9c76-7d9d-9bb7-c0004874bdb6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f178-9c7b-7154-83fe-4b66363b1f94
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f178-9c80-7903-be7a-d154e434c462
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f178-9c86-7794-a296-ba10d2f414b5

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f178-b387-771a-be17-2cb1a429b909
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f178-b38c-7087-8459-12a2e8fb7873
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f178-b391-7456-899e-2c8f3976cfff
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f178-b397-7166-8447-9e1fa4e51e66
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f178-b39d-7d59-bc0b-6cbc85bb3f05
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f178-b3a4-7db0-af5a-b735837946a8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f178-b3a8-7d80-9238-cdfe81fbaaa4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f178-b3ae-79b6-af51-cec1662629c6

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f178-c63d-7fa4-a21d-305f1385c178
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f178-c641-7ef2-9129-595ccb7c565f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f178-c648-7227-9804-e49a52820195
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f178-c64e-7c66-8f6a-b3e35bc4c5d9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f178-c654-72e0-8557-6e72629ea466
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f178-c659-7670-8bda-cf936a5a92f5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f178-c65f-7215-8f9a-e0c2a084b924
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f178-c666-71cf-9738-f8ac084db439

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f178-e0f1-7771-b29b-4482dc5a0e43
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f178-e0f4-7d4b-a6cd-3758de856fec
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f178-e0fa-71c2-aef2-8a385c9fd8f2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f178-e0ff-7ece-8154-9257caac6cac
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f178-e105-7c49-ad3c-710a9ab3db47
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f178-e10a-7cc6-a40a-12cf7e4cc40e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f178-e10f-7337-a43b-8e59aa47601a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f178-e116-7d7a-baca-951d9ef22807

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f178-f795-733b-a651-873d5fb5934f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f178-f798-7732-bad8-fda52d98c354
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f178-f7a0-7a21-bf53-3154792cf6d7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f178-f7a7-7064-8125-0a6451f13823
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f178-f7ad-759d-99d5-613fe5bcfb7f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f178-f7b4-7167-b41f-561bbcf7f040
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f178-f7bc-727d-a852-d0f993b05acd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f178-f7c2-79d7-a536-bd0ef1531b29

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f179-0585-77d3-a0c3-3e506c87d70b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f179-058a-7025-b470-34a97e9dd1fc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f179-0590-777d-93dc-a147ed2c6688
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f179-0597-7f2e-a471-03059433d248
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f179-059b-77ab-a0cc-64a0de5c3894
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f179-05a2-7da0-bd9f-4991e4240da6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f179-05a8-70f5-baa2-3a459d39bed1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f179-05ae-7ea6-852b-940c091b7e4f

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f179-18c7-7fb5-87c6-3042f91cd18c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f179-18cb-74ba-be48-628a356faf9c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f179-18d1-74ad-b870-542a07727f20
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f179-18d7-7314-a12c-027a72420ff2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f179-18de-7947-b39c-857951e2273f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f179-18e5-7590-bdb6-cc0ab4df96cf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f179-18e9-76df-b4bb-4e4a251709a4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f179-18ee-7bbc-9c53-1160d6ba8d7d

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f179-343b-7852-99fd-81768416d617
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f179-3440-78e8-b1c1-9afe1c433e94
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f179-3446-7ec7-ba1a-2762cc4683a5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f179-344e-70ee-83c0-6d7fac6f7b8e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f179-3453-72b6-9e5b-0d9e71b70f30
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f179-3457-79a9-9a0e-17a664ec64f8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f179-345e-7c11-a0c2-c9d8b8850afb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f179-3465-7ba6-8573-9072372a3236

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f179-5188-7fa8-b07b-dd89d8125ea8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f179-518b-7f0d-b2e7-2da850eb26b8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f179-5191-7b10-a3c8-207a5740493a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f179-5197-7a47-a468-13a6e87af128
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f179-519c-791c-8d28-b211cc73a541
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f179-51a2-78ee-b454-95982d286ab3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f179-51a8-71f3-9acf-c3a8d063cdc5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f179-51af-782c-b45a-b61ea1814922

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f179-6209-7f04-9b1f-b8153b0df883
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f179-620c-724e-97d8-bc0056d8a2cf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f179-6213-7651-b2a9-d1de45471b5d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f179-6219-78d5-a27d-458b560c4d91
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f179-621e-75eb-9638-72f586d3c83d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f179-6225-7685-a42e-75593ed0f4b3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f179-622b-7326-a861-22702a876b2d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f179-6231-7233-a702-e589651b4429

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f179-7526-7c98-a319-a1a4f95dd8c5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f179-7529-7fb1-9526-8724067bf45d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f179-7530-72d8-87ce-10fc9107d311
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f179-7535-73ef-9524-9d37b8db4f3a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f179-753b-78c5-a320-4d53a27e8f83
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f179-7542-7861-be4c-af05ac81de51
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f179-7547-7bec-84de-908056b386f1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f179-754c-796b-b22d-dcb98ec30bb5

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f179-8413-7904-8536-24db27e24ad4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f179-8418-7b7d-bfd3-fc030e9b5380
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f179-841f-76c3-9f4f-ec7eb83204b8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f179-8424-7782-bf67-22a73295c410
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f179-842a-74e1-9cce-90ea5d0f460a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f179-8430-706a-a682-f997a1b04e3e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f179-8436-7e5a-b833-e6932f09c316
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f179-843b-7651-8c4f-f8ff2ce5df45

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f179-99b9-73c5-989d-55072a67a764
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f179-99bd-7f66-82ca-e7c330d4dd1b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f179-99c4-7d71-a9bb-8930ce8ee8db
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f179-99ca-754f-a0bb-23df9126ae3e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f179-99cf-7c95-ad41-7d2ac755f865
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f179-99d5-7b3b-ad62-51dcec54528b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f179-99da-756c-970e-054ea13ad1f0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f179-99e0-7e1d-8bed-7a0664dbaed4

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f179-b33d-719a-abbb-e7e3714d5c61
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f179-b342-7103-8004-5b8215226c82
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f179-b347-7ea6-bb7e-a3ada943f5b6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f179-b34c-7eb8-a0eb-db108c7e195e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f179-b352-71ad-99b5-e1615498cece
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f179-b358-7b01-bae3-6486e9e6846f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f179-b35e-79b3-81b1-8a766aa3180b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f179-b364-7ee6-aefb-a87b62a81973

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f179-c918-79a6-93dd-36decded4302
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f179-c91b-71bf-985e-41acb4666799
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f179-c922-7b38-9951-48f13e592641
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f179-c928-7150-abd9-dbaad203bc83
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f179-c92e-70ce-a98b-3e216c07eca7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f179-c934-7b62-b000-a15a4b1c7388
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f179-c93c-734e-8e7a-2e0597b5886c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f179-c942-7f84-ada1-ae57b2777c53

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f179-e4a5-7440-a1c0-451c3aaf533e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f179-e4a9-7eda-8500-0f3b3fc3d043
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f179-e4ae-75ac-9cca-80f8fc5a019b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f179-e4b4-716e-98ba-71861e5775e3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f179-e4ba-74a7-824b-ef4f39e2d10a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f179-e4c0-73e6-a1c4-d6f3d1ed28ed
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f179-e4c6-7f8f-ae56-f50ce0b600dd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f179-e4cc-78a4-9902-41c595cdd134

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f179-f2eb-74a8-9a8f-6c83f4ca622d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f179-f2ee-7368-bf22-e8e0b7dbab9e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f179-f2f3-728a-a40a-45976f725016
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f179-f2fa-7ec8-a893-e2542ab16e15
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f179-f300-76ad-a683-be5566041ef0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f179-f306-7317-83b2-952e7c46591a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f179-f30b-71d6-8937-4e33f4d3aa5c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f179-f311-70c1-b395-2fda1c8611ff

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17a-0c51-7a97-bc88-2cb5e386bc89
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17a-0c56-7551-9443-ebd5a46b16cc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17a-0c5c-757b-8992-69228fddf0c6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17a-0c62-71e2-afd4-c71e8edde977
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17a-0c67-7727-a079-aff7a89443a6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17a-0c6d-7111-b50c-ac405a17d27c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17a-0c72-7419-9284-3fa1a4805643
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17a-0c7a-77ec-a86d-ee2cae26c956

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17a-1fc1-7d2a-882e-3dd93a44d59c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17a-1fc5-713c-9d98-dcf97812eeb5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17a-1fcc-70d7-ae3f-15b3745c3bb6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17a-1fd1-72dc-ad9a-ff9d3ac22dd5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17a-1fd8-78d4-856c-6781ef28853e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17a-1fdd-7c3d-bdb2-2fac63e43824
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17a-1fe1-7b36-961c-78cd9715c45d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17a-1fe8-747f-96d3-c66ac51bbb5d

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17a-3414-79e8-8c98-48c567c591a0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17a-3418-7c76-a6d8-5dbbe23955d2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17a-341f-7ce0-914a-5b724b1baa55
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17a-3425-7fa3-ae0e-8f46b73087df
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17a-342b-7112-a7cf-d524606b7083
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17a-3431-7254-b76a-c16c33d6cbb5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17a-3436-7387-a284-fb357e759331
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17a-343c-7389-aa3c-876fe81e07b5

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17a-4aab-7b8d-a01e-0c74ac9116af
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17a-4ab1-7432-bd90-37d8cf1e2854
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17a-4ab6-785e-ba5d-a30c91f90d30
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17a-4abc-7f7e-84c2-ce06d0571ef1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17a-4ac1-7709-95ad-8f3e17b33784
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17a-4ac7-7000-9fc0-74422caa49b0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17a-4acd-7e74-9929-215506eeb551
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17a-4ad2-7a92-8ffa-6bf49ae854ff

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17a-60d6-7426-a0e4-5d42d2708397
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17a-60da-78d1-8722-0e6d8bb02917
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17a-60e1-72f8-8d72-3afa9914f853
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17a-60e6-7be9-b852-b325c705b9b2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17a-60ec-79f6-bdad-df49bb8070dc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17a-60f1-7132-b250-02b9d0245632
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17a-60f6-75f4-982d-4a3c90d83871
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17a-60fb-77da-89d0-a4a32d0707f2

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17a-6beb-7b8c-91fe-b342e351da3c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17a-6bee-7a71-9e9d-04d45ffd487b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17a-6bf4-7232-8f38-63da8bad1bbd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17a-6bfa-78c5-860d-e9ffa5ed2dfb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17a-6c01-76da-84c8-09e39dd24af1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17a-6c06-759e-baa6-4ccc4709187d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17a-6c0c-7825-8455-aaefed60a292
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17a-6c11-7769-a5d9-436461b08411

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17a-8c6f-73cc-86ec-f9a0fd03a86a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17a-8c74-7568-a77c-5dcf867d72c3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17a-8c79-79b1-b7e8-5bb73a1685e8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17a-8c7e-7cf2-90a3-cd59b365232e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17a-8c83-7c9f-b6e8-1e59e36ff07d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17a-8c89-73b0-a77f-dc5d2fcae2d2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17a-8c8f-7d88-aeb3-6cd9f001f7b7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17a-8c95-7652-97e7-14c1e4220fce

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17a-aa76-73b4-9fd5-0c39f233ea10
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17a-aa79-74d8-9731-89a869c1e1e2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17a-aa7e-70b8-baeb-7909fa9425ff
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17a-aa83-755c-a553-5a91c8f66eb8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17a-aa89-7a86-a0ff-9fad5a89be38
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17a-aa8f-7bbe-8884-221ecbddb3a9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17a-aa95-7de4-8f8e-811c5e95856c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17a-aa9c-7f2d-bdeb-7a814586e22f

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17a-bd34-738b-af83-05e6e2aa2b60
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17a-bd38-798b-838f-25c33907e6e7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17a-bd3f-7f42-b544-b4b414a20858
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17a-bd45-7bf0-851b-1f5293295e66
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17a-bd4b-7140-ae57-e0670558889f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17a-bd51-7535-92f5-f93eb77b1dd6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17a-bd58-7692-b89d-18120d40c22c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17a-bd5f-72c7-911b-a7d9d6d41e20

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17a-d185-7f51-a50c-76d68b20f428
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17a-d187-72de-b8f2-ec1447803055
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17a-d18f-7911-9561-d307adae94f2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17a-d194-7081-b60b-fcd2b1634c7c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17a-d199-7ec6-a61c-bb005ed369fc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17a-d19e-7b20-b1b8-6cc14b3f94cc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17a-d1a3-70ca-ac19-bcc47e44e3ce
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17a-d1aa-7f2a-8688-a7d8015aba6f

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17a-e281-7bea-bb4a-5ab61c3f6339
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17a-e285-7203-95c0-257f5f747a90
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17a-e28c-7ef9-a9bb-fbfa0209ae74
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17a-e293-7913-bd2d-85b7394c87a5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17a-e298-7c4a-a115-52d006b78250
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17a-e29e-775e-8f6c-a26cd232633b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17a-e2a3-7c67-beb0-ceb132f9a3e0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17a-e2a9-7a00-911f-c858f4dddef9

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17a-f639-7104-aca5-6ebbddaeebf1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17a-f63e-794b-bad9-ece6e538891a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17a-f644-718b-a0ff-776e60564d94
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17a-f64a-78a8-8d89-44cf653a64e3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17a-f64f-7814-899d-e1a9e19fb984
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17a-f655-7a53-b6ac-a36edb8a584b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17a-f65b-7b5b-959b-096cfde58e5c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17a-f661-7983-8aa8-6da4b14df88a

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17b-0a52-7ed6-a36b-ed33d88ea482
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17b-0a56-7a36-a6fb-c183dc0b91c7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17b-0a5e-7b9c-8bf2-c7e0fdb2088a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17b-0a64-7cb8-837f-708a5f87ad3c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17b-0a6b-74ea-afb3-077f278f726d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17b-0a71-7600-bb42-eae05845fe6b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17b-0a77-7ccb-a099-ac0e85b98ed3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17b-0a7f-76f7-ba3f-3c47aa507011

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17b-2130-7b65-96a5-1891dc3f686d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17b-2133-7fe7-95da-6a675b5e6c28
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17b-213b-7ba7-8443-b27d112a19a1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17b-2141-737c-9a06-028ef21ef337
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17b-2147-7a52-8005-0120bceab5d4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17b-214c-7555-8e35-0404e86984fb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17b-2152-704b-9d40-799a942916d8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17b-2159-7053-9dfa-3e0352b2c2b0

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17b-4591-7476-b75c-2fe0cf64dc88
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17b-4595-72dd-81d6-2486b1af0999
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17b-459b-7e88-8871-7535dd08f59b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17b-45a1-74cf-b8b8-fc4a59ea2217
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17b-45a7-7df5-a86b-bd43e0f855a1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17b-45ac-7674-bd9b-ddd09fdb9658
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17b-45b2-7134-a471-c548def443dd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17b-45b8-7c27-8800-0ab5f2bc9f38

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17b-601b-71d2-b1dc-2e7a09abe349
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17b-6020-7bcd-9098-900b7c134ed5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17b-6025-758d-a08c-61fb4c01f5e8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17b-602b-7ae2-adf7-2d642ca39171
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17b-6031-72bf-b51f-b3977d619132
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17b-6036-7a4b-b2e8-68513e587ef3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17b-603c-766b-b663-379e99d495b0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17b-6042-71f8-91d7-e83e5d6e6c9a

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17b-72aa-7ca0-8c2d-0fd878fbc4b4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17b-72b0-7fd4-843e-97e87bd88843
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17b-72b4-7a55-867d-4b972436e418
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17b-72bb-7126-9cc3-f50e1be85c4e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17b-72c0-7d08-b7cb-c408156b1957
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17b-72c6-75db-afe2-3c7ac1f3d53d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17b-72cb-7986-b4d0-55d6d03ebefd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17b-72d0-7d06-8c4e-485f93838d22

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17b-8b67-70c2-a580-e81c241d249a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17b-8b6b-7cd2-a705-68e46cf22682
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17b-8b70-728e-9666-c8c0af4c529c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17b-8b76-7731-9bd2-6603f54cbddf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17b-8b7b-7a03-8e4e-bafa09a702d0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17b-8b81-7ff2-8e8d-2dbc0cdc8226
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17b-8b88-791f-aa23-933bdec27beb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17b-8b8f-7d41-8503-fc90c2617532

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17b-9f26-73a4-b1da-3da0a4195f27
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17b-9f2b-745c-ac78-20d4dac03f00
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17b-9f32-73b4-acfc-46e39c4ac6f2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17b-9f38-7e0b-8b38-cac1c6aa0809
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17b-9f3d-7a60-8115-371e728a427d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17b-9f44-7643-9455-3c108260a6df
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17b-9f48-78e8-a838-e0ca510f0580
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17b-9f4e-72ea-89ab-ec69a2968eb0

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17b-b562-7f67-9634-771412b4c04d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17b-b566-720f-b53c-25ca51b2dfa2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17b-b56e-7dd6-91ef-3ba4424faa25
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17b-b573-719f-a0b9-d0b95d99953a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17b-b578-70ac-b976-32d0a702cb4b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17b-b57e-7e51-8f28-b971ebde76a9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17b-b586-7cea-a62a-fcbf28e61424
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17b-b58a-767b-b344-cff6c5e26485

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17b-ce22-7fbe-9c03-2aafc80fc09f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17b-ce28-7aa2-ba59-f0d11dada695
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17b-ce2e-71cc-b387-48c6ce23e3c1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17b-ce32-7b1d-8a6e-d6bc66bc62cc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17b-ce3c-7bae-a9bf-d278b9001709
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17b-ce41-7966-9a41-4203243f69b3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17b-c7dc-7ad8-a5aa-623b5f5ecdc5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17b-c7e1-73c0-ad2a-07f1bfa0a38d

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17b-de55-7b3d-a4f0-8a080f630576
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17b-de57-7501-98a8-3a98096abb70
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17b-de5e-743f-aab4-4d5ecffeec63
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17b-de64-71d6-8fa3-433f550b319d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17b-de69-7ed5-971d-d4db9bae3cd8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17b-de71-7c2b-ad5f-b0b6c65b1ce5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17b-de76-7c0b-b89c-eaa29695ec23
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17b-de7b-7c51-b863-558dc9199cd6

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17b-f464-7f38-bfbe-9b85a4f2dbb7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17b-f469-707d-a11f-7725e065b87c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17b-f46e-7bcb-a734-2be89e9cf694
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17b-f474-7b58-bc7d-e0615d3b8bc6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17b-f47a-74a7-8b5e-c0c7267b674b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17b-f480-7944-a566-907f562c7974
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17b-f485-79f4-89a0-2d3b5f6efd27
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17b-f48b-7038-aa6d-c3e84ed172c9

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17c-0a74-7568-982b-807132f4ca60
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17c-0a77-7776-ac47-6000388cd1d1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17c-0a7f-7570-947f-ab75271d2c20
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17c-0a87-7388-a189-d5f9edc5f170
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17c-0a8c-70d9-8dee-e4792a481384
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17c-0a92-7be5-8e5f-50fed693505c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17c-0a96-7e92-a585-28c2444e2f9e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17c-0a9d-7c2f-80d7-df8059954e88

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17c-25d6-7ad8-9603-81c30f8b18a2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17c-25db-7f80-8a11-e1524e46f666
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17c-25df-7150-b204-790f3b5250af
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17c-25e5-7dac-859c-894ffb5a380a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17c-25eb-7c33-8a8d-3c5a86e608b7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17c-25f1-76d1-830d-aee940b1775e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17c-25f9-7524-84a5-a01014726f5a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17c-2600-7d2d-995a-3d1219661f00

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17c-45d8-7ac6-bb36-1045b650f1f4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17c-45df-7583-8dce-420488405228
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17c-45e3-70e5-a22d-95621402800b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17c-45e8-73d4-aae3-30714428db57
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17c-45ee-772d-b252-05ca98bcb0e9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17c-45f4-73d5-a6b1-3621a8e7c25e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17c-45fb-7d21-8853-7a8d69195f5d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17c-4601-78ca-a54e-6ab535abc037

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17c-69f2-70ce-ad9a-d42b24c21235
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17c-69f8-7e84-8818-38fa20284e9d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17c-69fc-7258-9600-cc468b31f5b2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17c-6a03-7677-b818-a2aa0d3609b6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17c-6a07-7f7f-8170-8605a58cfd78
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17c-6a0e-70e3-ba88-37862c008892
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17c-6a13-7be7-b5f1-63468131868c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17c-6a18-77c6-ab30-bf6fb70e3ee9

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17c-7d2f-7a36-9698-200b0f5b3814
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17c-7d32-7b4f-b01d-8fde2b4ef34e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17c-7d3a-7110-a247-9410b1c5d2fd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17c-7d41-7a92-9855-37470cfea24c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17c-7d47-7ce2-a269-f0d828495852
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17c-7d4e-7c56-91dd-7556e5f23516
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17c-7d54-7afa-b40c-5cb5496d8ebe
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17c-7d5b-78d3-9cb4-3009ee81ea72

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17c-8f3f-78a7-be5e-8ea01f209730
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17c-8f43-7bd0-8e50-175652e98632
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17c-8f4a-750a-bf3b-e38a79aacab8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17c-8f51-7694-8f10-f9d80ea56505
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17c-8f57-7d49-9eaa-c5757ecb0bff
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17c-8f5c-74a2-ada4-c08ffe147773
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17c-8f61-78d3-ac95-36b208ba94d8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17c-8f66-7afb-848a-f3452c58ec98

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17c-ac07-7674-a323-bb46217ebd53
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17c-ac0a-70b8-8a0a-94b574fff61e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17c-ac10-7744-ac42-599fbcede9ea
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17c-ac17-7ccf-899c-4f12c34fc559
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17c-ac1c-7313-a02d-fc23a4888787
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17c-ac22-769b-a43d-f76cd6edd4f2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17c-ac26-7ccf-8cee-7b1e6152c021
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17c-ac2c-7a4d-b092-3390f696457a

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17c-bc5b-7e15-8158-c8445af178dd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17c-bc5f-78c5-bbdd-6d00eca04838
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17c-bc66-7732-985c-3e1b052c7e39
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17c-bc6b-7df2-b0d5-63bb80cece7d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17c-bc70-7b95-b939-11071539196a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17c-bc76-71f9-bfef-361b8eb1a423
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17c-bc7b-730c-bbfd-c70186dfe6e9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17c-bc81-77ed-8910-ebca13bf0476

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17c-da52-7983-a8ff-bd3a36673d4c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17c-da56-788c-88ae-0609fbb9e4f9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17c-da5d-7a1f-9417-34d4db4f4eea
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17c-da62-7565-94ee-e174b6c244af
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17c-da67-7d82-8f0d-04413ef54641
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17c-da6d-7a1f-bec0-c8e7e2d746d1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17c-da72-7fe0-8b9a-9c429442cb08
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17c-da78-7f16-972b-d3b15466fada

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17c-eeed-7f6f-b05c-898377d32f3c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17c-eef1-7b33-ad75-e650dee50f00
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17c-eef8-7ffb-a07c-16384e75ca0a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17c-eefe-7af3-9b41-e2835dfef2da
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17c-ef04-76cd-9f30-d2d0203b44f0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17c-ef0a-7584-8cdf-c4f0088fa956
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17c-ef10-73aa-8280-eda3eb569633
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17c-ef15-7322-9d8f-621116d3e077

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17d-0403-7b3c-ae22-3d7b5a3198ed
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17d-0406-700a-b7b6-c10d72f19f68
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17d-040e-7731-a234-c24694d98510
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17d-0415-7d04-ad6d-fe836d0165ff
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17d-041b-7db0-8082-115663dad56b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17d-0421-79f8-b35d-c6fc117cb7d8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17d-0426-7af1-9545-e8438ad0c909
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17d-042d-7732-8540-942edcfbc25f

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17d-1acd-7996-a686-03903fcfa9f6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17d-1ad1-75d8-9e22-db05c9e1d5c2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17d-1ad8-719f-ab7c-cfb5b05dcbd4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17d-1ade-7069-8c41-78c33d458603
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17d-1ae4-7e98-8e99-7d0ea0f12108
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17d-1ae9-7f4d-a7e7-832ff53893d4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17d-1aee-737b-a5ad-8fcfb064ac74
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17d-1af4-73aa-b5df-0ee7cafcad7b

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17d-317c-7906-b7f3-ad25ba6f8696
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17d-3181-7765-8dfe-14098d83ef96
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17d-3186-7a5a-a8d1-69ea49a3588c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17d-318c-7e10-8c6d-2a8aee1dc4e9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17d-3192-78bf-b980-3519e870c78a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17d-3197-7f1e-b361-a6a5e6481287
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17d-319c-7c23-adf9-7bbb34ff13af
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17d-31a3-78e1-b3f2-633fa217db8e

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17d-485e-7f4a-9759-ddd720baaa68
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17d-4864-7ed2-b0cb-54cb67ba9b50
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17d-4869-7b6d-9fe5-08779feedc4d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17d-486e-71b2-b252-ea0a9b36f0b4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17d-4874-79b4-9d62-d8f0f4dd7882
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17d-4879-7eec-97e0-da19b2b5a685
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17d-487f-7f26-ada6-78455fa3a47c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17d-4885-7a20-83ed-60d11e27e707

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17d-5e7f-7bd9-862d-7df894a9a388
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17d-5e85-74a8-8e9b-bb97b94d4ffd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17d-5e89-7133-8e8c-afd4961af114
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17d-5e8e-7963-a495-9cf970ad18c4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17d-5e93-7628-9f02-80dd1f09adea
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17d-5e9a-7078-9225-1df191633797
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17d-5ea0-75ac-b3a5-d23b8ffb4479
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17d-5ea5-7805-8584-075fca7380f0

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17d-748f-7a6b-b683-39889cb21bd6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17d-7492-710f-9d00-c766a0c7168f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17d-749a-75c8-81e0-62b87c346b1a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17d-74a0-766b-a4ac-6c095de81ff4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17d-74a8-7459-94c8-a25ea28e1a4c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17d-74ad-71f3-89fe-091e9539e9a0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17d-74b4-7671-826e-00fa781fb478
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17d-74b9-7958-9b73-2abf530e1a7c

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17d-9042-7cd3-bc27-cfbc8554f30d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17d-9048-7ded-8c0b-1566969c3b6b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17d-904e-7897-9b0d-8e45531395d3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17d-9054-725a-9be7-24d679fd8e91
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17d-9059-7b08-8eb4-da9fc0e025e2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17d-905e-7a94-969e-e3ab9db87c66
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17d-9064-7cb3-9e04-782304750c87
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17d-9069-7147-b924-5bdf6f5123cf

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17d-a981-75fe-8ee5-bebafcd0fb21
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17d-a986-7be4-9a24-6905d58c0895
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17d-a98b-7cbd-b334-f1e6c5d337b6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17d-a990-76b2-aac0-ce505b9bf42f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17d-a999-7aee-9b1b-381324dde0c1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17d-a99d-723f-8f8e-ce4d779b6a11
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17d-a9a3-72fc-911c-1f78e53d279e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17d-a9a8-7a76-a014-93ae09957401

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17d-b717-724f-94ed-389c3cc1498b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17d-b71b-7c4a-b21c-9ae81e945a56
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17d-b722-7137-b1f8-76b294795d14
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17d-b728-79f7-86f7-3db7a01058b9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17d-b72e-7372-bd60-7e7372f2824f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17d-b734-7106-9f88-5e44dcadcf6e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17d-b739-7b91-9b27-25f2bfb22d3c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17d-b73f-78ad-a723-5dc79e9c30f0

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17d-d146-7f95-82a7-3d4a65a95c4d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17d-d149-7a86-a77b-c01e9b696a26
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17d-d150-7384-b92f-74664c90b5e8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17d-d155-7fe9-95ce-8955e13c7561
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17d-d15c-7f75-8d4f-84afd84f416f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17d-d161-7c6d-8fc1-3ef7b0f329ed
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17d-d167-7eb4-980a-683eb4523e4e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17d-d16e-75df-8e38-91a5d8a145d5

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17d-f322-7393-be34-d42e736de94f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17d-f329-77a0-9851-0b7efd27b789
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17d-f32c-74cc-8441-a2b4482b4885
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17d-f331-79f5-8046-5dddf69d836d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17d-f337-714a-83e8-b0c6efa2d980
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17d-f33d-7251-927b-6ea6218b7952
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17d-f342-72aa-b56a-84df95341bb9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17d-f348-7b8f-8b96-78caede83f08

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17e-0761-731f-9bcb-59a017f411de
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17e-0765-7a94-bc8c-ee5bc7646134
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17e-076c-79ec-bb3f-ef658be561bb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17e-0774-7816-9b85-b11b0af9f9c0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17e-077b-7303-836f-3ec8e4b6763e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17e-0780-72f5-8eea-7aa811c5b3e7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17e-0787-7199-86ec-8e9360dfb066
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17e-078c-7454-9dca-f49b0cc6f894

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17e-19cb-7cb7-aad1-b80e64d171ae
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17e-19d1-70c4-b19d-d6e3d2d5ba6d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17e-19d7-71e3-ba73-c4e9a42520d8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17e-19dc-7e44-877e-2e220efdd008
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17e-19e2-7746-b8d0-049247f69c34
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17e-19e7-7721-8e29-fcb65a78f616
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17e-19ec-7311-b61e-0cef3123e984
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17e-19f2-7003-9d74-ade2a992f6d4

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17e-2a02-749c-a34d-69892b5205e2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17e-2a07-7f05-bd1a-82ef5ac8bb16
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17e-2a0d-772f-9ed8-9fdb3ed4df13
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17e-2a13-7854-81a2-eebd74ef62ec
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17e-2a19-72e7-9578-c838f6b00347
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17e-2a1e-711c-8cdc-153a678d2db8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17e-2a23-7cbe-b951-b5e1e866cc5c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17e-2a29-7e6e-ad24-34deed63bc5e

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17e-3b58-7b6f-a123-5028e7b6c1a3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17e-3b5c-7b7c-8cd5-41760132ab6f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17e-3b63-7070-9251-bc10e21abdfe
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17e-3b69-7f7b-8844-a79a41bc64e8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17e-3b70-7037-a525-e564b5819d43
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17e-3b76-72f9-8ef9-49e22a4d266f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17e-3b7c-7e92-95d9-a593b48b9b0c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17e-3b82-7c23-9815-be50ba5e3b39

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17e-4cf5-7b3c-b9c2-93ad74b00405
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17e-4cf8-708d-947a-e54169f70316
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17e-4d00-786d-bb04-52692469778e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17e-4d05-7b04-910c-0aa3f2e5132f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17e-4d0c-7b67-ba4a-7fc892a9153c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17e-4d11-74cd-9dbf-bf119505d1eb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17e-4d19-756b-b0fe-280f6a7045e3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17e-4d1f-7208-9f0c-9720c12abd7b

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17e-6bed-7e03-9cb4-a4530385d862
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17e-6bf3-70fb-99b3-21619a55958f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17e-6bf9-7591-b172-eb3dd3213fb2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17e-6bff-78fa-8265-4f83540fc4ae
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17e-6c05-7335-bbc7-5a5a8b52e952
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17e-6c09-7351-a409-3f1e2ebd1272
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17e-6c0f-7f5a-878f-b64a279a6323
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17e-6c15-7fcf-ab81-066a6d009ad2

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17e-80a7-7324-92f5-b383dff3be34
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17e-80ae-7a73-80af-3d1bb4e8b0df
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17e-80b3-7dc9-a732-f2cfd4d7e4f3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17e-80b9-7a0b-86bc-1307e0d36265
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17e-80bf-7d7b-a250-e523435c8f12
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17e-80c6-7165-abb7-20304cafe4aa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17e-80cd-75dd-bbee-ce2a4bc67834
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17e-80d2-73f4-a4dc-b5c319e88fb5

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17e-92a2-7eee-8aa9-eb883e941a9c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17e-92a5-7d26-86b5-cd5f1be93b0f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17e-92ad-7f2a-bcf1-cd324c6c0def
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17e-92b3-7cdc-8e97-6841e432d832
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17e-92b9-7ac7-8310-399d0a371d7a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17e-92be-7adf-b55b-69a283d61950
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17e-92c5-78d0-8e0d-d0e3e675e2da
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17e-92ca-7426-8b02-244777976ea9

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17e-a82b-71a1-9b17-bb1fc2e8deb5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17e-a82f-70a4-9be5-18add9682837
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17e-a834-73d9-a3cd-6077f5bcf1c7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17e-a83a-7950-9132-f53ad8cd1067
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17e-a83f-7847-85f9-a4cb80597678
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17e-a844-7bf8-a053-8d30e24adcaa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17e-a84a-7c9b-a214-5090616c57a8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17e-a850-7479-bcb3-5cefbf54e9c7

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17e-c249-7897-a975-ba23b0d184a1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17e-c24e-788d-b067-9e2d56faf72e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17e-c253-7ea2-9015-d06244b51601
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17e-c257-7f6d-ba6b-31c078b91219
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17e-c25d-7e3f-8ca9-842b5423cf3a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17e-c262-709c-8779-8e25e5c7b09a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17e-c267-7085-a140-87329b0dc8b9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17e-c26f-7060-ab8b-d696f72acc9b

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17e-e047-7a7a-bfeb-ea6e266b95d2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17e-e04b-71be-9e99-14e9a8148d4c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17e-e051-78a2-93fd-d82d0070708a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17e-e056-798c-9ec6-fa51de741ba4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17e-e05c-73ea-a856-fe87ff68dea6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17e-e061-714d-b320-769f712aa19e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17e-e067-7240-a5f6-438c3db74c29
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17e-e06e-7bf1-b763-6bd1aa196f04

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17e-fb8d-7bbf-b6a0-af3331c348c4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17e-fb91-7c05-9c53-536619c28db9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17e-fb97-77de-85c0-d8714a908cad
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17e-fb9c-7999-bb55-07a95a8af3b5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17e-fba2-7969-9f21-bcfe4900336d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17e-fba8-7bbc-a184-73a06d3df5ff
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17e-fbad-78f1-819d-d05ae7ee544a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17e-fbb4-7d84-92b5-88f72b30292b

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17f-0cf0-73fc-aef6-61fc6eabdb4f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17f-0cf5-7d03-b8e9-2fab8d68f6e3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17f-0cfb-777f-b7a3-a0c3d065d8e2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17f-0d01-7619-a1ba-f5ba9b448373
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17f-0d08-72aa-a712-5826c10607f0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17f-0d0e-7d14-b396-718625bb1b51
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17f-0d12-7bb4-b9ad-8e8a2f534e73
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17f-0d17-7413-aa4e-57886dd9ebdc

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17f-1ad9-75ff-8ef4-6102e80cda67
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17f-1adc-7d87-8dc5-2905b38cf4db
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17f-1ae5-7e44-94d6-f92d1d4e1809
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17f-1aea-7f54-aa0d-74efe234e137
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17f-1af0-7f5c-9883-ed24a9657cda
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17f-1af7-739b-8927-975a6fd3788d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17f-1afc-7e95-ba19-37eab7fa882b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17f-1b02-7dc5-8ec9-4ccea9ab03f1

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17f-31c6-7ac9-824f-e65abad02914
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17f-31ca-7acd-bd5d-abd4d8643916
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17f-31d2-7227-9757-03121358e636
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17f-31d6-7266-9e0c-7f43a857a2f8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17f-31dd-7066-a751-01947bc82c24
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17f-31e2-7ffa-b236-e4fb4b41d8a7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17f-31e7-7f78-b117-160c7c1d50d1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17f-31ed-79f2-bc45-aefd6a68ce10

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17f-4882-75f9-844b-948c92873efa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17f-4885-7b79-98db-1083d1bd474c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17f-488b-7f6f-9c22-8640e12a39be
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17f-4892-7e1e-afed-98bc700b7474
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17f-4898-789b-839d-00a1f7c18135
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17f-489e-7116-a267-05dbf0acbde7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17f-48a3-7479-9835-06354590b565
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17f-48a8-7e16-bc75-b80296320b36

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17f-5c6c-7654-8344-25a3834130ff
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17f-5c71-7078-8459-8c2dd89b4358
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17f-5c78-7ebc-bc89-7a6dd594f896
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17f-5c7d-715e-b21f-1af19729aeb7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17f-5c82-7d6e-ab6e-13278696ec57
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17f-5c88-76f6-a3e4-208a3535a533
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17f-5c8f-71f8-97a5-fce8d84c3df7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17f-5c94-702d-894c-e795fa82a826

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17f-77f8-7ee1-ac26-48ce1ddf75fe
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17f-77fc-7b3e-9a87-7da5a13b7487
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17f-7802-7462-9e1b-a3e8c0f5253f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17f-7807-73da-a28b-13e4eeee5b18
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17f-780c-7c8f-8432-7e945654cfbf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17f-7812-78ec-8b9e-173b1081f1ad
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17f-7817-794c-b0fc-0755feed62e4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17f-781f-7b6c-9a0e-3949ca0ab69b

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17f-85c9-7cc6-a27e-f2a776902485
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17f-85cd-7abc-b0c6-daf86f175f20
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17f-85d4-7fbe-b3b4-dc6fee5fec54
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17f-85db-7082-82d3-43c12416b681
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17f-85e0-7829-a740-a0434f551bd1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17f-85e6-75ed-a671-c1af3fe732b0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17f-85eb-7f8f-92ad-ffe2d83d8306
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17f-85f1-77f9-afcb-afcfb4137f6d

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17f-9889-74b7-9fff-1ff948e190fa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17f-988e-7342-9b3d-e545e87a7b59
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17f-9895-74af-9988-86c8eab23edd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17f-989b-72c6-bdc8-36c36c06ee3d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17f-98a1-746f-a96b-5d3c324fa520
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17f-98a6-7630-a09f-1f8cd85da335
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17f-98ac-7996-a3b1-4a962d2ed3ca
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17f-98b1-760d-8bf0-c0ce1fd5f812

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17f-b207-777c-ac69-ab57fc6d6424
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17f-b20b-7f19-a5fb-0adb750599c8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17f-b213-7978-9d67-2d9cc3cbc316
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17f-b217-77c1-9833-bc79f4aa2887
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17f-b21d-7e7f-b6a5-1e22446b7a9a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17f-b223-7f24-abe9-0c833a923990
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17f-b228-7c63-92ea-14a1df237148
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17f-b22f-7bc4-9995-6db3d27a0ce8

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17f-c8c8-71d6-af89-9987d9fed681
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17f-c8cd-7f0e-a299-153bc4df7007
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17f-c8d4-7c1e-82b7-b91ec712f3b3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17f-c8d8-79cf-8279-ef3130d6e2ef
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17f-c8de-71d5-9878-193826dc5bcf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17f-c8e3-7c43-9f49-115d9a2257cd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17f-c8e9-7e14-9394-7b9f8fdb60f3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17f-c8ef-71c2-baeb-a083cad92302

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17f-e252-7fc6-9e4e-538121f342b3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17f-e257-7501-af36-a41ef17270dc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17f-e25c-78d3-808f-628bb7a3cc7e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17f-e262-7e9d-8135-738c77bbadc4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17f-e266-7707-aa02-d4eab7261755
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17f-e26c-768a-a76d-385af54cf243
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17f-e273-7c03-9d83-73786fcb51bb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17f-e27a-7493-b8ca-2634046036f8

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17f-fab7-7878-9da8-3af6bace4710
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17f-fabb-7b8b-9d81-38747a4dbf46
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17f-fac1-7f9c-bf08-4785abdbe614
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17f-fac8-7cf3-9d9e-384c2ae39b99
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17f-face-7511-9b39-c8dc3a77a357
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17f-fad4-72e4-9409-5d20ac9550ac
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17f-fada-72df-8603-353e834fd146
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f17f-fae1-771e-91bd-f55040203a77

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f180-04b9-7554-8bd6-5410e1ac4442
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f180-04bf-76a1-a8e1-90abdeb32435
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f180-04c5-7d7d-a9f2-42662b470ecf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f180-04ca-77fa-a96f-141e0e7c1fbd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f180-04d0-7cd4-9abf-824f4291acac
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f180-04d7-7307-9fd5-6996bfb3c0d5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f180-04dd-723c-8909-5aa2da2179f8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f180-04e3-72b9-9951-00b3a0acd527

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f180-1f29-77ce-b37b-0b05ad14944d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f180-1f2d-755f-811c-13f7dec705a0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f180-1f33-7cdd-ae90-78a93be6a4f1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f180-1f39-7753-b441-89be410fff70
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f180-1f3f-793d-b4ba-edf909f6fc38
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f180-1f45-7721-a3c8-8fffb908eb07
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f180-1f4a-7927-971b-7834e5150ef4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f180-1f50-7fee-958a-34febf705f74

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f180-309b-7d3d-81a8-fa8baeba730d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f180-309f-7fe9-bd50-5dcb14c142e6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f180-30a8-75b7-a21d-026c1f841d27
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f180-30ae-7316-a762-b59997e91564
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f180-30b5-7925-b342-44a73b3d7c49
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f180-30ba-70ce-860f-7d116defc863
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f180-30c0-7b09-a96e-59192c8b1daa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f180-30c7-7f03-bf01-94dd73595e43

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f180-4df5-7825-800f-b96f509ad8f0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f180-4df8-756c-b923-ff2779f6148b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f180-4dff-7f52-b8cb-4c9bfcee1ab7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f180-4e05-70b5-8bff-261dbf5510a2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f180-4e0c-7d1b-afba-bde265f0953b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f180-4e10-76a9-b408-6524ab074363
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f180-4e16-7ddd-9fea-0fcefcb85a68
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f180-4e1d-7b1e-ae1b-25dae88f47b6

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f180-64b5-795f-82c6-c4aaa89eeaf2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f180-64ba-72a2-96d8-8600c3dee7a0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f180-64bf-7a36-9a32-020b93b21674
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f180-64c5-7b9c-b37b-294d10c61d9c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f180-64c9-7e2b-9f71-e408ba0ffbd8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f180-64cf-7aa4-8c6f-03de3880130c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f180-64d5-72ab-9ca1-8f337980049e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f180-64d9-74fd-841e-9bec34c11128

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f180-79e5-7382-a4f3-ef18c8628b2c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f180-79e9-7c95-9b58-f768a44d4c37
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f180-79f0-7b8d-bf24-3bae386c4c41
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f180-79f6-7f81-92d6-9d8edf631030
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f180-79fc-7e2d-8628-5a74c29303e2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f180-7a01-753b-b0c4-9e7cafd76a85
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f180-7a07-75fe-a9c1-775a799289ac
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f180-7a0e-78dc-a310-d782a765f2de

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f180-8acc-74ca-8606-aa061ade0370
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f180-8acf-7736-bd34-77c4433494c7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f180-8ad6-7bb2-84f1-78843edaae36
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f180-8add-722c-88c8-4e3d38607d95
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f180-8ae2-7802-8737-c2c93300798f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f180-8ae9-7e45-b3ba-cbe21f4a3f15
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f180-8aef-77e0-a90e-9b4f269e3a03
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f180-8af5-7a2d-9e16-64581d02beb5

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f180-a321-7577-b9d5-b8aafb3cad5d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f180-a326-7f35-a3f7-3348d3819641
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f180-a32a-7d8b-8735-d4402171e525
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f180-a330-70ca-a7f2-2708640d02c3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f180-a336-7808-a028-c19479a0968a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f180-a33c-7aea-bbe3-24b4ce8a3e77
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f180-a341-7f33-a1ea-99d56788ce3b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f180-a347-7107-a9b6-a0966be4a5a5

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f180-c45e-72c9-9131-4b53ff1a48e4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f180-c464-7f06-b67c-78a7d224b04a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f180-c467-7f76-bc14-c30bf46e6b6f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f180-c46d-7db2-b97b-078a28482e68
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f180-c472-72cb-8652-9fd3429ed1d4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f180-c478-70ce-af3a-06023f287dc4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f180-c47e-7109-8d33-a384fae30cff
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f180-c485-7b8a-bb7f-e7e1d4c2ebea

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f180-e600-7dbb-b9ae-476e65c62c17
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f180-e603-779c-b3e9-d67fde2479cb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f180-e609-7bfc-abcf-7a8f98e502b7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f180-e60e-7e5c-8b66-756735673d5f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f180-e615-7d1b-afae-cc4367d84726
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f180-e61c-7fd6-a2e8-a55b84c0891a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f180-e620-77d0-a563-594cbc935784
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f180-e625-7c4a-8bc1-bc824c735888

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f181-0149-7da2-b751-22bdf2dfcd0d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f181-014f-7e88-8abd-79c20a53077e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f181-0154-7f16-b412-ef82b03d6977
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f181-0159-74d7-80a8-9aa9fcfe163e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f181-0161-7a42-910f-0b8a5f1c88e6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f181-0166-7f87-8f6c-a98b4d82be92
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f181-016c-7bf6-b4d8-6ef059225300
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f181-0172-757b-acf2-8b75d719e629

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f181-1727-726e-8dd6-ad1305645502
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f181-172a-73f0-843f-cdd9fdf87c2a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f181-1731-7445-9702-223e63e40396
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f181-1737-7d78-abdb-0bce7a9938f0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f181-173d-7a3c-82bf-a4491a7d3133
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f181-1743-7d5a-9999-674d76504f00
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f181-1748-7451-83d3-054fd1b83f40
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f181-174e-748e-8ebd-da3770f745a7

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f181-2976-7ddd-a264-d411d3802327
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f181-2979-7a43-b3e8-064a07fad48d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f181-2982-7287-a29b-a644d30f91a2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f181-2986-770d-9879-63825b82b98b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f181-298d-7a17-b1eb-f2709d89afc1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f181-2993-7ede-a499-b9e98d74ae1f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f181-2999-7547-a6d0-8f754f04a3dd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f181-299f-7ef1-b6d9-a1f7805505a1

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f181-3b5d-716f-a236-2fa1ed9edc66
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f181-3b60-7b22-ac72-c977e816fcbb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f181-3b68-7320-a4d3-1c53631d00e1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f181-3b6d-729d-949e-22a2191cd997
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f181-3b72-7ead-bd4c-9a6214285b95
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f181-3b77-71c5-8e35-e36500426a12
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f181-3b7d-7e92-9403-7a6fd80c1542
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f181-3b83-7dea-9ab2-97beecdbc129

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f181-54c6-77ea-b36f-4d470db20dec
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f181-54cb-7dfb-941d-b8475d0050e3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f181-54d1-740d-a3ec-9a9c380eb54b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f181-54d5-71b6-b01e-eaba8231ae43
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f181-54dc-70a3-ba5c-869cf7d9ec5c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f181-54e0-7e47-932e-cc1f4b49275d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f181-54e6-7fc4-8ed4-add9b7dcb584
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f181-54ec-72ae-abcf-2668d52b6cb7

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f181-69b1-72fd-9958-609655d37702
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f181-69b7-7da9-a8ef-7743884c5978
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f181-69bb-747c-85d4-e76f75a4a0a9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f181-69c1-7493-8448-f6cdd2ed6484
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f181-69c8-78ca-a7d0-aa23aa6180f2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f181-69cd-7e79-809b-ced0eb59547e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f181-69d1-7778-ab7f-126861298601
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f181-6379-7b67-ac80-909e654e1606

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f181-7642-77cd-95d8-fee3513d1c72
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f181-7647-798e-a385-c365cf329564
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f181-764e-704c-a6c5-39552d1a4036
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f181-7654-771c-b1d0-5fa5b9246ae9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f181-765a-7af5-8bba-ebc41a6134e7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f181-765f-7ef7-88bc-23ac46f2819e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f181-7666-79e7-8c51-94192e9f6d8b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f181-766b-7abb-abee-f71265710c9e

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f181-9371-730f-88c6-31ae50d9052b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f181-9375-732d-988d-98083a5939a4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f181-937a-7a77-b664-473680ba23f1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f181-937f-742f-b8cd-4366eb336633
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f181-9386-781f-beee-ac720a8adb65
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f181-938c-7717-a8e1-1a0b8feb8b38
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f181-9391-7463-9f67-98d323b9ec56
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f181-9397-700b-a543-223e9fea537a

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f181-ac2d-7656-bed7-782fea3fca57
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f181-ac32-75c2-b318-5fd74b19642b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f181-ac36-7bad-bc5f-e077a19f1ff7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f181-ac3c-7de9-8885-7e3d88f7b66f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f181-ac43-79fd-8492-53e9a26d67d1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f181-ac47-730a-b823-80058f52c1ad
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f181-ac4e-7961-9472-30e752d7c70f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f181-ac53-7c59-a249-44d229ce1cfe

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f181-c6a4-7e74-a7c0-a9148050a805
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f181-c6a8-7ffa-9d15-f3cff4c70460
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f181-c6ad-7ad2-a734-1f230d9fa0d6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f181-c6b4-7306-9f48-c18fe802c283
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f181-c6b9-7a49-8c42-4178e80acd82
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f181-c6c0-7ee5-98eb-56e92168a31c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f181-c6c6-7a63-ab4a-eba2f2686f39
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f181-c6cc-7eaa-a53d-2360442caf44

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f181-dd0e-70e0-8703-692b721d1001
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f181-dd14-76eb-b7a7-48543c8b5ec4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f181-dd19-7033-a1d0-ee048336b061
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f181-dd21-717b-8d57-308c6329a9e9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f181-dd25-7cde-9988-94a12214523d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f181-dd2a-798a-ba50-ca563f688aa4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f181-dd31-7168-8f18-00635a819f2b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f181-dd38-771f-84f6-61fa11faa0a0

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f181-e861-7c5b-929a-8b957ce0a2db
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f181-e866-72db-8cb6-522b48aa72ed
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f181-e86c-7583-95b7-4a86d3384357
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f181-e871-7838-8d9c-cd25966b2dbb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f181-e877-723e-9176-bdcfb15a97fa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f181-e87d-7dff-82e0-af29d9828738
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f181-e883-7281-b21a-4e63ef3561b6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f181-e888-7eb6-ab2d-7dfb3c07afe2

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f182-005f-796c-ab42-624c1dc3e8b6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f182-0063-7599-84a9-0b4bfbf7797a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f182-0068-74aa-a00a-6c6a227344ce
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f182-006d-7cd4-9027-c7ef7e8b7937
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f182-0074-7bb8-b7b7-8fef67d26f73
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f182-0079-7f8a-9a1f-4c250a644c33
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f182-007f-7d07-964f-65489e5cc277
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f182-0085-75b7-a463-ed6999803ba8

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f182-251c-7cff-9544-40bbbc24fb0b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f182-2521-7514-b927-a6b189b278e4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f182-2528-7504-ad43-6396a22f8307
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f182-252d-7359-9847-dc5c5de658cc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f182-2533-7477-b007-ea37f5124e3a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f182-2538-71d4-a04b-d13c012b67f5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f182-253e-7145-9deb-fe9263fb2f1a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f182-2543-797c-a0c0-80e5dbe98f49

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f182-3c16-75c2-9e77-0898dd7b9b8c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f182-3c1b-7600-884f-df4bf2bd4161
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f182-3c22-703f-ac96-25d8892acb49
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f182-3c26-7c3d-8a20-e01d9b94b065
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f182-3c2b-7c2b-b6ef-312806b64b4f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f182-3c32-7b0e-9dac-bc8432706235
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f182-3c38-706b-aad1-fdcd4015d266
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f182-3c3e-7728-b13f-ff343e09ca05

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f182-5632-78d1-af8a-11d4d6a8ba77
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f182-5637-7810-8493-72b755121a89
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f182-563c-7a70-a54f-4efa3c9abc55
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f182-5641-79d0-9422-81d7edfed1ff
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f182-5648-75a9-ad88-a6e887f51d7b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f182-564d-72c5-8612-4693292e2e91
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f182-5652-7406-a038-0b1964be319c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f182-5658-7250-877b-7a0e3e934452

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f182-6941-7872-8db2-c33491f8078b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f182-6945-7371-9478-64697dbb319c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f182-694c-7332-afcc-e99e5dd67edd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f182-6952-7f81-99b6-be7d1c6528fd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f182-6958-7ee9-b7ac-1b07a75f9940
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f182-695e-76b6-abf8-99538045d8f8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f182-6965-7993-b9cc-c81357b6e784
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f182-696a-7521-b0f3-98d22786a63d

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f182-7c20-7509-bc9b-64c76223f420
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f182-7c26-74e0-852a-28a2d0f9678f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f182-7c2c-79f4-8baf-dd25c71e4456
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f182-7c31-7d14-8775-05ec34fc643d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f182-7c37-78ec-ada5-7ebd7c341ff0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f182-7c3d-736c-82ba-f369f788ad7d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f182-7c42-7841-9b5b-d7c521dac6ca
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f182-7c49-705f-a950-fb213bda06dd

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f182-9459-7c17-b199-9ae24a2eeb2b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f182-945e-759b-89f8-c0d259acb578
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f182-9465-7003-8626-27c20ef4efa2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f182-946a-759d-9aaa-56110c120203
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f182-9470-730e-8056-880885c76668
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f182-9476-79dc-802c-8e9c7120abfd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f182-947c-783d-b70b-6aa27db3881a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f182-9482-7cc1-ac3b-d0c645d06a4b

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f182-b381-7c58-8f01-2764610c2ab4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f182-b384-73eb-8280-7fb17b612a79
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f182-b38a-7b01-807c-8dc7aa4d0203
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f182-b390-763c-91bc-1a801ab5a15c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f182-b396-77a2-b964-a9524c2272e5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f182-b39b-7ff4-9c03-ef4edde1a04e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f182-b3a0-7c13-838c-51a8f17da00a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f182-b3a5-7976-93f3-837be8b37644

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f182-cc3f-7492-b7ed-0dbe17a54fff
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f182-cc43-7021-98d8-469cc8b09147
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f182-cc4b-757e-8dde-131b21adf594
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f182-cc51-78a4-8415-527a87ce9bee
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f182-cc56-73ae-94d8-d5995ca89615
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f182-cc5d-79f2-a297-a9191f539a02
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f182-cc62-795b-a733-edfa4b303d35
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f182-cc66-7ef7-b305-bcf093533d17

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f182-dd41-707f-a12b-d01331533335
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f182-dd44-7528-b796-7911afa31a86
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f182-dd4c-7c84-808d-ccb02c0e1ae2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f182-dd51-7b78-a31b-c7133a7206e6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f182-dd57-70de-b837-a848dd1f3c67
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f182-dd5c-7e82-a08e-dd73962712c3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f182-dd61-78e7-a1fe-02d92c58bbe9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f182-dd68-75b8-818a-678a59c91fe3

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f182-edf7-7db7-975b-34f0ff25d8a7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f182-edfb-7b23-a74a-d4a9c111064a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f182-ee03-730c-a1cb-da0c9cf8ba03
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f182-ee08-7674-bc33-1d74f82e0844
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f182-ee0e-7fe1-a633-4ecfee0e37e3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f182-ee13-71ee-ad45-905a94fa31cc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f182-ee18-7a77-93e1-ec9933718254
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f182-ee1e-71de-b62d-9c9a74af6ec7

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-0099-702f-a749-8b13270b32a4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-009c-764e-9781-19c4739f2b94
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-00a5-79c4-9c30-3728b07ef7d4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-00a9-7515-a893-4e43fcd39aa6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-00ae-7fc8-96ce-b7a78e233a94
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-00b7-7d9a-b17c-bfb63c7c5e7c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-00bd-75e7-9857-afdee8bfbeea
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-00c1-7c4f-a08d-7ddcf77eae6c

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-197c-7c7e-8782-05137a41552b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-1981-7df5-89e8-0a9b3e01c020
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-1987-78a4-8475-7b2abe29b119
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-198d-7cde-a9b2-31de15acac03
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-1992-75d6-8ce8-25c1ab0a96a7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-1998-7c8e-8184-c6feaf5f307b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-199e-7940-8e29-93665aecfaa1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-19a3-757d-a474-4350a1be1a8d

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-2c62-7084-8a7f-c7c4f0ec9b8f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-2c66-7cec-869f-57ab615c8baf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-2c6f-7096-a724-a0e36e788ad6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-2c73-7d77-b01a-fe9fbc40e607
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-2c78-7685-92b7-77a26e14f4c4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-2c81-7fca-9bd0-91b364841113
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-2c85-779b-9254-1f1a66db95e9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-2c8b-70ea-a11d-5a8d1bf3ac75

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-45f7-7d70-a36a-6257ca688942
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-45fa-78cd-a5d8-349a51ac8ed0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-4600-700b-897b-f927945fa050
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-4607-741f-af81-684102b2148e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-460d-7124-a07e-db4cb4a37bd4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-4613-7d4f-8ea3-ebb617034f3f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-4618-7fc4-a831-af7e5ccd2217
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-461d-7893-ae7e-860fe69758bf

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-506b-7a9c-9af7-2febe1ff2f47
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-506f-7681-94dd-4bdd6e0262d0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-5075-7860-9216-e473f00fa71b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-507a-7e55-bb10-081fbe1f93ad
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-5081-7f2d-939c-6b72e078256e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-5087-7480-8824-4d62c3033ac8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-508c-761a-ac45-702cf63037ba
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-5091-713c-951d-fb7dd4721b8f

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-6a01-727c-b22f-cedfc18c5fea
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-6a04-756b-a099-315692741160
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-6a0b-72fd-8608-0d476e751307
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-6a10-7627-ab88-d099cbf1ef3a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-6a17-7d19-93f9-37176ff8ed30
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-6a1e-77a7-9ccf-1b31c607e1c9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-6a21-7169-8a0a-f4fe009464ec
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-6a28-7bd4-9e9f-2604020ff394

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-7ecc-7f05-886a-6feee94dfc13
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-7ed0-7b0b-8de3-cf424bd895ff
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-7ed7-76d4-881f-2a0fc4b1932a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-7edd-733a-8b25-e272b50a04bd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-7ee2-768a-b743-75f2f71881e6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-7ee7-7437-8daf-7a2a03e27616
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-7eee-7952-b8d3-b0b85b960233
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-7ef4-7d07-9a3b-d85ad11f93cf

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-8f2f-7a89-b37f-0ce645c24cd5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-8f36-745e-af4b-9d46edae74e2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-8f3b-74b1-b137-3a341296156a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-8f40-733f-b3f4-9d12fc0e3dbe
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-8f45-7742-8634-d71ccca0fe30
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-8f4d-73a9-bc2c-f05641119de0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-8f51-7dd9-9c70-2d5c030f67a1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-8f58-749b-b5fa-c492056029ea

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-a86d-7583-b3ea-604260d02b3f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-a872-7e81-8ece-70193f288303
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-a878-70da-a6bd-7126d9c19346
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-a87f-70c6-a5a1-2eae2f786332
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-a884-7d14-8f8d-dabc6f9d7f59
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-a889-7835-94f6-5da48efe06a6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-a88f-7618-90cf-46c1d9570a31
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-a896-7a45-a60f-acd5a6add5e8

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-b605-758d-94a0-3c8b9bbb207d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-b608-71e9-a506-b1941aae2c14
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-b60e-7d34-b1a9-9f800b8956f1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-b617-76ed-a8e9-462f3d8d4ef5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-b61c-73db-8664-c15c8e67ff6f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-b622-7b22-987d-c65d23513811
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-b627-70cf-a914-76cc9709a670
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-b62e-7518-ab5e-d5eb7ca4adcc

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-cce1-7718-831b-09bbc9847a34
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-cce5-738e-96e1-969dc7327da0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-ccec-73e0-a0a4-757aef9cdf17
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-ccf1-7900-8be8-a5828c8caf62
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-ccf4-7685-8af8-35c274b94ade
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-ccfa-75b8-84bb-5b1362aea0f2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-ccff-7168-bb71-a4f30e6b36ee
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-cd05-7d58-b45d-0f368c50db63

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-e368-7cb5-9236-05ec9484fe12
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-e36c-7eb7-9e04-997fc49c3141
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-e374-77af-a86e-2565e3a9ef72
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-e37a-7ecd-b548-062e46cb4de6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-e380-7b3c-b54d-f21e898ebb77
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-e385-77b6-b3cc-0382abf3b6d5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-e38a-7507-abaa-8a0ddba1245f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-e390-7d3d-8f14-820969544af7

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-f988-79dd-99e1-e670ab7a1ab1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-f98b-7fed-b88c-c4686549cf5d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-f992-7c6a-a48a-39e092b7aa49
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-f997-7be5-a20b-9b2c76a1ad12
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-f99f-7715-aa39-193270330c56
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-f9a4-71a9-b194-30277285d22a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-f9a9-7840-8947-d00d9fcc3d4f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f183-f9b0-76aa-a65e-ff2ba6ebbfe4

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f184-16be-78f0-a72e-ee5961a1efce
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f184-16c1-75a2-845a-b18b689d31cd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f184-16c8-7b3f-a441-e218eb852a29
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f184-16cf-7b73-a756-84db4f7b5e8f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f184-16d3-71b8-a6cc-d2d356c39685
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f184-16d9-7620-b057-879b101c917d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f184-16df-7f04-8d73-aafe16b41b17
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f184-16e4-7d69-8d3b-06c21c73fd06

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f184-34ba-78db-bf8a-8e571cb84d44
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f184-34be-7e77-85df-fc19f98a01f4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f184-34c6-79bc-bcdd-725ebec86301
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f184-34c9-788a-95d1-404497ca5b25
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f184-34cf-7ff0-9073-ceaba4753e68
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f184-34d5-74ed-88ee-b5ff26bf6798
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f184-34db-7fd3-b99f-81099dfea23c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f184-34e2-7620-acdb-8da22326bb37

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f184-4307-7cff-b17c-03b251afc80a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f184-430b-7db0-9388-661571b9a750
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f184-4310-705d-a532-5bccd0f1332a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f184-4316-74a3-aecc-35a7a05073fb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f184-431c-7661-ac78-c180d7b45df2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f184-4321-7fc9-83db-d0b147ef1915
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f184-4327-736f-8aed-4fe38888e03a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f184-432d-74bf-ba14-0d5ddd9ba6f6

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f184-5400-735d-9897-d5544f547426
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f184-5405-7cfa-a4aa-c7f4df32a8ae
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f184-540c-70ff-a177-cf96b9dc7c12
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f184-5410-7764-b7fe-95fea809d997
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f184-5416-72b1-a75c-30a3fcafb2ad
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f184-541b-7dec-afb5-d8790ed9735f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f184-5421-7c81-9241-1262cd7a5acf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f184-5427-763d-87df-ef8037b05c0b

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f184-6a6e-77aa-a223-10bd8032a18b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f184-6a71-70f5-b353-e219a953bbe7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f184-6a7a-742d-905b-bea48cbd501f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f184-6a81-70dd-aa53-2334db293c16
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f184-6a85-7646-a043-3667d9c92ff3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f184-6a8b-7735-b9e5-13415e312fe7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f184-6a90-7b17-b5ff-d2845abaeddb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f184-6a96-709f-84c2-5676fd45af5d

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f184-7c31-7717-a2ec-2cd83d55b143
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f184-7c35-7527-81f2-a37b75790a62
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f184-7c3c-7569-85c0-41fa5eafad8b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f184-7c42-7af2-bc4f-6e8d2089574f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f184-7c47-7e40-b53f-477eed3e4aa2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f184-7c4d-7f98-80ef-d4614b5dabe9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f184-7c53-7a52-a97d-12295716f58d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f184-7c58-7185-8bd8-c53c33e1fcf1

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f184-8d42-7fb7-8216-6e269952df38
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f184-8d46-7a70-9662-15f1637fa9aa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f184-8d4d-7038-b1e8-b2143e2ab19c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f184-8d52-7e37-b270-9fd510ffe8ea
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f184-8d59-7690-a5bb-5d1170dc74cd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f184-8d5f-7848-b348-8e02d1f8f1eb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f184-8d65-7ad6-91ae-a17688ac161d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f184-8d6b-7d29-9c62-2c38d236cf10

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f184-acf6-7433-8741-2f60c87520a0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f184-acfa-7685-990c-a9b94b932699
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f184-ad00-74f8-9e14-88187d59a328
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f184-ad06-78e0-bbc9-be18f087dc7d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f184-ad0b-746a-8a35-bad957f364b0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f184-ad10-75c7-b519-1e2ad297f128
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f184-ad16-7e3f-bd39-17d83113be3e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f184-ad1b-7d2d-aaa5-f9cd920cca6c

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f184-ba57-7192-bdfe-ceb1e2d7d4c8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f184-ba5b-77c6-9882-6bb23c1de807
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f184-ba62-7fa8-9073-90902fc854b9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f184-ba68-7fe0-9447-0ae28763ea7b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f184-ba6f-7dc6-b9fe-daf5e6dac4ca
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f184-ba73-74e0-80fc-d37ca866bdd5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f184-ba79-7161-b425-a3241c39a4ab
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f184-ba7f-7da3-a133-c227eaff881e

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f184-d5b4-7e21-9a96-d3b15ec47ca3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f184-d5b8-761d-abb9-a1425b6933fd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f184-d5be-72b2-a759-f283c6033ab6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f184-d5c1-7d39-b5ac-3d3751a65041
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f184-d5c9-719a-8bb1-19824d5fe2c6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f184-d5ce-755e-b091-2c5933c52fbf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f184-d5d4-7bc6-9a61-3b0440a2fadf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f184-d5da-714d-8098-bc8434d329cd

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f184-f541-701a-9986-bec661038b60
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f184-f545-7b80-beff-543c228741af
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f184-f54c-72b5-9329-dad80e44d31a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f184-f550-76e6-8896-60f653a0a01e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f184-f557-7e65-bdff-7001be9df533
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f184-f55a-7bc4-86f1-63c08384270c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f184-f55f-78e7-a970-520e390ed3aa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f184-f565-7678-bc99-ec3969cae92d

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f185-087f-7448-b0f1-0fa4de5ac4b0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f185-0885-7eb5-8540-6c1d9a9a8481
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f185-088b-7166-9410-0d2d4c86906e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f185-0892-7942-a726-3f4b5876f41b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f185-0895-7afb-a8c0-16aefde3b3ed
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f185-089a-7115-8667-fdf434e5927e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f185-08a0-7f6c-a82d-246b4e4b2d8f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f185-08a5-7962-b874-43cce24d930c

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f185-23bf-7baa-a86c-423995004b83
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f185-23c4-7603-8dd2-ca391990ece7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f185-23cb-709f-8b6f-7851348b4e69
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f185-23d0-779a-95cd-3355bc0ec41b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f185-23d7-7e8e-891f-c8cab7c755d4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f185-23dc-7c00-ba62-c6b19ebd9881
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f185-23e4-73b2-9e59-02b8b7e0066f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f185-23e9-71c4-8461-5dfce0e1f347

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f185-3e8f-7118-952d-d99c1e946af7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f185-3e93-7770-b4e9-738f645640ae
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f185-3e98-7efe-8e9b-7d32b3b97d65
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f185-3e9d-7ea5-a980-a4d3c8adfcbf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f185-3ea3-7f0c-bc1d-b471ee13b033
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f185-3eaa-7281-8833-df3d91e15e2c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f185-3eaf-7138-a720-e7cd213f53f4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f185-3eb4-7279-a81c-0bc112210f03

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f185-5091-7b6b-ad6f-1011f21eaf92
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f185-5095-7852-b026-721c190d0c58
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f185-509d-7bbc-bf96-20b1bdbbc868
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f185-50a3-7581-b64c-fb3072ea20a1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f185-50a8-79d0-ac90-80d6c0249583
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f185-50ae-758e-92e4-21597b1ca229
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f185-50b4-74a6-8e78-3d388f48ec2d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f185-50ba-786c-880d-c097a20ceca5

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f185-6d98-7bd6-bdfe-ec54cb51ff73
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f185-6d9d-7563-a4fc-f39600b53faf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f185-6da3-7bfd-bc25-d285f2065132
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f185-6da8-7179-9359-b04d6fa56f28
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f185-6dad-76a3-bd82-2b0a6ca2216e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f185-6db3-7aa8-9d27-3e16024481f9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f185-6dba-7066-ae31-91900d134e80
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f185-6dc2-7b1c-982e-a25cb53811cf

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f185-8493-7dbd-a096-6586c4bf16d4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f185-8497-7352-b3c7-5c1628490bd5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f185-849d-7b1d-9785-f4cf5d43dd31
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f185-84a4-7a92-bf32-a84aa1104479
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f185-84aa-76b6-adb4-b55db48cb273
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f185-84af-7c3f-8716-ac61abab0576
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f185-84b5-72ef-bebe-fb312e7baf44
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f185-84bb-7e27-80e3-10d4c6d38def

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f185-9d99-7d8e-97d8-c84f53965f30
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f185-9d9c-7ef3-a578-c68718a5b1c6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f185-9da2-770a-838b-8996e6808646
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f185-9da7-7872-8abb-d78fe56ceffc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f185-9714-7339-b8eb-22c5adcca5e8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f185-971a-71fe-9858-91171f0ed863
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f185-971f-7357-b2c8-3f2b2b7222a8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f185-9725-7b24-93ff-112c89cb5fc4

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f185-ae63-72dc-9a2a-4e13779eab1a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f185-ae68-7781-8079-fff197d010cc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f185-ae6d-7390-a0fc-1687cc930402
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f185-ae73-77d1-921f-75ddcef33cd7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f185-ae78-721f-b549-80529322fddd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f185-ae7e-7d6c-8172-d82195d92dc2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f185-ae83-7619-9e80-83fe4f0ed7d9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f185-ae89-7d77-8d2a-f28f5cffdc3d

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f185-c858-75aa-8824-5778fd1b578f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f185-c85b-77be-8192-4774889b5b86
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f185-c862-7c67-af61-46ed68e33047
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f185-c868-7f47-87e1-566df92ec175
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f185-c86c-7dd1-96f0-b1997ad54774
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f185-c873-7b57-a5e5-c9802fd18a38
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f185-c879-7b7e-8a18-85a82266ca9a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f185-c881-74c0-a3fe-efa50e5c452a

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f185-e2de-7f62-9c85-5fb94abdccd0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f185-e2e2-7b59-b397-1416b543264e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f185-e2e8-708d-be8d-356e7bf52118
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f185-e2ee-77b8-b292-a02f54c3932d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f185-e2f4-777f-96e3-a1c5b9cde661
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f185-e2fa-705d-8b1d-27b30a47e534
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f185-e2ff-7ce3-847d-dd2dc872a6a0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f185-e305-72c0-8d28-32985e5ffce8

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f185-fc15-77d1-89e1-c6088e6fb4d7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f185-fc19-71f5-9def-0cf87cf0d394
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f185-fc1f-76bf-a6b3-26a7db55ecdd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f185-fc24-7a56-9cbe-806d87d33d8d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f185-fc2b-7a7c-93e7-4eb0e6085182
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f185-fc31-7439-9279-15a26080a1da
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f185-fc37-763b-b142-d0ec9c581d9d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f185-fc3d-7ef6-a930-46634ae8b356

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f186-14a5-7879-8a91-a47a4cb6c937
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f186-14a9-75b2-8b82-69c5b1a431e7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f186-14af-70bc-b0b1-217de9f27448
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f186-14b5-7032-9b6d-3c1abb896d1d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f186-14bb-7fe4-8583-4bb7fde89a09
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f186-14c1-7f89-96ab-c8b98268a46d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f186-14c6-70ee-ac35-283302431602
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f186-14cd-7434-97e4-0a431f94ec19

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f186-2502-70b0-93d6-06633b7a1078
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f186-2505-78cd-9292-cd9f3a74a8d3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f186-250e-783a-bf03-9b64b6e4f0e8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f186-2514-71a5-aeaf-95ddf58784c4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f186-2519-7638-80ad-76ba0682c5b3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f186-251f-76b3-bbab-c0e24da2e37c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f186-2524-7923-a4b5-8c9db2250fe4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f186-252a-7f7f-b75b-0a88c3d7c40f

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f186-3b4e-7e70-ac9b-07a4efb99036
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f186-3b52-727f-99a5-8d2f03421f6f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f186-3b59-7a9b-a3e8-1b7bf4bcd48b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f186-3b60-733c-84d4-20a05b3bcbb9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f186-3b66-7eb2-bdbf-f4cf3cda0569
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f186-3b6e-720b-9e79-c5ade676a949
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f186-3b72-7554-ab05-510e7b766e95
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f186-3b7a-7b99-b3af-60a876f10e21

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f186-56b6-70b4-8984-75404fe13b59
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f186-56bc-72a2-b2d1-d7325a18f282
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f186-56c3-7325-be89-5f8c2d22007a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f186-56c8-7b65-ad9a-30baeefc01f0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f186-56ce-7f5f-989b-a236a92ea67d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f186-56d4-70f6-a944-c9dabe7b0aa6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f186-56d9-7b2d-8913-6fa8224c9f82
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f186-56df-7784-a5f1-324afb71aff2

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f186-6f44-7201-afc7-4c2e00f117f0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f186-6f49-76d4-b394-e4f3769c2e71
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f186-6f4e-7c0d-882f-cad2af546491
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f186-6f55-7ad5-8d10-67b3d4e9a8be
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f186-6f5a-7265-8d28-eddf346817f8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f186-6f5f-70e1-932b-3e5472eef747
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f186-6f64-771c-ae08-02a2391db970
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f186-6f6b-7bf1-b09b-7a9cb3cb4195

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f186-82ff-7482-8e40-eabf03040eb8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f186-8302-7223-9479-76bb1e57e1c0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f186-8308-7424-b74d-4a9f3c300f7a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f186-8310-780a-8721-b3075bdeb8e9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f186-8316-7126-be23-99a50c3432cb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f186-831c-7010-8a96-7583f9d8fdef
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f186-8322-73f5-a45b-604922d39524
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f186-8328-7768-a6fd-f8e86248f9b5

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f186-9470-7abb-af19-569ff5533bf5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f186-9475-77e1-942a-8a05078c4ab4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f186-9479-731c-ba9b-163a802f77df
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f186-947f-7c70-a952-c2d365465414
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f186-9484-7c38-84e7-55181e11c03f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f186-948a-7e6f-95a9-96cd0b141aa8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f186-9490-791b-b2e5-7c43feeab32a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f186-9496-7312-8872-055bab84ba9d

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f186-ae20-7f22-a41c-45c148c25913
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f186-ae24-7d88-891e-8ed3f1a2d02f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f186-ae2d-79d1-b84e-659288ac7eeb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f186-ae33-7010-b826-f7efc862ef5c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f186-ae3a-7f24-8af0-c00ce451c1be
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f186-ae3f-70d2-88c3-330e22afa6d1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f186-ae47-7e0f-b0dd-8620d5c1f971
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f186-ae4d-7533-9c00-05d8674c1260

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f186-cd12-7b64-8074-793400bb218f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f186-cd16-753c-8684-f3b1cb42b924
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f186-cd1c-7138-9005-c90b052eadd2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f186-cd22-7ffc-b66f-360b5e2594fb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f186-cd27-7e2f-9da5-59936bacd865
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f186-cd2e-7b28-b0a0-e583920610e7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f186-cd33-712b-b5a3-aa4f705821c1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f186-cd3b-7b17-9586-b7e307a0f2f2

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f186-e22b-7790-92f0-5a4f858a6840
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f186-e22d-7fab-b81d-05cf10d3aaf3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f186-e236-7c1b-b94d-0935b0cd0bdb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f186-e23b-7d04-a08f-ff4eff28f8b3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f186-e240-7944-b245-e52cd401a82b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f186-e246-7e48-83ec-7b5095c16eba
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f186-e24b-75a6-a1f3-5ab90d2bda7b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f186-e251-7a8a-9414-b4accc132370

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f186-fb0b-788b-84da-8908b9dc6269
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f186-fb0f-7c19-92d1-37f4516f18a5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f186-fb15-7817-861b-281dba4c47e5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f186-fb1a-70c0-8e1b-19dbce373934
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f186-fb21-7c00-bdf6-66084e0a120a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f186-fb27-74dc-8f91-c6391cb8403b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f186-fb2d-7e8f-b0c8-9a19be51f7d3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f186-fb33-7114-a444-7965aab98a68

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f187-0628-79e2-a530-3ad756aa896d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f187-062c-70ba-8358-678027d69929
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f187-0633-70de-b103-a41dce1ce01b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f187-0638-735f-9514-562069dd6af2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f187-063d-7d37-9a81-b6a85ebf6d44
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f187-0643-7a86-b827-74a0a0913cc9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f187-0649-7cbd-9312-1eb1b2a11860
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f187-064f-789a-b62e-d428dee3d45e

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f187-1d3e-72e6-8abf-e1ad22c5ba13
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f187-1d42-7b82-9a7b-54a743a6f67f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f187-1d49-7530-a4e6-041eee561ba4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f187-1d4f-7a56-9903-659f1d2bf691
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f187-1d56-7a62-9696-a8b71955a5d0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f187-1d5e-7fd8-b3c5-c8a29c9f1538
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f187-1d63-78c3-b022-f891452577c9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f187-1d69-781d-a10c-185b08ef5b2b

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f187-3825-7124-ab96-382ffdf1a1e7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f187-382b-7f72-98bf-827eefad35f6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f187-382f-7ce0-bb18-9c10e88d9d70
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f187-3835-7dd1-b891-1cfba26f2eda
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f187-383c-7bbf-b03e-ba81c3b39ecb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f187-3843-7ec7-985b-9094f4aad765
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f187-3849-7566-a714-9bf4907195f7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f187-3852-753a-b8d5-527173f9d46e

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f187-4955-7222-8867-03f0862d0756
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f187-4958-7012-8b72-3247126dce55
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f187-495f-72fd-b9be-28ced2efd46e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f187-4966-72b6-a288-9fca2bb70e33
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f187-496a-799d-868c-991c49478a19
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f187-496e-7643-81f5-f15981628363
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f187-4975-77eb-95e3-fd50939f237b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f187-497c-73ff-a048-cff38020b192

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f187-5c7a-7d3c-8315-b74f426a1888
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f187-5c80-7a5b-be76-8b4e852940bf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f187-5c85-70ad-afaf-8523a59aea43
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f187-5c8b-74c1-8925-948fa4fc2e9b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f187-5c90-76b1-aba7-0799a661593e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f187-5c96-7788-89e3-82531b1f44e3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f187-5c9c-7760-9219-8da829281bf4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f187-5ca4-717c-94fc-611cd6bb1582

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f187-7814-702a-95ea-6feb28607e0b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f187-7817-780a-93c1-ecbee46e131e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f187-781e-7e94-9e59-558cd3bc0219
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f187-7823-77b4-8ce2-aafc7a033539
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f187-7829-7e71-8c9e-40f13a2f95ee
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f187-7831-7b68-b793-9cf39e71c6eb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f187-7839-79fb-8343-17409739c256
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f187-783e-7ee6-9919-a38fbddfeaf2

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f187-93a8-7c9c-95b8-3f22cf9928a1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f187-93ac-745f-97b6-31e7d2af0531
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f187-93b1-798c-bb7f-10ab89e6bea9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f187-93b6-71d8-a004-0e542a5f8d6a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f187-93bd-756b-81e5-b8e74d601f05
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f187-93c3-7643-a5d4-42670ca2a6b9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f187-93c8-7145-ba2a-72341042a16a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f187-93ce-7f09-8da6-f3af4352216a

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f187-a72c-7385-a10e-52af7a29589a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f187-a732-712e-9518-50297b086fea
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f187-a737-725c-916e-9f7951b0c999
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f187-a73d-7dee-8eeb-22cb5d4e1701
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f187-a745-7b1e-8c95-2669bb6855f2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f187-a74a-7c07-b641-b4b08a180aa8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f187-a751-7e9a-9cf2-2c89658b82c7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f187-a755-75de-b7aa-4815049bb173

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f187-bade-7afe-a768-bc8ac80d860d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f187-bae2-79fe-9e32-091570a592c4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f187-baeb-7a8e-bf1b-4f9efb2ceade
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f187-baee-721c-9c49-f63da3b3d007
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f187-baf4-751a-9052-6763791f629e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f187-bafa-7263-ab28-2c6c73e6f811
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f187-baff-79f1-8e04-a2b375a37a31
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f187-bb06-7256-9ba3-4ed520f87131

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f187-d2d4-7497-8fc3-33e2a9a8e9c7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f187-d2db-72b1-92fa-7633e5304a11
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f187-d2e0-7e61-a210-1ba21996cc55
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f187-d2e7-7fb7-826f-b0f768281b23
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f187-d2eb-769b-8fce-3b2b37c58f70
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f187-d2f1-75b3-b313-bf06ab2d16bd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f187-d2f6-7f2d-9deb-b6180bf70660
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f187-d2fc-7d71-a993-100545f605f7

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f187-e582-738e-820c-988caa63135a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f187-e587-77f6-9009-979e09eeddd1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f187-e58d-7959-9f15-d5707ed7246b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f187-e593-723f-9d01-30a3d06face0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f187-e599-7ae1-8457-2cb5d7864220
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f187-e59f-7464-96a8-1764840d907a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f187-e5a4-78ad-a205-3c2873da30dc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f187-e5ab-70d2-bea0-edae92a4a9f0

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f187-f861-7911-a356-061af7873c7b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f187-f865-7385-a33a-0be43b177cc8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f187-f86a-73bc-8252-ca80b99ff5f3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f187-f86f-7a65-819b-64c90ec7cd1e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f187-f876-7c21-9f81-8b294377dac7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f187-f87b-7996-b331-858248146630
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f187-f880-7d46-aeb8-8dfdccb08d4d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f187-f887-7d99-9270-f1d0cbbca7bf

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f188-18ab-7828-9e7b-dbc0f1aa463e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f188-18b0-79d0-936b-40ab2ef6b0e5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f188-18b4-7eee-bedb-2cd1a36a296d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f188-18bb-79aa-8243-98bac4ee970d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f188-18c0-7e9e-8328-5312a1c55919
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f188-18c6-782c-8d0f-106fdbb17809
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f188-18cc-754d-a63d-9e35e484bb22
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f188-18d2-7bf2-a8fa-225955768799

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f188-3072-7416-9185-826013288039
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f188-3075-73e3-9e2d-b2abbe918fc1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f188-307b-7a1f-9723-7cf2987b57a2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f188-3082-7b9f-98cc-44e13eb782eb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f188-3087-735a-ae99-fb445488c44e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f188-308e-76a4-a476-3e0b79f46f61
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f188-3094-76e0-8f53-bd7806036186
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f188-309a-7b43-84e6-8fc85dfe56cb

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f188-554e-7cfd-8064-64fe8718e1b7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f188-5552-7634-95d5-3b225e0da2ec
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f188-5558-75d2-b01a-a8dd863e7621
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f188-555d-7186-a450-0337a99a0545
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f188-5562-7f06-96b1-fbbd805867d4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f188-5569-7d8d-9bc1-933a5ff58314
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f188-556e-722a-a475-1dafacb3e786
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f188-5574-7286-9e80-c28f6b647fc0

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f188-672c-7afb-9484-4700c3caa21f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f188-672f-773c-bba5-0aa1993c1d20
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f188-6737-7e58-aa39-87d4142f8134
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f188-673d-7219-8308-824949868f6c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f188-6743-71fd-8ea0-50543fce996a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f188-6748-7cc2-b521-fd3b8594b1e3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f188-674f-7547-91cf-e948c9b9c1a1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f188-6755-7d4b-b17e-6f1433c802fb

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f188-7226-7d98-9c7f-bd1768dd452f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f188-722a-77d0-939e-5f7928a3d10a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f188-7231-73cc-b9a6-c4f86a58b6a2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f188-7236-782b-950b-6a91fa12b8b2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f188-723b-71e3-b4a3-1e7d6b601443
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f188-7241-7070-8c17-53b15104e256
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f188-7247-74d6-82ad-90b109cd88f6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f188-724c-7bc6-9ae0-1c798d9f453d

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f188-96ce-77b7-981d-89434e41ee7c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f188-96d1-731b-962c-673a51509f8a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f188-96d8-7595-8078-f12fe5a8a2d1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f188-96e0-7570-9818-4e57d16ac9a0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f188-96e7-7df0-8c53-2646dd2ca6d4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f188-96ee-784e-b732-fc574051bb03
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f188-96f7-7146-b2a4-1da0832b107d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f188-96fc-7d52-a8c4-be107774e6f5

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f188-adc9-7c02-aa34-a66c10ea2c45
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f188-adcc-727b-a9f9-305aec317b74
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f188-add3-749d-82db-2fe375cf191d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f188-addb-76ea-8e2d-c538d528f5c2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f188-ade1-78ca-86f0-53f51231f4e2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f188-ade7-7c44-872c-f0ce62c2420c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f188-aded-7b94-a793-bd2a6e0bcbac
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f188-adf3-7616-bac0-5663a869632c

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f188-cecd-7990-b346-80ef431ff5ea
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f188-ced0-76ec-ae6c-908683f07d4b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f188-ced6-77c5-996b-cfce2dbd2471
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f188-cedd-76c6-9cf2-7138a9a779be
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f188-cee2-72b6-86f6-d9626ffe1f27
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f188-cee8-7189-bb06-b168ac7716ac
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f188-ceed-7a33-8537-5c5be9885f1b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f188-cef3-7182-bf78-9fb613fa1644

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f188-dbcd-7d46-b94d-b79cd7b57cd8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f188-dbcf-7a73-a165-3c4019daa766
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f188-dbd8-7764-a35e-9a815464243b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f188-dbdd-7864-9c1a-1e1c1c345c6a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f188-dbe3-7f04-a47d-07c4c756895f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f188-dbe8-7ece-aa90-73cadba03c77
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f188-dbed-7c1d-8737-8d165187530e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f188-dbf3-7a7c-bb8d-167c451072ca

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f188-f068-73e4-8d6d-291108caea18
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f188-f06d-75a4-9b2a-ab6aad768976
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f188-f075-78fb-8d2e-1f3f3b15a6ed
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f188-f079-7e2d-971f-d8b190b468c3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f188-f07f-75a0-b953-c305f3bed90c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f188-f085-75ed-b72e-054e86c776d2

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f188-f08b-7f05-91cb-ca9a4a886a1e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f188-f1d7-7c03-b2cc-ffed332a7a1f
[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f189-1017-7f10-900d-4a0b1aed0e82
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f189-101b-75d6-b01c-25985d9ce028
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f189-1023-7735-b594-714b9274aaec
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f189-1029-7050-9de7-49ad63d0f337
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f189-102e-71ea-9903-ceeaff844eed
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f189-1034-79c9-8652-03d286d75d1b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f189-1039-7e5b-becd-615796e05093
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f189-1040-741a-88de-f80146b71132

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f189-20c5-762d-ba65-57cff06992a7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f189-20ca-7014-bbdc-33e5208f6efe
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f189-20d0-7bcd-9bf6-31fae9e12f8b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f189-20d5-7d71-8105-1215946d81fe
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f189-20da-7da1-9805-51406e3a9a42
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f189-20e4-7a8c-b0ea-4fdb88efe54f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f189-20ea-7ee1-a5a1-15e9648cd131
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f189-20ee-7bfe-a25a-6828f4615eb2

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f189-4269-7258-bcaf-c9d4eaef7c4b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f189-426d-7eb3-a9da-ffa7b846c810
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f189-4273-72ab-ac08-b08e6a75292a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f189-4278-70df-a6e2-95a943d77ea3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f189-427e-732c-ad24-853175ba2fa3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f189-4283-7263-bf8a-6e1fc371db88
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f189-4289-7df6-a321-8104a099979a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f189-428e-715b-87e1-8062b5cdc4fc

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f189-54f8-73f9-b422-3e76696facc9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f189-54fb-7be7-a59a-649ac4a118aa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f189-5501-7a1f-baab-90e994a250df
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f189-5506-7357-8f89-7fe9b990476d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f189-550b-7a2c-abe9-14eb87f41cc6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f189-5511-7f36-9494-eff5be54e00e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f189-5517-7335-8aab-fd38c7e9e7e8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f189-551e-7545-8c2b-bf4040c6c6db

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f189-697c-7ef6-ad72-b6179f50d3c1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f189-6982-731a-8c10-2a912a680d53
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f189-6987-7af8-969b-a722edac6241
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f189-698c-74f9-8874-df4ecaed0b96
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f189-6992-7f70-aedc-c37c7dbf07a4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f189-6998-71f7-b55f-d38da4864947
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f189-699d-7e43-b1ec-bf79a7eff742
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f189-69a3-7bb3-9cc3-2a4c93f3339b

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f189-8322-726a-ae26-6b6bb7209e05
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f189-8327-7359-8ffb-cae334f7534b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f189-832b-76b7-a2c5-9ae2148e83ff
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f189-8331-7689-9e91-c455702f2823
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f189-8336-7793-bd32-0116c348b13d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f189-833d-7ac3-938a-8f9d75c81213
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f189-8344-7103-80c9-2e08a60b90dc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f189-834a-79ec-98ac-c960e1382b3c

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f189-9e97-708a-9210-93710cdcc3c7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f189-9e9b-7abb-9f5a-c4480c79cba7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f189-9ea0-77f8-9758-535d68fef63b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f189-9ea6-7d3e-845a-454d97bd0601
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f189-9eab-7d4d-899e-bee73ee2ccf1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f189-9eb2-7dcd-bd7c-ef491c3fbb15
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f189-9eb7-7a70-866c-bb93753dc00b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f189-9ebc-78a1-bd47-226ee5c754fe

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f189-b3e0-7a8c-93f8-091d260a0206
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f189-b3e3-737a-9c55-7cfe20128963
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f189-b3ea-7c79-846c-16932345da9b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f189-b3f0-74c0-b0b6-7ef444632dd9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f189-b3f6-7d8f-80fe-a735fc2154c9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f189-b3ff-71f5-ab16-966a13f1a38c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f189-b405-7ab0-9ac5-6fdc3afa50af
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f189-b40d-7238-93d0-b888e620a8e8

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f189-c584-74af-8953-e4353fdb53b1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f189-c588-734b-9bc9-1f526498c2fa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f189-c590-7ef8-a2ba-03d20641c26e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f189-c594-7c90-a19c-a502ee5df430
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f189-c599-785f-9756-dac5acf8d537
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f189-c59f-7312-8972-c7e34a60792a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f189-c5a4-7f3e-a68b-50b89fbec7ce
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f189-c5ab-78f0-8c17-9c4b2d6751fa

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f189-d14d-761f-aae4-ceca7fcd9625
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f189-d150-7eeb-b338-b0879b386a18
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f189-d156-75ac-9a11-1edaa7da1e04
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f189-d15c-758d-9eae-138c44cc5a42
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f189-d164-7b2d-97cc-b48f628a168b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f189-d16a-7013-9f0c-05d29d107b34
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f189-d170-7a26-86f6-7ae04679ab64
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f189-d175-7101-b8d8-e3492c1bc520

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f189-ec94-7d15-bd53-83a735af4293
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f189-ec98-726b-9b1a-17a7fe858306
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f189-ec9e-79ae-a8c9-5cf842382f48
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f189-eca4-776f-9f63-bb0a47bb4035
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f189-eca8-7092-bd17-dcee77063389
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f189-ecae-78e9-acdf-413c64c753e8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f189-ecb3-7bb7-afb6-b166dde40fa6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f189-ecb9-7b30-b24a-f6a94dbbea9b

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18a-01e4-70c1-ab6b-6eb3f50a025e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18a-01ea-7802-95e5-a8e5296da8e5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18a-01f2-7da6-b414-e2798a6ddf49
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18a-01f8-768a-aed3-515a8f56ebf3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18a-01fc-78db-ba9d-99c18eba021e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18a-0202-781d-bc0e-bfa0576c210e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18a-0209-7c15-b2f1-c09f54af1e04
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18a-020f-743c-8f87-611d19e4538d

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18a-1477-7529-9c02-5922a7773d04
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18a-147a-7b95-bd23-b83110dbe4fd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18a-1481-7d57-b0d8-1d9c2c199611
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18a-1487-7b3c-ba1f-71cc6934d029
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18a-148f-7b3a-8296-49e4067b58c7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18a-1494-7250-8927-df51845a797b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18a-149a-7eb6-92d1-0d5169c7adfa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18a-14a0-7d41-a4b6-f2ca06e93926

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18a-34f4-7fe8-b446-adc920d9495c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18a-34f9-769e-8133-b84fab837e33
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18a-34fd-7ce7-8ee5-f4ea6e23b994
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18a-3503-7498-9bb4-4b72742875c7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18a-3509-75cd-9a05-26e3cf16f172
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18a-350f-7c5d-ae2b-7aaaa433690e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18a-3515-7ba1-b8da-1857203d12b7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18a-351a-793f-bc74-00a9b2d28b19

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18a-44ed-7da7-bbde-aef8aeb489e7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18a-44f0-7ac6-a663-97bf8150b006
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18a-44f7-7401-9b68-3357c480a4b5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18a-44fd-782b-90c0-3e58822bc143
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18a-4504-7a84-b031-5ecd9a249770
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18a-4509-7bd9-a276-4a2f6373dd0d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18a-4511-7d9f-98f8-d4b75e882748
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18a-4516-7176-ab89-317203c43de6

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18a-5b8a-7f56-b1b5-3ee350890500
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18a-5b8e-7e59-b6af-7caf0b0962ac
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18a-5b95-7bd3-a3ab-7dbdc45e9b43
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18a-5b9b-7f7f-8753-4efcad8a1809
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18a-5ba1-75f8-a96c-9ceee5c0b4aa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18a-5ba7-7851-81c4-432292ac5e92
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18a-5bad-768c-843e-67d12a23acf6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18a-5bb3-75ba-b65c-87a2a9dc32f9

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18a-6d1b-743f-88f2-4071cd805583
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18a-6d1f-7163-941c-3ebba5e62485
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18a-6d27-7be0-a36f-4f1bf3068ad7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18a-6d2c-7065-851c-b0d909fd16f1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18a-6d31-72c8-9118-eb7fdf48e011
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18a-6d38-7445-8f4a-902d9ea297fd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18a-6d3e-7809-a8de-8a9674c89a56
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18a-6d44-7d03-a0a1-c574544b3213

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18a-81c3-7130-96b2-ab6cb30fd6fc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18a-81c6-72d8-88d6-bcb5b6569a8f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18a-81cd-7c72-9b91-714af185b6cd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18a-81d3-7cae-a0d3-fd6f5e691207
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18a-81d8-76ff-8bba-7c2f65a37be4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18a-81df-775e-8368-617cfe4e1c65
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18a-81e5-79ce-afbf-21c5c3ceab16
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18a-81ec-737b-b09d-8a042a69d494

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18a-987e-7f71-96e2-f27f2d0f5d69
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18a-9885-76d1-b07d-c660ebc177be
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18a-988a-7520-be8e-b028948bf4fb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18a-988f-7922-91ed-b7b54accde51
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18a-9895-7efe-9a40-22d15e7dd4e4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18a-989b-7268-8c07-76231c2dea0a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18a-98a2-7c6e-8eee-42d851e07a2b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18a-98a8-7eb5-ac13-85291f6feafe

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18a-ad70-791e-a30b-f349f21db65b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18a-ad76-7996-9a17-8c8a054f8f62
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18a-ad7b-78da-b291-f47d0bd665d3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18a-ad80-7e54-a6af-7ef4e2af2a19
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18a-ad86-7ead-a2ae-65a1072ea5f2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18a-ad8c-7907-83e0-0b2615fbd866
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18a-ad92-77e3-9b52-275b489002e0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18a-ad99-7a4b-a5cb-7828e9efc4b3

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18a-bc44-71f6-9426-0d365940219b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18a-bc48-759b-aa83-0c6a48d37913
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18a-bc4e-7b8b-acdd-fa93559330c9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18a-bc54-75db-9720-a9e9071cfbcf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18a-bc59-7835-a054-d0e5ced0d46a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18a-bc60-703d-999c-43dfe09aa382
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18a-bc66-7516-82a1-55848e35e430
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18a-bc6c-7516-a87c-37da3bfc08df

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18a-d021-7ca3-84de-27abafd74203
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18a-d025-7087-ab7e-73b87a61fe87
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18a-d02c-7475-8f6c-9609c50a5772
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18a-d030-7d99-b907-c8902dcd4b27
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18a-d036-709b-a895-d39fe4b12217
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18a-d03c-7600-9178-333122147f1e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18a-d042-754f-ba1b-7f439d5db3e5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18a-d047-7b88-a4cb-96b380a81d3a

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18a-f4a8-73a8-bd8f-47d6ef2c56bf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18a-f4ac-7fa9-9141-a180af3a0054
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18a-f4b2-79c2-bcf5-6e4a9f2065c9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18a-f4b8-7d81-b13e-2c2a80d57052
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18a-f4bd-70b2-a358-1003118b127b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18a-f4c5-7134-acfe-3a123424ad4f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18a-f4cc-7059-9d7e-7da5b0dd79bc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18a-f4d1-77fb-8ef7-81f50bb79c93

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18b-0eb6-764e-8b41-d0150be0e997
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18b-0eb9-7a6f-a5a8-95ff47156c72
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18b-0ec1-7748-a5d4-816582730a57
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18b-0ec8-704b-9ea2-a5e4cf27d7df
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18b-0ecd-7799-a4fd-23b0eccad37b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18b-0ed3-79e8-90a4-78432f8c0e85
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18b-0eda-7d1f-8b11-589b57217c97
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18b-0edf-7a9f-bf99-b3b56890e7c1

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18b-2708-73a6-bc24-d2a8e2038e6c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18b-270c-7aa7-a9b0-0704eb00c296
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18b-2712-7337-9fff-f94090f05c72
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18b-2717-7a03-bc50-35d53c75c7b8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18b-271e-759b-ad78-23e67a7b5210
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18b-2722-7892-aba3-3ff481b26517
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18b-2727-7039-af06-ed801fd865fe
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18b-272e-72a8-9b9f-179fd8457437

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18b-4425-7752-b9ca-93f4a4b4505e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18b-442b-7fac-bc44-fa1f00f0b9a7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18b-442f-7444-b127-8f094062f06a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18b-4434-76a5-8558-2d544c4e1e22
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18b-4439-7abe-aea5-0c0d0670c819
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18b-443f-7036-b60f-dbbef4f65f46
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18b-4445-73e4-a8d6-c4aeeb0f3e09
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18b-444b-7e84-8e52-d4a472a333a0

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18b-66dd-74fa-8680-6f2f188b6eff
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18b-66e0-7e6c-b836-bc733ccc487f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18b-66e6-7e08-96f7-5c8bc7a6d27d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18b-66ec-7d19-8721-a2bb55eaf386
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18b-66f2-7e32-b908-0efab426d21e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18b-66f7-748d-93b5-3ed9f4899aa9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18b-66fd-7ab8-8842-bb67f129b7ed
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18b-6703-7829-a817-df93dd6839e7

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18b-8592-763c-a3bc-49c3bff99965
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18b-8599-751d-83c8-0aa4e97bc644
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18b-859c-7e94-9baa-e4a74c5b39ef
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18b-85a3-7b11-98c8-6527a4d793c4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18b-85a9-70c1-b5fa-ff81ccb36cb9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18b-85af-7805-bc20-004e44a35c47
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18b-85b4-7f0f-8592-09b1ebbf9612
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18b-85ba-7770-b5c8-3b978ba4c1b2

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18b-9f1c-790c-afbd-9ed459f27499
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18b-9f20-7e42-8ba4-be40c9fddc21
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18b-9f26-7ba7-ab23-c751964695ab
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18b-9f2c-7e8e-a58f-edb804f31690
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18b-9f32-753f-a68e-70e72d9906cf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18b-9f38-7770-81c6-214da14e0727
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18b-9f3e-7dff-a0db-272d98fdf0a0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18b-9f43-7943-a1a9-0d5c738b9a64

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18b-ab0a-7c8a-9ebf-17eaf54ccfaf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18b-ab0d-76be-8dc6-51fdfb246562
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18b-ab15-7bd6-8e7c-416bf949f078
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18b-ab1a-7a75-b47b-53e1e6dd120f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18b-ab20-7c62-824f-a5aa507a4f13
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18b-ab25-714d-8b9a-6701bbdf9b73
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18b-ab2b-74dd-a341-0cf616437c14
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18b-ab31-7c26-b6d9-bc5fdbccabe0

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18b-be08-7c4d-abda-711ccd3c5f4c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18b-be0e-7166-b1d4-2e2dee0716c2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18b-be14-7726-a9a2-ce3c2ca7d1e6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18b-be1a-7ecc-b45b-73ef6543a1ef
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18b-be1f-737c-97be-671731b9777f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18b-be25-7ffd-9bfc-b6651413fc39
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18b-be2b-7a4d-a32b-1e8514830345
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18b-be32-7638-8594-0a16738fae9a

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18b-d383-7b4d-905d-f307fbc1eae1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18b-d388-7b5b-9601-429d8eb33f19
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18b-d38e-7e3d-8f69-b0e0e1b6f6a6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18b-d394-7986-8df1-eacfcceec13a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18b-d398-7e0f-8a5f-0f0d93127061
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18b-d39f-7095-953e-1a79f5c8fafd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18b-d3a6-7d36-a465-7b659bd5ebf3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18b-d3aa-73d5-ac00-af6dbe29eeba

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18b-e5e2-78b6-8241-d8e12828e82f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18b-e5e6-7c6e-93ac-a7403875e100
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18b-e5ee-7b3b-b2b0-fcd74c44162d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18b-e5f4-74a8-be9d-13bb30cb83b3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18b-e5f9-7a57-9177-0072b2bb707f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18b-e5ff-7660-9855-41f0ebe913e9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18b-e606-7e5e-b23b-8052da42e397
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18b-e60b-7d8e-b44a-611a003df94b

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18b-fdbf-7d8b-afe1-35787c9f34cd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18b-fdc3-7a1d-b69f-dcfd6d47c388
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18b-fdc8-7583-a63f-2bcdc7b26ae6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18b-fdce-785d-b31d-45c3b1159f4e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18b-fdd4-7190-8105-0814a9fceaab
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18b-fdd9-7f7b-8296-57dae6d966dc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18b-fdde-7fe7-b3d6-67522932cdbd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18b-fde5-7673-94cf-25d2850a05bd

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18c-19cd-7467-bb3b-517ab6e9db83
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18c-19d0-743a-9a96-5e36c38c4115
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18c-19d8-7b0a-b78e-2dcc21c90532
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18c-19de-790a-a624-28ea7c6cde68
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18c-19e4-7be9-8aa0-a676016dbc93
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18c-19eb-7ff5-97de-1b0941eecdfe
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18c-19f0-7dc5-b411-f6504be6eb6f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18c-19f7-7b79-b428-ed28f0e651a0

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18c-2c45-70f1-8eaa-dbc624ee3e7b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18c-2c4a-7547-8161-997fa32e15c7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18c-2c50-7d2e-ae10-deb5ed98bb79
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18c-2c57-72c8-86b0-07f30e323bf9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18c-2c5a-7643-8804-bd7716d2cf99
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18c-2c60-7e25-928f-9bf7594ecced
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18c-2c66-70e2-895d-ebda2a0303b5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18c-2c6b-7f9c-b548-08d2df090eb9

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18c-4da2-78af-ab4b-f0f58f201d6b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18c-4da6-7604-a5ed-b63a3e375220
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18c-4dab-7111-ae61-6e03f01f74ff
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18c-4db2-73a0-99bd-18cba1dd5553
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18c-4db7-7f44-a9b8-e6e60858a514
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18c-4dbe-7b19-86fc-012d8fe13e7c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18c-4dc4-76f4-a489-68e864d9f3d2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18c-4dca-7733-be36-5f924c702515

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18c-6bf1-7fc1-bd0b-a0e6b6993474
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18c-6bf4-79b0-9717-7f53a5325167
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18c-6bfb-7fc7-8f6d-115d450ac6c2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18c-6c04-7bdb-88ad-fa0778fa9cfd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18c-6c09-728b-8857-c9b98982713f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18c-6c0f-7608-ab0e-b7beda1e7939
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18c-6c14-765e-8464-4e40661a4374
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18c-6c1b-75ec-b53f-93fb39119911

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18c-830b-738c-a26a-e030c2ec9986
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18c-830d-7b4f-9781-8472b6167f18
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18c-8317-7e31-a41e-418f70d0c487
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18c-831c-7051-a660-5567b0163503
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18c-8322-7b1a-86ae-e732a97070f5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18c-8326-771e-9cf7-58c4eb80d4f1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18c-832c-70df-a23c-6a71f3565ab6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18c-8331-7865-aaff-a34fbaeab610

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18c-985e-74dc-b0ab-e0902831ed89
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18c-9862-7a3f-a9fe-303ffb29de8f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18c-9869-7fbe-ac7e-79418832a2e5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18c-9870-75bc-ab22-d442299ec6cd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18c-9875-7bef-ab11-c35d5e7a609e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18c-987b-78b0-8ee3-a0af4ab69c6c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18c-9881-7c5b-9d38-c8aa4fec5e77
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18c-9888-7143-afbd-94a93aeee938

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18c-b3d6-758e-8cfc-37e6bceda07d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18c-b3db-7c40-8d1b-68deffe32474
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18c-b3e0-7fbd-ad75-15a9ff091ff4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18c-b3e5-7187-ae45-b24fc40a63c6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18c-b3eb-7d24-8c13-9a89f540eb00
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18c-b3f0-78d6-a5bc-479fe45a97b6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18c-b3f5-7abc-85b7-af06808331c2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18c-b3fc-7670-bd12-fab4ffa0a1f1

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18c-cbc4-70b6-9c35-42b135620fd6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18c-cbc8-76fe-a50d-d2cd7296c287
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18c-cbce-794e-9fbf-3fdf684457a7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18c-cbd5-77d4-907a-422618e456a6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18c-cbdc-765f-ad2c-4bf447906419
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18c-cbe0-776c-9d0e-7c0558043f48
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18c-cbe4-7c4f-aca3-20eb1ef29013
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18c-cbec-75b7-a9c0-81df5028a01c

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18c-e482-72ec-ab96-794fcfb94ba4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18c-e485-7e13-bba6-233309b75793
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18c-e48b-77da-a0f5-dfc28084e400
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18c-e491-73b2-b897-b0a249a866f9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18c-e497-74fd-a23d-ad674865b5b3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18c-e49f-7bc8-9c18-7d5681c83376
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18c-e4a5-76fc-baef-802368d5427c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18c-e4aa-7612-8865-907b9f2ac03c

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18d-0967-74af-8d71-f797ef1afb05
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18d-096b-770b-ad51-03b4958e6f6b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18d-0970-736b-84a5-a01054418146
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18d-0976-70ef-bb8c-cb6020216f11
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18d-097b-7171-af23-57cb0e6935da
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18d-0981-74ff-85b9-7bbdb217d687
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18d-0987-74a7-9b2b-7574054b64fa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18d-098e-7738-8f3e-d4f00b513127

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18d-1384-7c2d-b305-186aad03d735
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18d-1388-78d3-8c83-c87c677f7a10
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18d-138f-7a21-98c8-da22668cd2da
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18d-1395-7bfa-b0a1-e4d6bb7ee091
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18d-139a-7c0f-b9de-79194ec1e06a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18d-139f-7142-94d7-21a23104dcb9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18d-13a5-7a5c-b8f4-4ef28947c488
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18d-13a9-77ae-a17f-8c9a02d6bcd5

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18d-35e6-72f5-8c58-7cbbaba49cbb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18d-35eb-7e6e-b45a-99727eca37c7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18d-35ef-7cfa-96b5-2c1dd17f0456
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18d-35f5-75fb-83f6-6c03a944166d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18d-35fc-7d8d-be5a-351be95d185b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18d-3600-7c09-816a-bfcb3b52e891
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18d-3606-7637-82b3-71363795bdf9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18d-360b-776e-b013-fd1f6b762e38

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18d-4a9f-791c-98f2-3acafc7fb961
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18d-4aa2-796e-a34e-e5edc3f532e6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18d-4aaa-7cf9-a778-6097b55be405
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18d-4aaf-7512-85f8-851ee9a04fe5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18d-4ab7-7ca4-8544-5504df25f44c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18d-4aba-7dba-8e40-55580d69f96f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18d-4abf-7b07-9ad8-edc2ac5f9ec4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18d-4ac5-76aa-90cf-004d2553f786

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18d-5f1d-7874-bf6f-b6c53ac6f17d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18d-5f22-7c7f-9383-015287352f06
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18d-5f28-7afd-bbce-cb08ba1ce7bd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18d-5f2c-710b-9171-891001c90e77
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18d-5f33-7abf-9398-40fc42bac31a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18d-5f39-725a-a120-2c36cde5e2c2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18d-5f3e-7882-9ed5-36dc65f423e5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18d-5f44-7319-9d91-6f234094b159

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18d-6f85-77f7-8bd3-89a2d629f88e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18d-6f88-7346-b17b-ec802c47a10e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18d-6f8f-71fa-a06d-f724f3a6c40c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18d-6f94-790e-b5cb-3c0de179d93d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18d-6f9b-707c-82b1-73b2ae73a5a2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18d-6fa1-70c8-8912-53dd3a078f37
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18d-6fa6-7475-9c57-692e0664f770
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18d-6fac-7e5c-8b80-ed135765974f

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18d-855a-7a64-8d2d-85b1a1e8378c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18d-855d-7005-b17c-7f4ee8d93bcf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18d-8565-701d-84ad-81ac0b2eeb38
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18d-856a-7090-974e-2ae843818788
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18d-8570-75de-bfa9-3d2b6546614c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18d-8576-76eb-a76e-819d4a0dcc2d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18d-857b-7962-b98e-150c21e7fe39
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18d-8583-712c-b1b5-9cad90787845

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18d-93b0-75ff-bd0e-6db60f850f39
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18d-93b6-7293-8c1e-8aab5e73584d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18d-93bb-75ec-9225-f27bfa67ba6d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18d-93bf-7c28-8013-f111fcf5cc38
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18d-93c5-7d74-8cec-3c85072855c3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18d-93cb-7067-bbf5-5ff98736c416
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18d-93d1-7ee7-832d-49f75a72f134
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18d-93d7-72fc-b982-6cad20be0861

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18d-a7b4-71ac-a264-79a8515c9b19
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18d-a7ba-7747-9230-8d0b29809622
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18d-a7be-78c3-9561-19334d0d48f8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18d-a7c4-7c0a-975c-ab49bf8432d8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18d-a7cb-71b4-95b7-26d1991ace7f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18d-a7d0-756f-9b7b-6099c77dc526
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18d-a7d6-796e-9742-b192b3a9ccee
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18d-a7db-73c6-905f-04ed8971c25f

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18d-c247-7041-b799-8e3614a33e68
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18d-c24c-7cf5-a538-5283dd81badf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18d-c251-7a9d-ad4d-280ea5fe30d9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18d-c258-7c2c-91ad-3de7e9dd4457
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18d-c25e-7c29-bd42-21072d8fa0bc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18d-c263-7734-ad75-46586eb5ab72
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18d-c269-7a57-83eb-b3b53736028d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18d-c26f-73dc-9448-1890bff8a743

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18d-d68d-7c95-bb13-f7cf53e47342
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18d-d691-7bdd-9ac6-1a2b6694ce89
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18d-d698-7cd0-902e-0ba015bbe5dc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18d-d69e-744d-924a-1b1dd6f83401
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18d-d6a4-7ab9-8f8d-8bc357434a7a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18d-d6aa-7dfd-a454-acef8f22262e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18d-d6b0-7060-8a1b-f7c8d4f72af6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18d-d6b6-7c0c-90e6-c6aaa80c6d50

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18d-eecf-7445-b1f7-ac76987d9307
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18d-eed2-7c90-b661-7023a643b1fc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18d-eed9-7076-8dd1-57a6656e634e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18d-eede-7fd1-91d6-aa70fabe59e5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18d-eee3-78af-bdc9-6b5fe784f9c2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18d-eee9-7cb3-8bad-e6355852100b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18d-eeef-70a4-8844-561c0348ea7a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18d-eef5-742f-93b6-4f48c8bd8847

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18e-08de-7862-91e5-80014e3ff4b2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18e-08e3-7e29-8a18-6a7808590ddd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18e-08e8-7ba5-8059-04652ca08adb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18e-08eb-7dab-b34a-cdcfd1dac1ff
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18e-08f3-7103-beed-12b1ca3e2a93
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18e-08f9-7ba6-a953-be1969dc76fa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18e-08ff-7906-be57-59056a4641bc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18e-0905-71e2-a61d-03afcee0544f

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18e-2d21-725a-a510-c010b8db6f29
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18e-2d24-794b-a4ed-3c215a8784d0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18e-2d2a-74aa-b7b3-920ef7db135d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18e-2d2f-77b2-b24a-9421074f9171
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18e-2d35-7c03-9d0f-09131cf87641
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18e-2d3a-729c-9e24-2f307d24322e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18e-2d40-78e4-bad6-f3c9cb26ba59
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18e-2d48-7049-b330-1db07688186c

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18e-3ea5-772f-93ed-ed5409410e39
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18e-3ea9-7d9d-ab2b-09ac1f4322af
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18e-3eaf-71c1-95b9-e792a4756154
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18e-3eb4-7194-804e-a59158f72b26
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18e-3eba-730b-a4d4-f3c035ead4a5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18e-3ec0-72f0-ac1e-83f65a2dbad4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18e-3ec6-78e1-ab28-914b5f5b5b19
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18e-3ecc-765f-a5e3-71cf891bf543

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18e-5220-70ac-ab8d-d59027fa0da2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18e-5224-714f-91ad-2a56993cf549
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18e-522b-7940-9bce-c53dade10552
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18e-5231-7074-8606-f4884cf61244
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18e-5236-7a87-85b9-3fbacd4a56e5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18e-523c-7f82-a388-cbdc697bcb70
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18e-5242-7656-9795-48fa929b21a8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18e-5248-75c4-bc40-879109729c32

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18e-7194-7561-b5d5-24a32df92ab9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18e-719e-7254-8a77-8f5a247633bc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18e-71a3-797f-a3ac-dec72291c9c2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18e-71a8-7a5d-b0dc-cf6607785f1f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18e-71ae-7fc6-890e-52341c83b9d0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18e-71b4-74b1-aca3-17e3fade3d65
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18e-71ba-721b-8b5a-2d4d7a64ab1f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18e-71c0-7eec-8eb0-cf679ea18f49

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18e-8879-7802-9dcb-fde530dee195
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18e-887c-7167-aa19-0d8ec5f7d7a2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18e-8885-7324-a4fc-e24a756eb3cf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18e-888b-737e-9e2c-4cfde0016dbb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18e-8890-7cb9-9467-c2c44d07f8c1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18e-8895-79a2-acaa-b9fd01632eb0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18e-889b-76bf-aa87-ddb8148ef3f8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18e-88a0-7282-806c-ad61c4b2dc30

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18e-9ea4-7f75-9dc5-a3361565b546
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18e-9eab-7948-8206-45cd0df8d2b6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18e-9eb0-77e0-a733-21ee10cffa84
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18e-9eb8-77d1-a14f-cd90c3eaadab
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18e-9ebc-7258-833f-4b515f9b754b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18e-9ec2-733f-ab14-d118ba8c6492
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18e-9ec8-7e5f-a94b-d4cb4059d227
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18e-9ece-7bee-b530-de2d48867e82

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18e-b031-774c-8358-5a2bd6b47bef
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18e-b034-7cb1-bf1b-d2f8a1c87763
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18e-b03b-7029-9554-c3e927f0717c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18e-b040-76bd-bf48-46eafb323225
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18e-b046-7432-8124-9c9987d7ea79
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18e-b04c-7efb-b04d-b4d4edb6a1ae
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18e-b052-7794-857f-330c077d56ee
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18e-b057-755e-ac5b-ab5081f8d7c8

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18e-caf0-755c-a7bb-47cde105f45e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18e-caf4-759f-a00d-5ea0ea27c3e7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18e-cafa-7af8-8ef5-8f3fdea3e516
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18e-cafe-706e-b75b-1a9e6bb10473
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18e-cb04-7fac-b83d-3f6c2c6779dd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18e-cb09-7cd8-bceb-2cbc1f7b971c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18e-cb0f-77f2-9ff1-c27cedce93d2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18e-cb14-7d51-89fc-7d556a129721

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18e-e435-71b7-9f04-46233bb2b19e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18e-e439-71e6-8d9f-20f024f819e7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18e-e43e-796a-9936-0a195551347b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18e-e444-79f6-803a-dedd725aa9fa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18e-e44a-73e0-b94f-a06cffdb4060
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18e-e44f-7640-b589-f49b7de26a28
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18e-e453-7755-8711-77e1ce482ca0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18e-e45b-7661-9f14-b560bdba9390

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18e-fb05-79d6-bedc-6d748d8c565a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18e-fb08-7073-a2b6-1e3f54c45eef
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18e-fb0e-79c7-8c0f-7e73c93cefb4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18e-fb14-72d4-9342-d77ee9436922
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18e-fb1a-7ce3-8ff6-c1d25d44c80f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18e-fb20-7eaa-8132-35f3f8b69e8f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18e-fb25-75db-a803-5c773709cb90
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18e-fb2c-7397-b898-2081465b8320

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18f-0d11-77af-a1e4-3e185bd82f8f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18f-0d16-7599-93a3-ea95c1d319f1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18f-0d1c-7c50-bce1-bf2428c69642
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18f-0d21-7256-9560-46b68d6e15ad
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18f-0d27-7ff1-8c8f-4a4bd0aca7d2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18f-0d2c-7b74-9a85-43b54ce46403
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18f-0d34-7b64-84de-6a2922ef6e53
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18f-0d3b-7ceb-b0ad-79a567e69939

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18f-2ade-7235-a7aa-b2f55481015d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18f-2ae1-75f1-8e5a-cc05c6c6c9ba
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18f-2ae9-76d8-bb32-1c40d14bc735
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18f-2aef-73c1-99e7-3564b8b03008
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18f-2af4-7bd4-b54b-e75017a3bbd7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18f-2af8-7861-987b-161ec398d528
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18f-2aff-78dd-a9eb-d7fe918785ee
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18f-2b06-761d-9799-e0f9badf6111

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18f-4f96-729b-a955-e07a0ff8bcc9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18f-4f9a-7678-9dac-c7aa70fd79b1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18f-4f9f-70e4-8489-929785765c2e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18f-4fa6-790b-8d67-f3f13b8ddb70
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18f-4fac-726a-b372-e0f5f2d5c475
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18f-4fb2-7b8d-83e6-2c4efd231d18
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18f-4fb8-7de1-9795-f89496fc7ef5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18f-4fd9-74eb-ae9d-6db8504ca65c

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18f-660f-79ae-bb55-cd96a416691f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18f-6617-7fc8-891e-4f6c5c5f0d00
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18f-661d-757a-930d-ee26c54ae131
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18f-6625-76df-8017-7bf784ea3ee5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18f-662b-7cb2-92a3-2b242b41d7dc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18f-6632-7aef-affd-5e6f0b719465
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18f-6638-7c58-b852-4adf173f69d1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18f-663f-720d-bab1-c34d9c2e86a2

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18f-79c3-79a4-a767-36a4330de8dd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18f-79c7-77ac-9713-2b72cf1d528d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18f-79cf-760f-86f7-a8dff515a904
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18f-79d6-74f1-821c-f10eabd6ff0b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18f-79dc-7f24-8586-3bb6506d4084
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18f-79e2-794f-9f48-560ff485ea4a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18f-79e8-732d-8c96-ab6a439a53cd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18f-79ee-7f52-8869-ae76e9ca20a4

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18f-9054-7d81-8149-afd28a89b594
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18f-9058-7637-b293-a58be291cfb5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18f-905e-7a08-adf7-c2a39c4e0ae9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18f-9064-7645-afb4-f068c5e1df9f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18f-906b-7fbe-bbf3-af034ba2a244
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18f-9072-7a3e-af8f-85a498e265ec
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18f-9078-7996-8814-8169d1b5b58a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18f-907f-7b11-a567-dfc8c710f280

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18f-a67c-76f5-91fd-bf6633e99bfb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18f-a67f-7a66-aa04-b016e7862459
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18f-a685-788e-aae2-9d6ff8c0555d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18f-a68b-7446-a4fc-dc76b5aa1131
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18f-a691-785c-aa48-7451dd44bb5b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18f-a697-73ef-abda-420cfe27907c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18f-a69d-73ca-8947-030cbfbd1b3a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18f-a6a4-7646-97e5-9728257ecc63

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18f-bb5c-7115-9458-a205dbcfda6e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18f-bb60-78a8-9d94-cfbe1db04d15
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18f-bb66-728a-a440-78a710f86da6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18f-bb6d-7098-90aa-36ba546791d8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18f-bb73-7a48-8561-e4d288d64adc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18f-bb79-7cb2-a07d-9b8627410f4d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18f-bb7e-7618-8d06-c062bc56f689
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18f-bb85-7c8f-b469-983ead5dd96a

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18f-cfc1-7639-8ba3-fa1c5eb9fc82
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18f-cfc8-7138-9c3f-10a4649b626b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18f-cfcd-7eec-9d3f-c25a0bbc0638
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18f-cfd2-7aa4-802b-f7efb010357d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18f-cfd7-7205-8576-03ef98c873df
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18f-cfdd-7de1-be05-5fbb08fc8050
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18f-cfe2-711f-8983-61b33698cd37
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18f-cfe6-7abf-bdbf-77964b817cdd

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18f-eb2e-7226-854a-7327b198fb22
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18f-eb32-79c1-81e9-bfdb8683cbc7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18f-eb37-74b9-8d00-f3bff3b0fadd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18f-eb3d-7ab6-8c28-925725bdc30e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18f-eb42-70b2-9571-5c0e44799f1b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18f-eb48-742b-b562-c79fb1373e11
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18f-eb4e-7339-806f-cb91af74ee66
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18f-eb53-7b26-8447-93731108c639

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18f-ff95-70a0-acbd-eaf02a3a5333
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18f-ff98-7863-8db1-750cebc70867
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18f-ff9e-781a-a126-dd6c31056a55
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18f-ffa4-7b8a-b909-eee18c997fb8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18f-ffa9-781a-9f10-09299b30babb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18f-ffb0-7784-bf1d-ddfdb27664f8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18f-ffb5-7c44-b2bf-776a2ddb7fcb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f18f-ffbc-76c6-bf36-5757eba5296b

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f190-1932-752f-aba3-8d76c126b1c9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f190-1937-7d96-87df-87c26e946cf9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f190-193c-7b0e-820b-9939a49adeb7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f190-1941-7dd1-b2c6-21ca811e87d2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f190-1947-758b-bd71-b107f78b385c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f190-194e-7e9c-b3c1-0d673fed1ec1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f190-1953-7b7f-99a1-c4386cf938e2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f190-195a-7931-b1cd-60fd4c520d8f

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f190-351c-758d-b101-3094f7548b29
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f190-3522-70a3-bcb7-c80e95bf0273
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f190-3529-7787-ae23-35a6b5e88d6d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f190-3531-7005-b56d-936dd5f3e53c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f190-353b-798e-a145-3059716cd65e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f190-3540-7a9a-bcbc-1bb6a4b892d7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f190-3549-7b47-9941-fa56f4545ce2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f190-354f-776f-865d-53aa6441e56e

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f190-5721-7e4a-81ea-065aaa848e90
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f190-5724-75fa-a232-bc6fe3067903
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f190-572b-7a2c-b74b-a37ac294336d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f190-5731-7cbe-bd62-27ade4bb0b92
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f190-5736-7e8b-a6ee-d78ebf770bf9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f190-573d-784a-abf1-33217fee4e9a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f190-5742-7358-8e39-f5f7b880e0bc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f190-5747-7b15-8c52-3651e9645f74

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f190-663b-7a33-9fe0-e316d597e79d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f190-6642-7d3b-b5b8-1a6a9cb3266c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f190-6646-7a02-9bbe-3a9413849f5c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f190-664b-736e-925a-949d8e788579
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f190-6650-71ff-94ed-73bc1de07392
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f190-6656-7655-ad73-cbdad080b5ef
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f190-665c-79de-b0be-397f0dc3e56a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f190-6662-7562-9201-12fb25a97d30

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f190-8332-779e-a109-6909589c4a34
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f190-8337-791b-a327-de50a1b30e94
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f190-833c-7723-b3a3-b50898470f83
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f190-8342-7987-b9d6-e7be604eddad
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f190-8347-723d-80e8-cfd4256d4610
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f190-834d-7672-8c8f-fcf791928e51
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f190-8353-78c2-bec5-6b798d6d2109
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f190-8358-7766-b7aa-64edb552a7e6

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f190-8d57-757b-b2cd-1ec8ecca3289
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f190-8d5d-7dee-86ed-68ec6646eaea
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f190-8d62-7d57-adeb-d620aaaf3b1c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f190-8d66-795a-a58a-f8399e63b753
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f190-8d6c-71c8-81ba-62bf0d869d7d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f190-8d71-7b10-ac4b-83d0299cb2b2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f190-8d76-7ad4-a60f-1590ab5c4fbc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f190-8d7c-7809-bcb4-e8d1484ad84b

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f190-a425-77ac-ab48-4852a4902983
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f190-a429-7e52-83d2-0188b538870a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f190-a430-7076-b604-13a296662407
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f190-a436-7332-b75c-5facb53b9ec7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f190-a43c-7541-9946-366ca5fc5371
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f190-a442-70d1-b971-e48e3c82c291
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f190-a448-76a0-92ed-d5271db086c3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f190-a44d-75c2-8cfb-c2c28dc15507

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f190-ba1f-7836-8ba1-0ff3779d4f8f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f190-ba22-7e48-afa5-7227078b034e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f190-ba28-74b6-b825-618821e41d49
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f190-ba2f-72a1-824a-cdd518d0574a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f190-ba38-7aae-b1a6-9996602a6dee
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f190-ba42-7601-926b-23636224b9e5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f190-ba4c-778e-9608-6aac4e96abb9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f190-ba52-71d9-8c02-db8cd4d425b2

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f190-d75e-7912-a1c4-465b94991de7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f190-d761-7def-aecb-e26daec714c0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f190-d768-7c8d-a7b6-a1852f1cf7c5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f190-d76e-7da7-89de-fd9e2b4af229
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f190-d772-7e95-b708-9a82292ba1e1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f190-d778-706a-b101-0fd86f553ae0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f190-d77d-76f2-9dbb-e42ff8b26e81
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f190-d782-744b-8480-1e734c1a513d

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f190-eeee-778f-aa5e-67610ce0847d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f190-eef1-7f19-8b7f-bb82aa2a6108
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f190-eef8-77dc-a082-b001e34423a7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f190-eeff-712b-ab99-538f8b818f30
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f190-ef05-75c1-9795-80656f03b314
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f190-ef0b-7878-9ae0-cd3d510e7332
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f190-ef10-7b4d-9959-8a1798802ae9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f190-ef16-7c33-9c27-0854e7b41297

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f191-0ac4-72be-a044-1ed475e6847e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f191-0aca-73e4-9441-7bc28584a63f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f191-0acd-7463-a38c-6742516fe876
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f191-0ad1-7895-a9f5-66a8a9300a76
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f191-0ad7-72b2-9659-7eb957a2d41f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f191-0add-73fc-acea-5d737c6445d1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f191-0ae2-70a4-addc-04ddea5d980a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f191-0ae9-7613-a8cf-23e4b8a884cc

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f191-1fda-77ee-a337-505594771d84
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f191-1fdd-7203-beb1-45126b3558b1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f191-1fe3-7211-b821-825bcbd86f39
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f191-1feb-7b8e-a401-b3abddc52dd0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f191-1ff1-735e-9b11-158b54108c77
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f191-1ff5-7d09-827a-14d8406be178
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f191-1ffc-7f71-9764-28d43b3f8f9c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f191-2001-7037-9873-d354c57266f7

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f191-314c-731c-b1b4-177e46456149
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f191-3150-7cdd-985d-f971bea6928d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f191-3157-78a3-9468-abf306d580a2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f191-315d-7611-93b6-60724574866f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f191-3163-7869-a883-3eb97e912ecf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f191-3168-7c4e-b831-131f8409a215
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f191-316f-7db3-a604-f9dacc74d3ac
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f191-3174-7daa-bf9b-6d7e0b8a683b

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f191-444b-70f4-ab1b-fb0b0bb2bacb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f191-444f-760d-a0cf-2df3fbb6adad
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f191-4454-7be8-81ef-867515d3e140
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f191-445f-7b97-87a4-a00a9df89526
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f191-4465-7066-a428-ceba5c67cb26
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f191-446b-7970-ba30-f9fd283b28a8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f191-4471-797b-b8f5-cd1ca1fd9162
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f191-447a-7362-ba1a-83eb0b3774ef

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f191-5e09-740f-9144-7d4c7cdd7b23
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f191-5e0c-7ca4-b32c-b789e8927ecd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f191-5e11-78a5-9b8f-75c0fc4c7ff3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f191-5e17-783a-80b7-d3ce9b25a04e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f191-5e1d-7132-ab01-09c73a37b407
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f191-5e21-7a3c-9ce3-ed1d9f10ce18
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f191-5e28-7188-af21-241749ccf573
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f191-5e2e-72dd-a7c2-60ca9007db35

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f191-791b-76b9-b00f-215ccbdb1c5d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f191-791f-79d2-9514-1ebc75baaebd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f191-7926-71c6-9e51-b0092ba56b0c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f191-792b-70e2-8717-5cc4422d46cc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f191-7931-75f4-b73d-12b9678a7116
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f191-7936-70d7-b34e-4de98644878f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f191-793c-7bf8-bc1d-88bb08752ea7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f191-7941-7e79-a725-57156c1dafb1

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f191-9026-7f0a-a6e4-16dbe8a8661f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f191-9029-7c79-8666-2a399431c48a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f191-902f-79d2-98dd-338edff226c8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f191-9035-7aef-a1f4-030f15f259df
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f191-903b-7eb4-9aff-295b78fd3e87
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f191-9043-78bc-9ea3-e92ed8edc9ea
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f191-9048-7b5e-a56d-209c568cb067
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f191-904e-7eac-9123-e87b2d8adb1c

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f191-a36d-7943-abcc-f05fd03b805b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f191-a372-7c16-890f-94ddbe79697c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f191-a37a-71a4-aaca-14c12ac1b85c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f191-a37e-7b28-95e8-580d410218ee
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f191-a383-71ca-bb7d-da097b530d56
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f191-a38c-7568-b2c9-c259f96437fc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f191-a392-70ca-88c4-f6ca846254c1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f191-a397-741a-8b76-091a9bc8990a

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f191-b912-7af6-af87-c62093e0afc7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f191-b924-71fa-93b8-e46523f1bef2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f191-b929-7764-92e9-d772d38beeac
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f191-b92e-71e5-ae8d-0c53a8439259
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f191-b934-7c80-ad4d-58624b5e6043
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f191-b93a-70ef-84f0-7be984a1cf81
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f191-b940-7055-95e4-f077b0d9a204
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f191-b946-74eb-b374-427944820dde

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f191-d52e-77a5-af54-725ad01a2209
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f191-d531-7485-83f8-1a28e6cdc6e8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f191-d538-79c6-a83d-7f2723f720d6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f191-d53c-78c0-9dbf-1fe13bb4b5f0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f191-d543-7bd1-8a7b-a92500ed6513
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f191-d547-773d-b283-94babc027457
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f191-d54f-7c28-8572-ac2ad9676828
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f191-d555-7ee6-b2bd-3ebf3c970344

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f191-e933-7cb7-b393-83f8b7524947
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f191-e936-743c-aa7c-1463ab0898c8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f191-e93d-7ebe-ab35-a43b40bbb728
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f191-e941-7313-9f58-7a3135f73a03
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f191-e948-7e54-82c9-31f285a4005d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f191-e94f-7e6f-b66d-35c652ade685
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f191-e954-7927-9bf6-f79e61982d8e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f191-e95b-7335-8807-42fdd757ac9b

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f191-f909-7c8f-9781-0cddd04dd75a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f191-f90c-71fa-af45-5e12eac96777
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f191-f914-7340-aac4-e13283dcc6eb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f191-f919-7450-9422-b592eb6864ed
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f191-f91f-7a83-9d54-bb1df67840ef
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f191-f927-72a7-bd17-7ba23f5af9e3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f191-f92a-7cd6-a441-52c19927c4d1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f191-f930-7810-a0cb-6399118436e6

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f192-0f0d-7912-9f8e-a1ac8bc35d5f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f192-0f0f-7baf-9f38-017ae1450eb5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f192-0f17-7d4f-aff9-c1bdc034707e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f192-0f1e-7631-a6e8-8683e8fe1c04
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f192-0f25-7bfd-9556-c5fb18a90f37
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f192-0f2b-756d-89d5-6ca9b857f6c3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f192-0f31-78ef-a911-61a3854648cd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f192-0f38-7ae0-a6e6-fcd181404223

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f192-22ea-7c9e-8a4f-c9f43f32a481
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f192-22ee-789a-b736-3de6b85fc318
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f192-22f5-7745-b169-2788905b9a5b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f192-22fe-7aef-9e28-1531542c1bed
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f192-2305-7011-ba2b-13f7aee11ede
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f192-230d-714b-98ec-eee6249316a0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f192-2312-7a1d-b745-f56e852c3730
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f192-231a-75ad-8495-5f7bab11818f

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f192-3950-78f4-bd29-f3aff5675ff0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f192-3955-7489-aeec-6fc968263d57
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f192-395c-7cf4-9b3a-98e352ef8bef
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f192-3962-7a58-b213-f9ab2cca8466
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f192-3967-78de-bad1-9f414e5d18cf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f192-396c-7746-93d5-5ca47afbe82d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f192-3977-7a23-8ac5-df755d163ce0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f192-397b-717a-845b-bc2844a3989b

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f192-57b1-72e0-a79f-285ef8df916b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f192-57b6-79ff-9870-c611c36f6c1c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f192-57bb-74ba-bff0-a49f14677b6f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f192-57c1-782a-b0f9-215fdc72b13a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f192-57c7-79a0-b72f-856ec1529635
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f192-57cc-7d43-80a9-571f37db9a07
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f192-57d1-737d-8f6e-47e446536ce7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f192-57dc-74ac-8dfc-fee0ec929108

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f192-67d8-7263-a056-f7d5787a2af0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f192-67dc-71b8-94af-80ea61c1e876
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f192-67e4-7371-975d-c2b4e2719427
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f192-67ec-76c5-ac9b-0fc8b7591757
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f192-67f0-7ba2-9ef3-9eae3fc6f15c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f192-67f5-7921-ac55-1271e7018a16
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f192-67fc-74a9-a5f5-cc5bc145aca7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f192-6802-787d-bcf9-a599ae2f2bf8

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f192-71dc-7297-b02a-4f4ff564e65a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f192-71e0-789d-8b6d-8f0eb9859144
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f192-71e7-7d57-8606-4fb319dd47d2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f192-71ec-79d1-a2ee-c9ec5a77723a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f192-71f2-7ea5-a3a8-4a5500b69928
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f192-71f7-7b94-acf3-03784ea95dd7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f192-71fd-7e5e-abb1-93a2f3ec80c3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f192-7202-7554-b027-fe70f9e38fb0

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f192-8ae9-7da0-accd-7aff9a144341
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f192-8aee-7a17-a439-48bfe5538b3d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f192-8af3-72c5-a215-fd15863e6d87
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f192-8af9-7956-a91a-135332e618d2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f192-8afe-7b83-b983-d5f981ccbcfe
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f192-8b05-7705-8559-971690f16dcb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f192-8b0b-7c06-93e7-c34b5140eddf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f192-8b12-7345-8024-8c8361427932

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f192-9f4f-7352-ae5a-cd1d7c270c43
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f192-9f55-7774-b374-f4f9d000de3e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f192-9f5a-71fc-8d1c-7de7e0ca868b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f192-9f5f-79ca-ad70-dc786448cae9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f192-9f65-7c69-9529-fae6e859bfba
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f192-9f6a-7eaf-b9d7-8e95e6b0a048
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f192-9f70-77fa-91ac-b0a68fdbeba7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f192-9f77-7383-b6f9-695d0c314976

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f192-c085-7e37-aec1-8ea2a25824a7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f192-c08a-7ce6-90c6-93d9778b5eca
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f192-c08f-7da3-8a8a-1e76ed027426
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f192-c096-75b9-b1bb-c7dd19ea5dbe
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f192-c09c-7436-8dee-a3aafbb0048f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f192-c0a2-770c-a772-0013c7ab885e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f192-c0a8-79a6-98bc-96de6a41c453
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f192-c0ad-78dd-b282-bdd14f966b99

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f192-d9a0-71a4-9476-4f2143054d85
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f192-d9a4-7922-b732-4a960d59e4a9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f192-d9aa-7807-83cc-9a14a0c38e69
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f192-d9ae-7a22-869d-f1a272cea3ef
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f192-d9b4-7b73-b1a1-de159d96ba23
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f192-d9ba-7b2b-b369-917238200556
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f192-d9c0-7940-90ab-bc3087f96a1d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f192-d9c5-7bf9-99e0-5beb1ba282a7

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f192-eb41-74b5-b339-b5dfe6f9f4a0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f192-eb44-7899-9c7a-5f204b9aa846
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f192-eb4c-7a0f-b69e-6f3bd24971ed
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f192-eb52-7722-a058-6cc00fe66a1d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f192-eb58-798e-b8d6-1f31f6366581
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f192-eb5f-7721-84c5-d7b862be21d9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f192-eb64-7ed4-9d2c-486cf3301707
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f192-eb6a-7d91-9c88-521abbef19c5

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-013a-77e9-8906-f6136a496c40
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-013e-71ac-8405-8c5cdd317703
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-0145-7ffd-9abb-39b58068b530
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-014a-79c5-adb8-6b7f8b07bb95
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-014f-7f3d-b0e1-d4ecaa7b46ca
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-0158-78fb-9ab0-cdf88cb656c3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-015d-7524-b72d-8a76c95ea1df
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-0162-796e-83ef-79df5620559e

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-10b5-7bbc-9c60-e327aed64e04
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-10b9-7b02-8d6a-f3b50aeba1dd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-10c1-7def-a303-680e92af658e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-10c6-7bea-811d-48c0fb524584
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-10cd-76d2-bbb9-da1c72d768aa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-10d2-7ae5-9c75-91b887dffab8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-10d8-7619-b201-42ad3a12fa85
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-10de-738c-b8d9-7746248d7cf8

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-211d-7f05-91be-5bb1e4e6597f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-2124-7170-90bb-a6f9b10f5c17
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-2128-7203-86f1-c6f337348c82
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-212e-7b4e-a4db-b1802862a886
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-2133-74df-9f9d-02ab9eb29f82
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-2138-721b-b0a5-3898805a1051
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-213e-7194-bc0f-1f42706ddd3d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-2145-7f54-88d9-8f2079e9d7f3

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-2826-7cb8-9579-b10e43137722
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-282b-7e32-9369-3eccde9bdba7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-2831-703c-97c5-5f4e83245d79
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-2837-7bda-b1e6-ddf06ec6df9f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-283c-7f05-99fb-8b7e6233aad5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-2843-7a55-9dca-ae2112685ffc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-2849-7b49-8e03-079d07e7cc6d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-284d-7baa-abbc-b899c97bbb68

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-44d6-735f-adfa-5db30595bd33
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-44da-75d0-8ae3-39ae10a99096
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-44e0-7351-9675-3feb0b0dc799
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-44e5-773c-9214-1ea722349d1a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-44eb-7046-bc58-60f5a1e120fe
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-44f1-7519-bbdb-33222089ae85
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-44f7-7f0c-ab67-b2d277aa9aa7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-44fc-7f66-9e5f-0f1c4df2c036

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-58d8-731f-b78e-202abaafbc82
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-58dc-70f7-9168-ec459aa0503e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-58e2-7f20-95b0-fb83b8df83a0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-58e8-7242-be85-458bc82a033b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-58ef-7615-ad3d-6d1e1b513508
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-58f4-71f6-9473-44ec0cc0af21
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-58fa-7919-abee-2dfe15966197
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-58ff-79b4-a3ec-657705c8083a

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-69cc-7b13-a02b-9e3014c72a43
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-69d2-70a5-81f5-c11b46fe1684
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-69d7-74d5-97a2-7f255a512d89
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-69dd-787c-982a-a7ac76140452
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-69e3-7dde-ad7f-d316cf6fca68
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-69e9-7850-8c2e-45343b2ae8c1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-69ef-7959-978d-0bc41d5f030a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-69f6-7a05-af2f-f0f8fdd7cafa

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-7c68-7a4c-873e-3291893d33d7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-7c6d-74c7-bca1-4c809f333c5b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-7c73-7c4c-838d-b43e558499a7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-7c77-78f1-9eb3-805de6a7a0db
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-7c7e-7935-9b87-49ac9b1a29a9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-7c84-70be-a9a9-69f1249f7e15
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-7c88-79e7-baee-0c3267060b91
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-7c8f-7488-9c61-6dcf995b3f54

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-9386-783d-aa68-6c88db69a1b5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-938b-77c9-8346-9478780da9b6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-9390-7c42-ad29-f5277b16d28f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-9396-7fe7-a856-57e6321135e9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-939b-74e7-ae78-8b71b397f2ea
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-93a1-79da-9437-818368641da9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-93a6-7018-a6a5-7060c1165e76
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-93ab-744a-b055-c484c99684d6

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-a962-7e5c-8479-55a6d561bedd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-a967-7221-8a00-5d8e97566a1a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-a96e-7bc8-a219-d29f80651948
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-a973-7d4e-bcaa-272be2c932dd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-a979-7705-a0a2-6b025040a0b3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-a97f-7949-9764-acb217767d53
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-a985-7163-812e-8456726f0bc5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-a98b-74f2-8f29-c074346292ee

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-bc62-7a7a-aee9-d7f6bfeb49ed
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-bc65-758b-a835-94b63803a974
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-bc6c-7f6a-8e31-9dffd528873a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-bc72-7ba8-b89b-89c97aac68ba
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-bc77-7101-9cab-0ed6348e1eb1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-bc80-7254-975e-60b5a61c4c0b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-bc83-716b-84d6-db2f330f682e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-bc88-7802-a8be-9f223fd64828

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-d44a-7c14-bd97-c36e6604fdb0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-d44e-73f8-a0e6-b54736119430
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-d454-7a89-91f2-fd0c996d6f2d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-d45a-7fc9-a70a-ebbe17f22ebf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-d460-7943-9a6f-b809e4bafc40
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-d466-7dcd-97c8-0f76f6b122d0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-d46d-789d-9851-6d1c9b7333d1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-d474-7d07-9986-036ab66df166

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-efa5-79a2-b358-6a70bd460ae6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-efa9-7556-b4d7-aa09cfe25358
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-efb1-7f38-b2a4-9782b319ef4c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-efb7-7f14-8d26-92efaf54a2a1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-efbd-72d8-9921-e4ad2b3f7f01
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-efc7-7835-a20f-d633c58ad3ba
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-efcc-7560-ba73-bf279ecfe415
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f193-efd1-7461-b0af-6bc971fc3468

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f194-0081-72b2-aa69-f26294d65670
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f194-0084-7a39-8c5f-62adce187223
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f194-008b-7f01-9411-d13b2b1a5e62
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f194-0093-7855-9f58-202247d824db
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f194-0097-7f78-94ce-e77da72e787a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f194-009d-7255-80ec-4dd55b8da868
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f194-00a3-775c-988b-184f0de7870a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f194-00a8-74f7-9ec7-a55cf1fc318e

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f194-12d3-7fcc-9782-3fc8fbeeb79f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f194-12d6-78f7-9d17-fcb17d215e2b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f194-12dd-7f50-891b-af423dd6ab00
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f194-12e2-7565-964e-29fd10e8cd8b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f194-12e8-7ca4-b61d-fcbcf6ee4802
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f194-12ee-7891-9b07-6df170d14992
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f194-12f3-7e16-a552-c6862bf0908e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f194-12f8-7976-b897-2129b84f15ce

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f194-2cce-7720-9dea-ed050e80dbe9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f194-2cd2-76b7-b4d7-e61266256fa3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f194-2cd7-7866-a922-3e201680ac0b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f194-2cdc-7683-b52b-c641702d2d2b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f194-2ce2-7bb6-bccc-902981b46e08
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f194-2ce9-7e2c-9d58-194d29da6058
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f194-2cf1-7074-b1d3-17d4a46e69b2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f194-2cf4-7ea0-96f7-c306ee86163d

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f194-5146-70d0-8246-16f1b71a9c63
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f194-514c-77bd-a894-f768fc6414ad
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f194-5150-738a-bfed-ee1e1874ea5f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f194-5156-72ef-b4fc-ed00ab4f51b5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f194-515c-74f8-a6f0-4b299e511636
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f194-5162-7916-891b-1af596468104
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f194-5167-74c2-8b90-6394712305ed
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f194-516e-7334-8c3c-1f4aeeda7ccb

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f194-63f1-7240-ab0c-e7ea7ac4970f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f194-63f5-7192-9942-d0991412cdf3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f194-63fc-7a75-88f7-dff29eb84065
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f194-6402-7863-9b1d-335affe20f13
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f194-6408-7fe7-90ce-fdd6e18ea81b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f194-640e-71a5-a760-6d687876c3a5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f194-6414-7c99-b544-47f4e9c2e611
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f194-641a-770e-9325-64db97454461

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f194-7d43-74d3-9ff0-b69851f77460
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f194-7d46-7488-8896-40b91f5c5557
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f194-7d4c-7d36-b1c8-a8ae40e4ea19
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f194-7d52-79bb-86e1-3c0688712314
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f194-7d57-7505-9c63-7a1bb8eab2fa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f194-7d5d-73c9-bac7-4a49c9428584
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f194-7d61-7eea-916d-3997f4b0d110
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f194-7d68-7ddc-9d59-02e8f2e1da30

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f194-8a0a-7e13-8098-73da23403b96
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f194-8a0e-715d-98c6-503792270d82
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f194-8a15-71af-bd83-11884ee00383
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f194-8a1b-7a02-ab83-b285912db390
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f194-8a21-7f9a-8f5e-e442ba6f7b27
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f194-8a26-7c9f-ab5b-c848032887a1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f194-8a2c-7604-8005-b7a4204217cd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f194-8a32-7a84-817e-dbf6e1cb7c2c

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f194-a164-7915-b472-99eaaada2cc1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f194-a166-7279-8268-c7ade784ba9f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f194-a16d-718e-9bcc-ac244e0f561a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f194-a172-77c0-ab68-2162fb4b5284
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f194-a177-7b54-aed9-ad08d1f7d007
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f194-a17e-752e-b10a-37e6403aaa27
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f194-a183-7cc4-8f94-90058920e675
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f194-a18a-7367-a154-4193a720ab4c

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f194-ba97-77ec-8962-bf7c278e5ec1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f194-ba9b-7ad2-acf2-ab5bef4af92a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f194-baab-7c82-b24b-5964328d1e01
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f194-baae-72c7-8ba1-8da027c8138e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f194-bab6-75e6-acbe-6a95e8076999
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f194-baba-744c-a788-47950cde7fdb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f194-babe-748f-a11d-08ba7994df96
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f194-bac4-7fd4-8f8b-6ade898409f5

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f194-df33-7bb9-873d-f304d6ea4217
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f194-df36-702f-97d8-88cc8ee2f9eb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f194-df3c-7b2a-bec9-2ac609957701
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f194-df41-73b9-a6ed-26d756ed83c0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f194-df48-7f44-a86f-7dafe0bbea58
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f194-df4d-7153-9a77-a05db79a72ed
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f194-df53-7f5f-a0da-127e8ca42079
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f194-df58-7135-ba0e-caf6a73024c4

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f194-f358-76e9-9e88-d3437fb95f76
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f194-f35c-71fa-8b36-1768121c3def
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f194-f363-7efc-ade9-ae527f8d83f5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f194-f368-748f-9cc4-4e553d45d12e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f194-f36d-7287-9c5f-a22ee6bc52fe
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f194-f373-7632-ad19-3bdaba287ec1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f194-f379-7f8d-9f9e-68dc3ba37d16
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f194-f37f-7084-82ac-a99c13206628

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f195-00a2-7944-8dcb-af0a1eee5249
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f195-00a7-7e41-9b53-10a00023523c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f195-00ae-7222-89b2-96f5f7f431f5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f195-00b3-796c-8d72-7f11c841d665
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f195-00b8-77c5-9682-038c05dcc335
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f195-00bd-7a64-8b65-81c7d492bce4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f195-00c3-7ab0-bec7-6f327250ea18
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f195-00ca-7469-9c1e-e68e9ec5eb7c

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f195-1383-7eb6-8b71-8af37f3ca626
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f195-1386-7fac-af5d-dba9963c538e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f195-138d-71b8-bcf3-3165937b9b24
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f195-1394-722d-a755-1119e1c6a5f5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f195-1398-7323-9d1c-6ca83d52d2c1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f195-139e-7842-afe9-ddd9049ad16d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f195-13a4-7737-9446-7413bb688ceb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f195-13a9-7185-8576-7e23b0cc581e

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f195-2c84-7451-bd11-38794b6377af
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f195-2c87-78a6-bf13-bc3819db71df
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f195-2c8d-7680-8281-6585b7ea5684
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f195-2c92-7a49-ad19-69cce78b7bf1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f195-2c98-7977-a873-f21b3caa186e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f195-2c9e-7a4f-a993-5d5c32eaca76
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f195-2ca5-7fe9-9431-24fca04c0b34
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f195-2cab-7665-9f62-4acba6acb594

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f195-521b-7d13-a927-fb8dbd3e0ad0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f195-5220-7b3d-809a-756c71aff858
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f195-5224-764f-bf3a-6fd2e8b2b2f9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f195-5229-76a4-9d8b-aeee45a2dfd5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f195-5230-7c5c-b1ef-5320fc8a7e84
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f195-5235-74e7-b4c7-e2ca7b203e40
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f195-523b-71c4-9ae5-deb3f3ce4124
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f195-5241-7982-afde-30ad74201716

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f195-6bbb-7894-af24-157959633159
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f195-6bc0-79bb-baee-40671ebefc61
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f195-6bc9-79d2-b044-32edaaeedc6a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f195-6bcf-7b13-b487-9c9eabfdec97
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f195-6bd4-7ccd-a121-837495e4476b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f195-6bdb-7cb3-a6cc-13dc131b28a0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f195-6be2-7828-b6b3-a022f1301bc0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f195-6be7-7a27-a674-da72e00f12f4

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f195-7deb-7e5f-82bc-8d173197b694
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f195-7df2-7f6f-951d-5922958f4d8e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f195-7df5-7ac1-865c-ebe903c9dc53
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f195-7dfb-7d51-9ed6-f77335cade6a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f195-7e00-7520-b173-2584e115a132
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f195-7e06-7395-905e-9f281b3a7227
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f195-7e0a-7f73-b097-8229297a04c3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f195-7e11-7511-8dd7-2eb86513d674

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f195-935e-7214-9ad5-d97ee832cd80
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f195-9361-7dd5-9809-bfb5ae09014b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f195-9368-756d-a42c-a63b8c5431d2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f195-936d-752a-ab82-adc8ecc2f340
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f195-9374-7326-b065-bdce8d69a7c5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f195-9379-7ddf-9a14-25672b68d4ab
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f195-937f-79da-a1a0-3dcad077d6f8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f195-9385-77ee-932a-d55a6a4e46ff

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f195-addf-7e22-bdf2-aec409413fae
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f195-ade3-7e7d-8e87-2e0828a5231c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f195-ade9-723c-915f-015ab82ffba3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f195-adee-7bee-b2b0-9b9f1eab3476
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f195-adf4-7062-a1c7-284ef1ffaa05
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f195-adfa-7aac-88b0-f09d00ae113e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f195-ae00-7b45-aeb4-d765444ca471
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f195-ae06-7fbf-a87b-9ef0d6fdc86c

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f195-ca3a-794a-b996-e551785abe48
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f195-ca3f-7683-a495-9f80fa5197b9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f195-ca45-783a-b8ce-0ceb05d9f266
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f195-ca49-7f25-a560-c2e05d6483e5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f195-ca50-7120-b53c-76401fbdd3ef
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f195-ca55-7f84-8d5b-039aa984900a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f195-ca59-76b8-aa2e-ac744dd3575b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f195-ca61-7253-8fb6-53e7490dd83f

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f195-e35f-7278-ab83-807e002803c7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f195-e363-792d-8778-6f3d6b0262e0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f195-e36a-7981-8e7d-91141d801793
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f195-e370-7d36-b08f-c31effafa994
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f195-e376-7523-924f-ef52efe80aaa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f195-e37c-7822-b849-1fa87f975503
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f195-e382-701e-a949-9d6ebd8b9e12
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f195-e387-7475-9e45-fd01584bab99

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f195-f2f5-79c1-a950-a250cd1ad446
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f195-f2f8-7703-ba7c-3bf8950c4683
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f195-f2ff-714b-bcce-7c008446f372
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f195-f305-7643-bad6-4f3fafee7a51
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f195-f30c-7279-9f7d-3adf63e761db
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f195-f312-729b-93af-b7e70449a28a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f195-f317-76c1-b28f-4e19cb4601be
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f195-f31d-731b-965c-fdad24502a20

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f196-0339-77ff-b6f9-f28fa2f6eab5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f196-033c-7855-aec1-930bf4639d0b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f196-0344-7d5c-baa8-5a45f579c869
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f196-0349-73a3-ac91-5c82161196f5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f196-034e-77d5-8e0d-7805c68c7318
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f196-0354-7b5d-b0e8-073fa7e9806e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f196-035a-793e-a4f4-3f25fdaa0a44
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f196-035f-7b26-ad53-82ff2bb206c7

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f196-1f5b-7885-8380-04461677af6c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f196-1f5f-73c6-abd1-ec09b35ac4bc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f196-1f66-7122-98c3-5168f44a2a90
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f196-1f6b-7bc5-baf6-0e85258f1fe0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f196-1f70-7f34-b2e0-89c088cca7d7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f196-1f76-7549-9f7e-48e0fb44312b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f196-1f7b-7140-98a8-4ac26d11f23e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f196-1f81-7b43-9ac3-6e1aed246cd8

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f196-34ed-7d8e-b5ba-8f867e71cce2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f196-34f2-70a6-9ed0-284677c130bb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f196-34f8-7744-bd5b-199cbfa235a8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f196-34fd-7c0e-b5b8-f787c160fdf9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f196-3503-79da-9cec-7065b2d21024
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f196-3509-7908-8041-8007a5616ad3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f196-350f-7780-98df-d782343174c6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f196-3515-744e-93a7-afa9e5346500

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f196-4d87-7c8b-829e-4ba65de28c67
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f196-4d8c-786d-9937-1cbcf707bb09
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f196-4d91-7a5f-87e5-3dd7c2004f44
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f196-4d96-76c8-9999-7379dfa5a448
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f196-4d9c-7ee7-b543-ef47b3f6ba2b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f196-4da2-7bef-a0d0-3f5e649c59d0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f196-4da5-7be1-9f56-32b2813595df
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f196-4dad-743a-b528-498f8dbd83cc

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f196-5ec4-7ba5-8102-2f5618a7d180
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f196-5ec8-7add-8399-3affea9c2bdd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f196-5ed0-7318-a756-f22ec0764850
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f196-5ed4-72cf-adb6-a8336221b0e9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f196-5edb-7656-be08-5e551c5f6f7f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f196-5ee1-718d-87c4-d712a7e9b207
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f196-5ee7-7955-b866-b14c67769102
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f196-5eee-70a3-a179-04f884939730

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f196-7ccb-72b3-9e28-330d0875723b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f196-7cce-74d8-a31e-ffd905d955d9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f196-7cd5-7d63-b4f2-9d15b2445ef8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f196-7cda-7c7b-962c-d5bff9e3a637
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f196-7ce1-7166-8c95-f6dfa4231ae5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f196-7ce7-7ece-8f45-8b2b7d61a2cf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f196-7cec-7d2e-a400-48e6b8594d73
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f196-7cf2-77cc-bbfe-5505208164a1

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f196-9384-7d90-9cae-54c78de64fa9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f196-9388-7411-87e1-d60b6bf3e113
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f196-9390-7b14-a4aa-4eecc8fef887
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f196-9395-7015-92c3-dc2107d41a00
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f196-939c-752c-956b-dcf13412f341
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f196-93a2-7bcd-9ce9-76e63cbc559b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f196-93a7-7c9c-8f49-d461989a94ac
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f196-93ae-7bb8-a270-c51994fe5852

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f196-a546-74ac-aaee-e1a28830a9c9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f196-a54c-7310-84ac-b70ec227c4f8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f196-a551-7031-ac38-2b69e17b2e26
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f196-a556-75f9-8196-e4c780e3ef29
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f196-a55d-7c98-a1f2-a6d2eac0b9a3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f196-a563-72cd-aea6-3e8484f030f4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f196-a568-7c93-baac-c7d088b0301c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f196-a56e-7845-aa00-f7ea03f93bf0

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f196-bcda-7dd5-bf73-736b670b8bb4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f196-bcdd-775f-9556-eacfe0b034d7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f196-bce5-73a5-b3aa-3f2b68a27d68
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f196-bce9-78ae-88b6-79531f959a98
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f196-bcef-7832-aa36-e961c3b41353
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f196-bcf5-7767-bffd-f85e3718610a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f196-bcfb-76fe-b5f5-a2f7d5bbe46c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f196-bd00-7124-8470-f68026fb8f60

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f196-d1cc-720d-8f5b-d152939cc9dd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f196-d1d3-76fd-967f-a1b18d14f11d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f196-d1d8-7b9f-a4d1-e57837de098c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f196-d1dc-7db6-9448-6c444a622a11
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f196-d1e2-72aa-9d34-212596021692
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f196-d1e8-7043-a9f5-f891e53f801c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f196-d1ed-7b7d-81c3-6e4900fc9574
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f196-d1f3-75d1-91ad-4b759dbc73f5

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f196-e539-779a-98b5-9a1c1f1f9cc3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f196-e53d-7501-abd0-785039528433
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f196-e543-7519-bd3e-a8ea20ff7808
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f196-e54b-7f15-87f5-cf253cd0ae14
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f196-e550-7a83-84a0-c794161f845c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f196-e555-7a5c-b799-9d4918a19f50
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f196-e55b-7884-85a6-bf8322ca8687
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f196-e561-70a0-a977-564795bc2b19

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f197-023f-77d9-b0a8-58a6c7e83acd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f197-0242-79bb-9c09-c21cb7bc7916
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f197-0249-7b8d-abdb-cde4c4e6fed2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f197-024f-7191-a67a-53ace3108c0a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f197-0253-7523-8301-28089e1671e1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f197-0259-7b22-831b-8ec91c77286c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f197-025e-7494-ab8a-1c54deb28bb2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f197-0264-7309-b5e1-35d85526131a

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f197-164f-750a-a4d0-b08aa20f2a7e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f197-1652-7ba2-a3dd-2fc8a76518f3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f197-1658-721a-8a11-c9673d1582b5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f197-165e-78cd-a28a-5a4209990614
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f197-1665-7372-b2ad-57ef6e3bafdb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f197-166a-714c-9c73-b77bf0002cce
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f197-1670-760a-bb09-72e2641ebe52
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f197-1677-7d74-8cee-c63bc0df0232

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f197-2b51-7737-8cfa-cf101c5ac218
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f197-2b56-7b5f-a052-9e45b1ff17d4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f197-2b5e-7e5d-b358-8feb58559f10
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f197-2b63-7116-a1c4-28fa8e20bf99
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f197-2b6a-7ca3-821d-fa84601a9e1c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f197-2b70-78a2-9af8-39e50808afb3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f197-2b78-7c1f-af4d-63d92f2d33d0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f197-2b7d-768e-9755-0fd782184c02

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f197-4991-7ad8-8060-8c0d98530b99
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f197-4994-7e90-ad57-b4c39d34d4b9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f197-499a-78af-ae1c-30b2ed7ef70d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f197-49a1-7c7b-9492-9a356913172e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f197-49a6-7d0c-b917-77361cd46115
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f197-49ae-7a11-a27c-e8cbcd6ee6cb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f197-49b5-76a2-ad76-359e8b39a71b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f197-49bc-7e87-897d-fa089b8f08f1

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f197-5540-7ba4-9fae-e53bc1f946e5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f197-5543-7ef7-9c45-e29545dd474a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f197-554a-74ea-a231-fba6fca2a43f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f197-5551-730b-adcc-afa92efb5fa3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f197-5557-7ada-be98-564b5581f262
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f197-555e-7cf4-aa47-d858e9e24408
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f197-5563-770f-8113-185f61d7173d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f197-5568-70b5-92bf-50b7c2e0a755

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f197-6d52-7ae8-a81f-d5f1faa756c4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f197-6d56-7893-94d6-ea6a96e5b8b3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f197-6d5d-7a97-a2ae-eac2560c4bf3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f197-6d61-7489-b31d-f797eb87c5da
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f197-6d67-7eb0-ba35-0f98c66242d2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f197-6d6e-7488-8d43-c5279a401b4b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f197-6d71-736e-bb74-957eda333daa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f197-6d76-7815-bc0d-1b9e7d9dacad

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f197-8b71-7741-950e-7591d93c8de2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f197-8b75-7a56-b840-cea0bd62a843
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f197-8b7b-70f2-bb0d-ccb8e9fae035
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f197-8b80-76ca-a353-c18e67ec3d87
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f197-8b85-7275-ad84-9d6c1b6bd8ed
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f197-8b8b-7558-8f74-b7b7b70aad3c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f197-8b90-7737-b790-ed37459ea322
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f197-8b97-7e4c-9e8c-bf36ab50dfaf

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f197-a10d-73a9-92d8-103c2a61fa1f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f197-a111-75d9-992e-aab28b862477
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f197-a118-7d62-a74b-cb9ea6108816
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f197-a11c-7fe1-8718-18a5b29d02e0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f197-a122-71a8-8bf1-4c8e53a92393
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f197-a128-7036-8eb4-ef41ef0fa7f1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f197-a12f-7bff-bd2b-0748a480bdc0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f197-a134-79da-bacc-8f750dbc25b4

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f197-bea0-7a5b-aed5-89747758cc86
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f197-bea4-7ca5-9b50-d2d5050d7525
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f197-bea9-7a23-ba62-0578468917a9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f197-beb0-7791-826f-66f5e232750b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f197-beb5-732c-9621-bf4f19fccb50
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f197-bebc-7e3f-960a-c37b96783afd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f197-bec1-71df-be7f-0933399c7b8c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f197-bec8-7d67-8934-b3c876ba934f

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f197-cfac-7f44-a4ec-094d0d15c8fc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f197-cfb2-7ab2-bab4-0b41360393f3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f197-cfb5-7534-85a2-17ea037367ca
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f197-cfba-79b1-aa31-11402095cd05
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f197-cfc1-7a2c-93fa-5976ab899f33
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f197-cfc7-7344-9fed-b7790aba7a2c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f197-cfcc-72cb-a9c6-33ccbb66be35
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f197-cfd3-757f-bc6b-5030a94d699a

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f197-f085-73fb-b7fa-6e6b03a76099
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f197-f088-71c9-a6b9-83dd16d85c93
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f197-f08e-768e-ac74-6ec2885088a1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f197-f093-78dd-8c31-4bdd1cf2f6a4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f197-f098-78bb-955c-97f0cf52984e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f197-f09e-7569-aa55-8db4f7d69651
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f197-f0a5-7d72-9528-f7540f30bf2f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f197-f0aa-7c91-83ce-e06db19e2da0

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f198-0cd0-796c-a715-072fe953fd01
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f198-0cd4-799a-82de-6a0b7edf416b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f198-0cd9-7aa9-8006-f95463c0ab23
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f198-0ce6-7026-a32a-c32ac213ef32
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f198-0ceb-780f-9dcf-8d29cfe3747c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f198-0cef-7754-8e93-3d7eeddee7aa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f198-0cf6-79b7-b260-4702ef182cbc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f198-0cfc-7ebb-bad5-fcc95bb9d36f

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f198-25cd-79c9-aaf6-7bde6b2ca429
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f198-25d5-75ce-a95e-da72a0347aa3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f198-25d8-7fea-bb7c-e7246311a49f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f198-25df-7efd-89f1-44e655bf8cd3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f198-25e7-7d9c-b4b3-e847aabeaf98
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f198-25ee-7413-8fe6-9e13ed913cbd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f198-25f4-786f-a5b3-faef93aa747b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f198-25fa-7765-87bd-a46b17c81461

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f198-4344-757e-b260-a4c63f52577c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f198-4347-79a6-b022-b4d89ae0abc6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f198-434d-706f-a66f-bd865db9ae12
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f198-4352-7ebd-a189-6fb7ff40f80c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f198-4358-79a8-8943-5333dc53eee3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f198-4360-79fe-92ff-208cf99d9875
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f198-4365-7f08-ae95-9f3c2f174885
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f198-436a-70ce-ba32-f62a559d5719

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f198-50a3-7d2a-ab38-74efee64e515
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f198-50a7-7a00-a331-3071bd3597fb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f198-50ae-7f2d-ac51-44f2b41da076
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f198-50b4-717d-816a-02ef54bae000
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f198-50bc-7848-aad6-5c805eb8081b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f198-50c4-71ff-9d39-1a5916bd4d48
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f198-50c8-7af3-a7f8-36656b00dfbd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f198-50ce-7658-973d-70f3aef1eef0

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f198-6f5d-71f7-9e92-7365b240d22c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f198-6f60-72ae-aa49-d7903f18c6e3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f198-6f66-766e-b667-026ce0db5c48
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f198-6f6c-7965-be47-66e20daf0c98
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f198-6f71-7320-90e4-7e9f13116159
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f198-6f76-75d7-8e84-ac4144e741fb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f198-6f7e-737e-8afa-7f6fb0d95ede
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f198-6f84-79e1-8ceb-08d403455636

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f198-819e-7421-9f29-97458d8c2022
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f198-81a2-7d18-9bcc-3fdcd488b7ff
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f198-81aa-7577-846d-265f0d2667c6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f198-81b0-7020-9612-1f19dcd55014
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f198-81b6-7f36-8ff9-977619ec3f21
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f198-81bc-76f4-8ab3-f7479f6008a0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f198-81c1-746e-a98b-40c8c20d5a79
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f198-81c8-7ebd-a2f3-48517725fe74

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f198-96a2-7dc6-becd-2cdc25e9c753
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f198-96a6-7349-90bb-bac805e94733
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f198-96af-70b9-979d-1094b5be547a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f198-96b6-7dce-ba91-0bc865cbd827
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f198-96bd-7a76-9007-f8872df49f3b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f198-96c3-702e-bf35-8c4b6e3dae2b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f198-96ca-76fe-a64c-4df5749e42ce
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f198-96d1-77b6-a8ea-b34cf3ee780a

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f198-b1e7-795b-a64c-75833736fcce
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f198-b1eb-7a0b-8a96-adbb3a576ca5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f198-b1f2-7407-865c-908023874333
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f198-b1f7-7fc2-982a-3bd7d8436a49
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f198-b1fc-7a15-b62c-b362ae4609d6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f198-b202-77db-8fe7-57a370e6bfc1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f198-b207-722d-8a0c-62d25dfbc252
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f198-b20d-77ae-b90e-65b25b9f3b88

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f198-c89a-7a42-a142-dfc0211a18f1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f198-c89d-7260-a109-d5b2fd85f6b0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f198-c8a3-7612-a618-2fd603f3f1a0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f198-c8a9-76e1-b213-ab626c124aed
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f198-c8af-7832-8da4-da9b02f007c7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f198-c8b5-79c2-b9b8-5fb87a13b3e3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f198-c8ba-7439-92fc-916ea88be3f6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f198-c8c0-77ff-a7a6-04280f3c2556

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f198-daad-7267-b213-d236111b8a74
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f198-dab1-71bc-9c22-d72e5ad7cc89
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f198-dab8-7c15-b281-879d379afe87
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f198-dabe-7803-9602-b3c166e90a31
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f198-dac4-76f5-aab4-4855634889fa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f198-dac9-7a89-b34f-cd5fc74731a4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f198-dacf-71e6-ad53-3d8dabdd96bc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f198-dad6-7b10-bd1e-e98076dc3eae

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f198-f541-78a9-a926-5a358fecbaa2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f198-f544-7ed8-8371-6b2b7627029d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f198-f54b-7fb3-9f49-84a785f0353a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f198-f550-73d4-88c7-789273f1663d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f198-f554-7a4a-a255-ab0c83539dce
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f198-f55a-704f-b53a-44e45b3802e9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f198-f560-771e-8999-3eabd9c497d4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f198-f567-7e2a-abe1-dbde3471d2f0

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f199-05cb-7317-a55f-0e0dfe3cb2a9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f199-05cf-77f2-aaaf-f55606584485
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f199-05d6-7888-8a09-ef64a356e1b4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f199-05dc-7916-bee7-0f8e758120f1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f199-05e2-78db-bdfc-7481d2cdd164
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f199-05e9-735b-81c2-5719a78f0dff
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f199-05ee-736a-a04d-6f7c39fa147b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f199-05f4-791c-b7bd-a19b0d26b77e

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f199-2020-7d96-a26c-368aa42412f8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f199-2023-7769-a5d1-3f3733cd522e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f199-202a-721c-abbf-4a2e68327c52
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f199-202f-7c12-b21e-83b0a5c64698
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f199-2035-7439-a17b-36727646cf49
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f199-203b-7b24-aeec-f96ccd257e8c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f199-2040-79b9-be7c-3b7b59fb1b21
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f199-2045-7c32-91b4-3b1864cddc64

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f199-2d31-7fb1-b6df-60fe7246d095
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f199-2d35-7b08-959c-06d60cf2df3e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f199-2d3c-73e9-9a27-156786f69dff
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f199-2d40-775e-a588-1c39ea3c7de9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f199-2d46-7c71-8981-5d40481c6de5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f199-2d4d-707a-afd3-a720a5b9b84d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f199-2d53-7aa4-86f7-76eafffc9408
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f199-2d59-74c8-a9d9-8d41a4d5a646

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f199-41ee-7a28-908e-1d91d8b836b2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f199-41f3-78a3-976a-9676fa8d12c1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f199-41f9-7427-bc4b-2d93c8b74f32
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f199-41ff-7615-a748-d3f8d36b5e4a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f199-4206-7572-b3f1-96d149113504
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f199-420b-7429-b658-2fccaa334d5c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f199-4210-7ee4-bf1a-bbf75bac037c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f199-4215-7086-9d6b-62213949a6f8

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f199-543b-77c3-95d9-60f98657acc2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f199-543f-785f-8687-472a3b64a6c7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f199-5446-7bcb-ab84-d30d4b30e13a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f199-544b-7f73-af78-9db7498a5589
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f199-5450-7c94-99fd-c96a7730744a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f199-5458-77f0-884a-a15dbddb2884
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f199-545e-7169-b2e6-050a6b9eb098
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f199-5463-7924-af1d-949ab44ea1b9

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f199-658c-7564-8d3e-54b3e5235837
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f199-6590-7a8a-9476-261442b6d63b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f199-6597-7543-9e3f-6c5416fcaa6b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f199-659f-7092-a090-d7e1bfc2424a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f199-65a5-748a-83e0-2536d8faa098
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f199-65ab-70d8-bc17-7917dc75135e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f199-65b1-7ae7-9417-bc2cc5e0dc14
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f199-65b6-7b78-baaa-a2654dde7c46

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f199-81ae-7151-99b3-283ffac13fdd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f199-81b2-730b-8d02-1919ddb6d875
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f199-81b9-7f13-8935-575d23e5fbd3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f199-81bd-7d4a-a4bb-d477d531c07a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f199-81c3-7e18-ae18-110a35891a19
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f199-81c9-7699-adf7-5bfc1cecbc87
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f199-81cf-7e91-9a06-3936418b23a0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f199-81d5-7d36-8299-a42cb6ff759e

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f199-a5e9-7897-bbd2-fdac20afe685
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f199-a5ec-7eea-8ee5-526dd4e4436a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f199-a5f2-7e67-8ed0-ea616fe3e493
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f199-a5f8-75d1-b043-5b4a1ae619e2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f199-a5fd-7276-a02e-47126f6a3f5a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f199-a603-72ea-b277-9f7d9f7a25fd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f199-a609-7e77-a88d-5fbee7421759
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f199-a60f-7b04-9721-7ccd22e78234

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f199-b64f-77ed-8f6e-3b8511503e68
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f199-b655-7d2d-92a0-e6ef3aba91de
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f199-b65a-71b6-9fe0-3aee8fbeb13a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f199-b65f-732a-b535-d10f4b362c86
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f199-b666-7207-9a68-96e358554e6d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f199-b66b-7559-bbc3-09f80b4ade26
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f199-b671-7a5e-ba23-8634c9d7708c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f199-b676-7220-813f-0bdce9f4a613

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f199-d439-7388-8107-08eb739e9cd5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f199-d43d-7b4a-ad6f-3a8868bb9a83
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f199-d443-7012-ac9e-bff494342235
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f199-d449-7300-b151-5ecd9ebb637f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f199-d450-7fbd-b966-4c18ef0fe48c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f199-d457-70c4-bc8d-bb1b7fcfbae3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f199-d45c-7f7e-89ad-bccbd92991cf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f199-d461-7d37-b52e-ab8f260d5659

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f199-f5c0-7eab-b167-e9b1a2bbb656
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f199-f5c4-7b4a-b7da-efe32264004e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f199-f5ca-7c63-8771-ffa72e1e81e9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f199-f5cf-7f26-9682-efe96d2c57d0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f199-f5d4-7f74-9a92-e336910d22cf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f199-f5da-7eda-afa9-d103bbd877f2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f199-f5df-7332-a2e4-2b5463bc6236
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f199-f5e5-79c2-8057-6332ecb665ca

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19a-0b40-7d40-abb5-23c0094118f4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19a-0b46-7301-b71a-dbcd5ce70891
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19a-0b4a-746f-bed1-4371f3903df0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19a-0b4f-7507-86b4-3e81ff30ee1f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19a-0b56-7394-9e8f-c5e81d3df31f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19a-0b5b-7398-abce-6e226112178c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19a-0b60-7d6c-9e77-b238c6c57c8c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19a-0b66-785a-8107-02d0a507df96

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19a-1f1a-771a-9979-559f1956769d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19a-1f1c-75b2-849e-2d67ebe9d6d0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19a-1f23-7a05-bd78-30a5e8d00f0e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19a-1f2a-77cb-8b56-26b165a00da3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19a-1f30-712c-bba7-c3182c7d94ee
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19a-1f35-7b8a-90f3-fd84653773a8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19a-1f3a-7a04-b1d0-eb1e022c26ec
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19a-1f41-7f8a-b4a2-48283658835c

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19a-2942-7818-8661-5f9f6f9c96e1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19a-2945-7693-a9f9-c5b531914958
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19a-294d-7bd8-a1a9-906165bf18df
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19a-2952-7048-b5b9-0436abff23a0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19a-2957-7670-9a0e-9fcbb9ddd356
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19a-295d-74ea-9bb9-a7ce663406fb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19a-2962-7978-8ac7-480938455c39
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19a-2968-707c-a21f-39ecefdc42fc

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19a-469c-7400-a076-d199a78c3d1b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19a-469f-7eed-8fd1-ac515e7e6fdb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19a-46a5-77ea-8e99-bdf25d340370
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19a-46aa-7134-acd6-36d39972f709
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19a-46b0-7f11-98ea-ac0b428bba2f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19a-46b6-7688-9cd8-38115f3843e4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19a-46bc-73a4-a278-f9d63ce75c80
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19a-46c1-7005-87b1-d7f3e6947239

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19a-57a1-79e9-9621-d0ad74e315eb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19a-57a5-7677-8189-dc0dc62de2a8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19a-57ad-77f7-9769-fa5e7b25bafe
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19a-57b2-785b-a366-cd0fc7cb96c2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19a-57b8-751a-a192-00b76d1888e3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19a-57bc-767f-9af0-68613cb47fd7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19a-57c3-7808-a433-a23ed72d0f5f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19a-57cb-7af9-b02a-df0a95126cc9

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19a-6c42-75f8-b2f0-18df5cf50c77
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19a-6c46-78e0-b515-ea5402c4e8c2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19a-6c4d-7174-8d5a-f918d013be74
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19a-6c52-7f40-a17d-935d06540740
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19a-6c58-7afd-b5e8-53fa7cc26a3d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19a-6c5d-7ef4-873c-3d152adde5d3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19a-6c62-7930-a6d1-295d294834c5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19a-6c68-7ab4-8ff0-9d3500506137

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19a-804f-747f-be8a-eddea34cc2e8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19a-8053-76bb-82f9-9f417e76b0ec
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19a-8059-7ed6-ad90-0eba6c68059f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19a-805f-753e-acb8-7bf12c1ec327
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19a-8065-7f73-8909-c2793e84be94
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19a-806b-71b7-b026-5d1317014496
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19a-806f-7147-a9a7-c425840ad221
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19a-8078-76e2-9172-69e8f24f883b

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19a-95f2-7b50-b303-211b9f63c4a7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19a-95f6-734e-b957-4f7fb0498194
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19a-95fe-722c-bfd8-380df16ee462
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19a-9603-789d-bfd0-3fb988966c32
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19a-960a-7735-a25a-8f1e5ffdc9d4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19a-960e-7eb0-af4b-42946e0a7197
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19a-9615-7f69-8a4e-816adc38bbcd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19a-961a-777c-baa4-7f5ecedf4534

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19a-a6c6-73fa-93d5-9082e39bf792
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19a-a6ca-73b6-b7b5-eedf1c93a180
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19a-a6cf-7174-90dc-f6ce943892f7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19a-a6d4-79a2-add2-6bd09080ad6d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19a-a6db-7cd4-b86d-80be317d4b86
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19a-a6e2-7991-93f1-a59d20502d5e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19a-a6e7-71b3-bdb8-52c8f9455550
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19a-a6ed-71a1-a3fc-c77cd1ecdc67

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19a-bc2a-781d-89bf-eb4ccbfa9359
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19a-bc2d-7036-a182-3b3654972401
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19a-bc34-7241-bd2e-4ad5ca6c495c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19a-bc3c-77d3-be96-17850cf65b64
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19a-bc42-7f01-9fae-363e476ca6eb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19a-bc48-7280-a4f4-03c92c952e90
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19a-bc4e-7de5-ab61-075ef2d37f6b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19a-bc54-77b5-9280-a4ab0dc4bb41

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19a-cee2-7907-a539-3098d94d15d4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19a-cee5-7c1a-a8b5-66e7d77d168c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19a-ceec-7cac-8e75-f67fdeab8379
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19a-cef2-7232-af9e-7d57381ee5a2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19a-cef7-7816-b1fc-30a1b2bb86fb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19a-cefc-7493-8f50-314c7c1242d0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19a-cf02-7c81-b734-efcb806d3697
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19a-cf08-7c73-abd1-552d75f9fe3f

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19a-eced-7f5e-999d-eaf51871573e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19a-ecf1-7d46-8a64-6db7be3b588b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19a-ecf8-7b31-a362-3439cd19126d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19a-ecfe-7233-92f5-121e519c647e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19a-ed04-7dff-badb-c5f12339e97c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19a-ed09-7e45-94b9-5f1323f9be16
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19a-ed0e-7d1f-9db2-a2412c78b6dc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19a-ed13-7585-a498-9d2d75b59184

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19b-0bfd-7e37-b8cc-27e108079e34
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19b-0c01-7954-85c3-cefe1dbcada6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19b-0c0a-7461-996e-db0f73b587d7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19b-0c0f-7fb1-9b02-4d37fc33ff25
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19b-0c15-7677-9759-dcfd7e078b90
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19b-0c1c-7160-94ac-558eb16b2bdf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19b-0c21-7db6-9cdc-e33293f900d6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19b-0c29-7252-81ef-45733848cffd

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19b-2469-728c-b782-65cc16cabe4e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19b-246c-7e5e-898a-49d2b5e00d31
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19b-2474-745a-a91f-c186406e41c3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19b-247a-7b11-a309-6aa2da225022
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19b-2480-7424-836a-1211cd8030ae
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19b-2486-7835-ad3a-074a01fe2eaf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19b-248b-7c21-904e-bbd61e96a3ae
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19b-2492-740b-8485-5ded21ba304d

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19b-3bd5-7794-89a4-b03882ee8196
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19b-3bd7-7d1b-9f6e-b320ab4d3940
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19b-3bdd-7d87-bd4d-edeb550d7cde
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19b-3be9-71b5-8ead-8accd6e05b2b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19b-3bee-7c20-8a9e-cb865f54bfcf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19b-3bf3-76d3-8f1e-cf309dbd64ab
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19b-3bfa-7c1a-9195-a2e7f1c5c43f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19b-3c00-7f81-b149-d8022a945470

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19b-5ff7-7bc7-adaa-a41a4cc2a4c2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19b-5ffa-7ef0-af79-53587e2e0250
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19b-6001-71ea-9c72-70c4337a2b87
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19b-6006-7f81-b605-9e701fedfa30
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19b-600d-73a8-8a0f-175b404821dc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19b-6013-79fc-82da-19e120c8693c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19b-6019-7610-ba3b-0cab739ad268
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19b-601d-718c-96a4-ae7349e18fd4

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19b-808d-77ee-ad53-300ed06df380
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19b-8090-7a20-bace-ae2908422930
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19b-8096-7646-9a54-e0ef0042ab8a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19b-809b-7baf-ab24-9ec44ed16b83
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19b-80a1-7bf3-8194-ae0af6c07564
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19b-80a8-7aa9-9801-68c7d5ad69bf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19b-80ad-7539-b4ae-209e81fa339a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19b-80b2-7842-93b7-5f99277c2e5c

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19b-88ad-7138-afbc-fcc0a0a31189
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19b-88b0-73ff-905c-9874193575fa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19b-88b7-7c37-89ad-2c6990f69737
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19b-88bd-7748-8a1c-f4775ede026f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19b-88c4-7827-8561-cac8ad98a70f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19b-88cb-7c5b-a167-0f12743fa4dd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19b-88d1-79c0-8f46-c54ba8e731cd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19b-88d9-7e08-b073-5e657cb23bd2

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19b-a165-77b9-8ed6-8a565cf97fdf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19b-a168-75f4-98a9-7164533ddc8f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19b-a16f-7c6f-8d98-db9e29189671
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19b-a174-7504-88bd-4c61627daf05
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19b-a179-76c9-96a7-9a9de04a77d0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19b-a180-760f-87a5-29cc476216d5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19b-a186-77de-8720-d9bfad6f2ea9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19b-a18d-7fb1-89c1-bfc43e71dd76

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19b-b7ca-7d7e-8316-5749c19112d5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19b-b7cf-79f0-8c8d-bd774711b6d3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19b-b7d7-7b91-ab41-b3cbf50885ef
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19b-b7da-705e-bb3f-cf3523804350
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19b-b7e0-7b45-b5c0-f9111c0dffe9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19b-b7e6-763c-a0f5-d2493bb783f6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19b-b7eb-71c7-8641-f4a42bf15a9d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19b-b7f2-7df3-8191-86a99fb52c05

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19b-cb1e-7aa5-95fd-6307a529f2f5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19b-cb23-70b6-bab6-3d8ef53b4a4c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19b-cb2b-70a9-9c84-37d2e141b758
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19b-cb31-795b-bb3f-f6a42e204186
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19b-cb37-7514-b7ea-991c8d7096b1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19b-cb3d-7938-a9e5-0801fee818c1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19b-cb42-7c3c-ade9-01a6b79a9c4d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19b-cb49-7add-8da9-eddc5fecd6bd

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19b-efc9-7ba5-bd13-5f7377fb1516
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19b-efcc-7243-a411-0d5e7e95325e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19b-efd1-7691-83c4-9b24b5dddb93
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19b-efd8-7d40-b0a3-42f79d81330b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19b-efdd-799f-897c-02d195e7eee4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19b-efe3-7dc9-a358-f9566a4990d2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19b-efea-7357-88da-a711085e4cd2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19b-eff0-7e57-9a5f-b6c917d84d8b

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19b-fe6b-7697-9bea-55506b2183eb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19b-fe6f-7514-bfc2-da67890c3801
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19b-fe77-7a97-9a05-0d593751b246
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19b-fe7d-7381-8894-7d9a3c842611
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19b-fe82-7cd2-b0dd-85d482485430
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19b-fe88-738a-8613-8d1ae6550733
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19b-fe90-7e31-abe8-e779b0392188
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19b-fe95-7117-b9a4-b3ffb88069d3

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19c-10d0-71ab-9d04-c04f5c7ac663
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19c-10d3-750d-be09-41449cf2b159
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19c-10da-7eaa-89ad-37cd3aac400c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19c-10df-72da-adda-4080765adf96
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19c-10e6-785b-85c3-89c89ba855a8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19c-10ed-77ea-8c67-0df7472c3e22
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19c-10f2-7675-b83e-12ae2866f43d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19c-10f8-7a5c-82a2-72290f4ac87e

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19c-24b9-7037-b7e4-efc4f0faf526
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19c-24bd-78d8-926a-7641c777d074
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19c-24c5-7670-95e6-0be149c2e5cc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19c-24cc-7d96-bf6e-0c3c53b56880
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19c-24d4-7eee-a228-5cdd3b2edcce
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19c-24db-75e0-9030-c7d87ffaf3f8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19c-24e0-72fa-b07c-8c802a79fa2d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19c-24e6-7050-828a-8a24c5488129

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19c-4811-7278-89e1-56a7e126b0c1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19c-4814-7376-9997-5847066f1a9a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19c-481b-7be8-ab45-1bd23936003e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19c-4821-7642-95e8-a9eeba7ea034
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19c-4827-7b41-807c-067bd9ca26f7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19c-482c-7e99-820e-dc9ac7ec407d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19c-4831-7e51-a116-b1128c5d4da8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19c-4836-7618-add8-b5e701c9a05a

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19c-5e93-7b6b-9e74-ac7aed7d9d58
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19c-5e98-7b4f-885f-ea07c92f6dab
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19c-5e9f-79d4-8ca3-491ff61404ee
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19c-5ea2-7e32-a0c9-cc2d5f893103
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19c-5ea7-71f1-936a-199f97054626
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19c-5eae-7fec-af25-a253ae40b50c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19c-5eb4-7308-8a30-d341461f87ee
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19c-5ebb-77af-948c-741c8ad41a8c

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19c-75fc-75e6-8a68-309a17b9fcaf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19c-75ff-75cf-bbae-dcc369402cda
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19c-7606-7486-a327-78b2fb3e7116
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19c-760b-73d5-8cd1-1a4cb5bbc925
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19c-7611-7e43-9215-dd3f6bcf16a2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19c-7617-74e5-b423-d4212322e088
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19c-761c-7bc2-bde3-3c292196a262
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19c-7621-7a84-a86a-60ad7e67bdd9

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19c-88f7-7a0d-a4b3-c3d12d720f75
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19c-88fd-778c-b983-fff14c80513e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19c-8901-7938-baab-42d0a3567a51
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19c-8906-7abb-94a1-1752380a8ace
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19c-890c-7a90-af7d-2f50ddd2f939
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19c-8914-7d28-9f4e-72d39d29be95
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19c-8918-7cf6-8050-07c55a48c5be
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19c-891e-77e7-a397-42c2bb881c34

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19c-9ec6-70df-8484-cf55fe3c9789
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19c-9ecc-71f1-bb7f-3e3297f6f635
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19c-9ed3-71fa-abfd-4512c8691897
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19c-9ed6-7c03-be1a-8d0e068ba4e4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19c-9edc-781b-99eb-a223bf53880e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19c-9ee2-7e0e-9dea-69221868123c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19c-9ee7-71fd-90e8-db561028eb92
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19c-9eee-7ab0-b1c1-9b0854cd947d

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19c-b731-797e-bc95-bc42b1910d12
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19c-b734-77d1-a84f-c7d48c95a7f0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19c-b73b-7505-a5bc-8885c7677ce0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19c-b741-71f4-8ad4-e0b3580a1ea6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19c-b747-786d-bf27-0af50a021e5e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19c-b74d-7b7d-8cff-d6a9675bec46
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19c-b752-7bd1-9912-0ade0a53b2c7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19c-b757-7f8c-ab7a-b94d782c2467

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19c-cd09-755c-b081-63502aeaa72b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19c-cd0c-7664-8c74-9881be053514
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19c-cd13-767f-af80-7a01dcf867de
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19c-cd19-752a-a81b-7045260f4f1e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19c-cd20-786c-8fbb-40390d74afec
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19c-cd25-7219-a7a2-6b03a95bc64a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19c-cd2d-77f3-9c8c-aaf7d7946a7c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19c-cd31-7add-834c-32957dbe6c81

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19c-e9d2-78f6-8049-d5529e6ce144
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19c-e9d7-7ac0-bf5a-399c124d9534
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19c-e9dc-734a-a0c2-76ada70c2569
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19c-e9e2-767b-b66f-59344dbb8e4c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19c-e9e8-7344-837f-f0b85f0ea7bc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19c-e9ed-72e3-b97c-d493a3e3f229
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19c-e9f3-773a-997a-ffd07d90cfcc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19c-e9fa-7e11-8ea6-65d595a8859d

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19c-f6e1-723a-af49-69b261182601
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19c-f6e4-7a7a-810c-52a813d7bf7a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19c-f6ec-7083-88cb-91b47fd7e025
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19c-f6f2-7aa1-b79f-bf428067998b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19c-f6f7-7569-830a-8ea66887b66b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19c-f6fd-7d78-83cc-a39d674009d6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19c-f703-7d7a-b222-06d2b94d6147
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19c-f708-7ee0-a63e-aefb7844f7cd

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19d-0949-7259-9b4c-0f1bf271cdc0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19d-094f-7575-b410-211a1c4923e1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19d-0953-7fb4-ae98-76b28d6b8dc4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19d-0959-7a0c-8510-89634480a6e4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19d-095f-71ce-a334-63d8db70b2fb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19d-0965-7b1d-b6b6-0b1a2652273d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19d-096b-7203-9be0-fd020ab5b27d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19d-0971-7ea8-945c-c756ff2745c1

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19d-2218-7398-ac9d-5b6a0dfa298b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19d-221d-7edc-a401-36a03da0e412
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19d-2222-7c2f-b7eb-b3f90185c91e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19d-2226-7399-bd45-4588cc58a22b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19d-222e-70cd-8b6a-5fbdb065034f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19d-2233-7a16-97c5-7f60d64f9bb2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19d-2239-707c-8a71-b65564e89927
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19d-223e-70ce-b932-e7bae2e811ae

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19d-490a-7715-8693-6766f23df8e7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19d-490f-7820-8bf4-26520dd67cb2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19d-4917-784a-9781-a177fad28cc4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19d-491c-7de9-b17f-cb40a52da72f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19d-4921-72b9-be64-6363f82c948f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19d-4927-7318-9de6-65c60c0128bc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19d-492d-7127-88c4-f130f455dd6a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19d-4933-7bce-8223-7eb97f2ac91f

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19d-5f92-70bd-9b5f-d9a2b471b204
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19d-5f95-7cea-ae50-90d2d590a162
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19d-5f9b-7bb5-bd7e-cb50d50c5fab
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19d-5fa1-72ff-aa69-bdef0b7e7421
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19d-5fa7-7014-98bf-0ed44aa01271
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19d-5fab-7f63-8aaf-18ed25be74a0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19d-5fb3-78c9-a18f-c209d6d518fe
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19d-5fb9-76d9-a3c1-709366d109db

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19d-7268-77a6-bad0-2be5dcd24788
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19d-726c-7414-a99a-b9705d689fbd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19d-7274-7d93-a39c-bbb535c94a08
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19d-727a-7e41-9ee5-6437a837c2db
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19d-7280-7d98-8f0a-7370b53b804d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19d-7286-7616-a398-23bfbee637ab
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19d-728c-78f8-b76f-d331ae03ecfb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19d-7291-7656-bfb4-9ff62bd047c0

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19d-8dde-79b3-b766-443e97bbd27f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19d-8de4-7a34-bde1-fbf4720fa2ea
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19d-8de8-702e-8990-b876ac7d54ca
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19d-8ded-7538-8dfb-07f94d3d1dec
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19d-8df3-73b7-b45a-a86c88cfc388
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19d-8df8-756d-b0b1-fbad9effb2e7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19d-8dfd-7c32-94d2-730015a056c5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19d-8e04-75a9-8fa3-c43f632f45dd

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19d-9b11-750a-8a77-f23cd18d5bbb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19d-9b14-78e0-8ff7-7481c6c2a303
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19d-9b1a-76db-a8ef-4a2656b6b3e4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19d-9b21-7595-a9c8-b56ff3ed4207
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19d-9b27-705c-a369-b9a445d2d901
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19d-9b2c-79c1-a4b5-9ff11dcf2f3b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19d-9b32-79d5-8d08-e74b463787ed
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19d-9b38-7d8f-8e72-c6fea694f7f5

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19d-b7ae-7905-975d-434ac426a922
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19d-b7b2-77f2-bd6d-689f52e3f0f7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19d-b7b8-78c9-bcd9-28325f990682
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19d-b7bd-7478-b9d4-bbf81ef07f66
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19d-b7c3-78ed-b979-dd7a1e3b9bd9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19d-b7ca-77fa-9be0-b968fb08a8f5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19d-b7d0-7d3d-9db1-27f372e1e6eb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19d-b7d5-7c67-aa66-68406b989fcd

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19d-c8e1-71ec-aa22-2b372d5eaa91
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19d-c8e7-7144-9525-def0c236f8fe
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19d-c8ec-7406-841a-07428eb719a5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19d-c8ef-712e-9e1b-1c154ce820c2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19d-c8f5-7ce7-8ba6-f7d4f2f2f262
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19d-c8fd-76b6-b919-46a8cc5ba7a3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19d-c903-7d58-bda2-cd20efa81180
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19d-c909-74e3-9de9-e4897ba1ed98

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19d-d973-7eb0-8d0b-3ee25281636a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19d-d978-731c-9522-37df5d432ecd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19d-d97f-7aad-8838-817cba975794
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19d-d984-7740-a266-f226acf0f025
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19d-d98a-77f2-8d7c-171000ec596f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19d-d990-7ca3-a121-9d5ded73ebbb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19d-d996-7be7-bf62-384b1b6b0d2b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19d-d99c-7178-b3d6-c9b15ac1358c

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19d-ee7f-70e9-bd24-b3e6439c42af
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19d-ee84-7981-be54-d620f2371990
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19d-ee8c-7c20-82d9-13b5265d567d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19d-ee90-7903-9444-720fa493e6c7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19d-ee96-78cc-94ed-7f5a718f5793
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19d-ee9c-7212-b09a-90c50f9734a0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19d-eea1-7166-862a-e6474ef3327b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19d-eea8-7804-b996-383e1c623952

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19e-130c-7b8e-823e-1fe8a1dc7ee5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19e-1312-7191-9823-837c879b55ce
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19e-1315-759a-981d-e32f0703ca37
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19e-131b-7610-8bd4-b37bb0964272
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19e-1323-7a0b-953e-47cfa059e617
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19e-1328-71bb-b9a7-8aa3aefa12e7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19e-132c-7e5d-aef3-2635e14ae3c9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19e-1331-7bf1-b9cf-377ad35a3784

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19e-37ad-7e69-9a91-2c778f3bb8f9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19e-37af-7726-80ea-e8bb853bed12
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19e-37b6-77be-8d74-a9147cb4aef5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19e-37bb-7e92-b818-661d9421d1fe
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19e-37c1-7ec2-a946-5cd249380bd5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19e-37c8-7c62-aec2-0aee80ee7390
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19e-37cd-7c37-a19b-4abba3b89022
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19e-37d3-787c-996b-fdfcf2961b46

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19e-4b09-7ab3-ab96-c29719aace48
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19e-4b0d-7552-895a-46584602d963
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19e-4b14-7fb8-84a3-53f4c6941c59
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19e-4b1b-73b4-98ac-a42dc0924fe5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19e-4b20-7751-9856-6dc85d229418
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19e-4b25-7e1b-962e-3fff3f2ebce6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19e-4b2c-783e-bf47-1dc3c6bbc9ba
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19e-4b32-7eed-b4e5-15a0818c7521

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19e-5d7d-7389-b6ac-5f91c352d954
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19e-5d80-7597-9a7b-c4c9efa30532
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19e-5d87-77cc-97fa-bc73b2dfd427
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19e-5d8d-70a8-9d7d-221916097c3a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19e-5d92-7b06-aba5-351ad730c610
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19e-5d97-71d1-a3ca-80826a193611
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19e-5d9d-7554-8dcc-4adc8e0a8095
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19e-5da4-7cea-8823-7918b77da9f6

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19e-77eb-7e1c-9bc7-a0ee6f0a895e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19e-77ee-71f9-ab6f-0333774fd0d1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19e-77f5-700f-ba90-0d4127a53252
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19e-77fb-7ac9-9934-99ea7c22e35c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19e-7801-7a62-8ff8-67f21a9162fa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19e-7806-7225-b184-b592f5509b6d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19e-780b-795b-9d38-e7b7d00f806b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19e-7812-7817-a687-204517eaad9c

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19e-898c-78d4-87d5-a3001774d503
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19e-8990-7ec6-add6-b2b48a19f7c2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19e-8997-71da-b769-6f0b93746485
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19e-89a4-74b0-af2e-b6bc8df06957
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19e-89ab-7356-ae90-465c426aaffc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19e-89b0-712f-87f2-5e1295a8dcea
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19e-89b7-70b4-be49-4aaf38a8d63a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19e-89bc-741a-99b2-fe5eaa49c1f7

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19e-9a45-74f2-92f5-d84eecfa6819
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19e-9a49-7629-bd94-7f95ec9be985
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19e-9a50-7d3b-be62-d2f84d3f80d2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19e-9a58-7d20-bb40-b297d943b09c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19e-9a5e-73bc-848b-6883b45a3459
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19e-9a63-75d9-bcd5-da1e82a8e76d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19e-9a6a-776f-883f-f73c581a08cf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19e-9a6e-777b-91a3-ce359fe9a54c

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19e-bd76-7257-94e1-38691152e9d5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19e-bd7a-739a-a79e-48ef34b208af
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19e-bd85-700d-a528-d48e1e8a232b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19e-bd88-7600-851d-74929692e5f4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19e-bd8e-7e4f-b89c-86d09eb7302f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19e-bd96-7488-ab90-df40e4058f86
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19e-bd9b-7bf5-86e5-2e5020be4e24
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19e-bda0-7bd1-a823-35641e8f8e1c

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19e-cbbf-7e66-8c6f-8e651f58862b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19e-cbc2-7d2b-afae-28c4fa0e8619
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19e-cbca-75c0-93fb-39de2f193dc3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19e-cbd0-7e3d-8eaa-804fa757ed34
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19e-cbd6-7c61-9aa7-608ed276ee01
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19e-cbdc-7384-a5bf-c881e460a45e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19e-cbe1-7546-a51e-b29efadc92f7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19e-cbe9-7444-96e9-8037a0e15cf6

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19e-e34d-7f1b-89e8-1ba1bed3fd3b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19e-e350-7683-99a4-d47e0457bb56
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19e-e358-7e02-9d36-c254a6f99ce1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19e-e35e-74bd-b8e3-81bc9da5ef43
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19e-e364-74cf-bcb4-7f4c3d30cfc0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19e-e369-7dba-8dd8-8147559e74a7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19e-e370-7fa6-9a1e-a2c4e60d6f20
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19e-e376-7e3b-99c5-47236584d4de

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19e-f824-715c-a979-6da3e34ee8e5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19e-f828-7340-baa3-6e737542804f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19e-f82e-7522-8f82-56f9c1f86f8c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19e-f836-720c-834e-ac9ff3e9d2df
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19e-f83c-728c-a03e-f0240c0212a1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19e-f841-7044-9370-a4c8167238b0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19e-f846-7d20-bf22-aa2dd451495c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19e-f84c-7d86-ba19-4680ad551737

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19f-0ac2-7c2e-9a75-c26537ce94b1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19f-0ac6-7d40-ad72-14a7220bf543
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19f-0acc-7341-b5a3-d1c596985afb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19f-0ad2-73b3-b093-56423e70d7f8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19f-0ad9-7c00-8c87-31b09c8e772b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19f-0adf-7c08-b20d-7adb507f0d99
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19f-0ae5-7c33-a555-a2c7754bc684
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19f-0aea-7d7a-a317-2cc526b0f7f1

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19f-1d41-7b76-9e51-9a90e173df8c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19f-1d45-7b78-a558-755760788b7a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19f-1d4c-7393-aebc-ca163ffd0ccf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19f-1d52-7e04-93cb-def0c36e6d93
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19f-1d59-745c-ab9c-53493cc22d5e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19f-1d5d-7bd4-af70-a894e1667c0c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19f-1d63-7750-b1a3-7a38dfb286db
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19f-1d68-77ca-bf16-41dbfa1d1d28

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19f-3443-707b-9ba9-7a39561467ee
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19f-3446-7773-a09a-99a42daeb0cb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19f-344c-7798-bd58-1e6e1ad408bd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19f-3452-76a8-810c-fe23ace44ec1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19f-3458-71b4-91e7-fb13e4fc2b82
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19f-345f-7493-9225-866e5ff6088c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19f-3465-716d-95c2-d713a7c14a89
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19f-346a-7bbc-b3c7-96db69ee21f9

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19f-4a0d-754f-8f5c-dd5d35b59df1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19f-4a10-7d9b-97fb-88e67c83093b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19f-4a14-7597-aca8-6035cd9bc5a8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19f-4a1b-7b9e-bed5-ab1720da4e74
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19f-4a20-7c46-882a-4aa0c53df970
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19f-4a27-73fa-89fa-0cf141ae9164
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19f-4a2f-735f-8a32-b13b966fd6a0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19f-4a33-7c80-9e89-aa32e79411ad

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19f-6aa9-761d-8e53-1bdea825125d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19f-6aad-7144-ace0-f6d8a8bf7611
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19f-6ab4-74ad-8217-d19ed89de4bb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19f-6ab9-7c4f-acad-0262bb2d59a8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19f-6abe-7be6-b87d-ad62236e0117
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19f-6ac5-7534-ad96-c09e102943dd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19f-6aca-7609-a181-a571c338bc02
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19f-6ad1-7fdc-8404-62eadf47c1a0

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19f-7fdd-75a7-9f7b-ebd676026e12
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19f-7fe2-7781-b507-6b7d893ce0b5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19f-7fe9-78f9-8a9c-7253581f09e1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19f-7fee-79b8-84bd-3c327091e687
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19f-7ff3-799b-9d35-7fcf42998039
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19f-7ffa-7916-b782-0aeadde5448d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19f-8000-7fcd-926e-b4fb67c99936
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19f-8005-7cee-a8ef-bbce1c2a2230

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19f-99aa-7619-8eee-758a7796f24d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19f-99ae-7aad-aae2-f1513cc2a5c8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19f-99b3-7c08-b8ee-d49eaeeb3949
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19f-99b9-7e8b-9d0d-7f59663ef04a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19f-99bf-72fc-8e88-61f1e646d20d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19f-99c5-7473-969b-179b2d92e5ff
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19f-99cb-7ae4-a70b-94dd4109bfac
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19f-99d1-7f29-b2ae-44b8003cf2e9

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19f-b1ec-7018-84e2-8fc195ff9534
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19f-b1f0-72eb-9be1-197f1a6f7820
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19f-b1f5-7a8d-abae-26a930f5dbdd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19f-b1fa-7ad1-9c24-fe988d8011eb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19f-b200-791c-8813-f34f4bfa071e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19f-b206-7374-a581-324eee4de20c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19f-b20b-7e1b-909c-cb4e28510870
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19f-b212-753b-8633-3b187473bf3c

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19f-c55a-7c3f-9f3c-23aea84858ad
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19f-c55d-74ba-bebd-c4fe8a655dbd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19f-c563-7b44-bbb3-91ebe665cad5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19f-c56a-7925-9945-64d7aff1952c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19f-c56f-7966-9382-cdc2ed29fe5e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19f-c576-7a10-868c-47dcf9ed8c80
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19f-c57b-7b33-b960-b38cce0e6baa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19f-c580-7f5c-a233-d41955c16572

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19f-d6a5-707a-99f2-0ab36c6e0930
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19f-d6a9-72c6-bdfa-ccbef81e6276
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19f-d6af-7044-bd29-6a9f0d3527b5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19f-d6b6-7537-8455-911493c399ee
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19f-d6bb-7628-8ee6-ce181e99a647
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19f-d6c1-739b-8f46-8eef732ed6a1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19f-d6c6-78bf-a87e-cb3cbc91c588
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19f-d6ce-734e-9495-c9a516cf74f2

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19f-e8cf-78cc-8329-ad417f84f07b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19f-e8d2-7c52-bad1-c9b498a46cfb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19f-e8d9-72ad-8724-75adfa13e3bf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19f-e8e0-79a5-81c5-58c834cbc8a9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19f-e8e5-7f93-9c0c-d1997df3e9a7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19f-e8eb-760e-b1f9-f0559a97b2c8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19f-e8f1-71cf-999c-b41157f2a5dc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19f-e8f8-7ccc-b338-21f1ab16d94d

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19f-fc77-7b87-b79a-b48f5355eaf1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19f-fc7b-7731-86db-71af0864187d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19f-fc84-7695-a801-09ae8ce7cddc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19f-fc88-7cfb-a48e-72e0ab758c39
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19f-fc8e-73a6-9e9b-a198d4e8a5e5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19f-fc94-7f15-8f43-5748feea9d5e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19f-fc9a-75d1-af42-03008714d07d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f19f-fc9f-7ef8-9f68-038374061225

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a0-104a-7b3f-b82a-9d2c2c38073b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a0-104d-7706-a4b5-cd0612f966b5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a0-1055-7159-9032-c63029597c75
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a0-105d-7430-b614-9ef666a588f3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a0-1063-7465-b782-37c81e3830f3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a0-1069-72a1-83b1-6de42a925ed8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a0-1070-75ae-87ab-1388ef3a6ffd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a0-1076-7d17-ac72-47a392e89926

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a0-2c84-7bdd-9568-6233cd2e1e1b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a0-2c87-7321-95cf-5e0df3e339fb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a0-2c8d-7381-99da-6a795702aafe
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a0-2c94-727a-865d-c8d6e6ee72c0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a0-2c9b-785e-bcfa-c62c75cf861a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a0-2c9f-7b12-8a46-e748f309b7bb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a0-2ca4-76be-a1f3-4196d9e734fb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a0-2caa-7196-93c1-d443358231eb

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a0-381a-7151-8ddc-a88c03f8e90a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a0-381e-7ed0-9336-31df22486234
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a0-3825-78c8-8101-c32d2488429a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a0-382b-73a3-948d-4ab1346b3548
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a0-382f-79a7-bd55-b945b64f2f3f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a0-3835-70bb-ae2c-0763b0648093
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a0-383a-757e-871b-2a2112f2cbdc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a0-3840-7c34-8433-bf8590f95e5c

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a0-4956-71ab-a014-4ce10e11175a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a0-4959-7e93-9ba1-ae20707e3a11
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a0-495e-7802-a41d-ffa7da515cf1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a0-4966-72e2-8fcf-eb3fbf401f5e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a0-496c-7b81-ac13-e5e7df2a5d0a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a0-4972-7516-9e92-531b9ce538b1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a0-4977-7fde-b8b8-f10859291b2b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a0-497d-77e1-b5c8-1804be437cf8

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a0-61bf-71ab-80d2-13c99e1a5983
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a0-61c3-7045-a114-be724cd47b82
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a0-61ca-73c4-8f32-a77db2a71bec
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a0-61ce-7e9f-9a57-b851d95f82c6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a0-61d4-705d-99d7-b45cb3738f1b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a0-61d9-7c77-a778-f148deebfcb3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a0-61de-7754-b7db-6369fd3dda82
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a0-61e4-7ebe-a973-16cc8c9a255b

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a0-7934-73c1-9585-e8b64f2e8dc4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a0-7937-7049-a8ab-b49828792833
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a0-793c-760f-a2c6-4a867cefb3cb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a0-7943-75e9-9397-e08943bb0332
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a0-7948-7de8-8dc5-492dc24bfabd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a0-7950-7761-997a-0725e7d3ce52
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a0-7954-792b-8ab7-3ba9809b9f12
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a0-795a-7038-b45d-01ad0e6c6acc

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a0-913a-79cd-900f-3b2d384cce4a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a0-913e-7e6e-9ea9-002a13249eb4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a0-9144-72d9-b994-3ff9cbeb2807
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a0-9149-72c9-b038-96d3ef742e04
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a0-914e-7642-ad4f-54706270b6b9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a0-9152-75d2-b8ba-2f52b43f49c9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a0-9159-7be8-88a7-5ecb95dd8353
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a0-915e-7848-a1dd-fda3ae77d675

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a0-a980-7047-908d-b01fc7ab53b2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a0-a986-7d10-a414-3ad9f2342788
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a0-a98b-7617-88ea-ce9c193b40b8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a0-a98e-7823-b27b-68a9d27d803d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a0-a994-70c6-8a59-38c2128106e0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a0-a99c-7534-bbf9-81fea4323d81
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a0-a9a1-7c09-a2cc-31cbcd065660
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a0-a9a8-7248-b2ca-efc9a8716793

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a0-c2b1-7c09-a2c8-b67d6c617016
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a0-c2b5-7c91-9753-84f2ef757909
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a0-c2bb-77fc-b2cc-4c37b83c3312
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a0-c2c0-73b9-95db-72c50caa56fb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a0-c2c6-7c25-8ee1-92581c01635e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a0-c2cb-7dff-8877-d575edb9d818
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a0-c2d2-7931-87db-69371606c8c5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a0-c2d9-718c-80cf-2106f73b94d0

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a0-d873-70ae-9c9e-b3b25b56efbb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a0-d876-7032-a920-35dd949cd799
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a0-d87f-723c-88b7-82af326beba1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a0-d884-7a0d-814d-8e167bf0948f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a0-d88c-76d8-bf7d-44e135728d5c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a0-d893-7506-8a6c-de2242682e34
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a0-d899-7e2f-93c3-2a75ff4af7dd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a0-d8a0-7754-956e-f1e13324e6b3

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a0-ee82-7d46-994d-b4d29ba109cf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a0-ee86-7be7-87e9-08f0656997e3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a0-ee8e-7560-b951-77ec739a9ce4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a0-ee95-7f7d-ba59-aa0c6ba8041e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a0-ee9c-7af7-9dad-72abf4112530
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a0-eea4-7332-bf05-4c45995f0384
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a0-eea8-77a9-93c7-cbc3c3a92703
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a0-eeaf-7019-b3dc-e2c463e75cfa

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a1-0135-7481-b27d-2ea9ea707ee2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a1-0139-7540-b3c8-364098182247
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a1-0140-73a9-8088-e70208ecca64
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a1-0146-72a2-b6e4-25d6865cae51
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a1-014c-7224-bc0e-dfbb5109c0a4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a1-0152-71b0-8a1a-f4f3d4b0b479
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a1-0157-7b34-bb2a-84591185228e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a1-015d-707a-9764-088f4d845fa0

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a1-1522-75ab-9da9-9f2028ddc86f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a1-1525-71ae-9ecd-049fccb662f0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a1-152c-7361-aa08-2e466cfa7083
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a1-1532-7076-9f64-63d307c136b0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a1-1539-7532-8639-ef7c5ae4cf19
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a1-153e-79e0-8e0a-e7eb64cd3dbe
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a1-1545-712f-805a-70537937dbcd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a1-154a-700e-834a-2877b96041ad

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a1-2e78-71a2-bb47-32858a98ef01
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a1-2e7e-7fa8-b3db-a5f213eaddd2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a1-2e83-7f16-9226-72db0459a775
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a1-2e87-7aa6-b402-3a042c5c0e8f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a1-2e8d-7918-b56b-935738a94137
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a1-2e92-73a7-8247-b21345b84f1c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a1-2e9a-75b3-a86d-156464ff3ed0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a1-2ea0-7ebc-a619-77cb71ef44e6

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a1-4818-7795-b2b0-f44391f40469
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a1-481c-7287-80b5-ac77b051bef0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a1-4823-73e2-916e-41b76529c8c4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a1-4828-7378-9bb9-94c0783295e5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a1-482f-7af8-85c8-b3dd366c626d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a1-4836-757c-ad3f-2e5dfe591591
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a1-483b-79a2-a879-e205b89e8773
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a1-4840-7a98-baf7-ca35a61459e1

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a1-5f20-7180-8032-26613ab3cb63
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a1-5f24-7d0c-bb4b-5d0940786e5c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a1-5f2b-7e19-a289-11ec93e20741
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a1-5f32-799f-b9ea-bc7379714341
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a1-5f38-752c-b9d0-b067bd62e71d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a1-5f3e-7b34-ba75-78dd364beed2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a1-5f44-7cc0-be78-25609f014dd4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a1-5f4a-7e86-9aef-6c39569416a4

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a1-71d4-7b4f-ac8f-c7d45b40ff6f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a1-71d9-7a77-aedf-09d5c7218577
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a1-71e0-737a-b743-3d354a5d9f2a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a1-71e5-7e56-8890-840d41f1ab0f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a1-71eb-7c03-a8ae-87c31057957a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a1-71f1-7aa6-adae-5993c58e06bd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a1-71f8-730d-aafb-ad9036caf823
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a1-71fc-7011-8055-ba03e90978ff

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a1-878e-7037-9857-40df9b8ef053
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a1-8792-77c5-8b75-15d22d1f75e1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a1-8799-782e-a77e-bac635f25ee4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a1-879f-7dbb-9790-55538d1302e5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a1-87a4-786d-b5b2-5ca6958ba1db
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a1-87ab-784c-848a-2c0bd9fe45fd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a1-87b0-75cf-86c7-70428dd81b2c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a1-87b6-716b-a703-d868712a9222

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a1-9d7a-7c6e-8886-afd00c482b31
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a1-9d7d-751f-aaaf-cc68fe0b07ae
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a1-9d84-72c6-9887-a5bf19786b0e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a1-9d89-7d6f-ac3f-95609f5ef27e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a1-9d94-7c21-8fc7-0938a884a2e8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a1-9d9a-7f4e-87a7-7cdb832979f5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a1-9da0-7a3b-8ea9-7c9478216fc1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a1-9da5-734e-b125-0f12b1f7b200

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a1-afbc-7c9b-9838-d4728ef1eb1c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a1-afbf-724c-8a0a-f5f7a6095461
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a1-afc6-74fa-88d2-d24495e775ad
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a1-afcc-7d3e-898d-f71ddfa53c39
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a1-afd2-72d8-996d-68e92f10c1ef
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a1-afd8-7e06-b8a6-65581d6b695f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a1-afde-75e7-bc94-ea5ba347ccb8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a1-afe5-768b-971e-21c42e7380b9

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a1-d095-7593-bb30-03061858c88a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a1-d098-706d-b10c-e96e575b2717
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a1-d09f-7081-a6c0-59db339538f0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a1-d0a4-7af7-8b0f-23f9234849a2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a1-d0aa-7a08-aa30-5e43690b2734
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a1-d0af-78d5-9e5e-2ff94d4c50b1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a1-d0b6-7646-9814-b803ea946dc8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a1-d0bc-7e76-84c8-b797fbd9dff4

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a1-e4fb-7fbe-9104-6d59873bf198
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a1-e4ff-77eb-bc07-497dc2a03c26
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a1-e50a-73fd-9819-3c90850d6db4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a1-e50e-7ee6-859d-645c71729c11
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a1-e514-726d-aa1c-d0943ad29533
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a1-e519-763e-95e1-8f748bef9d6f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a1-e51f-7a46-b309-d0a22f703be4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a1-e526-7922-a708-9793e7c0ab9f

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a1-fe44-76cd-8375-5df04e20fe25
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a1-fe47-7d0a-b238-35739fa03297
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a1-fe4e-7d30-911c-6278b3d6915d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a1-fe53-773f-aed1-4cc9cffb785f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a1-fe5a-7a12-bb36-66642711522f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a1-fe5f-7ae5-8cc3-92923618b9e5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a1-fe63-72e6-9a9c-c33442467a56
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a1-fe69-7c28-9f8f-e219d58538dd

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a2-08ca-714a-9bdc-d3b29802c1c0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a2-08ce-7228-9a1b-5338d8039400
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a2-08d4-716c-b4df-d8d42cf2175f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a2-08da-727c-89da-7b5f72b7c7eb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a2-08e0-7e8d-8d8c-bece0703c3a4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a2-08e5-7057-8b6d-fd3b7e969504
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a2-08eb-75a5-9e74-4c1f53fa1f15
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a2-08f1-7973-bfbf-ef819b957535

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a2-1c84-7aaa-a2d3-2a42fdc8f211
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a2-1c8a-72bd-b554-921f7a1f5b61
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a2-1c8f-7c55-aeb0-bb6134371d05
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a2-1c95-740b-be73-a7977c47b8cb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a2-1c9b-7bf3-8352-3aad94316de6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a2-1ca1-7e71-bd48-835e0af3451a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a2-1ca7-71bf-a75c-7dfcee3a01f8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a2-1cad-7849-bad4-daf9a47a4cb2

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a2-3bb7-73a7-8bbc-a8c1a8df6fbf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a2-3bba-711d-8f7e-08a0edae7c8a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a2-3bc0-7a56-b508-284df3375e6c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a2-3bc6-786b-be1c-c76bb302ff09
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a2-3bcd-7bb2-a0d7-c26548793009
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a2-3bd3-7e6a-8ef4-cc5fd192e5cd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a2-3bdb-7548-8c6a-eff25e97a5ca
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a2-3be2-7b9b-9655-dcdf05cd9a69

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a2-5b7f-7e9c-ba82-63627d7e9e0b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a2-5b82-7fcd-9835-46814578e73b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a2-5b88-7352-9c2f-c555d13172f8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a2-5b8e-735e-9141-2fc598d72361
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a2-5b94-7601-af23-7cdd6c19644b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a2-5b99-758c-84fd-c2343e80ae0c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a2-5ba0-706f-9865-ec3f1ab429e2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a2-5ba6-7a6a-871f-cc3e999b98ba

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a2-7af7-7149-9d82-6482a63701b9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a2-7afd-7a97-b77d-c61016a406ce
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a2-7b01-704e-9928-9da50311277e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a2-7b07-78a8-abd5-5415a5302d44
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a2-7b0d-772e-ac08-fa1a586dcda3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a2-7b12-7c14-81e5-5bdb0289271e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a2-7b17-7e4b-a9c2-8e876607f142
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a2-7b1e-717b-940a-a2d3d4eab8c6

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a2-889e-7624-a6ef-a0efc7cf35cc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a2-88a4-7c5f-8ba7-4e0f58050103
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a2-88a9-7164-a6c0-fcc7ffbcd551
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a2-88ae-7c9e-aeea-eea9a659dc0e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a2-88b3-7c14-a8d0-a34883aecfcb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a2-88b9-780a-bb2b-221b1a845945
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a2-88bf-75ef-a47d-a34337e552a0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a2-88c6-7f0e-bfee-fa7d0bb7a312

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a2-a495-746c-b7c0-b8c1f9e10fa5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a2-a499-7253-b267-bb641e7d91c8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a2-a49e-79b7-832c-53948163bded
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a2-a4a3-76fa-a05e-cc87132afcbc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a2-a4ab-7abb-b14c-61c879048e8f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a2-a4b0-71ea-b857-b828ce6cf521
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a2-a4b6-711c-b52c-ab9a4653ea9f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a2-a4bc-7db6-b80d-f4df838cdd5e

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a2-bb5a-7bc9-9ef1-f2b79ba229c3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a2-bb5e-7106-8331-d1f25c27ee32
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a2-bb66-7e41-b7dc-ab22c90dcef7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a2-bb6c-7232-a69f-1c0fa64ed0d7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a2-bb73-7cdd-a6bc-906765fb31e9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a2-bb79-78b5-94c4-d35f794acdfd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a2-bb7f-77ea-af7a-3de384b54223
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a2-bb86-7b22-9520-0053226e8d38

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a2-cfbe-7843-9177-8d4f7cee6f87
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a2-cfc2-74e1-9d50-068dda87c148
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a2-cfcb-7d63-946c-2e59aa02c528
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a2-cfd2-7405-9292-5a8c4a1e9351
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a2-cfd8-72b9-bcba-6ff72f1f16ef
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a2-cfdf-71c8-b421-65a04bcb16d2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a2-cfe2-76ac-84c6-dbbc90ade7d4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a2-cfe8-7afc-aca2-c93fe2074ff9

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a2-de75-7aad-8e82-9737f98a2550
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a2-de7c-7d9e-94cb-3590f2c54f08
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a2-de80-75d4-b152-b162a32c9340
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a2-de86-7cf3-9fa1-7b8537a58f56
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a2-de8c-7529-819d-8d0cc6b6aa2f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a2-de92-7dc8-9cb8-b784c6fb8a9f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a2-de96-77cb-955b-2fa3f10f0745
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a2-de9a-7ef9-b7ce-f65c3a58b3a6

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a2-f838-7ad4-85f6-fe0f7bede193
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a2-f83d-7229-8a2b-2e06960c98bb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a2-f841-74d1-9a20-3891e99c2878
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a2-f848-7fad-8166-51568b320c11
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a2-f84c-7c39-a475-523446596b63
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a2-f852-71b4-a6dd-4cfa3336e09c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a2-f857-7562-92ef-06c40386b04d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a2-f85d-72d7-9d81-4f8b085b026d

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a3-070f-7c93-b35d-1cb572f4e6f2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a3-0712-78d9-bf38-41085a0df5e1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a3-0719-781e-9a3a-cf1cfc815492
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a3-0720-7daf-a703-b6b556419eb3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a3-0726-76dd-b165-497cff54d596
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a3-072d-7896-ad1a-d8977205275c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a3-0732-7e8a-83dd-f85c29c3ed3c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a3-0736-7247-85d4-ce489b939fb0

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a3-2118-78be-8230-a0763ac5cbd5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a3-211a-76db-b4f1-4d629a4b9547
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a3-2121-778f-8cb8-ac092bcc1d12
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a3-2128-780d-82e0-50cdf4d91578
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a3-212d-77be-9f53-9ed1e4b7ea3b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a3-2135-7efd-9338-c6fc46be6bb3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a3-213a-72f9-b11b-79e25345178f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a3-2140-7e80-ae0a-28776ab7a1fa

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a3-3556-7600-96b3-6b1ac6f6bbf5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a3-355c-7569-a32e-3691b63e1feb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a3-3562-794d-8714-2267aa6be272
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a3-3567-72d5-aa62-e404d8d83b2e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a3-356e-7ab9-bca8-7a09c5bb4fb7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a3-3574-7349-86fe-b1fdc212d37f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a3-3579-70c8-8259-79cde03409e1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a3-357e-7636-8a90-4fd5ae8dfcef

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a3-4ef2-7665-8f63-dbfd6dfcc15a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a3-4ef6-7417-9ef7-c84e8c9293fd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a3-4efb-74de-b174-6dc93242c6aa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a3-4f01-7339-804c-2bc7d3957368
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a3-4f07-7214-ac63-41eefef63225
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a3-4f0d-759b-a90d-c181b1f4809b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a3-4f12-7c60-988d-19723a9db55e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a3-4f18-7146-9b3b-e9bb1175f28e

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a3-7370-738a-b5ee-5b824ce5f5c7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a3-7374-7224-80bb-3abccef04d9f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a3-737b-7619-bf60-18ec03cf0ce5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a3-7380-787e-a041-19c2d2de8168
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a3-7385-7508-9892-9e69890a4a54
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a3-738a-77a7-a5a2-89cf2886154b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a3-7390-7762-b298-bbd0948c4e23
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a3-7398-7580-bc64-87ad7cb85e40

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a3-824f-7627-b90e-60b1229e6b83
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a3-8254-7430-a6f2-777baa94bc6a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a3-8259-7fd7-a0ca-13cd644d54b1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a3-825f-7026-bc42-a7ad77dd7615
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a3-8265-75c9-923b-3fece9777d14
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a3-826d-7ef7-8f64-7a4d2fdbfaed
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a3-8271-78c0-a868-96ebabced29f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a3-8277-764d-a7cb-6da1024844ee

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a3-97c3-7596-974c-ff8db6ace5d0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a3-97c9-7f23-92f8-38c9c8fc3de0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a3-97cf-7e75-949b-29d432ac967a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a3-97d4-728a-9acc-65aca8fdb36a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a3-97db-739e-8a58-33b4ae38ccb0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a3-97e1-75a3-a74e-18a30f79fa7e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a3-97e5-7a69-9207-7efb746a1905
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a3-97ec-7c7f-8144-3d76d1882f08

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a3-b238-727f-bb53-5a38fc1805db
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a3-b23c-77f5-b99e-4a0ec1b754d6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a3-b242-71c5-96f3-37f71474116e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a3-b248-7258-945b-7b35ab40f012
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a3-b24d-780e-941e-767fdb27faa2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a3-b253-7691-85e2-63654f6246cb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a3-b257-7cca-a86f-ab541fafc33c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a3-b25f-7184-b8b1-542612498168

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a3-cd7f-71ac-aa30-31415a7b987b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a3-cd83-7249-a738-81c1eda7e9ac
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a3-cd8a-79a6-96c2-941bea864613
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a3-cd8f-7cb5-a2da-2341631a18c6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a3-cd94-78e9-a0aa-33f9984aba15
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a3-cd98-74b4-b1cc-e1c036907c63
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a3-cd9f-7b3b-8bf1-ad1e2d07d44e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a3-cda5-7ff7-8c49-defff5dd5cc3

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a3-dcdc-773a-991f-90e36bc05cd5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a3-dcdf-7015-865b-5700d75334f9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a3-dce6-7b47-99a6-49f4e612d11f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a3-dcec-75a1-aeb3-1837f555a0c0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a3-dcf2-7ab7-8a71-1b7049670367
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a3-dcf6-7b92-a24f-33b5ce2a57c0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a3-dcfe-7fc6-b2da-71ba3dd82d93
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a3-dd04-7bbc-b427-1a92ec316f81

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a3-fac8-774d-a23f-a615053f5f66
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a3-face-74dc-8b68-65a59c1943fa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a3-fad1-7ef9-811d-776c19abc5a7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a3-fad7-758b-a660-b0a24b467c6f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a3-fadd-7f7c-9286-347bc4bbf208
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a3-fae2-7660-ad67-44eaa314ec2c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a3-fae8-7522-9e9c-72e37f90af86
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a3-faee-78bb-94c6-ecbe73ab8b5b

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a4-16b6-7c3e-a428-c891349121cf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a4-16bb-777c-9d21-f985d20d50c8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a4-16c0-74bb-8ce6-169b2159b289
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a4-16c5-7273-b7bd-f724bd174533
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a4-16cc-7735-9200-1f1160f18df7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a4-16d1-7917-9fcf-018bd5f07f0f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a4-16d7-7d3e-892b-7b7e965ce5f3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a4-16dd-7438-bb4d-979c803a2f9d

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a4-2ea0-7216-9abb-e1b8992b40f2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a4-2ea3-7734-86c3-97b71c1a4ddb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a4-2eaa-7a37-a5cc-5ec26a4fed74
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a4-2eaf-7b3f-8ed7-8fa9d8911071
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a4-2eb6-7864-9e5d-f7631aae3aa1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a4-2ebb-7f69-a56c-8c051e42d62d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a4-2ec1-702a-8612-c51bf6bb41ac
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a4-2ec8-7b83-8d75-012cd443a565

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a4-4254-7a4a-a682-40db0ea8b4dc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a4-4259-75df-aa0e-e7a74ef11fc2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a4-425e-73ed-ab57-a6e99f738c4e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a4-4267-7bea-a389-ed31a3219b6d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a4-426d-7c18-afd7-289f8ed3b195
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a4-4275-7e16-a5d4-36dfa413207f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a4-427a-7b8a-8e32-e39ead40383c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a4-4281-76df-9dc9-9b26f630fc99

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a4-5db1-7b2a-a36c-474011b5ca84
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a4-5db5-709d-ac63-fa7fccf1a387
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a4-5dbe-7e7b-8055-e5936ec57ee2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a4-5dc4-7aaa-94d0-bd95cb56d106
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a4-5dc8-74ce-95eb-4cd3b7411804
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a4-5dcd-75db-a7ec-758d7b76c546
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a4-5dd2-7b22-97c4-f81811e0ab11
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a4-5dd8-78a4-a419-bc2e9a192abb

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a4-6a8d-7bdd-accd-8d71a89df2b8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a4-6a92-7f6a-ad81-cfe27fffb0ba
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a4-6a99-7a14-9113-206c503a7f15
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a4-6a9f-738a-84b8-7f954caaffa1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a4-6aa4-7142-9bf3-d8746675c587
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a4-6aaa-77f6-85af-67fa3d219edc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a4-6aae-7183-9747-7435a438bf31
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a4-6ab6-78dd-9f19-a855f4c31fe9

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a4-7cb2-7ce7-9225-b4a9149fc767
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a4-7cb6-7bf6-91d3-42ce9d213365
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a4-7cbd-7d26-a212-bc2eb90e357c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a4-7cc3-7b35-8630-4b678214dcd3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a4-7cca-7620-b4f6-157915f2d7cd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a4-7cd1-7d2d-8cdc-eb0305f3978d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a4-7cd4-7316-9da3-f799ee198863
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a4-7cda-750b-a565-79293fd5430a

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a4-9417-79b8-8e58-8b69fce1081e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a4-941d-76ec-ae14-4a64b9c5d3f4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a4-9423-7f35-a0a3-b22008519085
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a4-9426-7b46-802c-8418c5980a28
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a4-942d-7949-8111-98d31e197afd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a4-9434-75ee-9c81-35a7f48a46d5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a4-943a-7127-8c80-804aa1470b9d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a4-943f-7790-a484-b3b7628ade03

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a4-af3f-7271-8609-f5e8d462eb69
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a4-af43-7c2d-83ed-7ecb6ca6666c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a4-af48-7c1a-83a5-d3553c92546b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a4-af50-7281-9012-e81308cab80d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a4-af54-76ec-b4cd-0909ae878300
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a4-af5b-7052-8e39-96ddf1e6e8f7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a4-af61-793d-b07b-548add811911
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a4-af67-7270-9cc8-b35a680313db

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a4-d076-7532-a6a6-0be1cd11bcc1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a4-d07a-783f-95f0-6afcf483f2ac
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a4-d081-796d-a666-96af3a7d8899
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a4-d086-7a12-b43e-2ee0f76b9631
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a4-d08d-7bdc-8237-de5a4480cab4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a4-d091-767f-817d-1d172d1cedaf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a4-d096-7cfe-a8f2-10556aeec3e9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a4-d09c-783f-811c-169ce5bd49da

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a4-db95-7bb4-aab8-098bb96be53e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a4-db98-72bb-9b95-fa52d487c018
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a4-db9f-7e40-bef2-803b2a3e7c47
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a4-dba6-7a85-b8a7-cb7de9d42e6e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a4-dbb3-7a91-b47b-e37ed84af2fe
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a4-dbba-715d-8b92-db59c873191b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a4-dbbe-783b-bb4c-88bcf9d9e7a5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a4-dbc3-77d6-a7e9-f9750c7b665d

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a5-01e5-7278-8ec2-87e5e43674e8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a5-01e9-76d9-aba3-5a5e09445bc5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a5-01f1-7614-8f28-6ccb6d88b26b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a5-01f7-720e-ac27-f78158e249e1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a5-01fd-70dc-88f0-db23de7f8993
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a5-0204-736d-9f9c-709b535d0126
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a5-0209-7cb0-99ec-d21e188351ff
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a5-0210-7de7-af64-b0a07d869190

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a5-1f40-7d4a-bc7c-06cde51317ee
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a5-1f44-7555-980e-c447b118438d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a5-1f4b-7544-b513-a79fb2ba2155
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a5-1f51-7f6e-909d-555e43f74574
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a5-1f55-7025-b5bf-9d7df9b2cb72
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a5-1f5b-7916-b278-38f3c4a7be04
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a5-1f60-7212-ba54-c61ba95724ce
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a5-1f68-79bd-86ef-efb431ce4d77

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a5-43ac-78b8-ba32-6b230caa384f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a5-43b0-779a-8e4c-350486d0fca3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a5-43b6-7cfd-a3ea-9c0e951b14a5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a5-43ba-76d6-96ff-a6ebb28e581b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a5-43c2-769a-a555-364c70953d2d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a5-43c9-7f80-b9b6-5e6fc45e1ae4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a5-43d1-7a76-a5a2-966d4b56df1c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a5-43d4-7e10-bd36-aab34c29619e

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a5-605c-79da-99f3-e9c6660aa670
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a5-6060-7e15-927f-bf9801f2635b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a5-6065-7dc0-b06d-658ee2748d25
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a5-606b-7ebd-937f-0e7b4e1c78bc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a5-6070-7a6a-b743-7144d536f6d0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a5-6078-7041-b2ee-67bd34a090dc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a5-607c-753d-98f1-261b89e996bb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a5-6082-7717-a4b5-407ed57d02ec

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a5-737c-7a07-b1a8-869d8cd562d5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a5-737f-74a1-8855-d6cd7ef12a1a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a5-7386-7048-84ab-4995ad04d72c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a5-738b-7b27-96bf-3a4b3a0b7c0f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a5-7391-7f72-8a6b-05e25a285d1c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a5-7397-7b81-93ab-3d74bafcea79
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a5-739c-7bb6-b506-fe3868e75f62
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a5-73a3-75c2-931f-3915006daf90

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a5-8a71-70c4-98e8-c310b66b853c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a5-8a77-7737-892c-6258b6865804
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a5-8a7b-7737-a315-a40cae1f7a7d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a5-8a80-7006-8f10-36036744f862
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a5-8a86-7567-ad15-095ef16bd5be
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a5-8a8c-7207-915d-fce4fa2c6f8e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a5-8a93-7173-ba3b-82bf1817eb80
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a5-8a97-70ac-a118-4eee3190e264

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a5-a53c-7638-b33b-05928cc3e516
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a5-a540-705b-b784-d1d020ec0c31
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a5-a546-7cc2-8c53-7bef1030b594
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a5-a54c-73c8-a0ec-5fba469c2cd0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a5-a551-79c9-ad0c-043080a7a10e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a5-a558-7e84-aa4a-98028871b8cc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a5-a55d-75c0-b1fb-330adb50b343
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a5-a562-73bf-afff-145e088d0a41

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a5-be2e-78ac-b922-a8d23b6788bf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a5-be31-7599-9467-9cc35e5390e5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a5-be38-7153-a412-1a82e1f65e49
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a5-be3f-7260-81b5-7c91f6f4497c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a5-be43-73d8-a864-284a8f16099a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a5-be49-7277-9d3d-cd841271638a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a5-be4f-70bf-bb6c-cc5a42310f82
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a5-be55-71b5-b776-f0222295ba64

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a5-c9e6-73b9-b3bb-ead230d88112
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a5-c9eb-7288-bb5f-ce85adde1a16
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a5-c9f2-78ce-a28e-c94039962f78
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a5-c9f7-7800-8a92-4ffb324b563a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a5-c9fc-7353-9fde-3d7fdf1270eb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a5-ca02-7155-aff5-5d5c8add9b84
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a5-ca07-7002-88dd-c17f9bab1a38
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a5-ca0d-72d0-aee5-127be1fd3c4f

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a5-da4a-7ba6-9b84-33955612a696
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a5-da4e-751a-88fe-d699b7238db1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a5-da55-7f29-8c88-04cdd2cb4909
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a5-da5b-7e4b-aac9-0d7f126179f9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a5-da60-7bab-b63b-2619b4df0b6c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a5-da67-7625-a757-45b2f9ca53a4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a5-da6c-7c15-a889-a3dab2dff3df
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a5-da72-7a4e-8506-9ea8cd23e18f

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a5-ebf4-7135-b902-f038b3232d88
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a5-ebfa-7013-afa4-b48789ecf57e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a5-ebff-7555-80bb-3bed0cecd33a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a5-ec04-71eb-bfed-c370fc655a60
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a5-ec0a-73fc-ad72-7bb3ab90431e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a5-ec10-795b-bc27-c185a8e77b00
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a5-ec15-75f5-ad8f-d0fc0e5d188d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a5-ec1b-74ca-8f26-246511348b1b

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a5-febe-7bd8-8f0c-fb629685a487
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a5-fec1-75f5-9f61-184604464f4d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a5-fec8-7858-87fa-80a1c96eea0f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a5-fecf-76b9-b365-28e85472f98f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a5-fed5-76c0-ae4e-f39cc552f0f9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a5-fedc-71af-a61f-f843ad8c2c20
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a5-fee1-7eb3-b220-b00a3df9d5c1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a5-fee9-7146-92ec-37c86d93e826

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a6-1ae6-7426-8db7-82a687856565
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a6-1aea-7f64-a404-af7f6262ce2f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a6-1af1-7dfd-b57d-730aa286de22
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a6-1af9-78ba-9c2c-6523773dba60
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a6-1afe-7f57-9e89-893187fa68fa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a6-1b05-734a-bd72-8ed225a6d827
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a6-1b0b-7fcf-9d3e-7eac8842df97
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a6-1b12-7977-be1d-92f23f338834

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a6-2ff2-7e10-9523-781d14fe3002
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a6-2ff5-7577-b0d2-690f582d7b1c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a6-2ffd-723d-9c2d-e14301f92919
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a6-3004-7d26-b5b2-04ac312af73c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a6-300a-74b1-be95-ec41f7caa64b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a6-3010-73ee-a8d8-92d627a516c5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a6-3016-71d5-bef7-22a160755a14
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a6-301b-7571-b73c-5292f41ce3ea

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a6-4e9a-7844-947c-a9d7f2b83e21
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a6-4ea0-7da8-ac55-5de0407ffbff
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a6-4ea5-7a5e-99eb-fac931a75150
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a6-4eab-7f3f-b399-dd53ef42f572
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a6-4eb0-71a5-9a4b-730aae49632b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a6-4eb8-7020-8623-20a636770087
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a6-4ebe-75e7-8f34-679b888b1450
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a6-4ec3-7fdf-970f-28143c7631dd

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a6-66d4-727e-bb08-4f28ecebb4d3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a6-66db-7c80-bb39-856b4952d713
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a6-66df-7091-a314-13ab1853a220
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a6-66e6-79d5-89be-2b7847cb58bd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a6-66eb-78dc-adda-360b5e53cb30
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a6-66f1-7e8c-9089-90ac82bba887
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a6-66f6-7c2a-84dc-6a5b355c2fb1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a6-66fc-7942-a0fe-77824d761621

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a6-8cd7-730c-9fd6-17c934d61967
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a6-8ce0-7c34-bb81-3304f3a4845c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a6-8ce3-729b-ba3b-5ab7a63f7e20
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a6-8cea-7a51-8fc7-282fdf133ec7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a6-8cf0-76b4-814b-03ca1a8d16b4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a6-8cf6-7659-ba21-6fd5bbd036d1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a6-8cfc-77da-afdf-cbb4321a586b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a6-8d01-7e33-b56e-d0607fc7fb17

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a6-a582-74dd-a9d5-b8f4f39d816f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a6-a58a-7a0a-937e-7927d2a95995
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a6-a591-72e0-921a-983d9b816973
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a6-a598-776f-92fa-8d6648bb5f5d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a6-a59f-7047-b65c-ce39a729612a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a6-a5a3-78d5-9824-ee2b3da7bf75
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a6-a5a9-7b1e-a956-497288ee5a6f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a6-a5b0-7376-a2c2-fc8a5293cfa3

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a6-b84f-7afd-a005-d85cd6dceb0f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a6-b853-7200-aa28-0ecb2bf6564d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a6-b85a-70e3-9f0d-fbff3f4d3145
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a6-b861-7e24-a208-f883485b6ef4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a6-b864-762c-8668-9ebeabd3d0ec
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a6-b86a-71f2-8ab0-2c8d1c3959bb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a6-b86e-7aab-a3f8-a789c968efb4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a6-b875-7dd7-8bfd-998d8a3bc135

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a6-d64f-75a0-a20a-6315a07b3844
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a6-d657-70ea-b6f0-f0db9fbcc1c1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a6-d65b-7dad-ab6e-ffc55d272f57
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a6-d660-762d-bf26-55f9b4e511aa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a6-d666-7659-bf0d-6e32b41b0811
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a6-d66c-75ff-b9dc-d853102a2b76
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a6-d671-7d86-bc02-894a8af3b62c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a6-d677-7bba-b6df-8cb990eb3953

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a6-e890-718a-addd-bd7f6e0ff5de
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a6-e894-76ab-a052-7e33b55f4f84
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a6-e89a-7d71-af38-42543929cf1d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a6-e8a0-7c4f-bfa4-8e652f74d8f2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a6-e8a7-7b48-948f-8e1f3a6e5185
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a6-e8ad-7288-a9dc-037c3f5b166a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a6-e8b2-72a8-b653-a721093de91e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a6-e8b8-7b5b-86ff-ed5e30cecdd2

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a6-ff92-7910-b4a7-c91300b9801b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a6-ff99-7cd0-8a2f-72d3a910443c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a6-ff9c-7806-b573-affd1931d152
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a6-ffa1-7148-8942-e648c928eabd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a6-ffa8-7a04-9a84-71a5dc3408bb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a6-ffaf-7133-a17d-89b09038c03d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a6-ffb3-71a0-ac5a-d2841b01c67e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a6-ffb8-7f66-8645-c3554edc7996

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a7-1943-70c4-b617-f3722c252714
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a7-1947-7a2c-8031-2cb6f8461b31
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a7-194d-7485-b449-1f35037f4335
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a7-1952-79ed-b856-45a8d79856c5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a7-1958-7e87-8270-0b345945df7d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a7-195f-7926-8326-6fbe805567a3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a7-1964-7dac-a07b-475a13cdfecf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a7-196b-7761-b5f5-1b3314ce10d8

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a7-28d4-762b-a2e0-7471fb4bbcfc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a7-28da-744d-a90d-1e00903e9f97
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a7-28e1-79ec-88ae-67629a7b27f9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a7-28e7-7d1b-aa8f-e556e9b99b3b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a7-28ec-7062-862c-74befd301069
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a7-28f1-711a-92c9-327ca3b3daff
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a7-28f8-7660-a646-7aba2a0e4f17
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a7-28fd-7dc1-b128-0f9912276bf6

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a7-2e8b-7eaf-bb3e-57f1c202d074
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a7-2e8e-742c-848a-0419b21657a8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a7-2e95-76df-9766-119d3c996d27
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a7-2e9b-7d37-bdd6-89b3652ace1b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a7-2ea2-75d8-a5ca-bbec4dd68dd4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a7-2ea9-73a8-a5d3-5dccbbba26b7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a7-2eaf-75a0-b7e7-cf5fc54baea1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a7-2eb4-7cac-b0e4-361d599df746

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a7-40e0-71c5-ac99-e1c2dfe2f30a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a7-40e3-70c8-8c06-54c3b1a16aa7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a7-40eb-7349-b84b-f8442bb14e79
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a7-40f1-7717-90a5-5045383f124a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a7-40f7-7627-a002-e467381ffc7d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a7-40fd-7835-a0ce-9d3d464e3b2d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a7-4103-7076-9916-241e25e53622
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a7-4109-7de0-81b3-fcfe923f9984

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a7-4f9a-7f2f-81d6-2b4aab762d2c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a7-4f9e-7263-9754-5cc65e1cebc8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a7-4fa6-7268-a848-0b1e0c81d03f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a7-4fab-7de4-9358-8be58196f2bc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a7-4fb2-71fc-9b5f-d587f76f97e5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a7-4fb8-7a85-8222-39157021cf9f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a7-4fbe-75b6-aff9-307a9ec83aab
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a7-4fc3-7a20-89b1-90a6d76f55d7

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a7-6612-70dd-9fc2-d079bb28d78e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a7-6616-789a-9b75-ee85bfcafb5d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a7-661b-7822-b955-abb49249d32b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a7-6621-7708-bd28-f663ecb1d218
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a7-6627-771f-9ee9-5c6ae337ff5d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a7-662c-7c8b-b6d3-f4a05fe6ce0d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a7-6632-7a2d-9b81-803ea19dc13e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a7-6638-7020-b200-c473dd78079f

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a7-7aad-7fa8-9316-1446e37378fc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a7-7ab4-71df-a501-0174d073cf80
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a7-7ab9-7c33-b835-700c47192861
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a7-7abe-7ef4-92d5-4f16102f7194
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a7-7ac3-7fde-ae38-501117764487
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a7-7ac9-77a0-a0a6-d39082426429
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a7-7ace-7cf2-a915-26ffa0fc2414
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a7-7ad4-715a-8050-e4c1a22904cf

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a7-9793-7bf4-8a90-900f243d073c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a7-9796-7446-bc9d-c42b118e7bf7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a7-979b-7bf2-a846-cbdcb73b7445
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a7-97a1-71cf-a9fb-713dfbeb82e5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a7-97a7-7afd-a304-76ec3a78ae89
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a7-97ad-7a11-9019-9de77036228b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a7-97b4-7196-beac-de81e92863f6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a7-97b9-757d-9a43-694061c2f86d

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a7-a3ab-759e-a193-a0b6d7323558
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a7-a3af-7d2f-9718-c2c0e480f55b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a7-a3b7-753f-a2b4-4142c29062f8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a7-a3be-7e38-a74c-a759f353e5da
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a7-a3c6-7c97-b9d6-a17aa6e56232
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a7-a3cc-73a6-81ef-c4489ab84199
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a7-a3d0-7310-ba14-5627f6165ee4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a7-a3d5-74f5-8caf-700267ea5a38

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a7-b6e3-78cd-a646-2742254ce8fa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a7-b6eb-7081-af19-fa08a049e406
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a7-b6ef-734d-859e-da954dc6153a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a7-b6f4-7df2-90e9-af4eb1e92c76
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a7-b6f9-7004-ac3b-4b5fb9176cda
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a7-b6fe-7d92-83dd-f4c942b573bc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a7-b704-7216-86b9-c6d9164af521
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a7-b70a-7673-a922-c205712ad8a5

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a7-db00-75de-ab31-d4317451a53c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a7-db05-7c55-8269-d6e05aae67c5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a7-db0d-7b17-99d9-e868918a2620
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a7-db14-7be3-bd8c-9e3b89b315d0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a7-db19-7da8-9133-ed960eebb610
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a7-db20-7d58-b667-be7dab4c929f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a7-db26-72ac-9547-ad74925306b6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a7-db2c-774b-b279-530b0e6b7061

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a7-ed3f-7ea3-985c-541feceb5bf8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a7-ed43-7af7-90c8-462999af91fb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a7-ed49-78bd-b15f-f912eca37fe7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a7-ed51-7255-b172-8903cb7a64d9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a7-ed57-75cd-bc26-0e6cd5fad999
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a7-ed5d-7db0-bfe0-4dd3d7460f22
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a7-ed62-72fa-8f05-bff7ffd45573
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a7-ed68-74af-a413-6abcc2ab5872

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a8-0cc6-73c0-8c30-245e1c365811
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a8-0cce-7bc0-927e-1ce91bd269d6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a8-0cd2-7be5-9b08-8a00bf084192
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a8-0cd7-7ade-9d61-f7a731fd0071
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a8-0cde-7b28-b039-d14920ba9e7b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a8-0ce4-73e7-9fa8-d9333afca301
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a8-0cea-723c-bbe7-b260bd59a6a9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a8-0cef-7dba-9cfc-58a2564c84bd

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a8-1c9e-7b15-8570-a4055d7b68e8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a8-1ca3-7656-a6b1-5457a2af4e5d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a8-1ca9-7e57-8c2f-b392a306ecb7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a8-1cae-72e9-9778-3d42d0b493b8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a8-1cb5-74f1-8b79-28368908016c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a8-1cc2-7624-a66a-3b934889d8fa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a8-1cc6-7f76-b3f8-b750e07b4931
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a8-1ccb-72b0-8829-704dee18ebc4

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a8-3293-7991-8225-a35bbaf76835
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a8-3296-7a4b-a1d9-8d37d91406db
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a8-329d-7f21-8d05-c6dbbc00cfe1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a8-32a6-7044-932a-453934208f2c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a8-32aa-752a-9496-7f46f5843b78
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a8-32af-76ed-b808-8297b2772124
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a8-32b4-752c-8bfa-244126b3b255
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a8-32bc-7609-bec3-aea9ec93198b

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a8-44ff-71df-a67a-dc99d78ab711
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a8-4502-73eb-ac44-12abd20aa0df
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a8-4509-7199-accc-dbeb55326aec
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a8-450f-7427-8188-507e29daa6e2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a8-4515-703f-9110-1f66727d2575
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a8-451b-7a15-9450-2f54a3d880f6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a8-4520-7bc2-ac26-b0ea0bb1c617
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a8-4526-7a15-8177-c387ad6e9dbd

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a8-5d67-773e-84c5-344bd01f8335
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a8-5d6b-7a39-b373-6f28017345b3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a8-5d71-71e0-8573-80ec90bc6c85
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a8-5d77-7b0b-92f6-2a2bbd40a6b4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a8-5d7e-77fe-b3da-28dc30d6ebca
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a8-5d83-7aa1-9639-65da18f4a9c5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a8-5d88-73af-a409-aff3107377d6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a8-5d8f-7e70-aaa2-ba2fcdcfae23

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a8-7fd5-7033-a589-2a0e962066be
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a8-7fdb-79d0-9cdb-a9a759443caf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a8-7fdf-7dff-9e96-67e88605fcb5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a8-7fe4-7ae7-96e3-9bcd5e5c6192
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a8-7fea-7c80-8e8e-33d1e0eae6cc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a8-7ff0-739f-a35d-8881f2f9578d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a8-7ff6-748e-bff0-034738c34b08
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a8-7fff-7b91-a004-6e374e435aa3

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a8-92db-77f8-92dd-c56977597db6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a8-92df-74a9-9ee0-565ead49d3ef
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a8-92e5-773f-b64e-9dea7b813ab5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a8-92ea-7c5f-8b78-577db79c4d04
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a8-92f1-7bbe-b8a5-b6bb96c9acca
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a8-92f6-74fc-a19a-63c1fb3bd66a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a8-92fb-7be4-aa06-775d868de865
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a8-9301-71ab-915f-b0058805c9e2

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a8-a408-7d64-b705-19edc6085580
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a8-a40d-70e7-9d0d-073a562ae102
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a8-a413-7df7-8b6c-7c18cbd56c12
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a8-a41a-771f-9a1b-6265a920d51a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a8-a420-7a9e-b8c3-18e3ba4b537d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a8-a426-71cd-bc81-402d57554acc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a8-a42c-7e09-bf15-22acb22660a6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a8-a434-7883-9d5b-4a156266446e

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a8-bd9e-7c45-8883-3ca530c68283
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a8-bda2-7f78-b53f-44b23f9338d3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a8-bda9-7214-aebc-61f60cc3c5b2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a8-bdaf-7b84-bad5-05f039d796ff
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a8-bdb5-7c13-adc5-e5a8ad3e403f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a8-bdba-72df-9e01-60274fd892ff
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a8-bdc0-7057-9a38-99d411eeaf1f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a8-bdc5-7a6c-bb98-df59a02ddf41

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a8-d218-76e2-8458-2ac8448d2bd3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a8-d21b-72e5-9fb7-5fcc1ed52c0c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a8-d223-711d-8709-3beff5d5c6ac
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a8-d228-7cd4-954a-00da7ad4bf9f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a8-d22f-738c-9695-723059135fdf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a8-d234-7ebd-a0c5-4e918e019d0f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a8-d239-7278-873d-c8720b25b123
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a8-d240-764c-9931-e20ef08d6583

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a8-f6bd-7830-a9a0-460888060971
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a8-f6c0-7bd8-9f1e-703a29ec7ce6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a8-f6c6-786e-b46b-b37cc44b534c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a8-f6cb-7ca8-8212-cf6f9588ca35
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a8-f6d2-7ce9-b2e2-af8a412c1d33
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a8-f6d7-7afb-9687-f8b5300c2b06
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a8-f6dd-734a-9cb3-3fcf7c04205e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a8-f6e2-7d58-9f57-dbddcee49c22

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a9-056b-7b8e-b9a0-f7383bbeaecf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a9-056f-71fb-80c4-4ed6c9b9493c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a9-0575-7f9b-bce6-d471ba2023b6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a9-057c-70a5-a304-b6c0d35be5e5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a9-0582-7872-b244-9f2042b5caea
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a9-058a-7fc3-be56-df8bacf557ef
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a9-058e-7344-a3da-49f18ab5b0b7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a9-0594-7ec8-bfaa-4d7a6c5dc0ce

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a9-1d2f-7cc1-b4fd-9fd6fc838226
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a9-1d33-788a-a146-5d31151aa1ba
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a9-1d3a-7da4-b8f0-92c5c2b9e14e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a9-1d3f-75c0-9822-30fc456235b1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a9-1d45-7cbb-bf90-b006241b414a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a9-1d4a-7a02-94f4-b543503e3272
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a9-1d50-76fa-859c-0366221b02de
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a9-1d56-76a4-aa71-dff74de686f6

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a9-34ea-7a0e-a8e0-99587bb03976
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a9-34ed-7fb1-8565-74e0cbf0c7d1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a9-34f4-70df-93d2-6e29fa3e8cdf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a9-34fa-78db-8210-a3ee3eaa5469
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a9-3501-7f22-b014-20fb4f8ec01c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a9-3507-7b49-abf8-4937c45e453b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a9-350b-7bf5-ac72-edf3a27a3430
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a9-3512-78a4-95b1-c589981e7282

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a9-4f99-7be4-b64c-ff0490ff2934
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a9-4f9e-7321-8a56-180f4b0643ec
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a9-4fa4-74ec-8ea6-f11a34b0d8fc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a9-4faa-76c9-8ded-483446936d34
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a9-4fb0-742a-b3fd-c5a30727b519
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a9-4fb6-761b-a519-9b3cc015ca21
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a9-4fbd-7760-9198-7ee90fb70cd2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a9-4fc2-77eb-b5ee-39683fcd61c2

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a9-60d2-7d0b-b476-c57ca4de01d7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a9-60d7-7b6c-b1c2-9b9961bb43c3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a9-60dc-7674-8fca-8021c76829e8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a9-60e3-7444-80bc-2a0fbde17d60
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a9-60e8-713b-8664-bd11382b590c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a9-60ee-7074-a24f-1cd1bb705755
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a9-60f4-70c5-ae2a-5ace43991ced
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a9-60f9-7b6f-bc67-7c93a48ef9fb

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a9-7808-7ef6-bfbc-cff2b0cdcd54
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a9-780c-7d11-b643-7e02804ed8ad
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a9-7813-7229-8089-58784415ba40
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a9-7818-7b15-b1e4-e2e17c21eb5e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a9-7821-72c3-8a12-5c306c1c7c6e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a9-7824-7c8f-8184-b16369d5fa7d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a9-782b-70cd-8d34-d3abe4c6410c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a9-7830-7dc7-bda3-12b5a6b4c7c5

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a9-8439-7802-8170-3b6c3a92e4fa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a9-843d-7496-a15f-81de2d3dac77
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a9-8444-7268-817d-50aee63c9f45
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a9-844a-72d9-acca-4d9d6c1ddca6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a9-8451-70d3-9133-f56cbfe0bffb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a9-8457-7538-9329-df654c2425c0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a9-845d-7d9c-af0d-985b2d671d69
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a9-8463-719d-8d15-54832a86bdd5

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a9-945d-7799-af7b-20474564dd75
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a9-9461-767e-a8a7-e512fcb80454
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a9-9468-7e02-889e-66d414ec1059
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a9-946e-7f44-ba3f-5ccf855cd662
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a9-9474-7cc6-ada6-6a586eb02a86
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a9-947a-730d-ac2d-0d45c3d755da
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a9-947e-72de-91f1-cafda94b090d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a9-9484-7ab9-9e05-612014e2994f

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a9-aa23-7d7b-9f8f-b193f3653288
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a9-aa26-7bc5-9488-2ba4bc8f1295
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a9-aa2d-79ef-96b8-cc87be54395e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a9-aa35-7c2e-8e2e-2c15d6577a37
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a9-aa3a-7fc2-979c-fd6cddc7111d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a9-aa41-7846-9408-6cc2e01b16b3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a9-aa46-75f6-8f4d-39c8ad95184b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a9-aa4b-799d-852d-5a287cf6e502

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a9-c0f6-7851-9bad-a65249d0fa0b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a9-c0fe-7add-912f-cf6a2fc167a2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a9-c102-77f7-8f9f-897fbe304545
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a9-c107-7535-815e-05a9f6d98ff8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a9-c10c-7d57-a722-7962971d1772
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a9-c111-7d06-bad2-6b5b43dc6408
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a9-c118-71dd-9829-76087abc1e61
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a9-c11e-78b2-af1e-be2251f3200f

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a9-d287-70fe-965a-f20b2e5a8e2e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a9-d28c-7a02-8e38-49843b329917
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a9-d291-7f7e-8fb8-3f5ce2372588
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a9-d297-7379-b75f-19e262786846
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a9-d29d-76d4-a26a-e0ca81b813ed
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a9-d2a3-7a0f-b535-118af05c9496
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a9-d2a9-7c25-8c19-7dafb83e6916
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a9-d2af-7ab8-a18e-6915c2519e33

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a9-e436-7157-8061-8a00f9307c27
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a9-e439-7062-bb58-d4cd2af2ec68
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a9-e43f-7f1a-a46b-09c815c14922
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a9-e445-7f8b-a2c6-18347070fd53
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a9-e44d-739c-af90-47b6753d4f3a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a9-e453-7c53-85c0-fea3d2bdbc84
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a9-e45a-760f-89ea-6858688551bb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1a9-e45f-7dc3-863b-58c62d4fced4

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1aa-01dc-7d60-acbe-5b6738f10ea9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1aa-01e0-7e4f-8eb0-6daa82443fc0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1aa-01e5-7386-922b-2c1eed3ed78d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1aa-01ec-77f9-9e7f-38844030581c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1aa-01f2-79be-9823-b54c72f1b602
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1aa-01f7-7116-a2cd-dea63ce09ac0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1aa-01fc-73c5-88c3-ce34583031f1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1aa-0203-7da3-81ce-eee9baaed8ce

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1aa-1467-7a05-a785-a18511a029b2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1aa-146a-75be-863c-e43dc32566d7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1aa-1471-7549-99cc-f9efb3c47b7a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1aa-1478-714b-b8d5-622ded87b0f0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1aa-147e-7a88-a6d1-931edb962bed
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1aa-1484-7daa-9504-d6154921d94b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1aa-1489-7a20-bbd7-0e55d09e080c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1aa-148f-77e0-a32c-2b18eee17c9e

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1aa-2565-7bf5-9369-50067477c19c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1aa-256b-71b8-99d0-ae8a0218138b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1aa-2570-7af2-8c30-26b207d5d66b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1aa-2575-7fd0-b2d7-75e6b23b27e1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1aa-257c-77e2-aa3b-bab1c265af58
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1aa-2581-7115-b935-b06874d93053
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1aa-2587-7280-9e55-09d327631a4f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1aa-258d-71e5-9557-c53f1ed9ffad

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1aa-406f-757c-b3b8-980d526594f4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1aa-4075-70c3-8a95-92261c7cbc3d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1aa-407b-764a-a3cc-69ca30d3c569
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1aa-407f-7e63-9624-41d885f732ff
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1aa-4085-75f4-96f0-e94279824703
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1aa-408a-78af-9009-86b39b0c93f6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1aa-4090-7d08-89d7-63d4aa243935
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1aa-4096-7ea3-8d00-885b0ff90849

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1aa-55e3-7888-b6d0-73b4ed049815
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1aa-55e6-7b6e-992d-0b9a736dd2ed
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1aa-55ed-7cc0-91d2-7cbe4824668a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1aa-55f3-775e-a689-0552fd21fed8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1aa-55f9-7b74-9685-c50cc0d9ff5e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1aa-55ff-790a-b303-76be9dac77a1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1aa-5605-7281-a7c2-dbdc31472d81
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1aa-560a-7801-94f5-6cfaa04b34cd

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1aa-737e-75dd-a6d2-29be62838aa9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1aa-7384-71e4-8cc8-0f9b2e18d593
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1aa-7389-783b-b8ec-b383e1ad4835
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1aa-738e-7a12-9705-4f57d12236b3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1aa-7394-7306-9046-04b7e94461e1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1aa-739a-75d8-b466-c13aaecaa2f1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1aa-739f-7d84-b048-9a6c758f9ab6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1aa-73a4-7368-8e3f-933b21942e4f

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1aa-8777-7dcf-a836-be00ad508e05
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1aa-877c-7e40-9746-3a5d36df994e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1aa-8783-7fd4-a873-d67790bb12e0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1aa-8788-7a04-80b9-33be1901cc98
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1aa-878e-733f-b06b-cda132a6b8f6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1aa-8793-7718-9534-c88722176187
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1aa-879a-7d81-9e57-2124de71e54e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1aa-879f-76a0-a1e6-19a924f9a44f

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1aa-abca-792f-8e85-656e3a0a5c92
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1aa-abce-7d1c-b868-1a6913a765a0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1aa-abd5-763f-9fdc-da0370859a0a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1aa-abd9-7828-9ff4-6211e264aaa7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1aa-abe0-7d03-bb27-705af0e70005
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1aa-abe6-78e5-b049-064ebb85d7aa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1aa-abeb-7525-9952-70493e4795f3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1aa-abf1-7b87-a43f-207dda2a453b

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1aa-bf09-7a7b-b7e9-2b7dd7c0379c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1aa-bf0c-72cd-9687-105740d5c5b2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1aa-bf14-7201-a1c5-363f06585ecb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1aa-bf19-702b-81cf-726d512a516e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1aa-bf1f-77bb-bd07-bc8dfaad6ed7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1aa-bf25-735f-a53e-5b8f8d0d9ec4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1aa-bf2b-7157-8ceb-28a37e514207
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1aa-bf32-7d9c-bf54-329b0750455a

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1aa-d430-7452-9752-e02fad1b6a61
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1aa-d434-7d39-b7f2-7a2fdd50cd54
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1aa-d43b-78f8-83fa-0d42116944a5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1aa-d441-7654-ae69-c98d5be2eb2b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1aa-d447-723c-b294-d4c9fe71b4d5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1aa-d44e-772d-b254-8755b8fcc4b2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1aa-d455-7d3c-9b05-a339672373e8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1aa-d45c-77b6-abc5-04af6fc2b52c

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1aa-e1c7-7833-bc72-2a6ae0735efe
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1aa-e1cb-7082-bba6-cb701e253c31
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1aa-e1d3-7149-85d0-e7bfa6dd7fce
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1aa-e1d9-75f1-b596-37553d74bf4b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1aa-e1df-717e-bdb2-8ee0169e2db8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1aa-e1e4-7518-8181-6f6876609eba
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1aa-e1eb-7818-8064-c964e5bce3a7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1aa-e1f1-7e5e-99d1-462cd9556942

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1aa-fa66-7a3f-8c29-d7ff95e8e427
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1aa-fa69-7dfe-ae07-9dcb4c432172
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1aa-fa71-705d-97c4-728308925e6d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1aa-fa76-7e87-af07-35b8e771dc88
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1aa-fa7c-7360-a0dd-042522730b37
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1aa-fa80-72aa-9cc8-02da736921ea
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1aa-fa87-73f7-80c5-cf57b93037d3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1aa-fa8d-70d9-830b-d94e6299c2c7

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ab-0e45-753f-afec-7c8b036cfaf1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ab-0e48-78dc-bd59-6a7599bb444c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ab-0e52-790f-b276-864bd3f0ffa4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ab-0e58-73dd-929b-48848897cf30
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ab-0e5e-7d51-89bf-2b7784db93ee
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ab-0e65-789c-8d28-ae5308a95989
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ab-0e6d-7f9d-8177-df4809c49dbd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ab-0e73-7c9a-92de-029fa9c97346

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ab-2ccc-7787-a92f-84f94a606667
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ab-2ccf-774d-b064-979fd6c3307e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ab-2cd5-7357-a00b-7cce7ac1082d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ab-2cda-7b64-a5de-911cdbd311cf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ab-2ce0-7d8f-8961-d91ffff172fa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ab-2ce6-7be0-8b8c-bf050b8402ee
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ab-2cec-7390-b664-05b1e2322613
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ab-2cf2-7c2e-ab48-f7da2f8c54ce

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ab-43e4-7d59-9095-7e39311c869d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ab-43e8-7f6e-84b5-6abfd52045e9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ab-43ef-7773-932f-b26323f0c0a6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ab-43f3-76a3-8cfd-7aec2cad53e6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ab-43f9-79b7-b04b-48c2ce52ff83
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ab-4400-7096-bd1e-dcf3fc92180c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ab-440e-7fda-9cbb-25eb16e9a3f6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ab-4412-79c1-9251-db7aca8cbf6f

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ab-5cc1-790a-b777-b21298c2de81
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ab-5cc4-7261-84a4-7c704ccf709e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ab-5cca-74b9-b850-e5d895a36971
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ab-5cd1-7645-be35-4d47c1c645ab
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ab-5cd7-76e9-b27e-ddfb0b668974
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ab-5cdb-7322-957d-dfa40d9acdce
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ab-5ce0-7619-8b1a-e0a50c158ee0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ab-5ce7-73c5-9c21-2abdc39f5ffe

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ab-69fa-78d8-b9f0-9d6621facb2e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ab-69fd-7577-a6fe-dda2c0758e75
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ab-6a05-7c0f-a81e-629c2c7b430c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ab-6a0a-75f9-a28e-d85db578c3ff
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ab-6a10-73db-92f8-d23697b24d8d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ab-6a15-7251-9106-de37012a1cf3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ab-6a1b-73c6-839e-a1db3da382ad
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ab-6a20-7936-8931-57d70cdad219

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ab-8e40-762d-b4bd-ac9b6256ad5a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ab-8e43-7899-8787-2f666360de81
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ab-8e4a-72f1-aa45-a0cc7d901f69
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ab-8e50-7b8e-a356-8004af485e70
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ab-8e56-7983-b0d0-a998c9671d1f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ab-8e5e-7cd9-a2fe-01d8642940c4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ab-8e62-786d-b796-159cb4b4b7fe
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ab-8e67-74a1-bd70-12b9502427bf

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ab-a005-71c9-8f07-3a4ff2c2a8fd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ab-a008-73ba-8802-74e44ebbe853
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ab-a00f-7613-a268-7d14fedcb30e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ab-a014-7cb0-8373-4bcdb3bd8b30
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ab-a01b-78de-96bd-41edcfd3ac6a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ab-a021-7962-a90f-4c2a949ef53e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ab-a026-7b46-8a86-96a742397e8c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ab-a02d-7faf-8864-cb187828a7a0

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ab-b3ae-78c5-a4ec-f150c695a299
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ab-b3b2-70d3-bfdc-d9532b0865f7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ab-b3b9-72a4-b9fe-f458d0bc5456
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ab-b3bf-7ccb-940e-dc5009b9bf15
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ab-b3c6-7a7f-b85e-26afbd7ee374
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ab-b3cc-7ada-92e3-6d32ae09e4dc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ab-b3d3-7509-848b-39a9a218e54e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ab-b3d7-71fb-be7d-fd305e808231

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ab-c51d-7555-bdff-b39216a6715c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ab-c521-7e83-9786-d6affdec2d7f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ab-c528-793e-b3b8-40d43050e7b2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ab-c52e-7acb-848a-9f6eb811880b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ab-c533-7864-8550-ce28ca16f52d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ab-c539-7d30-9f4c-92ace2fb6f4b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ab-c540-7534-aec3-af71add2f7e3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ab-c546-70fe-ad64-053c16b7cfe3

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ab-d8b9-7b09-a9e4-31728b849ef1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ab-d8be-7b6e-9526-086a5c813c05
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ab-d8c3-7ba8-9053-2f814a67d6d7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ab-d8c8-76fe-8022-b2cecdc1ae4c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ab-d8cf-7949-b5c4-5feeae3179e9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ab-d8d4-7b53-a3a5-6eadb69635fb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ab-d8db-7867-8822-a6842a2ef0cf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ab-d8e2-7184-a94f-88ee7e532ed3

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ab-f7e4-7dea-8450-db8dd9cdc624
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ab-f7e8-78d5-9582-7bb2b903dd51
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ab-f7ed-79b9-8314-7ff327620097
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ab-f7f6-79e5-873f-3b571056f707
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ab-f7fd-72f4-85a2-06ca8d5280c6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ab-f802-75a8-a434-6344addd3be6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ab-f808-7a46-b27c-e90092343509
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ab-f80f-7442-ae86-62bfa442a524

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ac-1040-753e-933f-8bd8229cdc26
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ac-1046-7847-a00d-68693b2a3943
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ac-104b-7f61-8ea3-46a7b6d609a4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ac-1053-7bee-9180-28b7e34112ba
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ac-1057-7e2e-935c-e1f5bcbcbb07
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ac-105e-7796-9cc8-7e20f15a2206
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ac-1063-75ec-a01f-24aa34440672
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ac-1068-7ef4-8299-49fead797dc7

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ac-29eb-7619-bdd1-550571121eeb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ac-29ee-7328-a2ef-86845d07aac7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ac-29f5-7332-9a0d-de1abafeaf34
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ac-29fa-7b3e-87d3-970dbf81b1f3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ac-2a00-7425-817a-d4140a07c4f4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ac-2a08-769a-812a-1492b216096a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ac-2a0c-7a17-9325-fda88b5643d0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ac-2a11-78be-9dff-65593e6e2fa7

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ac-4744-7951-bfa5-9c322ad886dd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ac-4748-7856-a80a-f388ce1082e9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ac-4750-7230-b061-e55d9ac33700
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ac-4756-7337-b2eb-c4282face798
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ac-475d-74f4-b9cc-f997c988be41
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ac-4766-7ccb-83f4-417e8a10e6a0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ac-476b-784c-8963-1987a084acb4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ac-4772-7e09-b383-b76652d85a2e

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ac-5989-7689-908b-a8c91dccca10
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ac-598f-7196-b0f5-4de81bb6802c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ac-5994-7ca1-915f-49dfcbbcc84b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ac-599a-7a9d-b149-20e3745b9ffd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ac-59a0-726e-81bc-7398c7941d6c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ac-59a6-7af7-82eb-236740e07b6e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ac-59ac-7c75-9ff0-0c3bd82d3aaa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ac-59b2-719d-8ff3-d93ea5d20657

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ac-74c8-727d-9f4b-829db881daf4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ac-74cb-7015-be89-5c6b68707e01
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ac-74d2-7819-b07e-cbe8b4d006e1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ac-74d7-7aa3-bc93-914e7fa67cda
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ac-74dc-7b54-a991-a6bea4be3e35
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ac-74e3-714c-80a2-e6760b73c681
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ac-74ea-7193-b356-59812c15ba3f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ac-74f0-7ae0-a306-976c97b2ae04

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ac-8b91-7f8d-900d-2c0824c6e9a6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ac-8b94-71c5-8166-3528dd964ab5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ac-8b99-749b-850b-8ddf61cfa33c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ac-8ba3-7b4f-96d1-03ae1c68ca80
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ac-8ba8-79c3-8217-a2f4ac592352
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ac-8bad-7ff0-9f25-3388a24f8971
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ac-8bb2-78b2-9453-2a2108ec762f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ac-8bb9-726f-ab8c-ce9f575c5ecd

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ac-a8ab-7ab0-b3f2-2c1e7cf04cef
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ac-a8b0-7c8e-ab2e-ea43459bd0e8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ac-a8b5-7750-bd30-318ee3bba34c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ac-a8bc-74a1-bffc-d3c195a9e4a4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ac-a8c1-7ca2-b931-a221ba4c9ab0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ac-a8c7-7f0e-bdb8-4c8c7fba222a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ac-a8cc-796d-ba9a-b42338abf14f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ac-a8d2-7589-a468-30d6c4fbd3b5

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ac-be48-7dc9-bb61-56d1387554fd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ac-be4b-7035-a4bf-a9bf3fcc5cab
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ac-be51-766c-bc88-1aabc79e1f19
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ac-be57-7fe1-96ef-dffbc4864386
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ac-be60-786b-8806-a7b7cd95e112
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ac-be65-799b-b417-53c08fa98dcd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ac-be6a-749c-a704-2f2753fcce10
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ac-be71-7246-b5dc-608e201a5aeb

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ac-d23a-73f5-93e9-a169485aa665
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ac-d23f-7ebb-bb19-de862e9d6dce
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ac-d246-753b-b1a3-4a542d7fdd46
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ac-d24c-779d-90eb-785f3896a1c5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ac-d253-7519-92e5-d91d6f7d04ae
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ac-d259-7b4d-ab65-11756f328299
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ac-d25f-7566-8a9d-237bf60d056f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ac-d267-7970-b692-093035f336a3

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ac-e5ec-7e97-bcce-27fd70cfb041
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ac-e5ef-7128-bf8f-5403b032b8d9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ac-e5f9-7fce-bc53-23707c2ff38c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ac-e5fd-72c3-bd6f-bff3478db1a4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ac-e603-70b8-ae75-7bcca471383f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ac-e608-72b1-9e2d-19f66defd331
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ac-e60e-7026-8044-cb5cdaaf31a2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ac-e614-7f1e-b75d-070987db4921

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ac-f8bb-7675-aa5d-81372b7382be
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ac-f8bf-7dac-a2de-58fa17afdc3a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ac-f8c6-7423-9f27-879dc5dc858b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ac-f8ca-7a11-9e9e-7453b1ea9db8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ac-f8d1-7bdd-a77b-9fd81df45132
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ac-f8d8-7bb6-b0f9-857f09fc8935
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ac-f8dd-7e56-8aa0-c8a5f97409cc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ac-f8e3-7e47-9717-019f02542d74

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ad-18ba-704f-8384-ea89d586adb8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ad-18be-7bd9-ba3e-e3322bb91ef2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ad-18c5-7e79-9785-fc161c548256
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ad-18cb-7a7c-a48e-1122140aee98
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ad-18d1-70c5-885e-de34445914a9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ad-18d7-731b-95f5-703ab7b0cc48
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ad-18dc-785c-9145-92a2d8e135a9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ad-18e4-7cbe-a8e7-ad114a868091

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ad-3316-7ba7-aded-a05ed4226db5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ad-331a-7ec7-a9b8-d606c1c335e4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ad-3321-745c-b7e3-68a3eab51626
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ad-3327-70bf-b0b3-4b08b9b7c227
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ad-332d-707c-8e40-c66f32a40832
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ad-3332-7ff9-9726-d2f82278a82b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ad-333a-7c57-aae8-2d9a97dee196
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ad-3341-7b9c-9daa-52ac5289e11d

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ad-47c3-7905-81ab-2616cc633aaa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ad-47ca-7030-864e-ec44715d6952
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ad-47cf-7afd-be8c-6a7e2c6c02c8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ad-47d5-774f-a6a1-e65588cd311f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ad-47dd-7e52-bbc7-ff084938ad2a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ad-47e3-7310-b4fd-95844f178516
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ad-47e8-7b51-af8d-1cf0e6008a60
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ad-47ee-7873-9c78-da0176314895

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ad-6171-7eb0-9877-6e45fd59f02b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ad-6175-7a40-b25d-7ed04309bd28
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ad-617c-7164-b66f-37a852e0eb34
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ad-6181-7658-90fa-1e3633c7e8f8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ad-6186-7e76-aa0e-cb40182200a9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ad-618c-7a96-8187-375d0734b2c7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ad-6192-7dfd-b0b5-b257822bedce
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ad-6199-7b79-83dd-d1ca5953a9ed

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ad-7cab-7336-9cd5-680aca364344
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ad-7caf-7dbc-8cd2-809c4668ea14
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ad-7cb5-7c75-bd05-07848cd17afa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ad-7cba-79ca-ba01-b7a6ce9527dd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ad-7cc1-739a-b813-6cc4af2f757e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ad-7cc6-7daf-9dd6-68e0162541c9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ad-7ccb-776a-b03a-7034881635c8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ad-7cd0-7a68-9847-34c17387d51a

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ad-942c-74eb-bf34-59a8e2bae135
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ad-9432-7937-a3a6-c26bf05efae7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ad-9438-700e-8c22-348872d7a3d9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ad-943d-7a00-bcc9-8276459d4e72
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ad-9441-77a9-98ca-8c82b4986d71
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ad-9449-729f-9f0f-56409bcee12c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ad-944e-7a0d-bf51-408d96f7e691
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ad-9455-733f-bae1-2e3f54481080

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ad-ab02-7b0a-b967-b9eea19934c6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ad-ab07-7a75-8103-7e86a13a897b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ad-ab0e-7f73-833f-e15550391e44
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ad-ab14-712a-a197-9dfd7181069a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ad-ab1a-720d-ac5d-06e685d5f486
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ad-ab20-71b2-a56f-4ce5771f2c7a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ad-ab26-7580-8ae4-4ffac60c0774
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ad-ab2c-78c6-8c29-907f2ec65547

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ad-ba5d-76c1-bef2-4a039d854948
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ad-ba63-799b-a539-d22c100b4f14
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ad-ba69-7463-969e-a0fd266dc7b7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ad-ba6f-7b37-b630-1ed34739bd74
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ad-ba75-7382-9fe5-5031de09396f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ad-ba7a-738f-9e1d-a4f10d0e3456
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ad-ba7f-7afd-971a-7913a9a61287
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ad-ba84-7d1b-9539-2bb9921d95a7

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ad-cf01-751e-af4e-8c22cf50e766
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ad-cf09-7dc0-b96c-92955e9523df
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ad-cf0f-7feb-acba-218d80fadf8e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ad-cf16-7b2c-8bb3-ac0b04a4c570
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ad-cf1c-7c94-b009-f0645501baf5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ad-cf22-73d1-bfd4-bf6fe82c6de6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ad-cf29-7094-a36f-688eb416d071
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ad-cf30-75c8-bb1c-2b7a3799f60c

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ad-f420-7e60-a044-8201e5b70ed3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ad-f427-76cc-9222-571a90db524c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ad-f42b-768d-a100-191d544173f5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ad-f430-7b64-ab91-0865458eb0dd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ad-f437-76d3-9aae-8826e16192b2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ad-f43d-7bae-9337-aea9585234f7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ad-f443-7dee-80d3-8ad1671dc8a4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ad-f44b-7f86-9d7b-661432bb237c

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ae-0322-713f-9cca-a3ca1c3d01c7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ae-0324-7765-84d4-211effa89d8a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ae-032b-7012-8b08-f3384ee446fe
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ae-0331-75ad-b142-33d021f4fc4d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ae-0338-7d73-8dee-3edd76146989
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ae-033d-7814-96ea-7acb817ec4bc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ae-0343-7a4f-8f87-23387a2e0fe4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ae-034b-701a-a41c-c4826f1cbe80

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ae-1e59-7ca5-b446-baa3a532fdd3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ae-1e5e-718e-9dd0-1ee5d6529007
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ae-1e64-79c5-8a6c-bfaa192e2c94
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ae-1e69-721e-9777-0b711ab68a9f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ae-1e6e-7a8c-a85f-3f5a64d76b30
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ae-1e74-73ac-a01e-7e86a3f2c807
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ae-1e79-7945-932a-2b561556700c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ae-1e80-7c8a-ab2a-52f7ef298125

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ae-2da6-7ba3-8eaf-7a4b191da728
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ae-2da9-7b91-8ae4-ea27f3547f05
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ae-2db0-70ec-94c8-d89afe0d4af6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ae-2db6-7292-a76a-9a31b584cb8d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ae-2dbc-7219-9ad7-f906f01d949d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ae-2dc4-7aa4-b26c-a66aafe0fac2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ae-2dc9-7a7d-b575-cf085c0bc453
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ae-2dce-72ad-88df-f1d88db54cc2

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ae-449c-75e4-a841-670b9a0e308f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ae-449f-79de-80e5-7dd5e8a2db11
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ae-44a5-7f12-8696-b0ee39a72e3e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ae-44ab-73d9-86e0-5301efaa109a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ae-44b2-7705-bd73-2a5c51565cbc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ae-44ba-7df0-94b7-af30db81305f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ae-44be-7fd4-b74e-78c61ce6c348
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ae-44c4-76fd-bb80-8264a0593f48

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ae-5e1e-7d51-9cee-654cfcb9deef
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ae-5e21-77de-b48b-d93889df8667
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ae-5e26-7f70-9e21-9e49111ab25e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ae-5e2e-70b4-ace4-3eba906e5a7d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ae-5e34-737c-8228-56233766af39
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ae-5e39-783e-8c91-94ffd63c468c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ae-5e3f-76dd-9587-1a246d68e4a5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ae-5e45-79ef-9410-398d9e36ed2f

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ae-773a-7867-b457-c6c7efbfa2fd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ae-773e-7fb8-9aad-4bdfa840d3b7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ae-7743-7f52-986b-519d20e53d53
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ae-7748-78b4-8599-f8e1ab5a6592
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ae-774e-7ac5-ab4c-107ed4e947c6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ae-7754-7357-a087-aaaaeef8ecb3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ae-775a-7c0b-a4bf-a326847a6e1c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ae-775f-700d-9c8f-73cb00b9f59f

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ae-8e40-71b6-b4d4-80c1303349d3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ae-8e47-7b7b-914c-2aaf1f44e7ee
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ae-8e4b-755e-9919-f8a23d5697ff
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ae-8e52-76d5-97c2-22de8a60cbd5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ae-8e57-76d5-a89c-5b1837f972c5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ae-8e5d-7f95-89bc-007726a30c8f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ae-8e6a-7e13-84d2-1180e5e8fc5a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ae-8e6f-7af7-837d-e1f12dead532

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ae-a440-7972-bda9-c19f1deaabc3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ae-a445-73dc-8bcb-903b0caed5f2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ae-a44b-728c-8511-d62754f483c7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ae-a451-7fe5-afca-0771aa3b7a42
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ae-a458-7eff-ab9f-46c5dd22ccbe
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ae-a461-7d70-a9bf-691d352e7ece
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ae-a467-78c3-8ce8-5c635e68758a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ae-a46f-751d-b572-5da653136d55

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ae-c328-789e-a233-5baa6081eea0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ae-c32b-7ab5-8063-af0c2d632b61
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ae-c332-78c5-bdd7-8fea1d9932ee
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ae-c337-726a-9677-517e641fe0f9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ae-c33e-7989-84b6-66534f949228
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ae-c343-7bd9-b8de-8e93de7b8170
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ae-c348-726c-a5fd-84a78b1e9ad8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ae-c34e-7e68-9578-0407293b84d9

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ae-d661-73e4-a913-5e0a9d547b8c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ae-d663-7923-bf7e-e61f80cc4b71
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ae-d66b-7bed-9441-024d35111a34
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ae-d670-7594-b75d-44a4cb2aaa5f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ae-d677-7189-9956-952f53680d85
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ae-d67d-7370-a369-b7d99724e893
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ae-d682-76b2-9023-3841db0b171e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ae-d688-76f0-ac1b-8ccae63fd61a

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ae-ef20-7729-8bd2-c9eac36f0ae9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ae-ef24-7e66-9e6d-b395ea7a5913
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ae-ef2a-7538-bec1-769c03d5e01b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ae-ef2f-78bf-9d3e-ab000f4145aa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ae-ef35-78c3-84b4-27324a91ed55
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ae-ef3a-7111-bd45-7b52a17126d5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ae-ef3f-7ed7-8ae5-1faae52395e8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ae-ef45-7be7-b426-175212dad2be

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1af-0625-7046-9b6e-9d88612e1d65
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1af-062b-7013-b3a4-bc28f4a30919
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1af-0631-7c27-b20a-8b1d33a7c314
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1af-0636-7bcc-9563-4514aacd75be
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1af-063b-7bdd-804c-4f70c5e306ba
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1af-0642-7769-991a-a9f8f9144593
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1af-0648-728b-9b86-2bcbff095564
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1af-064f-733d-870f-b011f380144d

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1af-154b-7258-8726-0f43971d2963
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1af-154f-7d5e-9ea4-c338e306472a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1af-1557-7af6-a518-a81852790337
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1af-155c-7640-b379-2099acae6062
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1af-1563-77a4-a8aa-139c75a0f160
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1af-1567-7265-9003-8ce302d52a93
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1af-156e-70c4-a892-058d98048bd3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1af-1573-76e3-a349-9ba8769b5372

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1af-2dd5-7959-9d29-60bd947f55ce
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1af-2dd9-75c1-9628-d96f4a6b0404
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1af-2ddf-7db7-b5ef-22df442f0752
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1af-2de4-74ad-b2dc-aac784169f57
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1af-2dea-7a73-80ce-e5f52536490c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1af-2df2-70b3-ad88-1cb56a9fd8c7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1af-2df7-756b-bff6-0fba5e1f0df7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1af-2dfc-720b-b177-4993200b92e8

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1af-3e66-7275-878b-65a4c603c1f6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1af-3e69-71f5-ac35-8aebc7d04ef5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1af-3e71-7944-8a30-8f54a0fa3d98
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1af-3e77-7560-8259-81a709c2e960
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1af-3e7e-74e3-aefe-9cc56b1f6bdf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1af-3e84-74dd-830a-9464e7d086ff
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1af-3e89-7877-836b-bdc416836d71
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1af-3e8e-7f63-97a0-671a7a8f9fee

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1af-51f3-78c7-a0e6-85b3277bf41a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1af-51f7-707c-8710-39fe17bea7f9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1af-51fe-703b-958c-a1b18d8bdaa9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1af-5204-7ad0-ad09-0c61d1e7dcbd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1af-520a-707a-af88-963f92d8c87c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1af-5210-7aa8-80e5-f345a344fdc4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1af-5216-7f8c-9781-a23984dc7726
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1af-521c-7be9-8df2-f0222a39efcc

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1af-66af-7b75-b232-4e42bd763f25
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1af-66b3-74f7-939a-0e082d6020fc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1af-66ba-7013-96a6-bf6b3e45fb2e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1af-66c0-7a03-985a-9841188c6e74
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1af-66c5-7d5c-9043-9d46a73be003
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1af-66ca-768b-b943-bd93a9e521e9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1af-66d3-7c62-8b81-21018a57a194
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1af-66d9-7a76-85a8-70b152d2bf58

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1af-7966-7add-8ede-d1ce7fa08ca7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1af-7969-74ff-99a6-fec74e6b5678
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1af-7972-715c-be81-184bbb1b01b5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1af-7978-7def-8fff-c2d99f07c76c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1af-797d-7298-85f9-6e8333bf940e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1af-7984-7d05-8e8f-ed7c05c86188
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1af-798a-73f9-a14d-64ffa8fcd51b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1af-7990-78dc-83fa-a69b7e0a40f0

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1af-8b1c-7d28-a732-2bbd207723c0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1af-8b21-725a-b5f8-f5296019cebd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1af-8b27-75d7-b833-6b498ed4f348
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1af-8b2c-794f-8d5d-0b60e7819586
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1af-8b33-799d-96d8-aa3d17dc69ee
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1af-8b39-75cf-9b3e-a6fb41c0cfbf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1af-8b3f-7e59-b6f6-616d438b3652
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1af-8b43-7887-9025-fdac3aff9112

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1af-a90e-7574-a118-f54e1bbd5d37
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1af-a914-74dc-829e-d7d93740ea3a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1af-a91a-774f-8663-ab5255ad91e8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1af-a920-75a4-8f05-057f2ad7ac05
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1af-a926-721f-975c-d0d923e3a64b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1af-a92d-718d-ba35-d30a1aeacc7b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1af-a932-7a06-8465-35b4d121bf11
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1af-a93b-77f9-b778-7ccd4b123bda

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1af-c419-793c-882e-9c8b15eb5e15
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1af-c41e-7046-9577-cbbf6ed1e9af
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1af-c424-7286-81d2-ef670458d08b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1af-c42a-798c-b710-90268c48113f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1af-c431-7b9b-9acf-d297d2dbf02f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1af-c438-7dfc-acb7-51c4d910a796
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1af-c43e-7092-a3c4-af929ef7e8cc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1af-c442-739a-8b9d-768aa51983e2

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1af-dde0-7a5e-ad85-849137f54e19
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1af-dde5-72e7-9395-934120d6a233
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1af-ddeb-74f1-bade-84974e9950e5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1af-ddef-7c43-99b4-2ef3f4eb6558
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1af-ddf6-700e-bd1a-b9855ac5f2aa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1af-ddfc-71fe-b01b-25395b77f558
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1af-de04-7e20-932a-c0d72e850776
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1af-de0a-73fd-bb0b-0ca93b47955b

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1af-f81e-7eb2-b53b-e4afd1025153
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1af-f822-752a-9296-1791c9d91f06
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1af-f828-7138-8f7e-0e6549b7ec2d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1af-f82d-7e9b-a548-9b8f034f7284
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1af-f834-7cc6-a009-994d630bdb79
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1af-f83a-792e-9cda-d5c3d5848a4c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1af-f83f-76bc-addc-81a15a7156b5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1af-f845-7b2b-9b5b-15bb34f27d75

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b0-03b4-7b0c-b9a8-4ae36f9c8af4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b0-03b7-7b5a-b591-9c1e54d554c5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b0-03bf-784f-8cd0-ab87f0d1f6ed
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b0-03c3-78a3-8247-1badf8630570
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b0-03cb-7a27-8883-a130ff8495b2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b0-03d2-7324-82e7-0cb4f9d30cad
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b0-03da-792b-af4d-9afbc396d794
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b0-03de-7a09-b598-2728af67850e

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b0-173b-7ebf-9771-1a044cdcc8ae
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b0-173f-7dd4-8d6c-74b34dc88900
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b0-1749-7516-a31c-704a9930b63d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b0-1750-7e67-8c05-602c118ae784
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b0-1759-7e49-81b0-0df8d8b62289
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b0-175e-7b75-a326-0ae26c879158
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b0-1765-7752-8a1a-edbf6aed93b0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b0-176b-7505-9312-fa1cdfc2514a

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b0-3021-7a99-8312-e420f59076a4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b0-3025-748f-ae68-1defb92cd956
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b0-302e-7525-8cb9-98e83c9cb019
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b0-3033-7f96-bbb5-02117bcf9a2e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b0-303a-79a2-aaae-39974ccffb07
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b0-3040-7871-91e0-bef0e437e908
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b0-3046-730e-835f-afc2caaed6b3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b0-304b-745a-96a3-865ba2291bfb

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b0-4805-7f48-8ba4-22b707cdb28c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b0-4808-7acc-943f-1fc554c891e1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b0-480f-794f-8726-d0602e2d972f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b0-4815-78f7-ab11-837a8f8d4603
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b0-481b-730c-bd71-4ea055d507aa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b0-4822-7f15-86ae-4607314e95a8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b0-4827-7e25-8cb0-7a1af0c740b8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b0-482d-7e95-b122-f8848b6f70eb

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b0-5d96-701d-9eb2-322c80d11e4f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b0-5d9a-7e87-bb1c-45d17b900a0a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b0-5d9f-7fec-bb83-a61782be5b6e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b0-5da6-717c-8120-0a5609341daf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b0-5dad-78cc-a45c-59b5b4475ff3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b0-5db4-799a-843b-4d606f3c62dd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b0-5db8-730c-9e30-823a48936152
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b0-5dbf-74d2-9a82-4949a883a491

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b0-75d2-7c57-9663-b014ee333dde
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b0-75d6-71d4-bf61-4adf638eecca
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b0-75db-70fc-9858-af11cab34700
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b0-75e1-7368-be14-d1a783947093
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b0-75e7-7f74-85b6-0b899c8389b3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b0-75ed-72aa-a6d1-26dc52fae83a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b0-75f3-7ef2-85c9-f042b41988ee
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b0-75f8-7bc1-9b4d-5778d531b206

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b0-896c-7e44-a423-5876add1e71e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b0-896f-778a-a4bf-23f8ee260cc5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b0-8975-7ba5-9dfd-f56d6f0d1988
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b0-897b-7a59-9202-dcef9d26a668
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b0-8981-7074-a6d8-88b994f31aa4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b0-8986-79f9-890d-a9acfcaef451
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b0-898b-7829-bc59-eb23da3b5b31
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b0-8992-7845-b172-6597e9cd7764

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b0-a168-7c4b-9502-8947303f09ff
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b0-a16b-77ba-8fbe-a03a5d6b3f6f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b0-a171-755b-8669-a0951fce998e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b0-a177-7cd8-8046-cba2e7633860
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b0-a17d-745b-8c6b-7f9c78e32ed1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b0-a184-74a9-9ce3-19d8a6a2591f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b0-a18b-74d4-b43d-6e9de2e569c6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b0-a18e-76ec-abc1-510eb291f10c

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b0-b8a3-7be2-83ad-0115b594b14e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b0-b8a6-7989-a7e0-f9da7d4ba2ca
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b0-b8ad-7db0-a755-492cba7eeb80
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b0-b8b3-7234-9c10-1234f6c248e9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b0-b8ba-7e2c-9886-b6f3103eb313
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b0-b8c0-702d-8452-a2e974bcd966
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b0-b8c6-7a6f-85cd-75a60dfcf4a8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b0-b8cc-727b-80f7-d95aa6364b66

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b0-c0f6-79b0-b070-da827cd0d85d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b0-c0fb-707b-8d5d-48fc46a5c87b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b0-c103-79c8-9646-d4d21c67a6d3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b0-c10b-780a-9546-e4fbeb2ab431
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b0-c112-70c9-8d8d-c81928c7b598
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b0-c118-7208-b0ae-363b93e94773
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b0-c11c-7736-860d-b0ad0bb33327
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b0-c123-7e6a-92d1-c0582952b06a

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b0-d403-7093-b3a0-6de69316612f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b0-d408-75fc-91e8-295ed9fb818e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b0-d413-7a17-9da6-a69699a28fa2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b0-d417-7c6d-8f81-a0e657bf0453
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b0-d41d-7b56-83f1-630071959cca
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b0-d423-7be2-8e03-d6ac0062e4eb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b0-d42a-7613-87a6-72de4520c57a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b0-d433-700e-9199-8330ec313367

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b0-ef70-72e2-99ad-00683bd90d09
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b0-ef73-7694-80e3-1a87377c8283
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b0-ef79-7dc0-9e82-a80461ee32aa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b0-ef7e-7fcc-b6be-2836235e0003
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b0-ef85-7db7-8c19-0949e4bd55a2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b0-ef8c-7b07-a06e-9927cd1a6b4f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b0-ef92-7fe9-a26d-7f9f8121063a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b0-ef97-7a34-be60-414f4dce4f3d

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b1-0795-7104-9934-7d6b8f24754d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b1-079a-7046-99f3-54f2bfa4bf15
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b1-07a1-7d96-88c4-3ca9a696c950
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b1-07a6-70e9-8dc2-6e22e71faea5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b1-07ac-7c5c-b8c3-2fd3533569da
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b1-07b3-7b9b-a9a9-f47d6cc8d002
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b1-07b9-743f-a0bd-e9354b5431cb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b1-07bf-70cf-9e85-0024ce15889f

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b1-263b-74ac-8ceb-eeb9a450c7de
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b1-263f-702b-8869-bffd8b84f3cd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b1-2645-7a24-a8f0-1f1d774f1d49
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b1-264a-7956-aab8-0c73addedce3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b1-264e-783a-b8f5-99af2a72a814
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b1-2657-7e9e-bf12-5ab6386774f8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b1-265c-7fb2-b9d0-6c156d701334
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b1-2661-760d-b8c4-9ca677608462

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b1-37dd-783a-b2c2-99f080531e86
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b1-37e1-7795-8d68-4708f312fc5f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b1-37e7-789c-ba36-79c320dc3a19
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b1-37ec-764f-806e-7f2ff9ceea1e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b1-37f2-7897-998e-abd67a9593d2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b1-37f8-76c7-a9bf-ee55a1228bf1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b1-37ff-7116-b147-7b76f8f8815f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b1-3805-70d8-bd0b-f62f5d613f2d

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b1-492a-7276-9df5-9b4c43f4c473
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b1-4930-764b-926e-68006bdab65c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b1-4935-75be-95c5-c1e1a38ddfde
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b1-493b-785e-84a4-c101e27df1a6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b1-4942-7488-8498-42bad96c7ad4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b1-4948-7026-8b93-75f978f335d3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b1-494e-7263-bb0e-7066286cdb30
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b1-4953-7e30-8cab-8268a7108415

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b1-614a-7d2f-bd04-6e9971131263
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b1-614f-73a6-8039-bed60e7b6b80
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b1-6156-73ac-bec0-18dd9ddb10ff
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b1-615b-73be-8754-294d472cb5a4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b1-6162-74cf-ae48-3b98486350c7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b1-616a-76db-b1df-5bd711048ce9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b1-6170-7eb3-8c2c-d5ab61c2ebb3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b1-6175-7f5a-9594-a5918be80c07

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b1-780a-76f4-a9ec-05589aaf04b9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b1-780f-705b-8036-de6f956b5ad8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b1-7814-7508-b05e-bf1240cfbad8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b1-7819-7151-be9e-044e7b767cd3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b1-781e-7705-9cfb-407f62d88b82
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b1-7826-70fb-914d-64e7f31db15a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b1-782c-7dff-badc-054dd9d40fa6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b1-7832-7706-a221-78723f395720

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b1-8dcb-7a15-b4ed-37785a108d76
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b1-8dce-7d8f-af85-e4fbbf89342b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b1-8dd6-721b-af12-190bcf1400be
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b1-8ddc-726d-a053-ee214c63b3a4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b1-8de2-7355-a73a-f0a2bc0d4280
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b1-8de9-743b-8086-2f365e43f789
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b1-8ded-7d98-8fa3-0f3cd3f799b3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b1-8df1-7443-8cb3-d3117ead9c58

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b1-a05c-7fec-9f59-7221852d0abb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b1-a061-766c-887d-043f3f369f6a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b1-a068-7fbe-8bd6-3cba4a7cc7a7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b1-a06e-7afc-86c8-536dbe644d28
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b1-a073-79f4-a69f-de048e2febac
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b1-a079-7308-aa31-15aafaaacea4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b1-a07e-71b5-bc55-dba9626c592e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b1-a08a-7cb1-9db9-d2da7247955c

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b1-b6c7-74f3-bbc2-db7331370700
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b1-b6cb-7586-a8d2-8fc22289413c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b1-b6d0-7925-93c1-8c50b459d4d9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b1-b6d5-710c-a156-91cfc7b1d169
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b1-b6da-710a-97c7-af75feace5ea
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b1-b6e1-7f46-88c7-bf49a3668515
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b1-b6e6-7032-bbce-e8b94f9d4340
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b1-b6eb-70be-b035-26be89cb48df

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b1-cef6-7ea2-b949-fbe53242cd7f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b1-cefa-7d4f-9e5e-12f26bfd5a13
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b1-cf02-7f0b-93f1-aba8c821ed4e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b1-cf08-71e7-94fa-9e059d978843
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b1-cf0e-71eb-9c8c-be4a2dd6e5b5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b1-cf16-7458-943f-74e166352bcc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b1-cf1b-77fa-9c49-e1ed0bed9f5a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b1-cf20-725f-ad5c-253ee14a6975

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b1-dd88-7305-a1fd-4b6fb4d8fc66
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b1-dd8d-716f-82bd-ada117f00c3b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b1-dd93-7191-8f06-ae21e0e46ee2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b1-dd99-745a-ad8a-e8509d42e6c7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b1-dd9e-756b-81cc-9ba5f089b9d4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b1-dda4-7f7f-a670-3691ac618b77
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b1-ddaa-7c84-8cfa-80d8d42ddd75
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b1-ddb0-77a7-b86f-01bfb3cd242f

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b1-f4e3-79ef-b633-2e5427a2080a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b1-f4e8-7fa4-9ed5-c04f34db5bb3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b1-f4ed-70ef-b460-eac0574cb7a3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b1-f4f2-71de-aa96-bd95d6425743
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b1-f4f8-7267-89b5-456d811fa357
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b1-f4fe-7be9-9b01-1d17dd049a79
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b1-f503-7634-af2c-c2cb21604a7a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b1-f509-7bd8-b6f5-40f18729debf

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b2-0341-7435-89e2-abbc5d92ac61
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b2-0346-7bb6-8612-0c4d65f888b7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b2-034d-7618-86aa-9467b1533288
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b2-0353-7df7-a7b3-826acd16d4cb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b2-035a-71bf-b46a-5230a3ae14be
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b2-0360-70cb-adc8-3da90b8ffea2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b2-0365-7a75-9439-bb62876f4d26
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b2-036a-7e5d-9c5f-a57964773362

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b2-187b-77b0-9d8c-ca4c2dd73a4c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b2-1880-754b-90cb-fd15e49fa451
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b2-1886-7a54-aa4f-9c316902db17
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b2-188d-742f-be70-56dd151da997
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b2-1893-7700-80b8-3da06b1bb596
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b2-1899-7006-b7bd-a1353fab52bb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b2-189f-7414-bb8c-5654fc23020f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b2-18a5-71b1-a771-89630ae29722

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b2-2788-7c18-8369-f7c9622629c5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b2-278c-76f1-9af0-cf4c96956dca
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b2-2794-7d8d-80ec-7f48fd5e9fdd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b2-279a-718b-962a-81b9113aa58a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b2-279f-7bc5-b41b-9d1c95eccf78
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b2-27a5-7883-a127-8d1901e9e6e1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b2-27ac-7750-8d08-700f71d6ceae
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b2-27b3-7856-b34b-a35820f74b6d

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b2-3e01-75ac-a6b7-c195491720a2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b2-3e05-7ca3-833b-5bcf867f1b9c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b2-3e0d-72fc-8051-3a9900730976
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b2-3e11-7292-8be7-863c307e8919
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b2-3e16-7557-be98-09d05772dea6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b2-3e1b-7f4f-9d71-97eefe61c4c3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b2-3e20-701a-aba5-cd7c0fd9bd2e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b2-3e26-7b72-8f23-e9f7d58b4327

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b2-4e22-7490-bba5-6f55384babcb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b2-4e25-7fc0-a19b-3ef8298b3b1b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b2-4e2a-7d20-840c-0d7727a0e233
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b2-4e31-7b8a-a157-353543b4fdae
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b2-4e36-7d38-930c-e5b21c14f4b7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b2-4e3e-7bb0-8642-be821bd998d8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b2-4e44-795b-b6fa-e4c55fd14be0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b2-4e49-7fde-b9a5-ccaa760df7e5

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b2-6b2d-7ff3-811b-1cdd0d5deffe
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b2-6b31-7b95-b6de-ddea6c8af7ad
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b2-6b37-77ee-98ab-988875af6c59
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b2-6b3d-7575-b5ff-774dff6fe5c6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b2-6b42-7fe2-86a8-c6fb621797f5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b2-6b47-72bf-8e2d-4e3f57258c99
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b2-6b4d-72cb-a4ae-03d9f777ac67
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b2-6b53-7f05-a1bf-c0025a0e61b6

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b2-80f5-7a27-9a5e-29ad6dfcf05d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b2-80fc-73ad-8e55-365f08f9c577
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b2-8102-73ec-ab72-a07134f38e1f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b2-8107-7318-a304-69a5a5ade42d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b2-810e-7344-938d-c7a08cd152bb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b2-8113-71b5-852e-6144f1cc7fa6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b2-8119-7850-b7ce-ced729d4f2e2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b2-811e-7a55-a333-91807cf69ced

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b2-92d8-76c4-ab16-e658ceb5961e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b2-92dd-77c7-be77-fceaa12676b0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b2-92e1-797d-b301-9833a47253aa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b2-92e7-7fad-bee0-e2c7995a4736
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b2-92ec-7303-af02-f10a8944b3a4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b2-92f3-753a-bf23-b8d249772c73
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b2-92f8-7cae-ad37-581cb3e5f418
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b2-92ff-7498-8f6d-2a6d2acce1b9

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b2-a99b-7683-84a6-6b4d9f9ffc77
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b2-a99e-77fd-a7b4-4d70055143dd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b2-a9a4-77c9-a9b0-0b4b71dfc0d4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b2-a9aa-7457-ab02-31c8b613a754
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b2-a9b0-7bd5-ad44-7eae9875e337
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b2-a9b5-7341-8efd-f07fcc769caf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b2-a9bd-7131-baf5-9e994abde6ef
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b2-a9c3-7cf6-aa52-e8fdfde0d7ba

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b2-c137-7eb6-a37d-55a4c1659a40
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b2-c13c-70f6-83c3-00f2f16a10d6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b2-c141-792c-b41b-93624312204f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b2-c146-7571-a334-cfbee212ea45
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b2-c14c-759d-8eea-70ffedb8e5fc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b2-c152-7c1c-9385-ffec65e93f27
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b2-c157-7425-ad44-8df390c17bbf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b2-c15d-7edb-86d7-794a3cb72b4c

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b2-d599-7abb-b0be-0b4b47a2d1eb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b2-d59d-7e2b-8f70-060b9c205cd2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b2-d5a4-7fc0-a54b-8c92332a6ced
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b2-d5aa-7720-b181-152b47251208
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b2-d5b1-74b3-90a2-aacb44dc3228
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b2-d5b6-71c1-81b4-16d500661941
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b2-d5bb-7a49-8773-e00c69504e1d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b2-d5c2-7ec6-8e41-b908161bedeb

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b2-ebd1-737f-becb-24c2d19a1b74
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b2-ebd4-7544-9342-78d98340783e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b2-ebdb-74cc-95c4-61dc4c39891a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b2-ebe2-7b7e-9a43-45e78311001f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b2-ebe8-7be5-a2fb-6206b4b22c5a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b2-ebf0-7a45-96f5-cfb15a07108f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b2-ebf4-7efd-a8d9-f3b52496ee96
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b2-ebfb-77b0-bc10-5b78c60349be

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b3-09dd-760a-8395-3b022c71369d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b3-09e0-7ce3-b0d4-c37b8f111956
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b3-09e6-7564-9fce-8ee36035866a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b3-09ec-74ea-9d42-81ca03cff2d5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b3-09f2-7392-9b38-7f0614d797f4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b3-09f9-7836-a871-930dd4e3fdbd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b3-09fe-748b-b892-06c4a7f57d71
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b3-0a03-7786-894b-f702ed68f94c

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b3-280e-7da4-ae6d-91afed8d69e3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b3-2812-7d0d-9306-9abc52179bb8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b3-2818-7d56-9fde-6d241269ec83
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b3-281d-7f76-aec0-02ca60e41c45
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b3-2822-7f5e-ab6c-5b6a5b2263ce
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b3-2828-791d-9908-c8216abc213b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b3-282c-776c-94f7-87c3ad22be6c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b3-2833-7264-83a2-172d06c34f94

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b3-4377-7ad1-a6b9-f644c92c98b7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b3-437a-7b97-a550-3bb1d5b3392c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b3-4380-7e29-9bf2-21e5d93aeffb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b3-4385-766c-a785-8b9cb4beaa0d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b3-438b-7501-a7f8-ac3b1065739b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b3-4391-7d4e-85bb-39395d5c5f93
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b3-4396-7d95-b9b5-f24b0e41ad69
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b3-439d-7d50-877e-ba4d717a32ad

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b3-5582-7ca6-be85-4cee95c85117
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b3-5585-7ab7-8a4b-7c43d0ce1835
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b3-558c-79df-86b4-6a7371888e6c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b3-5592-7506-bf5c-8dc8ea5eac7b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b3-5597-7019-83d6-2166de7448f4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b3-559d-7463-99ad-da4d55ccf709
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b3-55a3-73e7-bb35-f558a567ae0b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b3-55a9-7da4-b27c-d9af5b6b1441

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b3-6d58-7637-b740-78c40d280796
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b3-6d5c-7937-adbd-6c5d982ed4c9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b3-6d65-73bc-8fd3-f56f2545568e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b3-6d6a-76cc-958f-877bad157292
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b3-6d70-70a6-a276-05d23cd3da18
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b3-6d76-71b1-8570-d9a851165570
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b3-6d7c-7768-ae65-99ee9597c76d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b3-6d82-7451-a4b5-b7cbfd718279

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b3-7dd2-7d28-8bf1-023606156b9d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b3-7dd5-7975-ab3d-8078346d9bf9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b3-7ddd-728d-95d1-cd8a9b0b5625
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b3-7de3-7cfe-b0b6-e69e9fe64b6c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b3-7de9-7f4a-8ec3-4331c8ed069e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b3-7dee-75cb-8771-e0ee526be318
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b3-7df4-7b15-ba6b-fa1c71b9ced8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b3-7df9-7aff-bd1d-17a04f23e1bf

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b3-97d6-7d59-957a-19d3ca5eb9d4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b3-97d9-79cd-badf-7127137a7858
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b3-97df-7142-b5b5-a39840e08356
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b3-97e5-7e3e-8039-12d085815d78
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b3-97eb-74bd-8003-8b75a968009e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b3-97f1-749b-83fe-ffc102258131
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b3-97f8-7fd0-85a5-42d66668ae49
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b3-97fc-70b9-8c82-352592fa3b92

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b3-aaae-7587-9ba4-c3251ea4cf22
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b3-aab2-77ea-9266-f756c4675b2c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b3-aaba-799b-a7d6-4daefbf8f9d1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b3-aabf-7bdf-81e0-58ac64130caf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b3-aac6-71be-b597-28775d764c93
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b3-aacc-7bb4-9738-0b1b11df97db
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b3-aad0-7fcf-8700-878050838b99
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b3-aad7-7b40-afc2-2838ff43cce6

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b3-c393-744e-aa09-56459d29832e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b3-c397-76aa-b083-9f4e0a1a41ce
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b3-c39e-74d3-a436-c0f9fef22000
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b3-c3a2-7cfd-959e-16a0fcbf767e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b3-c3a7-7326-a993-4e4a03385df9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b3-c3ae-7a85-9227-91dfa2e1fe1c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b3-c3b3-72cb-8f8c-118c66ad241d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b3-c3b9-7825-a007-37757e861ecd

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b3-d7e6-7a99-bca3-0ce08fccbd68
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b3-d7eb-7a28-bf0b-824c58487539
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b3-d7f1-778f-b837-cb8513fd43d1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b3-d7f8-7cfc-9f65-96b73a9f9365
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b3-d7fd-7d5a-9e06-d807ae165a66
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b3-d804-7df1-a102-2c811a04705b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b3-d80a-7a32-aded-8078061e8d6c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b3-d80f-70f2-ac31-1cb402cfe774

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b3-eab9-7a83-be5c-f1eb86a5a4c0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b3-eabc-76fa-8c6c-a943afb5b774
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b3-eac3-78c6-b5d5-d7e9baec28d5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b3-eac9-70eb-ba2e-d5b09a068e35
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b3-eace-74ba-bafa-70a15979f062
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b3-ead4-7306-99d1-0b91d02d21e9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b3-eada-7b3a-af2c-1607893ce573
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b3-eae0-789b-a67c-557665123f8e

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b3-fdca-7e74-a465-77a61e5d337c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b3-fdce-70c4-930d-e9f989e93050
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b3-fdd5-7ffb-827d-bdf23f57a9ac
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b3-fdda-7082-8892-882ccc237366
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b3-fde1-75c1-b3bf-d72eac39f061
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b3-fde7-77c9-b7a0-32a369a72ff9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b3-fdee-795b-b4f1-b3bba1bd69f6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b3-fdf4-7b64-a30b-9ddbeabef981

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b4-1dde-709d-8fd6-d43ebff59b09
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b4-1de2-75d4-a088-ffc98979cc6c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b4-1dea-7a98-b554-a7ce0818ff14
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b4-1def-7e45-b3c0-dad0bdb103fc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b4-1df5-76d0-9c94-f3413c9bc68e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b4-1dfb-742f-87ec-012fd2b70050
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b4-1e02-7a9c-acf7-d575692b93c7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b4-1e08-767d-9281-05d57e40edda

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b4-2ee0-7beb-b925-7e79d8513800
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b4-2ee3-710f-bd0b-d6cec5144698
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b4-2ee9-70e4-9430-b8821018376f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b4-2ef0-71ce-a7dd-80a1c7cc3987
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b4-2ef5-7ddf-91dd-8209cb44f212
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b4-2efb-77d8-86bc-face6e2894c9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b4-2f01-711b-bbcb-ade3667da8c5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b4-2f07-7a05-9298-0a81cda74832

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b4-5088-79f3-a40f-b88092b83a0d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b4-508b-7c35-bd27-025cc4cf47cf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b4-5092-7007-949d-123a87eba3c0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b4-5098-72d8-b990-9985b0a87286
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b4-509d-7294-8d49-307555faf608
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b4-50a3-72a1-bb45-f311e7304568
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b4-50aa-7390-b5dd-32020f2eb455
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b4-50b0-747b-8685-3bf600a88503

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b4-6c39-7d14-9c80-af16c3011f83
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b4-6c3c-7611-8d41-6c135bcd8cdd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b4-6c43-70f5-b865-f0bb3c73ff11
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b4-6c49-7f8c-85dc-354dd2b2fe2c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b4-6c50-7646-a258-655eef16b223
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b4-6c57-7724-a44d-06774040b47b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b4-6c5d-70eb-856d-e48a093dd685
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b4-6c64-78c4-8f2a-470e3588eed6

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b4-7764-7604-a0ff-6972eb55eb97
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b4-7767-7407-951e-75401745ec55
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b4-776e-755c-bd2e-600c1053b1d4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b4-7775-73b7-b706-1661824428ad
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b4-777b-718a-bede-49e4079dcf8a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b4-7780-7c1d-964e-eac446c131a7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b4-7787-7450-9642-07986c40e22d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b4-778e-7c2d-b713-ca4934f30956

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b4-8cec-73da-a14c-1d04a0929d41
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b4-8cef-73fe-9e6a-062dac2e3b4d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b4-8cf6-7d1a-bd4e-d2684adadbce
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b4-8cfd-73cd-99c6-51595c196a5c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b4-8d03-7ab6-8a1e-cea66eb9dbee
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b4-8d09-7205-a7a6-674f3a421ba9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b4-8d0f-79ba-b897-53f5d7c67187
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b4-8d14-72bf-94a3-ffa6d736a24f

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b4-a359-7f28-9d15-77aaaa86d5b8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b4-a35c-7ba8-909e-4947c149977d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b4-a363-7c14-9cbc-10118dbe3d97
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b4-a369-703f-a0dd-1b1c4e51998d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b4-a36e-7215-bc7f-88221de34e94
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b4-a375-762c-87cd-8d47344a69e5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b4-a379-70fd-8b1f-6b29ce9b12da
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b4-a37f-75b5-a96f-79278e56694e

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b4-bffa-7af5-a5d6-cc6d57e39e36
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b4-bffd-70fa-bdd4-46ee456757ac
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b4-c004-7bc6-b689-f1baa8633112
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b4-c009-7336-a362-aebc03cea934
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b4-c00f-7ff6-90e8-3b8202fd8eba
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b4-c015-7cde-a580-e3a2c8f01e0e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b4-c01b-7233-b51f-5a1f087d9fb0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b4-c029-7234-aa06-c71522c4da1f

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b4-e4c0-7dd9-857d-ea15844df91f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b4-e4c5-782a-b7dc-5f15e0244f76
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b4-e4cc-7613-ae1d-7e59136b926f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b4-e4d0-756e-ba4f-e59fac739945
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b4-e4d6-7679-99b4-15017e88b183
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b4-e4dc-776c-8bd1-9c86549fc295
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b4-e4e3-70cd-9f5e-0632c60b7e01
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b4-e4ea-77c9-8c79-9db208792891

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b4-ef63-73cb-a991-0256ffa7d8fc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b4-ef69-7296-98c3-85adecd09d48
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b4-ef6d-750a-adff-3456e85af963
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b4-ef73-70bf-991e-de5cef605627
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b4-ef78-793a-9d3e-1cddf5e9f258
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b4-ef7e-7e61-94e0-281cb1ead6d3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b4-ef83-79fb-a742-0c008ac62235
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b4-ef89-7ee3-840a-bf16cdb248c3

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-07f9-747c-9937-64a90e28e2c4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-07fc-717f-b470-b2cc00f607b3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-0803-7b09-bef8-3c0984b78245
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-0808-7135-9889-2882c00bc72d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-080d-7803-90c3-13bbf7c7a7fd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-0814-7d58-9d35-00b1875cfd06
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-0818-739a-90ed-cff2a3092b6d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-081d-79e0-b0ac-93dd66775017

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-1a02-726a-a06c-6507ae12b326
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-1a06-74d5-9563-6e197ab5baa2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-1a0f-701e-9a4e-77a672a84d37
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-1a14-7685-929c-e9322ca8f011
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-1a1a-7411-a0fc-ddb16bbb2d84
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-1a1f-7ef8-803b-018c31b64119
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-1a23-7952-8c40-b2d742d10a9c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-1a2a-7879-98ba-fb11cbf664bf

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-2b42-7282-bac5-e864d14af31a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-2b45-7348-bec4-9feb52fcc457
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-2b4c-73b9-8908-85ad69a9749c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-2b52-7fa1-9f66-85cf0cf8cba1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-2b56-71bb-8ad4-55b9f55ccdb1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-2b5d-7eb2-9397-741eb5953df2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-2b64-753e-9781-3ddb56bed990
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-2b69-7d15-a9ee-3e9b243f304d

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-431b-7466-911f-16f4220309d6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-4320-7b0c-8565-5037e1802d56
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-4327-78aa-8bfa-f26c5c0933e2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-432d-7ca6-8d01-8d1d59723ef7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-4332-7b35-9e00-4028006cf12a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-4338-7f85-a7bd-e7aa2dbbfec2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-433d-7682-9e8d-8ca1187015dc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-4342-7522-b197-18c82cfd57bc

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-5e82-7daf-9144-55f5b4a80118
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-5e86-7360-90ac-58e91d5daa4d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-5e8c-78b6-bb74-c831e6ab89ad
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-5e93-7dfe-a90c-a5d4ef17e570
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-5e99-70c1-9bce-456d8b03b90d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-5ea0-72a8-b013-d8a209369539
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-5ea6-74ab-ae74-85d256ae69f5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-5ead-7794-bedd-0ac904144ec9

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-6e9e-7cbb-b47a-a1ca48260fa0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-6ea2-7113-9758-700782263113
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-6eaa-749c-a43c-aac559a27cb6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-6eaf-7fa3-8533-51ba4f688278
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-6eb5-78df-8514-9e96990927d9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-6eb9-77b2-8afb-4f7f2a09ebb8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-6ec0-72b4-851d-121ab4fef25d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-6ec6-795b-b9e4-1e21bd9bbd9d

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-8292-7292-acf3-93f7cf133d7c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-8299-70ac-95c2-df4adb9ac9f1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-829d-7365-9ee1-12cebb977baf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-82a2-72ae-9428-b9e8cd88efd4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-82a9-7200-906b-a0d28063e2b8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-82ad-7466-9769-082611332c2d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-82b6-7cf3-9c37-4487fe04270a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-82bc-7e52-940e-4ada71e15341

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-9313-7074-bc87-813f07a32351
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-9317-77cc-9775-2897ba249a47
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-931f-775e-a2f2-1c243edac1f6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-9327-7fc3-b700-00f8f79390d7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-932e-73ee-9105-e7d012a901ca
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-9334-7633-be46-b432952f022d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-933b-7de8-a38b-4b73d19c409e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-9341-7220-827f-1e66e79d5503

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-aeed-72c2-9444-871ed52e6b01
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-aef0-7158-8fca-eff04a325722
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-aef5-7243-b097-3fa1dff4d264
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-aefc-7b39-b81c-5f79ee16d408
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-af02-704f-80f8-019a6c489353
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-af09-799c-b0c7-1f87d138712f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-af0e-7394-a6ba-8adeff5ad236
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-af15-77d1-a7b6-9c734e30728b

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-c743-723a-9498-e8b0e05977b2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-c747-7e7a-b621-7cfd12cfaa48
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-c74e-7c80-900a-0f1e8be5fd6f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-c755-791e-9a79-7d2a6e88170e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-c75a-7542-aa98-11972ef487d5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-c761-7481-b3ea-4f097597ea48
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-c765-70ec-9925-2315cec0f357
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-c76c-7a11-9918-5cc6e0b4c438

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-d8cf-7876-b5a8-0eaa783f0f40
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-d8d4-7a62-8508-c0ec19a33b44
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-d8d9-7ff2-8a7d-1a14d75a339b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-d8de-773e-ad8d-d8488b846d85
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-d8e4-7b5d-a87e-0b6b240f454a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-d8ec-7069-8672-bedfb12333ff
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-d8f1-751e-9ad3-6267f6aa7a25
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-d8f7-760e-93af-762e558d4ea4

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-eeb5-7153-8008-839508e99d35
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-eeba-779f-bf9d-4dd89c26604f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-eec1-7242-902d-611b8de154dd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-eec7-74a6-86ec-16005c57b06f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-eecf-7027-be5f-24bebe4230cb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-eed5-74c6-972e-b1c0fd33283d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-eedb-78ca-b0dd-468ded4afe0d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-eee1-70fa-813d-9568c55ed348

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-fe9c-7f93-811e-00fb998c3a59
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-fea0-7b15-9d95-e279605dab15
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-fea7-71c9-97ff-2fbfbd61294c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-feae-7816-8c4e-64003e505f0c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-feb4-72ef-a412-1d2acff10ec5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-feb9-7db8-ad2f-604876d808f1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-fec0-7770-8d2e-5568624b07cb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b5-fec5-79af-bf20-834d3cfaf76c

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b6-17a8-7501-9add-62d6d7937098
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b6-17aa-7621-bab3-2f4e20da0a63
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b6-17b1-7a68-a7ce-aa4bbda0b4ec
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b6-17b7-7493-8f7f-45381e98d21a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b6-17bc-75bd-a56d-3306ff3cd0b4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b6-17c3-7df6-b066-24c1ad89f4bd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b6-17ca-7a2f-b38f-45f19ce2a22b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b6-17cf-7eb8-8045-b62470980f8b

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b6-2aec-7d33-9ec2-f1b2fd6ba189
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b6-2aef-73fa-a829-81ef04cc613f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b6-2af8-7455-bbfc-b8325ddce790
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b6-2afe-73db-93f8-e88cf567a59a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b6-2b05-7135-a185-c6c9f786dd49
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b6-2b0b-7f4f-b3eb-5219a431adb0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b6-2b10-73bb-8f62-db1f0bd696fc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b6-2b16-792e-a5a5-f950a8c26b6e

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b6-4965-793e-a364-e3264d9c425e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b6-4968-709a-b736-8c946895eeb0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b6-4971-7fe1-9eb9-517d9cb1b1e6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b6-4977-7918-8e8a-95c174b379da
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b6-497c-761b-9506-9fbc2af0655e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b6-4982-7a1d-a680-7ffb5c0ee411
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b6-4987-7966-a2b2-dd179217e4e0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b6-498c-7a24-8f86-e9339d5f1608

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b6-5a08-7d5f-a5ac-a8294d2ae237
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b6-5a0b-7a53-a316-6faae99d76da
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b6-5a11-7cd5-81a8-5711a06a67fa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b6-5a16-76af-a97b-82fd41168310
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b6-5a1c-7846-b7d5-9d13399ad64f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b6-5a21-7250-b992-f16f047fdadd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b6-5a2a-708a-a2f2-ca2f6dd913f5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b6-5a2f-72cf-b646-46dbbf00a366

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b6-728c-7334-afd8-298f0b06ef32
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b6-728f-7db9-9914-43834faf26d4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b6-7296-7144-899f-19ad73a1cde1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b6-729f-7d75-b3fd-537447d79f4b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b6-72a3-78c4-8577-b457c6df08f6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b6-72aa-7e6a-bd78-8e2d365a86ad
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b6-72af-74c7-bdf1-99b855dc67b6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b6-72b5-7c24-a907-dafb7fb0bd79

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b6-88af-7081-a3e3-fbbc134425c8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b6-88b3-7525-8613-83c23b8683a1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b6-88ba-7724-87cc-d779ed475857
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b6-88bf-726f-bfec-1ebfaeb07540
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b6-88c5-744d-a8c9-b9d6424f7aff
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b6-88cc-7611-8066-5fc2a27d04a5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b6-88d0-7bca-ad6a-87331bec0e2e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b6-88d6-7e3e-89c1-de1fe00286e4

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b6-a4a3-708e-a260-52068d155417
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b6-a4a7-7765-942a-58e8f7d1686d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b6-a4ad-724a-8d5f-6956a3a4e075
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b6-a4b2-7790-9814-a0642fc68087
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b6-a4b8-7e42-b42a-4b124f25624b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b6-a4bd-70a2-b241-0618abaa5ab1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b6-a4c3-7adb-a83e-9997b2682e1e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b6-a4c9-7eb9-8241-966839a90a6d

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b6-b39d-753d-9afb-c6c51af46172
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b6-b3a0-7293-9205-9bd184368534
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b6-b3a7-7b29-85b7-11e87f9f4f37
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b6-b3af-723c-8c39-aaaa79c6122b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b6-b3b4-7ace-9576-b3877710c3c5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b6-b3ba-79d6-a579-c699ac1dcfe5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b6-b3c0-7704-a03e-179cbd58250d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b6-b3c6-7de3-9591-fb75e124458b

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b6-bf1f-7baa-b378-6e2ad8e20d0c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b6-bf23-74e0-9cf6-0d09e0d298f6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b6-bf29-75ee-842d-664e025d6cde
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b6-bf2f-7b00-a985-95c09179b1a1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b6-bf36-7b7c-bdf1-bb9ea3b2b020
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b6-bf3b-7103-8a6e-ca26a539eace
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b6-bf42-745d-b593-fc037dc11cff
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b6-bf49-7712-8baf-c617aa076c05

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b6-d3c7-72ef-8716-22fd42526d18
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b6-d3cd-7842-94e8-20d28a79d9fa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b6-d3d2-7448-a1ef-160906649d6c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b6-d3d7-7cc6-8406-3e3b3db18f1f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b6-d3dd-7e02-96eb-2e22d9506662
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b6-d3e4-736c-984e-6be7d57fc74d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b6-d3ea-72f3-8bc3-e17dd1064347
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b6-d3f1-71a7-9252-b0ae29c8ab46

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b6-efd4-7996-8c2b-c0425a33ba85
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b6-efd7-71a7-b9d2-8776eaf60dd7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b6-efdd-7f37-a763-8518741a97d6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b6-efe2-76cd-b162-043bbf3a2b1b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b6-efe7-7708-97ff-0c673632c008
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b6-efee-78de-9f54-613b181922dc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b6-eff3-72c3-b549-52ba86832dd1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b6-effa-762a-81e1-0131046078d0

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b7-0abb-7a60-9f8a-4dc806ed4a21
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b7-0ac1-7e3d-9354-e72b9c59f6c7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b7-0ac9-77f1-9a92-3f36b396a123
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b7-0acf-7b27-8690-9054ec8e8e71
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b7-0ad6-7292-8045-a0ce3e36b937
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b7-0adc-733d-87e5-07526d027deb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b7-0ae2-73b8-ac10-afefd161412f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b7-0aea-79ff-aafc-91e35e12b891

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b7-201f-793f-99b4-76e6fbce8dd3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b7-2024-75a8-80b8-5c02105bb3d1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b7-202c-77bb-b49b-f82bf15f2385
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b7-2031-7c26-bcd1-f268ae707d52
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b7-2037-730a-8ec9-74ac4482ec20
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b7-203d-7369-aef6-99dd46a92168
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b7-2043-7187-a85d-812391bec743
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b7-2049-7875-936a-26a82c60bf5c

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b7-34f6-7f84-a7e0-b378c118f30f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b7-34fa-711d-a5ed-db6c19fa43dc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b7-3502-7514-a4db-0ae8cbbc2e7d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b7-3509-7482-939a-9b0e2d877916
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b7-350e-748c-97e5-187e741bd809
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b7-3514-7663-87fb-86b1bc7f3bd0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b7-351a-7ebe-ac59-fc4766451bc8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b7-3521-706c-a317-ce8e135e7a65

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b7-4c0c-7a77-ada5-ab1876a5fabe
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b7-4c11-76a5-b636-eff524ab55d9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b7-4c17-7b6a-91ef-59060d1355e2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b7-4c1a-7afc-b9e7-f15d557e709d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b7-4c21-7e9f-b515-1bb348d165cf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b7-4c27-7191-ac7e-824d57fefe81
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b7-4c2c-7ce3-85c7-a441a702cb86
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b7-4c33-7a7d-b553-95a7d7513d33

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b7-6482-7736-8622-36e5dd7f9bcc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b7-6485-76fb-823c-9a17ccdc11f6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b7-648c-7c9d-bcf4-760d95c7bc51
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b7-6491-7af1-be62-24bd121b92ee
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b7-6496-7e5c-b601-365b6619474e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b7-649d-7fd6-9a46-7e369084147e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b7-64a3-7439-b44d-f9b3bab8e840
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b7-64a9-70a2-8bb4-e63adbee89d0

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b7-7ed4-7ca7-8a12-7409f31b8581
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b7-7ed7-7ace-b04d-473fec6bbc70
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b7-7edc-77a9-bc8d-1e93cf5376a3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b7-7ee3-728e-a06c-dfd85589a545
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b7-7ee9-7d61-a596-fdb08661830d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b7-7eef-7df0-a717-3a5b69d0384f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b7-7ef5-7d83-8fb5-81060cd8cf05
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b7-7efb-7e4b-a4ee-bcbb34f04d48

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b7-9ad8-74e3-abe6-95a2adc2c7b5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b7-9ada-7705-a69c-334d482a5683
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b7-9ae1-7923-bd05-906fe17a6bcb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b7-9ae6-7948-b165-1550c195de04
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b7-9aeb-7630-af11-ff8e4904cad6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b7-9af2-72d0-92c2-5ad85ac00c22
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b7-9af8-7150-84ee-02bca066c2f5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b7-9afe-7fa6-aab9-0ef3c9311d82

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b7-aa02-7eca-9f14-b44da301fbab
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b7-aa05-7171-adfb-a54bfb40801b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b7-aa0c-760b-b27a-1f4f30e5783e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b7-aa12-7e54-905f-83cb7086d954
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b7-aa19-7aa4-99ab-556e13245762
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b7-aa1d-7c75-9d74-b69da02f1847
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b7-aa23-7efc-8c3b-0fc60c37d008
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b7-aa2a-7f13-bd3e-b835187d6b4a

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b7-ba32-7a23-a2b8-9e041ce99594
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b7-ba36-7418-8236-bbee89cdd36c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b7-ba3d-70b5-b616-e0969ffddd95
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b7-ba42-768f-8e07-75bfe2fab12d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b7-ba49-743d-87cc-ba02daa74a55
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b7-ba4f-726d-ac92-495043143346
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b7-ba54-754a-997a-589052091e6c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b7-ba5b-7fcf-95d5-69b78a75798c

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b7-cb8c-74da-ad23-491551c7507c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b7-cb90-77ca-858c-83a885076865
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b7-cb96-7d5c-8536-de853c406a2a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b7-cb9c-7262-b7ba-db8d07e278e1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b7-cba2-76c3-b48e-c305b8eb9573
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b7-cba9-79f6-aaef-8cc300d7096f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b7-cbae-7524-bb75-30dc823ef3b3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b7-cbb4-7b5c-9895-9e668681ca5f

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b7-e077-793a-9037-914f1cd76f58
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b7-e07b-7165-b090-6fc5641acb50
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b7-e082-7890-ac7f-7e7f760cc2f3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b7-e088-757d-bb62-b7153353d00f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b7-e08e-7005-a33a-16d0b991c983
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b7-e094-70c7-a55a-abcc9329684f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b7-e09b-7b27-b99a-daa98f9d3d36
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b7-e0a0-7223-a560-89b30ceb1f76

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b7-f2bd-79f5-abfd-a001cf2215d7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b7-f2c0-7b60-b5d5-337e560df947
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b7-f2c7-7943-b2c4-2c9171b7d3db
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b7-f2cd-74d8-a468-2fee089cd2b5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b7-f2d3-7e33-915c-1e321c46ee92
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b7-f2dc-76ee-9ed1-eea006fcb77a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b7-f2e0-7317-8941-92b6f21b5711
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b7-f2e5-7455-b229-dcbf8e9dd78a

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b8-0a9d-77d2-b4a8-98bfda67493c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b8-0aa0-7e21-84bd-198cf9fb9736
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b8-0aa8-7828-a37f-a984252eb116
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b8-0aaf-7ecf-94cc-24fcbae7236d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b8-0ab4-78b3-be18-491b4f4f8860
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b8-0aba-7fe5-a348-b87eca084c90
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b8-0abf-7c67-8831-f246dd361371
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b8-0ac3-79f8-a94d-64f983c29c28

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b8-1ebe-743f-8850-9901f4212918
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b8-1ec4-7ea4-9c5a-7460c309e334
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b8-1eca-708e-ab9c-03c55d34d8da
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b8-1ece-7118-97e7-1e5138324e41
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b8-1ed4-7c47-a93a-20bf95bdd983
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b8-1edb-7b21-9031-98a2a77ad027
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b8-1edf-77c7-89cd-5a36b02d5c19
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b8-1ee4-7cc4-8e61-d61ac09c0c74

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b8-2aeb-7817-8b6f-ac3c76426f8d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b8-2aef-7b8c-bd1b-83cc2e600834
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b8-2af7-79b0-8bcb-f1bcfa2ee6ac
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b8-2afd-79c1-a5e2-95d657868dfb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b8-2b03-785d-bb13-fd9488699ccb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b8-2b09-7598-a82b-8f1d2cef3ca4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b8-2b10-7767-a319-6d461f382fb6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b8-2b16-732f-851f-a5d86260c23b

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b8-46c2-73dd-9487-16db80613d0a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b8-46c7-79a2-a0b2-3193927c726c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b8-46cc-7c85-bd2c-fd15e8df17fd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b8-46d1-75a9-b12f-32513b7d5a0b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b8-46d7-7b05-96a8-fc3da7ee8c0e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b8-46de-771c-91ce-70356c42d6b7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b8-46e4-7cdb-886d-f782f4d6abfe
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b8-46ea-7573-a21f-7aacc0e346c1

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b8-5db5-748e-8fd4-2e8d1e2c6248
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b8-5db9-7c8c-b517-c88c3bd1dec1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b8-5dc1-7160-9160-293b08032f13
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b8-5dc6-76c4-a6f2-97ea20b1fbbc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b8-5dcb-73ac-b454-f13a667c2812
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b8-5dd2-7b9a-87a6-2ced95be9e8a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b8-5dd6-74ce-a2f8-02a7d8389bc7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b8-5ddc-7d50-b627-c1af44caac7e

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b8-7407-77f0-b6b1-5834b5df9403
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b8-740b-7fa6-9626-7519d15d8c7c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b8-7412-7b12-8d44-01ee221c56ba
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b8-7419-7747-8fb4-0f15c3f294ce
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b8-7420-74cc-a984-b99cf5e1efa2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b8-7424-76e9-99fe-4d2e3c1d64cb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b8-7429-7e00-92b3-670a36f04808
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b8-742e-7402-a553-3677d203ec5c

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b8-9339-77a0-9073-a8772f855561
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b8-933c-7396-8d4d-6277301b0979
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b8-9343-7c2e-9cdc-32439b27998a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b8-9348-7921-94d6-a9f1fe44badd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b8-934e-7c2d-ad13-1f19eda57ea6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b8-9353-705c-a88f-66c258e0be54
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b8-935c-7553-b62d-7986bcff0c0d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b8-9362-7df5-b7e5-61f54d8b6a44

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b8-a9f2-72bb-9589-6e34340dd87e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b8-a9f5-7955-b263-8e8b60c855a6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b8-a9fc-7c2b-af62-c312aa8f867d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b8-aa01-7b16-9fc9-52fe3b5a47f0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b8-aa06-70b3-b7d6-d093c5e1a2a8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b8-aa0c-784b-8f61-2362b370f81b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b8-aa12-7c92-a88f-c49596309da7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b8-aa1a-7604-a51f-116c3b34f734

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b8-bb77-7e28-9af4-8545df8e2d0a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b8-bb7b-7954-a8f4-aa8b55e22655
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b8-bb82-7e76-90a0-3235340fe33d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b8-bb89-7a52-95a3-a6fe4c1a40a9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b8-bb8e-7857-b6cf-6ce7a6521735
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b8-bb95-706b-850a-f75642675c09
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b8-bb9a-7265-bf56-c0d64dac17ea
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b8-bb9f-7fcb-9e2d-5da3211edf09

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b8-e111-799b-8277-31c78dc5c8c5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b8-e114-73e4-a1e7-bf59aa39432d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b8-e11c-77cb-91ac-a00d287850fd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b8-e121-7bdc-8ba1-7c97a045848e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b8-e12a-7a15-90c1-1ba38c3d5362
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b8-e132-7a5d-a67a-4f627f04b27a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b8-e139-77a4-bd5e-f613fa5a1ae1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b8-e140-7bb6-8ab8-5a02f73f1cf4

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-0186-7ceb-b734-97e5b34a6ec6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-018a-78ef-924d-213e052c52a1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-0191-7fa8-a72b-4fd369fdebf3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-0196-759e-994c-0eaf0a2d57bb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-019d-7cf6-aca7-1f1aac54825f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-01a3-79df-9055-9dd5c5caa1f3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-01aa-7258-8e4f-315e1977cf50
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-01b0-7353-adb3-2e7fb45c69c0

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-120c-7c9d-8f68-70affb482ab1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-120f-786c-adac-5eec7f73827e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-1216-74ce-82c8-2f8fc6704257
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-121e-710a-b7fb-ec5bcd8356c7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-1225-73ca-88d3-9e9f94b5997a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-122b-7e43-abd5-d20497c2dd64
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-1232-7388-a388-ca34eb5a595a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-1237-7261-b897-1251bd913e09

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-21a6-7e78-b47c-6d7aeb5a5788
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-21ac-7f5a-9622-8fa2169940e8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-21b3-76bb-ba4f-a664eddfce3f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-21b8-7b5a-9f87-66f39c1442c6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-21bd-7c30-b073-a789ce64793a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-21c2-7a15-8499-8da7c273fff3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-21c9-71ea-9423-19f19383a1b7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-21d0-7088-a7ec-0c39ec793da9

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-35c0-7f17-9d04-0726ab8620a9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-35c4-7ecc-a027-966d474fa47a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-35cc-70ae-a8c0-b07532b532bc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-35d4-72dc-92c8-02d2aa0777df
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-35d9-7147-affe-926968f18a6a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-35df-7fab-9cf0-bbca2463babc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-35e5-71a4-96d3-2b299bf92c41
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-35ea-74d1-82e8-5ce541ab8dd1

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-4e75-75bd-8eb1-4f33867fbb0b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-4e79-7064-a3ee-57cfca3f339f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-4e80-7611-aedb-1ba0f7425990
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-4e86-7f09-96dd-dbc9c266a53d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-4e8d-749f-8abe-54ca7a4ac681
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-4e93-7533-9164-05f2b2c4e606
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-4e99-7ab8-87fc-3dd59e705ec2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-4ea1-7294-9692-4beb4af7b344

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-5fa0-77ac-8e76-0a039857d6d8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-5fa5-7a46-8f3b-0c48ca3e6d3b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-5fab-7fed-9179-26a6020cca1e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-5fb0-76e7-9267-84a99a9f488f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-5fb8-7356-ade0-58f02727790a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-5fbe-70c4-a854-97879f1c71c2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-5fc4-7f28-81dd-f7760096db2e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-5fc9-7475-9151-f6adc6d8af75

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-83b9-7e60-a219-8e94833adec0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-83bd-7d86-8e64-3af879154ac2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-83c2-74fe-ac39-4378558d50de
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-83c9-71f3-9a03-593aac64bca7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-83cf-75fe-9d82-2acf2dd375fd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-83d6-722a-8af7-6016047f13bd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-83db-70f7-9dfb-90606367858c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-83e1-778c-bcec-8ae0d5bcee05

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-8ea3-7a74-807b-5f59a0b61e88
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-8ea9-7e3a-9a78-3d0b148f7827
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-8ead-7c76-85c2-928df0bf5500
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-8eb3-7577-84bc-33f4be5b12f3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-8eb9-76f0-bf6d-257da1757471
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-8ebd-798f-aef9-2fa32d650cd0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-8ec6-7184-9098-5331fdfab65c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-8ed0-7028-9e7a-8edff7e08973

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-a1d7-7801-9ea3-7da275daf157
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-a1db-735c-8c1e-8b51c6829ee5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-a1e1-729f-9f31-8fe0bea9ed0d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-a1e7-77b0-b394-ec7cec3d308d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-a1ed-7c2e-8c9a-9148bec71cb4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-a1f3-7d79-841b-484aa2436e36
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-a1f8-7631-9a31-e1968e961098
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-a1fe-70ab-b5e4-5a4b4557c39d

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-b97d-7950-9c02-d387494c7869
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-b983-7484-aa21-e00728705938
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-b98a-737e-bac6-5987dcd39c5b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-b98f-72ba-b3cd-7333e227d5f7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-b996-791e-a298-00e411abb360
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-b99b-75aa-9e21-43c315aacca3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-b9a1-7164-904b-252da3ba7e07
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-b9a6-753d-9020-87dbf1a6120c

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-ce96-7ab6-9c56-1d075b1a8cdb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-ce9b-7fee-962c-55cf7229073c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-cea2-7beb-bec1-48382d021bce
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-cea9-7006-84fc-132ba95a0269
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-ceaf-7b17-a53b-042fd6e0867a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-ceb5-7b9c-bd55-5fa3e498c5ae
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-cebb-724f-a996-63c103ac5b00
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-cec5-71a0-8dc3-8e9956738c1d

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-ebec-7e12-860e-d122b6df8d73
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-ebf2-7eac-997f-6350a4da14e2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-ebf8-7d84-b052-d7f4e1d030b5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-ebff-778e-9348-f82fe52c8b70
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-ec07-71d9-ab2f-e3ca294bb86d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-ec0d-7ab8-ae4b-912750b38a9b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-ec14-79a0-ad5b-cb25e7bf8238
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-ec1d-7b6e-bec2-103498c2d6fb

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-fcd4-7ec7-b6d6-bda6767b8b39
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-fcda-7275-af20-7c28a5bee928
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-fce1-7b15-bc3e-4478d51fa1f2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-fce8-79dd-ace6-3eb58c6d345e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-fcee-7bea-80d5-87f3d908c6dd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-fcf4-7b62-b5a1-a8c72e4878b0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-fcfb-7442-bd49-f6f5a8017dd7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1b9-fd00-7a53-98b6-f8f052010fbf

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ba-19e1-73cc-a946-537a0ae04b43
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ba-19e6-7470-baec-a8b459e227a5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ba-19ed-73a3-a1b4-486be7dbe6ac
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ba-19f4-7d27-8d14-fcc59abc1748
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ba-19f7-751e-92f3-929b52c5729f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ba-19fd-7e56-b880-0eb45f3c1390
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ba-1a03-79eb-b372-932324281d97
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ba-1a0f-7f1d-ae7a-a3ccb34f471f

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ba-3a28-7b74-a297-b7f8553eb979
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ba-3a2e-7c43-b462-8ac5664569e8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ba-3a35-74df-8b0f-32db818476ab
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ba-3a3a-717a-b443-c0d4796ee3c0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ba-3a41-7fd1-a34a-c9ff78ab50a8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ba-3a45-7ced-9e23-b592577b8e26
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ba-3a4b-7a46-8df4-cfe209a9cdca
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ba-3a51-789c-9f01-445ff591d105

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ba-55ea-7676-955d-5e25d7c02164
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ba-55ee-7e94-a7f8-71faaf789396
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ba-55f6-7b17-a3d0-2406a91fa36b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ba-55fc-79a8-89f2-0cebe9c2922a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ba-5602-7d51-9aad-2d42635138d8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ba-5608-7eb7-979d-74307dc39656
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ba-560f-7f7f-a6ec-04ebd982c2ae
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ba-5616-733d-85db-e7f92a9af534

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ba-73c6-734e-b7a9-8082c729a99d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ba-73cd-74ef-9e8a-6a97e0e7f878
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ba-73d2-71e5-a53f-6dcaf2a540f7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ba-73d9-7062-b137-0d361371e7e2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ba-73e0-77e1-a24b-a185b02a2c08
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ba-73e7-7d4b-b607-fe65a5eb0bad
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ba-73ec-7972-a5af-328cd1ce7556
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ba-73f3-785e-9cef-aa5a7eedb901

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ba-82ec-7e10-b209-7420154dc178
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ba-82f3-7cfa-9d7a-f73551d0fd36
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ba-82f8-7fdf-9da6-eeda7064c5c0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ba-82fd-7dd9-a2fc-befbd9441ed1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ba-8305-7a74-b410-09b39f257bfd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ba-830a-7afa-86f9-fc6e34060d19
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ba-8310-721a-85c5-f143df4286d2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ba-8316-71c1-a481-799b5cb8ef56

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ba-9691-7240-b46a-0df7bec37659
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ba-9696-702a-bdc2-ac54046634be
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ba-969d-7d13-be84-520604622570
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ba-96a3-737f-bbc4-132026c608a8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ba-96aa-7c71-9573-b14597fe7c80
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ba-96af-775f-a3a1-8f68e91e7343
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ba-96b5-70be-b671-2701d4b1e9d6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ba-96be-77fe-89e4-7838496495d3

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ba-b532-7c85-a4ae-d017d69afbbd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ba-b535-72b2-ba7f-960ba8a2fae3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ba-b53b-7da1-bc02-a9d4a9caf374
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ba-b542-7721-8167-c7b736559aaa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ba-b548-7008-a688-25311dda292b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ba-b54f-7e9b-9555-9284dc8e8955
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ba-b555-719e-bdc8-ec61ca3435f0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ba-b561-750c-9913-a10d8d510643

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ba-c96b-74e6-a8d7-90e65c310445
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ba-c973-75a3-80d2-89662f550010
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ba-c978-75ae-aab6-6938994e2fc8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ba-c97c-732f-ae0c-a6f647a2e154
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ba-c982-7a4c-bc51-1d8c6e6052ff
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ba-c987-7a0f-a6c0-b34aff35a931
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ba-c98d-7adc-9d50-f59e695b02cc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ba-c993-7bec-b58b-fe74b8c1e614

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ba-dd52-7ffc-8054-3f0547750904
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ba-dd56-73da-8394-de321a66f22b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ba-dd5e-7a31-bba0-523399343c58
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ba-dd64-7595-badb-f14916a87af4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ba-dd6a-7204-b185-93ec2fe413d2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ba-dd73-79ff-9b74-28b9324507a1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ba-dd76-78df-ac69-bd3123a0e79f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ba-dd7c-7546-8968-47380fcad028

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ba-ef3a-7e1a-a730-23881de10522
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ba-ef3f-7234-a92c-2b8538817453
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ba-ef47-7854-8ff3-b98b24a067ca
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ba-ef4d-7be1-8e53-df6918ffe05b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ba-ef51-7cca-adcf-ce5e09601c86
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ba-ef57-74b0-9601-e6c49e713a8b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ba-ef5c-717f-b6d1-bb9f14bd1634
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ba-ef60-7813-90b9-7f78ea81bb95

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bb-0e15-7818-bf23-416592cf6c06
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bb-0e19-7585-a5e2-c8cc2c34bdb9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bb-0e1f-7964-9ffb-43153e50ba8d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bb-0e25-746d-8049-a3bb3c0ed8aa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bb-0e2b-7247-a053-205e752a60ed
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bb-0e30-7208-b57f-77ffd34c0696
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bb-0e36-7e1c-8592-529a3b05f2dc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bb-0e3d-7d3a-87f9-8a6a1e8c03b6

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bb-1f12-7493-9c30-21819ec7a7e2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bb-1f14-7b10-ac1c-37ab60116d75
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bb-1f1c-7df2-ad35-896b9b29824f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bb-1f22-75da-be9a-ef32d783c651
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bb-1f29-7e67-8de7-307b5998f4a9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bb-1f2e-78ec-a461-206850a2f331
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bb-1f35-7ee0-828d-c17d97d81dbc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bb-1f39-7886-85bf-23eadfef6a96

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bb-312f-7fe8-b212-f9318b55e967
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bb-3135-7196-9506-8bac49b3cb8a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bb-3140-77f5-b2f5-ce4c4f402614
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bb-3144-76e9-bb94-1c76792859ba
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bb-314b-7d3f-9b75-ebe73d4d5696
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bb-3151-7c42-be9d-64601a246e69
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bb-3157-738c-b457-92a73a7ad59c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bb-315f-7b06-ba77-0a42b9d3cd4f

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bb-4b88-7316-a3f9-0f69456995ab
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bb-4b8b-7255-82f8-858442051f56
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bb-4b91-75a9-8503-704fce4c08bc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bb-4b97-77e5-8bc2-b527d0021bba
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bb-4b9c-78ee-8844-a4c12be44463
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bb-4ba2-7ac5-ab3d-46eadff26d28
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bb-4ba9-796b-98bb-10d32f74f7b6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bb-4bb0-77de-b135-0644c83ccdd3

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bb-63cf-7488-947b-ef68a01ec959
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bb-63d3-7fc7-b02d-c74d5761029b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bb-63d9-7f2f-a14c-8676e3282ea1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bb-63de-730d-9d32-a5b9a72d24a1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bb-63e4-7f54-9da0-022b8b2f7c81
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bb-63e9-7bcf-918e-1025049b2924
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bb-63f0-7053-8083-992c338e3e16
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bb-63f6-7102-9a77-dcc3bdbfa44f

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bb-6fe8-7883-b6e1-1e1052a3e99d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bb-6feb-7e2f-8f33-c1e121367872
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bb-6ff2-7305-a041-5844e2a09cfe
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bb-6ff8-75a7-b5b8-0f41bc0fa80d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bb-6fff-7c29-ba69-0384e09119fe
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bb-7004-747e-9929-34db5565645e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bb-700a-7671-ab46-182c1bb2ee9b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bb-700e-7454-9abd-3796cd97bfb1

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bb-8df0-79b9-80dd-d8350c254659
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bb-8df3-72ae-a337-50cb847d6e9b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bb-8dfa-7890-b1ea-9237719b7101
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bb-8dff-7034-95a4-8277044e9036
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bb-8e05-730c-95a0-4f63fb9b524a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bb-8e0b-74fc-995f-36cf84576b72
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bb-8e10-75bc-aefa-5519a0d84aa0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bb-8e15-73a5-a63e-b77ef2ad6d41

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bb-a90d-764c-a4d5-77ec68be83f4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bb-a911-7c98-abad-2d97360c2594
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bb-a917-71e6-83f0-db14ac85f68a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bb-a91d-7916-84b8-4659b1d50c64
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bb-a922-785a-bd1e-9e63e458c139
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bb-a929-748f-bd41-a9aa41e3d311
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bb-a92f-776e-86c7-e468a9be5a00
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bb-a936-7260-9944-0203e3b8affb

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bb-c268-77ef-8998-18100a766441
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bb-c26b-7a31-9c87-c0b35a8f2867
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bb-c271-7a83-abfa-c02dcbeaa31c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bb-c278-7a03-a2e5-f0f5321edca4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bb-c27f-77f1-a9f2-7ac118f8d844
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bb-c284-7c1f-a687-801c4df5e7c7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bb-c289-77eb-88bd-21a9314a2ae6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bb-c28f-72c1-a3b8-9d3c1d0f194e

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bb-d3ed-71d4-b36b-9301c182eccd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bb-d3f1-770a-9279-3324dc00b954
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bb-d3f8-7678-9186-f62d3fc79163
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bb-d3fc-75e1-adb9-05e028c07085
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bb-d403-7262-9f35-f05e907dbbfe
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bb-d409-7cd0-8671-b9670505735a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bb-d40e-7b83-a311-58190e12f51a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bb-d417-7cef-8911-38942b1513e9

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bb-e10b-7572-96e5-b622c0324368
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bb-e10f-7430-b47c-26168a8335b1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bb-e115-71fc-adee-8940fabcf989
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bb-e11a-719e-bcaa-cf42cc46b4c6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bb-e122-720f-8ff6-f515dfb6e233
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bb-e128-7f94-8bd1-d9a0b3578a0b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bb-e12e-7776-9ac9-ab161815a628
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bb-e133-7555-afab-11aff86bdfb9

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bb-f13f-79f6-9a5a-82be6d68606d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bb-f146-743d-8faf-175771c76f1b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bb-f14a-70ba-9345-999b50df2544
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bb-f150-7741-8339-8b75a3771201
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bb-f156-790d-9c49-4c032934d77a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bb-f15a-79af-8de7-75d34b5f5edf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bb-f160-7a55-b573-38925308721e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bb-f166-74d3-b4e0-c3c4e0c4c2bc

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bc-0168-7a13-a674-90f9a117ae0d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bc-016c-7d33-80cb-529a048b15f3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bc-0173-7a0f-9ef3-2f30b9740929
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bc-0177-7bee-a6eb-bf522c9e5de4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bc-017e-77b9-b5e0-b3d34b185893
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bc-0184-7aa9-ae96-09d409f12872
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bc-018b-71d1-879d-92c184457a24
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bc-0194-7c89-aa8a-d7a2468a2256

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bc-23d9-7083-9903-b17facc2436a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bc-23dd-7ea4-adbf-87986b22c0c9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bc-23e3-7a14-a0a2-03d471142409
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bc-23e8-7737-8dfa-d3af1b61d27f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bc-23ef-717d-b2d9-fd0b9dc328ca
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bc-23f5-789b-bc00-f0bd31a95c4c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bc-23fc-7e8e-8e9a-c80406f365b7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bc-2403-73fb-b568-b32db6033ac7

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bc-4052-73ad-a371-e95d52b348f2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bc-4057-7a52-8cbb-7eb1ff415b96
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bc-405d-7dcb-8772-13744672cdfc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bc-4064-73b6-bd02-370520219418
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bc-406b-7c7e-8da2-d20a1f08e4af
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bc-4072-795d-b13c-b8e13d98d7cc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bc-407b-7b60-956c-2dfeab580090
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bc-4085-7cbb-8436-55e2ee014d12

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bc-583f-7020-bdd3-7820a889ddd7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bc-5842-746c-8037-35ee9c0ca4d1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bc-5849-74a8-9722-7b175120bf29
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bc-584f-7995-9fd0-3169360794bc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bc-5854-7a64-80fe-5024b5a684ba
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bc-585a-74cc-bc53-2cf3bf5470b4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bc-5860-7067-8a2d-96436f201921
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bc-5865-76cf-88b4-d0e3fd2af213

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bc-66f8-7f1f-aa7a-a59999c65836
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bc-66fc-707a-ac9e-ff06d1f7be54
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bc-6703-7a4e-bba1-a307aef8af17
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bc-6708-76bb-94ed-27fc003e926c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bc-670d-7a78-8647-5ca825ea4f68
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bc-6713-7848-9c6e-3a7ec92e6fa0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bc-6718-7245-9515-0cec781cbc5b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bc-6721-7097-81f3-e8ad1c6c0c7e

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bc-79eb-7ca2-8f35-e93ff85a9b82
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bc-79f0-7e33-bfea-415f59bdbc34
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bc-79f5-7b6d-bef6-781e35b56cf3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bc-79fc-7ba1-883d-5907507265b1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bc-7a03-785b-a8d8-d3f6aaa6dcb8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bc-7a09-7524-ba33-80b6c41f8c30
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bc-7a0e-718d-8a11-f1c5d3c7942f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bc-7a13-73a9-9fe8-a9b694f8b523

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bc-9239-7afc-bba3-f5d4506a2934
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bc-923d-7e42-b520-16d53dbda280
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bc-9243-748b-b5b6-75625b9724ea
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bc-9247-73a9-8124-a53ba790b2e8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bc-924e-7fb0-b0e0-88af9cc7d0f0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bc-9255-77b5-b38a-e2f2d0417f70
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bc-925b-7fa9-abe1-c474ce176e9e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bc-9264-7072-9bef-bcf9fcc94b04

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bc-a775-7591-8b21-caa80ec6ad9c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bc-a778-7146-a9f5-034804253a28
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bc-a780-7e54-a1bf-c59dda306445
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bc-a788-7bf5-b337-fe8df363680f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bc-a78e-7ac9-b241-c227ce087b4b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bc-a795-7b6a-b103-0bf3c1c9f2e3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bc-a79c-70f1-9405-17c0d1a0826b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bc-a7a2-7ea8-bc64-2386cbfe9112

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bc-bded-77e2-a29a-00e1eb702eae
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bc-bdf0-7a7a-95cb-f888adc87f64
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bc-bdf9-7a7f-9577-4b958b8f4dee
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bc-be00-7f82-9fb2-79561dd14f6d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bc-be06-7fb7-b832-9599d1ef3707
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bc-be0b-7fe7-a627-2e49dcfde094
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bc-be11-7c75-9d8f-6e2daf5170a5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bc-be18-7d97-b25a-ddba83beb380

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bc-daa2-7af5-bb1a-6917ef2d7a6d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bc-daa6-7da6-9db8-b04ffa3fd5bf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bc-daad-7f48-bffe-f77151fd401e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bc-dab1-7615-9827-996b27dc8ba7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bc-dab7-791f-8d80-8723a1674943
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bc-dabc-7b5f-9f10-7d37f0db37ea
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bc-dac5-70c7-a271-553526ae9c56
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bc-dacd-7b69-928c-ebd6d3345f3d

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bc-f5d1-7166-90a6-8393ec98b44b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bc-f5d4-7336-942f-caad84475102
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bc-f5db-78b9-b74f-ece42ee9143a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bc-f5e1-7428-8c9e-bb503b2f158d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bc-f5e6-7645-9582-d2814cf63454
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bc-f5ec-724f-9383-2cfb20d94626
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bc-f5f3-78eb-a46d-6ac83bfe75b2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bc-f5f9-7812-af6d-7e017b1f194c

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bd-0d02-7117-8b4c-afbdb1f3d6f2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bd-0d08-7c8f-be96-d0fad7b0c893
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bd-0d0e-7f6d-9128-d019a54294d9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bd-0d13-7b27-9e53-6b3028618c9d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bd-0d1a-7439-ae5b-4a2a5ae2a1ea
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bd-0d21-78a1-b3a7-badee430c7e9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bd-0d28-7e3c-a0bb-6cb710ef111c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bd-0d2e-7472-896c-705f774bbfe5

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bd-226d-78eb-9e3c-e09e14500ea5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bd-2271-7757-8bd5-cff4d79b6557
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bd-227a-760c-82a9-7c074533b914
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bd-2280-7184-8b9f-78da1bbdb86b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bd-2287-77f7-a9ff-284155573f5b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bd-228f-7307-be35-af581cee05cb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bd-2298-7726-bf73-0255a880b334
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bd-22a2-75fa-8208-b28c473f1f8d

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bd-3947-7e05-9986-aa615f45e8c4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bd-394f-7047-9fbb-ceeac00d53f6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bd-3954-7baa-9331-b613e1f324a7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bd-3959-78ba-9fff-238c4cc90829
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bd-3961-7bbe-97e0-89b1c7b0f35a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bd-3967-7069-8936-2150051e57bb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bd-396c-753a-888f-9a28ac6cd99b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bd-3972-7645-9056-0b52bffecbb8

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bd-4801-7fbd-a37a-ad364d02d931
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bd-4806-7fcb-9e74-564c6abb0ce5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bd-480c-7782-a43c-06b5328f2ac0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bd-4812-7ae3-b6de-f4c0b34342d6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bd-4816-7f91-b99a-2022d3f56273
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bd-481c-72fb-9260-bb441a45a609
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bd-4822-7867-af0d-17dc919efbba
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bd-4827-7cd8-bfac-2d9217a50624

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bd-5e81-74c5-a201-90263c064adb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bd-5e84-7c8a-8419-d240132a9522
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bd-5e8d-756a-a0b9-60f47b043594
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bd-5e92-7b76-884b-4648473e1629
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bd-5e97-7f20-8069-f594530f7e10
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bd-5e9d-736c-8246-4e9cc6eec364
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bd-5ea8-7987-8239-344cb84c4be9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bd-5eaf-71cd-952f-7437ba490882

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bd-73d9-7b5c-a93d-513bf706d170
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bd-73dc-7b07-80c8-cca498922ec7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bd-73e3-7561-8824-c85e5440a481
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bd-73e9-777a-af26-3d7de70d8ea3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bd-73ee-797f-8073-a56a0fea2b10
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bd-73f6-7e1a-93db-d6fe1bb37119
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bd-73fb-758a-8b32-2c91b521af44
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bd-7402-71e3-9fa0-44716773fa20

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bd-86f8-730f-8d4f-869ad4432206
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bd-86fd-789c-bd3b-449d430d5443
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bd-8703-7d1d-a621-d0184b107f0a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bd-8708-7fa9-a621-50084c00198e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bd-870d-77ae-a68c-5ca07c7b3d3a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bd-8711-71f4-898b-868b07c97d6b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bd-8719-7ccd-90a6-131099895086
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bd-8725-7212-8f4a-7f7f4a827868

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bd-a0d3-7d79-9164-e1d8373666bb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bd-a0d8-7dec-9289-b1df03d5f0ca
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bd-a0e0-7c94-befa-338e01a6f85a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bd-a0e4-7f3f-b015-5e7ad9324504
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bd-a0ec-784a-81af-03718e2a08ea
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bd-a0f0-797c-a620-740b5f3a68c9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bd-a0f7-7d3c-a787-f80de02cc581
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bd-a0fd-760a-8d28-e409fc9a8313

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bd-bbb2-70cb-aa5d-29a7b88b4029
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bd-bbb5-7672-b2c6-d2b88f4d2751
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bd-bbbc-7f69-aad5-370631696e9a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bd-bbc1-731c-9877-3b9b24fd460f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bd-bbc7-7b5a-a846-8bf4114a668a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bd-bbcd-77d0-8bfc-b7262be11771
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bd-bbd3-7197-abce-99df2923ca0c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bd-bbd9-75ce-b6de-a74e96455981

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bd-d052-7f16-89a6-b6bc17bb70a2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bd-d055-7cf6-be88-c5a9d858b92c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bd-d05e-7875-b7f1-d0e1d6e81206
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bd-d065-7a94-99af-06b343c90519
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bd-d06d-77dd-ad37-306164542256
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bd-d072-7595-9b44-36a0f96e0137
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bd-d079-7f5f-a75d-8560e22ae218
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bd-d07f-787d-9e7e-1832cb20c5e0

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bd-eac8-7124-b054-da8b461ede78
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bd-eacc-783d-8006-4891d3526f75
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bd-ead3-7f04-91dd-ecc817faf77e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bd-ead7-71c1-bf3f-2d3a0ccdd71c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bd-eadd-786b-8240-3fcaa61dda59
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bd-eae2-7f1e-b3f2-1491f2b875f1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bd-eaec-79ac-9d66-7b0822264b53
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bd-eaf4-7370-8d3f-231df3303060

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1be-000e-77f7-9509-d2e761d66232
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1be-0011-77b2-b93d-aca2494bab18
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1be-0019-7043-8c8e-75a21f27252c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1be-0021-7956-938c-16b85bb11d38
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1be-0025-7833-b936-fa1ea200ea53
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1be-002c-77a4-9a84-c1189df54b61
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1be-0031-7644-9407-d95df47fbcb6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1be-0036-75e3-9f9e-7b2961c92a89

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1be-2588-7581-aa55-497dba6795b3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1be-258f-7119-b73d-c7674c9cfd09
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1be-2592-7c2c-b601-d6433d05946d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1be-2598-79f1-9e0a-2408f5b89545
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1be-259e-7986-93d4-b33d708a0159
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1be-25a7-7ece-a2e3-7ddc83a1024c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1be-25af-72aa-9fad-5bc7657d8da7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1be-25b9-7674-8b26-198fa281ee6d

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1be-390c-7e3e-8a30-4311d84ef20e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1be-3911-7e73-a184-3698f3cd0ab2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1be-3918-7a3a-9e99-11114ced59f5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1be-391e-79c4-b589-65ca36370463
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1be-3924-7ae3-a777-c9d198d5c322
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1be-392a-79f3-9bd7-eb447957b6ed
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1be-3930-77af-8af7-a624191205d7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1be-3936-7a17-a06b-0f66bc022378

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1be-525c-7d24-b393-d8a1ce1f4e89
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1be-525f-789c-9672-8795c3984f02
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1be-5266-7c13-ad97-01002f7d09a5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1be-526d-7ea7-89c2-6f2ce8791b97
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1be-5272-70bd-8b92-a4b13365500a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1be-5277-73d3-be7a-ddeb00c518c1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1be-527d-7e42-bb20-e512838308c4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1be-5284-78f1-975d-afe8c361afd7

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1be-6680-7b29-a00b-a46b88b55f86
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1be-6684-7625-880c-c64d376a356d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1be-668a-768a-98ec-7cf9b66b596d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1be-6690-7568-9a2a-a28129f40f9e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1be-6696-769e-8ff7-9f259061c9f1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1be-669c-7782-a7f6-290a1edafee9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1be-66a7-74f5-8ed5-ce0bb2bc8320
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1be-66ac-7c0b-ac6f-c1d33b71e02c

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1be-7897-76df-9ca7-1fd2d897cdb4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1be-78a0-78ef-bddc-341781a1feb4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1be-78a5-7b52-a938-020d0e4e1e99
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1be-78ab-7e95-9f5f-26ea10febdce
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1be-78b1-70f6-b3fc-107ad7407f04
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1be-78b7-7f52-8358-338348b0e729
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1be-78be-741a-aea5-2e8361a722c3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1be-78c5-7835-bf27-78658f65d158

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1be-87f2-7a40-9d02-39ac4b7849e5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1be-87f5-7697-8727-8354630a7bb0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1be-87fc-7cfc-b933-c16165442a7f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1be-8802-72cf-b964-f07cab874863
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1be-8809-7e9b-a1b7-ddf9ad1d4668
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1be-880e-7f84-9ddc-a07c6eaa74c4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1be-8813-7f9e-8f74-dbf5b6ce006e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1be-881a-7d1f-a575-f0ee43d90e16

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1be-a485-7ddd-835c-deb5ed531861
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1be-a48d-7971-83ac-046850b08e54
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1be-a491-7db6-a452-32178b145de0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1be-a495-7e41-b5a1-81581faa6a97
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1be-a49e-74f0-956a-1e6b3a8bdf76
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1be-a4ad-71c0-8c40-6c2380adf9b0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1be-a4b5-71e7-8b46-8a12768a55ca
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1be-a4bc-7968-9590-6881ad6299a8

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1be-b7cd-7e16-b57a-6b2e663ae804
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1be-b7d2-73c6-a94a-fe17bb2d59d6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1be-b7d6-7222-ad0d-08aef99bb1c1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1be-b7dd-7c18-8201-50f9c778087c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1be-b7e2-70fd-b7e2-01725c760ca8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1be-b7e9-7815-a6a9-aa574318f398
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1be-b7ee-77ba-8d3f-7577e9c14711
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1be-b7f5-73a4-814d-21760601c878

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1be-cf29-7123-982e-8235a28b009c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1be-cf2e-7814-84e5-bc4e71473e2f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1be-cf37-71ef-8b5e-8ea9038efbe6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1be-cf3d-7e21-a1bb-d595eca872cd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1be-cf45-75b8-9e4a-f12ba9427337
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1be-cf4a-7d08-856d-d767a6545181
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1be-cf50-7594-8274-1da222b6dda7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1be-cf55-7f56-b639-e494f3d26737

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1be-e053-7bc5-bf72-0f9a6adb9790
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1be-e057-772b-b6b2-8260c505d074
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1be-e05f-756f-8cd1-253a8c306117
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1be-e065-771e-b264-be9b53dbb01c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1be-e06d-75bb-b713-766386973716
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1be-e072-7324-8ba4-5291da4677ba
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1be-e078-7e7c-a0ac-c819b725e549
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1be-e07e-7e98-95e0-031baaf22b48

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1be-fe16-7d8f-87f5-442819c43384
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1be-fe1d-790b-907f-934e6f024593
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1be-fe21-7b52-b031-10ffae0a2229
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1be-fe27-7b9b-84e5-93c1129fc12f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1be-fe30-7d79-be1b-5e972b05ec29
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1be-fe35-71b3-80fc-734103509b05
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1be-fe3b-75dd-9dfd-e27a17b712df
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1be-fe41-7707-a680-b3a8e99f8ce2

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bf-1375-74da-8294-dfe9b9a2fbbe
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bf-137c-745b-9df4-6c53c7ff8414
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bf-1381-71cd-bf92-180424fd523a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bf-1387-77c2-900f-44809c891cd1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bf-138c-78db-b2f4-c1b8f7bb675f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bf-1392-746e-908f-b07a21a38047
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bf-1399-70f1-b04d-379042310f43
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bf-139e-703c-80a2-fd32bece1979

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bf-2c2b-7d72-b232-58f36da42665
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bf-2c30-79fa-bdfc-efa52bb9f2dd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bf-2c38-7e4d-9297-8a264ff67c37
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bf-2c3d-7b4b-ba28-28bc97055779
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bf-2c44-76dd-8119-37d84e3d913a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bf-2c49-74ee-819c-8286550d7a10
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bf-2c4f-7690-8c1d-a8e1f971d03f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bf-2c55-7059-b5e0-d37242496a19

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bf-40a7-7be2-8062-7aee23f38ab9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bf-40aa-7956-bd9a-02cda4d0d59a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bf-40b1-79f5-8fe7-a884026f2cff
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bf-40b7-7496-bd42-1bb5fd1386c6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bf-40bf-7deb-b622-2f8d923f5c67
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bf-40c5-7859-9b6a-6941310f2a38
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bf-40cc-7f18-9f82-fca9102df104
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bf-40d3-7a52-84d3-77c2c5857166

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bf-5387-78f2-bdfd-17843777fc5e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bf-538b-7023-a649-5dd42a36fcb9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bf-5392-72a4-a1fb-502da4d18cba
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bf-5399-706b-a544-efa6147c3b1d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bf-539f-72ca-bdfe-7a79074a00e2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bf-53a6-71fb-b258-b044eb015566
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bf-53ad-73f7-b2e7-d7271cd41252
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bf-53b4-7715-a6d7-9f73890c8b4e

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bf-7001-7088-901b-56305a396382
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bf-7005-7043-a26b-9e1fc07acd6e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bf-700d-73bc-a1dc-e5e488b2b8b2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bf-7013-7365-92f8-f75d0436d31c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bf-701a-7f96-a0f6-f6b9e1ec0eba
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bf-701f-7bee-a8e6-2db7fff86c4e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bf-7024-7e1c-8dd7-c043824d7d7a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bf-702a-7f9a-8d30-5ef9183a69f5

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bf-82c7-782e-a5c7-5580b78a6f0c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bf-82cb-7f77-a0b3-6bf7102f6561
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bf-82d2-76d1-a7db-a1971c38a28d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bf-82d8-777b-855f-d49bae789d27
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bf-82de-70a8-80be-c46f41feb91e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bf-82e4-71cf-bec8-0ff14c274d2b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bf-82ea-7c3c-b5fc-1da967334d53
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bf-82f0-7aaa-879f-dac908a6d271

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bf-91d2-756e-8d52-3d8c5986e89e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bf-91d6-74b0-927a-7296f79aa541
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bf-91dd-7625-9374-c0a603d157af
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bf-91e4-7637-bdbe-9fc3adcf0803
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bf-91ea-7f3a-a2f5-bf95a964cacd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bf-91ef-7d97-a73b-2c5df9a83b11
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bf-91f6-7426-8313-922fb52bdb63
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bf-91fb-7f05-8a2c-4bf057b2d768

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bf-9b4e-7d16-a4b2-b9be0dc8f40d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bf-9b51-7531-b9bc-224143d2c748
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bf-9b58-7842-892a-b2e42063cd4b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bf-9b5d-77c2-8cc2-011f312ca18c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bf-9b64-7868-9e69-a033d7a0cc3f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bf-9b6a-725a-8d92-198a39ca47bf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bf-9b71-70d5-80fc-74aa7ed92034
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bf-9b7d-7c18-89c4-dcbe7fb630a6

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bf-b005-7fc8-a64d-bdcf759f6a4c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bf-b009-75a0-8a6b-72f7cbe5522d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bf-b00f-78d7-b1d1-95d660c44aa9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bf-b015-79d5-a8ca-935436900114
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bf-b01b-76e7-acff-a1dc10732a93
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bf-b021-7c3c-af19-61cf530ca35d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bf-b027-715e-b9fd-714b460a9532
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bf-b02f-752a-9c21-d237868cbe42

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bf-cf6b-7e8d-8bc9-10f08be318e7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bf-cf70-78b8-889f-d0e2658cfbf4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bf-cf78-7d3a-b109-435b1e7e0374
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bf-cf7f-70fe-afd9-3c907bb40629
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bf-cf86-7d65-8b6d-c262b6577dec
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bf-cf8b-7bdd-b3cf-fac845c7759a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bf-cf93-7a80-b123-198804763271
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bf-cf98-79f7-9c51-241620a5ef61

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bf-e5a0-7a75-a1c8-e382d11fba08
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bf-e5a4-7871-8706-913d93a8adc6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bf-e5ab-70fc-8a8e-7ecf3fae41d3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bf-e5b2-75da-9ec9-225cb49389ca
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bf-e5b5-79de-982c-1c620529daab
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bf-e5bc-78f9-a252-79fa1d0544d2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bf-e5c2-7447-ad8c-b85421360f19
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1bf-e5c6-7d41-a213-8c2247dcd7c0

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c0-0335-760f-b41a-989043029053
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c0-033a-7350-88f6-672edd21202c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c0-0340-7324-9e22-4d9f46071a5c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c0-0345-7fd1-a298-56ac07e35517
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c0-034c-7001-9ded-85f9a51bb0ea
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c0-0355-7ea1-83ad-0bbbd9e28faa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c0-035e-783d-b515-ae9af4c6a8a7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c0-0364-7afa-ad12-ea86221640c2

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c0-1654-760d-b637-5cafa71bee7f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c0-1658-7897-81d7-8339e571e00f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c0-165e-7284-86d5-5670e9ad47cb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c0-1665-7991-9d62-99ebbb97a814
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c0-166b-7cc3-aa5f-cb38932427ea
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c0-1671-753c-aa58-939148bd5cc9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c0-1676-705e-8fb0-6984c5fa7875
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c0-167e-7de9-b1a7-8f113307429a

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c0-293e-7ad9-9d28-adffc0edb9ea
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c0-2943-7a56-905f-e957410d7fc7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c0-294a-7436-9f9d-ce0e3e952ae6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c0-2950-7d00-931d-6904a13dc9cd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c0-2955-72d5-9754-3bcb20d48b36
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c0-295c-7740-bf7b-9863c7a19c81
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c0-2965-7749-9719-497c95f7ad66
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c0-2970-7019-b879-cbd7101371c3

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c0-40c5-7324-bffe-ba11825f2854
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c0-40c9-7ac3-bf06-a36ae3ec907f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c0-40cf-7db9-a8fa-f469f7350373
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c0-40d5-7344-a3e7-f7020dce7377
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c0-40db-7014-93ad-536a34b8a7ab
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c0-40e0-7fee-b69f-2550a9ac1688
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c0-40e7-7e09-88bd-7bec57f1707a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c0-40ed-7963-a831-a55ed830d644

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c0-5fe8-71a9-b76d-f93fdf5a6455
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c0-5fee-7028-8250-27a742ee075e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c0-5ff3-7445-be24-15c3272aa564
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c0-5ffa-7da0-8686-6e69056fa48e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c0-6001-7fe7-ac9e-fb4a50674648
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c0-6006-7c44-91de-4ccf25d07895
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c0-600c-7fa7-a613-834b5d17183f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c0-6014-7450-8b11-ba7a192ab86c

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c0-8108-7ce9-95fc-07f66538754b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c0-810b-70c7-b68b-0b2c59fe22a2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c0-8111-7918-b5d4-b6ba4b8820a5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c0-8117-7e56-8d03-843eb605e878
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c0-811d-7404-85cc-abaa22a34375
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c0-8122-7dcc-abb4-fc7e5f784397
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c0-812a-7072-9997-4d23aa4ee75f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c0-8134-7197-9c73-14523b3736ac

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c0-9a02-702d-9771-47fe7da47eff
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c0-9a06-7c99-87c4-a3918d639668
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c0-9a0c-7af6-ba6e-b07cf572e616
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c0-9a12-70cf-8859-2aeb5cc8e2d3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c0-9a1a-7626-9589-5101928b2fef
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c0-9a21-75ee-b54e-3aa7191475bd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c0-9a27-7d94-8667-9063ebec6205
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c0-9a2e-7558-a735-77a2ae2d62c9

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c0-aed6-7a29-82e6-a37184eb1930
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c0-aeda-7993-9562-48238a0f058b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c0-aee0-7b8f-9471-29fcfb552b92
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c0-aee7-723f-bea1-00feb7796109
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c0-aeec-70ac-ae8f-14a2c4bcc78b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c0-aef2-78e1-bcec-482cbfd78e8d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c0-aef7-75be-b350-f0d474451805
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c0-af00-778b-bad3-fe9483773175

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c0-c471-7ae0-b169-94d3569245bf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c0-c476-733a-bcf7-c712bf6268ec
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c0-c47d-7215-956a-d419d613233b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c0-c483-74ed-b398-5597099cd670
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c0-c48b-7dec-a72c-8116e754407c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c0-c492-7cc6-baf0-348548e6c341
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c0-c499-7d77-9a8e-cfc9a52caa68
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c0-c49e-73e3-90bb-756b2704488f

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c0-d4a0-7c39-b5a9-49422d97db61
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c0-d4a4-7822-b171-78d34979f814
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c0-d4ab-781e-b7a5-fd2ee11f09ab
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c0-d4b1-76af-80d2-d51e2e777e85
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c0-d4b9-7fc2-8f4f-f17e3f015f82
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c0-d4be-770b-ac26-cc59295c0832
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c0-d4c4-7ae2-a796-0380ad6315aa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c0-d4c9-7fec-8dbe-57f95433fec4

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c0-eda9-764c-9b8e-6f3cba2da33e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c0-edac-7389-81fe-b86f21c9d0b1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c0-edb3-7b94-9673-521d7d82bdb1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c0-edb9-71c7-98b1-3dbd587aa1c2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c0-edbf-7abe-8308-56cd908b5251
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c0-edc6-7e99-a830-7bfa0b270a5b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c0-edcb-79ed-8d4b-5f5d0b6a3502
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c0-edd2-7377-be5a-f814a26f3b74

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c0-ff6c-7485-83c9-2f16cc5d5d45
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c0-ff70-7201-81d7-3d8196270866
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c0-ff75-779e-8b2d-99d112bf7924
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c0-ff7b-78f9-b5c1-4178aeb5ffa5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c0-ff81-7ccd-9939-563b00c37e71
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c0-ff87-7e67-82e0-83d9f0002bd4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c0-ff8d-74d0-bd1c-53cc4838f804
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c0-ff92-7353-8b7b-7fd27df6096b

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c1-1560-7410-a210-ed508c71a07e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c1-1564-7c6e-b35c-2fd31c1d90fe
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c1-156b-75e0-a6f1-ab7af1739c3c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c1-1573-7bee-b326-1ae2f5b2dfea
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c1-1579-7338-ae74-5a8a43878f89
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c1-1583-7135-9d1c-2d46409297ee
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c1-1589-72e1-af79-d5b6ed3f24be
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c1-158d-7307-81cf-b6eec4d556e3

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c1-2be6-7779-a92d-df70169d2652
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c1-2bea-72a1-b546-525dec83823a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c1-2bf0-738d-871d-d0e4265a52cc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c1-2bf5-79db-9e95-e45be6cd6a24
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c1-2bfb-7ab7-a46f-a9b9d38e22b4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c1-2c00-7ca5-8d1b-3c0f383ed272
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c1-2c06-73f2-8e7a-970a75b53ae3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c1-2c0b-77fa-93e5-526b57813e3c

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c1-426b-7948-99e8-6ee121fe9f19
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c1-426e-75b6-bce4-66fc146b2f14
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c1-4276-7025-a515-53e461a8377c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c1-427b-7a83-8a7c-63e2d9568a1a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c1-4281-7498-8480-ecb4c72ec02e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c1-428a-7394-8530-142f17c57f8b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c1-4292-7b16-b9e2-e030a0721ffe
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c1-4298-721b-938b-6df7fc2460e1

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c1-5879-77c1-abab-73b73665d704
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c1-587f-716d-a1e7-610f55e05f7b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c1-5884-7432-8477-708510aa141d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c1-588a-7d87-9eac-82ed76a0417c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c1-5890-783c-9408-5bdecb03266e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c1-5895-70bf-b933-3da473713769
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c1-589b-780d-bab1-d2bb96c458c3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c1-58a2-7452-8110-6f99fcca7ae1

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c1-6fe1-79df-89c2-4806293ee284
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c1-6fe5-7c8e-9716-8d85d998131b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c1-6fec-7c19-a0aa-3cc74631e14d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c1-6ff3-74d6-b924-0fa7f135b2b3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c1-6ff7-7493-b331-b4b14e576396
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c1-6ffc-7b6f-b94e-e82f01ad8a63
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c1-7003-755a-ad28-6fe4087d12ba
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c1-7009-7bc7-969b-a71c595a75fd

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c1-89ee-7c24-a474-e90cb53e6123
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c1-89f2-7202-b0a3-dbccc79e528a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c1-89f8-71ef-b448-ae251a2a622f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c1-89fe-7eec-b58a-163efcb93385
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c1-8a03-7579-9009-0dcef5b097b1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c1-8a0b-7cad-9167-ceda7c0005bf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c1-8a13-780b-8374-a1e5d8229fda
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c1-8a1c-7f5c-99a0-07b9c81cdb1c

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c1-a1ca-7dd2-b63d-0710f86e7d06
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c1-a1d0-7178-a105-e7577be2523d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c1-a1d5-7494-9b10-221773325aea
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c1-a1db-79a7-b5d0-c467010a72dd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c1-a1e0-7825-9d7b-48a1b7eb1b9d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c1-a1e7-732f-8405-01f29e60fa4b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c1-a1ee-7678-9ee2-18746513eaf2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c1-a1f3-7afd-ad60-0420102ac684

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c1-b491-71ae-b0cf-a6f2dcebe73f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c1-b496-76a7-b7e5-f2deca091ee5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c1-b49c-7d7d-b5ba-039f01530cf2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c1-b4a1-74f1-8285-210c72a89924
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c1-b4a9-73aa-888b-3048bb3f3901
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c1-b4b0-727e-81a4-87a9cf2d93a9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c1-b4b6-7c3f-8336-f5a1d2b74b64
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c1-b4bb-72f6-948a-8172086ef3b7

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c1-cc28-7b9f-ac4b-5a68b6de9552
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c1-cc2c-713b-ad70-c54298177a4a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c1-cc33-7f0e-bcd6-16e5db37453a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c1-cc37-716f-b736-c8629775a467
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c1-cc3c-7251-8fab-dc1aab86bab2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c1-cc44-7810-86bb-d031b87a3516
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c1-cc50-753b-9831-9b77a9fbfdb8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c1-cc58-7df2-ab47-d0171f2baef8

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c1-de16-7425-a7bb-e2f1944678a4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c1-de1b-785f-8777-52a75dc90391
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c1-de21-7fd9-bc46-355e936bd187
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c1-de27-7d93-8314-067e6cb46469
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c1-de2c-760b-82db-b443c2c81688
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c1-de32-7d1e-8600-8284344524cf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c1-de39-766f-b862-a58e5e7f0c41
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c1-de3e-733d-a1bf-943c9815d311

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c1-f02b-7c92-8d1c-199efd3b741e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c1-f02e-7dac-a070-a2c377a3fe41
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c1-f035-7e43-8f08-148353b9a70b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c1-f03e-7fe2-956b-5d5379a0a845
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c1-f044-7fa7-b478-fe2e4f2b690e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c1-f04a-7ac3-8155-7d378fcc739f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c1-f051-70a8-8d3f-6dcc618ef8d9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c1-f057-7cb4-81c2-c717ac2aeb48

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c2-06e8-7a59-8ff4-bb41eb0d1ed5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c2-06ed-7222-b722-1f43932cbdab
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c2-06f4-7574-8995-f332bdbe4fb6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c2-06f8-74c6-8404-cd96f322b67b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c2-06fe-78df-a737-7d51b813b439
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c2-0704-7e9e-98a2-89ae3fedd19f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c2-0709-77f6-8167-14571577c121
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c2-0710-7027-a2e1-447d581faa8e

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c2-1ddd-78b5-9f11-551dc3879122
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c2-1de1-7a2e-ad87-a699303b7f60
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c2-1de8-76c7-8f01-a785ee554bd9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c2-1def-71fc-8e20-ab22c2c63cb7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c2-1df4-72a2-946c-61cc0ca0625c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c2-1dfb-7cc7-a5cc-354e6f4dfbd1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c2-1e00-7401-a057-6563a1296bb0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c2-1e07-7025-aec1-2a3e284c2759

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c2-3451-7b82-af96-734f1f39a44b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c2-3455-74a1-8c7a-965af79a3e3c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c2-345d-7a7e-8db9-7b0ca0314358
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c2-3462-73d0-9195-19f4a126cf8d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c2-3469-78ac-b2a1-6ab8ef9c428e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c2-3470-73a8-8511-56a4016c2278
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c2-3477-7bd4-b4ee-81dbf5cd1719
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c2-347c-7b82-b18b-c79c6a1b7443

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c2-45b5-7026-8e77-70547cf74e92
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c2-45ba-7a6b-ba16-05033636f735
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c2-45c1-7b4a-9fd3-b875f868623f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c2-45c8-7016-9ccd-6934850d3ddd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c2-45ce-7f5e-b4da-834581a5e5ca
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c2-45d3-7865-8c3a-f99755cec12a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c2-45d9-74b7-856c-86337292c8cb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c2-45df-72aa-b1b3-d3ddea520331

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c2-5fa7-772e-af77-bd55b3063d37
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c2-5fab-7133-a3cb-19541bb73433
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c2-5fb1-7c1f-acdb-379fe302e011
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c2-5fb6-727c-8226-d384cddd1159
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c2-5fbb-7cdd-9423-483bb7a7f4e5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c2-5fc2-7ba0-a20e-45bb56eb35aa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c2-5fc8-7f41-8779-9a6c973dfec1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c2-5fce-74b9-aa9f-b4dc6d0e0470

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c2-736e-7e2a-a2b3-761b1d875c55
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c2-7373-73e1-8d9c-c0a981429f6d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c2-7378-7f84-910e-332c03641bb2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c2-737d-7d8d-bfec-fec3b6035071
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c2-7383-7350-9560-e6aa33639f59
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c2-7389-7aa3-a7ec-9daf8e04069b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c2-738e-70db-b58d-d7de90b43541
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c2-7394-77dd-914f-483cb558d291

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c2-889c-710f-addf-a265dbe9e87f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c2-88a0-7243-ab6c-d59f26fa46e5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c2-88a7-7dde-b462-aaeec3d5a627
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c2-88ae-79f9-9e9b-ccecfbf20c09
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c2-88b3-7346-ac0c-0e4a4d8d8620
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c2-88b8-7397-a6db-ee31a77be327
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c2-88c0-78ac-a4de-587ff6458861
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c2-88c5-7e4a-8853-751026266095

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c2-a656-70a9-a3e6-dc59492f4e96
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c2-a659-7224-b40d-05370289b7de
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c2-a661-7d6e-ada9-34f9e3b7f144
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c2-a665-75be-8d34-b120d2e46289
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c2-a66a-7b9a-acb6-5e03c13716dc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c2-a676-7a77-81ea-d8e038f58b8b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c2-a67d-7b9e-a1e4-7e0ae0e7911b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c2-a687-74cb-bfe3-66a16596ea71

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c2-bc8f-7960-ae38-451d6903d398
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c2-bc95-7865-92b8-74a55e9a01c6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c2-bc9b-7bec-a44a-cdef56a23a19
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c2-bc9f-70a8-b70a-a8d2700f6748
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c2-bca5-7317-b2d1-1f144045a620
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c2-bcad-7939-8317-97f1111e8f78
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c2-bcb3-77d6-8dae-c4330777f2f8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c2-bcb8-7d15-b8ea-54586ebd8245

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c2-da8a-7352-8a24-311c1295dad3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c2-da90-71c0-b621-53744c203e7a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c2-da93-70ae-96b9-42f5d1b65e7f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c2-da99-7171-afff-9c1f0ec2e493
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c2-da9e-780e-b8e1-c922b978927a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c2-daa5-7e91-bfd7-1b49669ffdf1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c2-daa8-728e-8042-5279ef27faed
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c2-daaf-7f78-b987-bebb56817512

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c2-eab4-7dc9-8a44-05621ded92f3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c2-eab7-7607-b470-c241665855b0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c2-eabe-76f0-bfc0-b9dbb485a3a2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c2-eac3-791f-aafb-18e973a4b62e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c2-eac8-707c-b28e-4deed1508be0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c2-ead2-770e-b3e2-375d57924322
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c2-eada-7f72-ba9a-f56074494d75
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c2-eae1-7cdc-beaa-d36977317648

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c3-0e4e-77b1-8d60-bd873f0cda47
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c3-0e53-7b6e-82f1-8c7a16b41468
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c3-0e59-7575-9926-77ee258fa4ad
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c3-0e61-7da8-9fa0-7b797aa00c84
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c3-0e65-7a51-a476-be9c8951d97d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c3-0e6a-77f7-9528-7cd1adc6d26b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c3-0e70-7afb-bf4c-db61246f25db
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c3-0e76-754f-a445-cd4e8de4ae79

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c3-2833-7679-9a2c-b839dfeb4fc8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c3-2838-7164-8415-2a192ee7a38e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c3-283f-7d97-9f57-240da250975d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c3-2846-7f77-85cb-c696df3393fa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c3-284d-7c2b-bf65-55641b1cfb7c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c3-2852-7fe1-80f6-dcffe433fc81
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c3-2858-7d58-8c90-72fc3c7f1dcf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c3-285f-7f28-8b1a-079b6f807f8a

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c3-3f68-7517-9cad-ffb7de7575f7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c3-3f6b-7967-b25c-10f094cb4f8d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c3-3f72-76bd-9256-120380b7999a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c3-3f79-7bc3-9583-e4cd5efd4fe3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c3-3f7f-7564-8a1c-009d597ab246
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c3-3f88-7ab1-83ba-4de78369847e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c3-3f8d-7991-913b-2f0f3bda1109
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c3-3f93-7346-84c0-0242881ab0b1

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c3-544c-70c7-9746-7fbc9adec33f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c3-5451-7f5a-9eaa-f8f89e46202d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c3-5457-7572-bbb4-337ebacd5e99
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c3-545d-7832-a2e8-904f9791e4ac
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c3-5463-736c-bbe2-601f9ff993e9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c3-5469-7f61-8775-95e28e5d4aea
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c3-546f-7391-8fd0-b48e02ca33c5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c3-5476-7333-a446-e19638e5f7e7

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c3-636c-70e7-808d-e41ae7661311
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c3-6370-72bd-a5ba-6426425771b7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c3-6376-755d-82ab-f8531acc9c68
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c3-637c-7f0b-bcf6-70dc514937d2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c3-6382-7cc2-a6d5-bc18a945b9ed
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c3-6387-70f9-861f-44aeeca5c0a7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c3-638d-709d-9fca-e3824b5eaa0c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c3-6394-7a32-afe7-b86b3b68bcaf

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c3-7391-743d-abb4-76ddf7e045b4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c3-7394-7508-a172-a79ce340848c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c3-739e-7e31-80e5-820ad5602980
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c3-73a2-7bd8-b684-f4131e7dc24b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c3-73a7-7699-b335-fe8955b18672
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c3-73ae-7f16-8127-a39c39b4a43a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c3-73b9-7526-9afc-7b9205be7834
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c3-73c2-7023-b28c-c8f7eb153218

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c3-89b6-7673-85df-5a1b287e52c8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c3-89bb-721c-a6bc-66776bb46b17
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c3-89c3-78f8-8b29-4615d8b63aa2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c3-89cb-7540-bf3f-a4c7a2de597e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c3-89d0-7044-804a-6c8e32a190c9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c3-89d6-7e4f-afaf-080e820f58e6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c3-89dd-768e-bb24-62f68b92fc8a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c3-89e2-7163-a529-ab19da7d433e

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c3-a09f-75e1-bfb4-5024fac19d94
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c3-a0a3-70c6-aed7-8f34d4d4f977
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c3-a0ab-7f73-b0b8-afbadfc5213d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c3-a0b2-7844-887f-b7350636716a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c3-a0b7-7120-b2e9-6645a106e767
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c3-a0bc-75f1-b151-28c97b201064
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c3-a0c2-78ab-8c1f-3b12df98b450
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c3-a0c9-7ca7-b595-b181997f454f

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c3-c092-7ee8-84ca-19831d701472
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c3-c097-74d1-a5ef-05b8d33331eb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c3-c09e-7330-9d70-371eda869daf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c3-c0a2-7286-a1d8-1a1ea82383a7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c3-c0ad-7780-b965-f082f1fc0d75
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c3-c0b3-7ef7-bd38-2edaf54db735
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c3-c0bc-7abc-9a43-daf0690759ba
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c3-c0c0-7840-b234-c0387c1e1553

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c3-cd3b-7cd3-a743-d5c975d85585
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c3-cd3f-7822-930e-1feea5a5032c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c3-cd48-7600-a82f-743479409811
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c3-cd4d-7288-85ae-bf5c6259de47
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c3-cd52-765a-bbb6-0f288da517d9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c3-cd57-70ab-b531-0d0b9de6eeff
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c3-cd5d-73f6-9a22-5a674b4f82aa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c3-cd63-7590-9b36-5aa910b4273f

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c3-dfac-7408-9596-bdbd5a3948f6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c3-dfb0-74fc-80ed-acf699c686d1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c3-dfb6-777b-83ea-d9c27eeb46e6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c3-dfbd-7701-8953-31ba6b917c76
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c3-dfc2-731d-aba6-f09f0ddb1e1c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c3-dfd0-732e-b249-8e313918b009
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c3-dfd5-7f35-892b-8513ddff66db
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c3-dfda-725b-af5f-d4c88d24dd99

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c3-f637-704e-89ba-fd0a36e06e59
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c3-f63a-785b-a497-356dd91d5f46
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c3-f641-7a39-a0d3-b1112c4dd5a5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c3-f648-720c-96aa-a734fee783ae
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c3-f64d-7eb7-8db0-18716d7c61c7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c3-f653-7e7c-9f41-34e76613f7fa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c3-f65a-780c-9869-b3eed717b092
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c3-f65f-7428-9a51-e5b28a145241

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c4-0e9e-7476-875c-3b0e3dadba90
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c4-0ea2-77b5-b0e0-52868afbfa52
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c4-0ea8-7a14-b81a-3ac1a62fe85d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c4-0eaf-7654-b5c7-7197d12e5a22
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c4-0eb5-7cb3-83ac-408aa64b8368
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c4-0ebb-7bd1-ab72-aebc709ef20d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c4-0ec2-723b-8b77-1bc1481b7d1c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c4-0ec6-73ca-a3ba-042bbb456f66

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c4-2197-7114-8b80-a98777837723
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c4-219b-789e-b55b-82b6633d4272
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c4-21a2-7f8f-9959-65bd7a454df0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c4-21a7-7219-9f93-1c84c891b7fc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c4-21b2-7d11-910c-63495cfc0ce1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c4-21b7-7414-b0b0-e2eac55a2642
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c4-21bf-7a89-a0cd-ea53fa7d4102
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c4-21c5-784e-963c-c48210ab381b

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c4-32b6-7feb-ab16-11dbbb5c4a6d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c4-32b9-7cf5-bdd6-55b56ee5da94
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c4-32c1-7f7e-862d-e777695cb919
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c4-32c7-76de-90bd-b5bdc0009a13
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c4-32ce-71b9-954c-643498801dba
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c4-32d3-7e92-9071-5385b4015cd6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c4-32d8-74d8-90ac-7f0854e3260c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c4-32de-76a9-906f-0938956a3e7d

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c4-4e9a-7840-98e8-895a00949a68
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c4-4e9d-7731-aba4-05198a1bf396
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c4-4ea4-741d-a90b-50f10e9bb9b4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c4-4eab-7fbc-bba7-a761900cf608
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c4-4eb0-7248-9331-0d92534090a9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c4-4eb5-7aa6-a469-d157e9ed17bc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c4-4ebb-77a5-8fd6-d742b2ffc73b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c4-4ec0-7213-bd49-0ea128e9f08a

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c4-67ea-7e7b-abdb-40c7380c0e76
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c4-67ee-71c4-83dc-6ef13aa2a1d7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c4-67f4-7737-9647-0168657573b4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c4-67f9-73ad-ad99-d3258f3c4737
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c4-6800-71f5-b132-b485cf87f6d8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c4-6806-7472-8dff-aec99df77253
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c4-680c-7ce1-8a51-bdfdac6458de
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c4-6811-78f3-aff7-b5e02b4691bb

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c4-7c8c-7e94-865f-017416364ee5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c4-7c90-7dff-891a-c232a1ed8b66
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c4-7c96-7a28-9fef-7e54bfc68c12
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c4-7c9c-7d6c-acef-0885797919f3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c4-7ca3-79ba-9a97-f9646ae60379
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c4-7ca6-7bac-bad8-0e96b709f506
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c4-7cab-7e6a-a2b6-903c3e5f4181
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c4-7cb1-78c5-aec0-9c50488f1df9

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c4-8f05-79c2-b85b-2cbe2d8c12f3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c4-8f08-7b81-85fd-176b852158c7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c4-8f0e-7b73-9103-46feecf18511
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c4-8f14-7781-8dab-b79a2841a8a3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c4-8f1a-7397-8a0f-a33f789051b8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c4-8f1f-7cc6-8eed-1533798a92c7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c4-8f26-7c27-8a7e-fa86c09700f8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c4-8f32-7822-aeb1-ad790820ecf3

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c4-a00a-7fea-9830-2255ee941dc9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c4-a00e-73ba-94a1-7e4f82e60be4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c4-a016-791c-8fe1-bebfd7925396
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c4-a01b-7d01-9183-bddb2e56770f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c4-a021-7bc7-8815-b3eb434cc037
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c4-a027-70d4-8619-c818bf2ecafb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c4-a02c-7478-a7f9-a47357106e2c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c4-a032-71a4-b3d4-ba8acea6d462

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c4-b2aa-78bf-9460-eb006fcdc27f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c4-b2ad-7342-813b-56d78583f5e9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c4-b2b3-72ef-9ddd-f3640e53474f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c4-b2ba-7080-be16-440f65ad07d2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c4-b2c0-747e-9da1-aed021b3b39c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c4-b2c6-76ab-bd2d-0652de822a28
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c4-b2cc-7c24-9a73-6e411026eba8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c4-b2d2-7f20-a828-adebb3b3939d

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c4-c71c-7a4f-a35b-88cb81dc64fc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c4-c71f-719d-ba77-83eb73aa89f5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c4-c727-7ae2-837d-b019dd312211
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c4-c72d-7dc8-8317-97d277190a41
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c4-c732-73d1-9b06-619df6a0b227
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c4-c738-7c53-a421-d8acfe024117
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c4-c73f-7a6d-a57f-7d2589d334c1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c4-c744-719e-8e96-4d8038e483e9

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c4-d9b4-75a3-948f-8960efae1b85
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c4-d9b8-71e6-9226-af16c8dcf6e4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c4-d9c0-7372-a3ab-198fb01709c3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c4-d9c7-7c93-81a4-147a97b3b386
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c4-d9ca-7dd8-b177-4fd912262c8a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c4-d9d5-7249-a463-f4b2c2fa5b7e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c4-d9dd-73c2-a796-81c6bef13be7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c4-d9e2-7013-9dd7-8deb09e23da6

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c4-ed74-76ff-83b9-f7c2d71b0ffa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c4-ed77-7b8c-aefb-b5f57c87a1ad
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c4-ed7e-7c46-a9cd-ddbb130fa714
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c4-ed84-749a-b508-5ecb34f6fe8d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c4-ed8b-7600-a42a-176c60c61f02
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c4-ed90-7d15-817e-6bdfb41cee1e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c4-ed96-7c17-bfac-41e564089b6f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c4-ed9c-7834-a47e-0887e14dd2fc

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c5-0671-758c-be1f-8560b3eb8a40
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c5-0675-7b54-a8d6-6d5b85242748
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c5-067c-7fde-9ade-534aeae4e91c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c5-0680-73ca-9499-689445a3ce57
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c5-0686-7d2b-8502-412394b77a56
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c5-068c-7d0e-9df8-ff8b12beb0e4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c5-0691-7502-b9f9-68c2a9c2acb5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c5-0698-7987-85d9-d9eda729882c

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c5-2422-7600-819a-c6bda3097f55
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c5-2426-780b-a5de-b81b55716479
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c5-242c-71a0-8e59-08b9dca8b3db
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c5-2431-7140-8011-b3814d9c5b95
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c5-2437-7850-a0f9-90b64ddfb934
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c5-243d-77fe-8628-db0faad7aad1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c5-2442-7ae6-a76e-200a0aecc32d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c5-2448-7ad2-8eba-a93d2d64e9c1

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c5-49c5-75dd-a18b-ea726fda79d3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c5-49c9-72a6-bd90-f944dea1314f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c5-49d1-73c9-b360-0a67d1219521
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c5-49d7-7307-8a37-7404d2473224
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c5-49df-7f1c-a4eb-073cd5a935fe
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c5-49e6-7ebd-a230-5ba867b9fb88
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c5-49ee-7682-8cf7-b2868b075777
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c5-49f6-7e4c-9a85-4d5b91cf4e1d

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c5-6423-769a-99e5-34ee2a9f1944
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c5-6429-79d5-b5f5-c5fd31189ee8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c5-642e-7a7e-a0f0-67b60825dff5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c5-6434-7d4c-ad88-741dc06c27bb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c5-6439-7712-b047-55ee7c61c7fb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c5-6442-7a16-abb5-2a89f5cf52f2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c5-644c-75d9-aa56-f7ec99a4691c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c5-6453-7754-bbc2-d479582ba7f6

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c5-79fb-7a85-b70e-6bdf88d5566b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c5-7a00-7f09-ae66-15e64a1d3a50
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c5-7a05-79f3-9d76-59d041425a0e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c5-7a0b-717f-8acc-7bde98de71b6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c5-7a13-7dba-b309-96d7a051c369
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c5-7a17-7da8-854e-e547f2f13dad
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c5-7a1c-7f12-8743-2a967e453aff
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c5-7a22-782b-b265-e700e9adffcc

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c5-8d37-7b04-880d-a0e8ae3e69ff
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c5-8d3c-701a-b96c-21c103ba5901
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c5-8d42-7849-9adf-7ce171019389
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c5-8d47-7e8b-b0bc-53b0088ca633
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c5-8d4f-74cf-9bad-c23822d9205a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c5-8d54-7756-8059-88f8cbc37340
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c5-8d59-7e41-8e87-dacbf536f9ad
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c5-8d5f-7d16-b012-a2f962a834fe

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c5-a937-723f-b5bb-c93088a7ef05
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c5-a93d-7849-a64b-af3a52b1b318
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c5-a942-73cf-93f1-3b7d350977fa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c5-a948-7b39-ba51-d724ebed6c7a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c5-a94d-7f90-85db-5e151eb73d7d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c5-a952-7e17-8788-b77bc0de2424
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c5-a95a-7a28-8538-693bcb8fc67f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c5-a960-711c-9d02-addc494bc761

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c5-bf7e-7d5e-9c43-fd7a3c497c03
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c5-bf81-7784-8f41-4bff43745d1b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c5-bf87-7f0c-b16b-639fd45ef85c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c5-bf8d-7b23-bb3e-bc4fe9e55a2e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c5-bf93-7a32-b564-73d2ed703d43
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c5-bf99-7401-aa06-4babf901ac8d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c5-bf9f-7d33-9288-580cc640979e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c5-bfa4-719d-9fd9-78d319e65c00

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c5-d503-76c2-b0ab-bb1db62d7721
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c5-d50a-7450-8276-52279743a124
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c5-d50f-792b-9a02-7fea5554b881
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c5-d514-7fdc-8f5b-2f87da2cf9de
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c5-d519-78d4-9b4b-183a23c06d49
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c5-d51f-7519-ab33-54ec056f0ce6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c5-d525-7390-9008-9be382168f06
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c5-d52b-7134-b7ae-2cbb5dafcf89

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c5-e5a7-7bf3-97bd-308d124f46bf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c5-e5ab-78c6-a82d-d6441003b5fd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c5-e5b1-709b-b054-e9886454673d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c5-e5b7-74f6-9837-4df3935e58c8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c5-e5bd-76da-a80c-4ee782540811
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c5-e5c2-7caa-a3a9-7aee10a5d15c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c5-e5c7-720b-87f6-ae66214ec483
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c5-e5cd-79ed-942c-f624e283853a

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c5-f665-7c4b-ba4a-0c55821137b1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c5-f66b-7888-bf5f-532b907e5d7b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c5-f670-710d-b2df-f854e8941c8b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c5-f676-7c63-a78c-3db0a1c102fb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c5-f67b-78f9-afd3-7796eae96a50
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c5-f681-7e71-b950-cd4c62547106
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c5-f687-7571-85b7-3267277ae4d3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c5-f68c-7119-aa44-c51586d16fa4

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c6-1181-7a81-b404-be614296441e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c6-1187-7b6b-9ed0-83ac7d1e1544
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c6-118c-7b04-a947-7d117eafa592
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c6-1191-719a-b906-32c9b0404a96
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c6-1197-700c-85c7-0107526ad8ad
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c6-119d-789c-8446-9acaeabc2ff0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c6-11a3-7db0-852b-bf6fc2e5b1bf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c6-11a8-7e53-b3c8-50238ac10bca

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c6-2544-7156-9f04-d15c72e78803
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c6-2549-7ab7-b254-f261966d6634
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c6-254f-773b-927f-b3f186d3fca0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c6-2554-751f-a564-d1f4ff256a75
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c6-255b-75a6-b1b2-6ef5d148e29f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c6-2561-7490-a622-be4f039a4ce1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c6-2567-7a09-9e54-445ca7ac29d1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c6-256c-79a4-9383-2c7d9dc4e019

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c6-4a6c-728a-9531-d778c42c7d7f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c6-4a70-72cb-a9e6-b9dadc783e3d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c6-4a78-7e1e-8262-d9e4e276a9b7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c6-4a7d-7e1b-8b85-c060b559951c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c6-4a84-72a9-9fb1-240db4be1e86
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c6-4a88-75e8-9d70-03a4aab854fb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c6-4a90-74a2-97b2-590a00234028
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c6-4a94-7b9d-a9d6-8bd8db025259

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c6-59ee-753a-8d0f-db543f4cd1c6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c6-59f2-71fc-be33-9b527544037e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c6-59f9-7895-ad98-88893930dde5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c6-5a00-7817-8cf5-6ada46544040
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c6-5a04-75a7-95ec-b20725609544
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c6-5a0a-7668-aeb0-87dbb64402d2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c6-5a0f-7d21-8687-819590e0a51d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c6-5a15-72ad-8ae2-72d90c33dca4

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c6-6ef1-73c3-a8bb-a52f150c609d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c6-6ef4-7ee0-8abd-60cdfed9e428
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c6-6efc-7ad8-8be9-0e4e28aa95a4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c6-6f00-7f7d-aa41-1ecb9e3d7bc9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c6-6f07-787b-89cc-8c219b6ac00b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c6-6f0d-7d8c-b931-4103d1b325c6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c6-6f12-7a73-a44d-2574c41630b4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c6-6f18-71ff-b1ea-6c0691410a70

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c6-8256-77ae-abe8-37058ad826b1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c6-8259-77ee-89ca-9550854aa14f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c6-825f-7fff-a44b-fe92e76d7947
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c6-8266-757e-9d59-1128e2ac316d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c6-826c-770f-98db-ff33df482873
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c6-8272-7310-ad96-bbbdbcea4b84
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c6-8278-76f0-abb2-0c312cc977ea
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c6-827d-76e0-a1cd-bbdc874b002a

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c6-9bf8-71f2-98fe-7d7625a9c150
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c6-9bfc-7b73-8953-0c6836dd658e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c6-9c02-7f2d-923c-4e083dfb9a54
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c6-9c07-71c7-bdde-122528042391
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c6-9c0d-7b51-9cc5-0f9715336a20
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c6-9c15-7b99-9935-9301eca1e307
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c6-9c18-705e-bd7a-e1208864b2a7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c6-9c1e-750d-b578-3b59a8df0716

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c6-b1b7-72bc-8361-1ae3df660d99
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c6-b1ba-7800-9617-d4dc71a457da
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c6-b1c3-72f2-a7f2-eae2d0f1a48e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c6-b1ca-7022-8dc8-89903c269c85
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c6-b1d0-7f88-bbb3-1277826a0923
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c6-b1d5-77c3-87a2-0145f4c5b2dd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c6-b1db-753d-abc8-b73834bb6f0d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c6-b1e0-7566-9b45-bd0f27b8b083

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c6-c401-71f5-99ef-b4bd9746558e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c6-c406-7c5c-940e-46d23b24e19b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c6-c40c-73a5-9366-ee671ea477d8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c6-c411-7484-8cf8-15171e7c8d44
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c6-c417-71de-8ce8-0240c7baaf0e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c6-c41c-74ff-8a23-21d4151ea7e0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c6-c421-7af1-ac57-828546028885
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c6-c427-720f-851a-b17e4d7239d7

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c6-e233-7333-8732-183a9769218e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c6-e237-736c-a918-b5a7f03cf9c6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c6-e23d-79bf-a1e7-15adff4356b1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c6-e243-7f19-a6cf-5fec1a48abbb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c6-e247-7b53-ba8a-40b591f62850
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c6-e24e-7d04-a054-96ff5e9ba81b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c6-e254-7dc0-81b8-74e41a729a02
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c6-e25a-74c8-ac36-456bb27839eb

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c6-f94c-79a6-84a0-a7b57603d122
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c6-f950-7846-8c0e-7d3fece748fa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c6-f955-7b58-8866-c6039d942a0e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c6-f95b-7e42-9fa4-b1f0fe54df0a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c6-f961-78e4-b9d1-091e815eb77f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c6-f968-758b-bcc7-94c9b5a4b78e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c6-f96d-7d96-9cf4-9bd079820232
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c6-f973-7da7-81bb-7e332c60d088

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c7-0b55-7a25-ad92-61bf1f81b1d8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c7-0b58-76d0-8d25-ade2c0420ce7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c7-0b5f-7e37-ac36-18ea0ffa1228
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c7-0b66-7d82-97ea-3928b7070d8b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c7-0b6c-709e-ae01-2ed77002c181
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c7-0b73-7a9f-8e1f-a880a141b21f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c7-0b78-7f90-94e3-2a7256951c00
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c7-0b7e-71bd-b650-64bfec416a0a

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c7-1f6b-7589-828c-8a85c8f5c6f0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c7-1f6e-7530-9d62-544e2bb76d99
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c7-1f75-7091-8bee-ba5370d0a152
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c7-1f7b-7f58-9a47-052cdf9b6980
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c7-1f81-7ce1-a04a-f355170af250
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c7-1f88-7a52-8f66-46c6a0e7d428
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c7-1f8f-7025-8141-c9cfb823a9fd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c7-1f93-721d-a3fb-666a2eed17b7

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c7-38e3-7376-b47e-5afa08c28264
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c7-38e8-7b3c-885b-f921d6628a8b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c7-38ed-729a-ab26-38a24f1b80a6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c7-38f4-734f-892c-04b2dd754ec4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c7-38fa-7cfc-9b08-6064e225fbb0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c7-3902-732e-909f-c3de677fa955
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c7-3909-7ab4-81d4-36b6152a1b7b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c7-390e-7372-ad8e-c358a9db8648

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c7-43f8-7fae-b5ab-e5b3304736af
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c7-43fc-7247-bc10-663591aa1dd1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c7-4404-79aa-8bfc-5a57e8dfccc8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c7-4409-74e1-b15f-489917efc20a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c7-4410-7f9f-b84b-784672f4b88c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c7-4415-7d7b-ba17-141627612378
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c7-441b-7464-8592-fc48b56b2bf5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c7-4420-79d4-ae27-99e42d798080

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c7-5d9d-7fcc-85ea-f301fbb752e5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c7-5da1-7834-a5f2-efd3b56dfe6f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c7-5da6-755c-890a-21f13f801e5a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c7-5dac-7540-86d3-102242a196a1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c7-5db3-70be-8682-99cfa0e2f31c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c7-5dba-75a1-ae48-c531bb6394c9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c7-5dbd-77c0-92c3-180188b638e0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c7-5dc3-79c7-8c79-5f7b049be471

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c7-7335-7ade-bf97-293bddf24a18
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c7-7339-788c-ac34-001e9d161d09
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c7-7342-7549-b3df-ea2297c5ef84
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c7-7349-77bd-ac28-d911e2d2c8ae
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c7-734e-7d6e-94ad-628e4e0aa56e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c7-7353-7bfd-a365-161474db2c6e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c7-7359-737e-a632-8fd6c3fdc967
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c7-735f-79ad-8dde-e3a60d8276ea

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c7-8667-7ed3-8de9-7f9cf5b04856
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c7-866a-756a-85a3-ccfc47e656a2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c7-8671-76bd-af1e-850f154dc29e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c7-8677-7ab1-ba2e-b295d12aea72
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c7-867d-7efe-b121-6ce63353b7f9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c7-8684-7c36-ae40-edf1f21b26ca
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c7-868a-71a3-86ea-2fa92869e554
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c7-8690-71aa-b694-2a4437bb11c9

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c7-99fd-78c0-a981-5f401f3b9a27
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c7-9a01-798c-b85b-ef3cc355205e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c7-9a07-7c1c-92c2-faefc63f5d25
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c7-9a0d-7ab3-8b97-174da214f3a7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c7-9a14-76d9-b913-483d68ef709a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c7-9a19-71e0-a946-20813376e6f4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c7-9a1e-7d87-96f4-b47a7b8e6527
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c7-9a24-74bb-a0b5-e4bcd174566e

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c7-b92e-75bd-b938-ce98e4584912
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c7-b933-7f8f-b919-2df20c19f31d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c7-b93a-7730-970d-cf3e2fe36f35
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c7-b940-7c73-bda0-f6950347180a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c7-b946-7933-b6d4-b3eb8eaa1c1d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c7-b94c-7df0-9a36-27ae2bf5c2dd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c7-b950-72cf-b22d-336f66a3c68d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c7-b956-7b87-b56c-2fef7ea775e1

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c7-d6ec-7781-b01a-d1ab42ca5444
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c7-d6f1-7587-8b5d-dbf73d6311d0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c7-d6f6-798e-aa0c-00251e042b55
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c7-d6fb-78fa-8448-2fccc19d6ed0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c7-d701-7b51-ab58-4a3b84f28d00
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c7-d707-76c5-9c5d-168b8b85582b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c7-d70c-713b-8dc5-f099016f582a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c7-d713-756a-85e3-571ccdfd4dcd

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c7-edbf-7bee-b3c9-b06fc6e8ed11
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c7-edc3-728a-b8f4-8a1db03b0692
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c7-edca-7ceb-99d8-9eea3cf2651f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c7-edcf-7166-899e-53ef0993e889
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c7-edd7-7adb-a111-fb7f766ec922
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c7-eddb-7973-9e5d-f121f076d82e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c7-ede2-746e-af16-94fb4e700113
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c7-ede8-7029-b8b5-af4c9d998600

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c8-12d3-7d57-a85f-247c76addcab
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c8-12d6-785e-87fc-ab8d5bae0184
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c8-12dc-7b93-afcb-c0f28e3a42c6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c8-12e3-733b-8714-b7384e346f99
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c8-12e8-76e7-bdd8-5252c140ffc8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c8-12ee-78cb-9d06-df08ef9968f7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c8-12f4-7961-afc9-859fce7aa762
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c8-12fa-7364-b148-c842f52a5e2e

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c8-2ead-7534-85dc-fd3c8a366611
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c8-2eb2-7c90-a172-848cc6b94686
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c8-2eb8-741d-b9bb-8ab820f593ea
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c8-2ebe-7461-8bb0-c31376d5f3f3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c8-2ec5-742a-8a94-ca98f5375083
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c8-2ec9-7f27-b666-adc6f6126ec5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c8-2ed1-7572-b7ec-e54e4748f89b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c8-2ed5-7a65-9ae9-cf3f62440d91

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c8-39ce-7286-a728-2c44c8ed877d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c8-39d1-7a75-9338-cd3742251e2d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c8-39d9-7d90-b248-5a22d47e7a54
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c8-39dd-7747-a066-4f7627060353
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c8-39e2-7e4c-b4e2-8393ec1ac4eb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c8-39e9-7aa1-ba8f-639cec52eae1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c8-39ef-75a9-a308-edc6fa6ec385
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c8-39f6-7567-b2ea-7fb3de506e66

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c8-4a91-7a1e-8394-b605b5d6ab97
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c8-4a95-78da-a83a-5ca9b57c0123
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c8-4a9b-77be-af2b-ec6fcc10121b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c8-4aa8-745d-8752-837a83d52539
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c8-4aae-733d-b19c-685e14b1a891
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c8-4ab3-7e51-a8d2-a71cfddb84ed
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c8-4aba-71b7-9dcd-622e0adf5950
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c8-4abe-700b-9d78-9053b6f4bb5b

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c8-5d36-75b9-8913-f841037184c7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c8-5d3a-738c-9a49-296ebafbce79
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c8-5d40-7d1a-bf63-38024c0ffc3b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c8-5d46-7d2d-8eaa-9a5b8f00a979
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c8-5d4c-725f-9b4f-176ee1f12af7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c8-5d52-7713-b83f-f97ae13a49f4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c8-5d59-725c-989c-c3109021b0f6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c8-5d5e-7a98-815d-46f1137630ec

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c8-76b6-77c7-bc5b-0e9ebc35e281
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c8-76bb-7790-827d-189e41bb531f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c8-76c0-7e91-b42d-3bcbd5699ec3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c8-76c7-72e3-bbae-74218088ce10
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c8-76ca-7a65-9472-e84b95bfe294
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c8-76d0-7971-bc9b-dc52ec5b6ed6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c8-76d6-70d3-9c05-fadf8ec580e7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c8-76e0-7a91-848c-cdbcf4a36f03

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c8-8a40-7ca3-9eb9-16402d6ab41b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c8-8a47-735b-877f-9357d335ad8a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c8-8a4d-7474-8489-578645ed3335
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c8-8a52-74aa-ab50-675791f00a87
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c8-8a59-7dbf-8f68-da319752db7f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c8-8a5e-7bc4-9a2d-407e87f8f74a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c8-8a65-7a82-bc09-e305418be185
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c8-8a6c-7bdd-9860-dda3934ab048

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c8-9f30-76ce-91d9-f117e328a180
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c8-9f36-74a6-9389-565463563316
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c8-9f3c-76d3-941a-e2fe66c1c2c3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c8-9f42-7bf3-89b7-5d88cffc9dfa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c8-9f48-7c22-880e-1f255728232a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c8-9f4d-70d3-910c-8db1897ebeb0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c8-9f54-79f0-955a-3db79170262f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c8-9f5a-7de5-8093-69de4c8cac09

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c8-b1ab-704b-86d9-cc76c390c1b3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c8-b1b0-77ab-bcf6-bf9e36986ef5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c8-b1b4-7999-bbd3-739bdcfea8ba
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c8-b1ba-74c8-9972-cb291f06990e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c8-b1c0-7755-9f32-d7c3961c3176
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c8-b1c6-72ca-aa69-c6bba25802f9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c8-b1cb-7d1b-988b-fee0e14cbfba
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c8-b1d2-7490-9898-0df1a67f8e6c

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c8-c973-71c3-b342-6392a5e58433
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c8-c976-778c-99f7-9e1102ce8bd2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c8-c97d-7703-9ee6-62e174db8f7a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c8-c98a-76f6-893b-baae17d3dd7a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c8-c98f-7cc0-98fc-40bc050b0295
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c8-c996-7b3b-80a0-b867335fb095
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c8-c99c-7960-a6e7-0a05044d87e6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c8-c9a1-7d6d-b1a8-16484794d8ef

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c8-e2e1-766a-8eac-94a8a6c77577
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c8-e2e4-79d0-ba80-56c936921406
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c8-e2ea-781f-8e1e-cadbef6e3e2c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c8-e2f1-764c-8513-e2421e5484c7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c8-e2f5-7b58-b5dc-f0efcd6d61e1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c8-e2fa-7161-ba72-32ec6d52692e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c8-e300-77cf-bed1-be2d28352e99
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c8-e305-7046-aeab-a8430fe1c812

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c8-f647-78d0-b464-c7ebce1c8085
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c8-f64a-7b4a-a9f3-31b507f0d002
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c8-f651-7311-b0f5-051051439780
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c8-f658-74b7-b90e-c06f095ce956
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c8-f65d-76e0-9a07-1362c9077b74
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c8-f664-7a56-8494-7d6a5739820c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c8-f668-7abc-83b1-ac4e08381e9b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c8-f66e-7870-8ddd-b8ad62f5025d

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c9-14ae-7f16-9929-79fc78d3b175
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c9-14b2-78a8-abed-f697d0daa335
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c9-14b9-77c1-aa95-6925deb9b5f2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c9-14c3-79af-9827-bce9c8b21908
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c9-14ca-781f-ae80-4571f29e9fa7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c9-14d2-7ea3-811d-f82a7bf0bf4c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c9-14d6-71bc-9cfd-7630da43222a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c9-14db-7ea5-8174-ae8e86737717

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c9-20d5-72d8-a706-f27b89bec7c0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c9-20d9-727b-9b12-6ca64f05d779
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c9-20e0-7110-9532-cdddd1efa4f1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c9-20e6-7a9d-bb61-c29330fc7dff
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c9-20ec-767b-ac2d-57a087537f2a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c9-20f2-73c2-be69-e5f1bbd78230
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c9-20f8-7cf5-9189-d1e9d436185d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c9-20fe-7428-9079-98ba32418669

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c9-3635-704a-bf6a-5f8bbdd67247
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c9-3639-78e1-aae1-a89420d544ee
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c9-3640-7b5f-9073-30be8040140f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c9-364b-71c1-8461-ec7472bec14c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c9-3652-7e7f-bcbb-61bc637c84ef
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c9-3655-7cba-a979-3de48bdad0b8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c9-365c-76fe-b20c-11f58ebf4a92
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c9-3662-7f7c-b925-5176122360cd

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c9-441b-7d28-ba6b-a9bddd3e2298
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c9-4420-73b7-901e-62c980b2f017
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c9-4426-726f-b8bc-9cc9535184c8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c9-442b-7624-956c-51dfc4c4598f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c9-4431-70ec-b486-0b0a8e5b4557
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c9-4437-71a1-aadf-1902172a973d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c9-443d-7cc1-a32d-2f525a8188f7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c9-4443-778b-b770-d0fdc9728856

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c9-5ac5-7889-8a3b-e14aab524d12
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c9-5aca-7b30-b584-823f08e3e94b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c9-5acf-74ee-ab36-743f1a667ee8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c9-5ad6-7d15-aa7f-b22a334596ca
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c9-5add-76f6-b1b5-bd720313dc0f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c9-5ae2-7a35-8ab2-4565c022e790
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c9-5ae8-74a8-be80-f25f684fb0d0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c9-5aed-717b-bf10-96bf0747bbf8

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c9-803c-7548-86b0-b8bfac393825
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c9-8042-7b8e-b603-ff5a5bd9471f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c9-8049-789f-aac7-2866c94e9709
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c9-804f-7c66-b610-b2432b5b1c2d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c9-8055-7cc6-97ce-319b6abb8901
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c9-805c-720f-b8ff-ce8ec77cddea
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c9-8063-7966-9b3a-65888527e13c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c9-806d-7f34-a85c-d9d6e300ac63

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c9-94aa-78b5-b656-c4ddf2b9a341
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c9-94af-7a0a-b139-e28478bfff9d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c9-94b6-7698-b37d-21228e173bf7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c9-94bd-74e2-97b3-c97fb5bc4c99
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c9-94c3-7518-92d5-5db7c3e69e74
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c9-94c9-7dd3-9108-dab82037e6c7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c9-94cf-75be-a6a3-2b74df24a65e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c9-94d4-7efa-87c2-9b2ab0c91460

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c9-a0c4-7d70-a424-b8ba6ba4bbbe
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c9-a0c8-79c1-9cd3-c7a5d111fe58
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c9-a0d0-7394-ba9c-e088a36ab21d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c9-a0d6-700c-939a-02cf0a22ae5d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c9-a0dc-79ed-a0ad-be8fcac599d1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c9-a0e2-735c-9c2a-ddc715c9b055
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c9-a0e7-7560-99f6-905b5e552efc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c9-a0ed-7c98-8aa8-6f1e247a2b76

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c9-b6df-7ea1-86ad-547245bc6c23
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c9-b6e2-7dc7-adf6-92be5bf350a6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c9-b6ea-7396-8395-35d2f25af915
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c9-b6f0-7d44-a3c8-47b955d23e90
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c9-b6f6-7688-9c6a-3ed0d47b2b29
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c9-b6fd-7544-ac39-773533fdaa98
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c9-b704-7a33-be82-1fdbead90ebb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c9-b709-734b-83eb-5e477f0f9b35

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c9-c7f8-7608-b91d-651589c1528b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c9-c7fc-7533-a52a-1068832d55cd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c9-c804-78fa-8749-ed8de199c5b2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c9-c80a-703b-98f8-1e89401ceed4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c9-c811-7333-847b-a1f80a220c60
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c9-c817-7ba0-8ee1-78af67444f0e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c9-c81b-74fd-bf56-fc9d9a481ef7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c9-c822-74ea-aafb-0ad5826ee7c7

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c9-df2e-780f-862b-088cb4291260
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c9-df33-7670-8828-ef6db88512ff
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c9-df38-739f-a039-4eb66e166195
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c9-df3e-7c20-841d-b76c53665633
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c9-df43-7a83-8f0a-ff1eff56e73b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c9-df49-73ef-a9d4-bc36f3e52576
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c9-df50-7fad-b093-19d49f6ea6cf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c9-df55-7210-8c00-a09f1acad417

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c9-faa0-7162-b4da-a43a888c88d5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c9-faa6-70a8-be47-eab075be41fc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c9-faab-7da2-b19f-445e4ebff39c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c9-fab2-7d3f-8d7f-67cd0607d172
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c9-fab6-7c08-a82e-23f505802bd3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c9-fabb-7bf1-9199-5aa9015001ee
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c9-fac1-72f9-91a4-3680d61eaacc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1c9-faca-738a-87f8-33795628e81f

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ca-0e22-7a82-b30b-adb38f1a94b5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ca-0e25-7640-a0da-22e85008e319
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ca-0e2b-77e7-bcbd-c8b12a73b8a2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ca-0e30-7760-900f-f4fe78079e88
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ca-0e37-7e14-b0d7-e1fc746c7c4e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ca-0e3c-7569-9dec-faee20017e60
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ca-0e43-735b-8890-a53541e85acc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ca-0e49-7c90-8b68-4a767d122d4d

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ca-21ca-7555-bb15-9bf45f52d833
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ca-21d0-7401-8473-8e86da9af93d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ca-21d4-7a1b-87d2-f4696496315b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ca-21db-7746-9d0c-081696c8069b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ca-21df-7626-a4b5-0edae4c8ed3c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ca-21e9-7267-9cb8-edf684048236
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ca-21ec-70f8-b81a-1add57472453
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ca-21f1-7366-bbb6-edc7ab6a1902

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ca-38cc-7cbf-9c99-3d75a01e5455
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ca-38d0-722d-bfc6-65a987caac67
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ca-38da-7290-b645-0c4bfab35298
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ca-38de-7283-8527-f81d83e4dd53
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ca-38e5-706a-b06f-0b585db88656
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ca-38ea-7104-9b76-aebab1e5f90f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ca-38f1-7671-afc3-92fc6b17eac2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ca-38f8-7986-8279-cfec59e5838b

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ca-52cc-7db5-8a65-9540204d75c4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ca-52cf-73a5-b7f8-3fe4ca2afd53
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ca-52d6-7889-96e7-36fa53ea176d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ca-52db-7f40-b9dc-0e5590b38d0e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ca-52e0-7a97-83c6-6c3a3118cc9a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ca-52e7-78c6-8b23-689aa1ef986f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ca-52ee-7018-a4e1-69f304862637
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ca-52f4-7e9b-a222-af3090208ed7

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ca-72cf-7385-a7f3-ef8232eb7735
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ca-72d5-7696-bbd2-b30c302dd288
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ca-72da-79d3-b3d9-d37ae5437fa5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ca-72df-735a-a2f6-46e399cc0109
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ca-72e5-73fc-98f5-73e950cdfb53
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ca-72ea-7dfe-aa4d-881f3e42dedb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ca-72ef-7532-b73f-cf870b045944
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ca-72f6-7463-845e-2b8081f0c92b

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ca-83b6-76c8-9c61-f8f656b944db
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ca-83bb-70ae-8702-da35af44a448
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ca-83c1-79b0-8a3d-976a3959cb72
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ca-83c8-7493-96c6-864c8c91c738
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ca-83ce-7375-a605-d630541f25c3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ca-83d3-7603-b4cf-2243286a8b3a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ca-83da-7111-8ff5-0b608cf9a7d4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ca-83e1-7e09-a83f-030ec2e0377a

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ca-9834-74d5-85e9-396350b8d702
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ca-983a-7ca9-a3fc-b9db56adb04f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ca-983f-78c7-a29e-c59a0d4d92b5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ca-9845-7f13-af01-cdfa64f22aa2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ca-984a-7b02-a700-4d79273e1949
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ca-9851-7751-8c77-b068c550f143
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ca-9855-7c1c-9250-fad9bf174a91
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ca-985b-7569-82d7-19776871da42

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ca-bcf5-75c9-9643-541827ebb13b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ca-bcfb-75d9-87fe-84b9963cccc7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ca-bd01-7fc3-b83e-cd41be611446
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ca-bd04-77aa-84dc-70fda8984532
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ca-bd0b-7240-8dbe-4d3611ebf6a1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ca-bd11-7be1-9591-b0943757c935
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ca-bd16-7527-83fc-cbd5156c566f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ca-bd1d-7550-963c-1528c8035d23

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ca-d49b-7b35-848e-40fc6e90839c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ca-d4a1-7c2d-a988-d9072c90587a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ca-d4a8-750f-880c-2682d795bf28
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ca-d4ac-7b31-a986-99f940425a17
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ca-d4b2-76ea-abd0-d4ec61d9c691
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ca-d4b8-7950-bc25-1d14383d345d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ca-d4bc-7cc1-90bf-1d1522868e99
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ca-d4c4-78af-b3ef-bd7e55248f18

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ca-f066-716a-85e9-36b8486784f8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ca-f069-78da-b815-05a28d96771c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ca-f06e-75d3-9deb-eb66f1fecc61
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ca-f075-797b-94f5-a0780b5331af
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ca-f07b-7c0c-9b20-45928ca0f08d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ca-f080-7c9c-80d0-7df17924b35e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ca-f086-7093-b15e-042577b6675a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ca-f08d-7f33-b9d9-4ba8710cd2e7

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ca-f9b1-737f-b803-61a7a6a5f66e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ca-f9b5-72d4-9ec1-b2446bc0e65d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ca-f9be-7135-b8d0-dcb578b73d83
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ca-f9c6-7b01-a1ef-22bb663ba1ef
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ca-f9ca-70a1-9f72-9a1ac0300ad6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ca-f9d2-737a-9464-c0c3c5db38d8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ca-f9d8-7920-9f42-704018a7b70e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ca-f9de-7729-9273-1ac0a59f1bed

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cb-0e33-76c0-926c-de7f1092182b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cb-0e37-7bd4-bb47-3ef70fdd5ed2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cb-0e3f-77a6-afe7-6c582cf5052f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cb-0e45-74b1-b06c-70ffc553b30a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cb-0e4b-7fd3-bf36-ce42b262d6e0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cb-0e4f-70c1-a2bb-3332c5042942
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cb-0e57-7ed0-ac20-3f4dba4a5dcd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cb-0e5a-73bd-a260-2c2f6c686254

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cb-326b-760b-91d0-b5973ad21c6c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cb-326e-7168-a324-214398e85d0f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cb-3274-7a9c-869f-8147500c341b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cb-3279-7657-a0d8-6bc67333d224
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cb-3280-733e-b827-d56616587e80
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cb-3287-74d5-a554-74eeb61ee125
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cb-328b-7156-a52d-5fd48fdca97e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cb-3292-70bc-b737-614f4ded64f7

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cb-4873-7222-a252-b1f48ae7a1c4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cb-4878-7d07-a6c1-8c631b9d9e0f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cb-487e-7df2-9617-4c621302615d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cb-4885-7ff4-b559-ee22a6c7b4bf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cb-488b-7c79-9291-def9b1602a4e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cb-4890-7d31-ac8c-b262195ac38f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cb-4895-73f1-bbfe-ce52071faae6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cb-489a-7907-b0f9-147af0042dbc

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cb-618a-7463-83a4-dd1bd97fc815
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cb-618e-775d-b1c2-efdb0d6cfa9f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cb-6196-7c62-9e9b-4a64ada03898
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cb-619d-7aa0-a589-1b354e237ad0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cb-61a9-7f64-b0a7-c2461a244769
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cb-61ae-718f-9bd7-9710777a99d4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cb-61b5-79bf-a884-764c803c03b3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cb-61bb-700e-9cc1-7435b326afc7

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cb-74bb-7162-82e3-9db78303b889
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cb-74bf-70e4-9542-0d1e0b1aeecb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cb-74c6-72be-b27f-72e029e1bb19
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cb-74cb-7a9b-a075-f37081d382d0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cb-74d1-7ce6-b2e3-8b3980cd1988
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cb-74d7-7423-99d6-1bb161f6ca34
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cb-74de-790e-a978-56e29d7f89c3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cb-74e3-7988-8629-02ebd2afe5c4

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cb-8837-7be2-954b-47cbd45f5cd4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cb-883d-76f2-b5d3-280b7f74932b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cb-8840-77bf-b6dd-8966d882d7a2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cb-8846-724f-9268-6b54f3fd38e5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cb-884c-7470-b89d-f6da52406572
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cb-8852-750a-9c07-caf9f0a451bf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cb-8857-7da2-9bd5-07b28f2648f6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cb-885c-7b4a-84d7-e60a3bb6d58e

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cb-aa87-7d38-8e29-32c5837bacc3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cb-aa8a-7937-b8a8-1d1f46cedfd1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cb-aa91-74da-957f-e128bc726ca9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cb-aa96-7571-86d4-cf3edb86332d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cb-aa9b-7579-b1c7-8646021a3662
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cb-aaa2-79bd-92c8-390a60be24e8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cb-aaa7-7727-b706-e25c92641df5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cb-aaad-7686-8b21-e97c03d05a4e

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cb-c301-79f6-bb20-79d49c9eb72e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cb-c307-760c-88f4-0b69a00e3fe9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cb-c30c-763b-a7ee-9d2129d3aefd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cb-c311-74da-9a56-8e7f9cd2be34
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cb-c317-7310-bbf1-f9895131cedb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cb-c31c-79c6-bd46-b725cbaad56b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cb-c322-73a0-82cf-62893a7f96de
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cb-c327-7fd6-91fe-6afb856ffe1b

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cb-dc06-72e7-a992-1b01b58ef616
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cb-dc09-7f30-9126-87ed15a4f56a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cb-dc0e-70b6-bc9c-0e2a86c8a5ae
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cb-dc14-7230-8255-dfa0dbb5f1fa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cb-dc1a-7978-b31d-47a76f041e5e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cb-dc1e-7677-9a55-deb0e7b4f3ea
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cb-dc25-7113-8fd8-60aa4b79d5db
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cb-dc2a-7aab-9d89-1ee64de179ce

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cb-f20c-7725-ad58-9efb90a6d08a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cb-f211-7775-94f1-bf5f823f20fc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cb-f216-7035-a7e5-5eacfb0f6214
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cb-f21a-763b-90f0-9592b7b43db3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cb-f221-7717-a346-c4d9cd6ddfe4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cb-f229-7b10-a70d-001006769d01
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cb-f22e-79f7-902b-06e837eac223
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cb-f233-76a2-99f8-e02fe8c18245

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cc-0b9c-725f-b8ca-c357e7c6c861
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cc-0ba0-7465-bb21-fe91be09a31c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cc-0ba8-7b53-ad18-66f27a519f3e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cc-0bad-75ca-aff7-4edce24282a1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cc-0bb3-7447-b725-4843e179b91d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cc-0bb9-78d4-b318-9aa91c84a75c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cc-0bbf-728a-9467-0168e9984475
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cc-0bc4-7cf8-8c28-34b2c379b1ad

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cc-3097-772d-ade5-3d0f59345f23
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cc-309b-7b84-a8f5-a8589d47d78c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cc-30a1-79cc-a12b-deae774f344e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cc-30a6-71fd-bf89-466853b46266
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cc-30ab-7a13-b72f-482033b05e36
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cc-30b1-7e02-9a53-da42ec5828ff
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cc-30b7-747f-8fcc-74f835b5b56b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cc-30bc-7cf4-8423-858859f22f94

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cc-43cd-7135-9638-b7a5437f50ff
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cc-43d3-7b53-9bc4-0944e69f4af7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cc-43db-706b-bcee-187e6bb1cd7b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cc-43e0-7130-a852-a2f940e7fcdf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cc-43e7-7921-b09b-dc0f4f0e7c60
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cc-43ed-7a33-8556-719d30e1b417
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cc-43f5-731c-b514-659738380483
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cc-43f8-70c4-8f69-6479f6597313

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cc-5fc6-7f75-abf4-d15578a1da1b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cc-5fca-7b6c-a9b6-40875fff24b4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cc-5fd1-7f0f-86eb-261bd6d6b694
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cc-5fd6-7285-965f-0334e4b1ad90
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cc-5fdc-7da7-96d6-b021a532bd45
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cc-5fe2-7cf3-8889-af0452d88086
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cc-5fea-71a6-a29c-af3e0c1befc8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cc-5fef-7d40-8d4a-d8edd375b779

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cc-7347-70ae-af28-c07f33781c26
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cc-734b-791a-bcb6-ef72169f48ef
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cc-7352-7b39-8160-4245d0064fc3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cc-7358-7cce-a782-d7b4b9a45d09
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cc-735e-7719-9756-7ac9d2467219
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cc-7363-7a8f-b4b8-52ab74b911b7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cc-736a-7f3d-960c-8fda9dba9ea8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cc-7372-7a06-9977-c849b3c82ccc

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cc-8219-778a-a508-b0c9a1a9ffae
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cc-821e-7a12-befe-2416f6531598
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cc-8224-796a-badc-fc7917ac9cd3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cc-822a-7aef-991a-2fd9dfdbaa61
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cc-822f-7680-8eb9-7ec3daef420c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cc-8235-7e41-b54f-9787bbb986ba
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cc-823c-7a86-9ff7-d60b47bb38f3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cc-8242-7500-a774-bf4ffd876ec0

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cc-9c8d-7590-accf-9b50cd7d3e1b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cc-9c91-7e62-9930-5030d2f86e69
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cc-9c99-776a-b19a-299a3f379ad4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cc-9c9e-75a8-8830-2d928aa01abd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cc-9ca4-77a5-b351-b67dd5554e36
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cc-9cab-7dcc-b2cf-ba2a9f5a3887
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cc-9cb0-7bc6-a28a-39416f6f7c2b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cc-9cb5-7a71-9e03-d3c315976812

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cc-b150-7bbb-8758-f9e319b4544f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cc-b154-7625-b754-57c64835c535
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cc-b15d-76c9-aee2-1d8f9ee6a1f8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cc-b163-7ffc-8d65-8591a48d0036
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cc-b169-7066-bae7-f0b01182ff1b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cc-b16e-7775-8d82-7ba41cc65c5e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cc-b175-7371-a502-f451d291ba4e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cc-b17b-7f34-87c9-1ab3949ebb49

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cc-d619-7761-9f88-e7fc4c34cfa3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cc-d61e-7f27-8681-220b77472310
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cc-d624-7610-8d24-2a833456a48f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cc-d628-7afd-a617-590c95338dcb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cc-d62e-7bf9-a34e-5091b03c6beb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cc-d634-70f0-bc80-7799854b0614
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cc-d63a-743d-8302-30df330cf10c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cc-d640-732f-9894-7f1196c559ec

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cc-e1d5-7188-b464-7e46e5266e9e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cc-e1d8-73b2-8531-f0940103fedd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cc-e1e0-7bed-beb1-37cc11434780
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cc-e1e6-720b-ae84-dc5188d2bda6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cc-e1ec-781a-aa47-7e2cc7d850d8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cc-e1f3-7143-8686-d999b34098b8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cc-e1f9-77ca-8593-ede587451e92
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cc-e1fe-7d3e-a97a-c79c2aba2c60

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cc-f721-7b48-99b2-e07df029f5aa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cc-f725-7e4f-b487-8a2371bd39c5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cc-f72b-705b-98be-a1ed1df7fdd4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cc-f731-7356-ba70-db39117e2c84
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cc-f737-7eb6-9924-0e7149724861
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cc-f73f-7713-9ff0-2f4d7f22001b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cc-f748-79e0-840d-39348f00e495
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cc-f74d-7ec5-b355-653368749ff3

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cd-0953-7423-934b-7e2c3dc6a531
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cd-0957-795d-a760-366403d28b73
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cd-095f-7b03-97da-238066912b78
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cd-0964-73bc-a89d-c642f9107c56
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cd-096b-7b81-8b08-f107a9bdde04
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cd-0971-7c8f-afd3-134b1a96d36f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cd-0976-785f-a433-b5f94679bbb8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cd-097d-719f-b128-7131f4bc36c1

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cd-1a7a-7929-a471-7a99baec1764
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cd-1a7e-7ba7-9db7-e501de86cbf8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cd-1a89-78d4-83b5-3c1b3dc092b6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cd-1a8d-7b84-92d6-14c41aeeb65c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cd-1a93-70fb-86ae-891064705b6f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cd-1a99-7fd3-9277-1299c6274a53
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cd-1a9e-7b8a-bc86-9b1399335582
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cd-1aa4-74a7-a4d0-de8f1ce12bc3

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cd-3050-75b0-a370-9fb97d512a45
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cd-3054-7758-9d34-78cd03066054
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cd-305a-7cd4-8975-60efc9e21a1b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cd-3061-7049-b91c-696c2c681804
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cd-3067-7dc3-bf50-9a59dfbb6f23
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cd-306c-76a2-abb0-b7ec461da363
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cd-3071-785d-be95-5a54fac458f7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cd-3076-749f-8a6a-e916afbe6244

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cd-446c-778c-a0a8-80187868332a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cd-4472-7755-b6c3-84b81170458c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cd-4477-774a-9495-72a1fc5cbb4e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cd-447c-7fcd-aeab-b84338181175
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cd-4482-7061-9760-b987fbd40a1c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cd-4489-7409-b14c-b1c395199fa0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cd-448f-7160-adcf-b0f243a97c37
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cd-4496-7f48-8df1-b9c44e2bb115

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cd-4ff4-7863-8ac6-c48a9d18cf4a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cd-4ff9-74fe-ac31-3985f7c0691e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cd-5001-7db2-a9d4-e821ee9910c4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cd-5008-7783-a3c5-de75c7d0bba7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cd-5010-7dfd-8701-a6599d90ae1f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cd-5016-78a4-8f07-e1a0c820798f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cd-501d-7a82-87a9-b1716b238e65
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cd-5024-7833-9ea1-0f29bf0f12aa

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cd-6292-7b0a-ba7a-62f79d92f501
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cd-6298-7b83-90d2-51ace3c014d1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cd-629e-7e9e-9694-318a0804cf19
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cd-62a4-7fba-b1f4-3fe597be3ff3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cd-62ac-78ec-ba95-cf316169ba06
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cd-62b0-7f49-9036-aabc5ffca4a8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cd-62b5-705a-b1ec-83656597744f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cd-62ba-7501-b84e-5722bd594680

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cd-878d-7eb3-aa93-7d71886683b4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cd-8791-75b3-acb9-3aefd183b042
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cd-8797-76b4-b5bd-7280d5cc7dbb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cd-879b-7ae8-8151-42a1237e06e3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cd-87a2-730a-b284-107560077ffb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cd-87a8-7e83-b4f5-9320d38c02cf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cd-87ae-7b52-8e53-fcc85dbca08f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cd-87b4-7b1c-b25e-b467d238562a

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cd-9a63-7cda-84bd-7bd5689ffee4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cd-9a68-7f99-b0c4-6cb2bb5f2755
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cd-9a6f-779f-9120-18181b4542c2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cd-9a74-7721-8dc5-68ae7338d45f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cd-9a7b-7cc7-83ac-f9eef9efbc11
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cd-9a81-721f-b552-450a6138b3d6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cd-9a87-7ac1-8b70-ed3195f92650
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cd-9a8e-7ec8-a534-09265c19dcd0

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cd-aa33-729e-9b4e-a8b7e0bd2c00
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cd-aa37-7e21-8e83-cca0319d93a8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cd-aa3e-757b-87d0-354b7f3da5f4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cd-aa44-74d8-aa80-0f94955d2f76
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cd-aa4b-7490-8693-0b5fac4cbb8b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cd-aa50-778f-847e-da18118cdbf8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cd-aa55-7d66-86a9-0c78fe943284
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cd-aa5b-7ff2-978e-cbf9ff65db4f

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cd-bca8-795f-945c-dd748c36ed1a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cd-bcab-7a59-b26f-c45ab53a1611
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cd-bcb4-7c2a-b4d0-2cc656810601
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cd-bcb9-7f49-9e1b-06c19fb38ecf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cd-bcbf-7513-9fba-7cfd0cfdf192
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cd-bcc4-79ca-8c49-7c1d4ac8acd1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cd-bccb-740c-855b-da29eb6a68e2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cd-bcd1-74a8-b065-894c9f1235d9

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cd-d088-79a8-a3d1-febacb8875e2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cd-d08d-704c-81b6-0ac4b87bdff7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cd-d092-7f85-8990-e15f581f0af2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cd-d097-7cb8-b361-8aa7638a5a09
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cd-d09d-76f5-b2e7-e6985c155509
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cd-d0a3-7459-8c12-eee5e17e5233
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cd-d0a9-7a1d-8123-566a693dcb87
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cd-d0b1-7f9e-9f8f-f566e230a353

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cd-f18d-7d22-95be-fc443edd3ade
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cd-f191-7766-9e8a-97c72597e853
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cd-f197-7cb4-9893-4c3bf8bb47d0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cd-f19c-7976-87fa-2651cd101b3b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cd-f1a2-7f1d-8ade-faaf28afc924
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cd-f1aa-7ca6-9959-c334cc1b665f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cd-f1ad-72ec-88a3-7254ce4ef73a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cd-f1b3-762e-ba45-b65031d20196

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ce-061a-7fec-8f95-4143cdedb1a3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ce-061e-74ee-bb18-8349a8fa844f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ce-0624-7c3d-954e-2e2f5c52b6ac
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ce-062b-7676-9901-3d98edb40e7a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ce-0630-7774-8bb9-0219d4ff60c5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ce-0637-7216-a2f3-4318e7125286
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ce-063e-76bd-88ad-3fc4a9b14ea6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ce-0644-7297-99d1-3cae6a280b6d

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ce-2b15-72be-8685-7699b9cb9b5e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ce-2b1b-7a46-9904-6e5d7059a034
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ce-2b20-7f27-998a-71bc47869daf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ce-2b27-7a71-a8b5-e76721ffce89
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ce-2b2b-7a5b-9352-6e3bc04a2354
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ce-2b31-7605-8289-2c3571bd80a2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ce-2b36-796d-9ed3-bd2f689b90a8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ce-2b3c-7e32-8284-162af2c89626

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ce-3d23-734f-8b3f-63b01ddf6bcd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ce-3d28-78fe-918e-e8d9c3f13031
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ce-3d2f-7bd1-81f2-d853d36239fd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ce-3d34-7066-b9cd-9531ddc8c9c7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ce-3d3a-77e6-a1ea-3992d7520839
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ce-3d40-7250-ad1d-7474cd3784b2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ce-3d47-7984-90d8-6f28f34f9e73
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ce-3d4d-7a8a-ba70-4ef60337b23d

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ce-5352-7b24-846b-4482d35a8776
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ce-5358-764f-b44b-b22f6ad96b90
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ce-535b-7ebf-8915-2e30b73a4b35
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ce-5360-7f01-a79f-54cb75fcedc5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ce-5366-7a38-97e7-004da8eb0640
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ce-536b-7ba8-839b-86640ec6bcce
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ce-5372-78fe-94c4-4d6391a9d05e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ce-5378-71f4-b9a5-985a40446efa

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ce-68d1-75a2-8250-5f9f88ffeca5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ce-68d6-71ba-81b6-50afa92c0f2a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ce-68dc-7729-bc1c-f27fd57d523f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ce-68e1-7aca-9dd2-42a6a962155d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ce-68e7-7bdd-81c2-e6a43b2b0438
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ce-68ed-7024-a019-9b1235576072
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ce-68f3-79fe-bec7-b46bcf412924
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ce-68f9-7103-97ab-565a1bbe4a5f

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ce-7f7e-7d58-afe9-aed5f17c8a3d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ce-7f81-7465-8a50-867a22c1b06b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ce-7f87-7b3c-a6c1-fac6e4248b8c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ce-7f8d-7420-bc3e-0d27a6af65f0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ce-7f92-709a-bcff-e16d5202855b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ce-7f98-7bf5-ac01-86749820ba4f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ce-7f9d-7bd7-bec4-8e5ad0306b27
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ce-7fa2-75cf-8373-a2b8530f7861

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ce-95b3-730d-998a-125401e031d3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ce-95b6-769e-91f7-2fc65d16d26f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ce-95bf-7d66-a089-8356910f08a0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ce-95c5-7af7-adbf-474b777f3e32
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ce-95ca-707a-869f-5044a06e7c44
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ce-95d1-719d-8ac1-cff3e5cfb0ba
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ce-95d4-7eaf-b8ad-ceb664401a0e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ce-95d9-76ba-8180-25067c14e448

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ce-a8b7-7ada-a0b5-105e2b24a970
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ce-a8bb-7c32-993a-4c1484cd323c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ce-a8c2-73d8-889d-8ed826c25c60
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ce-a8c9-72a7-b1b4-be77288f7fd1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ce-a8cf-7226-b275-50ff96656a00
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ce-a8d6-7175-917e-142fe2773409
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ce-a8da-7573-8de3-6c1bb8b966bd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ce-a8df-7fed-bdb5-be302d48f669

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ce-ba60-72ef-8bfd-80c87ff40f9a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ce-ba65-7e53-958e-69da9e557a63
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ce-ba6c-76e4-af6f-ddaa00242520
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ce-ba72-7f0c-a8ee-67be88270fa9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ce-ba77-7489-9231-5dcc5bbcbe92
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ce-ba7f-7925-931c-8f7d951a8f71
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ce-ba83-747d-965b-ad38d0a800ba
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ce-ba89-7bc9-9698-18e0864d3975

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ce-d2f4-7492-8c7e-a34a5a907fa0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ce-d2f8-7c05-9171-c52b925d43cf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ce-d2fe-7892-871c-e90c57242fb8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ce-d304-7078-8e1b-87084a53b0f4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ce-d30a-7be0-8b61-ce18fa1e55a6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ce-d310-7ce2-8f85-0987b4c88f25
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ce-d316-742a-8b73-7b437a0c2bb4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ce-d31b-75a5-9350-160f6947265c

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ce-e86c-731c-aed7-e1138bdc9ade
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ce-e871-71fc-b08f-71ded46564b6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ce-e877-7401-a7e9-ad654f74b4dc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ce-e87d-70e5-8cda-41e39c67613a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ce-e882-7668-b1c9-aca800805b1e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ce-e888-717b-ace1-d996ddade86a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ce-e88e-7798-879d-51b694bb1e64
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ce-e893-7e86-a0f4-f5ad87c589d3

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ce-f9b6-7658-a783-af1d0bcfcb12
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ce-f9b9-7de7-835f-ae104f2961dc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ce-f9c0-7888-b38c-08f0a7a1b7c9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ce-f9c6-7c34-be71-79ef144061f8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ce-f9cd-70c8-927b-bad558c22c2a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ce-f9d2-731e-a543-6ad128d149a0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ce-f9d9-7b1c-9ba9-003f422964eb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ce-f9de-75ad-9f24-272204384426

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cf-0aca-707a-abe0-6a471d06e2d4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cf-0acd-7a09-baec-561a20355790
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cf-0ad4-774d-b933-5266f8bff64e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cf-0ad9-736c-a934-152b8150f88c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cf-0ae0-7ddc-9d63-8cd3d61fbc62
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cf-0ae7-7c1f-817e-3aaaa4760f29
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cf-0aeb-7d15-9bec-aad50b75bc6f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cf-0af0-786f-b2aa-5d32b4bb4e15

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cf-22dd-785f-8e6e-3ce097077a55
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cf-22e1-7228-a7fd-c640bfab19c1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cf-22e6-7295-b66c-429dca90e31c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cf-22ee-7edf-b808-06166c377c25
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cf-22f4-7ce8-b9de-124c31791ba9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cf-22fa-70e2-8737-21c6674b2310
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cf-2300-7242-a803-029aecb52da9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cf-2306-7210-8fb0-1ac0fb36320a

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cf-313a-7390-bc43-a98cfd336f91
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cf-3141-7345-a398-cd2d7a70811d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cf-3148-79c2-b214-efb9d0bfd577
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cf-314e-7668-9e69-af1cdc6aa31d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cf-3154-7603-b2f6-f218e2bcadc9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cf-3158-7e11-a28b-51fa8b18363c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cf-315d-70c0-9b4b-1b017f6f33c5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cf-3162-7686-a394-7e89f2d82cae

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cf-563a-709a-899e-01d09bdaf82e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cf-563e-7188-8866-5f6951472124
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cf-5644-7bfb-b28d-62c12787c577
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cf-5649-713e-8620-218e7a5dce01
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cf-564e-7768-85ec-512d7c578c4e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cf-5654-7b63-9c90-a31177bb3099
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cf-565a-7527-9efa-39fd0f6cdb28
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cf-5661-7a3c-8e37-fabb139a9f9f

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cf-7041-7aee-816b-4f705606692c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cf-7044-704e-8c3d-74a2a95c801c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cf-704b-7d9f-be5c-067ee3027578
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cf-7050-7eaa-ae1f-66b57ac78d3a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cf-7056-7107-bd93-d8e626e41db2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cf-705c-7267-83e2-3ac02ce9e0cc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cf-7061-7b5e-80e9-053c451913cd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cf-7068-74b0-8b9c-446e9dac1c69

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cf-8396-779f-b7cd-ee510311cbe4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cf-839a-744f-acae-da66f17a04a7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cf-83a2-7ff3-bf80-a202710a23c9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cf-83a8-7cff-9798-d2810e04b5af
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cf-83ac-7726-a77f-89ae2fd894a6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cf-83b3-7e87-ae65-517e8e3e288c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cf-83b9-7644-972c-15d9aa383f70
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cf-83bf-7642-9044-d843a3168ebc

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cf-a20c-7054-9cb9-bd21bcec1471
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cf-a210-7b2d-be67-e26247d83653
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cf-a216-7728-9ae4-f487ebaea48b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cf-a21c-7a3b-bd0d-e5fa4b51bb30
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cf-a222-72ce-9e4a-c8673b822ed8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cf-a22a-7030-8969-418934902150
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cf-a22d-76e4-831d-f1fe7c5e89ca
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cf-a233-7255-9e2b-9f87c894608f

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cf-ad09-75b3-b36b-ab81550ba089
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cf-ad0c-74b2-93be-93010a045b0f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cf-ad14-7942-9cb1-cf80b22d34cd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cf-ad1a-77e9-80b1-b4409ba5d188
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cf-ad20-72a1-bfa0-2f5ac343abf7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cf-ad26-76f9-9721-d73029079141
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cf-ad2d-78f2-8acb-0fdd9a1e3ec3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cf-ad31-7198-a264-9e898d2725fd

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cf-c54b-7a61-bce2-388894b12495
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cf-c54e-79f3-b3eb-b1de2257bf13
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cf-c555-7e29-885b-0585e7b8da67
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cf-c55a-7033-b8dc-98a8ecc63ffc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cf-c55f-7884-a908-57a2ff495439
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cf-c565-7850-abe3-b50c56207835
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cf-c56c-7e15-a8b2-65def3e30a99
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cf-c572-7d80-8ed6-c2f96c84df55

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cf-d698-77f1-a6d1-e77230e16880
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cf-d69b-77ab-ac7e-77c0a9431399
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cf-d6a2-70c8-884e-f4f4999dcb42
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cf-d6a8-7da1-8756-8c28f7f2c84b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cf-d6af-74ac-be18-b4b52c3fa1d7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cf-d6b6-748b-8d0b-8d6e9efc7f9f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cf-d6ba-7e6a-9e04-58b383da1e2a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cf-d6c0-7051-b5af-dcadb491bbcf

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cf-eb2a-720b-ade4-660319bc5036
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cf-eb2e-7d9f-a847-5fc1067eb2bf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cf-eb35-7fa6-91fa-0f11507a5fed
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cf-eb3b-7c0b-8a7a-26a9fb47c375
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cf-eb41-79c9-b433-86f10a089109
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cf-eb46-7e91-96c3-c103acd2b806
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cf-eb4c-72f1-99b0-d4ee5a19136c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1cf-eb52-741f-9130-aee70cccc5e2

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d0-03fa-7b83-af0a-364e63938a99
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d0-03fe-7777-9256-639c4f182080
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d0-0404-7d9f-b90a-e4aa7f6743db
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d0-040c-7976-b352-8de5ffcd2834
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d0-0411-7bfb-b613-f422bafc8e49
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d0-0417-7c48-b59b-3420e1eb5f5b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d0-041c-7d84-bc49-6bb34be1c492
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d0-0422-7d71-8f41-024148115a91

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d0-1451-7d02-97d7-5be042d066d8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d0-1456-7931-8036-a5e608aefb8c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d0-145c-7505-b736-4c85c55b4c02
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d0-1462-7476-bfde-096bb6336931
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d0-1468-712a-b9be-79b199427eb5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d0-146e-7901-bdbb-09a8203a5664
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d0-1473-79e4-82b9-ffded73b12a6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d0-1478-70e2-b0d7-5ebd20da648b

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d0-30fb-7977-941d-2def2d304011
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d0-30fe-7016-ac61-c058f2fcee23
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d0-3104-73bb-8088-c05458f931f2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d0-310b-71e2-aad1-dc36c3ff4d73
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d0-3110-7673-ac9c-c6f1347c6c58
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d0-3117-722d-a8f3-cafefcdea8a3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d0-311c-7041-b1b7-28ec8675bec4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d0-3125-7309-aa93-0800dffa910d

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d0-48d2-7fa3-b84e-0b57188b8c66
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d0-48d8-7b5c-9774-f7739fdc6840
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d0-48dc-7e7a-8f7a-a5666c7e99a3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d0-48e2-7d8c-955d-6fd81e9c344c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d0-48e7-7409-bfba-4e06d11f56ae
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d0-48ee-7dd9-8866-a7e6cf7576dd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d0-48f4-7b8d-b81d-a32a20b562bd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d0-48fc-7360-91c7-5ed12b5eeb11

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d0-5ee6-7f2d-a546-0350e0ea21ed
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d0-5ee9-7b8a-a7bf-9c082647514b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d0-5ef0-77ae-8a6c-a3365fa08c54
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d0-5ef7-77f6-a9ae-13b926003191
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d0-5efd-793a-937a-310ee1c15581
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d0-5f03-78f2-94ff-dacb33529d90
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d0-5f0a-7ef5-944b-ddac43da70a4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d0-5f10-7944-8fdb-23831a5abf24

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d0-779a-7249-81db-a613fa3e8081
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d0-779e-7740-8bb8-c7ad7de75fbe
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d0-77a3-706a-a933-cce66e191888
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d0-77a8-7b6d-879f-11c9ebb22352
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d0-77b0-7e77-83be-29724f286224
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d0-77b5-715f-aaa7-b3e43acf457a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d0-77bc-73a5-818d-77f860ed91c9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d0-77c4-79c1-96cf-e63c2354a162

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d0-8b52-7f38-83d6-e88280e50f44
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d0-8b56-7c65-978e-bb166d73026e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d0-8b5d-707c-8b74-376c7f0ea32f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d0-8b63-7cfd-bd48-e6bfce2d3457
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d0-8b69-76bd-8ac9-11f72e773d2f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d0-8b6e-75ca-9510-40e6bbf47c63
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d0-8b73-70ea-81ad-a49c43d90407
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d0-8b7b-7636-8944-5469e98d9798

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d0-a1fc-768b-a77b-5f5d097faed9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d0-a200-76a4-aa70-468b3065b93c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d0-a208-784b-a7a0-1fe88ac8aa87
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d0-a20e-7317-b406-e4db338fa03d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d0-a214-7848-acf7-0d6ae2f5e5bc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d0-a21a-7e6c-a558-627aa4cddd21
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d0-a220-7a47-b2fa-b751150edcfc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d0-a225-7a00-9b23-6e6847deb8cb

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d0-ba3b-7e95-a256-0f7949b47a45
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d0-ba3e-7e9f-91ef-adc54455e05d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d0-ba45-7502-af4d-05ab4e3bd5c2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d0-ba4a-794e-9d85-a74caa5c3e49
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d0-ba4f-7a31-b3f9-8cd8f43766d8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d0-ba56-7bd8-92af-ac237b21187b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d0-ba5c-7de4-9747-4159f83c225c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d0-ba60-718d-9bc2-7c100838e61e

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d0-cfcb-71f4-85ec-10b73d894625
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d0-cfce-728e-a3e9-4ca84213a175
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d0-cfd5-70bb-b406-d1815a9bbed1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d0-cfdd-70ba-9d47-6ac9358e47ef
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d0-cfe3-7058-b6d6-37c834479035
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d0-cfea-7000-8087-444481fc9799
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d0-cff1-763b-8ac0-cea295b990e7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d0-cff9-7a4d-8145-8a338315e1a4

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d0-e934-735e-8aa6-0d5a1d84fc4e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d0-e939-7802-b506-c9915e7bb31a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d0-e941-7f7e-9537-06723ca3b8c2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d0-e948-70a5-a09f-dc691c0c2a32
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d0-e950-77df-9c36-c09258de0528
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d0-e953-7e3c-8b24-645d9d5dd219
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d0-e959-7610-a40f-1a293bb92f24
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d0-e95e-77ae-8867-684c279ef729

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-00c3-7692-bd67-43b804077b35
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-00c8-7c52-87b1-ee3c632f22bd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-00cf-7360-a8fc-db8a9b661565
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-00d5-7088-bdcf-7af2c84ddf8d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-00db-75fb-91d8-99f1193dbefd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-00e1-7ef9-8dc0-fd1100be2e30
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-00e6-77e4-8979-97b6c87981cb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-00ec-7705-9f3c-8f76c6448ac8

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-0cc0-7f0a-98fc-399202fbca6e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-0cc5-77fb-a885-9b7dbc9ef52f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-0ccc-7a5f-8b17-e657a8df0c57
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-0cd3-793a-a126-6cbfb98f7324
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-0cd9-7a37-b31e-368ff7154d12
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-0ce1-7282-b0d1-3f36d056b8f8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-0ce6-7269-ac70-d3c27f5e451e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-0cea-76ba-bb38-fea9048489de

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-31b9-79b6-be72-7342b4bdb070
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-31bd-7b22-a051-7b9a334712a2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-31c3-730c-a7f5-9f9e770b54a1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-31ce-7326-85af-9d7289ecf752
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-31d2-78eb-98c5-7ab2fcdd12c1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-31d9-7798-94e4-c5eac7bc67f6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-31dd-7fab-8320-43c78e0be8b1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-31e3-7d4c-b9e6-41faa92546e3

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-4471-7cc8-837d-52023b0ab10b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-4474-7eb5-ae23-026aff7615e4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-447c-7afd-b894-9f0954bc3af5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-4481-755f-b65f-91f6c50d10dd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-4488-795f-9aad-2fd7d5ffd2e2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-448f-7fff-af40-87f2f65fe80b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-4496-7154-baa1-048237c30738
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-449c-74e6-9d94-a7c78eeab350

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-5bca-7b10-a642-e3eaa086edd4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-5bce-7197-99a9-d4531babd123
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-5bd5-7d21-836d-655db41ba53e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-5bdb-78c3-bf3a-9855f4a0c5cb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-5be2-7505-ad3d-8a6ab85b3870
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-5be8-73d8-9fde-3669a85fbb2b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-5bee-7b4c-8a67-e327fd5aee38
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-5bf6-75e3-b3db-e1b3370a754a

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-71fd-70f0-8866-7be1cbe51280
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-7204-769b-8d34-9ccef4576f8d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-720b-7b11-86b0-d0f9f326319d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-7211-7cd9-8fc6-801f301776f6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-7219-759b-bcaa-4cb23dc686cd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-7220-7537-bfaa-e95050c2a281
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-7227-7c03-bd76-d439769ae840
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-722d-73c6-8ea9-7ae7e65f65d1

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-7ff1-77c4-baa3-f363e96077f0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-7ff7-7c7d-9c09-6b110801ba50
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-7ffe-76a8-8405-f8fdb7dddb1d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-8006-7a16-89b2-c3ecce442d58
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-800c-7e03-bfcf-195b7486e05e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-8011-79ae-9b1a-256a0d737986
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-8017-7d85-8048-fc3d7aa295d9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-801d-7e06-ba0f-058cce9df46b

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-936c-7193-94dc-917a9650b431
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-936f-7eb7-b7ba-2b0ed8deec5e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-9375-73c3-9ef2-91658c17fb14
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-937a-7d71-85cc-7f2c44b7b205
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-9381-7d80-a13e-593ae833ee39
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-9388-7173-9db0-f39fbacc5b3b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-938c-730f-80f9-f745c3ee7fe2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-9395-7c3c-874c-d5eb8142db66

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-a999-75a7-bff6-4e3bc7efec94
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-a99d-7a57-9b6d-77995a7c58c6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-a9a4-72a5-9197-0d7d30be7e45
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-a9aa-7b39-9e2d-636f67af6490
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-a9b0-7c6d-a1ce-9a26e467877f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-a9b7-7828-b6ad-282760669558
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-a9bd-72c8-9998-a8f6acd00b18
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-a9c2-700f-b9b4-92b4b234a160

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-c282-733e-9196-9ff581a8bf8a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-c286-7640-8f45-b369f9ae65d6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-c28d-7667-864a-2038a988d235
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-c293-77ba-ae17-3d3adfa05a52
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-c299-7ad2-bed5-c5d59be13d73
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-c29e-73da-b54f-fb75166106f7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-c2a3-729d-a368-1b3c59e8e3c1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-c2a9-798e-b04b-99592c4cda1e

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-d8a0-74b4-a11d-99b9484274fc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-d8a7-7d7c-be5c-8f685e5bdb73
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-d8ac-71c3-abab-b97b5a88ae37
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-d8b1-7d61-b365-1be575ce9af4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-d8b8-75e4-9f4d-e49c12bfd1c5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-d8c1-71b2-8165-ab43a264b9f5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-d8c5-724d-8268-8e6c49f9ea3d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-d8cb-722e-a554-5b0c75516cd7

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-eb0d-757f-9495-118d79b1829c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-eb10-767a-8acc-6642f97cdc9f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-eb17-7e88-aca6-df6894cb64a8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-eb1d-7ec9-93b9-4526f2a5eefb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-eb23-7642-9446-c79d8c90b356
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-eb29-7245-8162-69c9fd1a3920
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-eb30-7091-8716-708cc17c630c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-eb35-7cf4-9a2f-9a462513f4f5

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-f9d2-7764-a164-b7842011d526
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-f9d7-779a-8b7f-0739ca27ac60
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-f9de-78ae-b481-348d7281531e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-f9e5-776b-92e0-28c6ad19ec28
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-f9ea-7213-bb5f-2aa1e5d563f3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-f9ef-7a1f-97e8-b5ebd2cf9bae
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-f9f5-76aa-9239-e6b6ffec53d6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d1-f9fb-722c-9364-5666a9c8ca67

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d2-13f0-7fc4-a7a4-6a0212ba7970
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d2-13f5-71ec-8620-07de41382948
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d2-13fc-7723-b75a-92c418b8a412
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d2-1401-7a20-9bd3-2336e460eccf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d2-1407-75ec-92a7-66b02e9a8184
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d2-140d-7036-ba2b-5004cff0c2e6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d2-1412-7889-9f0b-22839b51edd6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d2-141a-75f5-a203-f9e7c5ed1e24

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d2-29e2-723d-81e1-759a8140f8e6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d2-29e6-7c1c-b1f0-e044aff3274e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d2-29ed-7f0a-a3b7-569625f09688
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d2-29f3-70b7-83c3-930503c2fb68
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d2-29f9-75a2-9639-a99b59f93ba9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d2-2a00-7eed-9064-b754f4f4ff5c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d2-2a05-7410-8735-8c90bf5572da
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d2-2a0c-7b9c-8bed-84e520b2964a

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d2-41af-7bae-8778-b41cc6152b3d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d2-41b3-7b5f-82f6-4923d9fb2d0a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d2-41b9-73ed-b204-6b7537e5c3cc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d2-41c1-7c8a-a201-604a2a5145b5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d2-41c7-7c3f-92bc-d7c03fe82d7b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d2-41cc-7f53-9df8-a3f853dc683d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d2-41d2-781b-b139-7b6c598e159a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d2-41d7-7236-b19f-6ab47a7e3d01

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d2-601d-725a-bd24-e247b8ea0761
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d2-6020-70ba-aef9-31dba565c816
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d2-6026-73ba-900e-57a7a5e489a7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d2-602c-7c54-9d3d-413d000b9370
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d2-6032-7c3b-941a-18fc0de53ade
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d2-6038-7ce7-bc5d-d166b55237f7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d2-603e-71ef-9487-2f429729ec46
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d2-6046-71fe-87d5-98cbf3f5c684

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d2-6c43-7c82-a953-12242dfa413b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d2-6c47-7479-9738-99bdbe0407af
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d2-6c4f-7c24-86db-7d20da0958d0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d2-6c54-79e1-beaf-8f44d9599362
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d2-6c5a-737d-bbe3-37c2089aaecb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d2-6c60-727f-a4db-db8aff964bd7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d2-6c65-76ff-a5ed-fed8dbc8d5c7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d2-6c6b-7a22-a8cb-82136b358f51

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d2-81f3-71b0-b2c1-cf5f051ff93d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d2-81f7-7c4f-bd6b-7893497de890
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d2-81fe-7455-a06d-6b2c90ee2362
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d2-8204-777b-8a22-b0c0a2a04611
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d2-820a-7cda-89cd-d34131d69519
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d2-8210-731c-8ab8-77ebf63f1a6f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d2-8216-72b7-b993-e6a7f474b0d7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d2-821c-72e6-8935-65e622ffd467

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d2-94e3-7e08-81d7-c87b23dcca7a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d2-94e7-7590-bd73-e4d8989e6a62
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d2-94ee-7148-803c-c0dc8cf26fae
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d2-94f3-7037-bfc4-87f104781708
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d2-94f9-79ce-989a-bee6d2eea611
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d2-94ff-7359-875f-6cb8db633ed5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d2-9506-7391-8989-0c220f79727a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d2-950c-783c-97f3-0603f2e41460

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d2-a713-71ee-b247-7ba3f9735cce
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d2-a716-7575-b711-228b3cf36a67
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d2-a71e-7f49-aaf8-ec014d7e8c32
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d2-a725-7b27-ba36-eb88074dc438
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d2-a72a-705f-96fd-985b1f5c60c4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d2-a731-7bea-92bb-5de74ca14121
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d2-a737-72c1-9493-d1ed5b8c4710
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d2-a73c-7472-8050-5fd2cc83b531

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d2-b771-7ca9-bc38-586bba65d226
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d2-b774-76d4-b023-16debf7a31fc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d2-b77c-7437-9bee-215db597f349
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d2-b781-7fe2-a00e-49330624bdd1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d2-b788-77ee-ab81-7f0d48a2d25d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d2-b78f-7885-9d35-8e9938944270
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d2-b798-7009-b59f-9c886e4baf37
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d2-b79c-78e5-a392-f5ee0aaca9be

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d2-ccf7-7086-96e5-ac3b62c433ce
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d2-ccfc-7a2e-89d8-4e8ecfcfea41
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d2-cd05-77ce-ae0d-30aa401b0aee
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d2-cd0d-7099-bd19-1ae19f2c948b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d2-cd14-7f6e-b121-89747dc2402c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d2-cd1a-7da0-ae79-a1ab0a329ab2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d2-cd25-7e8b-bb08-eb2a44387dda
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d2-cd2b-7348-b7e7-c036b6881a32

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d2-e374-7d75-bddd-7b5f45d0b902
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d2-e378-73c4-855d-15d51aa44243
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d2-e380-7cff-9bd8-a514aba20277
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d2-e385-730d-a96a-e5e51fa38467
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d2-e389-7864-9dad-dc52c64324b9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d2-e392-7460-bd11-be645eeb3eb4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d2-e39e-7f60-b427-e2660bded965
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d2-e3a2-7076-968a-c6d6e0b10e6a

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-0129-7b92-acb9-1cb3a7e2c838
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-012c-793c-af8e-b4dbad2f83ed
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-0135-7e0b-99bd-7744d5307ecf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-0138-7177-8663-b321835ea777
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-013d-7730-bcb2-fc9b81f186a3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-0144-7054-b951-7ad16cd34998
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-014e-7bed-945b-c67499202faf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-0154-773c-a3d4-2c0a9a4230a5

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-11fb-7933-94d3-a621bce85596
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-11fe-7d21-98d1-c8165bc2656d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-1205-7363-a58b-4a3a57baeb9f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-120b-74bb-aa7a-8893538eb8e5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-1211-7672-adf8-91bfedcbd8a3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-1217-75fa-86bc-ce6968b88450
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-121d-793f-ae7f-4f0a66b39f9c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-1223-707e-be73-f62f42269203

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-338d-752c-a062-1a40b12e3fa9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-3391-79cc-8678-cc9920ccc8c3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-3397-764a-9280-eb78f7e545c2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-339c-7a60-a3c0-eeef06e286c3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-33a1-7ad2-8c8d-d12b422e87f4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-33a8-7066-9cd1-74859db885f9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-33ae-790d-9f41-8e87caa5b8ae
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-33b4-74f0-a570-67657939a435

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-4342-78f7-a7c6-91327a7e6dfc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-4347-7ef3-857d-9a40e5602dc4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-434e-7698-a534-cfd4e320609b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-4354-7301-80e5-a051d25ee816
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-4359-740e-8c86-a566a92dc68d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-4360-7548-88fa-271ea7db4909
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-4366-749f-aa56-fc4976ba06eb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-436c-7886-93a2-bc0d4916759f

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-57c8-7dcb-a4a9-e9919adc4c95
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-57cc-7b2e-bffe-9cf83c6601ce
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-57d3-7b57-9a61-6ce51d1ad064
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-57d9-78fd-81bd-b9f6024c8e1f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-57df-7fb9-9cf9-8840e38c8f4b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-57e5-7aa1-8a44-8e171ac738a5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-57eb-716b-8dc8-e819ca81b957
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-57f1-7948-b1ac-e19a96283bcf

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-6379-7683-a8eb-4aaae057bcb9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-637e-7824-b3d8-f2f9610c8c4f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-6384-798e-81f1-5dd6a633bbee
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-6388-7866-99c4-155c790d7fca
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-638d-7485-8850-6a17f95a4172
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-6394-7112-aeb0-09cb11ff81c7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-6399-78ee-a324-79217e150d70
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-63a0-7897-91a3-816523494acc

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-77ee-7dfe-8940-9d89e54a18e1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-77f2-73d6-9e95-66296fba59f5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-77f8-7e70-98a4-bed4f4dcf878
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-77ff-79b4-bf4b-200fb676535a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-7806-7466-82cd-f84fc5a094af
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-780a-7d64-99fd-ff753eebf885
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-7811-749e-a34c-738b480cccc1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-7817-7918-bdfa-2321608eb72a

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-884a-7b71-b040-fa986764ec9e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-884e-7410-b2bb-f68f6fe73798
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-8855-76a5-9f69-af8dc07615a4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-885b-7baa-b006-9d5a910c67d8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-8861-719f-8f5c-dd267813595b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-8867-7819-bfa4-aa254b21f50f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-886c-72fc-9db3-b29b0dbc1de4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-8872-77ae-af8f-22017540299d

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-a218-7117-86df-bcaa14baa34e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-a21c-7e0b-8924-b40ae9a1daa4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-a222-7cc5-9ee5-f5186dbb57ec
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-a227-71c4-975b-141c0d95ec40
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-a22e-7f13-8448-13a13097cf7b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-a232-7cc2-ab4e-46c9c7ba16ce
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-a239-7d8f-8a92-1851b873777c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-a240-7825-8619-533157678c44

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-bacb-7fd7-b0b8-af4081ab6e89
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-bad0-7bcb-9163-77882d866301
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-bad5-7fa1-b0f7-dcd722dffcae
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-bada-7552-8266-c1c63ba7af27
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-bae1-7ed0-b9e8-5ac57bc4e632
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-bae7-7ce9-bd88-33d7be59e23f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-baed-7af6-b3df-7a800feb4b2f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-baf2-7273-a854-0df4b0d95af0

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-cd04-7e10-807f-04dd59acc19c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-cd08-749f-b251-a49263d7a3e4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-cd0f-789f-82c1-981bfbc79bc5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-cd15-70c5-9e2f-04420790bbc6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-cd1d-71c4-8286-b63f54e59341
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-cd21-71a6-8718-59680d4d4272
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-cd26-73f4-8e3e-afc592ab464b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-cd2c-7e40-90a1-95a2ef89f0f4

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-e186-7050-aa9d-389f2b4a668b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-e18c-75dc-9a37-ae87a735e79e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-e18f-7bd2-9756-01f4a12a6e41
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-e197-717c-9591-b558f4cd6234
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-e19c-7846-b5b8-514feb3a9a3b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-e1a2-7aca-8938-4856b6c583cb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-e1a8-7e96-90d1-b343464a84e6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-e1af-7d23-ba92-c341fa6d1441

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-f3d6-754f-ab09-ce9fd27734ae
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-f3dd-747c-a3d7-35c75d7ae7ff
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-f3e1-7f2c-a51b-97deb4b69930
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-f3e7-7b4c-8866-b005a181bdba
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-f3ec-786b-953d-548ba5066d89
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-f3f1-7757-aedc-46eb03c68544
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-f3f7-7d2c-b6e5-515048424617
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d3-f3fc-7d5e-8349-a39c6e583bc5

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d4-0a7e-70dd-a798-835d1eaa18a2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d4-0a87-7693-a76d-7911f40e45f2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d4-0a8f-7a7c-b2e8-114f76456114
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d4-0a97-7a82-915a-e7cff9b6a8b4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d4-0a9f-75a2-ac4b-6519e01e401f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d4-0aa6-7eff-b556-036b4df648d3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d4-0aae-7a8f-b62d-737c4e72baaf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d4-0ab6-72d0-95c9-ce9ed9970b6d

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d4-1f9f-72fd-9d21-04a299adc197
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d4-1fa5-7770-9a85-b9a5f1253b04
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d4-1fab-74d3-bb3f-06e78ecf1620
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d4-1fb1-73a7-9506-bba4f09e4e14
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d4-1fb8-7173-87f9-01744fa24748
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d4-1fbe-76f0-b9bd-2a70e4b5c4fb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d4-1fc2-7287-ab42-6942fb97f9df
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d4-1fc7-74a0-b6cd-55aeb1a761d1

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d4-34f7-7299-b918-4f2b8435491e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d4-34fb-7479-9764-77788bc9b22d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d4-3502-7638-a4e2-01a3a2dcbfb9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d4-3509-793e-8044-a80106f985a5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d4-350f-77be-87bd-79398e4eb6c2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d4-3518-78da-ae55-7afe45ca4afe
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d4-351f-72be-80e6-058c490ff1f6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d4-3526-72aa-916b-21a9f0a1380f

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d4-4d25-7133-b4bf-73f4bf7dbe39
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d4-4d2d-7663-a1de-1d125c152336
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d4-4d32-7fb7-8788-36c9a88be452
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d4-4d39-7c25-8e65-cd3cbb8b5c49
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d4-4d3f-7bc8-baca-66d375d87d12
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d4-4d44-747e-b86e-d001f5645d0e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d4-4d4b-736a-b37c-03dbec2f740e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d4-4d51-7d01-a129-f5a7254cec10

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d4-6427-7e5f-93ce-559b79d6691b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d4-642c-7d29-8404-5e627bcee226
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d4-6431-7586-927b-d041e17ca85b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d4-6436-7bfc-b03e-aaa6912693b3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d4-643d-74cd-9708-c755e049a5b1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d4-6444-7eae-8e6b-f5ba7bf6cfd5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d4-644b-72db-b596-d973913d95d8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d4-6452-70a8-98fe-9ab8698e2f43

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d4-7a60-7695-8053-58758cf4292a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d4-7a64-7923-a714-57239bef107b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d4-7a6b-751c-b69b-81fb58cd14ae
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d4-7a72-775b-9712-f649971eba8f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d4-7a79-7a91-9cb5-96959c7ec907
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d4-7a7f-7b77-a8dd-7e295a8be06e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d4-7a86-76de-b76e-6234b4506581
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d4-7a8b-7321-b378-1b240a269cd6

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d4-9df6-7d22-9997-ac5cb14e54df
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d4-9dfc-7e4c-b8de-2d9995cdb87c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d4-9e03-7ee5-a54a-fbfb8a0202c5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d4-9e09-7cd3-ac93-881d4af6da38
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d4-9e10-7412-b8c7-ffc7ba42a290
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d4-9e16-7fb5-a4e8-0e5511ad974e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d4-9e1d-70a0-a71f-4969e428ebce
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d4-9e23-743b-9445-6cd912a384ac

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d4-bde8-7733-b163-271624e5f441
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d4-bdec-71af-a6f7-09030ee686e1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d4-bdf4-7ef5-b093-837ce26294df
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d4-bdfe-7d57-b17b-b16d14496f04
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d4-be03-74fd-a2a0-888125562e2d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d4-be08-746c-958d-07d2263e8453
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d4-be10-752c-a797-de01dad71249
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d4-be17-70c6-87c8-113fa4d18436

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d4-d4ee-7195-8257-c2b50b14b30c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d4-d4f6-71c6-8f85-fe53d13f95f8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d4-d4fc-746d-8c98-5734554f676a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d4-d503-7b47-8411-984c77e90037
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d4-d509-72b3-816d-bb979a352e04
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d4-d510-7eb5-b232-1a22a65cd3f8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d4-d515-796f-9848-f33372d2b309
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d4-d51b-79fb-a7e8-219996de68e6

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d4-e857-70c7-bbba-9e579a22e3f7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d4-e85d-7168-8b46-5424a81718a5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d4-e865-726d-80a4-d1f3050edd13
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d4-e868-78fd-9a0f-ff48592a5830
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d4-e86f-770e-b544-30a28b995c56
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d4-e877-71f0-8022-df671a46f8d3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d4-e87e-7f76-8305-763060b3ef5c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d4-e883-7f76-9d77-77d4a17b0c59

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d5-1153-73b2-bd22-c3cee7e1dd6f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d5-1157-7dce-8136-9c7708c9f2aa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d5-1160-7c24-b88e-704c8695d53d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d5-1167-7fa1-b442-0df7b510b43e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d5-116d-75f0-82ca-d70cd00b476a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d5-1174-74d4-8d9b-09c74e3adc06
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d5-117c-7c5d-aae2-a5021399494c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d5-1184-759c-8479-68aeba5b4ef1

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d5-29aa-7d81-b442-6a3b5fc0c64b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d5-29af-7c24-a01c-160eceab3461
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d5-29b7-7d52-ab5e-34260101a910
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d5-29bc-7b11-9ce4-e39a41a09030
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d5-29c4-7a64-90a2-970d57862a75
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d5-29ca-7dea-b3c1-0a701ce1588d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d5-29d1-7c35-9c60-39d103ebe4eb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d5-29d7-7db3-a9db-699914f79da3

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d5-4a41-757b-b913-b31bdf9a738f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d5-4a44-796c-b1fe-cf0568fb0fdb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d5-4a4b-7714-992f-f3e0758eda1a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d5-4a51-76af-959d-3abf903d5a3d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d5-4a58-7960-94af-808c8b1b4398
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d5-4a5d-71b6-b85f-c639ed6616c6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d5-4a66-761a-9617-0e231a2c0c93
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d5-4a6c-709f-bf26-d3308780c798

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d5-62ef-769f-9968-c039828b77eb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d5-62f6-72e7-901b-040ea5acff75
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d5-62fa-73fb-92b4-d916ef34d9cf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d5-6301-77f7-ba4b-a21595d22dbe
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d5-6307-72a0-af3a-aeb2a26e07c6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d5-630c-7b06-98d8-0e6196c82377
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d5-6312-7b23-85f2-93c07a729f89
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d5-6319-7a10-bfda-3f30dcaaa3e3

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d5-7ca1-7b98-abcb-fbf7afee7ed3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d5-7ca8-7963-bb4c-f573fd37084f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d5-7caf-7ef7-9e79-c80e03adf26c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d5-7cb6-72a5-857f-d8e60c2ca53e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d5-7cc0-7d75-a514-eabf4e87d04e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d5-7cc7-7e59-af88-b1f58c3e991c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d5-7cd0-7d5e-bb28-caac40946c94
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d5-7cd5-7e8d-921a-5991aca76ad7

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d5-926f-773c-a4d4-d95289946f9a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d5-9273-7ba8-8836-ad06ec9ef389
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d5-927b-7de1-8491-f701f5d9e99f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d5-9282-7c22-ba3e-ca1b3f4645d7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d5-9288-7dca-9f0d-2f149269897a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d5-928e-79dc-85ec-ca81e07abaec
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d5-9294-7e5d-9d25-de78b05c39ab
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d5-929b-70f8-9d55-e7863e20f489

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d5-aa83-796e-92e7-7d2e9f62575c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d5-aa88-70ff-957a-cb5f9a09421e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d5-aa91-78e2-b5c0-569edfa321ce
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d5-aa99-75c2-bc3f-49acfae454bc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d5-aaa0-70ad-9cbe-5ad968d41027
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d5-aaa8-789b-aa41-14881c3a2706
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d5-aab0-7971-9342-a8df7db7acf1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d5-aab9-716e-829f-25a349a914f5

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d5-cd38-7006-a0e0-759ec9bfc3af
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d5-cd3e-7e35-a9c7-40b8e986968e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d5-cd48-720b-b8ca-5cec0bf467e3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d5-cd4f-7783-82d2-06f5780ba6aa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d5-cd57-7a5a-98a0-120220071928
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d5-cd5d-7da6-bfda-b5a22b90b2e4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d5-cd65-7aaa-8800-7310ff6f7d45
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d5-cd6c-7941-b456-4e4c4b6c942d

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d5-f440-71f0-a718-e3323bbe203e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d5-f444-7536-882a-1a062a3a62c6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d5-f44c-7854-b827-2025a544da6d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d5-f454-7d57-87d9-3822a222416e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d5-f45a-7319-b982-db14d4d4650c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d5-f463-7269-82d5-ba2b85debf6d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d5-f46a-7613-a458-449d74b991a8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d5-f471-79b5-9bf1-0f5fef89cdb4

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d6-0d18-7d3f-a841-c6079652b731
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d6-0d1c-7ca5-b2a4-07ef5c8d7614
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d6-0d23-7dd2-a2ce-d69532e02757
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d6-0d2c-7f1b-9e3c-835811f4dff3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d6-0d31-78d5-8988-ee5ec0986e7a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d6-0d36-7780-9b5d-1184c51765b3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d6-0d3e-7cd4-949b-ff8ba680bc98
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d6-0d44-7705-bf5d-c7c3228a595c

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d6-2257-76d1-aaf7-458ba13ba5b5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d6-225b-7be4-95dc-674eb91614ab
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d6-2266-7814-b0d3-83a2c36422fb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d6-226e-7354-85f0-c150de7e66b7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d6-2277-73fe-bac9-12baaa1bc79c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d6-227e-7234-b0cf-08afc2712583
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d6-2286-7d9c-9a84-d1d0836e1f56
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d6-228e-710a-9a85-291e1d2cd52e

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d6-32bb-7b0e-bca7-4f9e8667d1cb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d6-32c2-7c28-9ad5-2968ff878702
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d6-32c9-7f75-a551-488c0be73f1c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d6-32cf-7c58-9d56-d18f77f3a07f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d6-32d6-7ed9-a1e1-88d7fd4d6620
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d6-32dd-7077-838d-80034652d9be
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d6-32e4-7058-aa49-773898ed07bc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d6-32e9-79f1-95d2-a19c751adf64

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d6-4976-7b2f-a291-4e6686330e46
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d6-497c-7bf8-937c-934775a19b40
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d6-4985-76db-9307-a6afa2bea07f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d6-4989-724d-a4e1-1b2f4823c55e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d6-4990-7ae2-afca-24347afb67aa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d6-4998-7ec2-9c5d-b8bee39cb303
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d6-49a0-79af-9ee5-5e8bac8f4ac2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d6-49a6-756a-a152-000cd6eb217f

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d6-6274-775f-8dbc-bd304362a8ce
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d6-627c-7b1a-9b93-93ca13544867
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d6-6283-787d-88d1-3eea17a7d75d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d6-6288-7be3-9afd-af3ec31b0350
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d6-628e-7d80-a31e-52afa9c64b92
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d6-6295-7b8f-929e-878cc8d1be94
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d6-629d-7512-92a2-f1c9a9f001c2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d6-62a4-715f-a2f2-f94a1f74c069

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d6-7fc9-78b4-a927-877f75c6f1f6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d6-7fd1-76fe-a24a-5d6b553df242
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d6-7fd7-7d0d-9835-f29be0cd8609
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d6-7fde-7d05-907a-c64e88410c6c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d6-7fe6-7462-9bb6-7ee60819b121
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d6-7fee-7cec-b18d-521621ad2e95
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d6-7ff5-7343-8e71-813ea0ea02b1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d6-7ffc-788d-b8d9-0151215c1861

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d6-9e71-734f-92e9-3826faa1a85d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d6-9e77-7fc8-918b-1e5c33d88df2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d6-9e80-7de8-ab96-34848b87b3a2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d6-9e87-7bf0-9eb7-853ab1e06e5b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d6-9e8e-7bf3-92e4-6ba048c3ec5f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d6-9e96-7d18-b291-c15c0df6db5f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d6-9e9f-72f2-9734-af70c0c58b50
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d6-9ea7-78fe-bdb9-51dc7aa0324e

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d6-b353-759b-b800-c53947276519
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d6-b35b-7c27-adc9-0fac15f3ec3e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d6-b361-7dd9-afcc-9e10b99c217a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d6-b368-758e-95c9-98dbfa71ad1a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d6-b36f-7ff9-a68d-72831fc08322
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d6-b375-77e1-a349-a0a97e22a797
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d6-b37e-72e8-a1dd-1b165d4b1d65
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d6-b383-70e8-a400-09a80b07095f

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d6-c947-7030-b729-39262965a9ea
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d6-c94a-782c-9b93-8f9ed2e51254
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d6-c952-72c9-8c9d-9167b5d98beb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d6-c959-7243-bc45-5cb6da78e1f4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d6-c95f-71f0-b66f-bd57a4c63c5a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d6-c967-7eae-bb67-57473a20302f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d6-c96e-7c64-821e-028ce47bd6fa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d6-c975-7b88-b77c-9002b0cc0e5a

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d6-e99b-79f9-8b23-6e882e46cbe8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d6-e9a0-7719-a63a-6175789cb8e0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d6-e9a7-7816-8d55-99538df579f8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d6-e9ae-7316-81e2-5aec6402e7de
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d6-e9b4-73e2-90ec-fb93dd83b14e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d6-e9ba-7ae8-8d15-fc1205a83561
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d6-e9c1-7aba-93d0-d3beb764686d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d6-e9c6-7241-9e6d-3b1ba20d79a1

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d7-0211-7c3c-95ee-6e0b286255fe
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d7-0217-7ccd-97eb-23bf8134f345
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d7-0221-7861-aa36-70072b37b64b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d7-0228-7d79-8c14-7252218cbc93
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d7-0230-7894-9513-d8dfe75cebfa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d7-023c-77ac-bdb0-b28ca6ee69c5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d7-0244-726b-b270-1bce135e112c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d7-024d-71c3-af46-2ca42f0625d3

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d7-173c-76ed-8396-c9c5bb81d867
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d7-173f-7d5c-84f0-9b8b34f1a9a8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d7-1747-7206-8663-8c5bccf1abbb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d7-174e-7145-9ab4-7508ea4d1de8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d7-1753-76f2-ac95-180570cd2275
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d7-1759-7fd5-9ee2-110cae57df68
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d7-1761-7a3d-9689-28c425c3e62c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d7-1769-7e10-8123-ff5d0eb08883

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d7-2d30-7f7c-9af9-720e5006c9ae
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d7-2d34-700c-a8b0-8ef4c1473f77
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d7-2d3b-70ce-9987-d489a95b38a8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d7-2d41-725e-9c9e-b379e5da20c0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d7-2d48-7d5f-b47b-28b4753026cd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d7-2d4f-7e5a-bd64-baf7ee03f5c9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d7-2d55-7916-89f0-df52c2bd2519
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d7-2d5b-7aba-b976-a9830f55f05f

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d7-465e-707b-975a-0f0e2ef74e44
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d7-4665-7f0f-b8ae-dd17c58e0c2f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d7-4668-745b-9739-5278f27d16f2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d7-466f-751c-aaec-c0a43dc22d47
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d7-4676-7d7e-bf0b-aec135271884
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d7-467c-70d7-9afe-f7c640cfe597
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d7-4682-70cc-aed1-b69e0e313910
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d7-4688-7fcb-bb21-25da725e9044

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d7-5c33-7664-b6bc-1448934fd6b4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d7-5c36-7de9-8b60-06e1bda64419
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d7-5c3d-78b1-8fe2-9d8d0fbb971a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d7-5c46-7e68-9341-97c8c08e0dea
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d7-5c4c-757c-a64d-b8ab538d4ffa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d7-5c53-71a9-9099-53bb37dbb512
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d7-5c58-7def-960a-21eacbb0fd82
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d7-5c5d-7983-bfc9-1bee6035f9c5

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d7-7210-7116-a67c-233e2331b1f1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d7-7214-7c0a-93de-864b9b9ed105
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d7-721a-7ecc-b900-0785b9b8521f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d7-7222-77a2-8aa2-9b652c1d0b24
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d7-7228-7cb8-bc6b-49158dd2fc55
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d7-722e-7a85-adff-82939727c83f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d7-7233-74ea-b541-a9005c008af2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d7-723b-72d9-ba73-3e72d8ed6032

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d7-8473-7a23-9ffd-64ea9288058c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d7-847a-7b10-953c-9d89346a7238
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d7-847e-74af-b268-88c6eb34c6fd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d7-8484-71c2-b8a6-16578e6a55ab
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d7-848b-78c7-ab37-c0478cde7cd2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d7-8490-7532-bde9-1f4f997d5386
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d7-8497-72e4-81a8-4401f224326a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d7-849d-71ef-95ba-fa512f10ad58

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d7-940f-7e88-929f-91f6db370a72
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d7-9413-70ee-b907-846ed2c5ddc8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d7-9419-7ac2-829d-04509fb8366e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d7-941f-7bed-b695-0b91ebaff801
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d7-9426-7a5d-8921-e5fd64518604
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d7-942c-75f6-b7bc-2127cfe38f26
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d7-9431-73fc-93d6-1eee832d809d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d7-9438-7f8d-b706-bd886c839bd0

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d7-b6c2-7f23-a183-ad0af9c8e93f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d7-b6c9-774b-b2a1-45652bd35186
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d7-b6cd-7a04-8ce0-b4cdeefa0534
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d7-b6d4-70ac-9918-6b5da9e24146
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d7-b6da-7ae8-b540-1ba9325ef640
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d7-b6e1-7c83-83dd-2e0763ff7d31
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d7-b6e6-72bf-8587-758aae80e00e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d7-b6ec-7b22-8be0-1a18c2a4beb4

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d7-c901-76d6-ac4f-c724a7b0c38e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d7-c904-7cd2-8777-d93347ddf1c6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d7-c90c-7b55-a02f-aba3f7240830
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d7-c913-7f5e-aa6e-dd875c07d143
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d7-c918-7d4a-a118-9f0999bfc2a3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d7-c91f-75e8-9151-2981591dfb1f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d7-c924-7f4d-b75d-daf31fec6bb1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d7-c92a-7cf7-b5a5-fb1bdb317190

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d7-dd98-7a28-be3c-92f804c471e3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d7-dd9c-7bf4-8ec1-3b115183c356
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d7-dda5-7192-bb07-09baa7fa4e4c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d7-ddab-774f-875a-67fa21a9502f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d7-ddb2-77e1-bbef-c92183536131
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d7-ddb7-7f56-88a7-698980a2895b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d7-ddbc-763e-8044-195500c819c6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d7-ddc2-7c49-a98d-c27df5792cf3

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d7-f34a-75fa-b657-07f8faa65a8a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d7-f34e-7ba1-bfda-39432e62f162
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d7-f356-7031-b480-98d020cd4924
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d7-f35c-7909-ab48-92b6ba07a033
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d7-f364-7323-a6e3-0fdc791d71ce
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d7-f36a-78b1-bd55-164ff6177d4c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d7-f370-7c5b-8dae-c3d5f5d289bf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d7-f376-7b7c-a3b6-d04476b4b587

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d8-03db-7d02-a4d8-43b82337bf57
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d8-03de-7279-9492-90c9b7a5c652
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d8-03e8-762b-af86-c061186209f8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d8-03ed-7b67-9457-1638d7a0f736
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d8-03f2-71c3-b79e-6a72e9a73d25
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d8-03f9-7cd2-8c96-18d404156200
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d8-0400-74a5-9fad-098cbee7265b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d8-0407-7afc-bd89-90e319fcd568

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d8-199a-73e5-815e-4f8e5d59060b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d8-19a0-71d3-8ab1-144c0dcf0b31
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d8-19a6-7ecd-93d3-fd27f753a328
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d8-19ac-7745-81f1-b8f756eb0dfd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d8-19b2-7068-8100-ba099c46da4e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d8-19b8-7ea5-99ac-3b0b58d9db25
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d8-19bd-72d1-96cb-2e353a8fced7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d8-19c4-7396-ac3b-83314400290f

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d8-3423-7f07-8940-0f2a68741d0e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d8-3428-7550-9dc1-88307d1071ef
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d8-342e-737c-9791-ec7a482881da
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d8-3434-77f6-b4c5-b26cd76a822b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d8-343c-7f10-9370-06f9f379bbec
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d8-3442-7455-8902-83934d1f723b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d8-3447-7770-8966-9d46d517f438
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d8-344e-78f9-ae35-65e776b6681b

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d8-4788-760b-a974-4860feecc987
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d8-478b-78d6-be1c-ac5b33746d62
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d8-4795-7f58-84dd-e50403dbffb7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d8-479b-7a87-ab61-b91cd1c1c971
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d8-47a1-7b55-b41a-05458e45745c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d8-47a8-72c2-b58d-01ff48548111
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d8-47ad-7115-8054-c8021fbeb83a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d8-47b5-7e04-8985-a1980194a361

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d8-6585-7c8b-bdec-b488a274b7bb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d8-6589-7aa7-8be1-2cf1cb9d2379
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d8-6590-7681-bce8-9a6c62ce5633
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d8-6596-7c20-9607-481fb417b771
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d8-659d-71b2-b70c-6258c272e49a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d8-65a2-7e29-b737-3e03f696596c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d8-65aa-7f4c-ba33-ebb3cdea64fa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d8-65b0-7608-8dca-424505531915

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d8-7b52-70ce-b1da-f5af9691dd89
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d8-7b56-71b3-909d-c5c1737f60e8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d8-7b5e-79fe-9af2-5d3f587284b4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d8-7b64-73e4-9057-06494321912f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d8-7b6c-7da0-9b29-44d27ffc3482
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d8-7b72-7cb1-ab4b-38ad0457babc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d8-7b79-7ab3-b9bc-71af5fd10562
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d8-7b7e-7485-bcf0-64fe31cb2f95

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d8-88b1-7398-a804-f62985c3620b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d8-88b8-7c5b-a2d2-dfc9f8016095
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d8-88bf-7a51-9841-2c0a55076af9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d8-88c5-735e-9a2a-ad09ddc84af9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d8-88cb-7782-999d-66994b1e2820
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d8-88d3-766e-9265-cea0411f272e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d8-88d9-77c7-a385-08254cea30ec
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d8-88df-7914-a6d0-4d6d04882ee3

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d8-a426-7de3-b24e-47d1d01998e6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d8-a42a-706c-be79-933d0e7e8cf0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d8-a432-7b7e-adcc-7c1f636bb9ca
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d8-a439-7823-ac8a-44e183cb0a94
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d8-a440-7340-b15d-258ee56bfbfe
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d8-a448-7403-8ebc-73e365e046b6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d8-a44f-7695-9da7-3a83e627e870
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d8-a455-7ddd-93bf-8c730ffdc2e7

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d8-b88c-71ff-ba27-56d568129765
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d8-b893-7e69-aecf-4da6ed7736ed
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d8-b899-769d-8703-cc3002ef1e55
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d8-b89f-70e4-9b98-27f729c46fde
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d8-b8a6-71bf-b427-e5ffa1083605
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d8-b8ac-7a38-a192-e7138ca2e601
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d8-b8b1-7df0-a5e4-30c79c813014
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d8-b8b7-70f4-95b2-29051f3373e6

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d8-d639-7d3a-8768-28176ec9bd4b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d8-d63d-7f41-b78f-c1284750d925
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d8-d645-794f-a1c2-1e21b301aaab
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d8-d64b-7f12-972b-5835a3be3fde
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d8-d653-76bc-8fb1-92cd6771b4df
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d8-d65a-70c9-92f9-4042fa156145
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d8-d661-764a-af33-08456643bd7a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d8-d668-7342-9e09-6c11aef54c0e

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d8-eec2-73d0-ab79-7810c2b8ce20
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d8-eec9-76d6-98d6-afd57d744b2d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d8-eecc-7c4a-85c7-1a8837bb19fb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d8-eed2-788d-93b8-d6f5c9cf307f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d8-eed8-71b5-b294-d32f0f3e5452
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d8-eedf-7b5d-8267-2158dd26d680
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d8-eee5-718e-b070-688439f79709
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d8-eeec-75b8-8bd5-bc9bdc22fe98

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d8-fc77-7f98-87e4-83e074c45b1d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d8-fc7a-77b3-93f2-3e89cda54aec
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d8-fc82-7bad-aee1-bb7871685361
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d8-fc8b-77a6-b3f1-b3b1938cea79
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d8-fc92-7492-8f69-2a5c762a00f3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d8-fc9a-7fc8-9dc5-f15f6611ca2a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d8-fca1-7fea-8c0c-262f8d80df20
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d8-fca8-720b-80cf-31878c2a0f57

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d9-1556-70cf-ba3f-4fd5c3c9d1ba
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d9-155b-730b-af04-d6d5f976d16a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d9-1563-7f96-a1d0-4efb811312d8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d9-156a-716c-aa35-0140febb215f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d9-1571-7e1b-b656-5751db324e33
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d9-1578-72f1-adb0-b5d4b79c53e9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d9-157c-7d4c-b97d-d1c3e9df7a9c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d9-1584-7588-b630-ca2477eb46bf

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d9-346f-7808-b475-4aec31b0f91c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d9-3473-76f1-881d-19a4e48781da
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d9-347a-74c2-8554-6947618598a9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d9-347f-7808-bec4-70ebdfc4cf75
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d9-3487-7d77-8b43-ef65813a1dcb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d9-348d-78cc-8b1a-c79a6be4f31e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d9-3494-7cce-bd36-fad1a478fd96
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d9-349b-7ea8-b9ad-d6a1f65459f6

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d9-45b2-762e-8800-241a42c91176
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d9-45b6-7514-bf2b-0a6ddc69f349
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d9-45c0-76ba-91e2-6f3598bff463
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d9-45c6-7ca9-96fb-b8fc875699b0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d9-45cf-74d8-a722-7cc47cb4422e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d9-45d6-722b-aed3-fac5bc34d180
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d9-45dc-7598-8938-051d0045736c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d9-45e1-7e8e-ac94-50081f4e9901

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d9-60aa-71a4-a50b-e3e4fc4ebaa2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d9-60af-797e-8933-fb6ddea7b058
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d9-60b7-7b01-be50-bda2e26a99e8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d9-60be-7638-a9cf-883a1859dd35
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d9-60c7-7455-8c0d-6ab494e5c589
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d9-60cf-7d4c-8c77-1e0fae135ea1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d9-60d7-7c88-87e1-da0c6cece398
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d9-60df-7be6-9978-871f4588ce76

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d9-73db-7f1b-80ae-7afb6d2f9604
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d9-73df-77b5-b36c-354b8e1ae0f1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d9-73e5-70c2-a66c-06177f123c7b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d9-73ed-7c3e-b68a-9adbb437119c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d9-73f3-7a5c-a896-a9c9781bab5f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d9-73fb-7fd5-91fa-5315f614aec6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d9-7405-7ff9-bcc8-0af02463a165
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d9-740a-7692-9cbf-c7e0b36b813e

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d9-8d88-7a92-99e1-2372915cd4f9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d9-8d8e-74fb-bc0f-35133199b692
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d9-8d95-7c79-8d18-6734f7f9a498
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d9-8d9b-762d-9779-244cf7746c32
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d9-8da4-7bb9-9347-1fa2c3d93362
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d9-8da8-76e2-b18a-b009ce7b191f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d9-8dae-73cc-9346-3fae3805c7b6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d9-8db4-7cbf-bcac-fc0bf132f496

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d9-a214-71b8-9db1-30d503cf810c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d9-a218-7a86-ac0f-59eb400df881
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d9-a223-7873-9c88-372940086871
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d9-a229-7dc3-b88a-bc736482613a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d9-a231-74e6-8b05-1088eb637e82
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d9-a238-71a5-9550-efb12850521f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d9-a242-7870-8b85-2d92aaeb1126
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d9-a249-7988-92d8-bb7e0bb57242

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d9-b666-7dc4-b721-bfc3b64479e7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d9-b66c-79b8-8ff2-14873ef671b3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d9-b671-7411-8815-f86699f99890
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d9-b67a-7be1-a472-be0d757b290a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d9-b681-7df7-96a6-f6c14026fc65
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d9-b688-7cdd-bf90-b6e2d7800636
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d9-b68f-738f-8e15-0496ef5fbd34
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d9-b696-796b-b948-70c8d6a08be8

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d9-d22c-7f5a-8a1b-371a4bcdb005
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d9-d231-7aa6-b27b-108997daffad
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d9-d23a-7538-9c21-2a5dbbba7839
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d9-d23e-79d3-b30e-0682ce56cf7e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d9-d246-7fc9-a4ca-df91f9e1b9b0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d9-d24b-751e-8a94-07671bdd94c3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d9-d252-72be-89db-f19f8609a1f5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d9-d257-7cd8-9715-1823bd06e987

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d9-dd88-7243-914c-6519db8a7cf3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d9-dd8c-7fb1-9c30-823603308df1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d9-dd95-7bdb-8ffa-3b1234d9c384
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d9-dd9c-7a6a-9011-c68a5310d164
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d9-dda3-7328-9f89-57bfdbbcfbea
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d9-dda9-7f04-b404-33c2d8440345
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d9-ddb3-7c8b-b7ae-5d65d2c6138e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d9-ddb8-7498-9938-1dbeb567ee36

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d9-f55c-7a8d-bc16-14157ee8dfb8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d9-f560-7994-b891-29700d6bfae7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d9-f567-7a8c-ad76-82d2baac8048
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d9-f56f-7854-9d48-19582978e5d0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d9-f575-746c-991d-7e1936327def
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d9-f57b-7fd4-9851-595b6fab391e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d9-f580-77b3-af9c-b3aef675539a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1d9-f587-7e74-b406-a19fe7e2ff32

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1da-05f9-7c82-be9f-b4ff71c81ea9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1da-05fd-7f72-b77e-74122d49f748
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1da-0606-7842-8c33-815656619c38
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1da-060f-7929-95a9-13e05c5b66e9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1da-0615-78fa-ada1-6bb4e6bb05c0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1da-061b-7dcd-b879-0cc731c2ef77
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1da-0622-7c87-ba8f-376e7c412166
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1da-0628-7443-97ec-0554c57dc969

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1da-1897-7af8-bfd4-034d7badb0b5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1da-189e-7652-baeb-c432cf7a5c41
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1da-18a3-7109-bdd9-8bda72ba0fcf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1da-18a7-7860-b1d5-98d6d2ad2bef
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1da-18ae-7f39-8458-8c4853870aa2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1da-18b4-7236-9a5e-a09b2a60383a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1da-18b8-7413-baf9-d6108f8f46a0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1da-18c0-7680-90a5-b6a4d80445cf

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1da-2a39-7b80-b7aa-b078dd0b688a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1da-2a3f-79e2-a0b5-7e002b558385
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1da-2a46-7736-b3d3-4121685b8e23
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1da-2a4c-705f-b543-395e7b4b6a48
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1da-2a53-7925-ab60-59cb117c5551
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1da-2a59-7e9c-a34d-b6176fed91f9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1da-2a5e-7e05-9a5c-b7a0de28a066
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1da-2a64-70c5-9398-55e7993dda26

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1da-44a4-7803-a836-8e12d3c67419
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1da-44ab-7936-b867-088be8cbb65b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1da-44b1-708b-8200-7dc81360c32b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1da-44b8-71e9-9774-b120c4df18c9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1da-44c0-7838-8407-d4ed29138ea5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1da-44c6-7c66-9e93-3723fbf1af5b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1da-44cb-79ff-914b-fb026e64cfbb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1da-44d1-7c9a-b500-62195980ee45

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1da-59fb-7ed2-acde-30cad8aea418
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1da-59ff-7737-b7ac-b9e7f1b2d273
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1da-5a06-77e1-9b26-e0125ce6841f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1da-5a0d-776e-9085-930eac5dc52d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1da-5a13-7e36-b8c4-7270799cfee8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1da-5a19-7e1e-b40e-bbe0161950c4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1da-5a21-7bb7-a7a9-04dea6ea4988
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1da-5a26-7c69-8550-2300f33ef39a

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1da-6f7a-794f-8dbc-879c60c712fd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1da-6f7d-736c-9962-6bbf7e55687d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1da-6f85-717d-996f-bffd50f9f938
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1da-6f8a-770d-b577-d9f483176ccd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1da-6f90-78a8-91b0-ac7465c6d551
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1da-6f96-7afb-82cc-2681a8028315
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1da-6f9d-7d3a-9799-288af6faa045
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1da-6fa3-7cbb-84a5-534142ac5b95

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1da-85c5-7b77-87ce-9b491c2863cd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1da-85ce-7e52-8019-8f3feec8524a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1da-85d2-7365-9298-d939de1b87e0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1da-85d8-7bbb-be1e-365fd837d5ab
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1da-85e1-7291-8b13-ca1aab28d9b9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1da-85e8-723e-8863-509744e1ec0f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1da-85ee-7b62-bea3-b217208f860b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1da-85f4-71cd-be1a-71dafb276924

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1da-98a9-7a72-8786-0eda258d54bc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1da-98b0-7037-8601-77b9b53f4fc5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1da-98b5-75f4-b93f-dca070001bab
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1da-98ba-7a8f-8019-79feccc030c0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1da-98c1-7763-83c9-39ff92c1894e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1da-98c6-7fa7-8641-975dfea5b9c7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1da-98cc-797e-bce0-21f1c9178baf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1da-98d3-77da-afbc-9664eec636cf

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1da-b9af-7bb7-883e-e71c50709793
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1da-b9b3-75ec-89fc-d59763c7a472
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1da-b9b9-70ef-9507-47169fed0f97
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1da-b9bf-7cc3-9689-374712325653
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1da-b9c6-771d-afa2-f40972e90b09
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1da-b9cc-7cd9-914b-c7563c6e1b23
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1da-b9d2-7994-92bb-3fe0029a6e83
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1da-b9d9-728c-9b3f-aba5b8227ab3

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1da-cec2-7698-8232-7474a4ed2e84
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1da-cec6-7f08-8c90-186bc6eb8145
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1da-cece-7953-b8d3-c5cd80157d43
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1da-ced2-72fd-9dc7-9f38318dc994
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1da-ced8-7ab9-b610-f3d607422e2f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1da-cede-7743-8857-21eeaf16eb34
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1da-cee5-7410-97ea-a4fdafe70bc2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1da-ceed-7880-a00d-8aa9313d5f4c

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1da-ebda-77cf-8239-50cb473b61ab
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1da-ebdf-7c4d-8b22-c6e0f5d6b83d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1da-ebe6-72ce-a746-e4c954a1d44c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1da-ebeb-7bbe-b538-b285d682eb7d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1da-ebf2-7267-8a5f-a21790b68a27
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1da-ebf6-7d3b-b060-2855fc93ebde
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1da-ec00-74fa-9c44-438547c5c2e6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1da-ec06-768f-bbe9-146824d773ad

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1db-07cb-7187-88b8-b7e82af59e09
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1db-07cf-7221-b78c-6140e3c78c80
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1db-07d7-7c42-9348-0a33322b6178
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1db-07dc-7ca9-8483-212c8ae1d548
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1db-07e2-7250-a582-60c893eca4b1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1db-07eb-7fd1-afe5-d15ecf112cc1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1db-07f3-7ecb-bdd9-90e75d9c07ee
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1db-07f7-78e9-bb3c-bad851adf94e

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1db-1f2d-72c2-b695-6dc0298ff710
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1db-1f31-7dee-8cbd-d137160730a0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1db-1f37-7ce7-bce6-688cac5f8da5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1db-1f3c-76ce-835e-844129d776c8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1db-1f44-71b7-8ab3-f3b02bad3e49
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1db-1f4a-70a7-8720-44ce731bf307
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1db-1f50-7d99-bc10-ab2da7014b6f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1db-1f56-7901-a722-9aade29e224e

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1db-40d1-7b0b-a6e7-291d40600a89
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1db-40d5-7756-a462-9c5ce685408c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1db-40db-7377-86b5-0dab3a2fa95f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1db-40e2-74b8-bc62-cacb320942eb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1db-40e8-722f-afaa-3d240923c662
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1db-40ee-71ec-b167-343c5dbad804
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1db-40f3-7a84-986f-f88ab8a5ef86
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1db-40fa-7817-8699-d86890f24b39

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1db-4f62-731a-9cad-333cfb48b575
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1db-4f66-7283-9e76-2ff2c3862f63
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1db-4f6f-7d78-99c3-8740ece083c9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1db-4f75-771c-b862-b58741a3c85e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1db-4f7c-7b78-81dc-3a3b185e47b7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1db-4f84-7699-8113-34ef6d642efc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1db-4f8b-774f-b4ca-58f0e2088c9b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1db-4f90-7e9b-8361-31874a626399

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1db-6694-72bf-a5af-ed528662e8aa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1db-6699-7635-9dbf-6bb9bee6fe3c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1db-66a1-7e40-baed-9fcab5d6864a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1db-66a7-7cd3-933c-34fa575ec773
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1db-66ad-74ba-8b5c-8e4c9a553963
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1db-66b3-785e-ab6f-d51da5ecf24f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1db-66b9-7dc9-96af-751c2a115568
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1db-66c0-7c1e-a192-287c1e7a52bd

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1db-8453-7ff7-9bc7-db0004ff7296
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1db-8458-75c9-bb38-743884362e61
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1db-845e-7403-a776-7d321816e9a7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1db-8464-7f1f-8a8c-0d3b62ed0469
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1db-8468-7426-bfed-d9d926cb69ac
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1db-846f-7cea-ab9a-86144bd38f47
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1db-8475-76d5-b149-a948b08e0a44
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1db-847b-7a08-80cb-b2a9290e620f

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1db-99fd-72f6-9cbb-7ec560babe56
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1db-9a01-70f3-97f8-7acd9be2ac40
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1db-9a08-798c-ab50-36b947379882
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1db-9a0d-75c0-95a5-ca694ddd4432
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1db-9a13-7f8f-8ebf-1663ade48188
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1db-9a19-74f5-bbd4-3ab61f7f8d0e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1db-9a21-70d4-9b26-2989bcefa453
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1db-9a25-777a-9af2-9306b80cc7b5

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1db-b195-7138-b83d-45707eb3819a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1db-b199-7a1a-8ba0-1fef8cb5925b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1db-b19f-7a88-8449-b8fbddfbcc2c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1db-b1a5-70a5-a377-0f93e2ef5e20
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1db-b1ab-7894-a510-8e3f6ebbf7a9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1db-b1b1-71d2-923d-6831dbb52abc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1db-b1b8-7555-a41b-2b0d25f7a6fb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1db-b1be-7ce9-b925-ffcd2b180ab4

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1db-cc70-7127-b67e-2299651b4679
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1db-cc75-7a06-885c-eaa1df8f9d6e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1db-cc7b-7420-bdf4-960fa3e186d0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1db-cc80-7101-bfbe-85c28b0c3db6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1db-cc86-7eb9-a67d-177e43594192
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1db-cc8d-70f6-b4ea-686c65305593
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1db-cc93-7dc4-a587-829157f8ecde
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1db-cc99-73a0-a9fc-9c69cdf2e0f8

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1db-dda7-7f36-a8ca-439f62eb17af
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1db-ddaa-7d33-8f1c-8fc279ea3a9d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1db-ddb1-7464-9335-377b534859cf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1db-ddb7-7ed7-a94f-99fb989af658
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1db-ddbf-7a4b-9242-2a17e58666f6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1db-ddc4-7529-b257-5d0d3b17ad1f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1db-ddca-72e5-984c-78dd9b91cc9c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1db-ddd1-76e7-ab46-7957ce2a2679

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1db-f436-7351-b7a2-51a276bdef08
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1db-f439-7be3-8345-bf20c25964f3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1db-f440-7e20-b832-37137b8ea928
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1db-f447-7c8e-afcd-d6993a7e82c1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1db-f44e-7e65-add4-838aa3b77bb0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1db-f455-7c19-9f0e-46e267c86aaf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1db-f45c-793a-9112-0fa203cbaace
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1db-f462-77c2-acc9-c9de04a6c97a

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dc-0fed-76a8-ae5b-9e9053054843
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dc-0ff1-7127-8455-f159f43f4977
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dc-0ff5-7caa-acbd-2415dd5a7a6a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dc-0ffc-77ea-88ea-d6e3e6fa6494
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dc-1002-7b9c-b679-ca8759a54543
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dc-1009-7d2f-a194-eafde891497c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dc-100f-7ffb-8f6b-ef38ed604b54
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dc-1015-7f54-b794-e81a37ad6820

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dc-280c-716d-aed3-f6fd3a292d35
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dc-2810-71a9-9405-eb175d96f042
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dc-2817-73a2-98fc-7ef145029902
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dc-281e-7f64-a240-2d5efcc8d029
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dc-2828-790a-af7c-768bc102a51d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dc-282c-72e6-88d8-887255d69075
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dc-2833-7bf7-b493-8ffafc91c149
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dc-283a-74ea-96f9-7ddc22c5b409

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dc-31da-79d6-8628-a03d4c0c9fd4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dc-31dd-7541-bc47-47369059c473
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dc-31e5-704a-b798-9372b8a2fabc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dc-31eb-77c6-a49e-ef46fe197adb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dc-31f1-753c-9be7-3c5cc328a993
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dc-31f7-75bb-b02e-0997f9c85602
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dc-31fc-70ec-a705-6b224dda7f40
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dc-3201-7361-a79f-aef7452e9e9d

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dc-4f1a-73e1-9255-2cb533cb980e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dc-4f1e-7bcd-a9a2-9b8b972748c1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dc-4f25-7905-9620-e429a267fa5c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dc-4f2c-7d41-82ab-ef323d380644
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dc-4f32-7a0f-92ec-49089f2ef7f0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dc-4f38-7a02-8e4e-d178014a1b9a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dc-4f3f-7de6-98f7-7db75d6238f0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dc-4f46-720c-88aa-53413a4e9d7d

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dc-6371-73bf-8778-2bd6d25dc741
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dc-6376-70c7-9d0a-8670f39efa4a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dc-637d-7ac2-814a-c9378ce736f9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dc-6383-7ed4-b87c-be19b38e7bdd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dc-638c-703c-93d2-6e41c2db2f9b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dc-6392-7941-b3ec-993b87a7d029
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dc-6397-702d-ab36-e8591b9be2ac
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dc-639d-7529-85a8-1c09d8769334

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dc-79b8-7580-afdc-6f45790ea27e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dc-79bf-72bc-bdb5-f78cca1023af
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dc-79c5-751e-bd41-ad31f2ec5114
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dc-79ca-78a4-95f5-79aac13d333b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dc-79cf-7855-8561-a2caee671226
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dc-79d5-7478-9dc3-c220728c8053
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dc-79dc-7bfa-a3e7-f140d9152468
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dc-79e2-7394-ad25-06ffc9c6ed57

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dc-89d2-739b-b4ba-7d23cb6e7fc5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dc-89d8-7964-8c36-1c818dcdb476
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dc-89df-773c-acf4-f284c37bf664
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dc-89e5-7ebf-9484-37eb01984af7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dc-89ec-7f9f-8daf-d51179cfb3e8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dc-89f2-7f13-8620-af1bd706b78c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dc-89f9-7e39-bfe1-b808e1916c74
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dc-8a00-73d1-bd8c-dc43ec389c7e

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dc-9b15-704b-9636-a63ed0377ef3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dc-9b1c-7b71-9880-ea116aa50bb7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dc-9b23-70f0-8263-f3f270d8e02f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dc-9b29-7a56-936b-936d2452666f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dc-9b31-7701-9205-4e4df0fb6f52
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dc-9b37-739e-a16b-5ee2de7c1757
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dc-9b3d-7567-8152-a4c53a4e4663
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dc-9b43-7e47-ab61-79e1a6f13f9e

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dc-ab2b-74f0-92b0-d02dcf039314
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dc-ab2f-786f-841e-3f7556df802a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dc-ab36-71b0-874b-dec0ac75ed14
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dc-ab3b-71aa-83cf-bbc50bcfff75
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dc-ab44-798a-98d3-3f75cc9b20e8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dc-ab48-7957-8d54-f44279d8d093
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dc-ab4e-7eb1-8041-a26f70fdee41
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dc-ab54-79bb-b052-5b7ecc6298dc

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dc-c00a-7e46-972e-052a2f9dee2e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dc-c00e-72c4-bd9e-ede21004fdfb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dc-c019-7c9e-9237-4acd576fcfc1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dc-c01f-7f86-a3f2-35753a0e4f6b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dc-c026-795a-99dd-d4435f962de2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dc-c02d-7495-a98a-e341aa93231d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dc-c032-7d9c-a2bb-191c4a7e5ea2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dc-c037-7086-84cb-2dcbc68e9f05

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dc-d44e-70f2-afaf-7b080c84907b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dc-d454-7957-abc9-76c9214c96ee
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dc-d45c-70d9-b683-ed10b7cc0d7d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dc-d462-73cc-9d02-e3290ad8d42c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dc-d467-7f18-b431-262204f1c150
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dc-d46e-747c-b5eb-d78a61fc5536
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dc-d472-7afe-80a8-92af5b9a4084
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dc-d479-7aad-bc7e-1437669b5d8c

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dc-e736-730e-97ee-0b5a35f8ceef
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dc-e73b-7e7d-a0f6-d26b8f340e0e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dc-e744-7bc0-9b8d-2ff684dee965
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dc-e74a-7dae-b98f-75d1930a3be6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dc-e753-7b55-b460-7db3e8308d78
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dc-e759-7471-8e86-d8bbd76e7e72
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dc-e763-7249-b183-a1849f6cee9e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dc-e76b-7d7c-b61a-b73c51f42163

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dd-0ba5-787b-9069-db59eb24f995
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dd-0ba8-7f3d-9238-dcf5eeb0d204
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dd-0bb0-7103-8d96-ae3e2e8e464b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dd-0bb6-70e8-bc0c-d72faafd81c2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dd-0bbd-7879-a112-869b07373e01
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dd-0bc3-773e-bd13-48cef7f94e0d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dd-0bca-702c-ac6d-89486b808ba4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dd-0bd0-70fe-88cd-9328d0262c7d

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dd-2211-774e-934f-99765da90411
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dd-2215-7988-b173-776bbb06dfc8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dd-221d-7964-bc50-2c95cbc7708d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dd-2223-77fe-abfd-5851a0f1dff2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dd-2229-7fef-8248-34b278b5a179
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dd-222f-728e-a8a7-c060f0037398
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dd-2237-7a8c-85a5-d9020979a958
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dd-223d-7136-8b08-d5aa6bfa8292

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dd-31bd-7f7d-ba88-178d14582924
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dd-31c1-7657-816e-764d0273eacf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dd-31c9-7024-8939-b9f5e21e994a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dd-31d1-78c4-9788-d07db8981beb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dd-31d8-7d0f-b0f3-561918f1b17a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dd-31de-76ff-a40b-1ccedf5538a6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dd-31e4-7657-aafa-4a8b3bc4c566
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dd-31ea-7c74-abc6-d8284aeeed42

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dd-49f8-7ce3-a4b6-948e320ecd90
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dd-49fc-7a33-b22b-18ab7cadc88d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dd-4a02-75f2-8bcf-ae17a1c13065
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dd-4a07-7ab3-9856-8bae91fd93c6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dd-4a0e-7568-9791-3c8af00187f6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dd-4a16-72ad-a5d9-aa6378e8f177
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dd-4a1e-7877-9adc-107da8780555
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dd-4a24-7ddc-a6ba-71d62d3cf01d

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dd-6031-7e34-b8ed-a296f15f1205
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dd-6035-75f0-b7fb-1a55238e1113
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dd-603d-7522-957b-eb9b75d6a688
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dd-6043-76c4-ba89-c27f5ff11ca9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dd-604a-7e79-aa5d-4183721282ad
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dd-6050-7c0b-9b8e-1506de8d784c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dd-6055-766c-9b15-675b8f28675f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dd-605d-7d82-b040-5838c3bd2562

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dd-8053-7da2-9d03-23ddc48a193c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dd-8056-7134-a1b1-832411666352
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dd-805d-7e74-b350-f01022e675a1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dd-8063-7960-8cdc-22980cbbf82c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dd-806a-7814-ac25-c24d8a84a266
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dd-8071-7ca3-8677-9b43e802bfe4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dd-8077-7323-b160-c672421f7a61
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dd-807f-78de-a6d3-5b8deaf278ac

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dd-93e9-7d4e-bd78-5ed22b938250
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dd-93ee-7902-a566-bba007faabd6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dd-93f6-7c07-8441-21ee49f4f227
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dd-93fd-7a98-a1b0-9174a6fac6c5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dd-9402-7df1-bf03-59be6b90e91d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dd-9407-784f-83fb-f4babb8d5e26
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dd-9410-7f3c-8b31-bec67ef0e3ea
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dd-9416-7eaa-896f-501a17921c58

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dd-a0c7-720c-91d6-5713e37ecb7e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dd-a0ce-71d3-857c-82a639faa8a7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dd-a0d3-7131-ad9b-b10b9d1f77d5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dd-a0d9-7b57-b192-6ca2aec6c3a8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dd-a0e1-7def-a504-32a89e79415b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dd-a0e5-7706-8ebf-e9da43d56e96
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dd-a0eb-7e1f-9186-83939c009adb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dd-a0f2-774e-a8ae-054b61fae73d

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dd-b4d7-7ac1-bdb9-e3788e08000d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dd-b4dd-7218-9b66-04c3469d7483
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dd-b4e4-7c62-8f77-daf2b585e4e8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dd-b4eb-76b8-8cdc-d1fc55c9cd74
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dd-b4f1-7765-9fcd-8d1620a9e1d9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dd-b4f7-79f7-8297-2ece32bd75d0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dd-b4fe-77b8-9398-c956be5b0978
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dd-b503-779f-a5b3-266c98c34a07

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dd-c954-78d3-8fd7-338d76468705
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dd-c958-7697-9773-285aead1889d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dd-c960-79fd-a545-e481345d6043
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dd-c966-724c-b191-22a18180c402
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dd-c96f-7c87-a95b-1f30388b7dd7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dd-c975-7b77-957d-8aafb4131905
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dd-c97c-7bf6-a866-eb61edf228b3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dd-c981-7197-ae59-e34d91e2396f

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dd-dcde-79c9-95cc-67c497a38d07
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dd-dce2-7b2f-a924-0b5ce33289d6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dd-dceb-70f2-98b8-b880d1c0cff2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dd-dcf2-7182-8747-5995472ed579
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dd-dcf8-7a46-b79a-067ee650c18b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dd-dcfe-7f3f-a36e-cee1db181d60
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dd-dd05-7338-a14c-06ff82f40407
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dd-dd0a-7761-93e2-99496605581f

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dd-f526-7e24-a689-90d7f25dd62a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dd-f529-7899-b961-181acd0c43a9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dd-f531-79ba-b8df-e2c5e69ffaa5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dd-f538-7ad5-ab95-204bdd35956d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dd-f540-7f9f-bf40-ab057a92f703
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dd-f548-7394-bb6f-c5e572868192
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dd-f550-7c71-aeec-02d5a9398934
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1dd-f556-7400-b4a9-76c52dce4bd3

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1de-0eed-7183-974e-04a21491bded
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1de-0ef1-7e90-b843-913a3d56d747
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1de-0ef8-7340-98c2-e23452d28761
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1de-0eff-7c28-b4c1-0748cc0873e2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1de-0f04-78a5-986b-b57371ea00d3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1de-0f0a-77fe-aadb-7fc684713d8e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1de-0f0f-772c-805c-3fe53eb8e438
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1de-0f15-7fbd-a05e-542ed8d25e37

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1de-20cb-736c-b0d4-792a6e9b0791
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1de-20cf-7e00-a422-fb817a85b6af
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1de-20d7-72be-b4ec-3d2b0cc635b8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1de-20dd-7d05-ac2d-f37c73d33ef4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1de-20e5-790d-b04f-13a2d265e2c1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1de-20ea-7a0d-bdd1-de5863e1b23f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1de-20f1-7f2c-be3e-3553972d8dd8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1de-20f7-74ae-8227-6daa03b1c1c0

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1de-360a-764c-8a7d-e97e2ff3499a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1de-360f-70bc-b3f7-1debe0b332d5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1de-3618-7345-9559-bb02ed1bab93
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1de-3620-7cf2-ab03-8a6de5f1ae94
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1de-3627-79bb-b23e-f413b619ab46
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1de-362e-7b5b-932e-6fde70f13d5d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1de-3634-706b-b7a6-62e4dbf17ca5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1de-363c-7d14-b7f4-327187a92180

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1de-536d-7fd2-a646-d2678dd690e1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1de-5372-71c3-b2e9-337313be1c6f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1de-5379-745d-9e70-3fce4e94fe6a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1de-5381-7233-ab0c-01ac19ffde0a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1de-5388-7134-afae-251a6535b63e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1de-538e-7158-a4d5-a94788e71b6a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1de-5395-7dcf-a758-d2583ed81e53
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1de-539c-77e8-861f-8da7817dafba

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1de-70fa-71fa-a810-feb8ae1c2f6a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1de-70fe-7bd6-9a9b-dd7ce8e05a06
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1de-7105-7785-80f2-2e727c01753a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1de-710c-7505-aeed-3b8fd8956af1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1de-7112-7660-93f0-53146752a2cc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1de-7118-7bfc-af26-8183a59e989c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1de-7122-7199-99b3-cc97dd274eca
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1de-7127-720d-af20-5c47054a6d76

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1de-85c1-7987-ab5f-68724150f51f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1de-85c8-72dc-96a4-f39baccc0e54
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1de-85cd-74f9-a222-7ffd77195d4b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1de-85d1-7282-8125-6e31e7ab08ff
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1de-85d8-75bf-8e6f-7bc6138a1274
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1de-85df-79dc-87db-b586df35d691
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1de-85e5-7680-aa93-57f6e497d1a8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1de-85ea-72bc-b177-8d4ad643c407

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1de-a61a-7433-8894-c88c95a1cd64
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1de-a61f-7f3e-94cb-950d6555a3d0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1de-a623-7821-9434-18af1f0a189a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1de-a62a-77c6-98a6-c7882127d7d4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1de-a62f-75ee-b940-15702ffa16df
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1de-a636-7b37-aa72-1850c4e0b70b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1de-a63c-7a2a-9ab8-618187821508
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1de-a641-768c-a270-b2e964ea71fa

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1de-b51e-71a2-b4ee-ed20cf5217f5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1de-b522-76fd-931c-e077b462521c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1de-b529-76b6-806e-35b849338856
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1de-b52e-7f5f-bd2d-9af067f2b49f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1de-b534-70a6-b70d-3c647778593c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1de-b53c-78bd-b2cd-89b396aa0fa6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1de-b543-749d-b420-30964e054013
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1de-b548-7e84-be2a-ea1913521da8

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1de-c8f8-7d7d-bded-dce4172f166b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1de-c8fc-743d-a112-38d684c3c350
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1de-c902-7a5e-9bfc-ecf7a6a47e09
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1de-c909-75b3-a913-c879cdcd8154
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1de-c90e-7d17-854d-8574a48ee115
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1de-c916-76fc-955f-5c9f6597304b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1de-c91e-7acc-b4d1-ba72cf04239d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1de-c923-7367-b89e-51bd62295075

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1de-d9ec-79dc-8698-0116d8c5c706
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1de-d9f0-7a85-9ecd-1874b0e82888
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1de-d9f7-75b9-9d04-e65f8fffffe9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1de-d9fd-7d0a-b4f6-fab2cff18aaf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1de-da04-7167-8b8b-aa3771504d61
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1de-da0a-7b06-b5cc-1a949f7b4a16
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1de-da10-704f-81c7-288367e209dc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1de-da15-7f90-a79b-9d5e847a3ff1

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1de-ed3b-78b4-bf63-f565017798a9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1de-ed3f-7f49-8b58-3a62e08e1929
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1de-ed47-704b-8b90-32b5bbd24465
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1de-ed4f-7438-ae5f-c9695445b19d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1de-ed55-7fe9-b8b1-c2aeba3ef1d3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1de-ed5b-7a4d-8e0a-528a7aaa030a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1de-ed62-7538-aa4c-25fad2c522a8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1de-ed6a-7fb9-ab5c-ab3936093c2a

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1de-fa27-75ac-862a-21ca85673d77
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1de-fa2c-7fc3-a5e1-a83fdc94b754
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1de-fa34-70e3-b7c1-3af12b8ffb63
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1de-fa3b-7717-97d3-af1f6f26fa5e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1de-fa42-79a8-8700-b61c3a3cec4c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1de-fa48-7a2c-b8f7-96c500b38f06
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1de-fa4e-71ff-adad-8b3825f00313
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1de-fa56-74eb-82da-0565e1042f19

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1df-0eab-79b1-991b-9771c46eb877
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1df-0eaf-7fc3-899b-a78e49c7a3d2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1df-0eb7-73ed-a981-113c52779183
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1df-0ebd-7ccb-b4cc-309cd6957124
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1df-0ec3-785b-bcc9-249d0e81fe5c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1df-0eca-7233-835f-89cc4f5b8568
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1df-0ed0-739f-a780-ad7e91f441c3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1df-0ed5-76b3-9b63-f7e09032e46e

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1df-20f6-7b81-9f31-1743b5336aca
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1df-20fa-7084-b97f-67279eead7b0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1df-2100-736e-a4f0-485ec71cee4d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1df-2107-7c9a-9be4-1101ef0389c9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1df-210d-7b50-90ad-3782331986ca
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1df-2113-76bc-9729-f4c492e287cd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1df-211a-7d93-93e2-c4a8f21dcf18
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1df-2120-70a7-bc48-ef44b9c318e6

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1df-36c6-7d65-82f9-f7db5a32caef
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1df-36cb-78f9-988b-14402f598c4d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1df-36d2-7f97-a771-08f367478cdd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1df-36d8-77b8-a038-fbbf5eabe191
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1df-36de-748b-a90a-3f9e3db83efd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1df-36e4-70b3-8d67-ed11d9b0d8a9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1df-36ea-7a88-8ab8-f962dc929e9d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1df-36f0-7fc9-b328-af2f38101b34

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1df-59f6-7954-ac64-9187a0405427
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1df-59fa-72e7-8e07-a8c84ac6bcce
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1df-5a00-7380-acca-4dabd1678087
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1df-5a07-7950-bc3c-8672d68cd160
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1df-5a0c-7680-ac04-4fea0af25e17
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1df-5a11-7f15-9561-0f166dfe670b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1df-5a17-75d6-aa31-4d3968b04227
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1df-5a1d-7b45-a371-9f6527e8fd89

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1df-7188-723d-9a61-678675e54c11
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1df-718c-7c03-a96e-bb2698ba873d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1df-7193-7381-b198-e335043e3a72
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1df-7199-78ba-b3eb-985cecf4552d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1df-719e-7efc-b078-0d69ee837825
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1df-71a4-7404-9ca2-81360549ac20
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1df-71a9-728e-8681-0672215c47dd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1df-71af-7710-b88d-3859067cdef8

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1df-84bf-702f-9499-d2df51854182
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1df-84c3-7b30-bcdd-39ea3dd8c69f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1df-84c9-7033-8ae3-8b4ad00e9ebc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1df-84d2-7578-b013-412b7bc7642e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1df-84d8-74f3-8ced-1585d73d6a58
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1df-84e1-71f3-86f3-c2176bb57fe3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1df-84e8-7e2d-b6f2-bad1ffeffa4c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1df-84ee-7108-8315-0b7ec69c2725

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1df-961e-73c8-8945-8fdecfef00ab
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1df-9625-7bed-962b-aab25dd93218
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1df-962a-746c-b9ec-8af680970113
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1df-962f-79b7-b609-afee8e5316e0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1df-9637-74fe-b6f3-8d2cf7cd9200
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1df-963c-7311-ad5a-f9e200b71448
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1df-9640-7bbd-b3f2-0f0fea916917
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1df-9648-7ec4-85e6-9f12eab0fe80

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1df-aac7-74c0-a26a-569e2efe7bbe
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1df-aaca-7530-9235-340c6dc4b3ab
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1df-aad2-7177-a7a6-1b2986f9d7b9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1df-aad9-7a09-985f-b4a680bea9a8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1df-aae1-7f6c-a7c4-f4cc719d4c05
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1df-aae7-73f0-a297-da42c663f58a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1df-aaec-755a-b454-e15d361745cf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1df-aaf3-71cc-9759-587566457164

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1df-c25a-7206-9fe3-5e44c991b700
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1df-c25d-7a0e-9edf-1546b92d6ffe
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1df-c265-7618-8ef6-b8d7e19721dd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1df-c26c-74c9-96d4-0d27e8627a4e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1df-c272-7b0c-b3ae-1bcfc969f790
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1df-c279-793e-afb7-976ebc608956
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1df-c27e-7158-b7e3-5f8653c8a837
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1df-c285-7043-87f0-13e2fb8da518

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1df-d6ba-776f-9f43-0264035b3840
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1df-d6be-79f7-bd2a-0a8993408517
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1df-d6c5-7c0b-8c17-28f95ab05987
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1df-d6cb-797a-97ea-5c02fe84c65b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1df-d6d1-7ee3-9013-e6ac305e2748
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1df-d6d7-7914-b4f3-3d524b365c3e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1df-d6dd-7af4-95ec-ea90e7f5042c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1df-d6e3-78dc-aee7-d1fa821c45b3

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1df-ea2e-71e1-8a7c-6d4d1c02a1e7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1df-ea32-7805-8fef-6af3f6e8d70a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1df-ea39-7c9c-bc7c-210dd0d1859b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1df-ea40-7dad-a58d-cd5f4ec1f567
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1df-ea48-73f2-8f90-52db62affd09
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1df-ea4d-7156-930a-5d77315fd82d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1df-ea54-7ffc-a46d-420b0778090f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1df-ea5a-7e96-a84e-94a6f8034744

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e0-03d7-7782-aa23-170c7bdf7d1d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e0-03dc-7dcf-9c02-cf5d2e0a17f9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e0-03e2-749a-9fb9-917667db30f5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e0-03e9-7294-bf6b-06dc6ca9d8dc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e0-03f0-7957-8611-c1f99af6ae58
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e0-03f5-79a5-ab55-04b195f0191f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e0-03fa-7e94-a487-1202199e7b3d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e0-03ff-716c-acdf-0c99adebc5c6

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e0-18b6-764f-a2e4-d19230349e05
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e0-18b9-7ba0-b9d1-5b1fba6d6abf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e0-18bf-7527-b803-f87d93482648
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e0-18c8-7400-8a84-ac6b02bf1a8a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e0-18cc-7480-9e37-25e7bc7d6b32
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e0-18d3-7e26-80e6-9bb3a75588c2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e0-18db-798f-8c44-f5eaff73482b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e0-18e1-7228-b614-c121da68b371

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e0-3702-7a01-8723-1d5733f73a30
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e0-3708-71dd-871b-52edc7dba8e7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e0-370c-778a-9325-2dd40d238f8a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e0-3711-7a68-ab3a-bca1ff95e22d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e0-3718-710b-b899-5639284e37fc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e0-371e-7e0b-84ba-08a5f19370cb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e0-3724-700c-909b-f91fead04c27
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e0-372a-76de-b5ff-9a0f699218d7

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e0-4ff4-7b7c-8e76-fe30ec3c18fa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e0-4ff8-7425-bba1-a8057b799268
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e0-4ffe-721a-a93d-1dd70a8ff100
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e0-5004-74d2-9666-72c87845d414
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e0-5009-79dc-9f8e-23eff3b70d92
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e0-5010-7fd5-810a-4ae17a578092
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e0-5016-75da-97a7-9093d3355cc5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e0-501d-77db-931c-fc872e973ca9

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e0-68df-7fee-95a9-01a4fdbf6dcd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e0-68e2-7479-b63c-d0f303eef5fe
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e0-68e7-708d-90ef-2b11f06fde2a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e0-68ed-7314-8500-9180441bcb2c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e0-68f3-76eb-9657-01afb1cbcf4d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e0-68f9-7df9-9960-29721be81bc9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e0-68ff-7b51-907b-abec8587414b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e0-6905-761d-82af-930a7ed3a18f

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e0-7d0b-74f1-af26-ea94653df0d6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e0-7d0e-7651-be44-fe26b6523544
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e0-7d15-7e16-b724-fc7a844af62a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e0-7d1b-7b8a-b409-7a3ef20b381f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e0-7d20-70c0-a441-391829f3c96f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e0-7d27-73e6-80d4-a372e833b32c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e0-7d2d-718b-b9b6-c2538ad9712b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e0-7d32-7b06-8048-39d1e53eaa31

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e0-8d31-7a0d-8fe5-ab363ebf04f6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e0-8d36-7fce-b982-c5561c14a768
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e0-8d3d-7571-8941-c60904e040ac
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e0-8d44-7532-b0da-7f979feea022
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e0-8d49-7cb5-8ce2-c7efabaa65c1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e0-8d4f-7986-bbb9-06f7f74af806
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e0-8d55-7e5e-84df-c102fb112364
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e0-8d5b-7b1a-9c5a-98e4626c46b2

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e0-a753-7aea-8da5-ecd1eb601077
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e0-a756-7c06-9941-82db89a608f4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e0-a75d-7047-bbc5-7c9ab593f9a7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e0-a762-7849-ba83-5a1f5085ed8c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e0-a769-7a47-9366-34601f85fc85
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e0-a770-754f-a628-6ca3219efa8a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e0-a775-7ce0-98fe-81a9a1f65ef2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e0-a77b-7447-8b1e-f5aab6dc4c90

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e0-be1d-7b68-a45d-c471af9b2bb6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e0-be20-7933-84ba-5bce7a582b82
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e0-be27-7a39-8e14-96e4ecac5ec0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e0-be2e-79d7-94ea-53cbf8cfafc9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e0-be35-749e-b044-d48099e9bb56
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e0-be3b-7aa0-900d-8b0e7ef737f9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e0-be3f-7013-ad0f-f293c6acaefa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e0-be45-70a6-adb7-6d2a36e93c08

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e0-d1c5-7766-85dc-51cff9b1c15b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e0-d1c8-7329-8c00-7315ea3d37c5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e0-d1d0-7d69-875f-a217f3f0a3f5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e0-d1d8-7ac4-a3f3-2b9c03f7ff0b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e0-d1dd-7300-86ff-ac970d2431aa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e0-d1e2-774d-9f0f-89b5a27aecb1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e0-d1e8-74dc-b680-02cb7d8a3ddb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e0-d1ee-7805-8f8c-9cffa661634f

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e0-e72c-7463-a139-438e8f1d9629
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e0-e72f-711b-bf50-69cf2eb3a634
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e0-e735-70ec-9ebd-897f3186daa1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e0-e73b-7150-ba47-64359cd3692b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e0-e741-7082-9520-c5a763afc81a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e0-e747-70f8-aa44-736a235f6343
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e0-e74c-7802-90b0-ef5ac43ea178
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e0-e754-737e-853e-2dde26c09527

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e0-fcd9-785d-9b0d-7ff42c7fa8b8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e0-fcdd-7d29-8cd9-151e2ad72d94
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e0-fce5-7351-a993-db573e103612
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e0-fceb-72d8-8db5-3b8c6ab24ce7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e0-fcf1-7da6-bbc2-9f203cd8ca2c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e0-fcf9-78c1-ae29-7c85903b28d9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e0-fcff-7e55-9e84-f737883b5ff1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e0-fd05-772d-822b-0e8f8623d96b

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e1-1371-7273-b225-c53161a0582c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e1-1375-7e00-a0e7-1d3fd7daef78
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e1-137b-7924-bf37-b1e3f5b5114b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e1-1381-755f-bfe8-6cdee6af505b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e1-1387-76b8-b636-74230d4cb1e3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e1-138d-78e3-98ed-2bd3c0afe91f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e1-1392-723c-8f37-d457abb1c2d0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e1-1398-76ba-9822-ed2ed957c0ae

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e1-225d-71a0-b043-08ba338c9f9c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e1-226b-757e-a99f-e0a65dacefbd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e1-2273-7e91-b640-e01066e190a4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e1-2278-71d4-9f27-48e93e409f12
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e1-227e-75b9-8a26-5f7cb38c2ee0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e1-2283-766f-9edb-dd861d56178f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e1-228a-7c7e-ba84-42f92301f9d6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e1-2290-7a93-a381-bf30db34e988

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e1-2f9b-746f-839d-a201676dc3f7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e1-2f9f-7aa1-ab53-727240db7ca6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e1-2fa6-7914-86ee-9ce02f1eb480
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e1-2fab-76b4-872a-1f0f46ef4cf7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e1-2fb2-767d-b903-d1297d7c1776
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e1-2fb9-7a83-9e68-fc75d456f267
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e1-2fbf-7859-9f92-43bd65c97a38
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e1-2fc6-79d1-9868-6d738ad84a59

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e1-44ad-78f5-9aa0-17c5f17fdc27
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e1-44b1-76f2-a454-b4428738a6c4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e1-44b8-7976-ab35-86f2936358c4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e1-44be-7a75-aad4-6cfafd973229
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e1-44c4-7301-9d86-30e6d42343ac
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e1-44ca-7a09-ba6f-adb76912f46a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e1-44d0-7be7-81e7-95b923c6809a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e1-44d6-77f0-9b1f-15e1a037fc74

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e1-4f0a-7e59-b6e7-69ac35898119
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e1-4f0e-791d-9785-4a174cf6f8f2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e1-4f16-72dd-afde-3a092f7d5029
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e1-4f1c-71de-838b-19a29dc40bf7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e1-4f23-7505-8a95-ab647085fa97
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e1-4f29-7c85-938c-de75280c06d6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e1-4f31-739b-a5a7-f7a58baa58f6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e1-4f38-7dbc-ab27-a1a96a141a7e

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e1-6cdc-7b5f-86f9-71060b94a497
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e1-6ce2-72b9-9847-6efab6d12b58
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e1-6ce5-7d88-af93-1d10ddbfce4c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e1-6cec-7230-89ba-c6f0d3c02981
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e1-6cf2-7d6a-aea2-f1c06918255a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e1-6cf9-73be-9ce5-1be2d1cf6e7a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e1-6cfe-7352-a2bb-c2f575b0999b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e1-6d05-70b7-bfdf-8c38b2730b88

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e1-81d0-7ac6-87a4-4bc03a405a37
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e1-81d3-76e4-b4db-e838a4268883
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e1-81db-7324-bea1-30ca589ba32c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e1-81e1-71fa-874a-bbc57cfd11b4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e1-81e6-71ea-b9d3-9030f337f129
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e1-81ed-7759-aad2-c032ef75e77e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e1-81f3-792b-a500-a932dfb5a611
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e1-81f9-7323-9e28-fc8760030eff

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e1-9c58-7580-8a4d-6ee7965ba8f4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e1-9c5c-7296-8fb1-5e7b6a91cd01
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e1-9c62-712e-8d8c-6f31897b0e9e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e1-9c67-7c35-8dd5-37d662211464
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e1-9c6f-790e-8c73-14681b4a2fe0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e1-9c75-76cd-b3ef-fb5ea149b98a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e1-9c7b-74af-98a9-3357c596bb6c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e1-9c83-792e-bf4c-6e739f764185

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e1-b0c2-719a-8524-5dae4bcb89ed
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e1-b0c6-7747-80a2-ff296bed8917
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e1-b0ce-78be-a220-b4b53f0b8395
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e1-b0d3-7468-9aaa-7e37b2691a14
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e1-b0d9-72c7-99e9-2bbd63d70a64
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e1-b0df-729c-9000-20eec926945e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e1-b0e6-7acf-9a7c-a6d6b439d52d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e1-b0ec-7500-a80b-3d8f7510020d

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e1-c717-7d4d-a652-fa5f901a12c4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e1-c71b-7fc4-8397-e6bd88d5c338
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e1-c721-712d-a399-a4158a5d5b8a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e1-c728-70bf-a8de-bb2004c7bbfd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e1-c730-7d21-afc7-a0195ecb55e8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e1-c735-7791-b1a7-618707f93fe1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e1-c73b-7e4a-b4c3-9de174f64948
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e1-c742-79e9-af6d-c58efd49851c

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e1-d928-7870-ae17-b0da970726a8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e1-d92c-72e8-9978-8023b4bba609
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e1-d934-78f7-b597-fbf396df8b8b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e1-d938-7898-a509-43a7ed82a987
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e1-d93f-75c3-96b6-cb0564535a6f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e1-d945-7d9e-8eff-a009a819e45e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e1-d94b-7a39-8000-f219f4094393
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e1-d950-7182-ba67-70d4d8ec7fcd

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e1-f730-709f-9e0b-1ad0ce902ab7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e1-f735-7c18-93bd-6c2b4182c4fb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e1-f73a-7574-b55e-b05edcd1fdc8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e1-f73f-7bec-9c5b-da0b6bf3edcb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e1-f746-7d43-a8d6-8aa45acdf718
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e1-f74b-7cf6-a94e-f8840e1bf8bd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e1-f751-7ef7-923b-74887087396f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e1-f758-7b86-b607-2b150eb110dd

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-1271-7583-a324-524d2edf54d2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-1275-7954-8dad-d51b0954e4b7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-127b-7077-8033-cf1f2eba03b3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-1281-7211-86e1-6be9856a3bbe
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-1287-7108-a2ab-b434b9948da8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-128e-70e2-a3aa-2022c2fcce3e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-1294-798c-b2eb-73e6ff93b4b1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-129c-764a-a736-e5099faf33dd

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-28cb-7251-a240-4381af53b4da
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-28d0-7dea-8a32-add4810659ac
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-28d8-71a9-b390-8e5b18221c84
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-28df-7375-b8c7-840299503d70
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-28e6-77a9-890a-af01f97072ae
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-28eb-7718-8b75-4c3dc3e181bc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-28f2-7797-9743-20c498d6f812
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-28f7-7cfc-85f6-5572bd48a119

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-3be3-7109-a79e-81b1702a15f7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-3be8-77cd-af48-6d00a8f22be2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-3bef-7b0b-baa4-9f3f9c7f0760
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-3bf4-7658-8dae-cd52141adf6b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-3bfb-7704-8278-07f13aef9ff4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-3c00-7481-b4c7-7811181afddb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-3c07-7d68-9f9a-23445b9e3893
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-3c0e-79c0-9f34-e1c1c716ddef

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-4d21-7ee3-838c-db789cb92c92
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-4d25-7efc-8522-3f50a24cfa09
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-4d2b-7874-b798-8048e1962a16
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-4d31-7789-9dca-a8526dbb0f23
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-4d37-76a7-975f-467acacfbb8f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-4d3d-7624-8e0a-d538c1be8c0d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-4d45-718e-8216-0d1c22996355
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-4d49-78ca-9efa-c28f0b085280

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-602e-75ec-8fa6-b8f24d27ebbf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-6031-768d-bd79-aa963b1c5eed
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-6037-7288-83ba-a1e6600272f0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-6040-7620-99a4-3f6cea8e398c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-6047-7ba9-89b5-3632ae1933cb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-604c-765e-b7e5-bbd96bfa80a1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-6053-73b3-963a-9e670123ff61
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-6058-7027-b140-583d7d79da54

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-78d3-7083-883f-bfc2b8d7eb9e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-78d7-795a-9b86-0032984e3a4d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-78de-7f6a-8f06-54a860ac845d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-78e4-7dd6-bcaa-3f8ec773f655
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-78ec-7d40-8e9e-eff110199343
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-78f1-74df-bfbb-843083f4c0bc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-78f9-76fe-9956-a6a16d4e7181
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-78ff-77a9-85df-2a07c94fb3e8

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-8ae4-7ce6-bfce-4066c826bc27
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-8ae9-7f50-9b6f-7a96097bf067
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-8af0-7e72-988c-8ff1d3718a18
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-8af6-7411-8fb0-d8bdaf09ca2d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-8afc-7855-b7be-5b710ccc4cea
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-8b04-77b5-a616-aa2621a2b023
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-8b09-7523-9a62-e70ebdb73542
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-8b0f-7151-816d-f2ebba4e42ca

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-9bfb-7554-810e-a5891a319058
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-9c00-76cb-a63f-0f55fc3610e7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-9c07-7772-8a96-7ac0c80d52ec
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-9c0c-76cc-a7a6-10509d4fbb5c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-9c14-72e3-b8e7-5385da9fb3c3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-9c19-73f9-a6b8-70ffcf2539df
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-9c1f-7cdf-9ce5-a662d2f415c7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-9c26-75c9-9d8b-790c46fc7920

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-b04c-7a2a-a118-eff4359dd685
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-b050-7a72-906c-45767844b15a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-b056-7c34-9507-2c16827ffeaa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-b05d-7b23-8a16-3cd970981cad
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-b062-720e-b24a-019dc2f78c72
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-b069-71f4-8ae3-f9fe630cdc52
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-b06f-72a3-94c1-f7b4fd238ba2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-b076-7091-bd2f-79129ae78cb2

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-c3d2-7dc8-8bb3-e696202df9bf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-c3d5-719f-96da-3e2d38b0ba44
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-c3db-7b54-bee1-8a75edf1e2c7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-c3e2-7932-9fcf-87d0062ff783
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-c3e8-7626-bffe-374d5b4d200d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-c3ef-73ff-a098-a498472ae838
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-c3f7-7f89-b07e-45bf92aa92a8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-c3fe-7a9b-8d87-efe519252821

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-d5b8-75bb-af06-2dd0d3c2654c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-d5be-7004-b128-6543927f8983
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-d5c4-71fc-b624-8614f4ff9909
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-d5cb-7b75-a1f5-8eb64caa883f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-d5d1-7d53-8610-473d45edc4f1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-d5d7-79db-8c44-9483fbe83a5d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-d5dd-70d0-90c7-c1d9f60ab7b1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-d5e3-7b50-9426-65d10a2e0690

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-e5a9-7374-b07b-4fa8821c1038
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-e5ad-7aa8-a813-1efdbbc51c52
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-e5b5-7b7f-a34d-0fba2b734dab
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-e5bd-7493-acae-5c1d7fa08c3d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-e5c5-765e-a4f5-8aab37b7a700
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-e5cc-736a-aa9d-fdddaae82640
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-e5d2-7bdb-a048-010200d44330
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-e5d9-76fc-bbfa-f18e316fcfd6

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-fe1f-77ce-986e-a9e0103d85d4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-fe23-7910-9c21-a3c494dc9cda
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-fe2c-72db-9995-cd5f2e9ea805
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-fe33-7fa6-aa20-9aefb6a917a8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-fe3d-7596-a2b6-e8685952d3b4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-fe45-7de0-9c3b-e2e6faed3500
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-fe4a-704d-bc9c-705eec33fe0c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e2-fe52-7156-a6ba-1f81677727e0

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e3-18c7-7593-9b85-fbfbba8a122f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e3-18cb-748a-92cb-4ba710d44e81
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e3-18d2-7d28-888b-3207ae974a2f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e3-18da-71df-859d-5b217aadaef6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e3-18e0-76d6-a6df-db0a84d37b72
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e3-18e7-7f5b-b1ef-eccac5070514
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e3-18ee-71e6-a291-248ae30c62b8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e3-18f4-75af-89e9-f72a437e7488

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e3-2831-7388-8896-7138d78d9a39
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e3-2835-7d9c-a54d-a762d82c34b2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e3-283a-7a38-8ecd-55577bd2f62b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e3-283f-7f76-9ddf-45805c1c9204
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e3-2845-78ef-8b0d-caa9afb74af8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e3-284c-71f4-b6a2-2832360a8b30
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e3-2852-7e35-a4ff-204b7c501d60
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e3-2858-789d-befe-85db8f905db9

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e3-45a1-7f99-86b7-b5a362b49357
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e3-45a5-7ab1-bfa6-c708daef3046
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e3-45a9-7647-a60e-a22eed99da71
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e3-45b1-7295-9776-ac82f35103bb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e3-45b7-7235-8449-e4c6936a728c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e3-45be-748f-b106-7837b2599171
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e3-45c3-78fb-9b47-d14b7df4dd0a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e3-45c9-781c-a86f-cd3e5b0a2201

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e3-58e9-7c6e-b8c0-ea25770dbc53
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e3-58ed-762c-bc73-7b457e6693b1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e3-58f4-77f4-b626-4cdfe45c1803
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e3-58fb-7676-9d93-4710802d522b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e3-5901-782a-a012-50442df5946d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e3-5906-7a72-9221-a85d752335ac
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e3-590c-7482-b1ec-fce37af00818
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e3-5913-7b39-b9e0-87f35451d364

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e3-6f17-76af-a513-f17e923e1c58
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e3-6f1c-7457-814d-8b875a2b0eb6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e3-6f23-7e2f-9f83-f356bfa58a3b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e3-6f28-7e77-bc12-9d6ba8570013
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e3-6f2e-7316-ba28-1f6d78972ab9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e3-6f34-7098-a8b1-03e1fe96a071
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e3-6f3b-71a8-a9e8-9234770c74e0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e3-6f41-7036-80a4-39f4a2beff93

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e3-7b09-7ff9-a9b9-1aaf9d4dd98d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e3-7b0c-74a2-a8d9-67bceebe8bfa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e3-7b12-7389-9231-4ed251a398f9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e3-7b19-7585-81bc-377a338ddc32
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e3-7b20-7824-ad92-1670de61d4fb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e3-7b27-75e1-8d8b-ac032a58427a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e3-7b2d-7e0b-aca4-e17d828f7b3d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e3-7b35-70e6-9250-3eb0c1cedf07

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e3-9844-7d72-8eb1-7f6cc641f15e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e3-984a-79d8-85d6-829bb3ce6e9a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e3-984f-76c6-98f8-934b72d4760a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e3-9855-753f-b49c-6028681523f1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e3-985c-7a42-8f8b-407605914041
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e3-9862-74a5-b517-03cf9c219c8d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e3-986a-72b1-8b6a-bda4b85e6589
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e3-9871-7b78-a11e-78ffd5db7c87

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e3-a50a-76cb-b841-4946c0b88534
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e3-a50e-786c-8e15-99474fc84551
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e3-a514-78bd-9e9f-d1f9e829554e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e3-a51b-7287-bf28-1ecba1dba485
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e3-a521-72c1-b892-2a57c0d7c76a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e3-a528-7568-a0ee-457c1163a2dd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e3-a52e-7f6c-a0bf-65f7423f2763
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e3-a534-704d-be4d-d93bc26dece5

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e3-b762-717f-b16e-e3991bda6d8d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e3-b768-78f2-b0b0-b9a1d757eb61
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e3-b76d-7049-b3d4-87fdf58b92f9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e3-b774-7f0a-9075-c5366628962e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e3-b77b-7f18-9863-826ae8d7b5d5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e3-b780-7c1b-9ceb-be24fb8a9acd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e3-b785-7947-bfa0-a20813a8afee
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e3-b78a-7b85-829a-7eaf41735dd8

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e3-ca73-718b-9e5e-ce0f36753e11
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e3-ca78-710f-912a-09127c586d19
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e3-ca80-7617-b6d2-fa7123dcbf50
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e3-ca88-711d-af51-715c2de10ce6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e3-ca8e-7560-88b0-40ebc5b080ea
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e3-ca94-75a8-a28d-cf8772af9648
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e3-ca9c-7457-bf78-238f083b08f8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e3-caa3-7732-818f-6535633fc6c1

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e3-dd9a-7d28-9af8-52e4bcb4c862
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e3-dd9d-77a4-9c09-97387f9880b3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e3-dda3-7764-a217-8269d3fdec78
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e3-ddaa-7a2b-bf3e-4a11560e8711
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e3-ddb1-7ed4-8ac2-abfe7929863c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e3-ddb7-7575-b794-8ac8b3a70115
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e3-ddbe-7ad0-99ad-b68c39b40185
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e3-ddc4-7c8d-8c91-a5fd2c80eff8

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e3-efd1-7360-8619-4da97b1ea48d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e3-efd6-7323-8ea2-d85e104660ed
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e3-efdc-7ad4-9d73-630dd3bebd81
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e3-efe5-7f82-a687-2138c59de1dd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e3-efe9-72ee-bf3c-7281aae51111
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e3-efef-7de4-94d1-8b7dc9de1f82
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e3-eff5-7267-847f-2b1722ee5115
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e3-effa-71d6-a052-f313e6881d10

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e4-0a0d-7d81-9c3d-4e8ff5407a72
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e4-0a11-787e-9c7e-13fe0c57ec85
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e4-0a1f-7ee3-9605-341af3b73656
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e4-0a26-72e5-90c4-37df9c193af1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e4-0a2a-797a-80a7-ec4cf2283712
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e4-0a33-7979-9318-62c2c898693a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e4-0a39-7f9b-a338-018a0110d170
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e4-0a40-7f4b-9c52-6347d74c5741

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e4-1a30-7a3d-9a9d-1eba4e453556
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e4-1a33-758e-bedd-c9c5420c6660
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e4-1a3c-72ba-8938-cd82b600ae68
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e4-1a41-7efb-bd90-61c886cb1bbe
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e4-1a46-7d44-9686-d573a0a9c7c1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e4-1a4c-7f4c-81ad-914b9d18bef0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e4-1a52-7e38-a4c8-dc0ad84c806b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e4-1a58-7d98-8803-e5ff9289769d

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e4-3e21-7a71-a31d-9d58cd69b261
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e4-3e25-7c9d-9962-f741baa7f021
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e4-3e2c-7c8c-b63c-9b0286a05dd2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e4-3e35-7a36-9cf5-a70bbaa949cb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e4-3e39-7d0f-9539-865dfab8e4bf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e4-3e3e-7474-b58e-b26db86e0ea9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e4-3e44-74f9-80f4-8ebade66d89b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e4-3e49-71f4-bd6b-72a8dd16f360

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e4-4fb1-7e86-afce-b14b2fe9ecdc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e4-4fb5-7d04-99ca-5a0e44d0cb0b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e4-4fbd-7170-9264-847baa2d4014
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e4-4fc2-749a-8654-798707c8a0c6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e4-4fc9-7b0f-a5f8-9d514749d092
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e4-4fd0-7406-9350-39a19399cdd9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e4-4fd6-7374-b0c5-1c3e9c1720bf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e4-4fdd-7c82-b399-c80f94d07e4a

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e4-69fe-74f0-b014-11bb5930ce1a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e4-6a01-77c5-b94e-9ede8600fc88
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e4-6a06-7c09-8556-06abb461b99b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e4-6a0d-716c-8440-a4ba15ffff4f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e4-6a13-7b02-b126-0d2762a63794
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e4-6a19-7404-8a17-d08a1e01a6b9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e4-6a20-7d4e-af68-0104c47c44fb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e4-6a26-7daa-b08b-9525b879b015

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e4-803a-7dda-b3bd-483356a47607
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e4-803e-70ee-8c0a-ee18af5df3ab
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e4-8046-725c-bf9f-c814979703c3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e4-804c-738f-ba5e-3c17615a1315
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e4-8053-761c-805a-4e74faa6e48d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e4-8059-7d46-82a3-fc072eb73bce
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e4-805f-7887-b336-2c13fcaff893
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e4-8065-7461-8992-d7c5ccc47402

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e4-8cb7-73b4-a13e-d30379bbb56c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e4-8cbc-7b73-b2ab-97080392dc73
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e4-8cc3-78c3-a2b7-373f202835e0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e4-8cc9-790b-a749-ccd8d18e618a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e4-8cd0-7543-b40b-1ba0e6b20997
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e4-8cd8-7791-8825-1b17ca58bb85
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e4-8cdf-742d-b06e-843021d48b5f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e4-8ce6-779e-a1ff-aeec619bf02d

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e4-a307-7d92-98dc-82ffb78ab370
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e4-a30a-7cbd-a06a-60fc348b04e1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e4-a312-7773-8d60-24b0ee923cb4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e4-a319-79aa-98f8-130bd8bfb844
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e4-a31f-7f08-83a2-8e1b4609c32d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e4-a323-7414-be60-4c944dec77bd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e4-a329-7472-b81c-162e60da6b10
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e4-a32e-7fa2-9e22-9b3ce91d1668

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e4-c60c-7d1f-ba5a-faaad4f73d2d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e4-c610-7d43-9aac-e390401bb048
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e4-c616-722c-877e-bf1226df8efb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e4-c61c-7f5f-82ee-7e6a9b0dd2d1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e4-c622-7b43-b74f-087d1b09b99b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e4-c628-707c-9c99-3e88a2e96224
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e4-c62d-7471-916d-122bc17b08b9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e4-c634-7f0d-989d-89f234852982

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e4-d78f-7b7f-a1b6-230971924fe1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e4-d792-7790-8a32-7beca493fe7d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e4-d79b-7454-ad09-07fcf91fc859
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e4-d7a1-7740-9fce-596c6bf0ca03
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e4-d7a7-7578-b8d4-7175900f6e76
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e4-d7ad-7b0d-9c29-c2f2b3c2e6bb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e4-d7b4-74cc-b0d4-00ff1eed256f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e4-d7bc-71d7-af94-4dd7c70e6c4d

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e4-f4c9-7b1c-a687-7af0f27720bf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e4-f4cd-74f8-b22c-a36fe2d372cf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e4-f4d3-7a75-9bd6-816b16ac0f64
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e4-f4d8-7f67-926d-7a715a591901
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e4-f4de-7bbc-a744-43beec67ce61
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e4-f4e5-72c6-95f6-35a2ddee3573
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e4-f4eb-7722-a925-77da5c55d8cd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e4-f4f1-77ba-8452-c9a7f928afc3

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e5-0db9-7e0b-8ef8-4b3a4e54b42f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e5-0dbd-7002-ac5f-57628e5b2bbc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e5-0dc3-733b-9408-3eb3eb085161
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e5-0dca-787b-92b3-3c44c942a0db
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e5-0dd0-7b81-8b0a-47da01303a83
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e5-0dd7-72c5-a191-bfd0ee8bdc45
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e5-0ddd-78ed-8a56-28c7e4e256d3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e5-0de5-7282-8d7e-a85a775da605

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e5-285c-765f-b474-2b6782a6768b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e5-2860-7c18-89e0-6b0ba5307df7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e5-2868-7afe-b5c5-5247821a42e0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e5-286f-7c1e-a584-353303f0657d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e5-2875-780f-948f-fd2637c3261c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e5-287e-7ca6-9d61-d89dd4dd314b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e5-2883-7fdc-b253-66d32b403532
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e5-2889-7f5b-a364-eb5b6a2dd0cd

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e5-4d8f-7a42-bfff-4d41488080f1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e5-4d94-7ae8-a7b0-2d530e124325
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e5-4d99-72de-974e-105f1dad5fc4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e5-4d9f-7294-baf0-044ec465f5ae
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e5-4da7-798b-be76-7b0b3b5daf85
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e5-4dac-7392-9812-b3d86c9abf57
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e5-4db4-7d0c-9a9f-1418c9798e36
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e5-4dba-7f36-a31b-dcd54d6f9114

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e5-6abb-7347-94ac-fbbecb6c15fa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e5-6abf-7927-88f3-1837f0ea4e85
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e5-6ac6-74c6-b141-e4e0a558eddc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e5-6acd-7200-b1c3-2afe34468137
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e5-6ad1-79c9-a49b-5db130c4c1bb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e5-6ad7-7392-b1a3-2473af323b73
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e5-6ade-708d-843e-958e45fff9dc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e5-6ae4-7877-85ce-b158d4c4dbbc

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e5-883a-7dab-8381-2c3f04f7a5ba
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e5-883d-771b-98d0-07d86e1791ef
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e5-8844-76ef-bd13-fd8e42539d97
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e5-8849-7423-9653-75febedfbc48
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e5-8850-79b9-b97c-4b40882d13fb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e5-8856-7cc7-a366-e0d7d63e2102
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e5-885b-7a0c-ba5c-a17d5015dee0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e5-8861-7da2-9fd7-c5dffe3c02a4

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e5-9b7d-7155-af40-fdb21ca5a52d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e5-9b81-7d01-8445-2e33a5920f49
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e5-9b88-7bb7-8e77-fc9357d5fb7d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e5-9b8d-7b39-bf45-b9542a9edcd7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e5-9b93-776f-9d3d-541d277d4434
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e5-9b9c-75cf-8944-3a4f821d298b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e5-9ba2-755e-a847-0b31bb0edd00
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e5-9ba7-777f-a902-b22006b3d216

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e5-ada6-73ea-a8d5-77904b9ed66e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e5-adac-7238-b1c3-e25ec7ad7972
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e5-adb2-79ce-ace6-d55c274df8e9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e5-adb7-7cad-a659-79c887b5bcf1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e5-adbd-7e37-80a7-36e010bf210a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e5-adc3-7ebf-b465-709cb446d911
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e5-adc9-7365-9743-26c5ed106e33
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e5-adcf-70ab-9c6b-2fe53560f105

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e5-c347-7d50-8d0f-2fb1a940196d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e5-c34d-74f0-a85f-d58fd684dfc3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e5-c352-7352-b7d2-e52bede7c7b8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e5-c359-78ff-b559-871f2a4a3dae
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e5-c35f-78da-8069-376702440048
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e5-c365-7b84-8eaa-38c3e67a1843
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e5-c36c-712f-939f-777dbf1795e7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e5-c370-7aa6-a57d-59d31319ee20

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e5-df9f-769d-9da8-97047019b2e2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e5-dfa8-7a28-bfab-c7f9ae5343dd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e5-dfaf-724f-94a6-cc783dcc7e12
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e5-dfb7-7404-9360-e61ff8a24d18
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e5-dfbf-7991-bf27-878f686dbeab
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e5-dfc6-7389-9e31-7df7d69b97ab
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e5-dfcf-7da1-8a6a-4a054db67a7a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e5-dfd6-7c0c-8d77-dff937a00eac

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e5-f18e-78ef-814e-4bcef8a27cf1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e5-f193-7bec-8af1-9ada632c2c04
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e5-f19a-78e7-b30a-ff27e1904a6b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e5-f1a0-7cdd-a3a1-0a5dd01fe9e7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e5-f1a8-71fc-8814-3a1e677f95f2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e5-f1b0-7fc1-878c-856a3497adeb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e5-f1b8-7539-b5a8-b5529c8bb557
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e5-f1be-7032-9ec0-4678b1baedea

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e6-1034-7d4b-8a8b-21e0124517cc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e6-1038-73d6-88ae-10f7aea631e7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e6-1040-7efc-a30f-8d6d249beeca
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e6-1046-7046-b0c7-af2d890186a4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e6-104c-7033-b789-bc431697e0e8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e6-1053-7426-ab41-02d1a1549384
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e6-105a-7f1d-b706-4cfcd210dcb9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e6-1061-722a-9b9c-5523637b4f46

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e6-2570-70e7-9e2a-20cf5e73d92e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e6-2575-7b25-9a10-5bc8984a55b1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e6-257b-77e1-96ea-a9f1fed273b4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e6-2580-7ee3-806a-bb3d1c4568c3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e6-2588-7cd5-83cf-90e6dac5806b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e6-258f-7a3e-ab18-c376bd7be320
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e6-2593-75fb-8ee8-8528621e7000
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e6-2599-7220-8bae-c3354c83b952

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e6-3e2b-75f5-9e10-f012a37fa163
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e6-3e30-7177-9171-5d383c9be217
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e6-3e35-7a59-88be-ace61f8ce705
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e6-3e3b-77d7-98dd-6dc9fb4bd464
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e6-3e41-7e2a-b1d2-d61a3d6e168a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e6-3e48-7840-9bb4-cb717eca81bf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e6-3e4e-72e1-9e9f-6830a5d0be5b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e6-3e56-723b-baea-1caa978a3a89

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e6-502c-7402-91f3-b761c3db4416
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e6-5030-753f-9d27-e5c930270b0d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e6-5039-7ec3-9924-f8a14dd7cbe4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e6-503e-7b70-9887-a44f4747903f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e6-5044-721b-981b-dd425b83e4b9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e6-504a-7b37-a6b4-966ca5db15f9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e6-5050-730b-a6ba-5d985092ff42
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e6-5056-7082-940b-9977be811bbc

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e6-6868-7b4d-bf3e-feb490dc026a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e6-686d-7191-81b9-be1a793b43f7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e6-6872-7a34-b4b0-7b32b9bf2134
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e6-6876-7e84-bc98-a7c4f7f06361
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e6-687c-7e83-a70c-2c05b021236f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e6-6882-70d6-9289-9aa2bebf1645
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e6-6888-7d22-b601-cc8fa40ce488
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e6-688f-78c0-b17d-908c5d6a749e

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e6-7d0c-704a-81a9-1f3c6a055f0d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e6-7d13-7c01-8719-d85e4eab8e7d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e6-7d1c-7c9e-bd96-343f31b62799
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e6-7d22-73c1-a27a-14d8dbad0d5f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e6-7d2a-7a28-9890-29ae15f303a9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e6-7d31-7f4a-a5c8-44a467f69ca6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e6-7d38-7ad6-adcd-688324e4eb29
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e6-7d3f-7aa2-8d81-973cb855a908

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e6-8cea-720f-b1cd-3312d654a445
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e6-8cee-7061-9aa7-3f413dd57f91
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e6-8cf6-7d39-b812-2ea37d11f723
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e6-8cfb-7f5a-9541-36232364bc50
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e6-8d02-781c-b10c-cbfee2973e11
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e6-8d09-7469-add0-14e9afe92814
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e6-8d10-718e-b8ff-ca9b36b68ce3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e6-8d16-780e-ad9a-04b7c71f6425

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e6-a320-7ce6-933e-a31fa4058f4a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e6-a325-7087-be1e-3dd7b8a65a01
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e6-a32e-7ed7-87f6-d28407bad0fb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e6-a334-79ad-84f0-9d3e43d5c074
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e6-a33c-7314-b4c4-4f0bd508d9d3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e6-a341-7897-9bec-a815b3178ddf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e6-a348-708d-877d-2478ef50b034
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e6-a350-7e92-8b91-92233ca95b7a

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e6-c2e8-7a66-a082-49ed172ed89f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e6-c2ed-72a7-831f-7d7d0e3b345a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e6-c2f4-7a99-928b-f43ca78714f5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e6-c2fa-7aaf-8d20-ea0fd978fb90
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e6-c300-73c6-9c30-ad9d1b7318eb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e6-c308-751c-aabc-d5948dd67ef3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e6-c30d-7820-9ef4-f48d11496f99
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e6-c312-739b-bf12-0d305b2ee0e7

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e6-d83e-7d9a-9927-438c04fc5817
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e6-d845-73d8-9f35-de88e38d6703
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e6-d84b-752a-91c8-1284bf38c4a9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e6-d853-7a0b-b08d-f9affc95fcd2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e6-d85a-79fb-80f2-fd95f40f561a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e6-d860-7aa8-9ee3-4092c35c675c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e6-d869-73a4-b172-8a389d2cb6fd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e6-d871-749b-b414-77408647486b

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e6-e2a7-776c-aa51-fd7aa93b1eb3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e6-e2ac-736c-9e35-048833b701ef
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e6-e2b2-7aec-adba-11476cdc3442
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e6-e2b9-74cf-b4d1-2c8ef938fdf9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e6-e2be-7ef7-afea-36f1ddd73790
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e6-e2c4-753e-a854-5a92e476a2c7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e6-e2cb-7b17-ba48-7ff659512d86
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e6-e2d1-786c-858d-310a588d4c01

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e7-0ba7-7b6e-8e76-dae95897dcaf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e7-0bab-783c-8319-e124dae61c77
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e7-0bb3-7a21-8eee-a966de08bd83
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e7-0bb8-7327-aa45-bc265ba95a08
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e7-0bc1-7b3e-ba49-e382d851eb85
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e7-0bc8-7835-828b-3cfc35cde2c5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e7-0bcf-703f-9300-b588aa1bb5f9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e7-0bd8-7bc9-b2a1-b12a7fcc8945

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e7-2ffc-7a7c-94fc-e70b39765c78
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e7-3000-7961-9205-a41106752d24
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e7-3008-77d3-9dfd-7ed4e6bce7fd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e7-300d-7697-b3bd-85c5f078e080
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e7-3014-74f5-a694-b90b4c52b8d4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e7-301c-7a62-a6d3-1757a243840f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e7-3023-7562-a726-1f06ab23dab6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e7-3029-7187-89b5-48a625ab8eac

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e7-4486-7025-b87a-9c2bce047a8a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e7-4489-7f9b-a522-c654411b00c8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e7-4491-7200-a1c2-eb4aaca4a6db
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e7-4497-7e41-b66f-a69575b9cb22
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e7-449f-78d7-a1d1-2262a9606578
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e7-44a6-7eb1-a723-d49a828bae1b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e7-44ad-7c9a-913f-11117b6b4b81
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e7-44b4-7be5-b2b1-94a4e13beb41

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e7-5899-72c3-ae06-e40a4d396ba3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e7-589f-799b-9081-4b8b9ad84ad3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e7-58a6-7b75-8236-cea7c398d51b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e7-58ac-74cf-bbaf-07bc66ae7b08
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e7-58b3-7f2a-b440-c08f0c0ecb8f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e7-58ba-7e2a-ba30-fabed25e13d5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e7-58c2-7758-b9d9-d8d291398a93
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e7-58ca-7435-8696-ed59472a2253

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e7-73f5-7d62-9ab0-f02bf56d369d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e7-73f9-7d72-9ea9-3fda2688826e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e7-740c-747e-910b-cdc08b68f927
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e7-7411-7592-b3d7-29485e872b01
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e7-7418-7346-91e6-fa4be913d444
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e7-7420-736c-aa7f-eb64e8e63168
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e7-7427-7f30-b2a1-45b34e38cf1b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e7-742d-7c58-811b-4480edb98b34

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e7-997a-7877-b7f5-cad8f03e4287
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e7-997e-722a-a778-e326359d8221
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e7-9986-7799-91eb-7315c82c973b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e7-998c-76b4-ba7c-cbffb49d00a3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e7-9992-7caa-8b44-ddd500fbab9b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e7-9999-7491-a565-be0440fdb92b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e7-99a1-7851-8bd2-26520435b650
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e7-99a8-7a94-a85a-1d350b883f06

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e7-ac32-7d8f-9501-0a98294e315f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e7-ac36-743c-8e0e-3f48445bf07d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e7-ac3e-7d5f-9124-16b8bd7b5d06
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e7-ac44-7c92-9902-3ff23ee4d970
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e7-ac4a-7b7e-85aa-3f7330a8ccdb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e7-ac50-73fe-8376-7af44d8b34fe
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e7-ac56-71d0-a68a-f28278c92da2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e7-ac5c-747b-89d1-fcdc4cd85502

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e7-be89-77d2-85cd-3832f63cce0d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e7-be8e-7130-be0c-39ab43073783
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e7-be94-7b45-b8a6-354ea02dc5ce
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e7-be9b-786e-86c2-8631cf4c9584
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e7-bea1-74d9-8f2d-e8a874573289
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e7-bea9-7156-bd18-118b696bdba5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e7-beae-73f2-9f08-df4ef6986ed4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e7-beb5-7607-b910-66b218bae9b5

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e7-d6f8-7c42-9e7b-e199f8648c08
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e7-d6fd-7040-9d79-21dec21296aa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e7-d703-7777-ba4c-aea987835fd7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e7-d708-7925-8a23-e97efd452833
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e7-d710-7f1e-b0ad-957717fb4322
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e7-d717-7e55-b179-0e0a0ab26c71
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e7-d71d-7d6c-8239-4a88695a3b3f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e7-d724-7c48-96cf-56a1538d8315

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e7-f2d9-7366-bbf2-2666193c7041
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e7-f2dd-709b-aec7-b3757b97ceb6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e7-f2e4-718c-b009-8bd96867c329
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e7-f2eb-7c4d-8a39-cfa27aa0633f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e7-f2f1-71ce-a954-1737123255ce
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e7-f2f7-731e-b0a6-419564dd9498
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e7-f2ff-7eb4-bba8-45a7fbe838a5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e7-f305-7573-aff4-66c7fd481db1

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-021e-798f-9dc2-bbb6057de975
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-0221-7882-b86f-72a99b02c280
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-0228-77cb-b991-d261a02fa161
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-0230-7653-bdef-974a74b191ab
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-0236-780c-b80d-0678d80203d0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-023d-762d-8b93-5ab1f029e086
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-0243-70b8-8a19-1c4ed7247b14
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-024a-7608-8d2f-ea60ecb8dc7c

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-1eb3-74ed-a7e3-0b8c6e7a8bb3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-1eb7-72ab-b3a8-ac56442c4c7b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-1ebe-71a5-8b12-24dd19932843
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-1ec3-71bb-9fc0-956be7120c1c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-1eca-7d38-99ed-e44e01557688
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-1ed1-7ebd-96f1-245a85a092e0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-1ed9-776e-9d40-cda02c9f58bd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-1ee1-777d-8920-1d99b095d05c

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-341a-7677-b9b6-073be5c02f99
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-341e-7d0a-b9f2-c4d438d1a54d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-3426-70dc-ab2e-b74ea88ce85f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-342b-79b4-81e7-ff89918ddb4b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-3432-7f6e-8efd-6f98919398d0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-3438-79ec-bece-ae20b24c2f9f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-343e-748e-a8a0-3303c95c5d25
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-3445-7d42-83f5-88dd5634d1b8

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-48af-7e22-a655-2d2515b74acb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-48b5-7ee6-bd3d-1130bde6fb7f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-48bc-75d7-989a-674b05a51bd2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-48c3-7414-86c4-f4ceb554e0e0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-48c9-7b7c-9d0e-f1ea26d4183d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-48ce-79fa-85fa-3ef18d7edbe8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-48d5-7668-a2c8-505360d8c0a6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-48db-7b3e-93a4-89c45e359026

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-54c6-755a-b0b7-1426a2d4f80c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-54cb-7d10-bd88-edb10d763d49
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-54d2-775c-b8ce-49b2a96823ee
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-54da-739b-8398-78769483720b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-54de-73c2-bba7-f3120377b0fd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-54e5-7f5a-a86c-2c83173a9e4e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-54ec-7c63-8126-606070275d9b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-54f2-70d5-89ea-716231fa9679

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-6633-7c1f-9222-13965c9677a7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-663a-7591-89fb-837f6d9dd408
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-6641-73cd-a804-eb427fc034a7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-6647-7429-93ab-520797bcfa60
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-664d-75fb-87a8-4f25f4be51c3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-6654-768c-902a-6de3e2f68440
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-665a-7a82-8506-539b9c2015cc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-6661-7b9d-9f91-1c3527a57c74

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-7c5f-71e9-9e15-3da4a26f1dd6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-7c63-727c-8751-77fdd62fcc52
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-7c6a-7501-970b-480325a9aa0c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-7c71-7edf-9b62-ed71c8e5480b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-7c77-7324-be93-c851d42b7107
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-7c7e-7b00-b589-8e31dbf2d203
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-7c84-7f65-af11-1d85640fba30
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-7c8b-7b41-8b8b-74748ebb8068

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-9119-7f05-b875-b008f0db1617
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-9120-7b9a-b50d-5097168f2412
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-9127-7161-83e4-4b1507ef22b8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-912f-7c58-9b3f-4b89146eeab4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-9135-7428-b247-e597c3066362
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-913c-7384-8db2-b5cf5ff822a6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-9142-7715-8230-7fd655f1a3b6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-9148-77bc-a7e8-fcec7a870239

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-a598-7254-8375-bab007dd9c13
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-a59b-7d92-a19b-fda3d4e3b208
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-a5a4-7f73-81c5-10e5ff570099
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-a5ad-7301-be97-a8c24a59eef1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-a5b5-79ee-bdbd-80c2c9bbfbb4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-a5bb-7e49-9668-2684aa587991
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-a5c1-7b1d-9c6b-5882fa87ec9d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-a5c8-7409-9887-4e8bee721ca4

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-bcdd-7fcd-80ec-eb92be99093e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-bce2-7852-b764-ac1b3c5aada3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-bcea-7a59-8eb7-a1aa9d8ae9fa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-bcef-78ab-b0fe-e5eef8faa0dd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-bcf4-7e35-a67e-159bc2d4c67f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-bcfb-716d-b027-ef9cf8521460
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-bd01-737d-84fe-547ce4f69937
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-bd08-75f3-a5ea-0c7433e50fcc

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-ca1b-79c0-a78f-803206c90189
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-ca1e-7df9-bd85-7c863e364314
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-ca26-740b-b7e9-4fccb9c59ac6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-ca2c-748c-8845-83445a29604d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-ca32-738c-a7a3-bc8a4e27545c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-ca39-7073-b84b-f51754af5e15
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-ca3f-7e6f-b7f0-3efb5b6651e9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-ca46-7c2c-8845-9e33f23114cf

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-e3b0-755f-9e20-2cb38bb16b5b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-e3b6-7fb0-9b54-448b1799d235
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-e3bc-7dc7-ad20-0bb68c97d4bd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-e3c3-71c4-a968-eb967f27a60a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-e3ca-78bb-bed6-aadd96c1ecd2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-e3d1-729f-8d3b-1444e18ec575
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-e3d9-7994-a9e2-a01e06852e73
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-e3e0-7006-a82b-00465fc6121b

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-fac8-72a1-8c07-6c24f6a26a87
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-facc-70a3-ac59-5aceb6a8fe19
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-fad4-70ea-b8e5-e685a1e5c71f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-fadb-75e0-a099-750132f3a398
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-fae2-7b51-9dbd-6e7fe2cf7e15
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-fae9-78e0-b966-ce0f4fbe6de5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-faf0-7ae1-a82d-a502056d4ce3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e8-faf7-7b24-8f83-b6ef981d1724

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e9-1490-7fdc-882b-9801d7524f88
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e9-1496-7cbe-b75f-e261f52156f6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e9-149e-7e33-b061-e836fbedbaf1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e9-14a5-7cf2-b299-2f29dca86d31
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e9-14ad-76a9-9f5f-bc017610bc5a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e9-14b4-7850-be23-47223e57bb66
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e9-14bc-7bca-aa16-70a6e6d23f89
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e9-14c3-7c5d-af10-bbe55a570667

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e9-254f-7b02-b0f0-393494230389
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e9-2554-75d1-b3c1-aaf3d433667f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e9-255f-78c4-b5a6-5a7222b8ff4a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e9-2567-7f32-bec7-a88ede94a86e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e9-256e-7855-9b54-3aff2b5aa57b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e9-2576-79ac-b907-742a87d1fad8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e9-257b-7c1b-bf53-c8bce8b7db41
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e9-2582-7811-af88-c64bde904f85

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e9-40be-72b8-801c-f22489ac1f09
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e9-40c6-77f6-a2f6-82b668f23862
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e9-40cc-7c28-8524-0765cfb9127e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e9-40d5-72ff-98c0-87cb10286fc9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e9-40de-7a3c-ac4e-c5324ff7ecc9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e9-40e2-7407-bef8-4e602f6ff5f0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e9-40e8-7407-98ba-95a9c30357d2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e9-40ef-726a-8e6c-4a49f19847a6

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e9-55f9-7a5c-80c2-da0fc2f16ffe
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e9-55ff-7a4f-8714-2391094f153c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e9-5608-787a-8b84-86815c27687c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e9-560f-715a-bea0-6de8b740486d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e9-5614-742e-b69d-c732f9abadb2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e9-561a-7c69-a331-5b11da7b0daa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e9-5620-724e-b7cc-f5e127882a3b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e9-5627-72c1-bf42-3ed03a072b7d

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e9-685d-7575-b075-a976a6279898
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e9-6860-7c27-8204-18e7ebcd6052
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e9-6868-7d5a-a4da-a7520c7c3ea2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e9-686e-7a20-9885-ab01dafb8392
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e9-6875-7b7e-ae3d-cbdca7b25ae5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e9-687b-7e2f-a415-5f05740b2659
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e9-6882-70c9-8d4e-e49a2ed91533
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e9-6888-7ea5-8a89-9d44d40c0770

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e9-8608-76a2-849f-7c654308d111
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e9-860c-720f-a7e1-62637d2970a8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e9-8612-70ca-82aa-fb834a468b71
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e9-8619-72d8-b955-3a88aeb5dc01
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e9-861f-7727-9aa4-f70822061bed
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e9-8625-722a-88e7-5beaeb1e2553
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e9-862b-7789-ab02-54d11a2a4cff
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e9-8633-72ef-8a49-5de594116896

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e9-a654-723c-a5f8-9273102f6419
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e9-a658-7c2c-8cae-6e14494cbd4a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e9-a65f-7fb0-99f6-dce6effb4491
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e9-a665-771c-95a8-4aa06d5f7b49
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e9-a66c-7e4e-b25b-8234c7d24c80
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e9-a673-7d18-86a8-8a523a54e600
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e9-a677-743e-8aad-edcf42f05b7e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e9-a67f-7302-8375-665372603459

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e9-b2ec-7d13-9a1e-0611e4024e38
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e9-b2ef-7ece-aa7b-c7a147485f47
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e9-b2f8-7afc-abb9-e1d9454f20c7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e9-b2fe-77ff-b643-73f41eae5012
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e9-b304-7a0f-8ff9-4e8c77453805
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e9-b30b-7e7b-b0e2-5ddfbf8c87a1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e9-b311-7333-9e2b-95327765c671
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e9-b319-7dc4-b647-8614d86f835d

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e9-c8a2-7cc6-badb-f049f989e390
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e9-c8a5-714b-a5f1-92a48428e380
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e9-c8ad-7bb0-acb9-030b6ebf9ccc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e9-c8b5-725f-b10c-3821a5f89935
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e9-c8ba-7cce-9d72-fed1053d77d5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e9-c8c0-71d7-aea7-514f9e5d09d8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e9-c8c5-7d1f-b988-95d6652ee1bd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e9-c8cd-7832-870b-e63fa2edc2ea

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e9-efb9-7d13-be3f-3b4416ede79a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e9-efbc-76d4-b8c9-b693e7e9da40
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e9-efc2-7cb0-9489-6722279eef55
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e9-efc8-7f94-b744-199b598c9dbd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e9-efce-77c6-a4f3-7376b0bfbcb4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e9-efd6-77ea-b592-246c087e667f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e9-efdb-77c9-9564-63423ab79f53
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1e9-efe3-77d4-ad3d-72ede0806270

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ea-0608-7475-a081-2673a1b358f0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ea-060e-7fdf-a579-28a0328bbf55
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ea-0617-7d65-b8e6-cdb5bcfbecf7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ea-061d-7628-9df6-3f3fc5fc9b6e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ea-0625-71bf-8f0a-1b959c72f682
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ea-062c-7c75-bc3c-63c9fb5514ae
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ea-0632-7ad2-b173-48445cd0f970
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ea-0638-705b-93a2-f8b7798e5b39

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ea-26e5-73db-a3dc-86e4f7b10b0e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ea-26eb-76eb-8f9c-712053061f22
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ea-26f1-7454-8cc5-9ec0128f6bc0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ea-2001-714e-9c9d-f94f1120f5dc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ea-200b-7c9b-9e85-80a189e9f8fb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ea-2016-7cef-82db-30575b49efd6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ea-201d-71be-9b75-f7c8b8c3f4d6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ea-2026-7b6e-9faa-471f5b183c07

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ea-3a0e-70fc-bf0a-614cf1ab6800
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ea-3a11-7603-8b26-293e29e804f3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ea-3a18-7cbc-b216-3d83a480ba00
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ea-3a1d-77ae-8fae-994a04f21768
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ea-3a24-7166-a5fb-e49250ec6507
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ea-3a2a-79fd-8f84-9413732cfc17
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ea-3a31-7226-bfc3-8fa1499560c1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ea-3a37-7516-b30e-dbdc3eda0475

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ea-528c-7819-9353-b57d43c256d1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ea-5290-7f46-9468-9c52a591c729
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ea-5297-7335-b4ee-d99f14484e46
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ea-529f-7942-a89c-1d0cdff4f6ef
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ea-52a5-7d09-9a9d-85109e0386d0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ea-52aa-77f8-8abd-b7c139946ef0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ea-52b1-7cd6-94bc-80623ba9792b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ea-52b7-7aa8-92df-3901dcb56333

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ea-6a16-72d0-a2d1-8644bc3c9ace
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ea-6a19-754f-a400-e89749d35d86
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ea-6a21-7cba-88f5-b72c3e1c7f90
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ea-6a26-783f-a463-5c898906aa82
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ea-6a2c-7213-9fff-ff259059ba75
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ea-6a33-74f4-9cf4-86808558afca
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ea-6a38-792c-a637-2bedc5d95ef4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ea-6a3e-7237-bdfb-8366ec228073

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ea-7f67-779b-aa1b-50dec7b46ef9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ea-7f6d-745f-9986-1819c12c2a43
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ea-7f72-73d3-9fbb-d402d225409f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ea-7f78-768c-ac72-93ab9ee5f25c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ea-7f7e-76d6-a1f8-19ab147d842d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ea-7f84-7dcf-ba7a-d863a88c056d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ea-7f8a-74ff-8c67-fe6915a2a5f3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ea-7f92-7847-aae1-5c7b47e5684e

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ea-92d6-77ce-b88f-06894b1019bd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ea-92da-7469-8624-834a3e6a5d50
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ea-92e2-735b-90aa-e5c7817961a4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ea-92e9-7559-a721-89731f26fe9d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ea-92f0-7a09-a876-cac4c2643c6e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ea-92f7-7a43-99a1-a4659aa304b0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ea-92fd-7092-a05c-92b772a07db5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ea-9304-750e-9917-9800217de694

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ea-a084-7807-8894-008201e8f53e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ea-a087-7291-aed9-bc72d76614cc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ea-a090-726e-a448-c7beac1152e4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ea-a0a4-7b4d-bc59-0c7da23c3647
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ea-a0a8-7325-9fb5-c250a8ba53c2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ea-a0ad-78a0-a5fa-a6fdab9f23aa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ea-a0b6-7db2-bbc9-9699795da979
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ea-a0bd-7f58-95e3-a0b04776fe65

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ea-b553-7160-8286-85a60831d4a7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ea-b556-7150-b50d-701033bb4700
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ea-b55c-7cae-8064-78151bfbeebd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ea-b566-72e5-9e1e-85eae03a7d8c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ea-b56c-7d39-8ba4-bfd28b2c6a01
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ea-b572-7896-a46f-4a399f1f189e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ea-b57a-7599-bbbc-421610d50378
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ea-b581-7cfd-a38d-c51b716ab573

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ea-cb87-7d27-9bec-8fc5b22706bd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ea-cb8b-7e12-a5b4-51d84ec174e5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ea-cb93-70fb-9de4-792598f2ea3b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ea-cb99-728f-a947-7977fd46258b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ea-cba0-7ce2-845d-8722c52ea605
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ea-cba7-7667-a525-ca9d9a2e0e0d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ea-cbac-7d50-a160-18b8b99f1adb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ea-cbb3-7dfa-9678-8816b2b1aa34

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ea-df9d-70d6-b7d4-2c8a15cbb7ca
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ea-dfa0-7a6b-8539-3e301f36dc2e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ea-dfaa-706e-be63-de8d48d3d05e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ea-dfb2-7f6e-99cf-ad22070a4f23
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ea-dfb8-7ba8-ab6b-bf0728fec475
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ea-dfbe-7f5b-8e11-8e4c62f20009
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ea-dfc3-736a-ab7f-f760d974d219
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ea-dfc9-7547-a156-11a83f3ca107

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ea-f187-7d42-adcd-4bf993eea58c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ea-f18a-77b3-be3c-56e9b5ea3de8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ea-f190-7980-81de-25b69f7529f0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ea-f199-75e9-a3c6-80f6193aa211
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ea-f19e-7bbe-ae52-05adaa86b506
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ea-f1a4-70b2-87dd-730da3608609
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ea-f1aa-78b2-92db-7a05d386ac34
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ea-f1b1-7794-8eab-f1eec320a2d7

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1eb-08c1-7780-976e-a5499127bb2f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1eb-08c7-7584-b3ee-af1af60be6fc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1eb-08d0-7f80-9329-789eb53ddbc9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1eb-08d6-7c40-9c43-727301670d1c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1eb-08db-71fe-a800-ba796eba6818
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1eb-08e2-7060-8db3-b89056ccaec4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1eb-08e9-7055-b3b6-8ace254c8667
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1eb-08ee-76ea-9e45-b42c3de9b6e4

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1eb-298b-7beb-9d31-e342a36c926e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1eb-298e-7b01-bba0-84a0d91306b7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1eb-2995-7b12-955b-858aac96443a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1eb-299b-75de-bb7e-0c7b06c35d55
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1eb-29a2-710a-bbc5-b22ebcd8a98c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1eb-29a9-712f-ab29-9b8ffb673892
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1eb-29b1-7026-8dfc-6a2479b5fb68
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1eb-29b7-70e0-909d-ec2f3392e6a8

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1eb-4760-73af-98d5-52fc99248593
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1eb-4765-7d2d-b851-b69a1a03bd06
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1eb-476c-7726-ad6f-ac5f79072cf2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1eb-4773-7fe9-a0e1-34baf2500d2a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1eb-477d-76fa-8ab0-5fd026e35eed
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1eb-4786-702a-9f88-6c64a7c43bc7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1eb-478f-742a-b456-c7e0bc2c06ff
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1eb-4796-7f90-b6fb-e0db46ebf018

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1eb-6774-7958-88d4-f3e4ef65b567
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1eb-6779-76cd-a146-f63cd6791bfa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1eb-677f-7d4a-a1c4-07674d4d83f7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1eb-6785-7903-870e-24d7b52ec0a0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1eb-678d-7587-aa9b-b0859eaf576b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1eb-6795-7337-a56a-0c581c816501
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1eb-679c-78ec-9c87-8275f35afd50
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1eb-67a2-76b7-94ba-14f1450c4307

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1eb-7e3b-73c9-b1ab-c3a9db45a585
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1eb-7e3f-7b4b-ab02-10d71a767261
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1eb-7e47-7d48-b06d-adeca96337f6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1eb-7e4d-7b4b-bb51-926d73323831
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1eb-7e53-7245-9d8e-6499dfd417a8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1eb-7e5b-7c9d-9671-8786d0380163
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1eb-7e61-7273-92be-cd6726653aba
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1eb-7e66-7b8a-aa02-a5ef7b33fa5d

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1eb-92f5-74d8-b59d-ac7132899cbf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1eb-92fa-77c7-abeb-bcabccdb4a12
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1eb-9301-70ef-9aae-c390ecf4fac4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1eb-9305-7dab-9548-639352189c17
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1eb-930b-77c5-b038-5727f6318aeb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1eb-9312-7dbf-9f7f-8b6711ea1630
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1eb-9317-7db2-91b5-8af0aad4331b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1eb-931e-7c5b-b268-84960f3583e6

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1eb-adaa-7473-be9a-7edccbd53822
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1eb-adb0-72e5-a775-efcc9d48197a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1eb-adb5-7de6-9fec-4fd9c4afade3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1eb-adbc-7837-9039-8938b85b17e5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1eb-adc2-75da-b048-b891a3ddde9c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1eb-adc8-7aa4-aeaa-de94b7190a9c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1eb-adcf-79de-976f-564d3b744c79
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1eb-add4-7e94-a2cb-0f5424101794

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1eb-c776-7f6d-a9e8-0fab0acd0b3b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1eb-c77a-736f-adcf-a3435f11b567
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1eb-c780-7628-8edd-624c15e2cbc9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1eb-c786-7fe4-b523-e6b4d6b84a21
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1eb-c78a-79c4-a746-cc2dbb570451
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1eb-c792-75a3-81a7-eebf5df22341
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1eb-c798-7504-a5f8-b21e420231bb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1eb-c79f-767f-b226-07290007cd26

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1eb-e5b3-7e0e-964d-47deb4655357
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1eb-e5b8-7a4d-a95d-568d8494e8eb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1eb-e5bf-7128-82c2-0770c5728f4f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1eb-e5c7-795b-b609-a90599719c9e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1eb-e5cb-7200-b109-ddf612f510df
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1eb-e5d3-7dea-93ae-af260cdab88f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1eb-e5da-7280-8963-a86915f9baf4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1eb-e5e1-7471-a939-d629cfbf470f

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1eb-fa39-7c77-b643-5677c6087a2a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1eb-fa40-7ce0-ab58-f4e36489d338
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1eb-fa4c-7434-a4b9-98d0d485ef03
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1eb-fa50-7c1e-aeed-3169056d812c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1eb-fa56-76ce-84e4-0270718577f0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1eb-fa5d-7d5d-ae6e-0b356e464640
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1eb-fa62-7306-9796-f31e9f59afed
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1eb-fa6b-762e-a811-8e91a7d79267

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ec-0d51-761f-8883-23bce5a26a94
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ec-0d55-7def-b164-ad5c316c3820
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ec-0d5b-72cb-9349-5aa530128a9f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ec-0d62-7e9a-8e76-f3b2e82c587b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ec-0d6b-7fdc-a9fb-eeea2e725d80
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ec-0d71-7301-9817-8b769962cd45
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ec-0d79-75d7-865b-4923f2335eab
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ec-0d80-7c87-b541-b31977837171

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ec-1f69-7806-8ae6-090dc26dae16
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ec-1f6d-739d-a3a0-a63cd1d88e8b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ec-1f75-758f-a4d3-67c6cc077f63
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ec-1f7d-7676-9f97-1a12a2ce676e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ec-1f83-72e7-bb3a-370f60855901
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ec-1f8a-7c5e-8827-8b2ebfae2ebc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ec-1f90-7a54-bb24-8601fb47433b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ec-1f98-7693-b042-78cf897539de

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ec-407a-7a40-a735-6468a3cad4b7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ec-4080-74ba-913d-869982cd964b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ec-4086-79ac-b7a9-363c108e7409
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ec-408c-7567-a690-81cbd5857b32
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ec-4092-7e87-9c30-239dde6c3951
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ec-409a-7aa6-ae00-d1db8f58b38a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ec-40a0-72b5-906b-b8ac236e8d2b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ec-40a6-7d9c-a9b6-39d598bdf403

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ec-53ac-7d4c-99a7-f6b8208b4ae3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ec-53b2-7116-a5e2-9fa94e3e7701
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ec-53b9-7dff-8c13-680317afd087
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ec-53c1-70bd-994e-96f1e4aacdc5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ec-53c6-73f5-a3ef-53a02f38340b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ec-53cb-7b9f-825c-98e8831811a5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ec-53d1-7fb1-9a86-ea6bbd6e924a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ec-53d8-759f-9a0f-0d605e8a0694

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ec-696f-7856-bded-4e51bdd383ec
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ec-6974-7afb-899d-d3a89ba69666
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ec-697b-7a06-a53d-ded43876b629
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ec-6982-7d26-843e-29c68a2ced18
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ec-6989-748b-a0c6-438cf92e4a84
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ec-698f-7980-ada1-f37e0c865d5e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ec-6996-7022-a13a-19f40371a919
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ec-699c-71f1-a0b0-37936ea6070b

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ec-8610-79c8-889c-97e19f0b025f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ec-8614-72bd-989a-72b186da7a3e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ec-861b-7b4c-a72b-81b78f8e24b8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ec-861f-7d63-9442-73579d233ebf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ec-8625-7d01-b278-76ec5e453c58
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ec-862c-7ba5-86d0-3361dd436fa2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ec-8633-75f6-8053-7bc94759778b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ec-863a-7b7e-be7c-c5773db8545d

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ec-985e-7b2f-ae1d-00bb69700288
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ec-9865-7409-970f-cc0d8cfd8ed7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ec-986a-7989-abc5-22ad8718b3c1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ec-9870-7e2a-9e07-596e8ae523f7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ec-9877-7ce4-8781-44e206666763
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ec-987d-715b-a04d-7ab3394753df
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ec-9885-7be8-b6d7-2e55b75f6fd5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ec-988c-7d55-96fe-e3280bb3c6dc

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ec-ae88-72aa-a808-cb0517c2f649
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ec-ae8f-79e5-855f-a79ba4d190b1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ec-ae95-7dcb-8d1c-70ffef456afd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ec-ae9a-75cf-a356-db7a85b02185
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ec-aea2-7dd9-9cf2-0c7a8857cb0d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ec-aea7-7816-a0a2-10b294e4609c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ec-aead-7d0f-8c66-277edd9e76b1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ec-aeb4-7ed8-af52-22d1a8161749

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ec-c50b-7d66-ad0c-c0cc879f73d1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ec-c510-7e0e-baf3-3fdbf1b1696e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ec-c516-735d-81fb-0932d8952bea
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ec-c51c-7a8f-8651-749da7cd3d56
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ec-c523-782c-a604-49d292566da9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ec-c529-7b8a-9c4a-82613f7030fa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ec-c52f-7b33-a44d-566b54739fc9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ec-c534-7c0a-ba1f-0fadda285131

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ec-d64a-7c91-b513-9928749549c0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ec-d64e-7bed-8dad-7e2afee18575
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ec-d655-7cc0-84c8-057695d50aa1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ec-d65b-7d82-a8a1-7dfb50c90b90
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ec-d661-77b1-982d-7c78a3a82d01
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ec-d669-7e51-8773-056625c7ef08
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ec-d66f-7c66-96e3-71e89120daa8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ec-d675-76ac-af78-4fbcf3ad1bfa

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ec-e960-7f4f-95d3-e68ec5cc1b43
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ec-e965-7f40-bbbe-c481b9fe1bc8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ec-e96c-74bc-a778-5418bb7bf81f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ec-e970-770b-b5ab-688f8547d4ca
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ec-e977-78ec-9b37-d4bb2db38cd2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ec-e97b-7f98-aa17-792decb5b81a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ec-e984-7a53-b273-899432a72fab
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ec-e98d-7e59-a2f4-cba11cbf7dc4

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ec-f6ea-7985-9303-d15171f486a6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ec-f6ed-71f0-a5ea-dff808dd5d94
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ec-f6f3-7ef7-806f-1f30bd49d00f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ec-f6fa-7473-964b-8cfceb6fca2c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ec-f700-792d-b8df-cba97ac15e78
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ec-f707-701a-8022-3ef28b9b5815
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ec-f70f-7747-aef4-6e537498f504
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ec-f715-7538-9a72-0c573e838b7e

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ed-09d8-7036-88de-6c5beddcc768
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ed-09dd-760d-a482-5f1ef9bf1b54
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ed-09e3-7b80-95ee-067b2633c971
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ed-09e9-7993-a2dc-2b8763efa704
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ed-09ef-77ac-9eae-0b09a0acda4b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ed-09f6-739a-8ffe-dbd6670dfa9a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ed-09fc-713f-a2ba-26e76fca0b3b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ed-0a02-720f-af63-df7a6774f283

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ed-21ee-7d6a-89a9-d3f9b693eb15
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ed-21f0-74a0-a798-fe2fa44de44d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ed-21f7-7d1b-98fb-743614d083ed
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ed-21fd-7875-8ed5-933aad990669
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ed-2205-71de-9c8d-a4bd264fd2f1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ed-220b-7b97-a472-a5749983d07e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ed-2212-7f3d-8954-0ed51d2467bf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ed-2219-76a2-962e-326336565ff3

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ed-318b-773f-82cf-d98fdb9b1d58
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ed-318f-771b-a892-fa3310a32a81
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ed-3196-7453-816c-c072c7730bb8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ed-319d-714f-ae9f-893465c84949
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ed-31a4-72ec-9b5f-07876cd8e0bb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ed-31ac-7868-badc-0d7cc15a8554
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ed-31b1-7717-8390-0b9f17f34ba4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ed-31b7-7ef2-b5af-cc13a19e1b3a

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ed-47e6-74ca-bd32-746bc0e24d1d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ed-47e9-762a-89cb-4ae7a78912e6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ed-47f1-794e-b68a-c316f7248b8a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ed-47f8-7d02-8d2b-eedce37401e7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ed-47fe-7acc-8cb3-b60692950883
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ed-4803-7ec3-a1cf-e9f20ed0fcb4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ed-480a-7ad5-8f45-b7880f2496f0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ed-4810-72a6-be19-3b4bbc246f2c

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ed-5fbf-706a-9fee-ed73df591795
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ed-5fc5-7a49-b590-c8aebbac551a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ed-5fcc-74de-89f9-1ad34d8bb679
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ed-5fd0-7111-a40e-ecd4f12aa660
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ed-5fd7-7036-8727-e013913522c2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ed-5fdd-7ce8-848b-4c992db33b6b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ed-5fe3-7fad-8b83-327fd9ceb9e5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ed-5fe9-717c-a969-39503ef39c7d

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ed-6bf5-739f-82f0-e8bcfba93b99
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ed-6bf9-7b84-88c9-75242b2178f6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ed-6c00-78a2-97ed-fd8d61697d7d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ed-6c08-7ba3-b4f7-0e7e18fb4188
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ed-6c0f-7294-a592-0710bce56409
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ed-6c15-7d8f-81c2-372d74840bf2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ed-6c1c-7fef-9a14-01f8a3b53052
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ed-6c22-78c3-8339-b0f9f8b3d10f

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ed-8197-7031-816e-3e359332951e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ed-819d-7192-9215-0a3078370ab9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ed-81a4-7dba-9e43-fcf4450130aa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ed-81aa-77cc-99a1-7e030c62d3e0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ed-81af-7bf1-97e8-8f644f4929f3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ed-81b6-787a-9374-5a7754839db4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ed-81bd-7c9a-b993-17c2e329ee1b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ed-81c3-7260-926b-63e8c12e109b

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ed-9dc1-74dc-bec1-85018f1cf2d6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ed-9dc7-7243-b447-29c438dd799b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ed-9dcb-71c6-9192-374d87a33b76
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ed-9dd0-70e8-9713-e707a20c684a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ed-9dd6-72c9-8ffb-05f7dd657edd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ed-9dde-7c81-a779-c096d3959d5d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ed-9de4-7fd3-aa26-1d7883e4029d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ed-9dec-79c9-a110-77a824a9198a

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ed-c446-74f8-9705-a2aa4ba63e71
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ed-c44a-7c97-bb0a-1b960d1037e8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ed-c452-768a-b945-f2a92fb5508f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ed-c457-7423-b221-dd7be2cdc006
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ed-c45d-7995-add4-af6f6fa81f5a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ed-c464-7575-ada8-00c1c5fa5263
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ed-c469-725e-bd22-d9cb67c86ba3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ed-c470-7897-a20f-279b41828375

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ed-dd36-7341-a9d0-39b255e4eb31
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ed-dd3c-74b6-88a8-40a5ac52a535
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ed-dd40-7dfa-a4f9-505eb615d2f7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ed-dd4f-7ff3-b0c7-fd4463a4f0ce
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ed-dd54-70ba-8cb6-ce974f8be008
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ed-dd5a-7aa0-98f1-c136e4e294c5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ed-dd60-7573-babd-6089bc563d54
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ed-dd68-72ce-8145-9beedab42081

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ed-eced-7323-8bfb-557c75188a21
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ed-ecf1-7196-9bc8-3a60e307f995
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ed-ecf9-7fd7-a507-a2f1a2cca2dc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ed-ed00-7ba3-a778-67a158954b45
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ed-ed04-7843-9a95-01bcf2895c50
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ed-ed0c-7391-8b6f-2ad5d807d9b7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ed-ed14-7e43-81b0-00a847109678
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ed-ed1a-7f23-867c-f5a95883bc53

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-0456-7b0c-9189-62de8fcf8481
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-045a-7813-a4f0-c9f62296c2e8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-0462-741c-b2fb-5883ccfa9f52
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-046b-75d1-ac08-1b6f07e3ac35
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-0472-7179-9ac4-4b3d1e1b98e1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-047a-73af-88d4-77ebac4894db
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-0482-7f20-a5fa-d07acce69f30
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-048a-7fbb-be06-318c526b35b9

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-1948-70c2-a980-a9d14ee60d0f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-194c-721a-bf48-eb0126ae6841
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-1954-79b0-802f-ea06cdf916cc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-1959-77bc-9c3d-25b5b0911e58
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-1960-716f-a144-fafb8d287769
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-1965-702f-a917-3f052f401b75
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-196c-7d86-a7e0-e866f4708bd6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-1971-7bbc-8d9d-8e88ac134885

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-2c1d-758e-86f6-8d517c3409ef
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-2c21-7069-b3e3-2efd95bd220a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-2c26-7ad1-b9d3-cd5af5213b6b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-2c2e-79c7-b204-fec2b19d80b4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-2c34-77b7-80c9-4ad74ceca8eb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-2c3b-7007-a154-87cc66413805
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-2c42-7d83-bdb9-cbfe45b50d37
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-2c48-7023-8752-02027ed268b9

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-462e-7820-9699-15ae3bace455
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-4630-7cd8-96c1-36b62f6c898c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-4636-7835-b65e-79faf5c96f24
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-463c-710a-baed-459ce1328398
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-4643-74ef-896a-bcc085785252
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-464a-7a96-8488-b24f67cb04f8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-4653-77da-ac01-b83ac6a0f793
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-4657-73b9-aa1b-a9cd66095406

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-5221-7c51-b8ba-0ba7c6543f67
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-5226-7768-b200-bd4779e7c3d6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-522d-7828-834d-f02b4f8fd327
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-5233-729d-947e-e158fe82707d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-5239-7816-9117-6fcfaad906fa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-5240-7d99-a113-0b9802a6be02
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-5248-7413-8c78-53563ca90a9c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-524e-7f90-9ca7-cf2d6b0590dd

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-693a-7198-8cb4-e40263f990fd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-6940-79a8-bc8d-dfda505ece80
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-6945-7002-b9f1-11b46a3d6e5e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-694c-7c06-a80e-ef5fe0e801f9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-6952-77fc-b4bf-03a0fa9aba34
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-6958-795a-9c7f-2c5c3da7876f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-695e-7adf-8223-009c6269ca8e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-6964-73f5-9247-27e0627d953f

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-7e11-7bef-b716-2acab79dc5c2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-7e15-73b8-8fcd-d72394dfaeac
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-7e1c-773c-8500-ba89acc74c23
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-7e22-7772-b2b5-cdfe35b01173
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-7e28-7d0c-9312-d5df8058ec38
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-7e2f-794b-8a10-ae269b1140f3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-7e34-7bbb-8eb5-0e0546a9b581
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-7e3b-772e-a9af-6032ff11d1d0

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-9a8b-716e-a8ad-efedbf2af175
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-9a8e-7510-a9b6-d5d46f750a44
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-9a96-79b8-bd3d-4cfb81dcc595
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-9a9b-7cfb-aa67-4a9536fa0089
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-9aa3-75d0-bce4-a5350e5fd27c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-9aa7-73a1-82f0-5eb934546487
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-9aae-7c39-a0f7-52e5f7ff5930
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-9ab5-7530-b315-5e26c1a86942

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-b052-7c9e-be3b-8260ab7ace91
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-b056-7f68-942f-a8a16824a87b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-b05c-77bf-b875-5531b4215224
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-b063-7739-8c4f-bb2bcd339218
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-b069-76c6-93ef-4074955beb80
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-b071-78f4-b4ae-63643b80ae54
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-b076-71b1-93c7-d0767e472912
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-b07c-77c7-b5f6-db3b0dc0455b

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-c5f9-7f14-b702-5fb02f5faf7b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-c5fc-7259-8f9e-19696125f13d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-c604-72d3-8e04-c170eb9c00b3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-c60d-7131-8819-5d3e6ecbf238
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-c611-7be6-b8dd-f09a17d62306
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-c618-7911-a488-0a43d216b927
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-c61e-7845-a025-d1f6be2c2e26
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-c625-7a7b-b3fc-fc672077fd8f

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-d411-7604-aa31-f82fe27ca133
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-d415-742e-9043-cc5aab97a58e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-d41c-7c56-a8da-bfb4beddb401
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-d421-7165-aeda-b61f96bac9a1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-d427-743f-895b-79608405f2b8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-d42c-776e-af8c-e86518b2f2d7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-d434-796b-98c2-0346592de2fe
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-d43a-7fc7-abc9-20bb8939c25a

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-eb60-787b-bb92-f50e625a2aae
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-eb62-78ab-b5b5-154817774e01
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-eb69-7d5a-879e-3f1e8c7bfd19
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-eb6f-7731-a26a-7bb643b70db4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-eb75-7493-9ebd-ffd0a94e9b7f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-eb7b-71b2-bb9a-3e733359a44c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-eb80-701f-b2a7-7b601e65e875
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-eb87-751f-b33a-1c8d5a6173c4

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-ff26-76a7-9335-71133576d3ff
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-ff2b-7794-8174-86887e298295
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-ff33-7cd6-bc55-74df847649a1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-ff3a-7ea3-9389-c12b64644d59
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-ff3f-70d1-84e0-c310edb89652
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-ff48-7d66-ad17-6546b4d511c6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-ff4e-7f96-a30c-4399b580d65d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ee-ff54-7e3c-a8a5-460375e602a1

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ef-290a-7009-913e-4012d1f3ef56
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ef-2911-7ef8-aba8-b76867bdfea5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ef-2916-7bde-8136-c087632ee84d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ef-291c-7bbe-a55d-3aed5dedcf3c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ef-2922-7d77-9aa1-3ee6c33b4aa3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ef-2927-7d63-8740-f15039d3571e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ef-292d-74a6-8140-13a7c168c7d2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ef-2934-7f17-9ad0-e34b8eb103d6

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ef-4847-79a5-a57e-bd16443d2e3f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ef-484a-7342-9faf-9f2504da91e6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ef-4851-7554-932e-278da1c64288
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ef-4856-75c7-b36d-9a08bf15e3d1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ef-485c-714f-b614-d004a00ff228
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ef-4863-76ca-a1ee-ba7423bd6bc7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ef-4869-7d69-a158-35882f03ce71
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ef-486f-7f28-ba5c-19c05ad14b51

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ef-5d34-719c-b589-0f1fa128d5fc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ef-5d38-7d02-8a6a-9346a61523cf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ef-5d41-73a3-b907-0e6273a5516b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ef-5d48-7884-ba95-2b9f6b5010b4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ef-5d4e-71cc-b5dd-67308ab416c8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ef-5d55-7266-9ad0-5bcdc4001d17
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ef-5d5a-787b-8988-2ec0e9129a6d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ef-5d60-74a2-8afa-6ec4fee2956f

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ef-8171-79ae-955b-a04a3d372376
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ef-8177-7b55-9f5d-930b7660f689
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ef-817d-79a1-aa06-676c83df397f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ef-8183-7c04-acd3-50b39417cf8f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ef-8189-7288-ae02-163ee34df352
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ef-818e-7345-a187-b450057c93a3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ef-8194-716f-a738-ce9b5dbbaf90
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ef-819b-7a4c-ba24-fb64b4009426

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ef-9a5e-787f-9159-6ad75f5bf775
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ef-9a60-7552-8689-1c2553a2f2f1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ef-9a68-7e5b-afd8-6b6948e45cd8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ef-9a6f-7d62-b9e0-49182ba69869
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ef-9a74-7597-8b3c-60cb7d84d3d0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ef-9a7a-743d-8195-db1209525cb9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ef-9a80-7820-a47c-0ee739674984
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ef-9a85-7625-ae97-3ee81ecabb20

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ef-b305-7c57-86ef-fa833174865c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ef-b309-7f0d-8e4b-7612ae8553d6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ef-b312-7af9-aa2c-05be5b2f444b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ef-b317-7ba9-a4a9-779690d50692
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ef-b31f-7ba3-99fb-6a7424a8a3bd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ef-b327-7ebd-ba3f-8959a9c494ae
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ef-b32b-7897-926d-35705fc94b50
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ef-b332-7d14-a94e-d4d3905d9fb8

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ef-c293-7f8e-93ed-daab93cc815a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ef-c297-71aa-a9d5-388f41eda7da
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ef-c29d-72e1-bd5c-2cea62aef66d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ef-c2a3-749b-bd09-34691f98e61a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ef-c2a9-7d29-8e0e-f7b3b645afed
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ef-c2b0-7afc-a32a-4d8f02844db3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ef-c2b7-7d92-b41b-9944827ab940
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ef-c2bc-7bcb-9af9-9ff84ff2244d

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ef-d72a-7567-a073-53336c0de082
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ef-d72f-7211-be44-0746be559b18
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ef-d736-7d5e-a62a-1b91eca9bdec
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ef-d73d-7ad5-931b-c1879cf6409d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ef-d744-77bc-bf2d-df661e1c2c56
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ef-d749-7019-9840-fb42edc164f7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ef-d750-7354-b2c2-4f3049fa93f5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ef-d756-74a0-b27b-ee3187aa1b30

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ef-f6e1-7fad-8337-97229dda8b30
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ef-f6e5-7d5a-b61f-771a9eec0ed0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ef-f6eb-7fb5-9c16-6395e93433d5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ef-f6f1-7f7f-9e26-1d2a0a07813a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ef-f6f6-78b7-b7a7-cc3fd4778530
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ef-f6fc-7ad3-b0da-81a2c1286c1a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ef-f702-761b-aaa6-8bd18b7888d4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ef-f709-77a8-826d-c8da42cd268e

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f0-0a8f-7a96-b6c5-58d8cd836f82
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f0-0a92-7a91-b081-19065d8190c9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f0-0a99-7297-b7d3-cd449812664c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f0-0a9f-7e6b-a9b5-f6d5b911786a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f0-0aa7-7683-af92-401c57814149
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f0-0aad-7770-a1a3-ed37914761fa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f0-0ab6-78bc-945c-b35aba9b19d3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f0-0abe-7aaf-bef9-1376cf097df5

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f0-25d4-723f-ac30-7fa0753cc30c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f0-25d8-76e5-a99d-e6ae0ad29f91
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f0-25df-79f7-8f1c-3ea3ca31920c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f0-25e5-7300-9845-b830e15cc2df
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f0-25eb-732d-8359-cc06aa4cba6f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f0-25f1-7e2c-a15b-3889d8e508ff
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f0-25f8-713f-85d2-1f3090fc9561
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f0-25fd-74f7-9f17-e2820254d146

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f0-32c4-7dab-a97f-c3c80763b76a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f0-32c9-7bae-8733-f71af621acba
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f0-32d3-7398-8aba-731686e2fda8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f0-32d8-7925-8ba6-f05b77de1d38
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f0-32df-7b55-9006-85744dfe7600
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f0-32e5-7481-829b-0f7c809a600c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f0-32ed-700f-ba4c-726ba3cefb84
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f0-32f7-788a-a327-385bbabae8de

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f0-4808-7314-b919-8bc7815591d0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f0-480e-793a-9a40-4910cf48afc3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f0-4815-709f-a871-942d37f6030e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f0-481c-756d-be23-ad9e7042d0bd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f0-4822-7183-a884-05609fd7348a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f0-4827-73bc-ab35-f6a9bea68a66
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f0-482d-793b-beff-9916d7e9bda1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f0-4833-71fe-b4a9-063dff40c373

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f0-5ca3-74c0-807f-2b7c08368973
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f0-5ca8-7570-a522-73f43d9e2732
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f0-5caf-7c20-b010-b9d7ee212ccf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f0-5cb6-70f1-9a74-fc851ec681ca
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f0-5cbe-7136-ab0c-84b842828486
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f0-5cc4-7344-a281-078a0af52112
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f0-5ccb-7a2a-8624-d6f39752eca0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f0-5cd3-7f30-9d09-c509af65f085

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f0-7374-7997-a2ac-43f155396d19
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f0-7378-7240-8359-fbe87bd9d15c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f0-737f-79b1-bc43-c22a4c0eac50
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f0-7386-7d22-878c-f91b5179d845
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f0-738b-7a3e-8c46-f9de5ba51ffb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f0-7391-7968-ba30-36cb0152b577
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f0-7397-7bac-b422-7289c06fd33b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f0-739d-77b7-82b0-70a972331e4e

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f0-8343-74ff-92aa-d0a462a04ec1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f0-8346-7b77-a503-aafa31fb9ede
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f0-834d-773e-8ddc-8d4581eb0335
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f0-8353-746c-91d6-03c0def4a96a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f0-8359-78da-87d5-7b1a4b10efba
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f0-835f-732e-a173-29aeb02ad774
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f0-8365-7937-8d3c-461b86ca41ed
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f0-836d-775e-9f16-53de9bbc4156

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f0-9b84-7e0f-9178-36ea0f760974
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f0-9b88-7936-9cdd-a83a137de227
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f0-9b93-71a7-a474-dd990995a72d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f0-9b99-718b-962c-2cfb076334c7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f0-9ba0-7c2b-ab8a-52f34b38174c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f0-9ba6-7065-86f7-4c5b80826fc6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f0-9bad-75fa-868b-7af43d7260ca
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f0-9bb4-7132-90cc-3df6da5bfe32

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f0-abdb-7223-9bd9-a6f43d1024e6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f0-abe3-7f76-9476-14aa38dfd3d9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f0-abe9-7b76-9fba-a5d1f281caaf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f0-abee-7e9a-b2cb-baf8d9b7d86b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f0-abf4-7dac-a928-e881d1a826f2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f0-abfb-7588-8c7d-b1456888b2e3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f0-ac04-7b71-ae6e-7bcadfd31b73
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f0-ac0c-77a4-8e3e-3169c90dd36b

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f0-d2ca-7138-94dd-3703d8827610
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f0-d2ce-7174-ba61-93e38a945560
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f0-d2d4-7863-8672-312d29883aa2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f0-d2db-799f-9fc5-075051d63e89
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f0-d2e1-745c-ad10-96f3c1d6b2d8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f0-d2e8-79a2-b43f-41e1e666673a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f0-d2ef-7183-89fb-bde50e6a0ec7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f0-d2f6-72a0-a7db-15022be0645a

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f0-e82e-738e-a2e3-7d21b335dd3d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f0-e835-7ae1-87e1-fa9e981eb690
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f0-e83a-7919-b7c7-74a5e103bfc9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f0-e83f-7bfa-9b2a-f5a178832709
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f0-e846-7e26-b629-5ef8acc44e02
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f0-e84c-7c6c-a3b2-b048952038fc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f0-e852-7060-a838-7df5ea1e56d6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f0-e859-7394-b93d-d0b55ad21158

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-038e-7268-ba31-e8774226149c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-0393-74b6-94d7-fd3b7092a71a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-0399-75b9-abe2-d752e8e0fcf1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-039e-7681-8089-0a555abca22c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-03a5-778f-9a2c-089efb72605f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-03aa-7a7c-ae82-02aaf29c9a5f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-03b1-7f8a-aca7-7f44107928fa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-03b7-7310-b2e4-e81fd51355c5

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-1ce4-7c1e-9f6f-d677cf05d6e4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-1ce7-7b9d-9f66-96371045a8ae
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-1cee-7938-b2c0-432e1a8a68ce
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-1cf4-7b4e-8f29-970ff7ae2da1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-1d04-7c16-8a32-6277ea867c25
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-1d09-7fa8-85f8-7d72d09d78a6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-1d0f-7683-999d-ad34ea0b747d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-1d15-78c7-a6cd-7e4910d9284c

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-3782-76c6-9554-d789e1b51ff5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-3787-7af8-bd31-d2e672f3a756
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-378d-741d-8958-d75f3dd0dc71
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-3795-7549-9fd4-3a4425a63ceb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-3799-7f06-8533-fc0bf8bbddbb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-379f-77de-853c-993bdff5332d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-37a6-7114-9df4-3de44f435b90
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-37ab-773e-bc3e-4cad0b9724fb

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-4ed3-723f-b324-72e39c317cba
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-4ed7-7131-a41f-68f9fc850b63
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-4edd-79a6-abd4-3a5b7017768a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-4ee4-722c-a946-bd569d7cf417
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-4eec-77f3-bbe6-bee061517a59
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-4ef2-787d-89c3-3d1e0c319b19
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-4ef9-7b55-9167-389f845a7a75
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-4eff-726b-8a37-63ff074a34c7

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-6050-74ed-bead-4daaad1970f8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-6054-7f7d-990d-43b7db41f3e6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-605d-7ffa-a8ef-f0cbd3ef8e32
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-6063-750b-afc9-b494ed484961
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-6069-7af9-b192-96dae73317d4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-606f-71ab-8184-39ff01ab3374
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-6074-738c-ac51-b80ac2a8b16f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-607c-7e8e-8346-37a784c163c9

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-738a-7d6a-9362-892f0a4216dc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-7390-71d1-bd53-54ce09fa5252
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-7398-7124-ae19-22d6a9328778
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-739f-7e20-829a-0cda08558207
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-73a5-7535-886d-17ee56c175fc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-73ab-77cb-a7b1-ebde2660ca83
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-73b1-7348-a2e4-73ae5d4e3caf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-73b8-766b-8e51-61e8d69a2935

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-8ba2-7c3d-832f-ab5b138f3e03
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-8ba6-758b-872c-0abec1c32ec1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-8bac-709c-8e16-f1d74d8093b4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-8bb2-7b5d-be48-2224b5f851c8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-8bb8-7b09-980f-0a9b992d443b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-8bbe-7033-9377-8510d2b1f279
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-8bc5-7c88-bbf9-6b00c6b7a0cf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-8bcb-7033-8018-7a560de43a1d

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-97c7-7fa9-8c95-a6d92da14c71
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-97ca-7cc4-be9e-863b32420efe
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-97d4-7670-8ef5-844518a59308
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-97da-7599-9dd9-cc9a18d64fa7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-97e0-7891-9d84-c36b18eff816
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-97e6-7ff8-84a8-5a018b3ae239
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-97ec-7945-8b43-01a8fa43ff38
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-97f3-7d90-b174-574fa14dd774

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-a73a-7c01-8b35-ccd906e5fd67
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-a73e-7326-a054-19cd636b4bdd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-a745-7b18-9c7b-fce8982eaa23
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-a74b-75ed-9211-d9c918fe222c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-a751-775b-b00a-5bb18d8c5f94
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-a757-7c97-8040-11b32dcdb582
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-a75e-7721-9ae1-00f57ab14d31
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-a764-7770-8ac6-11a4d4ddfb80

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-b85c-7f27-8e4f-e35991a383f9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-b860-77c4-b665-79825418f37f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-b867-7772-940f-bed97ec5f6f6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-b86e-70cb-8a99-da96b7df55d5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-b874-72a5-90c2-2580cf4a822d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-b87b-746d-bd8e-296ba5abd2ed
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-b881-7a8c-8338-6326325f28ed
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-b888-7b5b-967d-db32b30753f5

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-c8f1-7802-8be4-7f3ded8c8b80
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-c8f7-7b8e-beaf-055c9a7493d5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-c8ff-7056-84c3-a412f3b9f1e0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-c904-7bff-b2d4-707a975d6bc9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-c90a-7d6d-bc3c-4eb517815182
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-c90f-73e6-b800-a430deec597c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-c918-7d11-80bd-c4236855b47a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-c91e-7492-8569-2924f0342ae9

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-dfe3-7d50-a0d6-2150170c7d80
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-dfe9-7faf-b5c6-15d554819122
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-dfee-721d-ba3e-71580ba2ccbe
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-dff5-7323-a5fd-cb3193cf50d2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-dffc-7ee4-bdc1-ad181c6a15aa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-e002-774b-b038-e53be0e8e38b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-e009-7399-8312-d6f18c9273a8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-e00d-77bf-af58-6ed479e884b5

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-f43b-7ea8-9dd1-39f0fafea5a9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-f440-7474-af9c-7df3f49682a5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-f447-7bca-a9f4-369d70195964
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-f44e-7dd5-b189-def0c747e412
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-f454-7e7a-a8e6-8ba4bcc3dd98
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-f45a-77c6-a03f-31a5c7b79501
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-f460-7db6-9d49-e63df34bb5f9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f1-f467-7d21-be9f-25bfcb7c1a52

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f2-0be6-7f2e-8abe-2b25ea36d8e9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f2-0beb-7b33-94c0-9c8cba8c6799
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f2-0bf0-7294-8dc1-3d33b164d4f0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f2-0bf5-7ce5-9b21-e383a941c5b9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f2-0bfc-7e49-95f1-d72ffcc96ba9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f2-0c03-7adb-9598-f31d56c6afe3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f2-0c09-734f-9e8e-1a70e7959762
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f2-0c0f-7697-873f-979c526680e5

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f2-31ee-729d-a99a-1de1ba7aea15
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f2-31f3-72ae-8381-21bb8bd69f9f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f2-31fa-76b9-84c1-a724abd7ddb1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f2-31ff-7303-af7e-fdc0366856b1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f2-3206-78a5-baa3-76ce85f5e7b0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f2-320e-747e-8032-951b032dbc1b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f2-3213-7ae1-9259-27757bd859db
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f2-3219-7ae2-a67d-b67090f1a389

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f2-4a2c-7270-a0bf-a800d78393d9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f2-4a31-7244-9bb5-cd6ad3cc27d8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f2-4a37-76d3-8fde-a12b4b40dac6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f2-4a3c-777c-8156-c427b7a27fe9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f2-4a43-7a3b-8370-d48b5c513e74
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f2-4a4a-7f6b-aeff-2338925f85ee
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f2-4a50-7a19-9a89-d9b6d7776879
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f2-4a55-7627-ac66-897acca7b191

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f2-6562-7706-8f6b-e57115a9c893
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f2-6567-7601-ac36-3e8ed71d5270
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f2-656e-7c26-9107-546752ff8242
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f2-6573-71b2-b717-701265fc20e5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f2-6579-7cbf-9dc7-35436b23b66a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f2-6580-7314-b584-fc261baab21c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f2-6587-74d8-a1a3-83a5e9f6bb4c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f2-6590-73c3-b4f7-4b32c80c1aad

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f2-7798-7194-97b9-29d0d3edb052
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f2-779e-71f0-bab9-20011e29a2b1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f2-77a5-7b98-bc41-a88c00e19a1e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f2-77ab-7373-adfc-75b03a51d6fa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f2-77b1-7fb4-9338-c9126474aeeb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f2-77b7-7752-a772-5cd53257c20d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f2-77bd-7c71-adb3-0de119fff3b7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f2-77c5-7446-a719-dbe853bdb495

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f2-9b99-7e84-8fef-657b621676fa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f2-9b9e-70a0-aabb-f8c6e5d558f6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f2-9ba6-7cc1-90c4-75422db08d32
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f2-9bad-7d59-9b63-ffaa229a5145
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f2-9bb9-7508-ad88-615b64c392fc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f2-9bc0-7569-b1b4-3dd6a58f2a8e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f2-9bc7-793d-8df7-ad517a429ea3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f2-9bcc-79c8-a04f-49f5b1e297ad

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f2-b380-7b9c-a744-6b202f346d2a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f2-b383-78d4-b2e1-151478a1d050
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f2-b38c-746a-8768-5dc39dc1acae
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f2-b394-7086-9978-b27e0c5bad4c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f2-b39b-7070-8390-fdd90c5d4fa0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f2-b3a2-77a7-ac10-e075a81f59f8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f2-b3aa-7519-be54-ed82190e63e7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f2-b3b3-79c4-a45c-129537417847

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f2-cbd3-7fdc-9403-18aa29e44a46
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f2-cbd6-7861-bbe4-d1e7f3b252bd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f2-cbdd-7ae9-801a-2f1ed9b13d55
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f2-cbe5-7307-a6f0-ea452935a93e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f2-cbec-751e-b1e8-6aabafda99d6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f2-cbf3-7480-8022-56f538f50ca5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f2-cbfa-7b35-8df6-debb41748658
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f2-cc00-722f-b8d2-b159dc5097b0

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f2-e62e-705b-ab57-e920c1a42736
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f2-e632-7f25-9006-e0a59e8d281c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f2-e639-79e7-9179-39c1715445ee
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f2-e63f-705f-b540-d809f5d082ae
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f2-e644-7e22-b22b-bb916260cb24
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f2-e64b-7763-ac85-6381b8d5d433
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f2-e652-753d-9f05-f980cf40ac3b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f2-e659-7b89-a285-10d5efd564fb

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f3-0497-7ea6-9041-a428a76a5f7b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f3-049c-7fde-8727-586aadfa1549
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f3-04a1-7e15-92f9-a1a674e59add
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f3-04a5-797f-8113-5eff32b4598d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f3-04ac-7a5a-819b-9c629e8369e5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f3-04b3-786b-802e-e91c8c5492af
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f3-04ba-7d7b-8fc1-b390a5e8a341
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f3-04c1-7c4b-a069-c3f8a6b68d4e

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f3-1ec3-7329-99f4-501705ffe8e3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f3-1ec6-7247-8c00-3c7735c22693
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f3-1ece-7466-a66e-b145a4692010
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f3-1ed6-703a-acd8-a86fcd2f54c7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f3-1edd-7cde-a9ab-ce0ac67cfad8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f3-1ee3-7203-a69d-335222f5170f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f3-1eeb-7b22-b66b-fc5d59a79e36
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f3-1ef1-7cd5-a940-bcdb56acf920

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f3-41b1-74a7-a5ac-c9fe507ef626
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f3-41b7-7e58-80fb-97695d9b4f00
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f3-41bc-7728-87f9-1d48ad3b62fd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f3-41c7-74a5-a45d-c088c60ef153
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f3-41d0-775f-9f8e-b3e1f09f44fc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f3-41d8-7975-9d8e-e24b351233b7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f3-41e3-789c-b6c3-8e7d28653e58
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f3-41eb-7ee4-90ce-7bbd32f8e532

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f3-6256-7c4f-b1fc-0770d43a6b84
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f3-625d-7fef-9794-4ee2df6c13e5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f3-6266-785c-8d2b-ad006ae8576d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f3-626e-71eb-bad4-d9865c2bc065
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f3-6276-7381-bb6a-006b153901c2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f3-627d-709d-849d-218919dc336e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f3-628a-7653-904e-ee5f240ee05e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f3-6291-7518-ab93-e30fbfae10ee

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f3-6c8c-7a94-bb24-900898c05a2a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f3-6c90-7e2f-9522-4bf84d7852a2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f3-6c98-7a64-85b2-7f3984c231d8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f3-6c9e-7eb9-b647-f5b964afa683
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f3-6ca3-7fee-8a97-74431e174b27
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f3-6cac-7fbf-b9bc-a11877ded374
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f3-6cb2-7dfc-96be-7e9ca5745a83
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f3-6cb8-785e-b128-5ab7239f856b

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f3-83ff-7fa0-a9f5-138d254c1a7b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f3-8404-76f7-ab45-b96e823114d5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f3-840b-75ef-a044-71e00584754d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f3-8413-77cd-be71-701c2faa0fd8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f3-841b-7062-99aa-c434eb62a7aa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f3-8420-7ad5-9fde-e5ad0b342e92
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f3-8427-7eab-84ea-00b25badde08
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f3-842e-7465-af33-41ba1fccdcff

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f3-9c40-7b9e-8065-144e56e5b0cc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f3-9c44-7c91-a121-e94453616a53
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f3-9c4b-788d-a7d4-103161da1f56
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f3-9c51-730a-84ca-15eda4dac417
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f3-9c57-7dae-801b-2a444e5b1c01
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f3-9c5d-7687-93b4-3b6613c3ad71
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f3-9c63-7504-a148-e2d2ee73e84c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f3-9c68-7d8e-81f6-4e18034c5162

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f3-b281-7d6c-bd3b-644dcf54198c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f3-b285-7203-a2e8-8ab094850160
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f3-b28d-792e-a6e4-8459dedc80dd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f3-b295-7e8a-a3a3-7504f8a1da5d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f3-b29b-700f-8ae0-0f597c117a39
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f3-b2a1-77ef-9a77-563fe6f63718
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f3-b2a7-7e16-a4c6-62e8648e5f55
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f3-b2ac-73ea-a53c-020d52320e5b

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f3-c520-7e19-8d4f-9864beeddb30
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f3-c523-71fc-986f-1eb5bd4cd500
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f3-c52a-7322-9733-e4b1f7a54511
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f3-c532-7ce5-81c0-0e0d92b904d1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f3-c538-7ccb-a8af-06786a4e38cc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f3-c540-7eef-ba2f-7119b72e6e0f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f3-c546-7ba5-a602-19be7280d1c4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f3-c54b-7108-9181-163932bc424c

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f3-d9da-7169-b319-4098b29616e9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f3-d9e2-7f76-b690-25e57e0da167
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f3-d9e7-7a2f-86a0-daf97bf86474
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f3-d9ee-7196-aa64-c21fd9ff2ece
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f3-d9f6-745f-be53-7705332f0098
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f3-d9fd-77ef-8b18-aa91e26aa8c5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f3-da05-7cfc-8ce6-c68d1047972e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f3-da0a-713d-a44d-96ade4cbd09b

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f3-e424-7301-a979-84fb5659ea1e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f3-e429-74f4-837f-199ddc180714
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f3-e430-78fc-b6f5-29c4339992ff
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f3-e437-7d45-9246-52866297c193
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f3-e43d-7ffc-88dd-576337c01228
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f3-e444-7f3f-a676-5837821e4bc9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f3-e44a-75ea-b685-53c10d9249f5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f3-e452-7cf8-a38f-816fa6189ba2

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f3-f971-7684-8a40-8e6a8053541e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f3-f975-7c73-9658-58160edef37d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f3-f97d-7a98-b5fb-79d70b33d501
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f3-f984-722e-b635-fbb19f2120b0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f3-f98b-76d8-a12c-646e9abd7a32
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f3-f991-7b3b-972a-e849441ea1ea
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f3-f998-7313-b040-a5d7e9fb79ff
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f3-f9a0-7f33-9767-da168029b601

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f4-113e-7d7e-8c0a-fcf9481b4095
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f4-1144-7347-8337-7df3d77d6bd6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f4-114a-76ad-a38b-b437572d5377
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f4-1153-7a93-a159-c3f4e5528e4f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f4-1159-713d-b466-7ae93136fa3b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f4-1160-7636-86b7-c13560d81322
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f4-1166-7e93-a3b2-422884a125fb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f4-116d-7d4b-b3c9-05dd81b51e68

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f4-30e0-7a9e-ad44-f8786d732294
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f4-30e5-7569-a704-68799e0c5a43
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f4-30eb-71d7-9d82-10378571bef4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f4-30f3-755c-89e4-cb66510d98c3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f4-30f9-7f02-9623-da51525ce8b0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f4-3100-78b5-9ece-12405129d961
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f4-3109-74b8-9950-db368e45a993
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f4-3110-774d-971f-20376ca6691d

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f4-52f0-73bb-8b13-6ea3310154d6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f4-52f6-73aa-896e-b9ad6a739f12
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f4-52fd-73a8-b632-1dd9ab52169a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f4-5304-7d78-9883-41088cb14015
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f4-530a-7359-b24f-c704a0ac1660
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f4-5314-7b2a-9d47-a6488689ceed
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f4-531b-7b74-afe5-4d3f21333096
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f4-5322-7f3b-b9cd-2d22b9bb3bc1

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f4-6470-7711-8fc9-a5247e9661c0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f4-6474-7b7a-971c-59e6580b5c6a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f4-647b-7176-9c56-ff6b5a576765
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f4-648a-7e50-8132-d575b4b1e249
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f4-6491-728e-92df-d22de75dbe12
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f4-6497-74d4-bef4-f9cf8011aa8a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f4-649e-74ae-8b12-1b628d28e08f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f4-64a7-7ae7-ae39-2f0b653c33e9

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f4-7c99-7467-9a69-ddc288b36305
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f4-7c9f-77a1-b6a2-d5f1b812edc0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f4-7ca4-765d-85b7-bb8afdb67b07
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f4-7caa-7ac5-8e5d-96e2617b17f8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f4-7cb0-7a92-a1f1-62f141f51d98
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f4-7cb7-7999-ab88-463b9a9ceaa9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f4-7cbf-7dbc-9fd2-a2d0f9dd4cb3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f4-7cc7-7e0c-bb11-0d8087c35c4e

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f4-979d-7688-ade8-aab1c59b116a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f4-97a0-7f10-8886-2814c39e9695
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f4-97a7-72a1-a547-2f07bdcfacc7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f4-97ae-769f-9f26-0803e473ce54
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f4-97b5-7c3c-b0d2-ca7e8ebd32cb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f4-97bc-7224-a0e1-24ff857503e7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f4-97c4-7007-a627-9b56b60c63d0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f4-97ca-7a6b-8dc0-81245545e0a1

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f4-b064-7f24-a902-52055d8740d2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f4-b069-7de4-b8b0-bb1ca5791fdf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f4-b070-7b85-a4d2-41c83dcf6ead
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f4-b077-7af7-b506-195f40488203
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f4-b07d-7d70-918a-3091b595f7b0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f4-b084-7a50-a4a7-3c3aa94c48ac
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f4-b08b-7092-806e-45e0a23ce3cf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f4-b093-7220-8112-1324b7bdaa6b

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f4-d052-79b1-8351-0dccb8049f64
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f4-d056-7917-aec1-a317b7b149db
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f4-d05d-758d-a793-b74825869e2f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f4-d064-7e33-90fa-cb55e0c57c11
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f4-d06b-75b4-9862-e3582c94a16c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f4-d072-7ebb-b2b3-699b5b0d2442
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f4-d079-730f-9377-4d1e55509c15
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f4-d07f-7e68-9c2f-0b7887f6ae59

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f4-de05-7910-961d-230b44a2f6d9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f4-de09-785e-98f7-db451e551393
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f4-de13-7559-bf29-72d86d7792db
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f4-de1a-728f-b19d-358cf3b1fabc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f4-de22-7288-b147-566a4b1ff361
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f4-de29-75a5-be81-f30e411d5613
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f4-de2f-7f0d-8323-6f4fed6bd060
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f4-de37-790f-bd71-6c0f3a478767

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f4-f109-74f4-97ee-d26cfebb85cd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f4-f111-7ac7-92ec-d947fd988e1d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f4-f11a-7746-9492-90a9e93aaea0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f4-f121-7ee1-afc4-fe62da1d5428
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f4-f128-7a29-ba2e-c6395caf2a9e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f4-f12e-71df-a390-f200af502b2f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f4-f134-7a75-b6d9-ef67ef822c58
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f4-f13d-7a0a-ae07-5d2884d0be60

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f5-0249-711a-819f-413a7574236b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f5-024e-7b7a-b120-95ac2d2b2288
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f5-0257-7eb6-ad0b-3b790e411ab0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f5-025f-703f-99f5-f5f210ff6e6f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f5-0264-73ae-a5e6-e9d4f495bfdc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f5-026b-7a54-bed0-c32eb0847ce6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f5-0272-7706-8197-16deebb440cb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f5-0279-7ee9-9d5c-900aae8a1dbf

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f5-256c-7352-ad26-4d1c7dc7bdde
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f5-2572-7bcd-a7e6-488937c12cd4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f5-2579-763d-bb5f-0da5e2d60896
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f5-257f-74e3-9594-6f13539965e1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f5-2587-7669-a4cd-7869ebb6d41e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f5-258e-7121-bc1a-691068a187da
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f5-2596-7301-b71c-3597fa778cae
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f5-259e-7bb9-907d-a11e5206f8b8

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f5-4dd9-7c1a-ad7e-1294fee54f43
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f5-4dde-7f8c-95b6-8404972f4428
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f5-4de6-7502-b886-8dcad439d23e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f5-4dec-7bab-93d7-aac845774e0e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f5-4df3-7d54-8bfe-5e119cedc3af
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f5-4dfa-7f3e-b213-808482d9b573
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f5-46f4-77bc-81ed-a679a3ca535b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f5-46fc-7043-bf8b-458841f2fcb2

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f5-5beb-7530-b1f2-ddade8658035
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f5-5bf2-7ae8-bf88-9ed09cd42b45
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f5-5bf9-74fd-8803-6054d7c2ab60
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f5-5c00-73eb-a03a-49d377e3f81e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f5-5c07-7fe7-bdf4-967d6bd6fb14
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f5-5c0e-7a1f-bcc0-e2c508db9a83
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f5-5c15-764b-b371-4ac2b02032bb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f5-5c1c-7e43-ac12-2170f9473453

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f5-7443-7872-8df1-16cab7b25de0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f5-7449-7590-b083-410c153a869f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f5-744f-71d9-bbb3-6e502bf5a01e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f5-7457-781b-a907-9944180ecd3d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f5-745d-7996-9965-fafb1e6ae5e0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f5-7466-76fe-869f-4c0163b0052d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f5-746f-7f84-ade4-d9dadfe19180
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f5-747a-7b68-b11f-c2c4ffbbb3a8

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f5-8f74-7724-993a-71b1a8cc260c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f5-8f77-7938-971f-fef06f055823
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f5-8f7f-73c3-816f-1200ec0a8695
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f5-8f86-76a4-a5c4-2edb9e2c7050
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f5-8f8d-7332-819d-1eaddf90dcf9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f5-8f95-76c8-9d9b-ba78c9495896
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f5-8f9b-7e69-986f-07cbc4b2c2c1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f5-8fa2-78f4-b054-90293827c39d

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f5-a71c-7262-b5f8-9e89c9fbeff9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f5-a720-7ebc-a7dd-e3b0f044dc8e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f5-a729-7e2d-a8f0-1568cb22e5d9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f5-a72f-7e95-a37b-6f44b657c5e1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f5-a737-755b-916a-f65cf9769e73
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f5-a73d-7f2c-b4f5-d196d1fa2bd6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f5-a743-77ee-ad4d-d7c7da0fcd89
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f5-a749-7f43-80c7-75a9e0997192

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f5-ca7b-7eea-98d2-a9418f3205d7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f5-ca80-752f-90c1-b251a3b80ee2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f5-ca86-7e24-997a-2b1357838431
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f5-ca8c-729f-9db1-96d392a07ce6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f5-ca93-7275-a38b-90da80489010
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f5-ca9a-758e-916c-81251e793c5f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f5-caa2-7657-9bc8-a685692f87b4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f5-caab-7406-9b9e-8d8a5d5c5cf9

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f5-dd7d-7775-81f3-600524f483a1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f5-dd82-74c2-8a0d-76a93796c862
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f5-dd8a-7190-8d6f-8a92687dea88
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f5-dd94-7f42-af9a-46ea325b986d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f5-dd99-7d01-82cb-cecd83fb9514
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f5-dda0-7258-9b92-9a701f6cc127
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f5-dda9-7172-a2ee-e06c72c7429c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f5-ddaf-76b8-b9ab-9de5dbce4d08

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f5-fa99-7472-87f7-92675803c680
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f5-fa9e-72e0-a7bc-236008d06f0d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f5-faa4-73d0-9748-ac1256551a5c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f5-faab-756e-8590-6a61c999ea0b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f5-fab2-75f0-bf84-5544e34757cb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f5-fab8-7f75-bae8-307591efb8d1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f5-fabf-76c3-be5c-eaf4acd57b56
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f5-fac5-7c9e-b125-162268c5cbc3

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f6-1183-7f45-83af-4248076d5342
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f6-1188-79d8-bb0f-799c439eea0b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f6-1191-78ca-a7aa-af44459eafa3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f6-1197-7302-a4db-6012dc912fbc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f6-119e-7aa1-b4b1-609202ad87a8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f6-11a5-7c26-9711-335adfa262fa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f6-11ae-7034-9ae6-9daeca34081d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f6-11b2-7d15-81f2-e9ca39e5dee8

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f6-2367-73b1-b20f-4be472053342
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f6-236b-7ba7-a963-226c8c9ed04a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f6-2372-7448-a232-8a9e4b75a175
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f6-2379-7e9e-9e98-ebffa2041c7c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f6-237f-7ae2-95ad-335c09b38fed
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f6-2386-790a-a97a-b18332b003f2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f6-238c-7f50-b3bb-da53f1c13255
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f6-2392-7fd9-84e6-e84aef85fc7e

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f6-383f-7e61-a967-198b866be17d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f6-3842-74cd-bc38-1a8c4461cc16
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f6-384a-727d-a3c6-d45a79237267
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f6-3850-7f57-be21-f15c1eb2ae03
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f6-3857-755c-b1b1-8d8a41f88623
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f6-385f-7340-8dfa-47c0e1674cb6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f6-3867-74f8-a007-6a5c9a3e1832
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f6-386e-755a-b430-eb8e91a02969

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f6-51ce-7a35-accb-e8971dda4f80
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f6-51d3-759b-884a-2e060ad6e6ce
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f6-51da-755f-82ee-f9d2e20dc3c4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f6-51df-79a7-8935-529119b6ce20
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f6-51e6-703b-bbe8-533dcd2b5a20
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f6-51ee-74c5-9018-6f3560492495
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f6-51f4-7d0d-8d2c-008495feb394
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f6-51fa-7d32-9230-5646fd3f31b0

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f6-64d2-73e0-a3de-adedbbbdb251
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f6-64d6-7c0b-9e11-f202d0ac7f2c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f6-64de-7cca-8f53-28395e1b14fa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f6-64e4-7b3d-a59a-51af68032ec6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f6-64e9-7de0-a740-a0188af2f22f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f6-64f4-73e4-abe0-9a0409ce5cbf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f6-64f7-75b7-9c12-54ea4ce3d447
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f6-64fd-7c2a-a67c-4e49bb30d966

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f6-8160-77eb-882b-53945036eff4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f6-8165-7d03-8d17-8333ea552de2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f6-816c-7bd3-9001-0d904f885971
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f6-8176-7694-bb8e-f0bdb155fcb1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f6-817e-7472-9ebf-6b1adc03e83d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f6-8187-73e9-a2f4-4f4adebfeff3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f6-818f-7f58-bee4-6ddb831f3156
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f6-8197-7c02-b2b3-d41ce277d696

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f6-9dbe-75e2-aa0a-d46b90e833f0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f6-9dc3-7420-a453-de8bd21d9e45
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f6-9dca-73a4-843f-72a4e8b72c79
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f6-9dcf-73fe-b9df-7a486476d8ea
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f6-9dd5-70fb-b428-a74963ea0399
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f6-9ddb-7bb8-a76b-34d11e29765b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f6-9de2-710b-aee4-10c3dc09d223
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f6-9de8-7198-81de-a9cb0176a25e

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f6-ad8c-7245-8ce8-3a834904303e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f6-ad91-72e9-8bc5-b6229e4e639e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f6-ad99-7b58-861e-95a8f1162158
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f6-ada1-7299-8e3e-2c3a0d6ef1c7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f6-ada8-745f-8604-176197317e2d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f6-adaf-7052-9194-876afaf013ad
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f6-adb6-762b-a393-b46eafbc6155
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f6-adbe-7331-8138-9a10b860bad4

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f6-c80a-7e75-a5fb-8d14517da3ff
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f6-c80e-7236-9578-96b4da1dd0d6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f6-c815-7b93-8f6e-40b87a10225f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f6-c81a-7188-b81c-cc506814ee83
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f6-c820-7802-b5d5-9dce54d2cec2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f6-c827-7eaa-9be2-ac0fb76f2c54
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f6-c82e-7090-9eec-913ca81d4a0b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f6-c833-7a1d-8aae-d9a94d01c98a

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f6-e6cd-7e31-bc7e-462d200fab82
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f6-e6d0-78a1-ae24-d2a0c357b249
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f6-e6d6-7538-9192-7b94aeb462dc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f6-e6dc-7d54-86ce-783b57b8b3d3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f6-e6e3-7905-bc06-4e892259dc1c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f6-e6e8-766b-8c31-b06fa8e9cd3a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f6-e6ef-7001-80dd-9fccc2f9ec35
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f6-e6f3-77b7-bbb9-b7c508d25e8a

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f6-feec-7ca7-8c7f-dcdc49dbe559
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f6-fef0-78c8-9e50-29c18140e36a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f6-fef5-7b10-bdce-0db6a101e49e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f6-fefa-7bdb-817a-81331585151b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f6-feff-79ea-8ad6-0ad35fe58825
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f6-ff07-7ca2-b06e-422680809806
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f6-ff0d-7d7d-8fd2-626dc9a597c6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f6-ff12-7e22-8f9d-c51e2a76fed5

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f7-1900-7347-a4cc-5f9e88b18b00
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f7-1904-75c7-bad8-7105a24495f7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f7-190c-7a51-b167-e20f72b55ec4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f7-1913-700e-86ab-7b1abcfc1750
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f7-191a-7122-a73c-14c23dd20032
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f7-1924-7c56-b26d-dcaf8af980cc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f7-192b-7277-894d-178bee583531
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f7-1931-77ef-8a89-d27212af21ca

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f7-2bdc-7be7-8a36-1fe3a855368c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f7-2be0-70bf-9577-b6f0ea9c9088
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f7-2bea-707c-9530-e5b269905f4d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f7-2bf1-7636-9f6e-5d07f835afe3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f7-2bfa-7fe3-b10d-fb7cfa6f71b5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f7-2c01-7d35-9263-1c9f765205a5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f7-2c09-78c7-8f2f-9ffb78f50189
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f7-2c11-73c1-9579-bc062add50e3

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f7-4c89-7da0-b834-4b7915f2fd15
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f7-4c8c-7801-9b12-f9cd5979f32d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f7-4c93-798f-a49d-ae43fe35029c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f7-4c9a-77c0-91dd-b75f837eb12d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f7-4ca1-742a-a077-2c0a7ff7240b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f7-4caa-7429-b8d2-02dc20aa422c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f7-4cb2-7ff0-b1cf-7bfddc9c0285
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f7-4cb7-710e-9285-1e00f588d2e9

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f7-67ad-72e9-b126-24abc25b9c52
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f7-67b2-7a29-866e-607c6f8013e5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f7-67b9-791c-8f41-1a9e1ac26806
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f7-67be-7b4d-86fb-fcdc8add5204
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f7-67c5-7ee0-bcae-dd4f60d93528
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f7-67cd-788b-82e0-15a04208c36a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f7-67d3-7f74-995b-d77b33db4954
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f7-67d9-7b12-83f7-35aaf253b475

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f7-7f9e-74c8-b614-c454c278b7cb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f7-7fa3-7868-afd4-fedbe1a64b37
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f7-7faf-7223-959e-7502345e61d6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f7-7fb7-7e79-a93b-0d81e713fb25
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f7-7fbe-7c33-b537-c4383459f5c5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f7-7fc5-7567-b2e7-e1bd471602e0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f7-7fca-748a-aefc-a6da52532c63
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f7-7fd3-7de8-afb7-0d5814a5075d

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f7-94d7-7bfc-90b6-14a834fac42e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f7-94dd-7c98-9a7e-a716dd931bdb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f7-94e5-77a8-8b37-f89b56cab054
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f7-94ee-7e03-9844-044026924bb1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f7-94f8-7225-93b6-e10c7e10fe1c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f7-9502-7187-94df-e7402bc49646
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f7-950c-74ba-ba52-d762fe2119d7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f7-9515-718f-85c8-ccddb9fbed9c

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f7-a587-766f-a2ba-851252163e95
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f7-a58d-76c5-a058-71da1ee45987
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f7-a594-7fad-a53e-ba09432d32a7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f7-a59c-7c56-b433-109e3ffd0b92
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f7-a5a4-7fe1-b918-48e34689b7f8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f7-a5ac-7124-8b16-1ed6566997bd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f7-a5b3-7451-a9c8-a136b21cb715
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f7-a5bf-7e6c-a354-565696547a2a

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f7-c5b0-75e4-8804-5f88df958e3f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f7-c5b6-7bbb-82fb-4a33f74a4156
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f7-c5bc-79c7-a2dc-06331b93b2a8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f7-c5c2-7692-9176-03ee3a5c5541
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f7-c5c9-70ad-9457-47de0e9bc61c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f7-c5d2-789f-ab58-5c6646c7510d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f7-c5d9-7db4-b5e4-ab5136e40176
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f7-c5e1-73c1-ae6f-7152a7fc39ce

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f7-eb0f-775d-b2e5-b2727ce341a9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f7-eb12-7c30-b162-1925e2a752ee
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f7-eb19-7647-98cb-a22a04bb7b1c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f7-eb2a-7d71-a751-2ea52311fd8e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f7-eb2f-7541-9d4f-04066acd10cf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f7-eb36-73f9-97c9-ca7f1d5b419d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f7-eb3d-7438-8695-310e8d729d53
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f7-eb44-7229-84f4-117c976572e6

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f8-0054-7064-875b-c6dd44046191
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f8-005a-7e5b-9028-d1c028f655c9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f8-0063-7607-9f57-7222affde5bd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f8-006a-7924-8c50-d16f6e3cfc21
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f8-0070-7c4a-952f-7f25d0289812
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f8-0077-703f-bf44-465b4142a044
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f8-007f-74b1-8acc-c977a8fb1a7e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f8-0086-7d6c-95db-342d09ba38b7

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f8-24a2-7238-8635-f96c6553e2a0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f8-24a6-7788-8732-6cfd1c573cf2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f8-24ae-71d1-940b-1df8867504c0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f8-24b5-7c5a-a8c5-a244a686f46f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f8-24bc-759c-a73a-d59f6fc0fbbe
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f8-24c3-7f08-ac81-1fb0b00eeaa7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f8-24ca-75c4-8e4f-13fd8f346efa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f8-24d2-765f-8066-42538f737062

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f8-3aea-73fe-935a-7cdffbc809a1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f8-3aef-7634-bf0f-1c14aa4baaf1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f8-3af8-7b1e-a51a-d38f20675aa5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f8-3b00-73fe-b8b5-e5f98819eeb4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f8-3b09-7124-a6ac-9916f2bdd87e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f8-3b0e-7b31-9830-2cbf73c2877c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f8-3b13-7dc6-a62d-ed41b5c53b7b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f8-3b1b-76e6-a85d-bdb19d996a1b

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f8-54d9-7c9e-9e1f-2f86805d747a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f8-54dd-7f96-ae09-0ee1b20c508f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f8-54e6-7a37-ab7b-5de11157fc12
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f8-54ed-7189-9a69-3eeaa4e0fc12
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f8-54f3-75e1-8e62-3793e67fbd37
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f8-54f7-7d01-bd60-5b65b154cb9c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f8-5500-7778-98f9-5bcb35aedea8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f8-5505-787c-aa36-f4be18a2d59d

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f8-6a01-7f0d-95d4-249ab4b6cd0a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f8-6a06-7d30-84bf-0eb15edc2fe1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f8-6a0f-7aed-acd1-716fb5951404
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f8-6a15-7c85-82f1-68551208c074
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f8-6a1c-72e4-9789-a6cbc12535a2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f8-6a23-78d0-8e58-fa134f964208
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f8-6a2c-7462-8f33-156eba4d1931
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f8-6a36-781b-bcb6-ecc5b79495f2

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f8-8e52-722b-9591-05fe777872d2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f8-8e56-79fd-84a3-f4b09e52425d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f8-8e5c-7078-aa0b-d0aebf59305e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f8-8e65-727b-b695-155f9005642d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f8-8e6b-7ece-90c3-136a4c5f7356
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f8-8e72-7b22-9c26-2122c28d8a83
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f8-8e7a-7598-a54a-dba02dcb0286
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f8-8e80-7373-aa6d-eef08d265ca2

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f8-a089-7feb-8ce3-6f5f39686900
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f8-a08f-7f91-bffb-7396c191b951
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f8-a094-7138-9328-dcad3de25d04
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f8-a09d-78bb-bfbd-2cc8a799341c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f8-a0a3-7e97-aafb-922486597330
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f8-a0a9-7ed1-bd8c-f4202caa0e7c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f8-a0af-7d21-a731-17b555be67cd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f8-a0b6-7c28-8afb-dd153e132fa6

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f8-bbf3-7275-b6be-61b4c187c000
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f8-bbf7-7281-b9bd-e8decc103a36
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f8-bc00-74d7-b23f-d7f851d54b1d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f8-bc06-778f-97d9-360d10385dc1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f8-bc0d-790a-99e9-05f50602cd2d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f8-bc12-7e3c-8cdb-9328b2da64e1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f8-bc19-7e8a-bd56-dfbba2c14d8f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f8-bc1f-7e74-ba3b-e9e528d53b80

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f8-dada-7976-9777-842a621a5758
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f8-dadf-7f2f-8925-5d742ddc793c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f8-dae6-7532-800b-37f75f2d614e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f8-daed-749c-9c2a-ffdd70dd3da2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f8-daf2-74e1-aac8-2724869f8c8f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f8-daf9-75ac-ab5a-a83fc7b4f88c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f8-daff-71be-9431-2edbd348d020
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f8-db08-71d4-8cc8-683e4092f69e

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f8-ed95-71ea-b9a7-c0f2c312fbed
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f8-ed9a-7b7b-8369-b0103011851b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f8-eda2-7913-b500-e1753a231d1b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f8-eda7-7588-be9b-b05a418c3746
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f8-edae-7997-9446-fd6758e2c6fe
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f8-edb5-7081-be1b-ddbc2e0b82e4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f8-edbc-7146-a3c0-c6eab251516e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f8-edc4-78e7-928e-aba2cbb28af0

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f9-0f92-7229-b858-fda0c5a3daa9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f9-0f97-7f70-99d1-3d1cca75d363
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f9-0f9e-76ed-8879-afa7c0d641c5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f9-0fa4-7c6a-ad65-aff7c62b5806
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f9-0fab-7d7a-b51a-9673712bd22e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f9-0fb2-7a99-8724-c9c974d3ffb5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f9-0fb7-782e-94a3-617090cfc719
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f9-0fbf-76aa-a447-5b8104f5f3a9

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f9-224d-7cf4-8108-3370b183ddc0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f9-2252-7d42-9993-f237a1e555bf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f9-225c-7328-a8f5-6b40e8e51465
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f9-2263-7879-bc7c-98140ad02d02
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f9-226b-73d8-8c53-5af14a59a166
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f9-2272-7657-b53a-83dff549ee53
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f9-2278-7671-815a-5a8bc4cfb4b4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f9-227f-7a2a-b563-804878d21b26

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f9-3a56-7ae5-b5be-ff053a8dae55
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f9-3a59-70ae-970c-cf46a296cd10
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f9-3a63-7aeb-b480-74e130ec7372
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f9-3a6a-7726-8edc-8a36b974369f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f9-3a70-7737-8ef3-9f11b515101f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f9-3a76-7236-b707-2cd6c305fa1c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f9-3a7f-7f47-9f1c-e7194bdd5205
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f9-3a86-73b0-8cd0-07f55cab9847

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f9-5501-7319-a8d1-1ab56a907ec4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f9-5509-75b2-9863-089e7a25c983
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f9-550d-7999-be6b-ad5ffa731129
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f9-5515-70b0-8912-6b1b59d67438
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f9-551c-737e-b2eb-0f1b612ce2e6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f9-5523-7bfb-8c38-87547cda585e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f9-552b-7259-b054-28a25ac88a7b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f9-5533-7dfd-a447-8931077238d2

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f9-6bb0-7c16-8c55-a98a61fe6e10
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f9-6bb6-7961-968e-89b80f97e980
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f9-6bbe-7f73-a495-cb1398430adc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f9-6bc8-77de-87d0-983953b5b543
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f9-6bcd-749d-8c87-b8bf8c7061da
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f9-6bd4-7ec9-ae2a-f95bae349dcb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f9-6bdb-7310-8df3-0f841db02fc7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f9-6be3-7bf4-a39f-cef5d48331cd

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f9-7654-765d-a4e0-1432bb41cec3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f9-7658-72f7-a602-cc3c1a431206
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f9-7662-77d2-a485-3d54ba8da6da
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f9-7667-7396-b1f4-e4cf456e36a7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f9-766d-7bbf-a4d4-35c90d6473bb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f9-7674-766d-9af3-c4cbe0b973ee
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f9-767b-7d04-a84a-5e12338a15db
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f9-7682-759f-972b-d715f0e4a24b

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f9-8d12-7605-8c3b-2e480754a2da
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f9-8d17-712e-984a-f41221962f9a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f9-8d1e-7629-9132-731e3ec2e9fd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f9-8d24-750f-81d6-1855fe74050b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f9-8d2c-750a-876c-b729e927b800
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f9-8d32-7af5-b292-335434833d9e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f9-8d39-7f66-b63e-7bf26e49b643
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f9-8d40-770c-a40c-3b5cc1e7a4d7

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f9-a7de-774e-85af-460b69184fb6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f9-a7e4-791d-8293-34f52e95d315
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f9-a7eb-7464-9da1-f18d188feb50
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f9-a7f0-72f7-a635-58e20024cae0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f9-a7f7-7c73-b367-89d23c977614
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f9-a7ff-75df-bb69-65b264505a31
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f9-a808-7f07-959a-7f1ba86628d0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f9-a80e-7485-bcea-f0bbeb7deccb

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f9-bce2-7b3f-a7ea-ac2309cc5ff4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f9-bce7-7d4d-aa62-707be2c7e884
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f9-bcef-7181-ade0-9eb38e5fadd9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f9-bcf6-7a28-8c11-71b6da2dc4fd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f9-bcfd-7d4a-9072-46938db4667d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f9-bd03-7cdf-85e7-770ff08cfe00
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f9-bd0b-7df5-be54-94cde07c0cb6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f9-bd13-7fb2-8f05-1cbd3e56d8db

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f9-d1d2-7981-af4a-8228127969c7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f9-d1d6-7866-9bc9-5bf2c5c3f7ce
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f9-d1df-76ca-b17e-8b922b2fc130
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f9-d1e6-7021-8701-faf49faa05e6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f9-d1ee-724d-bac0-3813a912b68e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f9-d1f5-771f-b3d4-8694a2382306
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f9-d1fd-775c-b2a7-a2677e5efbe6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f9-d206-7838-b8a1-56fd152906bc

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f9-f124-7edb-b633-6fb8e9818487
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f9-f128-7090-a936-83718f60790d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f9-f12f-772a-bbf7-76e845ee32d5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f9-f138-7c6a-ba44-1b5d4225d90e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f9-f13d-7a68-a448-1a49a35b9495
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f9-f145-7447-a779-996f9ece4d45
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f9-f14b-7d80-a35b-88231572f8eb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1f9-f152-7080-bbc4-a32da06b71c6

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fa-0988-758e-a38d-39b0e0b015d0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fa-098d-7585-a192-8e88a89e0912
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fa-0992-78cd-ab0f-1826e764f5a9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fa-099a-7881-8fa6-42b0ba79d892
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fa-09a1-7024-9330-99fb980abf8d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fa-09a7-75d2-a5ec-f79fc12b4a03
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fa-09ae-7d7c-a410-5b6d9098188f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fa-09b6-79a2-aac9-a0dc62277ca3

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fa-2b36-736e-8265-5082106cc488
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fa-2b3a-7544-bad1-9da6ae028ecc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fa-2b42-765d-bf68-ec402e4ed23b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fa-2b49-7176-9dbf-3c639c6d625b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fa-2b50-7ef3-b9db-ab1e06e4088e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fa-2b57-73a3-8d39-c59e5cda3ce3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fa-2b60-7156-83b1-1c6d2355dbad
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fa-2b67-7f35-9542-5b1ba24c5052

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fa-5860-7481-9fbb-4b2de92767ce
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fa-5864-75c5-9e27-e7f976813616
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fa-586b-7085-abea-399448d83f5b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fa-5873-7169-82be-82eca5f068aa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fa-5879-79b0-96a3-c4d4dee9afbf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fa-5880-74b4-827a-e9b970bbd9d0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fa-5888-7834-8b5b-5d439841697e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fa-588e-7431-bdca-37bf51c817c8

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fa-6f9b-7924-ad21-2a8c28c33028
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fa-6fa0-7d61-af42-c4bd9854fac2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fa-6fa8-7e7b-804d-a992dfe29afa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fa-6faf-7c56-8e1e-cf4a2c7c3ebc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fa-6fb5-76dd-af87-d691fe8d5eaf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fa-6fbd-79dd-b748-16f25cee784a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fa-6fc4-7337-a209-51673a74f47b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fa-6fcc-7f7b-b0ea-3dabfcd49fe6

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fa-8a19-7984-8f02-d7b4a1bef811
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fa-8a1c-7799-a98c-1c2bf45ad224
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fa-8a24-7783-acf8-1a210da48dc5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fa-8a2a-7761-8604-67dd9065f212
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fa-8a32-7a30-b475-d0a788269140
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fa-8a3a-73dc-80ee-56ac23ea1628
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fa-8a40-7934-8c17-47ac2f58db07
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fa-8a49-7aac-8a9f-8ba804d3ed4c

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fa-a678-7057-8478-5f4c5b82bcf5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fa-a682-778d-8c5b-e7b0e700d5ec
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fa-a687-77fb-ab01-6c35a45f2008
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fa-a68d-793e-9253-ea8f05ff263c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fa-a694-7db5-a3f3-fcf8651c5c0c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fa-a69b-7074-94a7-d65ca79dbfa8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fa-a6a2-719e-bc44-0766fd36cb33
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fa-a6a9-7929-83c5-9abf6dabd78f

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fa-c232-7715-878e-b8b85bcac770
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fa-c237-7e4f-8b00-8f26d7762b6e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fa-c23f-7a74-80c2-5297d8ee0d63
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fa-c246-766b-848c-5ffae28699ae
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fa-c24c-7576-985e-1101697838dd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fa-c253-7e18-b0f5-61d8b105e065
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fa-c25c-72b7-b222-10e7b5699722
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fa-c264-70ea-a9b7-8bbf6fca58ea

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fa-d644-7da7-b038-f2693ab813a2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fa-d64a-7295-9745-7ba21fdd02df
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fa-d652-7c79-9c3b-c92c7a81a5ba
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fa-d659-7940-b195-806550c8945c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fa-d662-76b9-9dd9-bcc99b63222e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fa-d668-78a2-ac9a-fa9a967df062
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fa-d66f-7658-a98b-3030ac4ddbcf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fa-d675-7f6d-bb78-a37580399733

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fa-ee87-7c50-b95d-79beabfa9a90
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fa-ee8c-760f-bc8f-8f5fd05cf205
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fa-ee94-784d-82d2-2883744b5541
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fa-ee9c-726a-a544-85e1634708aa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fa-eea2-70c3-ba43-9bcad0131d58
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fa-eea9-7f30-8526-1c1b07e00abc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fa-eeb0-7bd6-90a9-8269bf22557d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fa-eeb9-72ba-b36f-0020642cbe13

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fb-0689-7eff-9b2c-2b2892ad25e5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fb-068e-792b-ac21-b35adae63f8a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fb-0696-7970-a657-f940b7ba4672
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fb-069c-7dd3-b628-67db69d3b7a2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fb-06a3-7c64-be6c-11cab488e34f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fb-06ab-7d3a-acd2-2a7a5cdd1ccc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fb-06b2-7ed5-ab96-36d309366317
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fb-06ba-7dbd-b9ed-9464c33c5335

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fb-2abb-7851-b882-9cf5126bd7d7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fb-2ac0-7966-8994-3d1402889d76
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fb-2ac6-78cb-a19c-3b76d5da203b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fb-2acd-7e11-8728-35961bf7d6de
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fb-2ad4-726d-95a8-718e08d205ac
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fb-2adb-70a3-ab21-d643ccb2a599
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fb-2ae2-7512-a6d9-af42817f2e2a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fb-2aea-7494-bbaf-333722130289

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fb-43b0-7f3e-a28a-27bb12f58290
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fb-43b7-712a-9a71-f9a440a01382
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fb-43c0-75ae-9fde-f51e4e8d8463
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fb-43c6-772c-88a4-9a64906866c5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fb-43cc-754b-988e-e7c8be137523
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fb-43d2-7bd3-b69c-1ab627c97a4b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fb-43db-7be5-bb81-849c4e5c526b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fb-43e3-79f2-a4de-11563d55a96a

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fb-629f-7b58-880b-e56e05ea412d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fb-62a4-7795-90b6-3a945dda3164
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fb-62ac-7f39-90a0-e70ce8b6d486
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fb-62b2-7043-9309-fb590efaa23a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fb-62bc-775c-9235-1d114a079882
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fb-62c2-7532-8fec-56530ff774db
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fb-62c9-7f09-a6f3-9cf03c52c024
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fb-62d0-747f-bff9-38e30485c5cc

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fb-8da7-7bea-ba9a-f0036fb60fba
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fb-8dae-7102-8652-027f20d09dfc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fb-8db6-7c73-8b1f-b9513493d125
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fb-8dbd-777a-86df-b3affe3bd986
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fb-8dc5-7f8b-8d8b-c6f73a9c1913
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fb-8dcc-72b6-bdae-cff0b7fa3917
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fb-8dd3-720e-8381-e1126d569a0a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fb-8ddc-7bf8-8f86-ca3869722d7d

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fb-a2e7-73a7-8f51-ea953643ce67
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fb-a2ec-7a65-9919-77c7a76cfcec
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fb-a2f4-708e-b7af-8f522c5ac047
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fb-a305-7b3d-a474-76992036fab0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fb-a30a-7f81-8f3d-fe1b0d642847
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fb-a311-7f00-abc1-56e99bad03b3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fb-a317-7b0e-a8b3-482367faa59a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fb-a31f-7bea-a305-e198089f2529

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fb-be5a-750b-b68b-826af3fa7293
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fb-be60-7e7e-8fbb-05d5a92133b0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fb-be66-7715-aa3f-44a88bc79174
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fb-be6d-7850-b24b-cdc783a312b2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fb-be76-7fad-8fb0-63948261f502
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fb-be7d-7d85-97f9-ffb22b95991a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fb-be84-7286-ae8a-aa7b2c5f1707
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fb-be8a-7d3d-b2ad-0937f68576df

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fb-d5a2-7797-a530-2b07cbe32c5e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fb-d5a5-702d-8bd7-738728872143
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fb-d5ab-7e72-8f2a-b8e3da371855
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fb-d5b3-7040-ab6e-d1b9f3123baf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fb-d5b9-7720-aa15-d7e834f4fa78
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fb-d5c1-7b65-b292-4a9b0456790b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fb-d5c7-70da-b3ce-0062a1013f56
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fb-d5ce-7738-9d48-d50fe32e492b

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fb-f4c8-77bd-a236-00d2fca55aa4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fb-f4ce-71a4-ad81-fe3b7fa6565d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fb-f4d6-73a0-8ce1-ec7e216c0bb4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fb-f4dd-76d6-b3eb-734d8fcfbe8a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fb-f4e7-7762-b55b-75bcde22bae2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fb-f4f1-7120-b49b-a376d78ef7a9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fb-f4fa-7b74-ae1a-7e441f97d747
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fb-f503-7ac3-b5bb-c08e382ef220

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fc-19b6-7bc2-ba33-3d770d1be51e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fc-19bc-7309-9a60-0cc462c08291
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fc-19c1-7995-aac6-4557a5e4d912
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fc-19c9-7609-ae49-3bc66e734d70
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fc-19d0-7e8c-ac1c-20f970d2030c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fc-19d6-7b4c-81d4-e76dc5b922f6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fc-19dd-79df-9353-da85ee59f563
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fc-19e4-77e5-97eb-19980cfb4450

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fc-425e-7f51-a8a4-b815ccba96a2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fc-4264-72cf-9912-83e69e5fd5cb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fc-426b-73e4-a9ab-f6be7991e25c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fc-4272-71f4-8aa3-91a4621952b2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fc-4279-77a9-95cb-9a79cf55e54b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fc-427e-7d91-a7ed-b8f839b27eef
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fc-4285-7150-8e61-38aebc46df14
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fc-428b-7f3f-ada4-9bc75227e77b

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fc-538c-77e1-ba8d-abe9cec59484
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fc-5391-7b07-a7f0-3859883d83a6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fc-5398-7eba-b15b-453def8bcb3d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fc-539f-7760-b242-7eb20b538e42
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fc-53a5-7dcf-a944-de43fa1ac1ca
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fc-53ab-799a-b8bd-6fe3722c8c8d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fc-53b1-742d-817d-c430a68fc3fd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fc-53b9-75d3-913b-45dbdb888828

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fc-6a94-7bfd-a183-1c502b96cf9a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fc-6a97-7bd9-9b56-e44e8a5fb554
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fc-6a9e-7069-8492-e1f2af90eef6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fc-6aa5-78af-a054-f0cfb64cac63
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fc-6aac-7ed5-9e2c-8085233df070
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fc-6ab2-7c11-bc3f-68e026aef0fc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fc-6ab9-719a-ab87-5628ed628551
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fc-6ac1-7ede-9b8e-215bfd56ae84

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fc-7e7c-7bd3-a392-eb257fb0c156
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fc-7e80-7ea3-afc9-ec6a5fae4cbc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fc-7e88-7c42-8df0-e131a8067d62
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fc-7e8e-7794-afa2-9a8645a382cf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fc-7e98-7ac3-82a3-719f6a8dbf85
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fc-7e9b-7897-ad78-e591e7e27796
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fc-7ea1-7b12-abad-a77b3bbf9a20
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fc-7ea9-7488-890c-65861120b09f

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fc-9f0c-7e45-b28d-24e3099b1ae0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fc-9f11-73a3-99b4-119e23ef3f12
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fc-9f19-7c97-8a99-31fd4dd2d979
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fc-9f1f-7799-ba52-c8a8bd570b6b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fc-9f24-7d32-8bfe-caf93d474af6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fc-9f29-7392-89ea-411d75bf83c1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fc-9f32-7d5e-ae8c-898657e3c396
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fc-9f38-7729-a615-9c2489613e06

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fc-bd22-777d-9ee3-3c4d208cd6cf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fc-bd28-7d8c-babe-32ea0270ec4a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fc-bd2d-75fd-82b6-6734c97f2902
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fc-bd32-7af7-80a7-310700e763fe
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fc-bd38-7396-b0c1-a82f20809635
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fc-bd41-74c5-8782-a5396134ad84
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fc-bd45-7380-92d8-851ae0a08792
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fc-bd4d-79a5-b89b-ce67768bfcd1

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fc-d4a4-7333-b41a-51dad1d254ae
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fc-d4a8-7ed8-b2f7-2505c3046e00
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fc-d4af-7099-a183-51a607929f3c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fc-d4b5-731f-8848-16e41545d4f8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fc-d4bb-7aef-b46b-f785f3614fb1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fc-d4c0-7fb4-901c-363fd0e04e88
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fc-d4c6-7f07-8d7f-bc8cdd8a3e5a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fc-d4cd-7012-a888-803a66053c44

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fc-ee90-7f48-9216-15077ca7c1ec
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fc-ee94-7fee-8720-083e4130fb36
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fc-ee9b-76cc-93b0-c051961d8255
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fc-eea2-7475-8839-3a6cbad76854
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fc-eea8-7532-8cb9-94040cc8ea02
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fc-eeaf-7dd1-81f2-0e8229403691
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fc-eeb4-73a8-90f3-f682259b31c8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fc-eebc-7584-af73-abf2fa1113d4

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fd-016c-7091-870f-2effdbed6501
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fd-0170-79c9-99a8-a61d9bb63264
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fd-0178-76eb-8aea-dcb9e6be0d6b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fd-017f-7ff0-96a3-6b6d21d69038
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fd-0187-770e-80d2-17502355841e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fd-018c-7ef7-813a-00da84aa27be
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fd-0196-7c44-a2f6-cff4f88aa071
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fd-019b-7a8b-b861-e0611aef28da

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fd-18c6-7366-a1d8-ba0df990602f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fd-18cb-7a34-b18d-45c2007d1e86
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fd-18d2-7f38-bccc-6e660fb4c3d1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fd-18d9-750a-b609-79e5f749fd90
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fd-18e0-790a-a40c-ccd591d3e7fd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fd-18e4-74ad-81e0-1cdaed0d4731
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fd-18eb-7e34-94ad-f640bce0e182
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fd-18f3-7a20-8aaa-6ef87b2290e2

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fd-2f36-7e42-9cf7-b6b95cf926fa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fd-2f3b-72f2-a429-9325c3dc7be4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fd-2f44-72e7-a64b-c2e1dec97b4e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fd-2f4b-747b-b8c3-fd9fbd96a669
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fd-2f51-701a-a721-1e8138efca5d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fd-2f58-7bea-92da-92e2c89622b2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fd-2f5f-7146-8b24-a16880ee3dd2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fd-2f66-709f-a0c7-89e6c06ef21a

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fd-4200-716d-9efa-fdb058437786
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fd-4203-75c7-9b2e-a6488c20d067
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fd-420b-7835-b443-40eaad9b3ea2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fd-4211-7e9f-a4f6-bd8f5e46a85e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fd-4218-7270-9585-7a296c8fd8ea
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fd-421e-7187-b6db-bf346f452763
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fd-4227-7a06-9b45-9d8d8ee54f9a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fd-422e-7480-864c-3c14eac7b078

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fd-57a4-721d-8ea5-b78a19ca343e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fd-57a9-763d-a2f2-b1a9b125f28d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fd-57b0-7c1a-8caa-6aeaf5621010
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fd-57ba-797e-8e1d-c13293eca725
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fd-57bf-74d6-b8a5-705387f3fc4f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fd-57c4-7fc9-8092-c6d719295848
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fd-57cb-7160-8a34-88a49b645a68
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fd-57d2-7a54-a0ff-f5fd7d4d29bb

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fd-7076-7d26-8215-c2ee6373b6cf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fd-707c-7eee-ad7b-86d1e8052c42
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fd-7080-7318-aae9-98a4c8b05bba
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fd-7086-7383-91b7-4157b238f481
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fd-708c-7cbc-9a8d-43090f4fe6e4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fd-7095-7860-89b5-f5bf05eff936
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fd-709b-72eb-b92d-5fbfe14dec4e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fd-70a2-7920-928e-db2caa8d9762

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fd-8449-78a9-82c8-3a67f76b42fe
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fd-844d-7a51-97b5-382122d9c546
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fd-8454-73c1-b0b6-8efecc497b36
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fd-845c-7db2-b4c5-b054f16a901b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fd-8461-7784-8c38-c96de7c4f145
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fd-8469-709f-b206-284b1e701e65
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fd-8470-7fab-a392-380258b3ff9e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fd-8474-7e85-831e-d1f886ebc5be

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fd-a5a3-7feb-bd32-94f0868e5524
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fd-a5a8-7eb2-9ceb-360d3bd702f5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fd-a5ad-7ffd-96ce-74a3e61e9775
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fd-a5b3-75ba-a3c6-854bc88b8eec
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fd-a5b9-7a19-a86f-1d548cbe5d66
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fd-a5be-7c76-82a9-0897a820eed8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fd-a5c7-70a6-a80f-18522bfb4ec4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fd-a5ce-7324-9d13-1f182829699a

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fd-b524-747a-8566-fd224c5cba25
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fd-b527-71c4-9996-d708e414b4af
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fd-b531-722f-a06e-2695d7de4e89
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fd-b536-7126-b223-fc46ffd93497
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fd-b53f-77ce-b8c0-d94c21a4cee8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fd-b544-7a27-88fa-344a5d370b18
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fd-b549-7fb2-a26b-ade043b2106d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fd-b550-7efd-87c3-5bfa146a0d64

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fd-c7a5-7876-8e55-2f7ba57cf6f8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fd-c7a8-7e36-bf2d-8b174f13120e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fd-c7b0-7224-bf38-d87645c97017
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fd-c7b6-7645-b48b-489f7b35e5db
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fd-c7bd-755b-be8b-69320dfc7012
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fd-c7c2-70ee-8a6e-d16c83ecce67
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fd-c7ca-75f6-91f6-060d6ba5bb94
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fd-c7d1-7109-b10b-ab96c108340d

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fd-db50-7b3c-a549-bd1eb8885cd3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fd-db55-7ad8-ac31-63f538b610e6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fd-db61-7b19-9f11-cb7748c094cc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fd-db66-7a80-9b22-5fa8e555e778
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fd-db6c-7ebc-8bcf-9bc4a1fa48e8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fd-db73-751d-a499-9ccc68a00c5b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fd-db79-763d-8412-c34e3e21c2e0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fd-db80-74b9-89a2-b1f5c9a8fedb

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fd-f7e0-7664-a987-9e339938349e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fd-f7e5-7006-8389-4051fd62bb44
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fd-f7eb-7fbc-a8eb-82df53c51f2c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fd-f7f0-7b04-9a88-a97a47cc7ca0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fd-f7f6-7e7b-a19d-bbae566f81d6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fd-f7fc-742b-b8f4-5bd38682a53a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fd-f802-771c-b5fb-91acaa646543
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fd-f809-71be-9ac1-2fecf8f0cd37

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fe-1332-785f-aa93-800cddb5a269
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fe-1337-77be-ba12-3481f191da88
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fe-133c-7fb0-be7f-7b778ac2e32b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fe-1341-7d11-9e2e-7d5a3ad5ce90
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fe-1349-7963-89cc-542f410b9c9e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fe-1350-7303-9495-699f919e92db
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fe-1356-7702-8d5f-4afef4fe2e90
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fe-135e-731c-b785-60382616a07f

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fe-21d9-7a07-ba5d-7832d6140a20
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fe-21dd-733c-b8a0-66e4c6be70a9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fe-21e6-7eaf-b385-b9f737dab409
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fe-21ee-737c-ad8d-d6fbbd93fef8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fe-21f6-72e4-9ac3-7873c39d73a7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fe-2200-7066-99c8-10f1a33a835e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fe-2207-7a5d-b76a-6252fd8dd231
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fe-220f-7448-8333-a5e7bb7d663e

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fe-3269-7c62-bdd5-8264b42fb17d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fe-326d-7b82-8d50-7f6da0aa352a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fe-3273-7411-bfa1-e2c652621718
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fe-327a-7079-a0a8-e21a086105c5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fe-3281-770c-bf58-e6ba52014bc1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fe-3286-7591-9f56-ec7d3f199d91
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fe-328d-7514-bd23-1ef5f4a2acb9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fe-3292-70fa-abf8-52caa23f11aa

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fe-5d47-7b11-bf73-c66125ef5cd0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fe-5d4c-79c4-b729-4291188abacc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fe-5d52-723d-94a6-4ffa6ba453e4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fe-5d58-700d-bd0b-e644fffdd785
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fe-5d5e-7141-8b23-a5a7c95b2442
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fe-5d63-7b51-aaca-ca9aa6e4f9a7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fe-5d6a-7a2b-9392-8b32e58d4104
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fe-5d70-7d1a-a589-eb375fbb4218

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fe-794d-7811-a1a7-e3f1b4b6d0a0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fe-7952-7b9c-8bbe-74cf9362bca3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fe-7957-76ab-aa94-90997af2601f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fe-795e-7e8a-bfce-2de27bf01979
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fe-7966-7193-92ac-13aefebdb611
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fe-796e-7ac7-bac9-0d722d43fd3b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fe-7974-763f-b4bd-e933ca0ffadd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fe-797b-78c4-be07-d7a37848d233

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fe-90b3-7b49-a803-1241c9d5dddd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fe-90b7-714d-bbe1-0db0aeccf15a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fe-90be-7e2f-887c-eda0de7cf059
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fe-90c4-7913-989e-888885cac30f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fe-90cb-71a2-8014-7bc82b8aa655
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fe-90d1-7d3e-bce1-df308d0214b3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fe-90d7-7761-9afb-4249e58b7401
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fe-90dd-7076-aa5a-7f15c76a0996

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fe-a477-7af9-a00f-ea417aa9d64d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fe-a47a-71d6-b237-51f115cdd4ec
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fe-a481-77bc-bda5-8277d23aa75c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fe-a488-7eee-872d-442d60954856
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fe-a48b-748a-b0eb-42cb39dc71d8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fe-a490-7f77-b329-bff4c1a2781c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fe-a497-7622-87cd-698d19521691
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fe-a49d-7c56-80d3-6389557e508f

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fe-c2b8-7fd4-8ea3-f32a55b0d7f2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fe-c2bb-7269-aba6-0500e36a9a8c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fe-c2c1-7191-85b3-066131792b95
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fe-c2c8-79db-8c24-c8c93301e4a6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fe-c2cf-72f3-856c-ed8db4aa069d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fe-c2d5-7554-aaea-1e185ef3d9df
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fe-c2da-73c5-8b89-c4cb262b2f2a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fe-c2e0-7670-b1ba-107ecef7862b

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fe-df6f-7349-a068-8bbe253936e8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fe-df72-7862-81fa-8601a9c1f6ae
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fe-df79-7832-b8fb-592c82c6b64f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fe-df7f-720e-bd0a-df86db6b1487
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fe-df85-7e75-8e05-edb17b037708
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fe-df89-7163-a5a4-85d16fc6d2e8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fe-df90-7576-91a4-1ff3de89c412
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fe-df96-7bd9-bb7d-df5b525cde66

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fe-f46d-78dd-9827-6c300285ebf3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fe-f471-78d3-8199-0dee9c5ce814
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fe-f477-71c5-a64f-f09e8e14d083
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fe-f47e-7ec9-9906-2fc3b80f7a34
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fe-f482-7b15-a80d-b2ed1a4750cc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fe-f488-7872-91cb-6aaf91df8b7e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fe-f48e-7eeb-8705-69e27ae38af8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1fe-f493-7f36-97d3-1d9e44b44ce7

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ff-0926-726e-9640-48d16b363b14
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ff-092d-7a39-95a0-0a0aa02fc1dc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ff-0932-72b0-a0ac-0253df9486df
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ff-0938-7ba0-b347-a35c7fbcd727
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ff-093e-7e29-aef7-9633a49ee3e4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ff-0943-7ef6-a65e-36f9562e7d72
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ff-094a-7e97-983e-1809f7fb6f9f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ff-094f-75eb-85ae-0e6f16a8f05b

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ff-1549-7046-aafb-76481816414d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ff-154d-708d-a2ca-14c40c1ea412
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ff-1596-7157-a819-3a78056517ca
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ff-159c-768c-9b64-f1fbf0e3983d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ff-15a2-77ce-9ed1-57870f2e3119
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ff-15a9-7577-b981-ac52590792a1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ff-15af-7722-9707-c952192c1778
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ff-15b5-79a6-9470-b5a7d63265db

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ff-3544-77ea-952b-cdfc155073b0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ff-354a-716b-9674-b2cfed39a6cb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ff-354e-7209-8a2a-b49d4a3fbe83
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ff-3553-7184-bf50-a670c09ab26c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ff-3559-7864-a856-4abdc92d507a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ff-355f-7f56-8fce-dba2ae757da0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ff-3565-7b35-b9ce-586dfbea5d2a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ff-356c-73c7-afc2-f4a39de175e8

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ff-4957-714d-95fe-3eb5d55e52a4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ff-495d-7716-b8fc-814230fa60b6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ff-4963-76db-b0e7-594647f605d5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ff-4969-7524-8d2a-25a016dc0c9b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ff-496e-7705-9803-0fa064665fc3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ff-4974-747c-88b1-9d9e68d56379
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ff-497a-7c7b-9594-741e51206b70
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ff-4980-7180-b0ab-3953eec14ce0

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ff-55b2-737a-ac37-b964eb0ece4d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ff-55b5-7ab9-a127-609635485d2f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ff-55bd-7aa9-b80e-19b389d4b100
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ff-55c3-70cb-9d08-159c468a8a01
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ff-55c9-798a-b829-a3276a683151
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ff-55d1-7b06-b242-3f82f68eb28c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ff-55d8-7834-92e9-ed9cc11be264
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ff-55dc-7fe9-a6d6-5503cb9a2b24

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ff-6ee9-7dcd-bde9-c7b026f64bba
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ff-6eed-75fd-9b3c-a6b74c74ec8c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ff-6ef4-7938-833e-92190744a088
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ff-6efa-7165-8a42-bd29403e2123
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ff-6f00-72d2-ac16-d8eed5b78db3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ff-6f06-7827-a9d0-8558599eeeb6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ff-6f0c-7c09-a9fe-395d827b07ca
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ff-6f13-72ff-8fd1-d35516558134

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ff-82e0-778b-8628-25091a3da3f7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ff-82e4-73db-86cf-4a70f4023f88
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ff-82eb-7a65-9ad8-f20bde06fe7a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ff-82f0-7399-9894-e7ae05e8302d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ff-82f6-7b6a-af3a-a2394c9fad87
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ff-82fb-731b-89aa-fbc891924815
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ff-8301-70de-aede-b30a5f9ba503
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ff-8308-76db-96b8-4e60503284af

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ff-945e-7f08-ae62-ae0abd166a2e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ff-9463-7ca5-92e3-614117fc0d8d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ff-9468-79d6-bc71-2429d260c810
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ff-9471-7d44-8264-925f235fe01b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ff-9474-74ee-aab5-c1d00a452062
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ff-947c-7a47-9a9a-c1835b9ef98e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ff-9481-7b4e-858a-497fed8fc536
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ff-9486-79c6-93c7-0df6aefac5ef

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ff-a8a2-7e19-84f0-c511f3ef8e8a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ff-a8a7-7d96-a11e-99edbd216e89
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ff-a8ae-7c12-9767-24b885c560cb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ff-a8b3-70d3-a141-d611035e5c9b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ff-a8ba-7308-b125-0bbaae68fd95
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ff-a8c0-7e00-9822-94282c92420c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ff-a8c6-7fbf-829a-cfdb1ff8e5e7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ff-a8cb-7817-8ef0-f01c2a110d37

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ff-bcf7-7863-ad7f-8eb185b24329
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ff-bcfa-7f07-bd14-0ad1c4924495
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ff-bcff-7f1c-a62d-f74856f6bb0b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ff-bd06-7eff-b569-7f3a526996d5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ff-bd0d-7d41-8f38-e6fb41a3a046
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ff-bd13-79ac-9d5e-4f2eac01bc53
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ff-bd18-721d-9d0f-ed03b6a669d8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ff-bd1e-7006-ad65-44cf929db9dd

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ff-d218-7a3e-a850-b4bf7ee38c50
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ff-d21d-74e1-bec1-5b0a692b73dc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ff-d223-78ff-9e29-17532b6999b1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ff-d22a-7a82-9a8d-8af1d3e80118
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ff-d22f-7f86-a1ee-abd74fc0b806
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ff-d235-7ca9-9de7-982d661dca27
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ff-d23a-7c88-a82d-3ee2b176eb24
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ff-d23f-74db-b7e8-72b5a0a62392

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ff-ea3e-76bb-9b62-afb634e17699
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ff-ea41-7878-978a-0697c98f07ab
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ff-ea4a-711d-b8da-7bbce921731c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ff-ea50-7812-bf37-60b30951bf39
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ff-ea55-71f8-9474-b1dbfc1e5c60
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ff-ea5b-7932-9c1f-cce7c31fd561
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ff-ea61-7ed6-959f-687f5b66dd97
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f1ff-ea6a-7ebd-a3c8-bc00cf502c68

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f200-001c-746e-abe4-41daa68568b3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f200-0020-7240-ad35-e095f1613c86
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f200-0027-7ca9-bedb-c076676f78bd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f200-002d-79ac-bb06-d338d3a82229
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f200-0033-702f-915b-b4ae80d2f00b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f200-0039-7356-8086-5b7af667280a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f200-0040-7d1e-9929-64d8527dfccc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f200-0046-7096-ad04-212324ea319c

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f200-1ee1-7389-9064-3182117e55a3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f200-1ee6-7177-930b-48bf9f6cebcb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f200-1eeb-7c5c-ad98-ae58fc4bb1d5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f200-1ef1-7d5c-9694-36b905221645
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f200-1ef7-7a7c-a425-8b7b3597805c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f200-1efc-7e9c-9384-25604b5fcd23
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f200-1f01-701b-a4ab-73e150f883c5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f200-1f08-7616-ab1c-4655ad04e8ec

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f200-3881-72a0-bc69-49eb2dfee7e6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f200-3885-7a76-87da-5d0c5e01f22f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f200-388b-7a7d-a825-79b81030e3a0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f200-3891-795d-b212-275518cd818f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f200-3896-768f-b0ec-778cd280c5b4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f200-389c-79b0-8cef-3301b13b7ecb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f200-38a1-7b75-ba85-580697969450
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f200-38a9-7c63-bf7b-f7582b06a8f3

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f200-5424-7c27-b142-b6ab36f17400
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f200-5427-765a-8dd6-87c493e442b8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f200-542d-7cc1-a713-b3d80ea3b1a1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f200-5434-7779-8483-cb9fc4519590
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f200-543b-72cb-a2ee-d6c9f77266af
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f200-5440-7f69-8f60-51b170d67971
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f200-5445-7170-bf97-0c60239283ef
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f200-544c-7dfc-b7eb-8056539139ef

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f200-6b53-70b0-aea9-4e0c7a6215b4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f200-6b58-7009-86ff-39976d1ca5b7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f200-6b5e-7441-b142-bdbd8c409450
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f200-6b64-7d67-b782-fef9ed907d33
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f200-6b6b-782f-9e78-697b2a69e81a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f200-6b70-7547-bfb0-cdc583727841
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f200-6b76-7bcf-907a-7bfbda8c5e24
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f200-6b7c-76f9-95e6-f9891336f606

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f200-7b74-7a3d-9b7c-098fd772cfdf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f200-7b78-77d7-9346-c3443c5b8aec
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f200-7b7f-7c0b-a97e-f12ca023711f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f200-7b86-7662-8da4-c275b2324c4c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f200-7b8c-7ca9-b5c6-72c3cddf94f9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f200-7b93-75e4-9574-ffcea2c6d186
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f200-7b98-7682-8da1-f12e20d38e06
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f200-7b9e-7a13-a357-aa93575c7f06

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f200-911b-7650-ae24-b00431649ef8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f200-9122-7c43-91ef-12cc599ce5d1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f200-9127-713b-a18c-bd714f67aa44
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f200-912d-7236-bce3-502c4b6a87d3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f200-9133-7262-95f4-06485a5653ec
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f200-9139-7151-ae29-96467a923223
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f200-913d-72fc-b05d-c7f5c63a23f6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f200-9143-70a7-975f-6ca15c787365

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f200-a3e1-7005-836c-4559cef3391d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f200-a3e5-77cb-bc4c-c45a792cdcbf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f200-a3ec-7782-87e6-bca7c25f96b1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f200-a3f2-7908-9293-222d45a4808b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f200-a3f8-72f8-8071-79a0ff3227f6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f200-a400-724e-95a5-eef627fffbd9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f200-a406-76a2-a094-011538333640
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f200-a40c-7cf1-936b-02908096ada9

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f200-c55d-72fc-8d07-5d5ed80c0903
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f200-c560-7241-808f-e5ae9dbe448c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f200-c566-7e4e-a435-43ecdde2745e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f200-c56c-7488-a923-a99d40087232
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f200-c571-7d32-8c65-531a1ee73c6f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f200-c576-7538-96f7-6c7c8076e2e5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f200-c57c-7e3c-8fbc-33ced186a05b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f200-c582-76dd-8a1b-502f9eac848e

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f200-dcd4-7897-8cad-ba8efbd75f4a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f200-dcd9-7e85-aba6-78a114b49528
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f200-dcdf-71ff-bd57-916a3e6ee3eb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f200-dce3-7c7a-811f-66ea05df7777
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f200-dce9-70a3-b03e-d6a9c4322266
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f200-dcf0-76ed-bf18-d9516f19edc2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f200-dcf5-7468-97b3-cc5829c167d6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f200-dcfa-7b6d-84e8-e31362b03cc6

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f200-f1f9-7e52-99e1-bf6d4a4c1828
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f200-f1fd-78e4-8f5d-346fada34be1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f200-f203-7c0d-baee-78b371c816f9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f200-f207-7ada-b5af-a6b75bbd90ed
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f200-f20e-725a-a81c-8a281bdcaa18
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f200-f213-76cb-ae05-bcb342bf1a87
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f200-f21b-76f8-b6d7-abcaf1732418
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f200-f21f-7590-9040-2ecb6a695a84

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f201-1090-7978-9657-590d6079e40c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f201-1095-72c0-a407-3ed01f67727d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f201-109c-7208-a5ac-f4236a9392d2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f201-10a1-706f-8b55-a08c230894f4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f201-10a7-7ee5-94f3-4a9abb42882d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f201-10ad-7032-a593-b5e6853dc8c9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f201-10b3-71f3-9fd8-965b2933def7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f201-10b9-7c77-ab45-213947f0ad1f

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f201-251e-7729-9f4d-a3dc9f55ef41
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f201-2522-7618-925d-ba81d714fbe5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f201-2528-723a-bd16-156524693990
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f201-2530-7f73-9f99-da5f995c7b7c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f201-2536-741e-a24f-fb5bc7cc01ac
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f201-253c-7d45-91d5-44e803fac1be
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f201-2542-7067-88c4-54ddc57d5aae
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f201-2547-7608-a3b9-ff09f5df7117

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f201-37ea-78d8-b352-a0fa8aaea9cb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f201-37ee-79cc-9d04-461b346e58ae
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f201-37f4-735b-871b-9fc9944bf173
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f201-37f9-7ac3-8ad1-66ca47c4586d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f201-37ff-7e19-87c4-d41b046ff507
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f201-3806-7583-b5fa-c9c484574d17
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f201-380c-78c9-80e0-c88829926794
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f201-3811-7a4a-a4b3-0fd40a386191

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f201-4f09-7a06-bd83-e14d03123040
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f201-4f0f-7f12-9841-65fdd1575fb6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f201-4f15-76cb-a8ab-347e6bd0c20f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f201-4f1b-7f6c-ad7d-fdabab4a8852
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f201-4f21-7942-9413-bbe6c0d1a27d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f201-4f27-7ba3-905a-7f742fbabcfc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f201-4f2d-745f-bec6-0cc166a60a24
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f201-4f33-7b18-a996-276dc438cb79

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f201-5e5f-7d57-9b8b-b0da2072cc44
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f201-5e63-72c0-b3f1-4100a5838040
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f201-5e6b-7cfb-a0ec-b9647825577e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f201-5e70-710b-9b61-82710cc209f0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f201-5e77-7b49-9fd6-b8e6d54bdca8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f201-5e7c-77cf-98ac-c61b72e0646f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f201-5e83-7a96-a1a7-5a317484875d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f201-5e88-7a1f-84e5-5a3654d8ce81

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f201-708e-721b-b71b-b22e53800962
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f201-7093-7d96-9630-7c982b72cfc7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f201-709a-77fe-ae8c-5f7e12779b22
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f201-709f-7f68-9724-e9c12e3da771
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f201-70a4-7693-b7d5-b2a42e9a60e6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f201-70ab-78a4-81f1-943ff22e8ec8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f201-70b2-75e5-a8ab-bc64602ce2d8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f201-70b6-73c9-9938-caf319aa924f

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f201-8556-7f63-868d-e8df1e8792a0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f201-855a-73b2-99d3-91fd2476fc36
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f201-8560-73ad-af45-2194ede3a79f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f201-8566-7081-83ac-7d3fca662ad2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f201-856d-7319-a8a6-843bb99b7420
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f201-8573-7d47-9a37-7a613e7f4d92
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f201-8579-7990-89ce-2214d3de83a2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f201-857f-7343-baf6-81b7db3b43ee

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f201-9600-73ec-a11b-0e1866cf2664
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f201-9603-7a85-9ca4-aee08ec176c5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f201-9609-7757-851c-1eccf0c97b5f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f201-9610-787b-87ec-9d00c59fd82b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f201-9615-7120-99a8-594471e9c567
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f201-961c-7570-b839-894ee267d6e6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f201-9623-73b7-8545-656551535b61
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f201-9627-760c-8abd-0a23a92e5de4

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f201-b864-7f56-9be7-43318f52922f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f201-b868-7e2e-baf7-23257a415094
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f201-b86e-79bd-9338-72abdbc477d4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f201-b873-71ba-aa91-36a64be03a34
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f201-b879-7563-8d19-c1cf351827a4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f201-b880-778d-a855-9a3d79926dfc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f201-b886-7c64-b029-12eb68f3c0d3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f201-b88c-7589-8b78-f9a811fd300c

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f201-cdbc-767c-b6fa-29e5d0955c84
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f201-cdc0-7017-9f99-709781d6e9a8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f201-cdc8-75f6-8580-320896bfd888
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f201-cdcf-7ce1-b75a-f346e7816332
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f201-cdd6-704d-af5a-5e551a48fc79
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f201-cddf-747c-9e35-e3c8c259ecac
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f201-cde6-7125-8426-9bad051add63
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f201-cdec-70ba-8a22-07b89cdb9bd4

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f201-de8b-7291-a6dc-63348013d7f1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f201-de8f-7ae3-ac3a-fab97ab8e470
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f201-de98-770f-8d44-53f57a4b5018
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f201-de9d-743f-a5d4-ef90be22eaaf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f201-dea2-7b75-9f4c-c5249ae1980e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f201-dea7-74f4-b153-14994a6e498b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f201-deae-7e12-abc9-3a2786e7978f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f201-deb6-7675-8462-bad829bd778b

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f201-f2ad-7765-8c62-88f6cbb577ee
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f201-f2b1-7082-a701-9839c30ab021
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f201-f2b8-7546-9c62-d3b1cda0f1bd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f201-f2bd-76db-b38e-97d59897280e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f201-f2c3-728a-bbdd-fa885b5d5871
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f201-f2c9-7d7d-b0c5-6ac1e097cb0a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f201-f2cf-7134-83eb-d4cd244df5e8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f201-f2d5-7eb6-bd2c-e31f7e52ecc5

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f202-0b91-7e36-85f1-4b79e3b11255
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f202-0b94-7369-97b1-d469fe38d78f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f202-0b9b-7c0e-a750-4d1675e9c50c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f202-0ba2-70b0-b339-9623b0060c6d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f202-0ba6-751e-80da-ebc89c03122c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f202-0baf-7df0-991f-96e5ce29e589
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f202-0bb5-7130-9e25-008ad0187ac6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f202-0bbd-7076-9c36-0a1351ecce33

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f202-2091-74e5-ae97-da58c035ec53
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f202-2095-7ef0-b28a-626973ed9b65
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f202-209d-78c4-a030-bd22d1e33a8d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f202-20a2-7293-a120-97d63751a0ee
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f202-20a8-70df-bc9d-abbcb09bd9d1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f202-20ae-7d1a-afc9-6ed768b72480
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f202-20b4-7c43-b680-5cd89f56822b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f202-20b9-7d87-a8a6-7b84a591a6f7

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f202-2cf8-75d9-bb36-9d0c07e43108
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f202-2cfc-70a6-b251-92f2cd57c984
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f202-2d04-7a65-9922-9addc95c2f23
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f202-2d14-7ee3-907c-1bf6c43574d9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f202-2d19-7289-ac5c-741d49a0c5d9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f202-2d21-7038-8fb8-8131e16e335c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f202-2d25-7c77-8a06-0e3adabab881
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f202-2d2b-761e-90d9-2bbe36196e01

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f202-4cf8-7b0f-85a1-d6d3794ca189
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f202-4cfd-70f7-b9f1-cd5b60a1d8cd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f202-4d01-74f3-bbfe-776a9a99f7a2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f202-4d07-7ab9-b20f-dc07fa75af09
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f202-4d0e-76d0-8513-be21f708461f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f202-4d16-7a18-8ea1-d6bcd2888673
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f202-4d20-72b7-bd10-144f6dddb759
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f202-4d27-7e9e-ba6a-31680943c63a

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f202-5efd-72d2-8681-fe546b05d992
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f202-5f03-777e-b57a-8d5e3b130cec
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f202-5f07-7232-a7dc-555a379baaeb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f202-5f0d-703c-a016-24d87f893c81
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f202-5f13-7d56-8b16-095ad25a8824
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f202-5f19-7f5a-98f1-05edd7366390
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f202-5f1f-7e55-936a-9f22c32757a5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f202-5f26-7e09-a212-fcf06adac76c

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f202-77c1-71ec-8747-a08cbdd8d48d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f202-77c4-7fca-a30c-93178e7e4e96
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f202-77cc-7515-b688-8ac993b22d40
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f202-77d2-7ce1-a483-645a8519bc1e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f202-77d8-72e3-af8e-1cc4eeb052eb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f202-77de-7fe3-ba19-651415ff9c33
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f202-77e3-7cf3-a487-3ec47c6a4984
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f202-77e9-7e8c-a50f-873a8a8da113

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f202-906e-76f4-a1b5-736d00d20622
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f202-9072-7d26-a5c1-67da62dc1659
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f202-9077-7310-8357-5f4adfd2e82d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f202-907e-72e8-8ccb-2a0ea2b8ed0f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f202-9086-7ac6-9108-f8cfde2a71f8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f202-908a-76a5-91a8-ed6edbb82165
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f202-908f-7caf-9287-5f62f52a31cc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f202-9096-7b8f-be54-f20f239b7004

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f202-9f56-7608-9f9e-207653eaaa93
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f202-9f5c-7b3b-ac32-d61510aedaf9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f202-9f62-725b-b91c-362a9be4ce28
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f202-9f68-78df-a79a-df16a6f37466
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f202-9f6f-7ea0-83af-96af46e72c84
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f202-9f74-71a9-9ff8-f2e7a691287f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f202-9f7a-7fcb-9030-184e8d1b9b05
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f202-9f80-76dc-9890-d6bc57134e99

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f202-bb9f-7353-ab93-45ff3abc356d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f202-bba2-7809-8902-3f3f2044eaf0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f202-bba8-7ef9-b374-82ec165f244c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f202-bbae-70eb-bc67-683facd71f28
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f202-bbb5-7339-961a-ebaffcc3fa1c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f202-bbbb-765c-b8c3-5e5560b14437
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f202-bbc2-72ab-ae69-641859cf5496
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f202-bbc7-740e-b26d-ee6c2e07c332

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f202-d65f-767d-b754-0025f2aafe06
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f202-d661-7d03-86dd-4720dfbe4181
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f202-d668-78ef-9dbf-5bfc16680672
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f202-d66e-7f09-8f06-93033c5520d5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f202-d675-7010-b928-1b046081bad5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f202-d679-7e4b-9432-295e82ac78d3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f202-d67f-7edb-84fe-34adcf4e3595
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f202-d685-7205-81c1-cc816b603bda

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f202-eb0b-7508-bb43-0dabbbfd3cf3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f202-eb10-758e-b3ec-163a4894d75a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f202-eb17-77a0-a4a3-35c0a2e1d557
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f202-eb1c-7a85-9cfe-7deb1da275b9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f202-eb20-7a7d-b194-d90c0f8a4d05
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f202-eb26-793c-90ad-2bacea9bd41a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f202-eb2e-7821-b6f4-7f86be3f18f0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f202-eb33-73d9-aae4-6288ab76d7d1

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-047c-7b80-b974-3388fefe40e3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-047f-7b43-b9ec-ee7db8f709ae
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-0487-7570-9cb9-146fbc982389
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-048e-7fc3-b420-fe8aaaa317b5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-0495-7fd1-9265-f4296603d0c1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-049b-7c9e-a470-27c10cb93d8b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-04a1-7cf8-8beb-30558eccb9d4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-04a6-7f1c-bef5-0d82ba06b877

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-1389-732b-baa2-c7838f970449
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-138c-7781-bb5a-24208472b564
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-1394-7e63-81ff-0d671d7b7883
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-1399-7858-8d77-46a8d94a4983
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-139e-70bb-bb88-f375b58a0126
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-13a5-7779-a56b-420048b3fb7e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-13ab-7c7e-958b-ebc2af362d83
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-13b1-7991-95d0-76ac3159d95d

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-2f37-7669-9d0f-51c6fbe5203c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-2f3b-7bde-98d6-f4e9e5aadfed
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-2f40-7f8a-b2b9-f1ad153eb7f0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-2f45-7125-9f4b-7f447b249bfb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-2f4d-7796-87f9-d8d9f86a5414
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-2f52-72bb-9d42-baa178963fd9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-2f58-73dc-9751-29c39f89ae59
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-2f5e-7224-931d-5b5862ec06c1

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-3d4e-7e96-a256-ad5fd4d5c77d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-3d52-7347-aade-5bdaf6f714f4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-3d59-7e87-954b-a31c68176a19
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-3d5f-75fe-8466-2b2752b8314b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-3d66-76f6-b2f0-552f0849b06c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-3d6b-7bf2-921e-1e69513f8ba8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-3d71-76ba-9cae-6d50ba2c9864
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-3d78-7ac4-ab42-e18d1f43fbda

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-4b62-7e55-962b-ad21b0009216
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-4b65-729b-965b-d1afc0b77845
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-4b6c-7e86-9f2d-24ed4ae9f949
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-4b73-7f65-88f8-be0094ece8a4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-4b78-7837-b119-0bbc41cec72d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-4b7f-74e1-ad88-85f5961c2bba
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-4b87-7f06-948b-ad4d00e10cc5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-4b8c-7fae-8f37-a7f538cee7fb

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-6731-7786-8a2d-f8612a00b187
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-6737-7937-87d8-96392bf7922e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-673c-7fb9-b1f5-e41b46d6118a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-6741-706f-ad46-7793e7d01ee5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-6746-79e3-b666-026541aa5eff
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-674c-7a84-b9b1-a593e5d498bc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-6752-7af9-a15e-74a8fa5b6bab
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-6758-71e1-a544-908112ed7d92

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-807b-7a57-a8f0-8d9a420a9ab4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-807f-72af-9734-86e027c0c3ff
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-8085-7faa-914a-0398954790f1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-808b-7c04-b8e7-de92c5666c08
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-8091-7c1d-9f38-588d520b4ff4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-8096-7edd-92ff-c1aba0908e54
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-809c-78a1-8ac7-8d9f1870dd61
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-80a2-7572-b0ed-5f3d0fd0911e

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-a04a-7500-90e5-7f8c7d4fbfca
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-a04d-78e0-ba7c-e57ec786e67a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-a053-76a9-b6b1-04205e1f6a41
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-a059-7ba0-86b4-edebcced8fd0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-a05e-7f7a-83bf-b4ce2963825e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-a065-7153-ad3a-15fc1a603829
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-a06b-7931-96a5-b3368963b6da
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-a072-7450-b709-7e7a2d8d6157

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-af5b-79b0-b909-3ace0d6efa7a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-af5e-71bf-9287-c61e52a028b2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-af65-7e08-8cff-f062f1521e9f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-af6c-7be1-9ec0-cad32c9b7a61
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-af73-7c11-b1a2-efa9d4177359
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-af78-769c-9f3c-5a3d40febad1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-af7d-7ddc-9217-9cd9a4306c11
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-af83-7f0a-b5e8-44547188caa9

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-c112-7c00-aa86-a53774fd2dd4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-c115-7f46-8b7c-adf091936feb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-c11e-7a77-a665-3a8a5812a1d3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-c123-736d-a123-159aa3ea06dc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-c127-786d-a04f-11e6f45b8fcb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-c12f-7839-9d46-5919a40c6b3c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-c134-787c-aa7c-d460a0d13d06
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-c13a-700b-902b-399923d400d5

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-d43c-7f36-85b4-501237b06421
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-d441-7736-8980-6ded3df6ece6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-d448-7414-a626-87caa4b61eb1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-d44f-73e1-8d77-156cd2148d85
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-d454-75c4-8761-fef2be541a61
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-d458-7aad-829b-6198ae792f71
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-d45f-7d47-a046-6ee705996a8a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-d48e-7b0c-9766-93762b70de20

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-e7fd-7b62-9f85-1307c707fb3f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-e801-7f5d-bfb7-53ceaee6a3c7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-e808-764f-878b-5b341ff89272
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-e80c-76d3-bf44-2c977876a80b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-e813-71c9-a185-255b2a5fe5c2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-e81a-71c2-9873-b726ddc61131
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-e81f-7116-9313-c4f5226132a6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-e825-7fe2-a06b-dbf821d9d816

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-fa64-7fcc-a305-d618e81e750f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-fa69-7298-b0c2-8fd1d559cd36
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-fa70-701a-b5ef-696c76a0a952
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-fa76-7d3c-b394-5ec090f3778e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-fa7c-75a8-b333-45cb47b0cb02
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-fa81-709e-b026-fc71c66f07fd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-fa87-7871-89ee-c0f0aac341ad
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f203-fa8c-7089-b618-386da17d8ca2

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f204-13c6-79e3-ab7c-264d607f67f4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f204-13cb-7e9f-b63a-4d545b04125a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f204-13d0-7674-bd14-759416d23dd4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f204-13d5-70cf-86c0-0e35b0e0f268
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f204-13db-76a2-8a74-c3a4cf1314a2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f204-13e2-7037-b23f-7e3692d27b8d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f204-13e8-7735-ab6e-72b91272964a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f204-13ee-7788-ae32-9f039878cfea

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f204-272d-78d1-9421-3bd1469de3ae
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f204-2730-7765-8fe5-4d3e9a642c5a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f204-2737-7d86-bf53-38b7f38f1928
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f204-273c-7e69-b242-021984aa5365
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f204-2743-7a57-b2c3-f0729c7f3a83
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f204-2749-7d3f-90ec-e6c137c7b239
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f204-274e-740a-88f0-ec82861c5a48
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f204-2754-7f6c-858d-c6c36373fcd8

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f204-39de-7488-a888-3e99715e0d9f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f204-39e3-709d-adfb-5466f75fb95b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f204-39e8-718d-bf73-848bb24c0fca
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f204-39ee-71a2-a10a-a8cdb7148455
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f204-39f5-7c8c-af58-f8e538902eea
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f204-39fa-7d6c-9d8b-8b7d5327231a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f204-39ff-7ec0-bdbd-6441a181bb5f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f204-3a06-795c-aeff-0de97e8fc0eb

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f204-5f12-727d-b21c-565d9c1c5eda
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f204-5f17-7553-8746-ae2daacd96b1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f204-5f1d-74b1-a8b5-a52317f6ef43
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f204-5f22-798d-b35d-762edf364db0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f204-5f28-7d6f-a001-c61cbcd6232e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f204-5f2e-747b-9771-8b3356ba6749
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f204-5f34-75ad-9369-979f88f66230
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f204-5f3a-731f-bb65-f5df8216db34

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f204-7621-702e-964e-01db106d3684
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f204-7624-7d9e-b114-330ca240d636
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f204-762c-7d28-b497-257ab54b5c69
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f204-7631-7dba-b103-708fc75ab883
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f204-7638-7e3a-9109-c80d6295e2af
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f204-763d-7715-9581-6528c1c8bc60
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f204-7643-70dc-91c6-9a5192b6d63f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f204-764a-72fb-a6eb-e118fd58e3eb

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f204-9c5e-78f1-aafb-3a66ce5ecaa2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f204-9c62-7dd8-9b55-e42d77fe2b98
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f204-9c67-75ed-84a9-5d4a6615358b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f204-9c6e-72ce-a24b-e490d824cd6e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f204-9c75-7081-9c1d-4a7418140b32
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f204-9c79-7db0-8c42-66640919f21f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f204-9c7f-75f3-b762-6bfefb69392d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f204-9c85-79d1-b6e4-1231bf10a2e5

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f204-a300-7a05-8316-43c11750d17c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f204-a303-7a30-acb7-1b6200f4e2ea
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f204-a30a-7325-8949-ad47a33950fc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f204-a310-7b01-8254-82615c4225f0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f204-a316-7941-bfc2-6337d976939b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f204-a31d-7e55-a185-f0ecaf01b4bf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f204-a323-7278-a276-6c3eac82946e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f204-a329-70fe-a883-e512c9d2c59e

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f204-c8ac-79f7-b228-5f8305e3972c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f204-c8af-7b20-ad7e-e66983d99fea
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f204-c8b5-7af2-8b38-8097c081f206
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f204-c8ba-7427-9ecc-d4c1717135e0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f204-c8be-7156-ad93-349f0e1a2c78
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f204-c8c5-774e-b6ad-55dc890b4ab1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f204-c8cb-741f-867b-04fbdaa6e2d5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f204-c8d1-7808-9d1a-cfe90f230e4c

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f204-db47-7fdd-b07c-e75f978c0558
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f204-db4c-71c0-863c-7632866b48c8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f204-db53-7aba-8cf6-2120349953c5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f204-db57-7066-8cd3-ff554f4c04b9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f204-db5e-754f-a0bf-52bfcc5e74db
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f204-db63-70d3-894a-6b32fa54037b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f204-db68-72db-b47b-34f3b6dddfd2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f204-db6e-7786-b109-49c48417811b

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f204-f528-7af7-b6df-fd8a93418246
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f204-f52d-7925-a53f-47f26a070730
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f204-f536-7d67-9ed7-bf4ad8672fbb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f204-f53d-780e-ac94-5647835c28da
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f204-f545-721e-9347-5b6594ac62c2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f204-f54d-778f-ba0d-89dff7de17f7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f204-f553-783a-a71a-62818ca2437e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f204-f55b-7ce6-ae06-1062f3cb7f52

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f205-0dd3-70e8-a26d-838541953e74
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f205-0dd8-74f7-8a2c-8003b9b84eb5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f205-0dde-7208-a315-a32cd8824612
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f205-0de3-7f87-bce7-81f2029c425f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f205-0de8-7417-8bf4-73db21713cde
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f205-0def-74b2-acc9-6f3453890c75
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f205-0df5-78dc-9214-9b01d9ba1137
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f205-0dfc-7fa1-9046-a4150765bdc8

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f205-23d0-735b-b2ff-33a96e0c9505
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f205-23d5-71aa-be7b-68c79aa46790
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f205-23db-73c1-bf9b-d4a8920e8b63
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f205-23e1-7258-9000-1053f39efede
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f205-23e8-7b9c-bc29-dc0e2433459e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f205-23ed-7ba0-b8f8-6aceb1587c71
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f205-23f1-73a2-a823-3634aaac191a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f205-23f7-73b1-8127-f55846e0c83e

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f205-3433-7ed6-a746-2ce80a5f8859
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f205-3436-708c-98af-3f619b2f13cd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f205-343c-7e9b-805f-3a81aabf6730
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f205-3444-767a-bb1c-d12e3a44e124
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f205-344a-7157-9281-b979c951ac5b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f205-3450-7fd8-a50f-aec9910468ce
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f205-3455-7a99-a044-52bda5a939e6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f205-345b-759e-9a8c-adbb798a8c94

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f205-4682-716f-b0fc-a8739de989a0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f205-4685-7801-ad8a-d4eeda6e8526
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f205-468c-79c0-86b9-a9629209555e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f205-4692-76ae-8bad-2c5eec1492c8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f205-4698-7c91-bcff-794db413230c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f205-469f-737c-966e-c28e61383c88
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f205-46a4-772f-9218-849ca73b8a1c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f205-46ab-76c1-ac4e-984817407071

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f205-5b33-7eea-af6a-2d8eac6c53e1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f205-5b36-7de9-8196-d1b9ea31260e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f205-5b3c-72d7-9401-4d428dd3f84f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f205-5b43-7ed7-99d4-0519aba4c778
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f205-5b5d-7f2d-9b03-9f75f397f9ae
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f205-5b62-7175-b146-477134a8eb30
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f205-5b67-71f8-83f3-aa1f751e5d78
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f205-5b6c-7677-899c-ae783f29b43f

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f205-70db-7f33-a7d2-8d388bf664ab
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f205-70e0-7f2a-b438-3d775fefaa47
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f205-70e5-7bbd-8147-1bd3ae395292
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f205-70ec-768c-afa3-ad66fd57615c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f205-70f2-7d41-811e-d766281ddae9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f205-70f7-72a8-be09-372891e15824
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f205-70fc-7f49-9df9-65772ddc4717
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f205-7102-7414-90c9-d5a1a30a23da

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f205-8c35-7cdb-86e3-616d2ed18643
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f205-8c37-7b30-9cc8-f5b0229e1268
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f205-8c3e-7d75-ba67-ed29b3b7d4ef
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f205-8c43-7ede-84fe-9e2900ff95b7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f205-8c49-713a-b0cb-ebd77d2807db
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f205-8c51-75e1-b7e7-82d117daf818
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f205-8c55-7665-99cf-e1d8585b676f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f205-8c5c-7a55-bd6b-6e5ac9e24262

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f205-9f09-714c-9275-3b0c2295a3f7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f205-9f0c-7f9f-b33e-2abc7185546d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f205-9f13-7c53-a42c-8bc744ebeef5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f205-9f19-7de7-b0c0-5168a75b269c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f205-9f1e-7e08-955c-c4ca706bad7b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f205-9f25-71b1-9f1f-23f4efb7b58a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f205-9f2b-71ef-bc6b-9e2f5a0f202b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f205-9f31-7086-9dd5-7637e7bd9731

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f205-b882-7b30-8ee8-d644b863f954
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f205-b886-7186-8746-49c8fce98aa3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f205-b88d-7ef8-a73b-00df9df75264
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f205-b892-7635-a002-18cdd882fb1c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f205-b899-7fc3-bd4e-eb09d1087c2f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f205-b8a0-7488-a4bc-9430fc7f0ef0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f205-b8a9-7325-a0e6-5976ab45c207
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f205-b8b2-7bb5-9da0-f35e893416cc

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f205-cb15-79b7-9e70-2db6b29f0581
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f205-cb1a-7df0-a6fd-3e655b936604
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f205-cb23-7660-bff6-420f22aaac47
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f205-cb2b-75fe-8b52-0da5348ffd5e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f205-cb34-7edb-843d-2947875df873
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f205-cb3a-7013-963c-c206b0063089
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f205-cb42-71ee-8af4-894efd040ecd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f205-cb4a-764a-8525-49f7cd732fa6

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f205-e327-725b-b466-99d8740836bb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f205-e32c-7a65-90c1-bfe401357982
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f205-e332-755f-bf48-53f352f49f8f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f205-e337-7a9e-8ee4-7a90ce090fb8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f205-e33e-749b-8c61-07a27e864e24
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f205-e343-7f15-b3d1-5573e5e7593e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f205-e349-79af-b336-0c752243d610
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f205-e34f-772a-81c0-b1cf2f868fa2

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f205-f592-76cf-868b-bbe5323af71e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f205-f598-7f76-bccd-48ef37d66ebc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f205-f59e-7617-abfb-56213e6e487d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f205-f5a4-7823-9abd-3286bd6a7219
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f205-f5a9-730e-b729-8962ecdf849d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f205-f5af-7f35-9735-bfee4ed0dce1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f205-f5b4-715f-977d-165ce1bbfb21
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f205-f5b9-7f02-973e-200c8858db8a

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-037d-7375-8872-94f52cafab5a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-0381-7ad3-ab04-1278052a34b9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-0388-7569-9f5a-6fffedce5493
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-038d-7b6f-a5ce-03af38d6e0ff
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-0394-7698-92b7-9371f4576623
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-039b-7ced-abce-ebb77698e6a7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-03a1-7533-a63c-ef36a187fa33
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-03a8-737b-880d-6f9f681171e1

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-17e8-7bf0-90e3-0bbb4685058f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-17ed-7a5e-8c70-75f478f9b125
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-17f4-7a84-ab84-4cbfa384ab57
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-17fc-7519-a15d-97f137e88948
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-1801-7bd8-b5ff-86205afac47c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-1806-7e23-8719-2dd0a8d9bb9f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-180d-70a2-8107-bd3e79659ee1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-1812-7472-9ad7-1fb367e0c74e

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-244d-7c53-826f-60568d187e15
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-2452-7fb1-84d6-7d5f115cd19a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-2459-74d1-9407-d9c1261283b9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-245f-74e8-b52b-277e7080d717
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-2466-76fa-9412-72be217f6d19
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-246c-7bc9-ba9a-707e30526828
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-2472-7b37-b003-96d813f72f59
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-2478-71ec-b9ef-098ead7c201e

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-399a-7b40-96fc-be39d150eceb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-399d-7690-8d70-16982d8bfc22
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-39a4-7d7a-912b-661f3f381f27
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-39a9-7e0b-bc2f-021a9b739ecf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-39b2-7751-b91b-4e9c1c02517b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-39b8-7fc7-accf-f28948b068b2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-39bc-7c22-a155-bbf899d96d35
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-39c3-7795-a53c-498f7ba74405

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-4b24-7f8b-b1e5-0fc686ffbd4a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-4b28-7a42-b5d8-90c58b2d4ac5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-4b30-7df6-b945-ef7607dbe3fb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-4b36-7fcf-be4e-45e1beaac191
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-4b3d-768f-ae99-fb6fe037bab4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-4b42-7747-a81e-89cde74c5e8a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-4b47-76f7-8989-b0818faa0e6c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-4b4e-7ae5-8579-d107d7fc3db8

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-5f67-7421-b75d-55d7df7f3f17
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-5f6e-771d-8b64-8b25358bb430
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-5f74-7e72-bbb8-b035995f4b81
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-5f7b-7a41-bb0f-04d0c8b13c59
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-5f81-78fe-90f9-32905f39238c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-5f86-7d40-b87f-0d0eba33279e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-5f8e-7867-9f73-dd4a5483c96d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-5f93-7f45-a443-82165d93f235

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-748c-792e-ace3-c617940a7c54
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-748f-70c7-9075-caee8e87ce1a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-7496-7ea8-b2d3-f7a0384c79d5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-749c-7c45-98d6-d998236a498b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-74a3-736a-b360-1a4db32c8221
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-74a9-764f-9a7c-235be33fa5a9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-74af-70fe-9f6f-b76949c39bfa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-74b5-778d-8b00-b85b225fc508

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-837b-754e-8030-30a35d945c5d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-837e-7ff2-9837-fda498fb2ae6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-8386-7dd3-a457-a79bfd79b9d5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-838c-749c-9e31-ee9e7f48417c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-8392-7433-8409-4101a745e1a2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-8398-75ec-afe2-de6b9e357ace
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-839d-7446-ac0a-d708190fb8c3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-83a4-745a-835a-2d14fac2730a

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-9541-749f-8adc-7c3408aa0953
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-9546-7896-8b0c-207a2cf797a5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-954d-7b30-8236-0af022606f51
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-9552-7ae3-97c2-e3e065ef666a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-9558-71e1-8a1c-e8696f6d3a55
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-9560-75bb-8496-5eebfbf47227
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-9565-771e-af62-f59691bcaf57
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-956b-7e68-96cf-d95032b45db3

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-b0f2-72d5-adca-875de8c601a1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-b0f5-784d-aa0f-8581e1d88f2b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-b0fc-7ace-bbac-febb608990f1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-b101-7e05-a623-eabca7d5b695
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-b107-7cab-a835-283d8702231e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-b10c-7eca-8d3c-15a3044820a7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-b112-7c29-be55-def85ded2adf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-b118-7fc7-b16c-2c7a62f0200b

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-cad9-7106-82d3-351f9fcb9352
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-cadc-7522-9efd-12e352449fc7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-cae2-722a-8bad-2be550fa3a1a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-cae8-75a9-acc3-da127fa8c446
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-caee-7fac-9af4-8c2cf9f43053
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-caf3-7f59-b735-4d82431c6d15
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-cafa-7e4d-995b-e031514d3972
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-caff-754f-9df6-147c83329d10

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-ea1c-74e7-9faa-f3d68ea3e519
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-ea21-7e9a-b0b5-d8d95a929be7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-ea27-7e5f-87a4-d53a931bd08a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-ea2b-7b94-ae92-f9ace94a4404
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-ea30-7f15-b0e1-d97f6a32f33b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-ea36-7b83-84bd-d90297a1b804
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-ea3c-75b4-8685-f566e63e608e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-ea44-730f-a0a1-edbcda21fa89

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-f7b3-77e0-9c06-53da916ff3b5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-f7b7-7182-9829-3a40e3e08545
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-f7bd-714f-b4fb-43a882b5c1f6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-f7c5-79d5-b4ec-d0a9850c2204
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-f7ca-71c6-ae14-40b60f504a41
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-f7d0-7573-adba-ed96d8da3e12
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-f7d6-71d8-89a2-7d4cb0756b21
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f206-f7db-78e2-af8d-000f86a8b40c

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f207-1bb8-722e-a755-40099d507ef6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f207-1bbd-7960-824e-ace2edc9d10b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f207-1bc1-7218-b408-dd5de6c7dbf0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f207-1bc6-763e-a451-4eaa3485c956
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f207-1bcd-7f21-b6d1-5ae6d527a075
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f207-1bd3-7804-abb4-ab03b9ae3bc7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f207-1bdd-7edf-86cc-99dec770aa40
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f207-1be1-7f54-a203-f28944ef272c

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f207-341e-7136-8301-864e3b99ea52
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f207-3422-7eed-8809-cbd41c1b9752
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f207-3429-7fef-bf80-2994f7e9a9b6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f207-3430-728e-8bb1-83ab1eac92af
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f207-3436-7737-aa90-0d7db7771771
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f207-343b-7bb4-9b20-7549897f8e59
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f207-3441-79e0-912e-f7c7cacb4900
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f207-3447-787f-be79-46525d02148b

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f207-4c5c-77b7-b474-df6bb7ca7224
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f207-4c61-70c7-b221-73304a72ad25
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f207-4c66-74c1-96c0-6acdfc1adc63
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f207-4c6b-70f6-8916-2ea47d439fef
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f207-4c72-7cf6-86fc-097648b1ba6e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f207-4c78-7fba-8af5-6ffcb8b1874b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f207-4c7c-7459-b351-1fd0e96fe1d3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f207-4c83-701a-a2a7-295f25d593ea

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f207-647d-797a-a458-fbb54db63870
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f207-6482-7172-a6ed-9313f9f6f7c9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f207-6488-7e85-bc7b-0500e3320bfd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f207-648f-7db3-9f53-098d290d34f8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f207-6495-7ce8-9ef6-b2977838c66f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f207-649a-7be0-b2be-b45bb6db8ca9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f207-649f-7477-aa7e-c253cff3d4b5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f207-64a5-79f5-accd-a1328a0dbd64

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f207-6e8f-71d9-8800-acbb3a568f0b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f207-6e93-7278-98b6-c49e374d5f43
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f207-6e9a-77d2-987e-5c03e8ec5c3d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f207-6ea1-71fb-a402-e98c4ec2ef2a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f207-6ea7-73c5-807d-475e48019544
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f207-6ead-7f2f-b27a-7a92da16347a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f207-6eb2-7b46-8551-ee3a6ced23df
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f207-6eb7-77cd-8366-e5ce0783e712

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f207-83c7-74da-ae39-b4df00ee0771
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f207-83ca-728f-b580-2f9acacdbc89
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f207-83cf-7bd2-9b16-96b94559b563
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f207-83d8-71fb-a608-24d81b9c882c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f207-83dd-73a3-a85c-3e1b045a6978
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f207-83e3-7c1a-a760-0abc57520878
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f207-83e8-7bdf-8019-ff944b24a688
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f207-83f0-7ea0-8a88-44fcdb6a02ce

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f207-9800-7637-8123-ddc64bdb8573
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f207-9802-7561-9b16-7c3463d51df3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f207-9807-7119-a019-180908ffa35e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f207-9810-7972-bceb-1241241c3e12
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f207-9816-75be-84b0-d3ea31fe1cf7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f207-981c-759c-b201-be0fcb7cfc00
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f207-9822-7415-8334-7e3e70c3a03f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f207-9827-7230-b4d5-4ea4db9f9013

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f207-b592-724b-bf69-13c4328560db
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f207-b595-74a7-a4f3-ac5d67170b65
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f207-b59b-7682-b5c7-e6cdbfb8ecf3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f207-b5a3-7716-96f1-4ca9801b2c4f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f207-b5a9-7bd1-b724-432e0614ed60
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f207-b5ae-711a-8355-0c02182e68c3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f207-b5b4-75aa-919f-7d7b22d752e0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f207-b5bc-71f6-8fd2-1faf93d3fc05

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f207-ca4a-785b-ae51-0900389c6bd0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f207-ca4e-7dbf-9995-dac5dd5d96be
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f207-ca54-7ebf-a7c1-20472970ce44
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f207-ca5a-7bda-87e4-91fe164985ac
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f207-ca60-7296-b8fc-b20dad272d58
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f207-ca68-7aa9-a5e2-904e22149abe
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f207-ca6c-7aae-aa38-bc803be5c783
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f207-ca72-7086-a0ec-9130fd972c4a

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f207-dfdd-7e21-9dbe-27871478ede3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f207-dfe2-7a85-a072-78764bc21137
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f207-dfe7-75a4-9730-2b6a0876bc6e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f207-dfed-7e7b-8828-ebb1ec3c1511
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f207-dff3-7b83-9167-431110b9fc8a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f207-dff9-7bbe-8996-1f473fc36953
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f207-dfff-73d0-87b2-4a8ecddbd607
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f207-e004-78df-be9c-e373d470f0ac

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f207-f8ec-789a-ad79-48cd1377d21f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f207-f8f1-75a6-ab6d-9e462846f5e0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f207-f8f6-7e81-9002-2f9d1563a4f0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f207-f8fb-7c1a-905f-1cbef70eefa5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f207-f901-7f49-afd5-a086f2b60fcc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f207-f906-790c-9e30-58104e2eca2b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f207-f90e-7c90-939e-36552e6b563e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f207-f915-74a5-b787-b2b1d6e2684d

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f208-15dd-754b-9baa-e3b45d7dc480
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f208-15e2-786f-a436-b9d8d224026d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f208-15e8-75df-836a-3f30559ab4f3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f208-15ec-7771-b463-b4b3026255dc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f208-15f3-7af8-9310-485334aef0f4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f208-15fc-7e1a-b21d-c6fd2b3f6561
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f208-1604-7ae3-b1b4-a67f89cce471
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f208-1609-74f9-9351-b41e5636dacb

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f208-2f0a-7b4d-893d-79569e719993
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f208-2f0e-7795-8d3c-e05093b9d45b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f208-2f14-7faa-9152-f501964222db
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f208-2f18-7f37-a6d2-02f245a2c93f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f208-2f1f-7272-9090-70403fec3613
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f208-2f23-7c48-8644-eec63e6201bd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f208-2f2d-7286-ac78-7d49d1ba2593
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f208-2f36-74d3-864d-114a33e2d24f

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f208-4142-7693-8c72-529673232edb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f208-4147-792a-a36c-274db1ba2f6d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f208-414d-79a1-ae5a-f5ad9d63a636
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f208-4153-79c7-90a7-fca6286f97c7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f208-4159-7704-a3fc-528a2344ac50
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f208-415e-7865-9866-3f1f95bedfbe
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f208-4164-7487-a88c-48af8efeeff8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f208-416b-788c-8a4e-72d172212f2b

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f208-51b3-7917-9a84-9f079defc38b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f208-51b6-7d43-8216-49b6bf175b0a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f208-51bc-78f9-ae31-0ce48741664c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f208-51c2-7251-a2ad-c16127344c64
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f208-51ca-766e-94d7-d9b023a98f74
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f208-51d1-7950-a3b4-729caee175ae
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f208-51d4-71c0-ad03-75bbf9942ccd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f208-51da-7a0c-9b54-be268fb46e4f

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f208-6525-7ab1-88c5-f6cede14dbe8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f208-652b-79f2-94d5-7a01c23dc70d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f208-652f-7f40-9cef-57cd44c974f2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f208-6535-72e4-b30a-87389a0d5d2e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f208-6542-77f3-9a81-4dbb27fc116b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f208-6548-7b3e-96d2-2bd063973a48
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f208-654d-783b-9830-df0a5d1a49e7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f208-6553-7d81-89e3-6be465ccf0da

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f208-7838-7cae-a1de-7c403387f19f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f208-783c-79bb-800f-2a6c39905698
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f208-7842-7ad4-a5cd-028262d7293e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f208-7849-792f-9aa7-18c6c23e61c3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f208-784f-72c0-b87f-d3498425ab5b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f208-7856-79ab-9535-942b75b3eef7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f208-785a-7f55-9e63-e40ad5a31eb9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f208-785f-781a-9740-794e6240d26c

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f208-903c-7cce-8b72-b166928b4d93
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f208-9041-77b6-afef-da0ae323695f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f208-9046-792d-b8bb-bd7b72a9be06
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f208-904b-77bc-b8d5-46a3c0ca12ca
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f208-9051-7ced-9d3b-2dbe9be7e217
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f208-9057-72f3-b653-fdcf9475c67f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f208-905c-77e6-a370-f75cc25113af
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f208-9065-7bce-b959-dff7271516de

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f208-a32d-74a0-ab5c-041141a29d65
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f208-a331-72ba-bbfe-77578eeedece
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f208-a337-79e8-acdd-6d990ed1fb17
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f208-a33f-798b-898c-94c4f3a29ce2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f208-a344-70f8-8c76-5ddf7dcca8c2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f208-a34d-7a8a-aedf-91614ecf66f4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f208-a352-7bee-b179-d178574d06e4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f208-a358-7583-9827-5de6473ae9d7

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f208-b375-7733-a10f-1773af1ea7b0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f208-b379-7d77-b5fd-8fbe6e2dd4e5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f208-b37f-7bbe-8817-60e3f4ece2a8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f208-b385-7076-bcf5-a9cc93a7f06b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f208-b38c-7c03-ba80-bf3cc11582a9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f208-b391-7ae4-84a2-d9359bf39eee
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f208-b397-741b-b15c-ae8195208f2f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f208-b39c-760e-b19b-0aa939c58465

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f208-c473-7d87-8d73-af6cd0ecd51b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f208-c476-7afb-b804-c10c16d79fdd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f208-c47d-7802-b73a-ab15a510ce10
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f208-c481-7cc8-b33f-438b2e7257e5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f208-c489-7481-84d1-73f7cd29ae55
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f208-c490-7c57-a9e4-199d90750139
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f208-c496-791d-9b6d-8d29593d66c1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f208-c49b-76f5-ade9-0ba60599f0b8

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f208-dbf3-7a9d-a00f-7c8e9b6b4a25
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f208-dbf7-7562-a048-02230611cfc6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f208-dbfc-725a-b614-972719339c71
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f208-dc01-78f7-a203-b9d530b036c3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f208-dc08-79e0-8665-781072289645
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f208-dc0e-7e47-99a9-00a62a868a33
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f208-dc13-7d9e-9d44-72a2174d47a9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f208-dc19-762b-923f-4f24dc1df9d5

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f208-f106-731b-a764-a11bb95be506
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f208-f10a-78ed-81f8-cc310c51ad96
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f208-f113-76e1-b571-25480f7d36ae
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f208-f118-7aab-9d8d-49f762af360a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f208-f11f-7117-ad3e-987807befc8d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f208-f124-76c4-b6f1-e15bccddf099
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f208-f12a-71e7-a1a8-be2b380b50ad
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f208-f12f-73f7-bdf1-0c47df729a81

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f209-0293-74b6-9d2d-2c8a1988d7f2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f209-0297-7af7-b8df-406fb51af983
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f209-029c-7492-9e0a-520f1ea64151
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f209-02a3-7f68-9abf-d3cb0836fc0c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f209-02a9-7eea-b042-1440abc54ed1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f209-02ae-7552-894a-1f5cae4547b1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f209-02b5-710d-87eb-979362f73a02
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f209-02ba-7be3-bb6c-eba5321a300a

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f209-1fc5-76e1-b760-00b56a7ac619
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f209-1fcb-7be9-afd9-d487fe879b78
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f209-1fcf-7234-8759-4b9d739e09ea
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f209-1fd4-7a76-ae64-414df0e8c79d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f209-1fda-7018-96c6-a10231486872
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f209-1fdf-7377-b323-d9a92e2c2609
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f209-1fe6-7f0c-a57c-a5d81640750f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f209-1fec-7ff9-8b97-0050d03859af

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f209-3ae9-7395-94b4-2ff5f734645a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f209-3aef-71a7-95d5-1f5042824232
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f209-3af3-7bf1-9782-b597df03bb66
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f209-3af9-7d28-a601-e4ac8a9f59f5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f209-3b00-728e-9496-18935669fcec
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f209-3b05-756e-9e0e-d10a7ccdbc29
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f209-3b0c-77c2-8369-619a25db87e1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f209-3b13-7610-9353-8724b322b721

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f209-59c9-7bd2-8849-b59c56e8c0c6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f209-59cc-7204-b23a-88786f34f080
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f209-59d3-7138-ace3-85f444b2233c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f209-59d8-77da-a71b-5b5179c6f174
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f209-59de-715c-820d-28a037af2932
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f209-59e3-72cc-98f6-9aff03a5ae0a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f209-59e9-7865-b54b-e660305bb9d7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f209-59f0-7bba-bb4a-21be65921ac4

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f209-79d0-7d82-82f2-2e848ff22679
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f209-79d3-74b0-94fe-71aa25a20b99
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f209-79da-7eb0-bf41-373471989be5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f209-79df-72df-b1c1-574210fa98d6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f209-79e6-715f-973f-0303bf066bdc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f209-79ed-7113-9835-cfc01c1ff0ac
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f209-79f3-7582-ae67-9c02500e4247
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f209-79f8-7215-8e98-b7535f63ef58

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f209-8c62-7d7d-b7dd-7b4d0e031e3a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f209-8c69-7984-9b42-526c9fb797b3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f209-8c6d-71ad-a37b-3cb678aa7d66
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f209-8c72-7f07-8aac-547d6e7e5220
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f209-8c79-71d6-b69f-020e92755994
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f209-8c7f-76c3-a3a4-73d9b19d3bff
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f209-8c84-74f6-8229-9b9a7e1c0797
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f209-8c89-797f-b338-0eb4867e44e9

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f209-9bfb-782b-b462-83cca21fa206
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f209-9c00-7175-87d0-9f3f56191b49
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f209-9c07-7e75-ab55-7550846068d3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f209-9c0c-7ce7-b542-205ea2e1e555
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f209-9c12-7cf7-b9b3-d5a9cf88dc74
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f209-9c18-779c-bfdd-44396861e98c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f209-9c1d-7e62-b051-53a03e6d11a8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f209-9c24-7038-8ee6-6d3aa03d6039

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f209-b198-79fa-ba4c-483c4bf810ba
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f209-b19b-7fa9-a586-c2ac45fa6543
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f209-b1a1-744a-aab0-816f3d18c8dc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f209-b1a9-7ec4-93bb-bb49d3681c9c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f209-b1ae-7b07-b08a-fba75f6067ba
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f209-b1b4-7bbb-8f40-10aa111e180f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f209-b1b9-7418-a48e-712c5eddbf40
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f209-b1c0-7bde-b97b-d1f226f268d1

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f209-c8ab-7c32-80f4-8b950bdf0224
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f209-c8b1-796d-aa69-3cef42ea52fe
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f209-c8b5-7e6d-b0a4-3e310dd62c37
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f209-c8bb-7998-81de-c61fd975f803
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f209-c8bf-7af1-b8c5-5f6aa1593603
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f209-c8c6-73a0-86fc-2e531aba99e0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f209-c8ce-7721-aa3a-8aff7964c74d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f209-c8d4-734d-b2a7-94a178379dc4

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f209-de5b-7fe7-b100-cf2f87408f3d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f209-de5e-7e57-8b0a-258e52b8daf3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f209-de65-7f9a-a4a0-726f687775ef
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f209-de6b-72ae-a775-13e8b3bed345
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f209-de71-7035-aacb-78b83c7efa77
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f209-de77-7691-a9b8-be37680369a3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f209-de7e-793f-98d5-e1a701a3358d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f209-de83-7226-b1f0-3e558ff5b6ef

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f209-fa4d-7a7b-9cb5-d74932f06ab5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f209-fa50-7d0b-8252-3dead556170f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f209-fa57-7166-a2f5-26c4fadd1c9a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f209-fa5c-77fa-80fe-615189cceb04
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f209-fa62-7940-aee0-a96fdb29b851
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f209-fa68-7cac-acf1-19e08af661ad
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f209-fa70-75b4-8fde-a59f97efddb4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f209-fa75-7ae4-9b0d-f07983357c1b

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20a-0a95-7557-b922-a78cd2860563
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20a-0a9a-79dd-9ec0-a83376c36495
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20a-0aa1-7c85-8091-a33f4ca142cb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20a-0aa6-79f7-a9ab-5ca4bbb5ce82
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20a-0aad-728a-917b-f26baef65670
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20a-0ab4-78cc-97cb-bb8b0d196872
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20a-0ab9-7c13-8c8e-53e6ac1e2c7f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20a-0abe-73a7-abcf-e04343ccc7c4

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20a-26c8-7d16-9e50-8a6256ca98c5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20a-26cd-7d68-b6af-d120a0e894d5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20a-26d3-77c9-867c-db361a02fb4b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20a-26d7-7a9f-aaac-b4b8fb2fa7dd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20a-26dd-7fb8-8410-e4b4df74d8dc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20a-26e3-7f4b-ae16-bbc577c81be4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20a-26e9-71d0-aa8a-a6b89cd5b170
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20a-26ef-7b5c-a182-2d4e2b3c209d

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20a-3624-7112-b4d7-c876eb411774
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20a-3627-720d-a90f-254a2350691a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20a-362e-7ab6-b62c-fbf7d9984d8e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20a-3634-7a10-b157-e4c29dc719d2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20a-3639-7a3d-bfa5-9d776b3d6764
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20a-363f-7382-8c90-7819581c3a48
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20a-3645-7579-a12d-79fb55044345
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20a-364b-742b-8196-3f82be9f6775

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20a-530d-7b58-84ca-2f782731970e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20a-5310-7a2f-9220-39bbf95244ae
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20a-5316-779d-8806-3dd1a17873e9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20a-531c-769b-9ea1-6510648959d5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20a-5324-7156-8886-c04cbd792f70
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20a-5328-72dc-a288-bbc7a22de6fa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20a-532d-79ef-8ef2-27573025193f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20a-5335-7944-9e12-4eeefd889417

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20a-66ba-7bef-8255-15b29754142e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20a-66be-782e-b87a-11546262d3c5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20a-66c4-7145-a12b-8863ef16b7f7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20a-66cb-7ea0-9ba8-b95cc69dd0ab
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20a-66d2-7e7b-85aa-f712ce6cf8de
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20a-66d7-7c7c-ad06-2b3bb030e0c5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20a-66de-7ff0-afcb-8520a188e9e3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20a-66e4-7edf-89ea-b33452ffee3a

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20a-7e7a-7b52-be7c-4a6f85907ed4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20a-7e80-72e9-855c-d86820d8e22d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20a-7e84-7e72-af2a-b4e633b1bb79
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20a-7e8a-754b-a1ce-bbe3c1b68f63
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20a-7e8f-7a24-9e0a-c079a739d913
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20a-7e96-75aa-9d89-19579a148eaa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20a-7e9d-7361-aba6-4b3a80f29bb4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20a-7ea2-7e46-a23b-0e30d7d41a82

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20a-9409-7b5c-a8cc-f0ea4d82213f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20a-940d-7622-a83f-f3c7381b678f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20a-9414-73fe-b23e-61a9430996da
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20a-9419-7481-a054-eb7c106d669f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20a-9420-728e-9c8c-353cd67d2011
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20a-9426-7e34-9dcd-a7264fe346b9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20a-942d-713e-95d5-c64b9680e36e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20a-9433-7e34-a04b-ffb34201f255

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20a-a406-7123-b1d2-defc2d7abd78
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20a-a40a-7dfc-8691-f8574d86f0ca
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20a-a40f-70bc-8396-c2dd46b1a4f0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20a-a416-7b52-a52e-4f9c9dd91961
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20a-a41d-7eaf-a321-e43542a57005
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20a-a422-7784-a5cd-ef0dcf861020
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20a-a427-79df-a4a3-d796f9049b06
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20a-a431-74f4-a4b4-21b5b024aa2f

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20a-b163-7222-992c-afbdd25f07d6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20a-b16a-736c-a028-2c23a0a22627
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20a-b16e-746f-beeb-a788756182c5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20a-b174-7302-84a4-a700a138c785
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20a-b179-7104-a575-00c62a457afd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20a-b17d-734f-884e-e74c0dd4f8fb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20a-b184-78fb-a9aa-ff3d18b92f11
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20a-b188-7caf-84d9-40c02681e931

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20a-c63e-70ec-9db8-e80e0d0562a9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20a-c642-70c4-b647-006d687db0ca
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20a-c649-77b6-8718-066ed558adc8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20a-c64f-71e3-972e-d9181a648b4a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20a-c655-71a8-b783-fad25e49337b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20a-c65b-7986-a871-e7583b78a3e5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20a-c661-7f81-afca-b8e1155d4551
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20a-c666-7e64-ba85-79c1aabbefc4

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20a-dbe4-7af8-b4eb-a3cbcf90bd72
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20a-dbe7-7328-b418-f8f7e17f6108
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20a-dbed-769a-8c3f-b71dfd6a2d64
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20a-dbf3-7e78-8d2c-045cd0f38201
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20a-dbf9-747b-a04a-410b5a9a7e5e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20a-dc02-70ab-a019-217b308ab47d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20a-dc07-7cb4-8ff1-b4f8ee37d65a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20a-dc0e-7253-8707-6004d7e1964b

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20a-f56b-7511-8dd6-cbc3329b4ba8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20a-f56d-72c0-97df-404ba333bfe0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20a-f574-7079-a267-940b5ec7d838
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20a-f57b-73fa-85be-2c044ba8c592
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20a-f581-7e77-875f-55b87073fd1c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20a-f588-7cac-a727-c25034cc0236
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20a-f58c-74df-947d-24cbc3efd442
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20a-f591-7625-a82c-78b4ee42cda7

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20b-0cd4-7a67-8232-237d20adee3d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20b-0cda-72ec-908c-3e4b800d4ea7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20b-0cdf-79e1-b29a-5a5822e1bba8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20b-0ce5-7f15-8566-47834f707391
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20b-0cec-759d-bf1c-3561f78e6319
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20b-0cf1-7b3c-82ba-b4fc2d1ff150
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20b-0cf7-7c09-b3ce-004fce0d18f3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20b-0cfc-73b3-8b66-41175d2a4cc9

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20b-22d1-7fc4-838b-700d9bc45fba
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20b-22d5-7315-b3f0-c4230fc9958f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20b-22dc-7391-99ea-c1731a2993d4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20b-22e4-7bdf-8917-7d114d9597c7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20b-22eb-76fa-8d23-fe64e70462a0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20b-22f5-7503-9e2c-de6bac19aaf5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20b-22fb-7c54-a94e-bd2f042c8da5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20b-2303-7950-8429-9df8a6af6dcc

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20b-30ce-7663-9379-4a48463f5083
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20b-30d4-7192-95e9-0a580079ff9c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20b-30da-7912-8de6-8113490f4127
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20b-30e1-7c64-91ff-3f71692150d0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20b-30eb-7967-8464-1e22af1d857d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20b-30f2-74d7-83ac-208a287e7e46
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20b-30fa-7409-afc1-3fdf4befdb82
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20b-3102-724b-b295-8b880f123edb

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20b-4909-7462-b85f-e1de84b05635
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20b-490d-70a1-8059-aa085e68028a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20b-4913-7a30-a498-94fd33ec0547
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20b-4918-79f0-a486-f693dba2ffb4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20b-491d-7b5b-9bd3-0d99c0b5b214
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20b-4923-74c7-a67c-c1c0d12be454
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20b-4929-7ef6-ba7f-1bf9a1ef69ce
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20b-4932-74be-b9d2-77969503c099

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20b-616b-7fc2-ab7f-9ccb6c6660b0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20b-616f-7fa8-aee6-d34176f68195
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20b-6177-7b27-ac17-3977f0318574
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20b-617c-7616-b89b-db5dcf56c295
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20b-6182-7972-a2f7-ac9e91fec510
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20b-6189-752f-93af-581f6f5e4a03
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20b-6191-7684-990a-ed988aed532c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20b-6195-7088-a8fd-f573d966c2ec

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20b-7544-7e2d-b5f1-21a4b127c487
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20b-7547-7d8a-97ae-d6e911319d9c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20b-754f-7d0c-86b4-5ea16737c479
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20b-7555-799c-9635-4bcc5533003c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20b-755a-7bc7-b740-4eb6085dd7d3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20b-7561-7854-95de-15ee4c00ed30
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20b-7570-73ce-8b02-6fb5b23d0fae
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20b-7574-72e7-b156-ed6bb9fb97f7

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20b-8c73-7972-b9d0-ea181f3ce24a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20b-8c78-7af1-904d-af56149ca336
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20b-8c7e-7b26-8052-4b3a3d7c689a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20b-8c84-7650-9db6-dc9c185bef6b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20b-8c8a-7eaa-a698-dc3e7651ae62
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20b-8c90-70f4-93ba-9184adcef0fb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20b-8c97-71de-b312-1b333e931580
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20b-8c9e-71bc-ab57-61b50ded85d6

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20b-9742-7219-af0e-e8f21fab74de
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20b-9745-7967-ae29-58366d540630
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20b-974d-7171-8a04-4d8bb491c97c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20b-9754-7c5e-b824-7867dd3e3e33
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20b-975a-7266-afff-fedef25d8919
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20b-9760-7cb7-af3a-d86482bc3ff7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20b-9765-7eff-9246-f74d58c22bc6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20b-976b-78c5-816e-69db1774d17a

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20b-afd6-7b11-a210-a7c746a47e01
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20b-afda-7e1a-9fd6-1fda5d6c8145
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20b-afe1-799a-877d-d0bc0f289ff3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20b-afe7-7269-b12b-5d8632e06306
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20b-afec-76d8-9f2c-73f197d1f0db
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20b-aff5-7be3-b5c8-871c4156b309
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20b-affc-73cb-a4de-cbb89b0c3021
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20b-b005-726e-be77-32867cfd9c71

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20b-c522-70a0-87b2-8f739cf51405
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20b-c526-7b06-ae28-bde23589ea71
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20b-c52d-7eb5-b97d-a1d842caf493
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20b-c534-7848-af94-2e7ba5e3b88b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20b-c53a-7ec9-ac56-f951827e3970
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20b-c53f-77a6-ab87-a294ca130415
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20b-c545-7efb-b2f3-40d6e16b8bf3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20b-c54b-77f3-a33a-4277cd866dae

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20b-df7b-79fc-b553-d924ebb2d098
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20b-df7e-73e1-92b3-2e6b41015cdf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20b-df83-7496-8853-a5f3683b8a12
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20b-df8b-719c-8bf9-c883af3eb9e9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20b-df91-77c3-9ead-33623453309c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20b-df96-7c8f-b52f-3c2cdf30b649
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20b-df9b-76e8-8bd2-26271f6920dc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20b-dfa1-7a10-afe7-f448478c2762

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20b-fc5d-7cd5-bcf6-2ccc5f5bfa99
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20b-fc62-7916-b25e-ba631c590cf7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20b-fc68-7b43-8f21-b7e6de5132cd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20b-fc6f-7dab-a202-54d6e56ce34f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20b-fc75-77ee-8683-a9c245132f44
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20b-fc79-7938-9a22-b2e095e728c8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20b-fc7d-7bfa-b175-fa794b2003d7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20b-fc84-79e4-8f33-da81c7066fb9

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20c-0ff8-79a4-98fd-b9eac0632655
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20c-0ffc-7117-969c-7836b441a1af
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20c-1003-76e1-9b93-596f17bd9259
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20c-1008-7c41-85ca-734d11e21f4b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20c-100e-7169-90d0-c7a67341d7d2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20c-1014-7d47-8f6e-0889f4a42f11
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20c-101a-7283-9e11-22030f8bd299
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20c-1022-7c58-8ffe-540b0dd5aac5

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20c-299c-7da9-95f1-b033c4416eb6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20c-29a0-79f1-912e-73ffaaf71347
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20c-29a7-714e-8c34-62dfe0d768b0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20c-29ad-7a16-8c41-342fe8c7a7b8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20c-29b1-7f4f-a5b7-d1dea5503de1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20c-29b7-7efa-a0fc-68fd1bef9a00
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20c-29be-7826-8d4f-16822464c12c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20c-29c4-7ab8-abcc-f825bc7a1e08

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20c-487c-7366-afc3-b46422821369
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20c-4881-7e5e-b87e-16a9e5fc3419
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20c-4887-7d17-8760-692adb93f6af
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20c-488d-7da7-b4ae-e04d30a51ce4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20c-4893-744a-8992-31dcb3d5fb80
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20c-4898-75a3-be53-72d209729fe7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20c-489e-7cd3-bf8e-b3f9683607f8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20c-48a4-7846-913e-c3fc5cd4379f

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20c-5e8b-79c8-833a-cf687543a314
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20c-5e8f-74e4-9a8b-a4917eca304f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20c-5e96-77ae-af40-929628e60291
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20c-5e9c-7a53-a02f-99906c4860d0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20c-5ea3-728e-9b92-cb4b09273ae0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20c-5eaa-724c-8706-e42a695de4f8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20c-5eaf-7942-9144-22d4434ed604
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20c-5eb4-7999-b928-f973cc68a395

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20c-75ad-795f-a73e-ba0faf2215e7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20c-75b1-7837-9ec9-8175a529e48b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20c-75b8-7224-bc71-475d4f837655
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20c-75bc-7265-9047-9dce9c86ef50
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20c-75c2-7883-8729-d83a78df008c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20c-75c8-7e7f-a0be-01c1002b73a9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20c-75cc-70ca-88c2-4dd9bad43236
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20c-75d4-74a5-9be9-2b17a6abb291

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20c-88e2-7928-b7b6-76e7db0b0e4d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20c-88e7-7cc9-8333-734a9e45aaeb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20c-88ec-7b85-89e4-9924970d73b2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20c-88f2-7f2a-85d5-1ba9a63cca63
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20c-88f9-72e1-8588-e187030143a3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20c-8900-7fa6-8a06-c988a607d128
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20c-8905-7be1-a217-4315972ad02e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20c-890b-775b-845e-93de0b3966e4

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20c-99bf-7c83-90e1-9d32bc1b8d44
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20c-99c6-7f94-9d1b-8e8fb635f750
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20c-99ca-779b-95d4-1f1459c43db9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20c-99cf-772e-a776-f3b0c55765a9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20c-99d5-7cce-a661-66a13a13b756
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20c-99da-77fa-869e-c29c8331850a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20c-99e1-7fc6-834e-664bde76a818
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20c-99e7-75d3-b5dc-cb514b8ff886

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20c-bbd0-7f22-a80c-d20ce988349d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20c-bbd3-7579-bf41-a9c4b1dbc1ed
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20c-bbda-7bb4-adb0-dbcc8f03a328
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20c-bbdf-7861-b4a9-e98debcc2b77
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20c-bbe3-717a-a4f8-824230bc0ee5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20c-bbeb-7245-a503-1c44e8b0b401
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20c-bbf1-7823-bf31-9c1eaeeb138f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20c-bbf8-74f8-9470-16216fe3e6fc

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20c-d49c-7446-90db-3df928cbe479
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20c-d49f-72b9-82d1-561e36568c2c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20c-d4a5-72fa-832f-e73cb5d3f6e6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20c-d4ac-797a-93cc-9ac9cd68559d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20c-d4b2-7483-86c6-24b41afbb462
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20c-d4ba-7db6-bb80-0d7c33e32060
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20c-d4be-7b11-b816-e46840dc3d73
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20c-d4c5-7b5d-b4ea-1132189bb2a3

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20c-ed65-7364-b50c-3e48eedaac4b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20c-ed69-7896-897c-82a95ebf2a0c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20c-ed70-783a-8ef2-fff732f85161
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20c-ed78-7b94-8245-5e2d6bfcb8d9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20c-ed7d-7050-955b-52ef512723f0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20c-ed82-75ec-bfc7-ad968762467c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20c-ed89-74f1-85aa-1e0f3d2a2960
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20c-ed8d-7904-b53e-4627f662dc41

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20c-fff6-7e79-a05c-85292c74e08a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20c-fffa-754a-834f-05b05121dae2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-0001-74f3-ab28-c8fa2367c06b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-0006-794d-a825-9edbc1fcf5e4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-000d-7c81-9fdf-933c4a7f30ed
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-0012-74f0-8da5-47429da351eb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-0017-73a7-b21d-6ae015784c88
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-001e-756a-b0ef-09f582209463

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-1496-7f5b-9f4f-cd096d99f446
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-149a-7d1d-90d9-cea4e13b5ebd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-14a1-71df-af4e-e8935453b785
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-14a7-77ba-ac3e-927fbd104135
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-14ac-7751-bef7-2f2f748451f0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-14b0-775f-bf94-68e3e9e88593
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-14b6-7bc0-8ece-9f25cee4cc73
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-14ba-731c-b062-646e59ef5c1c

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-2c6b-77cf-b5e0-3695e9f1af2b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-2c6e-7fdb-acc5-61c57ff6c6a0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-2c75-76a4-bc0c-9ac214c38dbd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-2c7a-7531-bdfc-fd599e8c2fe2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-2c80-7514-9fa7-54c0972e8c62
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-2c85-79ee-ab25-ad0aa47ffb95
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-2c8b-7c71-880a-439237ad285a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-2c91-7dd2-8796-ffc7f2351948

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-48b0-7427-9149-9266adccb5a9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-48b6-7b6c-915d-636de366b529
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-48ba-7593-8251-82d151dd7538
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-48bf-7056-bfe8-deb31f4c1389
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-48c7-7619-ac86-9f774c945db4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-48cc-7172-8037-6f7dc6f65509
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-48d2-709c-8b60-429bb1c4c730
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-48d8-7210-bcf4-b4ff27ddc49e

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-69fa-766f-8d35-6a3dbfb5d7e5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-69ff-701e-8a4b-178de2c7cd7c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-6a04-71d8-94d4-ff6c91add118
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-6a09-7e28-8ed9-8a13c0237cff
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-6a10-76b1-8cd6-10e12715940b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-6a16-72a8-82e5-3ef45422bc31
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-6a1b-7c9f-8453-da984921d015
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-6a22-77e1-9896-5452395f05cb

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-7754-7832-acb8-9d432a4eac04
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-7758-7b43-bc00-dc36688949d8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-775f-7476-af90-b143bbedb462
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-7764-7630-92ec-4dfacf5f8df5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-776b-7fa0-af5f-abf3e1698410
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-7770-7fc1-8553-285c2e307ac8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-7776-7b7e-bcf0-b1d283bdd0fb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-777b-7488-b2dc-707e211d30db

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-8f34-730e-ad87-8944b854defd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-8f3b-7700-b8fa-c101cb49d1f1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-8f40-7720-bf5b-ff5bff7203c5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-8f46-79c3-b70d-b918691743e3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-8f4b-75ed-8f2f-03a009d4e91e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-8f51-7535-9d2a-290dc662ae19
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-8f57-790b-be01-5a07de716be2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-8f5e-7038-946f-59f3f1c4cc11

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-9e9c-743e-bed4-0c5d21078560
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-9ea2-7a1d-b5c9-c01881df75a2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-9ea7-7ae5-be31-9fcc51aab6cd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-9eab-77df-970a-7f2c77c0acf4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-9eb2-7e3d-be89-90db50ea1e03
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-9eb8-7178-902a-40c1aefed93b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-9ebd-749b-a2d6-d83b2bff7b6b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-9ec4-7e5e-bbc8-24529fb2e62f

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-b01b-7fa1-b0b3-6946bdb74ac6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-b01e-7de6-9bc2-fcb862c8df05
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-b024-796a-9eb5-7335abd0b378
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-b02b-7474-8f0a-9645ca73bfbd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-b031-76ec-8499-b929432917b1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-b037-7b39-86b1-8604a0e39db0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-b03b-71d1-ba2b-fec9d8dcdf9a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-b042-7946-9f16-8cfaaefe2de5

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-c5f9-7f20-b1ed-e0de08571bad
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-c5fc-7a55-9f5d-484da3c8b51e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-c603-79a7-b298-d5f341899ddb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-c609-76c2-8d55-7452dece40fb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-c60e-7fc8-8cf7-af8b8eb49cf6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-c617-702a-8d13-b12612c4e876
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-c61c-7fd8-8e9f-ed7e65ac91b4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-c624-7dfe-a81a-de808c67a4cf

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-dd33-72e7-9397-d6a14f9c6afa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-dd37-7356-8364-dd71051a1a44
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-dd3e-7df8-bbd3-9958505011c9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-dd44-7bd4-a70e-402f8aab9472
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-dd4a-7b78-875f-630ac2d6c587
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-dd4f-7415-ad06-cc0643d380c4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-dd53-7c2f-9dc5-0af09a3871be
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-dd59-7a24-a83f-f4583d06985e

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-ee69-75a7-8744-eb3873c04bf7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-ee6c-7e92-8f17-f1414438f076
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-ee73-724a-b0b1-c8d8840696e6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-ee79-7e26-a563-be7e7f7708f0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-ee7f-7ecf-920b-1a95657730dc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-ee84-7f41-b5a7-d7288d61333e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-ee8a-7c77-9327-61f346d5e005
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-ee90-7129-980e-dda6ec6f18b7

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-f72c-7f17-9136-85de43e6fa73
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-f731-74fe-a2c1-6ad7099aa1c7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-f737-7038-a19c-4c2bfbce3343
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-f73e-7840-b402-a51464ba4dfd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-f744-7fa7-bc00-98ef8ff13846
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-f74a-7c1e-8d72-3db336903e02
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-f750-7b35-8ad8-8967f539b280
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20d-f756-70e6-8199-1423e2925254

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20e-0d7d-716c-85e8-b924eec2ded9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20e-0d80-79db-bd95-7550b60f73fd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20e-0d87-7954-9eb0-f3ca26d57ab4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20e-0d8e-792f-a8cc-e8669ea9551c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20e-0d94-756a-85ad-b2add296b264
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20e-0d99-7067-af31-4b4029552cc7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20e-0d9f-76be-88d2-cc9188c983f7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20e-0da5-7b4a-801c-c0a121f8267a

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20e-2207-7d57-9868-4ce5bd98ff1c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20e-220c-714c-8ac9-c36ca7780056
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20e-2212-7fa0-bc0c-bdfb5ad3f623
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20e-2217-734a-aee5-6703bab598d3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20e-221e-7c3d-9945-f4e4266d1cc1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20e-2223-7a71-8e9d-08f8ca13901e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20e-2228-7f11-b562-36c6261c98bf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20e-222f-741b-9ace-79e72ba839e1

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20e-3a60-709a-beca-81aedba73ccd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20e-3a65-71a9-b6f9-ca6f8d021d1b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20e-3a6a-78c4-b101-090a24365dfc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20e-3a70-7de3-b384-b862e10f0fe8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20e-3a76-7351-be00-e02ddb9cf59c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20e-3a7b-7fda-b3c2-ea6e918741ca
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20e-3a82-7eca-8a1e-a0d00b6020a6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20e-3a88-7610-985f-00c7dafbace8

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20e-4d0a-72c9-b8cf-c2833b93ec53
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20e-4d0f-75e4-864a-80d9b3a2f54b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20e-4d16-75a3-8e63-12f70559a9e3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20e-4d1b-757b-8bcb-6e6133029762
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20e-4d22-74f6-8812-ecb1b1c00828
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20e-4d29-70b0-973e-fce35e706fcf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20e-4d2f-72bb-ab4f-08b10470252e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20e-4d35-7754-bf04-36a5172dd4a8

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20e-5f4b-738d-9185-651b14fd1119
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20e-5f4e-770a-9044-815ce84d9b43
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20e-5f54-7f0c-9c22-f3d6a4f35e6b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20e-5f58-76b7-8d97-96bbd1ba34fc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20e-5f5e-7c94-a922-5e81cd6e245d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20e-5f64-7a09-ba45-79ef711c8116
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20e-5f69-771d-bfb8-9c50262d5194
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20e-5f6e-7abb-a02f-6057aad60a5f

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20e-796e-795f-8baa-d7b61b83fb77
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20e-7974-798d-aa77-81255f74f728
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20e-7979-7d34-8886-095b3e8883b6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20e-797f-7982-89c5-02a9a92c06c4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20e-7986-7b17-bba6-5f3808170b0a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20e-798b-788c-b895-f16989033752
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20e-7990-79d7-853a-49d0dc06d313
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20e-7996-7644-814e-814af2c422e4

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20e-916a-7db7-8191-729ff9e6cc78
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20e-916e-7746-ac94-3484d249f245
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20e-9174-78b6-8e5e-e3d7bde4bf89
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20e-917b-71d6-acbd-398f2fdcb754
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20e-9180-7272-a0c2-c825e654703e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20e-9187-766e-89c0-0f272184c1a6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20e-918c-76e7-a006-f56426666e9c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20e-919c-7206-82cc-acdd2fbf43e9

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20e-b356-7682-bc86-e8a3a292453c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20e-b35a-7e46-ac18-0612bd4f64d0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20e-b360-719f-9f76-525006876907
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20e-b365-7516-a8bc-5758973f15fa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20e-b36b-798c-a750-ce0cb8bfc94b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20e-b371-79b3-86d4-3c887670ad7e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20e-b378-7a40-a9bf-b5ce12278787
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20e-b37f-7eca-892f-49513dae748c

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20e-c575-77e0-bbe0-523a19f961d9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20e-c578-7052-868e-3bfca7dcc95d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20e-c57f-791f-9f5d-b0d3fd05c9e9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20e-c585-702c-a84c-30db16159e0e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20e-c58b-72f0-bf17-5d4c99f3e86a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20e-c591-7c77-9ae3-48f5ffe5dac9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20e-c597-748b-ac51-c100dd06a97e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20e-c59d-7a76-8400-a53c11e96b8e

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20e-e41b-72fb-a2af-237cd83a8e78
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20e-e424-7197-b074-c4d8bd42a851
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20e-e42a-7ac7-be89-4d7382fd157f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20e-e431-7912-8661-a32810c4384f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20e-e438-764b-8494-26c6d563db90
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20e-e43d-76e8-b0bb-fa63144aa281
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20e-e444-73c6-870f-29dfe0b46ade
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20e-e44b-7c51-8bc8-845e3cc3e2e5

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20e-fd0f-7c21-b394-b8e0800601d2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20e-fd13-7542-98cb-d306f3dca5bf
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20e-fd18-7404-8668-d0f583ec5c74
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20e-fd1f-7f56-a4f7-ac4a41d1e92b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20e-fd26-7611-ba06-64867fdfb13a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20e-fd2c-7d11-b860-9a53d0443754
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20e-fd31-71ea-8051-d6f0eabfa7a9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20e-fd37-7ea9-a06f-0e48b2aee27f

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20f-2107-7071-9674-edc4dd1c9a84
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20f-210a-74c5-9ec9-e5efef900d3d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20f-2110-7b95-8bc3-3f16570a83b4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20f-2116-701e-b236-09eeec2b0926
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20f-211d-75d1-81eb-4d597f528c40
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20f-2122-7c27-846d-5b02b0981186
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20f-2127-73ac-a315-6f72bf25d56f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20f-212c-7ccd-bb17-cfc4103047f4

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20f-3843-710c-af0a-d746088e322d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20f-3849-7e5b-a312-ca240051a282
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20f-3850-74b5-99b7-ec9bfa358469
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20f-3856-792c-a8e0-6adae2e3e4d2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20f-385a-75f9-a454-f701b9591bd2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20f-385f-79bf-8aad-cfb377ba1ce0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20f-3866-7ab1-96a9-3d6af729b0e1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20f-386b-7b89-a5f8-72aeab74cbb1

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20f-4b83-71c5-82e2-d8953a44d10c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20f-4b89-70a2-b9da-93e760bf9e9f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20f-4b8f-725e-851b-ca62f7db4e6e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20f-4b95-7c25-a09c-34af90032e3e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20f-4b9b-7150-b004-f5f921476c64
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20f-4ba1-7ac9-a187-a1d20ffb3d15
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20f-4ba8-7384-9e03-464c2a65145f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20f-4bae-7a5d-8d3f-e2b99fa01e9e

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20f-62e7-784e-9d87-97798f667d1c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20f-62ec-7115-bf91-6707287450e7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20f-62f1-755f-9f4e-3d83f3615838
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20f-62f8-7715-bc4e-a2ee768103cb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20f-62ff-7a74-a34b-7bd75a5f6127
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20f-6304-7164-b1bb-3d6d8dfd3759
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20f-630a-711f-ba2f-eade1dd8aaa4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20f-6310-7d2f-938b-ee96d34ebf7d

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20f-77b1-7fff-b3a1-94e09a9bd7f7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20f-77b5-7831-9215-11f46c32bb7c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20f-77bb-7201-95cb-56b3994e808e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20f-77c1-748e-a54b-a86580cd94d7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20f-77c7-7443-ae53-30737f56349a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20f-77cd-7ad5-b72f-dd3f6b9ff664
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20f-77d3-76a5-a3dd-a973c90a6556
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20f-77d9-7a7e-878d-9ef2fff37792

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20f-999e-7d07-9bfa-b3e07fcdae36
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20f-99a2-78bf-aaa5-5a3916afd3aa
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20f-99a8-7b49-a954-5d7febc4326a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20f-99ad-7c95-960b-d2198f3ca8e6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20f-99b3-73f2-aaf5-29c096349704
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20f-99b9-7190-91d9-6c724a20c484
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20f-99c0-7c69-b346-129a645b4f31
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20f-99c6-75bf-918b-01d56b79c115

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20f-ad8a-76f8-9ee2-bb10e2ff253e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20f-ad91-775c-9d22-67cf6696b0ad
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20f-ad9b-75e6-9e10-a965aee9667a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20f-ada3-72fa-a489-3c9f6c1fba0c
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20f-adaa-78c4-ae60-242dc7199c1e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20f-adb0-70de-995e-e7bde32bafda
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20f-adb8-77f4-be1b-077d4dc6ed32
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20f-adbf-7731-bcaa-eea83b566a9f

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20f-c629-787a-ba68-5d9b13a7c9a4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20f-c62d-7579-9d1b-b589f752324e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20f-c635-7e0f-960c-28b8e2e05ba2
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20f-c63b-79a8-8de8-f33307c19e73
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20f-c641-7370-9a27-39a823728110
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20f-c647-7cde-bac5-ce7909c35f3e
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20f-c64c-7f42-a6be-8eaf4bcee62b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20f-c652-7b00-b949-6c6ee61c92fe

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20f-d855-7921-a90d-8b90e6e75b07
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20f-d859-7aaf-a3e8-b9ff1b62b6b0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20f-d860-78d6-be9d-fece65787673
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20f-d866-72d0-ad7f-86bfddc2b101
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20f-d86b-7cbb-be94-6a54c2ca0031
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20f-d870-790e-8bcc-144eba0fe5c8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20f-d876-7a23-87e8-5fc386c55ac1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20f-d87d-775f-961a-84a2d707a554

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20f-f466-78f9-9d15-61d3c349e138
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20f-f46a-78dc-a98c-80b4e735ecd4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20f-f471-7be9-a68f-4b0d0c5c111a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20f-f476-7ac4-a02d-86f5f199f068
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20f-f47d-7d78-a959-00a791fb0ade
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20f-f483-74d2-8249-50cf6829bdd6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20f-f489-7fc2-835c-b40ba01ce0f5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f20f-f492-765c-8dbc-1b29b8c8eb1f

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f210-1221-70ef-bdb2-bcd1f70ef84f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f210-1224-78ba-8746-0603b5c91170
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f210-122a-7252-8a44-253a25e78d77
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f210-1230-7922-b136-aab066aaf615
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f210-1236-7aab-8f32-bc0b2db17f7a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f210-123c-7065-9ece-d8535a2b8ed3
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f210-1243-77df-9686-e4ec19209fa0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f210-1248-7018-b3d6-dba58f8ba636

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f210-3821-7f46-a954-5b05a91ea4c6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f210-3824-7481-8e96-c66ea5c42d2f
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f210-382b-7c58-877c-85fd6d90c3b7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f210-3832-7601-a695-a148897cdfa6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f210-3836-7cde-8f2e-d060daff0a85
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f210-383d-764a-915f-233a40b65b84
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f210-3843-7e1d-a3bd-756c8167761a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f210-3849-7550-ae14-2aa7e497b5ae

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f210-401a-7ca5-ac24-73b6796244bb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f210-401e-7eaf-ab46-bbb1cd6f6a4b
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f210-4026-7eb4-937f-74d86f3b9b59
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f210-402a-7ee4-a8c8-ab2f4c9fced4
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f210-4031-7828-b5bc-9481869abec0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f210-4036-7d76-bd82-a89d75e8e725
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f210-403d-7eaf-8212-8719cf3de80d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f210-4044-7aa1-a720-e5d022dcea85

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f210-5505-7319-a4ca-48b171f7de61
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f210-550a-7583-97b9-d023e8178463
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f210-5511-746d-9ff9-9a604ac9c0b0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f210-5516-755e-a46e-2cb1f9d07bcd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f210-551b-7c5f-968f-ef7b2f713153
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f210-5522-7dd6-8ade-1125d83911f7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f210-5529-7a2e-b667-c17bad68d096
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f210-552f-726a-b3b8-46912cd89ee7

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f210-68d2-7fbc-92b3-f6c996d57ffc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f210-68d7-79d3-9188-e23d4a74de52
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f210-68dc-791f-9fd8-ce9a46a7e9ef
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f210-68e1-704a-b5a1-2e51053d9c83
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f210-68e8-7246-a916-51f13bedaf23
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f210-68ee-7fa2-9d0e-fb9b972fa60a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f210-68f4-7e64-95e8-48f4989bb8b9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f210-68fa-7a59-b73c-7dba47b1623f

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f210-7f03-7735-98bb-6c7454f127db
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f210-7f06-7452-b4f2-c8014ac240e5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f210-7f0e-7bbc-92ab-93c855b400b1
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f210-7f13-7b97-81ba-0b7b6cb41cfd
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f210-7f19-7daf-80e0-1df49cb166c9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f210-7f1f-75e7-8a59-f2ee333c47b8
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f210-7f26-751b-b70d-23844bd0473d
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f210-7f2b-7a8f-9642-0f1ef480a7af

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f210-90f0-773d-a3ac-e28198af91c9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f210-90f3-7bf9-829a-5decdb027025
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f210-90fb-719b-9f6d-ec5d1be5b9c5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f210-9102-7bb6-a8c9-d26df4e8b0fb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f210-9106-7de1-a699-2fbc732e2fc9
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f210-910d-759a-ba2a-500796560fc5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f210-9114-7d7c-a6a2-4fbe1c1788e7
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f210-911a-7aea-b00f-b1d67704e01a

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f210-ab36-763d-a8e0-10ecddf84a09
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f210-ab3b-79c3-8ad7-7d280bb0b9a6
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f210-ab41-798f-af13-a067ebcd66f0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f210-ab45-7b8f-a3a1-84e31dcdd471
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f210-ab4a-74ce-8be4-ba077cb93eb0
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f210-ab4f-7d05-9e53-46d9bfddd1dc
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f210-ab56-7124-ba6a-1b5e6ead9745
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f210-ab5c-7ce6-826f-c0ceb08c29e4

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f210-bd00-76f3-8022-bab6d409ac07
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f210-bd04-7be7-a950-8d4b51581a3a
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f210-bd0a-7bf1-b98a-3741cf26b448
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f210-bd0f-7301-8476-61820646c848
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f210-bd16-752c-93e4-49e7b9fed2eb
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f210-bd1c-7ff6-bd88-aa46521d0427
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f210-bd22-7028-b547-7e44033f23a5
weave: 🍩 https://wandb.ai/alex-esau98/mllm/r/call/01a0f210-bd27-7684-975e-cf73e811c147

BEFORE BERT sync
BEFORE BERT sync OK
AFTER BERT call
AFTER BERT sync OK

In [10]:
#GRID
#3.5-4B JUDGE   10:47:56

#Patches
#3-5-9B JUDGE   ca. 40h

trainer = GRPOTrainer(
    model=hf_model,
    args=training_args,
    train_dataset=train_dataset,
    reward_funcs=reward_func,
    processing_class=processor,
)

trainer.train()

wandb.finish()
weave.finish()

NameError: name 'training_args' is not defined

In [15]:
wandb.finish()
weave.finish()

Error in callback <bound method _WandbInit._pre_run_cell_hook of <wandb.sdk.wandb_init._WandbInit object at 0x7f152ae746e0>> (for pre_run_cell), with arguments args (<ExecutionInfo object at 7f14445199c0, raw_cell="wandb.finish()
weave.finish()" transformed_cell="wandb.finish()
weave.finish()
" store_history=True silent=False shell_futures=True cell_id=vscode-notebook-cell://wsl%2Bubuntu/home/alesau/mllm/mllm/train_model.ipynb#X44sdnNjb2RlLXJlbW90ZQ%3D%3D>,),kwargs {}:

ConnectionResetError: Connection lost

ConnectionResetError: Connection lost

Error in callback <bound method _WandbInit._post_run_cell_hook of <wandb.sdk.wandb_init._WandbInit object at 0x7f152ae746e0>> (for post_run_cell), with arguments args (<ExecutionResult object at 7f1444519a70, execution_count=15 error_before_exec=None error_in_exec=Connection lost info=<ExecutionInfo object at 7f14445199c0, raw_cell="wandb.finish()
weave.finish()" transformed_cell="wandb.finish()
weave.finish()
" store_history=True silent=False shell_futures=True cell_id=vscode-notebook-cell://wsl%2Bubuntu/home/alesau/mllm/mllm/train_model.ipynb#X44sdnNjb2RlLXJlbW90ZQ%3D%3D> result=None>,),kwargs {}:

ConnectionResetError: Connection lost

In [19]:
print("Judge devices:", {p.device for p in judge_model.model.parameters()})
print("RL devices:", {p.device for p in hf_model.parameters()})

print(
    "allocated:",
    torch.cuda.memory_allocated() / 1024**3,
    "GB"
)

print(
    "reserved:",
    torch.cuda.memory_reserved() / 1024**3,
    "GB"
)

Error in callback <bound method _WandbInit._pre_run_cell_hook of <wandb.sdk.wandb_init._WandbInit object at 0x7f39000b86e0>> (for pre_run_cell), with arguments args (<ExecutionInfo object at 7f380cfc1ed0, raw_cell="print("Judge devices:", {p.device for p in judge_m.." transformed_cell="print("Judge devices:", {p.device for p in judge_m.." store_history=True silent=False shell_futures=True cell_id=vscode-notebook-cell://wsl%2Bubuntu/home/alesau/mllm/mllm/train_model.ipynb#X61sdnNjb2RlLXJlbW90ZQ%3D%3D>,),kwargs {}:

ConnectionResetError: Connection lost

Judge devices: {device(type='cuda', index=0)}
RL devices: {device(type='cuda', index=0)}
allocated: 13.657028198242188 GB
reserved: 14.025390625 GB
Error in callback <bound method _WandbInit._post_run_cell_hook of <wandb.sdk.wandb_init._WandbInit object at 0x7f39000b86e0>> (for post_run_cell), with arguments args (<ExecutionResult object at 7f380cfc2750, execution_count=19 error_before_exec=None error_in_exec=None info=<ExecutionInfo object at 7f380cfc1ed0, raw_cell="print("Judge devices:", {p.device for p in judge_m.." transformed_cell="print("Judge devices:", {p.device for p in judge_m.." store_history=True silent=False shell_futures=True cell_id=vscode-notebook-cell://wsl%2Bubuntu/home/alesau/mllm/mllm/train_model.ipynb#X61sdnNjb2RlLXJlbW90ZQ%3D%3D> result=None>,),kwargs {}:

ConnectionResetError: Connection lost

# Rest

In [26]:
dataset = train_dataset[12]
img_rl = build_grid_image(dataset["grids"], dataset["rl_order"], **img_kwargs)
img_judge = build_grid_image(dataset["grids"], dataset["judge_order"], **img_kwargs)
display(img_rl)
print("RL Order:", dataset["rl_order"])
display(img_judge)
print("Judge Order:", dataset["judge_order"])
print("OG Description:", dataset["og_description"])

KeyError: 'grids'

In [ ]:
#!pip install bert_score

scorer = BERTScorer(lang="en", rescale_with_baseline=True)

Loading weights:   0%|          | 0/389 [00:00<?, ?it/s]

[transformers] RobertaModel LOAD REPORT from: roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.dense.bias        | UNEXPECTED |
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
pooler.dense.weight       | MISSING    |
pooler.dense.bias         | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [ ]:


dataset_train.iloc[0].conversation[0][1]

for i in range(130, 140):
    utterances = dataset_train.iloc[i].conversation
    conversation = ""
    for utt in utterances:
        if conversation == "":
            conversation += f"{utt[1]}"
        else:
            conversation += f", {utt[1]}"
    conversation = re.sub(r"[^A-Za-zÄÖÜäöüß,\s]", "", conversation)
    print(conversation)
    #print("Target: ", dataset_train.iloc[i].target)

yellow
orange
blue
purple
Target is the orange square
purple
tan olive
green
gray
green

In [ ]:
scorer_raw = BERTScorer(lang="en", rescale_with_baseline=False)

Loading weights:   0%|          | 0/389 [00:00<?, ?it/s]

[transformers] RobertaModel LOAD REPORT from: roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.dense.bias        | UNEXPECTED |
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
pooler.dense.weight       | MISSING    |
pooler.dense.bias         | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [ ]:
P, R, F1 = scorer.score(
    ["red", "red", "red", "red", "red", "red", "red", "red"],
    ["The red one", "pink", "red", "blue", "green", "red red", "red red red", "the horse rider falls on his back"],
)

print(F1)
print(P)
print(R)
#print()

#P, R, F1 = scorer_raw.score(
#    ["red", "red", "red", "red", "red", "red", "red"],
#    ["The red one", "pink", "red", "blue", "green", "red red", "red red red"],
#)

#print(F1)
#print(F1_new)
#F1[0].item()

tensor([0.2657, 0.4357, 1.0000, 0.6542, 0.5561, 0.7249, 0.5524, 0.0383])
tensor([0.3139, 0.4975, 1.0000, 0.6536, 0.5553, 0.7738, 0.7098, 0.2696])
tensor([ 0.2160,  0.3734,  1.0000,  0.6536,  0.5554,  0.6759,  0.4022, -0.1761])

In [ ]:
!pip install sentence_transformers


model = SentenceTransformer("all-mpnet-base-v2")

cands = ["red"] * 7
refs = ["The red one", "pink", "red", "blue", "green", "red red", "red red red"]

emb_c = model.encode(cands, convert_to_tensor=True)
emb_r = model.encode(refs, convert_to_tensor=True)

scores = util.cos_sim(emb_c, emb_r).diagonal()
print(scores)

Requirement already satisfied: sentence_transformers in /home/alesau/miniconda3/envs/mllm/lib/python3.14/site-packages (5.6.0)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /home/alesau/miniconda3/envs/mllm/lib/python3.14/site-packages (from sentence_transformers) (5.13.1)
Requirement already satisfied: huggingface-hub>=0.23.0 in /home/alesau/miniconda3/envs/mllm/lib/python3.14/site-packages (from sentence_transformers) (1.7.2)
Requirement already satisfied: torch>=1.11.0 in /home/alesau/miniconda3/envs/mllm/lib/python3.14/site-packages (from sentence_transformers) (2.11.0)
Requirement already satisfied: numpy>=1.20.0 in /home/alesau/miniconda3/envs/mllm/lib/python3.14/site-packages (from sentence_transformers) (2.5.1)
Requirement already satisfied: scikit-learn>=0.22.0 in /home/alesau/miniconda3/envs/mllm/lib/python3.14/site-packages (from sentence_transformers) (1.9.0)
Requirement already satisfied: scipy>=1.0.0 in /home/alesau/miniconda3/envs/mllm/lib/python3.14/site-packages (from sentence_transformers) (1.18.0)
Requirement already satisfied: typing_extensions>=4.5.0 in /home/alesau/miniconda3/envs/mllm/lib/python3.14/site-packages (from sentence_transformers) (4.16.0)
Requirement already satisfied: tqdm>=4.0.0 in /home/alesau/miniconda3/envs/mllm/lib/python3.14/site-packages (from sentence_transformers) (4.67.3)
Requirement already satisfied: packaging>=20.0 in /home/alesau/miniconda3/envs/mllm/lib/python3.14/site-packages (from transformers<6.0.0,>=4.41.0->sentence_transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /home/alesau/miniconda3/envs/mllm/lib/python3.14/site-packages (from transformers<6.0.0,>=4.41.0->sentence_transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in /home/alesau/miniconda3/envs/mllm/lib/python3.14/site-packages (from transformers<6.0.0,>=4.41.0->sentence_transformers) (2026.2.28)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /home/alesau/miniconda3/envs/mllm/lib/python3.14/site-packages (from transformers<6.0.0,>=4.41.0->sentence_transformers) (0.22.2)
Requirement already satisfied: typer in /home/alesau/miniconda3/envs/mllm/lib/python3.14/site-packages (from transformers<6.0.0,>=4.41.0->sentence_transformers) (0.24.1)
Requirement already satisfied: safetensors>=0.8.0 in /home/alesau/miniconda3/envs/mllm/lib/python3.14/site-packages (from transformers<6.0.0,>=4.41.0->sentence_transformers) (0.8.0)
Requirement already satisfied: filelock>=3.10.0 in /home/alesau/miniconda3/envs/mllm/lib/python3.14/site-packages (from huggingface-hub>=0.23.0->sentence_transformers) (3.25.2)
Requirement already satisfied: fsspec>=2023.5.0 in /home/alesau/miniconda3/envs/mllm/lib/python3.14/site-packages (from huggingface-hub>=0.23.0->sentence_transformers) (2026.2.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in /home/alesau/miniconda3/envs/mllm/lib/python3.14/site-packages (from huggingface-hub>=0.23.0->sentence_transformers) (1.4.2)
Requirement already satisfied: httpx<1,>=0.23.0 in /home/alesau/miniconda3/envs/mllm/lib/python3.14/site-packages (from huggingface-hub>=0.23.0->sentence_transformers) (0.28.1)
Requirement already satisfied: anyio in /home/alesau/miniconda3/envs/mllm/lib/python3.14/site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence_transformers) (4.13.0)
Requirement already satisfied: certifi in /home/alesau/miniconda3/envs/mllm/lib/python3.14/site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence_transformers) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /home/alesau/miniconda3/envs/mllm/lib/python3.14/site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence_transformers) (1.0.9)
Requirement already satisfied: idna in /home/alesau/miniconda3/envs/mllm/lib/python3.14/site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence_transformers) (3.11)
Requirement already satisfied: h11>=0.16 in /home/alesau/miniconda3/envs/mllm/lib/python3.14/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence_transformers) (0.16.0)
Requirement already satisfied: joblib>=1.4.0 in /home/alesau/miniconda3/envs/mllm/lib/python3.14/site-packages (from scikit-learn>=0.22.0->sentence_transformers) (1.5.3)
Requirement already satisfied: narwhals>=2.0.1 in /home/alesau/miniconda3/envs/mllm/lib/python3.14/site-packages (from scikit-learn>=0.22.0->sentence_transformers) (2.22.1)
Requirement already satisfied: threadpoolctl>=3.5.0 in /home/alesau/miniconda3/envs/mllm/lib/python3.14/site-packages (from scikit-learn>=0.22.0->sentence_transformers) (3.6.0)
Requirement already satisfied: setuptools<82 in /home/alesau/miniconda3/envs/mllm/lib/python3.14/site-packages (from torch>=1.11.0->sentence_transformers) (80.10.2)
Requirement already satisfied: sympy>=1.13.3 in /home/alesau/miniconda3/envs/mllm/lib/python3.14/site-packages (from torch>=1.11.0->sentence_transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /home/alesau/miniconda3/envs/mllm/lib/python3.14/site-packages (from torch>=1.11.0->sentence_transformers) (3.6.1)
Requirement already satisfied: jinja2 in /home/alesau/miniconda3/envs/mllm/lib/python3.14/site-packages (from torch>=1.11.0->sentence_transformers) (3.1.6)
Requirement already satisfied: cuda-toolkit==13.0.2 in /home/alesau/miniconda3/envs/mllm/lib/python3.14/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.11.0->sentence_transformers) (13.0.2)
Requirement already satisfied: cuda-bindings<14,>=13.0.3 in /home/alesau/miniconda3/envs/mllm/lib/python3.14/site-packages (from torch>=1.11.0->sentence_transformers) (13.3.1)
Requirement already satisfied: nvidia-cudnn-cu13==9.19.0.56 in /home/alesau/miniconda3/envs/mllm/lib/python3.14/site-packages (from torch>=1.11.0->sentence_transformers) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu13==0.8.0 in /home/alesau/miniconda3/envs/mllm/lib/python3.14/site-packages (from torch>=1.11.0->sentence_transformers) (0.8.0)
Requirement already satisfied: nvidia-nccl-cu13==2.28.9 in /home/alesau/miniconda3/envs/mllm/lib/python3.14/site-packages (from torch>=1.11.0->sentence_transformers) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu13==3.4.5 in /home/alesau/miniconda3/envs/mllm/lib/python3.14/site-packages (from torch>=1.11.0->sentence_transformers) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /home/alesau/miniconda3/envs/mllm/lib/python3.14/site-packages (from torch>=1.11.0->sentence_transformers) (3.6.0)
Requirement already satisfied: nvidia-cublas==13.1.0.3.* in /home/alesau/miniconda3/envs/mllm/lib/python3.14/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.11.0->sentence_transformers) (13.1.0.3)
Requirement already satisfied: nvidia-cuda-runtime==13.0.96.* in /home/alesau/miniconda3/envs/mllm/lib/python3.14/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.11.0->sentence_transformers) (13.0.96)
Requirement already satisfied: nvidia-cufft==12.0.0.61.* in /home/alesau/miniconda3/envs/mllm/lib/python3.14/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.11.0->sentence_transformers) (12.0.0.61)
Requirement already satisfied: nvidia-cufile==1.15.1.6.* in /home/alesau/miniconda3/envs/mllm/lib/python3.14/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.11.0->sentence_transformers) (1.15.1.6)
Requirement already satisfied: nvidia-cuda-cupti==13.0.85.* in /home/alesau/miniconda3/envs/mllm/lib/python3.14/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.11.0->sentence_transformers) (13.0.85)
Requirement already satisfied: nvidia-curand==10.4.0.35.* in /home/alesau/miniconda3/envs/mllm/lib/python3.14/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.11.0->sentence_transformers) (10.4.0.35)
Requirement already satisfied: nvidia-cusolver==12.0.4.66.* in /home/alesau/miniconda3/envs/mllm/lib/python3.14/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.11.0->sentence_transformers) (12.0.4.66)
Requirement already satisfied: nvidia-cusparse==12.6.3.3.* in /home/alesau/miniconda3/envs/mllm/lib/python3.14/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.11.0->sentence_transformers) (12.6.3.3)
Requirement already satisfied: nvidia-nvjitlink==13.0.88.* in /home/alesau/miniconda3/envs/mllm/lib/python3.14/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.11.0->sentence_transformers) (13.0.88)
Requirement already satisfied: nvidia-cuda-nvrtc==13.0.88.* in /home/alesau/miniconda3/envs/mllm/lib/python3.14/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.11.0->sentence_transformers) (13.0.88)
Requirement already satisfied: nvidia-nvtx==13.0.85.* in /home/alesau/miniconda3/envs/mllm/lib/python3.14/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.11.0->sentence_transformers) (13.0.85)
Requirement already satisfied: cuda-pathfinder>=1.4.2 in /home/alesau/miniconda3/envs/mllm/lib/python3.14/site-packages (from cuda-bindings<14,>=13.0.3->torch>=1.11.0->sentence_transformers) (1.4.4)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /home/alesau/miniconda3/envs/mllm/lib/python3.14/site-packages (from sympy>=1.13.3->torch>=1.11.0->sentence_transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /home/alesau/miniconda3/envs/mllm/lib/python3.14/site-packages (from jinja2->torch>=1.11.0->sentence_transformers) (3.0.3)
Requirement already satisfied: click>=8.2.1 in /home/alesau/miniconda3/envs/mllm/lib/python3.14/site-packages (from typer->transformers<6.0.0,>=4.41.0->sentence_transformers) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /home/alesau/miniconda3/envs/mllm/lib/python3.14/site-packages (from typer->transformers<6.0.0,>=4.41.0->sentence_transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /home/alesau/miniconda3/envs/mllm/lib/python3.14/site-packages (from typer->transformers<6.0.0,>=4.41.0->sentence_transformers) (14.3.3)
Requirement already satisfied: annotated-doc>=0.0.2 in /home/alesau/miniconda3/envs/mllm/lib/python3.14/site-packages (from typer->transformers<6.0.0,>=4.41.0->sentence_transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /home/alesau/miniconda3/envs/mllm/lib/python3.14/site-packages (from rich>=12.3.0->typer->transformers<6.0.0,>=4.41.0->sentence_transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /home/alesau/miniconda3/envs/mllm/lib/python3.14/site-packages (from rich>=12.3.0->typer->transformers<6.0.0,>=4.41.0->sentence_transformers) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /home/alesau/miniconda3/envs/mllm/lib/python3.14/site-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->transformers<6.0.0,>=4.41.0->sentence_transformers) (0.1.2)

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

tensor([0.5746, 0.7402, 1.0000, 0.7394, 0.7460, 0.7848, 0.7123],
       device='cuda:0')

-uni VPN einrichten
-qwen evaluation (vs. Claude vs. Gemini vs. gemma4)